### ISSUE TITLE
Feature Request: Support Magic characters for VIM Powerline

### ISSUE THREAD

**Issue by rekendahl** [blinksh/blink#1]
Powerline (and a lot of ZSH like ohmyzsh) uses magic characters for enhanced command line effects. To support that the fonts used need to be updated. You can find open-source updated fonts here: https://github.com/powerline/fonts with (it seems) permissive licenses. I vote for source-code pro which is my favorite font (from adobe).

Here is what my environment looks like with magic characters:

![screen shot 2016-03-31 at 2 43 43 pm](https://cloud.githubusercontent.com/assets/1612072/14187217/f491ed44-f74f-11e5-9c61-5b065f7d829e.png)

And here is what it looks like with BLINK:

![img_0023](https://cloud.githubusercontent.com/assets/1612072/14187280/471b3e80-f750-11e5-8591-8f3b8b1fc8f6.PNG)

/Robert

**Comment by carloscabanero** [comment]
We will make sure to release with a few of these fonts.

For the fonts that we do not ship, we will provide a way to upload yours. I think having custom fonts is key in any terminal.

**Comment by rekendahl** [comment]
Works

**Comment by carloscabanero** [comment]
Did you notice that we have also removed the bar at the bottom? None of the other terminals have so much real space!! 

Closing this ;)
