### ISSUE TITLE
ALT+E, C doesn't work

### ISSUE THREAD

**Issue by rekendahl** [blinksh/blink#10]
I have mapped tux create new window to <alt> + e followed by 'C'. This doesn't work in blink even though alt+hjkl and alt+n/p works. 

The difference is that this command is two key board presses (not sure that should matter): ALT+e followed by C.

Strange.

.Robert

**Comment by carloscabanero** [comment]
I have observed the same problem with Ctrl+Q and Ctrl+_ for undo. We will review the mappings in this version.

**Comment by carloscabanero** [comment]
Also, Cmd+C, Cmd+X, Cmd+[Any key reserved by Apple] don't work. I can probably fix the normal operations, but Cmd+Space or Ctrl+Space will be more difficult.

**Comment by rekendahl** [comment]
Interesting. To a large extent users can remap vim/EMACS/tmux/screen etc so fix what you can and list what's not possible. I can easily remap around it (but the less the better)

Robert

**Comment by carloscabanero** [comment]
We have now Cmd+Apple reserved key working, couldn't do anything about space but good enough.

Still working on Alt keys

**Comment by carloscabanero** [comment]
Fixed too. This was an interesting one, it only happened with Option+e because it is a special command in iOS and OSX to add an accent. I couldn't make iOS disable this event, but I could override the character and just remove the accents, which is similar to what iTerm seems to do.
