### ISSUE TITLE
Config corrupts keyboard

### ISSUE THREAD

**Issue by lukebrowell** [blinksh/blink#100]
Device: iPhone 6
iOS: 9.3.4
Orientation: both
Steps to reproduce:
1. Open App
2. Type 'config' and enter
3. Tap 'done' on config screen.

Expected outcome:
It should return the user to the Blink prompt, with the software keyboard so that other commands can be typed.

Actual outcome:
It returns the user to the Blink prompt without the software keyboard. Double tapping on the prompt itself invokes the keyboard but it appears with corrupted display of all non-alpha keys being completely black, making it difficult to use without App restart.

**Comment by carloscabanero** [comment]
Is #34 what you are seeing?

**Comment by carloscabanero** [comment]
A hot fix is to just rotate, doesn't require to restart the app. Will see if I can present the popup in a way that doesn't trigger this on iOS.

**Comment by yury** [comment]
I think we can close this.
