### ISSUE TITLE
Support use option as meta key like macOS terminal

### ISSUE THREAD

**Issue by wendajiang** [blinksh/blink#1001]
This feature is supported in the future?

**Comment by yury** [comment]
@wendajiang I think, you want set option as esc modifier.

**Comment by jakub-stastny** [comment]
So this is pretty relevant to Emacs users. By default I had to press `Alt-[ x` to get to the `M-x` prompt, which really was annoying.

I went with @yury's advice:

In Keyboard -> Option:
- Press send: Esc
- As modifier: Esc

This did the trick, so now `Alt-x` works as `M-x`. Brilliant!

**Comment by carloscabanero** [comment]
I am an Emacs user myself, and this was a Must from the beginning. :)

But you can also map "Meta" or "Esc" to something else, like Caps and then Cmd as Ctrl. This is my go to.

**Comment by yury** [comment]
@jakub-stastny Press send: Esc is a little bit wrong. It should be None, otherwise it will send "ESC" when you press and release "Option"

So Just "as modifier": Esc will work for you fine.
