### ISSUE TITLE
Internal ed Text Editor issues

### ISSUE THREAD

**Issue by bjoernwibben** [blinksh/blink#1002]
When using the internal ed Editor and you are in Insert Mode there is no way to insert tabs via tab key (Soft- and Hardware Keyboard tested). 

Additionally using the external command clear via !clear and listing the file again with ,n the output is messed up  (see Screenshots - first before clear, second after).

![ed1](https://user-images.githubusercontent.com/376722/80280125-6c9af380-8702-11ea-87e0-ffe10f564ef8.jpg)
![ed2](https://user-images.githubusercontent.com/376722/80280128-6dcc2080-8702-11ea-9736-fdef9177deec.jpg)

**Comment by egberts** [comment]
also in `ed` insert mode, when pressing Ctrl-D (to end data input) actually locks up the entire app.


It is still a good app.  Keep up the good work.

Using Blink Shell v14.0.2 (2 weeks old) on a 7th gen. iPad running iOS 14.8.

**Comment by carloscabanero** [comment]
Fixed the issues, but closing in favor of added Vim on 17.3.0.
