### ISSUE TITLE
It Should Be Advertised That Cmd+Period => Escape

### ISSUE THREAD

**Issue by crsohr** [blinksh/blink#1004]
I just stumbled upon a [MacStories article](https://www.macstories.net/stories/magic-keyboard-for-ipad-pro-a-new-breed-of-laptop/) that reminded me that, on iPadOS, Cmd+Period behaves as it does on the Mac: like if Escape had been pressed.

Just tested on the Magic Keyboard, it works as expected in Blink. I believe it works with all physical keyboards.

Might be useful to include that tip in the Config screen.

**Comment by javierdemartin** [comment]
Thanks for the heads up, we will add it to the public documentation we're working on and will ad it to the settings view too 👍. I'll close it once it's been done.

**Comment by martinorob** [comment]
Is this Cmd+Period working anymore?
Whit last update (in beta too) i can’t esc anymore from vim with “cmd + .”
Is this a bug?
Thanks

**Comment by martinorob** [comment]
It seems than now, cmd + .  now is “page up” 🙁

**Comment by carloscabanero** [comment]
Documented on Q&A https://github.com/blinksh/blink/discussions/1940
