### ISSUE TITLE
Alias Support in Blink Terminal (Feature Request)

### ISSUE THREAD

**Issue by jessiebryan** [blinksh/blink#1006]
Hello,

Would it be possible to have the Blink terminal support aliases?

One use case is to connect to specific SSH hosts one after the other:

alias WebFarm='ssh web01 ; ssh  web02'

Then whenever I'm in Blink Terminal, I can type: WebFarm (Tab Completion?) and it would ssh to web01 then when that session ends it would ssh to web02. Both web01 and web02 would be already defined Hosts in Blink.

Let me know your thoughts.

**Comment by gstokkink** [comment]
Would like to see this as well. I often have to execute certain SSH commands, and would be very useful to be able to set aliases.

**Comment by oG14108149527Exl0Ftr7sY** [comment]
Would be great with alias support in Blink for starting SSH tunnels

**Comment by kkebo** [comment]
I think Blink should be able to support the `alias` command easily. ios_system has already supported it since v2.7.0, so just update ios_system (if Blink uses older version) and add [this entry](https://github.com/holzschu/a-shell/blob/a86c5314ad01f74f19917eeb885a2d64e16cdbda/Resources/commandDictionary.plist#L5) into commandDictionary.plist. Then, Blink can run the `alias` command.

**Comment by oG14108149527Exl0Ftr7sY** [comment]
Re: ...so just update ios_system...

Question:
This requires a jailbroken iPhone?


If, not.

How do I add the  [this entry ](https://github.com/holzschu/a-shell/blob/a86c5314ad01f74f19917eeb885a2d64e16cdbda/Resources/commandDictionary.plist#L5) to the  "commandDictionary.plist"?

**Comment by kkebo** [comment]
You can't do it. My comment is not a user perspective, but a developer perspective.

**Comment by oG14108149527Exl0Ftr7sY** [comment]
Thank you for clarifying. Then I will have to continue to use [Textexpander](https://textexpander.com/individual) as a replacement to get similar functionality.

**Comment by oG14108149527Exl0Ftr7sY** [comment]
This is a list over Textexpander optimized apps:

https://textexpander.com/textexpander-ios/apps


This is the Textexpander SDK:
https://textexpander.com/textexpander-ios/sdk

It would be great if Blink could be enhanced  for Textexpander with the Textexpander SDK.

**Comment by carloscabanero** [comment]
We support now this flows through our Snips functionality. We will be coming up with easier ways to running Snips as well soon. Closing.
