### ISSUE TITLE
Hide Keyboard

### ISSUE THREAD

**Issue by norcalli** [blinksh/blink#1007]
Before the keyboard refactor, I could tap the screen to hide the keyboard. That seems to no longer be the case. I can't figure out how to hide the keyboard or find anything referencing this in any existing issues.

**Comment by carloscabanero** [comment]
We had to disable this to support mouse touches and scroll. The way to do it right now is by just sliding down the keyboard. Will add to the Docs.

**Comment by yury** [comment]
Closing this issue. Feel free to reopen if needed.
