### ISSUE TITLE
Generating RSA keys actually generates DSA keys

### ISSUE THREAD

**Issue by fingolfin** [blinksh/blink#1008]
If I generate an 4096 bit RSA key in blink, it instead generates a DSA key. In the end, I generated the key in another iOS SSH app and imported it from there to Blink.sh.

See #998

**Comment by yury** [comment]
@fingolfin on what device? Can't repro yet

**Comment by fingolfin** [comment]
This was bogus. My sincere apologies for wasting your times.

Background: I've had issues getting Blink.sh to work again after not having used it for some time. I tried importing the keys from Blink.sh to Termius, because with that, I still was able to log into all my servers; but I setup different private keys for Blink and for Termius. So my plan was to copy the Blink private key to test it with Termius. But upon importing the key, Termius reported it as DSA!

But now your comment made me question whether I should trust Termius. So I sat down and figured out how to decode the private key myself (ASN.1, *sigh*) and verified that the key *is* RSA. So the bug is in Termius, not in Blink; and the trouble I've had must have some other source.

Again, sorry for wasting your time.
