### ISSUE TITLE
Feature request: support Eternal Terminal

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#1011]
(https://eternalterminal.dev/)

The issue is that mosh is effectively abandonware at this point; the latest news item on the website is from 3 years ago, and the latest commit was almost a year ago.

Eternal Terminal looks to support the same sort of functionality, and is actively developed. Would it be possible to add ET as a supported protocol in Blink?

**Comment by dmitryzykov** [comment]
+1 for ET support

this issue is a dub for https://github.com/blinksh/blink/issues/597

**Comment by sbromberger** [comment]
Oops. Sorry for the duplicate.
