### ISSUE TITLE
emacs solarized frame-background-mode dark

### ISSUE THREAD

**Issue by drewwells** [blinksh/blink#1013]
Seeing issues with colors when using frame-background-mode dark in emacs. Light mode looks fine. Emacs also looks fine without loading solarized theme. I tried 256color tests and everything looks fine. Anybody know what the issue is? Happens on mosh/ssh with or without tmux.

![E115D6ED-96DB-4634-8E88-4968F7F8D5AB](https://user-images.githubusercontent.com/239123/81223849-51ef3700-8fac-11ea-9624-e4773c56b029.jpeg)

**Comment by aulambda** [comment]
Do you have this problem with all themes, or just some? I know the doom-themes package includes some fancy features that don’t play super well with terminal emacs without fiddling. I had some similar issues with background colors that I fixed mostly by just using different themes, although making sure I was running Mosh with 256 helped. Terminal emacs just ends up being a bit of a second-class citizen in the emacs world, so even though almost everything works, MELPA packaged are generally made with the assumption that they’ll be used in GUI Emacs (for good reason, it’s better, but not an option on iOS).

**Comment by carloscabanero** [comment]
Make sure on your bashrc you have the proper term too. This is what I use:

`export TERM=xterm-256color`

**Comment by drewwells** [comment]
I use xterm-256color. I’ve only noticed it with this one theme, even light version of the same theme works okay. I once upgraded all my melpa packages and loaded up emacs with perfectly fine colors... so I can’t pin down exactly what the issue is. I use this setup in any number of configurations across SSH/mosh connections and directly on my laptop. I only get this washed out effect in blink shell.

**Comment by Alan-Bodygram** [comment]
@drewwells, did you ever figure out what was causing this? I have the same issue, also only in Blink. All of the colors seem correct except for:

1. Vim, which also uses the dark Solarized theme; I have the same grey background as you.
2. Powerline in Tmux; again, the grey background where it should be true, dark background.
3. Some other places in Tmux Powerline, like where I'm supposed to have dark text on orange background or grey text on white background.

My `TERM` is also set to `xterm-256color` (or `screen-256color` inside Tmux, but the behavior is the same in or out of Tmux).

Thanks!

<img width="2096" alt="iTerm vs Blink" src="https://user-images.githubusercontent.com/84754519/187357828-a044bf41-5dd0-4c35-9d5f-95778efaef15.png">

**Comment by carloscabanero** [comment]
Closing here. I can only replicate this if I do not have the proper setting for TERM. We used not to pass this env variable to the remote, but it should be all good now.
