### ISSUE TITLE
Custom keyboard shortcuts: Send ANSI, Hex & Text

### ISSUE THREAD

**Issue by JonGretar** [blinksh/blink#1015]
I would love being able to customize keyboard shortcuts and send escape sequences and other things over to the terminal.

The only feature I miss, and I mean the **only**, from the terminals on my mac is being able to use _Command-K_ to clear the screen. It's just such a natural shortcut for me after decades of terminal usage that I accidentally use it a few times a day in Blink.sh.

No instead of just adding this specific keyboard shortcuts to the app wouldn't it be more powerful to add, to the current keyboard shortcuts menu, the ability to bind [ANSI escape sequence](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_sequences) code to a shortcut. And even other shortcut Actions could be _Send Hex Code_ and even just _Send Text_

That way I could just bind my _Command-K_ key to something like `'\033[2J\033[3J\033[1;1H'` and everyone is happy. It would really turn it into a poweruser terminal.

**Comment by exPHAT** [comment]
@yury Can these new key-bindings be used like the example provided in the original description? Looking to bind `Command-K` myself and can't seem to get it working by inputting the hex version of the ANSI clear sequence.

**Comment by yury** [comment]
Yep, I will add Send ASCI sequence as well. And there is a bug, actually. We just output but not interpret sequence. So I hope we will push 13.5.1 soon.

**Comment by JonGretar** [comment]
> @yury Can these new key-bindings be used like the example provided in the original description? Looking to bind `Command-K` myself and can't seem to get it working by inputting the hex version of the ANSI clear sequence.

If you need it right now you can send `636C6561720D0D` which basically just prints `clear<cr><cr>` to the remote terminal. The only issue with that until the fix is that the clear commands appears in the history.
