### ISSUE TITLE
Issues reconnecting to mosh

### ISSUE THREAD

**Issue by soleblaze** [blinksh/blink#1016]
I’ve been having an issue lately where I’m doing something in blink, go to another tab for 5-10 minutes, then when I come back to blink mosh won’t reconnect. However, it tends to reconnect fine if I close the app for the night and go back to it the next day. Do y’all have any suggestions as to how I can troubleshoot this?

**Comment by yury** [comment]
Are you connecting to the mac? MacOS can go to sleep.
Also try to use ipv4 address for host instead of domain. (It could be ipv6 issue)

**Comment by Abraxas-365** [comment]
One thing you can try to reconnect is create a new ssh connection on an new window and  and mosh connection will reconnect automatically. That works for me

**Comment by soleblaze** [comment]
It’s a linux machine running Ubuntu 20.04 Server. I’m connecting via the hostname, which is only configured for ipv4. I’ll update the firewall to allow ipv6 as well and see if that works. I also tried sshing from another window and that didn’t help mosh.

**Comment by soleblaze** [comment]
Changing my hosts entry to the IP of the server fixed the issue. Thanks!
