### ISSUE TITLE
ed appears in top right of screen

### ISSUE THREAD

**Issue by soleblaze** [blinksh/blink#1017]
When I use my custom font (dejavu sans mono nerdfont) with a font size of 22 or larger ‘ed’ appears in the top right of my screen using the same color as the background. It messes up the font a bit as it’s rendered on top of whatever is going on in my terminal. This is shown even before I ssh/mosh into a server. Any ideas?

Here’s an image of it when I use a different colorscheme in neovim: [https://imgur.com/a/kqwqkgW](https://imgur.com/a/kqwqkgW)

I’m loading the font from this [gist](https://gist.githubusercontent.com/soleblaze/dae162dfa86055822632054a87062169/raw/5917b553999059955aa2a4d8062569b2990f9a2f/dejavumononf.css)

And the theme from this [gist](https://gist.githubusercontent.com/soleblaze/4d18777238efe3f500809323b729a174/raw/94d9e9d9f5c4373450b29e1fa43d1d29e476f33f/cobalt2-hyper.js)

**Comment by yury** [comment]
@soleblaze thank you! It is end of `undefined` :) Fixed. Will ship in next release

**Comment by yury** [comment]
Fix is released with Blink 13.5.1. 
Closing this issue, feel free to reopen if needed.
