### ISSUE TITLE
Close sessions

### ISSUE THREAD

**Issue by iohenkies** [blinksh/blink#1019]
Hi. With old connections, you get this at the top of the screen:

`mosh: Last contact 2.19 ago. [To quit: Ctrl-^ .]`

How can I close these sessions? CTRL C, CTRL D and CTRL ^ doesn't work, as does swiping down with 2 fingers.

**Comment by iohenkies** [comment]
This helped me:
https://github.com/blinksh/blink/issues/944
I.e. use the ^ tucked away on the software keyboard instead of the one right at the top.

**Comment by carloscabanero** [comment]
Closing as this seems to already be tracked in that issue.
