### ISSUE TITLE
Right cmd key doesn't work as modifier for functional keys

### ISSUE THREAD

**Issue by alandao** [blinksh/blink#1021]
Only the left CMD key on my iPad Smart Keyboard Folio works in the terminal for functional keys. I've checked that Command is set to 'Any' in Settings -> Keyboard -> Functional Keys. I'm on iPad OS 13.4.1

**Comment by yury** [comment]
@alandao thank you for report.

Turns out they fixed bug, location for right cmd was 0 before. Now it is correct 2 value.

Pushing fix.

**Comment by yury** [comment]
Fix is released. Closing this issue. Feel free to reopen if needed.
