### ISSUE TITLE
iPad OS and Background Application Killing

### ISSUE THREAD

**Issue by acm0055** [blinksh/blink#1022]
I am currently using Blink to forward SSH ports to access a website in the browser from localhost. I would like to have a full screen web browser; however, that would cause iOS to kill Blink.

Is there any solution to the killing of background apps in 30 seconds?
I saw mentioned somewhere about Geo services. I do not see that in the application from the App Store. Do I need to build Blink myself to enable this?

Also, would it be possible for Apple to grant an exception since this is similar in use to say a VoIP application? This is probably not possible, just wondering.

**Comment by carloscabanero** [comment]
The `geo track` command is available on the AppStore and it does exactly that. Try it out!

**Comment by travelingflwr** [comment]
I’ve been having issues with the latest 13.5 update where even with geo disconnects still happen.  Having a shortcut to send a soft (or even hard) reset may help to prevent having to kill Blink to reconnect.

**Comment by travelingflwr** [comment]
> I’ve been having issues with the latest 13.5 update where even with geo disconnects still happen.  Having a shortcut to send a soft (or even hard) reset may help to prevent having to kill Blink to reconnect.

Ios14 pub beta now seems to change this behavior somehow.  Not saying it’s a fix but now I have not disconnected my mosh connection since upgrading.

**Comment by carloscabanero** [comment]
Lets keep an eye on this. Mosh shouldn't disconnect. SSH will but shouldn't with geo. 

Closing for now, feel free to reopen please.
