### ISSUE TITLE
Cannot access iMac with Remote Login enabled

### ISSUE THREAD

**Issue by gzikfrid** [blinksh/blink#1024]
I am trying to ssh my iMac from my iPad Pro using Blink. When i try to ssh using imac's name(while i am in the same wifi) or by the routers IP address(while i am in the same wifi) i can connect with no issue. When i try to do the same by using the public IP (while i am in the same wifi) instead i receive a socket error:

`blink> ssh -vvvvv <Public IP address>
ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPY
ING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_socket_exception_callback: Socket exception callback: 2 (-1)
ssh_socket_exception_callback: Socket error: Unknown error: -1
ssh_connect: current state : 9
Socket error: Unknown error: -1`

I am trying to access it using Pubic IP so that i know that i can work remotely and not only if i am on the same local network

**Comment by yury** [comment]
Could it be, that router doesn't port forward to your mac from internet?

**Comment by gzikfrid** [comment]
@yury YES!!! You are right. I made it work when i enabled port forwarding to my router. Excellent work guys. Just bought the application today. It worked perfectly. I can now work remotely. And kudos to the support!!!
