### ISSUE TITLE
Socket error: Unknown error -1 on iPadOS 13.5.1

### ISSUE THREAD

**Issue by imphat** [blinksh/blink#1044]
Hello. I’ve just purchased blink for iPadOS and I cannot connect to any host.

```
blink> ping 192.168.1.10
PING 192.168.1.10 (192.168.1.10): 56 data bytes
64 bytes from 192.168.1.10: icmp_seq=0 ttl=64 time=6.541 ms
64 bytes from 192.168.1.10: icmp_seq=1 ttl=64 time=8.565 ms

--- 192.168.1.10 ping statistics ---
3 packets transmitted, 2 packets received, 33.3% packet loss
round-trip min/avg/max/stddev = 6.541/7.553/8.565/1.012 ms
blink> ssh 192.168.1.10

Socket error: Unknown error: -1
blink> ssh -vvvvvv 192.168.1.10
ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_socket_exception_callback: Socket exception callback: 2 (-1)
ssh_socket_exception_callback: Socket error: Unknown error: -1
ssh_connect: current state : 9

Socket error: Unknown error: -1
```

Termius works fine. Any ideas?

**Comment by yury** [comment]
@imphat Does `ssh2 192.168.1.10` works for you?

No ideas yet. Please restart blink or reboot device.

**Comment by bthooper** [comment]
I'm getting the Socket error: Unknown error: -1 when I try to ssh into my local server...or any other server..

On iPad running iOS 13.5.1

**Comment by yury** [comment]
@bthooper can you post ssh-vvvvvv host output?

**Comment by bthooper** [comment]
sure....just FYI, I was able to log in with a different (not as good!) app...so my server is working....
this is what i got just trying to connect locally....

ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_socket_exception_callback: Socket exception callback: 2 (-1)
ssh_socket_exception_callback: Socket error: Unknown error: -1
ssh_connect: current state : 9

Socket error: Unknown error: -1

**Comment by yury** [comment]
Do you use direct ip like `ssh user@ip` or created host in config?

**Comment by yury** [comment]
@bthooper just in case, can you reboot device. This log is really doesn’t make any clue.... ;(

**Comment by bthooper** [comment]
i've had the problem both ways - with a cofigured host in teh settings and by directly inputting the IP address....i also did a hard reset and the problem persisted for me....

**Comment by yury** [comment]
@bthooper can you check `ssh -G host` output and make sure everything is ok there?

**Comment by bthooper** [comment]
hmm...it looks right....

**Comment by yury** [comment]
Can I try? You can dm me on discord or email. I really wanna diagnose this thing and push fix asap

**Comment by bthooper** [comment]
wait....i think my internet provider has changed my ip address because i doin't have a static ip...

**Comment by bthooper** [comment]
weird though because it didn't seem to work just on the local network either....but now it is...so i'm thinking i might have just not noticed the new ip address
