### ISSUE TITLE
Socket error: disconnected when trying to use ProxyCommand to bastion host

### ISSUE THREAD

**Issue by ptimmons** [blinksh/blink#1045]
I have ~/.ssh/config on my laptop that I am trying to get working in Blink. The configuration looks like this:
```
Host     labsystem6
    User root
    Hostname abcabcbabcbabcbabc.onion
    ProxyCommand        ssh root@lab1 nc --proxy-type socks5 --proxy 127.0.0.1:9050 %h %p
```
When I try "ssh labsystem6" in Blink, it returns "Socket error: disconnected"

In my Blink host configuration I set `HostName` with the `.onion` address, I set the `User`, and `ProxyCmd` with the same content as shown above.

**Comment by jjo93sa** [comment]
+1 for Blink to support a wider range of config commands, see #970

**Comment by Laffreux-dev** [comment]
Same here with this ProxyCommand

`ssh -o 'ForwardAgent yes' preprod 'ssh-add && nc %h %p'`

When i try to connect :

```
blink> ssh prod
Socket error: disconnected
```

**Comment by KyleBoyer** [comment]
Any updates on this?

**Comment by carloscabanero** [comment]
For some reason I forgot to close this one more than a year ago, when all this got implemented. You can now use ProxyCommand or ProxyJump indistinctly. We prefer ProxyJump as it will be more compatible. We also added all the remaining flags to SSH config file. The only unsupported thing (for now) will be the "Match" clauses.
