### ISSUE TITLE
iPadOS 14 Beta 1 - Buttons Block Bottom of the Screen

### ISSUE THREAD

**Issue by wintermi** [blinksh/blink#1049]
On iPadOS 14 Beta 1, you have a floating middle dock, showing [Fill | Lock | Close | Create].  This hovers over the terminal and blocks the screen.

This makes a full screen SSH/Mosh not usable as you are typing directly below this floating dock.

Can this be disabled?

![blinksh](https://user-images.githubusercontent.com/33818/85491458-ee31d380-b616-11ea-9148-0dbe7aeaaa88.jpeg)

**Comment by yury** [comment]
I will try to fix that once I get back to office (at the end of the week)

**Comment by peppy** [comment]
A temporary solution for those in trouble can be to force quit the app (they will be gone until next multitask). Not optimal, but for longer sessions it can help.

**Comment by travelingflwr** [comment]
> A temporary solution for those in trouble can be to force quit the app (they will be gone until next multitask). Not optimal, but for longer sessions it can help.

That’s not my experience.

**Comment by wintermi** [comment]
> A temporary solution for those in trouble can be to force quit the app (they will be gone until next multitask). Not optimal, but for longer sessions it can help.

This did not work for me.

**Comment by yury** [comment]
@wintermi 13.5.2 is released, please try to update from app store

**Comment by wintermi** [comment]
> @wintermi 13.5.2 is released, please try to update from app store

Thanks @yury 

Update just came through and works well. ☺️

**Comment by yury** [comment]
Nice. So I'm closing this issue.
