### ISSUE TITLE
iOS 14 Beta ctrl key.

### ISSUE THREAD

**Issue by MacDragon** [blinksh/blink#1053]
Ctrl key input on soft keyboard does not seem to be working for me on ios 14 beta on iphone, can't terminate remote closed mosh sessions, or disconnect tmux.

A lot of keyboard flickering happening that only seems to happen in blink shell for some reason too, that I expect may be related in some manner.

Both the previous only seem to apply to iPhone, iPad is functioning seemingly fine.

Though All of these could of course be entirely OS level issues that will be fixed in due course, but should be reported to apple if determined to not be new behaviour.

**Comment by MakeItGreatAgain** [comment]
Can confirm, same here, when it even works, it's normally too slow to use - mosh keystrokes can be delayed multiple seconds on an iPhone X

**Comment by MacDragon** [comment]
Can confirm this does indeed appear fixed, thanks, was one of the very few things acting odd so far for me on beta.
