### ISSUE TITLE
blink shell overwrites ipad's paste buffer... sometimes

### ISSUE THREAD

**Issue by gyre** [blinksh/blink#1055]
After killing off the blink shell app, or switching to it after having had other ipad apps as a focus for a while, I see the scissor icon appear in the centre of the screen.  This overwrites what I originally had in the ipad's paste buffer with what I'd previously put into the paste buffer for that blink shell window.

If I then move to another blink shell window, I see the scissors icon again and once again the paste buffer is overwritten, presumably with what had be put in the buffer for that window.

After that, moving between windows does not overwrite the paste buffer... at least for a while.

This is with the latest testflight version of blink shell, but I noticed it on the previous version too.  My ipad is an 2017 ipad pro 10.5 running the latest non-beta version of ipados.

If I can help debug this further, please shout.

Thanks!

-- gyre --

**Comment by gyre** [comment]
latest testflight mentions this issue but doesn't appear to fix it.  :)

**Comment by carloscabanero** [comment]
Closing. Fixed on #1956.
