### ISSUE TITLE
Unresponsive and slow on iOS 14 iPhone

### ISSUE THREAD

**Issue by alepacheco** [blinksh/blink#1056]
Just downloaded the app and it it’s really slow on my iPhone when having two terminals open to the point it is not usable

**Comment by yury** [comment]
@alepacheco we are experiencing same thing, but with other apps too. So we think, it is general iOS 14 beta issue.

**Comment by dlasky** [comment]
I can't tell if it's the same issue but I'm also essentially unable to exit broken mosh sessions without a hardware keyboard

**Comment by Stephanvs** [comment]
I'm experiencing the same thing. My config is iPhone 11 Pro running on iOS 14 Beta 2. Haven't noticed this problem with other apps yet. Instagram, GitHub, Reddit all seem to work fine for now.

**Comment by yury** [comment]
@Stephanvs we fixed that and we will push to review today

**Comment by javierdemartin** [comment]
@alepacheco @Stephanvs Newest version is in the App Store 13.5.5, check it out and let us know if that improves :)

**Comment by Stephanvs** [comment]
Downloaded, and the problem seems solved! Thanks
