### ISSUE TITLE
imgcat support seems to be broken in Blink

### ISSUE THREAD

**Issue by gravicle** [blinksh/blink#1058]
I tired imgcat inside tmux over mosh, as well as over just plain ssh. I do not see any image pixels, but empty lines. I am running 13.5.2.238.

**Comment by carloscabanero** [comment]
The problem is that imgcat doesn't work over mosh, because mosh pre-renders the sequences itself. I'd suggest trying ssh, and we will be adding file browsing soon too which will help.

**Comment by gravicle** [comment]
Thank you for the response! Looking forward to file support.
