### ISSUE TITLE
Can't get Hosts configuration to work for mosh

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#106]
I don't seem to be able to get the Hosts configuration working for mosh (ssh works fine)

With the following setup:
![img_0045](https://cloud.githubusercontent.com/assets/112306/18030826/dd772c72-6c94-11e6-9e6e-725c9f49dd10.jpg)

I get this error:

    blink> mosh katamon
    bash: katamon.physik.uni-kassel.de: command not found
    Did not find remote IP address

**Comment by carloscabanero** [comment]
Ok, the "Server" area equals the --server argument of mosh, which is used to specify the path to the mosh-server command. Just remove that and you should be good.

I will keep this open because the bug is that it isn't clear at all what that does.

**Comment by goerz** [comment]
Ah, I see.. that works.

I think the confusion came from that the "SSH" and "Mosh" section look like they are equal in importance. Maybe it would be better to have and "Advanced" sub-dialog (or "Mosh settings (advanced)", or "Mosh settings", or whatever) to imply a hierarchy. I would imagine that most people will rarely change the mosh settings.

I would pre-fill the mosh "Server" field with `mosh-server` (in grey, just like the default port number in the SSH section). In the same way, I would pre-fill the Mosh "Port" field with `UDP port or range`, since it's not immediately clear how it differs from "Port" in the the SSH section. It's also not obvious what the "Startup Command" setting is.

**Comment by carloscabanero** [comment]
Up on version 0.931

**Comment by jeffswitzer** [comment]
As someone new to mosh and trying to set everything up I too got hung up on putting the hostname in the mosh Server box until finding this github issue. Maybe the prompt text should say "path to mosh-server" or give a sane default example like /usr/local/bin/mosh-server. I don't know the best solution, but just know for this newb that it was unclear that mosh-server is even a command. Awesome app by the way!

**Comment by chris-neely** [comment]
I was in the same boat as Jeff.  My noob brain understood "mosh-server" to mean the IP address of the mosh server instead of the path to mosh-server.  Now that I understand how mosh works it makes more sense.

**Comment by goerz** [comment]
See https://github.com/blinksh/blink/issues/415#issuecomment-366393974

It would definitely be good to redesign the UI for this field for more clarity.

**Comment by jjarava** [comment]
+1 to making this dialog much clearer... The `mosh_server`

**Comment by yury** [comment]
![9411ac97-6223-4ca9-ad71-fd403c946845](https://user-images.githubusercontent.com/5250/49689339-e7c13100-fb30-11e8-92db-30786da29e81.jpeg)

What about like that?

**Comment by jjarava** [comment]
That’d be much clearer — Probably just changing the fields title label to “Mosh server command” or similar; “server” makes you think of IP addresses 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by carloscabanero** [comment]
I think the path to mosh-server in the placeholder would be a lot more clear. Because command could be anything. Or command and path-to-moshserver

**Comment by jjarava** [comment]
If you change the “Server” label to something else and then the “default” suggestion is something like `/path/to/mosh-server` (lets say `/usr/bin/mosh-server` as is the case on my Ubuntu box) then it’ll be much clearer. 

Seeing “server” and then “Port” in another line makes for confusion 

(Anyhow, this is mostly nitpicking on an otherwise *great* app!!)
