### ISSUE TITLE
IMPORTANT NOTICE: iCloud support temporarily disabled

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#1066]
Hi everyone!

Tomorrow we will be releasing a new Blink version with iCloud temporarily disabled. If you need it, please do not update. This is due to Apple policies regarding App Transfer. 

I could tell you the whole horror story but hopefully we will just re enable it in a few days. 

Apologies for the inconvenience.

**Comment by scruffydan** [comment]
Well now I am curious
