### ISSUE TITLE
ALT key override prevents access to some keys

### ISSUE THREAD

**Issue by lukebrowell** [blinksh/blink#107]
iOS: 9.3.4
Blink: v0.927.27. Aug 27 2016
iPad Air2 with Logitech Type+ bluetooth keyboard case (en-uk)
**Steps to reproduce:**
  1. Open Blink and try to type a ```#``` character (alt/option+3) on apple en-uk bluetooth keyboard.

**Expected Outcome:**
 * It should display the ```#``` character

**Actual Outcome:**
 * It displays the ```3``` character

**Notes:**
 * Makes editing dotfiles, shell comments and writing markdown awkward. 
 * Not a feature in other ios ssh clients.

**Recommendation:**
Don't override ```alt``` behaviour by default as for many users this requires a work around of setting alt to none in config>keyboard. 
Alt+[key] is used for lots of special characters on ios/OSX, so any single key override should honour these combinations.

**Comment by carloscabanero** [comment]
Agree, will remove the default behavior :)

**Comment by carloscabanero** [comment]
Up on version 0.931
