### ISSUE TITLE
Beta 14-2 (and 1) config doesn't work 

### ISSUE THREAD

**Issue by dlasky** [blinksh/blink#1071]
Launching the graphical config editor via config command appears to execute but no GUI appears.

**Comment by javierdemartin** [comment]
We're aware of that issue on iOS 14. Currently I've seen it happen on my iPhone but not on iPad. Will fix it soon.

**Comment by dlasky** [comment]
no worries totally understand its a beta, was just trying to be helpful with the reporting!

**Comment by javierdemartin** [comment]
@dlasky Current App Store version (13.5.5) solves this. I'm closing this as of now as it works in current iOS 14 beta 2. Thanks for the tip!

**Comment by dlasky** [comment]
confirmed! thanks for the fast work!
