### ISSUE TITLE
ICloud should not sync the host key name

### ISSUE THREAD

**Issue by gaevoc** [blinksh/blink#1073]
Most of the times, keys are device specific, so the key name should be not synced along with the host profile in order to avoid messing up the host profiles on devices where that key is not available.

**Comment by javierdemartin** [comment]
iCloud sync has been deactivated in either App Store and TestFlight versions of the app for the last week, see [here](https://github.com/blinksh/blink/issues/1066). Is this issue related to this or is it still happening?

**Comment by gaevoc** [comment]
Hello,
As far as I know iCloud sync has been reactivated in version 13.5.5

Regards
Gaetano

**Comment by gaevoc** [comment]
> Edited previous answer as it was not correct. We don't sync key themselves, only `key_names` are synced.

This is the key point. IMHO key names should not be sync'd because it is rather frequent that on different devices different keys with different names are used. 

Thank you!

**Comment by carloscabanero** [comment]
Closing #623
