### ISSUE TITLE
Ctrl+v Ctrl+v activates recording on iPadOS 14 beta

### ISSUE THREAD

**Issue by jakub-stastny** [blinksh/blink#1079]
![image](https://user-images.githubusercontent.com/60524926/87457638-50ef0d00-c5ce-11ea-9d1f-2dcb0194e6bf.jpeg)

I'm running iPadOS 14 beta 2 with Blink from the App Store.

When I press Ctrl+v twice, I hear a system sound and the recording indicator gets activated.

After few seconds it plays the sound again and the indicator goes away.

What's going on? I don't expect neither microphone nor camera to be used.

**Comment by carloscabanero** [comment]
We will check this out, but just to set the record straight, we don't record anything in any way. We don't even have anywhere to send us anything. This seems like some iOS shortcut.

**Comment by jakub-stastny** [comment]
@carloscabanero yeah I suspect so, but I'm confused that it's not bound to Command, which would typically system-wide things use, but to Ctrl.

For the record, I'm using the SmartKeyboard Folio, iPad Pro 2018 11" in case it's relevant in any way.

**Comment by javierdemartin** [comment]
@jakub-stastny We've tested it and looks like the `Ctrl` key acts as a system-wide shortcut to trigger dictation. I haven't been able to find a page on Apple's website that documents this but you can try this on another app that's not Blink that accepts text input.

We don't know if this shortcut was here before iOS 14 as we've just discovered testing it though.

**Comment by jakub-stastny** [comment]
@javierdemartin yeah you're right. I played with it and it seems that it's `Ctrl` `Ctrl` that activates (and disactivates) dictation. I guess that'd be fine, but where's the issue is that it also gets activated by `Ctrl+anything` `Ctrl+anything`. Of course nothing you could do about it directly, but I see this as a mayor annoyance to many users (especially users of programs such as Emacs or in my case Tmux as well).

**Comment by yury** [comment]
![862B67DE-9C5F-4182-B010-E590DDF9F00C](https://user-images.githubusercontent.com/5250/87548835-bc5fda00-c6b5-11ea-82b5-da5140f06d70.jpeg)

Found settings for that (Dictation shortcut).

**Comment by jakub-stastny** [comment]
Thanks @yury, that's exactly what I was looking for!

**Comment by javierdemartin** [comment]
@jakub-stastny This has been fixed in iOS14b5, tapping twice `Ctrl-<KEY>` doesn't trigger the voice dictation warning you mentioned, only when tapping twice `Ctrl` to the Shortcut modifier you specify. 

I'm gonna close this in hopes it stays as is, feel free to reopen if you see this happening. Thanks for reporting it!
