### ISSUE TITLE
"Keys" vs "Keyboard" is confusing

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#109]
Could I suggest the "Keys" section of the config box be changed to "Encryption keys" or something else that's uniquely unambiguous with "Keyboard"? I realize it's under "SSH" vs. "TERMINAL" sections of the box, but I still have tapped "Keys" a number of times when I meant "Keyboard" just because it's the first thing that looks right.

**Comment by goerz** [comment]
Another nitpick: in the "Special Keys" section, it should probably be "CapsLock as Esc" instead of "Caps as Esc", for consistency

**Comment by carloscabanero** [comment]
Will fix both. Thanks a lot for taking care of the experience!  :)
