### ISSUE TITLE
iOS 14 Public Beta: black bar at the bottom

### ISSUE THREAD

**Issue by perelin** [blinksh/blink#1098]
Hi,

I just started using the iOS 14 public beta and Im observing a black button bar at the bottom of the blink console. The buttons are (Cover,Lock,Close,Create): https://imgur.com/a/MOWU33p

Blink v13.5.234

**Comment by javierdemartin** [comment]
Is this permanent? I'm able to bring up that menu tapping with [three fingers](https://appleinsider.com/articles/19/06/27/new-ipados-button-bar-offers-a-shortcut-for-three-finger-gestures) and dismiss it tapping anywhere on the screen.

**Comment by perelin** [comment]
Hi @javierdemartin ,

I forgot to mention that Im using the Magic Keyboard for the iPadPro. But it happens also without it.

The black bar does not go away when I tap the screen. The three finger tap open this button bar for me: https://imgur.com/a/x4v6BjG tapping the screen then dismisses. But this doesnt affect the black bar.

I can reliably reproduce the issue:

* start Blink
* switch to another app (either by swiping or CMD-Tab)
* switch back to Blink

How can I help debugging?

**Comment by MrMarc** [comment]
I can reproduce the problem on the release version of iPadOS 14. Tapping the screen doesn’t make it go away
![36ABADE3-4BAF-48A0-82E9-357580A04A48](https://user-images.githubusercontent.com/363793/93410399-ee80ea00-f866-11ea-99e9-06cd765c8a2f.png)

**Comment by yury** [comment]
We released v13.5.7 build 244 with possible fix for this issue. @MrMarc @perelin can you check with that version?

**Comment by yury** [comment]
Closing. Feel free to reopen if needed.
