### ISSUE TITLE
command “clear” moves the cursor off the screen

### ISSUE THREAD

**Issue by thegreatluke** [blinksh/blink#1100]
After typing the clear command on a 2020 11inch ipad pro the cursor is moved out of the display view. It looks like it goes above the top of the screen. If you hit enter a couple times after “clear” then the cursor come back into view.

**Comment by yury** [comment]
Hello, I can’t reproduce this. Can you record short video?

**Comment by thegreatluke** [comment]
Well I’m starting to think it might be just when I’m connected to my Fedora 32 machine now that I look a bit closer.

I actually don’t know how to record my screen :) I’ll look though.

**Comment by yury** [comment]
To record screen go to Settings.app -> Control Center and add “Screen Recording”. Now if you open control center you will see circle in circle icon - that is record. Tap on it and record to Photos

**Comment by thegreatluke** [comment]
So I have a video recorded in my photo’s. Thanks now I know how that works! - anyway not sure how to share it. Github apparently doesn’t like the file type that Apple uses to create the video.

**Comment by carloscabanero** [comment]
Closing as couldn't replicate and this is old. Please open new one if this shows again.
