### ISSUE TITLE
imgcat doesn’t work over SSH

### ISSUE THREAD

**Issue by gravicle** [blinksh/blink#1102]
I tested imgcat over SSH following this: https://github.com/blinksh/blink/issues/1058. However, it doesn’t seem to work over SSH either. A gray pill appears in the center of the screen in response to `imgcat <file>` and that’s all.

![D58FEB04-29DE-4A59-8D65-CFB59A886D4C](https://user-images.githubusercontent.com/1091114/90720467-6f01fa00-e26b-11ea-9135-a99ddc53c1ba.png)

**Comment by carloscabanero** [comment]
Closing here. This is used regularly by some users and should be working atm.
