### ISSUE TITLE
Can’t get scp to work with ssh host setup

### ISSUE THREAD

**Issue by Blogostef** [blinksh/blink#1103]
Dear Blink dev team,
I am using Blink on iPadOS 14.0
I have correctly setup a host called _sandbox_ to connect via ssh and key authentication

blink> ssh -v sandbox
socket_callback_connected: Socket connection callback: 1 (0)
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
blink: setting socket keepalive: 1
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey,gssapi-keyex,gssapi-with-mic
blink: using auth methods attempt: 1 of 5
blink: import key sandbox_key_ecdsa
blink: open channels
blink: open session
ssh_packet_global_request: Invalid SSH_MSG_GLOBAL_REQUEST packet
Activate the web console with: systemctl enable --now cockpit.socket

Last login: Sun Aug 23 07:22:52 2020 from 80.214.66.32
[centos@s1-2-de1 ~]$

However, I cannot get scp to use the same key to authenticate and copy a file (see below). Any idea where this could be coming from (is it a syntax problem with my command or a problem on the host?).

blink> scp -v file.txt sandbox:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 51.89.119.114...
TCP_NODELAY set
Connected to 51.89.119.114 (51.89.119.114) port 22 (#0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* SSH MD5 fingerprint: f4c98b121b5fd31a43001608c58b59be
SSH host check: 0, key: AAAAB3NzaC1yc2EAAAADAQABAAABgQDepwM4YExKoVGYTJSm/ky0p49qkeOt/bjCJP/XOztd8xuTE8p+2ZzagzM22UfeK/HdfwcPcgSEmWp7AWjU8lbtGM8dvK+m7bzPZUubdqCJXB7rajlFsCkh5RTE5DUtd/e9Sp/EUaVU3NvPV/2VlqucW7mUlBk2Iefdhv12fHnJiSJDL82+0CvBC83t1aQCW2pYQkaF3NZDfr+TsNdm6453UzCJEoXFpSs/SRjTvluvAIyfmCSlrvdhsbPAavSqFgjgUksTpt5OxSQy3V+NMyqn2YexnraXt6rfjGUEWA3zzlmaLaAzC6XDMi5GftjOJC7qGlrQlrXKQU88/k3iCSqVflq+8SqFM653RuTY2Ez1tlBda4mUnMSmuA37y26xg9WWeLEM3QHM0R35/jHr/4jKph85H2c78uB4FuDFGv4qm0pMVE0TEzoqmhKN9pp1LvTXnV1Bu4vUlriGKIZSNK0Bg+xHlA/u+uVTKUqU+SGUynaYWPsFfnVP8vh7s6GScOU=
SSH authentication methods available: publickey,gssapi-keyex,gssapi-with-mic
Using private key stored in BlinkShell keys: 'sandbox_key_ecdsa'
SSH public key authentication failed: Callback returned error
Failure connecting to agent
Authentication failure
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Closing connection 0
curl: (67) Authentication failure

Thanks in advance for your support.

**Comment by javierdemartin** [comment]
Currently there is ongoing work improving SSH and also SFTP support in Blink. We'll let you know as soon as we've finished work on this area.

**Comment by SuperBo** [comment]
I also really need this feature, please let me know if I can help in any part of development.

**Comment by carloscabanero** [comment]
This was already part of the 13.90 release, available on TestFlight.
