### ISSUE TITLE
Feature Request - Duplicate Host Configs

### ISSUE THREAD

**Issue by mentalrooster** [blinksh/blink#1108]
I have a number of hosts that share similar configs where the host name is the only thing different, but other settings such as port, key, and proxycmd are the same. It would be helpful to be able to duplicate a Host to quickly create another with the same config.

**Comment by carloscabanero** [comment]
Totally forgot about this but recovering per a discussion on Discord. Should be out on next TF 17.1

**Comment by carloscabanero** [comment]
Done and shipped on 17.1.
