### ISSUE TITLE
Feature Request: Mouse Support on External Display with Extended Mode

### ISSUE THREAD

**Issue by chipsenkbeil** [blinksh/blink#1109]
At the moment, there is no support to use an external mouse (wired or bluetooth) on an external display connected to an iPad. To my knowledge, you can still touch and use mouse on the iPad's own display when using extended mode.

Was skimming through issues and I didn't see any that directly talked about this limitation in depth.

### Questions

Curious to learn a couple of things:
1. Is this a limitation on Apple's side to enable apps to provide mouse support on external displays?
2. If not, what are the technical challenges that blink would need to overcome to support this?
3. If it's possible, is this on a roadmap or task list of blink's?
4. If it's not on a roadmap, how would I get this added to it? Add a bounty for the feature?

### Use Case

For me, I have blink leveraging mosh to connect to a remote server with an active tmux instance. I have a super ultrawide monitor (49") that my iPad Pro is leveraging and - with blink - I'm able to take advantage of the entire screen.

I have three tmux panes for a left, center, and right view. I want to run [browsh](https://www.brow.sh/) in one of the panes, but it unfortunately requires mouse support at the moment as there are no complete navigation keybindings (vim or otherwise). My only option would be to run in mirror mode, which would limit me to a much smaller viewspace on my monitor.

![20200829_171443](https://user-images.githubusercontent.com/2481802/91647020-723f7780-ea1b-11ea-8ba4-ac1f02756ec7.jpg)

**Comment by yury** [comment]
iOS doesn’t support mouse on external display. Actually it doesn’t support any input on external display. We have to do hack to make kb working with external display. 

Only way, I’m think it could be done is by mirroring cursor. 
No plans for this feature yet.

**Comment by chipsenkbeil** [comment]
@yury, thanks for the quick response. I was afraid it was an Apple limitation. Here's hoping that an easier path opens up with some later version of iPadOS.
