### ISSUE TITLE
Feature Request: \007 (BEL / ^G) in terminal results in (optional) ipad sound / notification

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#1110]
Hi,

It would be really helpful if, when we receive a `BEL` (\007) character in a terminal, we could configure Blink to send an audible beep or notification to the ipad so we can hear a sound.

(Edited to add: my use case would require this in mosh.)

**Comment by sbromberger** [comment]
Thanks!!! This will be a HUGE help.

**Comment by javierdemartin** [comment]
@sbromberger Once this build is out check the new "Notifications" menu in Settings to configure everything.
