### ISSUE TITLE
Document undocumented features

### ISSUE THREAD

**Issue by Immortalin** [blinksh/blink#1111]
Geo track for tunnel keep alive etc.

**Comment by javierdemartin** [comment]
You can find at [blink.sh/docs](blink.sh/docs) all of the current available documentation. For the `geo` command you can find more info [here](https://blink.sh/docs/advanced/unix-roundup#miscellaneous). Is there anything missing that you'd like to see documented?

**Comment by Immortalin** [comment]
Sorry missed it oops. I think a search feature would be helpful.
