### ISSUE TITLE
Nerd fonts does not work

### ISSUE THREAD

**Issue by Puccet** [blinksh/blink#1113]
I’m trying to use Nerd Fonts,

I’ve correctly installed FiraCodeNerFont from the galley

it seems like it’s correctly configured

but when I login on a remote server that use nerd font only boxes instead of the icon appears

the same font works on my mac with iTerm2

**Comment by wozman** [comment]
I came across the same issue over the weekend. It appears to be an issue with the Fira Code Nerd Font css file as far as I can tell. All the other nerd font css files contain the fonts base64 encoded and they all work. The Fira Code Nerd Font just contains links to external files such as https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Light/complete/Fura%20Code%20Light%20Nerd%20Font%20Complete.ttf

If you look here https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts you can see that Fira Code was updated 8 days ago. Clearly the update broke something.

**Comment by wozman** [comment]
This is the merge that broke it - seems to have removed the .ttfs that the Blink Fira Code Nerd Font css file refers to

https://github.com/ryanoasis/nerd-fonts/commit/1cf59ffa5552d230582254bf9cb5c3335284dcc7

**Comment by Puccet** [comment]
Hmm very strange I've just test the Arimo nerd font and they are BASE64 encoded but don't work as well

**Comment by wozman** [comment]
I switched to the JetBrains Mono Nerd Font and that’s working fine for me for now

**Comment by Puccet** [comment]
No way just imported JetBrains Mono Nerd Font from GitHub gallery but no icons at all

**Comment by Puccet** [comment]
I'm running iOS 13.7 it could be related to this iPadOS version?

**Comment by Puccet** [comment]
It appears like the font settings does not work at all

**Comment by Puccet** [comment]
I can set the any font I like but the appearance does not change

**Comment by Puccet** [comment]
also size is ignored, I've changed the size from 11 to 14 and nothing happened it just continue to use 11

**Comment by Puccet** [comment]
Well, this is very strange, during some tests I've disabled the cursor blink and the nerd fonts reappeared, ok then I've re-enabled the cursor blink and the fonts are still there, so it appears there is a bug in the settings managements

**Comment by wozman** [comment]
Are you creating a new window/tab after changing fonts? Changes only get picked up in a new session, they don’t affect your existing session. With regards to iOS 13.7, I upgraded to iOS 13.7 yesterday which was after I had had the problem and switched to JetBrains Mono Nerd Font, and everything is still working with JBMNF after the upgrade.

**Comment by Puccet** [comment]
Thanks for support, I've restarted the whole app to be sure and now I've installed and reinstalled but the weird behavior remain

Now fonts are gone again no idea why

**Comment by Puccet** [comment]
Ok, I've just understood one thing, session are persistent to app restart and to iPad reboot

so your suggestion was right you have to kill all the running session/windows and open a truly new one

this way the settings are loaded and the font honored

honestly I find this behavior a little disappointing, for what I known is not documented anywhere

**Comment by wozman** [comment]
I’m just another user who came across the same issue with Fira Code Nerd Font a few days back. We’ll have to wait for the devs to weigh in.

**Comment by Puccet** [comment]
Ok there's no issue with setting and Nerd fonts just Fira code mono nerd font is broken
