### ISSUE TITLE
Font settings are ignored

### ISSUE THREAD

**Issue by Puccet** [blinksh/blink#1114]
On IpadOS 13.7 it appears that font settings are completely ignored, I've tried to change font family, size and other option but nothing change

**Comment by Puccet** [comment]
It turns out you have to kill all the existing sessions and open new ones to have them use the new settings.

One important point is that sessions persist to app restart and also to iPas reboot, it's not clear if this is the intended behavior or not since documentation is not so detailed.

**Comment by javierdemartin** [comment]
Settings take effect after opening a new terminal, that's not the same as closing the app or rebooting the iPad. Same applies to changing themes or fonts. 

We'll add that to the docs and let you know. 

Is this problem still happening after opening a new shell?

**Comment by Puccet** [comment]
No the issue was the misunderstanding about close and reopen sessions to have the new settings being applied
