### ISSUE TITLE
Bug: Text selection is broken on iPadOS 14

### ISSUE THREAD

**Issue by aofei** [blinksh/blink#1116]
[iPadOS 14 GM](https://developer.apple.com/download/) has been released. After my test, the text selection is broken.

iPadOS version: v14.0
Blink Version: v13.5.6

**Comment by yury** [comment]
It is working different now. Double tap and swipe, instead of long tap

**Comment by aofei** [comment]
> ... instead of long tap

Confirmed.

And one more feedback. When the text is selected, the toolbar remains until I click on one of them. Otherwise, it won’t disappear no matter where I click outside it. This flaw existed before iPadOS 14, and I always forget to give a feedback.

**Comment by MacDragon** [comment]
Tapping outside closes the selection/menu fine here, so if it's an issue it's not universal.

**Comment by andreiburov** [comment]
> It is working different now. Double tap and drag/swipe, instead of long tap

Could you update the navigation doc? https://blink.sh/docs/basics/navigation

**Comment by yury** [comment]
@andreiburov thanks, will deploy new docs today
