### ISSUE TITLE
Support raw TCP connection (telnet)

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#112]
For debugging purposes and to connect to embedded devices, it's frequently useful to run `telnet $host $port`; while there's a Telnet protocol for login, it's been superseded by ssh (and now mosh), so I'm not sure full Telnet support is necessary, but it would still be very nice to be able to "telnet into" older/embedded devices, even if that just means a raw TCP connection.

**Comment by carloscabanero** [comment]
I will definitely consider this. It will be really cool for embedded devices!

Will put in the Icebox so that other people can jump in and we decide a way to go through it, although probably just raw TCP just be enough.

**Comment by carloscabanero** [comment]
Closing. We have supported through ios_system for a while. And nc for debugging.
