### ISSUE TITLE
Can't hide "Fill/Lock/Close/Create" bar

### ISSUE THREAD

**Issue by amunra81** [blinksh/blink#1121]
After the iPadOS 14 this bar "Fill - Lock - Close - Create" appears and I don't know how I suppose to make it disappear 

![IMG_0320](https://user-images.githubusercontent.com/3176255/93724640-9cff9480-fbb1-11ea-92a2-f7c458647618.png)
![IMG_0321](https://user-images.githubusercontent.com/3176255/93724643-a557cf80-fbb1-11ea-958e-618f7f961fbc.png)

**Comment by javierdemartin** [comment]
That pop up appears when you tap with three fingers on the screen, this is the same either for iPad or iPhone. Tapping away on the screen should dismiss it. 

Are you using the latest version in the App Store? We submitted a fix for that a couple of days ago, see [CHANGELOG](https://github.com/blinksh/blink/commit/3972742219c9065b9532498a84b597db8c6f9eeb).

**Comment by amunra81** [comment]
No, I'am using the latest "raw" branch from repo. And i'm not taping with three fingers, is like this no matter i do is there

**Comment by amunra81** [comment]
Sorry, my bad, it din't correctly pull requested, now I've just observed the git error
