### ISSUE TITLE
Losing connection on iOS 14 after being in the background for only a few seconds 

### ISSUE THREAD

**Issue by dwetzel72** [blinksh/blink#1122]
I am losing ssh connection after blink is in the background for just a few seconds

**Comment by carloscabanero** [comment]
SSH connections are lost whenever iOS kills your application. To keep them running longer, please execute the `geo track` command as well. It is a way to keep location services in the background which will keep the sockets open.

**Comment by dwetzel72** [comment]
Does not really stay open for a long time.

**Comment by travelingflwr** [comment]
I’m seeing disconnects even with mosh and geo track on.  I’m on iPadOS 14.1 (beta) and the latest beta of Blink.

iPad Pro stays on the same network so nothing is changing there.

Even with something running in the shell (like a continuous ping), the mosh connection has dropped 3 times as I was composing this response.

**Comment by monkinco** [comment]
After the last upgrade 13.5.7 with Public Beta of iPad OS 14 I'm also seeing degraded performance when using Blink. With great internet connections it's starts lagging and after a while it loses connectivity. That didn't happened earlier.

**Comment by carloscabanero** [comment]
Closing here, this is old and if there is anything going on it should have been fixed long ago.
