### ISSUE TITLE
Permission error when accessing icloud from ios14

### ISSUE THREAD

**Issue by iamwille** [blinksh/blink#1123]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Configuration

14.0
### Describe the bug

I am using iPad pro using 14.0.
When i try to access icloud directory from blink, a permission error occurs
Please see this snap shot.
Thanks

https://photos.app.goo.gl/TcHk6YNXasA2UrnH9

**Comment by yury** [comment]
I think it is known issue of permission from iOS13 to iOS14, you should delete iCloud folder and restart the app. Blink will create new one.

**Comment by muammar** [comment]
I wonder if it is possible to access my iCloud files from the terminal?

**Comment by yury** [comment]
@muammar yep, you can use `link-files` command for that

**Comment by muammar** [comment]
> @muammar yep, you can use the `link-files` command for that

Great. This worked. What if I want to remove a link created by `link-files`? Let me explain quickly what I plan. So, I have 2 TB of data that I would want to upload from my iPad. I don't have a MacBook pro. So I plan to use sftp and the `link-files` to try and see if it works :). I see there is no `rsync`. Is this possible to have available somehow?

**Comment by carloscabanero** [comment]
The new sftp has a --update flag that would help in this scenario. And yes, that would definitely work with the new sftp, do not try this with the Files.app.

Closing here as this is already a few months old.

**Comment by muammar** [comment]
> The new sftp has a --update flag that would help in this scenario. And yes, that would definitely work with the new sftp, do not try this with the Files.app.
> 
> Closing here as this is already a few months old.

Thanks for the update. I tried using sftp but it looks like directories can not be transferred. Is that correct? I also could not find a way to specify a port.
