### ISSUE TITLE
Enable "X11 forwarding" for ssh

### ISSUE THREAD

**Issue by sergii4** [blinksh/blink#1126]
I use my Ipad Pro through Blink.sh as a client to my remote workstation. I use it for coding so I use Vim as my editor. 
Unfortunately, I am unable copy to clipboard from remote server even after following the [manual](https://askubuntu.com/questions/347519/unable-to-copy-from-vim-to-system-clipboard). I assume that I need [enable "X11 forwarding"](https://superuser.com/questions/326871/using-clipboard-through-ssh-in-vim) with `ssh -Y` that is not supported on blink.sh:
```
blink> ssh -Y root@100.100.100.100
: illegal option -- Y
usage: ssh [-aCGVqTtvx]
           [-F configFile] [-i identity_file]
           [-l login_name] [-o option]
           [-p port] [-L address] [-R address]
           [-W host:port]
           [user@]hostname [command]

```
Could you please add this feature?

**Comment by nanzhong** [comment]
I've worked around this by using the OSC 52 escape sequence which Blink supports. My setup configures tmux and emacs to use this method whenever I need to get something on my system clipboard.

**Comment by sergii4** [comment]
Hi @nanzhong, thank you for reply. To be honest I haven’t try`tmux` yet, I have been still configuring my remote workstation. Could you please guide me what should I do to use your script?

**Comment by yofriadi** [comment]
is there any update for this?

**Comment by carloscabanero** [comment]
Closing here as the original post is about requesting X11, which I think we have mentioned in other Issues that we will not be doing as it is out of our scope and there are other apps that offer better "Remote Desktop" experience than what we have the bandwidth of doing.

For copy to the clipboard, we have a bunch of tips here: https://docs.blink.sh/basics/tips-and-tricks#editors. In the OSC 52 case, and there is a known bug with Mosh #1205.
