### ISSUE TITLE
Passphrase protected keys

### ISSUE THREAD

**Issue by smokemyshoes** [blinksh/blink#1128]
I can't seem to find the feature that allows me to protect keys i create in blink with a passphrase which is a must for me.

In the GUI config I simply cant see the option when generating keys and if i create a key with the _ssh-keygen_ command in the CLI, it neither show up in the GUI config nor is it available to copy with _ssh-copy-id_... Or at least I haven't figured out how to do it.

I would like to request a feature in the GUI to create passphrases when generating new keys or alternatively create a clear instruction on how to create and transfer keys using the CLI.

Thanks in advance.

**Comment by carloscabanero** [comment]
Hi @smokemyshoes, sorry for the delay getting back on this one. Our keys are already stored encrypted as part of the keychain, and we now also support Secure Enclave protected keys, which cannot be read from outside. We think the passphrase maybe made sense when an unattended computer or key could be stolen, but as the app itself can be protected and even the device as a whole blocked, it is time to move on and distracting with a passphrase is not necessary.
