### ISSUE TITLE
Feature request: external display rotation

### ISSUE THREAD

**Issue by kimburgess** [blinksh/blink#1130]
Hi there - I work from an iPad and live in Blink almost full time. I also enjoy vertical monitors. Unfortunately these two things are not compatible.

At the time of writing iOS does _not_ support external display rotation. There does however look to be the [ability to control orientation on UIKit view controllers](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621438-preferredinterfaceorientationfor).

When using blink with an external display, it would be an incredible feature to have a config item for explicit orientation control of the terminal window shown on this. This would enable a physically rotated (portrait) display to be used without the need for external image processing.

**Comment by yury** [comment]
Hello @kimburgess.

I'm wondering if latest iPadOS with stage manager solves this issue?

**Comment by carloscabanero** [comment]
This should be supported on iOS and probably Stage Manager at one point.
