### ISSUE TITLE
External display feature crashing after a few keystrokes

### ISSUE THREAD

**Issue by nico-bellante** [blinksh/blink#1133]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

blink v13.5.7.244
iPhone 11 Pro Max
iOS 14.2
airplay-ing to an apple tv with tvOS 14.0
### Describe the bug
When trying to use the tv as a second monitor (not-mirrored) configuration, I am able to make it work for just a few keystrokes before what looks like the shell crashing, and starting a new one (i see the little blink terminal size icon appear and disappear) but then it's just a blank background that I can't interact with. cmd + o does nothing. shift + cmd + o does nothing. only thing that seems to fix it is stopping screen mirroring and restarting it, but then the same issue just happens again after a few key strokes.

**Comment by carloscabanero** [comment]
Closing as this is old and it was fixed a long time ago.
