### ISSUE TITLE
Unstable connection when port forwarding for VNC use

### ISSUE THREAD

**Issue by augustinasn** [blinksh/blink#1135]
Greetings!

Connecting to a remote machine via SSH and creating port forwarding with a -L flag for port 5900 (for VNC) appears to be creating not so stable connections - I am trying to VNC into my AWS machine via the aforementioned technique, connection succeeds, but screen freezes after 10 seconds or so. Connection is stable when connecting from my PC, thus it can't be AWS's fault, I've also tried multiple VNC clients for iPad and they all produce the same outcome (frozen screen) so it's not VNC client's fault as well. There has to be something wrong with how Blink is forwarding the traffic.

Would appreciate any help!

Best regards,
Augustinas.

**Comment by carloscabanero** [comment]
Hi Augustinas! Have you tried to start the `geo track` command, before starting the tunnel? What may be going on is that while Blink is in the background, iOS won't give us any time to read from the sockets, and that's why you may experience this.

**Comment by augustinasn** [comment]
Carlos,

Thank you very much for a prompt reply and provided information - your proposed solution solved the issue. Based on your problem description I've also tried running Blink alongside the VNC client, in a split view, and it solves the issue as well :) it could be a nice alternative to some who has a problem with sharing their geolocation.

Thank you again and best of luck!

Augustinas.
