### ISSUE TITLE
Feature request: prevent background unloading

### ISSUE THREAD

**Issue by KimBurgess** [blinksh/blink#1142]
On a heavilly used device, background unloading can happen frequently when switching between apps. It's a more or a minor annoyance if you're connecting to a tmux session, but still an annoyance.

iSH has taken an interesting approach that seems to work well: use location requests to prevent this from happening. See ish-app/ish#249.

Having this as an optional feature would be an incredible annoyance remover.

**Comment by javierdemartin** [comment]
The [`geo`](https://blink.sh/docs/advanced/advanced-ssh#persistent-ssh-connections-with-blink) command on Blink does exactly that.

**Comment by KimBurgess** [comment]
Oh wow, that's perfect - I had not seen that.

The `geo lock` subcommand is a beautiful feature.
