### ISSUE TITLE
SmartKeys are very large on iPhone 12 (Pro)

### ISSUE THREAD

**Issue by m-rossi** [blinksh/blink#1143]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iPhone 12 Pro
iOS 14.1
Blink 13.5.8

### Describe the bug

After updating to Version 13.5.8 the SmartKeys are very large and less symbols are accessible. See a screenshot below

![IMG_2616](https://user-images.githubusercontent.com/4509134/97781520-4c099580-1b8c-11eb-9308-66ac6a71ad56.PNG)

**Comment by yury** [comment]
@m-rossi thanks for report. Can I invite you to TestFlight to test fix?

**Comment by m-rossi** [comment]
@yury Sure, I will send you a mail with my apple-id.

**Comment by m-rossi** [comment]
Fixed with version 13.5.9, thanks!

**Comment by yury** [comment]
Yep, v13.5.9 with the fix just released.
