### ISSUE TITLE
Cannot ssh, ssh2 or mosh into LAN server

### ISSUE THREAD

**Issue by dryad** [blinksh/blink#1144]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug

I can ssh into WAN servers, but not LAN servers. It worked one day, then the next morning (after update to iPadOS 14) it no longer worked. Nothing I do fixes it (restart iPad, restart server, etc.) Termius works! So the server is running and it is a problem with Blink....

**Comment by dryad** [comment]
And now it works again. No clue.

**Comment by yury** [comment]
Closing this issue. Feel free to reopen if needed.
