### ISSUE TITLE
iPhone 12 pro layout outside safe area

### ISSUE THREAD

**Issue by rahrah86** [blinksh/blink#1146]
What starting the app on iOS 14.2 the prompt is rendered outside the safe area and behind the Face ID notch making it difficult to see what you’re typing:

![0C1B6E65-CD6A-4CDE-A12A-B7C82938EB0C](https://user-images.githubusercontent.com/66896752/98518785-b40f4a00-2224-11eb-9a8c-20e5ae12ccf9.png)

**Comment by rahrah86** [comment]
Note: The screen shot does not reflect the notch

**Comment by yury** [comment]
@rahrah86 
What blink version are you using?

**Comment by rahrah86** [comment]
13.5.8.245

**Comment by yury** [comment]
@rahrah86 you fresh install app or migrated it from older device?

You can tap with 3 fingers and choose fit/fill/cover display mode to fix that.

**Comment by rahrah86** [comment]
This was migrated from an old device.

The three finger tap worked - thanks. Strange though because going to config -> appearance and changing that setting didn’t seem to fix it...or at least it didn’t trigger a re-render.

**Comment by yury** [comment]
@rahrah86 config->appearance is for new sessions.
