### ISSUE TITLE
blink auto change focus when connecting to external display

### ISSUE THREAD

**Issue by larme** [blinksh/blink#1147]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

blink version: v13.5.8.245. Oct 27 2020
iOS version: 14.2
device: iPad Pro 2020 using 2 different usb c docks to connect with external display by hdmi

### Describe the bug

When the focus is at the external display, and the not-in-focus blink session on the ipad is refreshing the screen (like running htop), blink will switch the focus back to the ipad session. This bug appears after I upgrade to iOS 14 and is still not fixed in 14.2.

**Comment by carloscabanero** [comment]
If you don't mind, although your report was earlier, let me close this one as it seems like we have more move on 1158. Thanks!!!
