### ISSUE TITLE
Refactoring/Renaming suggestions

### ISSUE THREAD

**Issue by RalphSutherland** [blinksh/blink#115]
TermView.[mh] contains the class `TerminalView`, not `TermView`, inconsistent with the rest of the classes file naming.  Not critical, but could be refactor renamed to be the shorter TermView for the class.   

Also, the `SmartKeys` class is a view controller, so perhaps calling it `SmartKeysController` along with the file names would be more clear.

Again, nothing critical, just issues that arose while learning my way around the app, and I completely defer to Carlos on this!

**Comment by carloscabanero** [comment]
Completely agree! Man, I read that class 3000 times and didn't realize they were different. Code review for the win! ;)

**Comment by carloscabanero** [comment]
Fixed
