### ISSUE TITLE
Option key cannot be configured to esc 

### ISSUE THREAD

**Issue by branaway** [blinksh/blink#1159]
I was trying to configure in the config pop up the Option key of my Apple magic keyboard to function as the missing ESC key to use in emails in a remote session.  In the “PRESS SEND” section I chose “Escape” and in the “AS MODIFIER” I chose “Default”. It did not work.  In emacs the Option key functions like some other key combination that I cannot recognize. 
![AB8CE8A2-B44B-4575-B9A0-8B635F328B9E](https://user-images.githubusercontent.com/179513/99739661-3db5f600-2b08-11eb-91ae-4580fd065b1d.jpeg)

**Comment by carloscabanero** [comment]
Hi @branaway, sorry for the late reply. For emacs you will want to do "As Modifier - Esc" for that, so it will be configured as the Emacs's M key. I have no problem having Option as Escape on press. Can you give us more information on what keyboard you are using and would you mind going here https://javascript.info/keyboard-events and send us the output that you receive? 

Thanks

**Comment by carloscabanero** [comment]
Old support issue. Closing.
