### ISSUE TITLE
Crash when switch the input method

### ISSUE THREAD

**Issue by CubeTian** [blinksh/blink#1162]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [ ] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
Blink 13.5.9 IOS 14.2

### Describe the bug

When you switch to another application, change the input method, and then switch back to blink, it will crash

Want use normally, not crash

**Comment by carloscabanero** [comment]
Hi @CubeTian, could you please attach a video so we can see how you are changing the input and to what for replication? Thanks
