### ISSUE TITLE
Render error on vim and tmux via iPad Pro 

### ISSUE THREAD

**Issue by cospotato** [blinksh/blink#1167]
- OS: iPad OS 14.2
- Blink: latest on AppStore

## vim

with plugin `flazz/vim-colorschemes` and scheme with `colorscheme solarized8_dark`, render error and missing fonts support

![image](https://user-images.githubusercontent.com/7987906/100538707-65c1f980-326c-11eb-99d5-41609594c5ee.png)

## tmux

missing fonts support

![image](https://user-images.githubusercontent.com/7987906/100538767-a457b400-326c-11eb-94dc-512a86e77af7.png)

**Comment by monkinco** [comment]
Is that font in Blink shell?

**Comment by cospotato** [comment]
> Is that font in Blink shell?

yes, i'm using this [font](https://github.com/blinksh/fonts/blob/master/MesloLGS%20NF.css)

**Comment by andrius** [comment]
You might have issue with the font. It is PragmataPro (not Blink-shipped version, I've purchased font-set in past and have created a .css file while ago)
![image](https://user-images.githubusercontent.com/26776/100599542-7623b400-3300-11eb-9f90-51d47a3d7f5d.png)

**Comment by cospotato** [comment]
> You might have issue with the font. It is PragmataPro (not Blink-shipped version, I've purchased font-set in past and have created a .css file while ago)
> ![image](https://user-images.githubusercontent.com/26776/100599542-7623b400-3300-11eb-9f90-51d47a3d7f5d.png)

I use this [font](https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf) to build my own css. It does not work.

**Comment by cospotato** [comment]
update: 
The font problem was fixed with setting `export LANG=en_US.UTF-8` in `~/.zshrc`

**Comment by carloscabanero** [comment]
Thanks @cospotato. Linking to #1171, which should be fixed soon too.

For the colors, are you using ssh or mosh. Is that inside tmux? What terminal do you have set in that connection?

Thanks

**Comment by carloscabanero** [comment]
Closing here. Two fixes on 13.5.11:
- We are now bundling full Pragmata, which was having speed issues before.
- We made changes to the way we are passing the locale so it is compatible with the remote.
