### ISSUE TITLE
Ability to use System Text Replacement inside blink

### ISSUE THREAD

**Issue by kurktchiev** [blinksh/blink#1169]
On a regular system you can have tools like TextExpander or aText or for simple stuff the built in System Text Replacement functionality of OSX.

Currently Blink doesnt honor text replacement shortcuts from the system library and it would be really useful if it did. You could hack something together using the command history and what not, but thats just duplication of effort if there is already a cross system synced replacement engine running.

**Comment by carloscabanero** [comment]
Not sure I follow the requirements here. The problem we usually have when replacing text is that characters are often sent to the terminal, so it is difficult for us to replace the ones previously sent and just send what the builtin system wanted to do. We would need a special "writing" mode for that, and we have another concept in our heads for how this should work.

I will add the icebox and close so we can keep this for future reference when the time comes.
