### ISSUE TITLE
Some key combinations don't do anything

### ISSUE THREAD

**Issue by brontitall** [blinksh/blink#117]
I'm not sure how much control IOS gives in this, but I've noticed that 

Shift-Tab
and
M-Delete

Don't seem to do anything at all. I use the latter in particular all the time in emacs and at the shell, and shift-tab in org-mode.

**Comment by carloscabanero** [comment]
Hmmm... I actually do not know if those combos are sent as special modifiers or is a special configuration from your side. Could you please do a showkey -a and let me know what they send? Thanks!

**Comment by brontitall** [comment]
Ok, I've tried numerous terminal emulators with these two key presses:

* Mintty, windows 10: Shift-Tab , Meta(Alt)-Backspace 
* Putty, windows 10: Shift-Tab, Meta(Alt)-Backspace 
* MobaXterm, Windows 10: Shift-Tab, Meta(Alt)-Backspace 
* Iterm2, Mac (option sends escape):  Shift-Tab, Meta(option)-Delete 

They all produce the same results:

*Shift-Tab*:
 
```
^[[Z     27 0033 0x1b 
         91 0133 0x5b 
         90 0132 0x5a
```
 
*Meta(Alt/option)-Backspace/Delete*:

``` 
^[^?     27 0033 0x1b 
        127 0177 0x7f 
```

**Comment by bradleyjones** [comment]
any update on getting shift-tab to work, that's something I use all the time with zsh tab selection. Let me know if I can provide anything that will help.

**Comment by OolonColoophid** [comment]
I'd like to second this - shift-tab would be very useful for me in Emacs org-mode.
