### ISSUE TITLE
Not Sending Locale Over SSH

### ISSUE THREAD

**Issue by redreceipt** [blinksh/blink#1171]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug

This may be a well known issue but when ssh-ing into my mac server, blink doesn’t seem to be passing LC_CTYPE, leaving the locale unset (and messing up the remote PATH).

The locale be set the UTF-8 on the remote server. This is the expected behavior for Macs so it would make sense that iOS apps would behave similarly. Plus it causes other downstream problems.

Blink output below:
<details>
  <pre>
 ```
blink> ssh mini cat /etc/ssh/sshd_config | grep Accept
AcceptEnv LANG LC_*
blink> ssh mini locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
blink> env | grep LC_C
LC_CTYPE=UTF-8
``` 
</pre>
</details>

**Comment by carloscabanero** [comment]
This should now be fixed on 13.5.11. Additionally, there is a blink/profile file, where in a key value way you can decide on other variables and pass them with -o if required. Please note that Blink per se does not need a very strict locale, so everything we pass is towards the other side.
