### ISSUE TITLE
Bind drag left and right to cursor left and right for command line editing

### ISSUE THREAD

**Issue by jgrg** [blinksh/blink#1177]
I like being able to drag up and down with one finger to navigate the command line history, but dragging left and right isn't bound to anything. I think it would be great to be able to drag left and right to cursor left and right when editing a command line. It should be faster than using the cursor keys.

**Comment by yury** [comment]
@jgrg one finger horizontal swipes switches terminals. You can swipe on arrows key too.

**Comment by jgrg** [comment]
Ah, OK. I only ever have one terminal open.
I didn't know you could hold and swipe on the arrow keys. It works, but I wish there was a gesture that did it faster.

**Comment by carloscabanero** [comment]
Won't fix for now as we have arrow keys. Added tags for future reference if we decide to change controls
