### ISSUE TITLE
Keycast Toggle Keyboard Shortcut

### ISSUE THREAD

**Issue by joshmedeski** [blinksh/blink#1180]
I would like to toggle the keycast feature with a keyboard shortcut. I think it’s helpful while pair programming but doesn’t need to be running all the time.

I can currently hit `cmb+,` and can get to the feature pretty quickly.

**Comment by yury** [comment]
Hello @joshmedeski.

We released v13.5.10 with toggle KeyCast action. You can bind it you keyboard config.
