### ISSUE TITLE
Can't input non-ascii characters

### ISSUE THREAD

**Issue by kadaliao** [blinksh/blink#1181]
![image](https://user-images.githubusercontent.com/7401626/103155606-5c30a080-47dc-11eb-83c1-bf703dd31cec.jpeg)

Hi there, I love blink shell and use it on a daily basis.

The only thing bothers me is that I can't input Chinese characters or emoji. Currently I am typing in another app and then copy and paste the content I need to blink shell.

Don't know it's a bug or a feature not yet fulfilled.

**Comment by yury** [comment]
Hello, what exact input do you use for Chinese? 
I'm able to insert characters:


https://user-images.githubusercontent.com/5250/103172247-369aaa00-4863-11eb-88dd-8fa3fbd273ef.MP4

I use space after words and also numbers

**Comment by kadaliao** [comment]
@yury Hi, I use [sogou](https://apps.apple.com/cn/app/id917670924) and also 'Chinese, Simplified - Pinyin' that comes with ipadOS. Neither of them works.

**Comment by yury** [comment]
Hello @kadaliao,

I still can't reproduce your issue. Can you please screenshot you keyboard settings. Settings.app -> General -> Keyboard. It will help. 

Thank you.

**Comment by kadaliao** [comment]
> Hello @kadaliao,
> 
> I still can't reproduce your issue. Can you please screenshot you keyboard settings. Settings.app -> General -> Keyboard. It will help. 
> 
> Thank you.

Thanks yury.

![image](https://user-images.githubusercontent.com/7401626/103213333-4dff9300-4948-11eb-9447-5f4f7c02fef7.png)

By the way, I'm using magic keyboard for iPad Pro. Maybe it's the reason?

**Comment by yury** [comment]
I need previous screen.

**Comment by yury** [comment]
Also, do you have turned on Full Keyboard control?

**Comment by kadaliao** [comment]
@yury 

Yes, "Allow Full Access" is on.

![image](https://user-images.githubusercontent.com/7401626/103216763-c585f000-4951-11eb-90fc-6138942989cf.png)

**Comment by yury** [comment]
Oh, please remap 'Activate' command to shift+space instead of just space.

Settings.app -> Accessibility -> Keyboards -> Full Keyboard Access -> Commands.

**Comment by kadaliao** [comment]
> Oh, please remap 'Activate' command to shift+space instead of just space.
> 
> Settings.app -> Accessibility -> Keyboards -> Full Keyboard Access -> Commands. 

Oh it works now. Thanks.

But what is this 'activate command' for? Would it affect something else?

**Comment by yury** [comment]
If you don't know what is activate, then it will not affect anything :)

**Comment by kadaliao** [comment]
> If you don't know what is activate, then it will not affect anything :)

OK, never get into this setting page before, looks like a bunch of shortcut to me. Guess I will find out will I need it.

Thanks for helping me out.

**Comment by kadaliao** [comment]
It stops working again. No settings changed.

**Comment by kadaliao** [comment]
> It stops working again. No settings changed. 

And after I reinstalled this app, it's working again. :)
