### ISSUE TITLE
Add an option to disable scrolling.

### ISSUE THREAD

**Issue by jakzale** [blinksh/blink#119]
Sometimes scrolling can get in the way (i.e. when using mosh).

An option to disable scrolling would prevent any unwanted scrollings, especially when using mosh and on-screen keyboard.

**Comment by carloscabanero** [comment]
Just for the record, I tried to solve this but disabling scroll in the WKWebView didn't really work and just messed things up. There must be a way to disable scroll in HTerm, or I will implement it.

**Comment by willhbr** [comment]
Hey Carlos, have you had a chance to look into this? I was just about to file this exact same feature request but found this bug after writing it up. For the record, iTerm supports this by setting the scroll back history to zero.
