### ISSUE TITLE
Custom keybindings

### ISSUE THREAD

**Issue by joshmedeski** [blinksh/blink#1191]
I’d like to remap `CMD+S` to `:w<return>`. Is something like this possible? [Alacritty](https://github.com/alacritty/alacritty) allows you to simulate custom keystrokes with any `CMD+{letter}`.

Alacritty uses hex codes to define the custom keystrokes.

This would make me more productive on the iPad, as I would bind tmux commands (ex: `<prefix>+g` to `CMD+g`).

**Comment by yury** [comment]
Hello @joshmedeski.

You can use `config` command -> `Keyboard` -> `Custom Presses` -> `Add` to add custom bindings.

Choose hex, for you shortcut escape seq would be `3a770d0a`.

**Comment by joshmedeski** [comment]
This works perfectly, thanks for pointing it out for me.
