### ISSUE TITLE
Socket error: Network is down ... but its not! 

### ISSUE THREAD

**Issue by stekole** [blinksh/blink#1192]
### Checklist

- [ X ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ X ] Read the [docs](http://blink.sh/docs/)
- [ X ] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink version: v13.5.10.258
Configured a ssh host using `config` and also tried the address directly 

### Describe the bug

I am having issues connecting to my local network only from the blink.sh app. Other terminal apps work fine. 
 _I have tired the termius app which works for private IPs, which proves its not network connectivity from the device._ 

Public addresses work fine in blink but private does not work. 

I noticed ping and ssh fail for internal network calls.

I expect to be able to ssh and ping on my local network from the blink.sh app. 

I tried some commands which others recommended in old posts to help troubleshoot the issue but it did not give me any more information

I am on the same network, and I see the output of ifconfig confirming this. 

blink> ssh -vvvvvv pi4
ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_socket_exception_callback: Socket exception callback: 2 (2)
ssh_socket_exception_callback: Socket error: No such file or directory
ssh_connect: current state : 9
Socket error: No such file or directory

blink> ssh2 -vvvvvv pi4
Could not resolve host address.
blink> 

**Ping output:**
ping: sendto: No route to host
Request timeout for icmp_seq 0
ping: sendto: No route to host
ping: sendto: No route to host
Request timeout for icmp_seq 1

**Direct SSH to the IP gives:**
Socket error: Network is down

Any help would be appreciated 

Thanks

**Comment by carloscabanero** [comment]
Instead of trying to use Blink's host resolution, could you try to pass the resolved IP you are trying to connect to?

**Comment by stekole** [comment]
That is what I tried in the **Direct SSH to the IP gives** section

I get **Socket error: Network is down**

**Comment by carloscabanero** [comment]
Sorry about that, I had a mental model on my head and missed that header part. Have you done it also with ping?

Reason why I am asking is because they both are completely different implementations, ping is just the standard tool and it tries to resolve using the typical socket libraries for that. The fact that both are failing is usually a smell in the configuration somewhere.

I connect to my local Mac all the time (that is how I am coding Blink these days), and most of our users also do private network connections, so it is weird that something is not resolving properly.

**Comment by stekole** [comment]
thanks so much for your response and help. I know this is very bizarre issue!!! 
Ping also show the same as hitting the hostname. 

**ping: sendto: No route to host
Request timeout for icmp_seq 0**


Is there anyway I can list my routes similar to a `netstat` or `route`  commands? Or anyway I can see my gateway? I have DHCP enabled but I wonder if something bizarre is happening to my gateway or routes.

I will try over tailscale shortly and see if that works.

**Comment by stekole** [comment]
ah ha! figured it out. Sadly I kept focusing on the blink app but in the iOS setting -> blink -> local network was unchecked. I didnt notice this before. 

Closing. Thank you

**Comment by stekole** [comment]
if this isnt in the documentation can we maybe add it somewhere?

**Comment by carloscabanero** [comment]
AAAHHHH completely forgot about that one. There is a box when you first start using it which says "do you want to use devices in your local network". The message really sounds suspicious, but yep, it blocks local connections.

It would be a great idea to add it to the docs, this would probably fit well inside our basic SSH, kinda like a warning, and later on we will add it to our tips & tricks.

Thanks!!
