### ISSUE TITLE
Control + Space changes keyboard layout 

### ISSUE THREAD

**Issue by keshet1** [blinksh/blink#1193]
Ish has this feature that control + Space sends to the terminal instead of changing keyboard layout 
I would love to see it here

**Comment by gcv** [comment]
Go to Blink settings > Keyboard > Custom Presses and configure ctrl-space in there.

**Comment by HouzuoGuo** [comment]
BTW - in a generic terminal emulator (windows terminal, putty, etc), the key-code generated by Ctrl+Space is "00" in hex.

**Comment by janiversen** [comment]
Ctrl-space (external keyboard) is used to change language in iOS (iPad / iPhone), and normally it is caught by iOS before the application gets a change to do something.

**Comment by gcv** [comment]
Ctrl-Space is definitely configurable in Blink to _not_ switch languages. https://github.com/blinksh/blink/issues/1193#issuecomment-780674916

**Comment by janiversen** [comment]
I never doubted that, I was just seeing that on my iPad Ctrl-Space (from an external keyboard) is not passed to Blink or other applications, but are handled by iPadOS itself. To be honest I have not tried it on a "clean" iPad, so it can be that some of my developer software that interferes.

Meanwhile I did test it on a iPhone, and it works "sort of". You need to go to Blink settings > Keyboard > Custom Presses map ctrl-space to ctrl-space, in order for ctrl-space to be sent. Maybe that is something that deserved a line or two in the documentation.

**Comment by gcv** [comment]
Ctrl-space for me on the latest iPadOS with an external keyboard when configured explicitly in Blink. It’s passed on to Blink and I use that keybinding extensively in terminal Emacs.

**Comment by carloscabanero** [comment]
That is correct. This was fixed (until Apple breaks it again) a few releases ago. I use it myself all the time too. Feel free to reopen if there are any issues.
