### ISSUE TITLE
Alt key on magic keyboard not working in shell

### ISSUE THREAD

**Issue by in42** [blinksh/blink#1195]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Using iPad Air 2020 - software version 14.3
### Describe the bug

- Open a blink shell
- Type a word
- Press Option-b on magic keyboard
- A special character is inserted

- The cursor should move back one word instead of above

**Comment by nanzhong** [comment]
This is the expected behaviour. To achieve what you want you need to configure the option key to be treated as `esc`. You can do this via the keyboard menu in settings.

**Comment by in42** [comment]
Even if I configure to `esc`, the first 2 presses result in a special character being inserted and then the cursor starts moving back one word.

**Comment by yury** [comment]
@in42 can you screenshot your kb settings for option?

**Comment by in42** [comment]
![image](https://user-images.githubusercontent.com/12832671/108698059-b2466980-7529-11eb-92e2-9db54531a4f5.png)

**Comment by yury** [comment]
Change to "None" in "Press send" section.

**Comment by in42** [comment]
I did that but the issue is still occuring.

**Comment by in42** [comment]
> @in42 can you try in new terminal after you changed kb settings?

Yeah I tried it in a new terminal using `exit` to exit the current session.

**Comment by in42** [comment]
Using the touch keyboard, it works perfectly, this issue is only occurring when I am using the Magic keyboard.

**Comment by yury** [comment]
https://user-images.githubusercontent.com/5250/108699417-427ab380-7516-11eb-857e-fe7767c9287e.MP4

**Comment by in42** [comment]
Unrelated question, how do I attach a video of the screen recording I made to a github comment using an iPad? I can't drag and drop in iPad?

**Comment by yury** [comment]
![2D471341-EABC-4866-AE79-A446471E956E](https://user-images.githubusercontent.com/5250/108700097-29263700-7517-11eb-914d-383e92749b5f.jpeg)

**Comment by in42** [comment]
https://user-images.githubusercontent.com/12832671/108700239-516c6080-752c-11eb-8871-9f756b57f8fc.MP4

**Comment by in42** [comment]
I am using the 2nd generation Magic Keyboard, if it helps.

**Comment by yury** [comment]
I'm too.

Can you please screenshot Settings.app -> General -> Language & Region and Settings.app -> General -> Keyboard -> Keyboards ?

**Comment by in42** [comment]
![57B10C87-92BD-44F1-82B5-22C958600752](https://user-images.githubusercontent.com/12832671/108701461-005d6c00-752e-11eb-892c-bfa8176e0ce4.png)
![3673A5DC-2E10-4B2C-A530-74B3E44C22A9](https://user-images.githubusercontent.com/12832671/108701475-06534d00-752e-11eb-8e96-3025917ae377.png)

**Comment by yury** [comment]
Please run `cat ~/.blink/kb.json | pbcopy` command and paste to https://gist.github.com and send result here.

**Comment by in42** [comment]
https://gist.github.com/in42/40dd13bd697ab353d9777a5f350a83a1

**Comment by in42** [comment]
I have noticed one more thing - Alt + F is working fine, the issue is only with Alt + B.

**Comment by yury** [comment]
Still can't repro... set all your settings...

**Comment by in42** [comment]
Ok thanks for your help, anyways.
I restarted the iPad, but the issue still persists.

**Comment by carloscabanero** [comment]
What character gets printed instead? Does this also happen when connected to a remote server?

**Comment by in42** [comment]
> What character gets printed instead? Does this also happen when connected to a remote server?

It just changes the previous character to something else. You can seen an example here: [https://github.com/blinksh/blink/issues/1195#issuecomment-783295262](https://github.com/blinksh/blink/issues/1195#issuecomment-783295262). Yeah it happens when connected to the remote server also.

**Comment by in42** [comment]
Changing the type of “Hardware Keyboard” in settings to “US” solved the issue. Earlier it was “Indian English (ABC)”.
