### ISSUE TITLE
Can't import key.

### ISSUE THREAD

**Issue by superdima05** [blinksh/blink#1198]
### Checklist

- [ - ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581). I've built application using Xcode.
- [ + ] Read the [docs](http://blink.sh/docs/)
- [ + ] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iPad Air 4. iOS 14.4

### Describe the bug

When I am trying to import any key using clipboard or file app crashes. Xcode throws me error in file Settings/Model/BKPubKey.m at line 307. Thread 1: EXC_BAD_ACCESS (code=1, address=0x8)

**Comment by superdima05** [comment]
Once I got an error which says that problem in OpenSSL. I embedded OpenSSL when build the project

**Comment by yury** [comment]
Try to use main branch. Raw branch is not stable yet

**Comment by superdima05** [comment]
I've compiled app from main branch and now app works perfectly. Thanks!
