### ISSUE TITLE
Support SSH if MOSH unavailable

### ISSUE THREAD

**Issue by cirqueit** [blinksh/blink#12]
It would be great for when mosh is not available.
Right now, I'd just use my VPS as a jump-server for those connection that don't support mosh.

**Comment by rekendahl** [comment]
I now @carloscabanero has mentioned even implementing 'scp' (and I assume document picker) so I'm sure it will be made available. I agree it's a very important command

**Comment by carloscabanero** [comment]
We actually have a little bit of that implemented, and that's how the new version was running Mosh! I don't know if we will have it ready for release, as Mosh is also a terminal emulator abstracting things like keyboard, that we would have to manage in ssh. Nothing too big but...

**Comment by binaryben** [comment]
Sorry for asking here, I can't open a DM in Twitter it seems. Is Blink likely to be developed into a fully fledged Prompt competitor with MOSH being the major difference over time? I'd be very excited to see a standalone shell for iOS which supports MOSH and SSH. Or should we expect it to remain as a MOSH client only?

**Comment by carloscabanero** [comment]
We will have both, but I do not know if by release. We currently already support ssh, and the way mosh is started is through a real ssh session. The command ssh-copy-Id too. But there are things still to debug like window size changes, keyboard codes, etc... Completely doable though.

We also plan to add other features in the future like SCP, etc...

**Comment by binaryben** [comment]
Very excited to see what comes then. If you have any space in the alpha program, I'd love to be considered (@BinaryBenAU).

**Comment by carloscabanero** [comment]
@binaryben Already sent you a private message ;)

**Comment by carloscabanero** [comment]
Coming next... I changed my mind and think it is actually a must have.

**Comment by BinaryBen** [comment]
![Good news everyone!](http://vignette2.wikia.nocookie.net/en.futurama/images/a/ad/GoodNewsEveryone.jpg/revision/latest?cb=20090731021518)

**Comment by carloscabanero** [comment]
Added since v0.722
