### ISSUE TITLE
Share Encryption Keys

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#120]
From #79 - @joeshaw 
I like the idea of having a default key generated when you first use Blink. Could it be made fairly easy to share the public key using the iOS share sheet? That way I could email or airdrop myself a copy to more easily put it on the hosts I access most often.

**Comment by ezzizzle** [comment]
Hi Carlos, I'm happy to have a look at this feature if you'd like. Not sure what the handoff label is but apologies if this means someone's already looking at it.
