### ISSUE TITLE
Blink.app is not able to connect to Mac

### ISSUE THREAD

**Issue by marchenk0** [blinksh/blink#1200]
### Checklist
client:
**iPadOS** _14.4_ + **Blink.app** _13.5.10.258_
**iOS** _14.4_ + **Blink.app** _13.5.10.258_
server:
**MacOS** _Big Sur 11.2_ + **zsh** + mosh installed by brew - _mosh 1.3.2_ [build mosh 1.3.2], **firewall is off**

### Configuration
* **Termius** is able to login to mac with the same configuration
* All tests were done in **local network with disabled firewall**
* Generated public ssh keys with Blink are located in .ssh/authorizes_keys on my macbook and I'm able to login to it with pure ssh
* I used wireshark and [this](https://github.com/mobile-shell/mosh/issues/1039#issuecomment-489917932) to ensure that my UDP ports on mac are reachable and able to transmit data.
* I faced with locale issue and already fixed it with .zshrc
* These is an exactly the same behaviour whent I specified ports like 60001:60002 during host configuration
* My blink::host configuration
![telegram-cloud-photo-size-2-5269366952101523691-y](https://user-images.githubusercontent.com/1183579/107548523-d2982f00-6bdf-11eb-9bb3-256bf400b47d.jpg)
* Wireshark sniffed connections
<img width="1342" alt="Screenshot at Feb 10 20-51-26" src="https://user-images.githubusercontent.com/1183579/107550243-d62cb580-6be1-11eb-8023-0a07e7799699.png">

### Describe the bug
I'm not able to login with blink mosh into my local mac 
![telegram-cloud-photo-size-2-5269366952101523702-y](https://user-images.githubusercontent.com/1183579/107549221-9d401100-6be0-11eb-98a1-fdb879f87900.jpg)

**Comment by carloscabanero** [comment]
Two things to figure out what is going on:
- Could you try to connect directly by running manually the server on the other side, and Blink passing the provided key (-k) and port (-p)?
- Usually if Blink cannot connect for some reason, is due to not finding the proper key of the remote Mosh. But I do not see that in here. Could you remove the "who am i" command and see what is the output and if we get a shell there?

Thanks

**Comment by marchenk0** [comment]
> * Usually if Blink cannot connect for some reason, is due to not finding the proper key of the remote Mosh. But I do not see that in here. Could you remove the "who am i" command and see what is the output and if we get a shell there?

Carlos, thanks. The problem was in "who am i" command.
