### ISSUE TITLE
How to map Ctrl-F behave as Tab when using local bink

### ISSUE THREAD

**Issue by SuperBo** [blinksh/blink#1201]
I got used to Ctrl-F for suggestion complete. However in Bink, I can only use TAB to complete suggestion.
Can you guy consider adding Ctrl-F as a alternative for completing suggestion.

Thank you

**Comment by carloscabanero** [comment]
Hi SuperBro. You can already do that with Blink. Go to settings (type Config), and under keyboard, select “Custom Presses”. You can there press Ctrl-F, and under action select “Send Hex Code”. The Hex code for tab would be 09. Exit all that, saving the changes. And voila!

**Comment by SuperBo** [comment]
Thank you, I didn’t notice this feature. However, can we make this mapping the default behavior as with zsh.

**Comment by carloscabanero** [comment]
Not sure I follow you here, Ctrl-F is cursor forward on most systems. I don't think we can replace that default, sorry.
