### ISSUE TITLE
Hosts not being stored in the list after being added (Local and iCloud Sync)

### ISSUE THREAD

**Issue by zer0her0** [blinksh/blink#1203]
### Checklist

- [ x ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ x ] Read the [docs](http://blink.sh/docs/)
- [ x ] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink Version: 13.5.11.261
iOS Version: 14.4(iPhone XS Max & iPad Pro 10.5")

### Describe the bug

TL;DR: I'm having issues w/ Hosts not being stored in the list after being added, regardless if iCloud sync is on or not.

I've been using Blink for a while now on both iPhones and iPads, currently an iPhone XS Max & an iPad Pro 10.5". Though I mostly used it to access machines at home, since we've been working from home for a better part of a year I have not used it at all during that time. I just got an M1 Mac mini, decided to set it up in Blink as I am in the office a couple days a week. Opened up Blink on iPhone add the Mini to the Hosts list. A few minutes later flip over to the iPad as I expected it to sync over and not only had it not, all my previous hosts were gone. Add back my current linux box and new Mini to the iPad. Switch back to iPhone, don't see anything there. Add them there again. Wait a bit switch back and they're gone from the iPad again.

Hit up the discord and got these steps to try:

> Try this:
> - Remove all servers on both, exit and reload the config, and disable iCloud on both.
> - Then on just a single one, enable iCloud and try to create a server.
> - Make sure you have notifications for Blink enabled (on iOS settings), otherwise syncing won't trigger.
> - Then on the second one, enable iCloud. Close the settings, open them and go to hosts. See if then it shows up in there.

I removed server on both, exit the config, loaded up the config again and turned off iCloud on both. Force closed apps on both, reopen everything looks good. Walked home for lunch, open up iPad to try out the second step. And somehow my linux box is back on the iPad even though it wasn’t there after i turned off iCloud sync?!? 

So repeat removing the linux box, seems to be gone. Close config, re open, add Mini and turn on sync, go to setting to check on notifications they’re on, go back to Blink...and the Mini is gone from hosts. add it again, close config, and quickly re open and literally see it slide up and away in the UI.

Come to the conclusion ok maybe something is broken/corrupt in the black box that is iCloud sync, since it's just 2 devices w/ only half dozen machines only 2 of which would be used w/ any regularity I decided to just switch to no iCloud sync and set them up on each device. Test the linux & Mini connections on both the iPad & iPhone, everything is good to go. Ok time to make bug report, go to get the version numbers for the devices (both OS and Blink's number) notice the iPhone is missing the Mini in hosts again. Add it, wait 30 seconds to a minute and it's gone again.

**Comment by carloscabanero** [comment]
Thanks for the heads up. Good to know that we were right on pointing to iCloud on this one. Although with iCloud I don’t know if that is a good thing or a bad thing.
