### ISSUE TITLE
ssh <host> -l <user> hangs session

### ISSUE THREAD

**Issue by ucomesdag** [blinksh/blink#1204]

**Comment by carloscabanero** [comment]
Hi, could you please send us the log using -vvvvv so we can figure out what may be going on? Thanks.

**Comment by ucomesdag** [comment]
The hanging only seems to happen when the first thing you enter in a new session is something like: ssh <host> -l <user>

Also the -vvvvv works if you put it directly after the ssh command, ssh <host> -l <user> -vvvvv just ignores it and prompts for a password (without hanging). I also noticed when it does not hang it will just ignore the username completely with -l, only <user>@<host> works.

Output from -vvvv:  https://pastebin.com/nzxEsJCb

-- 
Uco Mesdag
phone: +31 10 3400 826
skype: ucomesdag
vcard: https://uco.mesd.ag/

PGP Fingerprint: 733D B941 416F 02C1 747F  4F9F 18CB 489F 47ED BF14

(Send from my mobile phone)

**Comment by carloscabanero** [comment]
Yes, all these parameter issues have been resolved on latest TF 13.90. Unfortunately they require a new command and we cannot back port it. Will push to production hopefully soon, but let us know if you would like earlier access.

**Comment by ucomesdag** [comment]
> Will push to production hopefully soon, but let us know if you would like earlier access.

Yes, please! Btw is there a donation link somewhere?

-- 
Uco Mesdag
phone: +31 10 3400 826
skype: ucomesdag
vcard: https://uco.mesd.ag/

PGP Fingerprint: 733D B941 416F 02C1 747F  4F9F 18CB 489F 47ED BF14

(Send from my mobile phone)
