### ISSUE TITLE
How to edit the default ssh config?

### ISSUE THREAD

**Issue by in42** [blinksh/blink#1206]
While ssh’ing to a server , I am getting this error:
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_us.UTF-8"

```
I believe this is due to such a line in the default ssh config:
```
Host *
              SendEnv LANG LC_*
```

In MacOS, the default ssh config is present at `/etc/ssh/ssh_config` and there I can just comment this line. How to do the same in blink?

**Comment by carloscabanero** [comment]
By default, Blink already sends to the remote the LANG flag, that should configure on the other side the proper locale. Do you have en_US.UTF on the remote?

**Comment by in42** [comment]
Ok sorry I meant I don’t want to send the LANG flag.

**Comment by carloscabanero** [comment]
You can configure not to send the LANG by just setting it to empty on the .blink/profile file. I wouldn’t recommend it though (that will break your mosh, etc). I would just configure that specific server, on its Shell profile, to set the locale to be empty. Note that will mess with your Unicode and all that, but if you are asking for it, you probably already know.
