### ISSUE TITLE
Turn off ligature on fonts

### ISSUE THREAD

**Issue by yury** [blinksh/blink#122]
Take a look on flow word and how cursor is placed. 

![img_0170](https://cloud.githubusercontent.com/assets/5250/18412129/f8e52544-778f-11e6-9654-7156e4fdcca8.PNG)
![img_0171](https://cloud.githubusercontent.com/assets/5250/18412130/f90d7d8c-778f-11e6-8025-b4415ec5c1a1.PNG)

**Comment by carloscabanero** [comment]
It is normally set to skip ligatures, but I found a case where this could happen. Can you confirm that if you just restart the app it doesn't happen? It is set on boot, but disabled once you select at some point the Default theme, even if you go back to a different one.

**Comment by yury** [comment]
Can't confirm.

If I set Menlo font it does ligatures after restart also.
