### ISSUE TITLE
Can successfully ssh to server, but mosh hangs

### ISSUE THREAD

**Issue by joshourisman** [blinksh/blink#1222]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink: v13.5.12.262. Mar  3 2021
iPadOS: 14.4.2 (18D70)
iOS: 14.4.2 (18D70)
Server OS: Ubuntu 20.04.2 LTS x86_64 
Server mosh: 1.3.2
MacBook mosh: 1.3.2

### Describe the bug

From both my iPhone and iPad, I cannot connect to my Ubuntu server with mosh in Blink. It just sits there forever, and nothing ever happens. I can, however, connect with ssh, and if I don't use a key when I try to connect with mosh I get a password prompt, and it hangs after I enter my password, confirming that the issue appears to be solely with mosh.

From my MacBook, I am able to connect with mosh without any issue, so the issue seems to be connected specifically to Blink.

I don't attempt to connect from my iPad frequently enough to say for sure, but I believe this issue first turned up after the most recent Blink update.

![image](https://user-images.githubusercontent.com/39895/113932030-2af34380-97c1-11eb-85cf-624fa76a3b44.jpeg)

**Comment by brianczapiga** [comment]
Same issue. I can mosh from MacBook but using blink terminal on iOS, it hangs.

Host OS: Ubuntu 20.04.2 LTS (focal)
Host Mosh Version: 1.3.2-2.1build3 (focal)
Blink Version: v13.5.12.262

Both devices (MacBook and iOS) are attempting to ssh to the host along the same network path (same source and target subnets.)

**Comment by yowie** [comment]
Same issue for me.

**Comment by jkraemer** [comment]
same here, Debian Buster host with Mosh 1.3.2.

**Comment by aimerib** [comment]
Same, with mosh 1.3.2 on Manjaro but I’m on Blink 15.07.536

**Comment by aimerib** [comment]
A quick update. I was able to solve my specific issue by changing the mosh server config in Blink shell. If I understand this correctly, Blink will ssh into the server, start mosh-server there, then switch to a proper connection via udp with mosh-client.

In arch distributions systemd seems to be messing with services, and to keep sessions alive with mosh you need to execute it through systemd-run `systemd-run --scope --user mosh-server new` so if you place this bit of code in your blink mosh server config, it should work, assuming that’s the issue.

Found my answer here: https://github.com/mobile-shell/mosh/issues/730#issuecomment-224280671

**Comment by carloscabanero** [comment]
Closing here. Please open a Support issue on Discussions if this still comes up.
