### ISSUE TITLE
External Themes and Fonts: Defending against malformed URLs and JS before _webView evaluateJavaScript: ??

### ISSUE THREAD

**Issue by RalphSutherland** [blinksh/blink#123]
Not an issue yet, but soon....  

If you are going to more fully implement allowing loading themes and fonts from arbitrary URLs,( and solving the ATS Apple Transport Security issues that will bring), what are the plans if any to defend against accidentally or maliciously malformed URLs and/or JS before it is injected into the `_webView` in `- (void)loadTerminalThemeJS:(NSString *)themeContent` and `- (void)loadTerminalFont:(NSString *)familyName fromCSS:(NSString *)cssPath` ? 

 I am surprised to see a raw NSURL  load URL from a textfield input with only minimal url format tests, but I assume that is boilerplate placeholder code atm.  

 Having an internal theme format and ability to edit them would still be great too, and you control the validity absolutely, plus keeping it internal to the app and sandbox will make it much more robust against a whole range of security issues opened up by allowing arbitrary URLs!!   But if you have plans to carefully vet downloaded themes etc before using them then no problem, but I suggest it may not be worth the complexity.

You may disagree, but I suggest it needs some consideration.

**Comment by carloscabanero** [comment]
Thanks a lot for bringing this in Ralph. Glad you noticed that this is all done but disabled ;)

So those two are the options that you already mentioned, either go with our format or do JS all the way. I thought there would be a third, less drastic, if we could make CSS work but unfortunately I couldn't yet.

In defense of the JS path, and having a "sanctioned download repo", I would add that this is how others like HyperTerm or Atom are doing it. Being able to share code with HyperTerm or HTerm will be a good thing that could make everyone benefit from a bigger community. Creating our own way to do this, even if it is just 16 colors would hinder everything else that could be done.

It will be disabled for release (maybe I only enable the CSS for fonts), but thanks again for opening this up :)

**Comment by carloscabanero** [comment]
done on v5
