### ISSUE TITLE
"mosh <host> tmux" will break the command history

### ISSUE THREAD

**Issue by kkk669** [blinksh/blink#1236]
### Checklist

- [ ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

- Blink Shell 13.90.3 (279) (TestFlight)
  - Blink Shell 13.5.12 (App Store) doesn't reproduce this issue.
- iPadOS 14.5, 14.5.1, 14.6 Developer Beta 2

### Describe the bug

After running `mosh <host> tmux`, pressing the ↑ key will display the last command with trimmed spaces.

Steps to Reproduce:

1. Open Blink Shell
2. Configure a host to use mosh
3. Run `mosh <host> tmux`
4. Run `exit` on the remote session
5. Press the ↑ key

Expected behavior:

`mosh <host> tmux` will be displayed.

Actual behavior:

`mosh<host>tmux` will be displayed.

![IMG_0519](https://user-images.githubusercontent.com/601636/117395682-5dfd3400-af33-11eb-9918-3f5576cd3892.png)

In addition, the following commands doesn't reproduce this issue.

- `mosh <host>`
- `ssh <host>`
- `ssh <host> -t tmux`

**Comment by wongjustin99** [comment]
I’m seeing this for mosh commands without Tmux. 

i.e., 

`mosh -P 123 user@host -I keyfile`

**Comment by kkk669** [comment]
When I opened `.blink/history.txt` with iVim, it found that each space of `mosh` command had been replaced with null character (`^@`).

![E15CE14F-9828-46FC-AA61-795FA44BB45A](https://user-images.githubusercontent.com/601636/117667155-945edb80-b1df-11eb-9cd4-5a8face0df68.jpeg)

And this seems to happen only when you run `mosh` with some characters following `[user@]host|IP`. (thanks for @wongjustin99's hint)

**Comment by kkk669** [comment]
Blink Shell 13.90.3 (270) couldn't reproduce this bug, but 13.90.3 (273) could do.

I'll look into commits between those two.

**Comment by agkozak** [comment]
I never saw this problem before two or three days ago, but now it's constant.

**Comment by YujiaBao** [comment]
Hi, I just want to add that the latest app store version `13.5.14` has the same bug too.

**Comment by carloscabanero** [comment]
The issue with the characters breaking the command history was fixed, and it should still be working on latest TF (341). Please let us know otherwise.

This version will make it to the AppStore soon as well.
