### ISSUE TITLE
Mosh never seems to reconnect after iPad lock & unlock

### ISSUE THREAD

**Issue by wongjustin99** [blinksh/blink#1238]
### Checklist

- [X] Using 13.90.3 (279)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
Blink 13.90.3 (279), iPadOS 14.4.2

### Describe the bug

I can successfully connect to a mosh server, and use it. However, once my iPad locks, and I unlock it, I am never able to reconnect. I get the “last contact XX seconds” until I use the escape sequence and re-connect manually. 

Expecting that I don’t have to re-connect every time the iPad locks.

**Comment by Ajaymamtora** [comment]
Also having this issue M1 iPad 14.6

**Comment by carloscabanero** [comment]
I am not able to replicate it, and we have made a lot of changes to Mosh. I don't think this may still be an issue, but let us know.

**Comment by Ajaymamtora** [comment]
I can’t replicate it anymore either

**Comment by carloscabanero** [comment]
Closing here then :)
