### ISSUE TITLE
The prompt will be shifted to the right after pressing Ctrl-L and then running a command

### ISSUE THREAD

**Issue by kkk669** [blinksh/blink#1239]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

- Blink Shell 13.5.12 (App Store) and Blink Shell 13.90.3 (279) (TestFlight)
- iPadOS 14.5.1
- Magic Keyboard

### Describe the bug

Steps to reproduce:

1. Open Blink Shell
2. Press the return key some times
3. Press Ctrl-L to clear the screen
4. Run a command

Then, after the command finishes, the prompt should appear in the right place, but in actual, it will be shifted to the right like the following screenshot.

![8F2778CE-020D-45E8-9533-CDF68239E94B](https://user-images.githubusercontent.com/601636/117676449-8497c500-b1e8-11eb-9347-43a473d5a4ca.png)

**Comment by yury** [comment]
Fixed. 

Thank you for your report.

Will be out in next release.
