### ISSUE TITLE
Blinking cursor makes cursor movements difficult

### ISSUE THREAD

**Issue by brontitall** [blinksh/blink#124]
I may be misremembering but it seems the latest update has added a blinking cursor — seems appropriate given the app name :). Unfortunately it seems to continue blinking even when moving the cursor. 

This is an irritation on the command line, since it's hard to position the cursor when it's not visible half the time. But for some reason I don't understand it seems to be even worse in Emacs and Vi, where if I lean on an arrow key the cursor remains invisible until I release.

Is it possible to have the cursor only blink after a (brief) period of inactivity? This seems to be what IOS does  for text fields.

Alternatively, an option to disable cursor blinking would help.

**Comment by carloscabanero** [comment]
Thanks for the feedback. I thought the default theme should have a blinking cursor, so as a workaround you can try to just change the theme. I will add the option to have a blinking cursor.

**Comment by carloscabanero** [comment]
Related to #144

**Comment by jucor** [comment]
Hi team! Same problem here, blinking cursos makes it really hard to navigate in Vim. Is there a way to turn it off, please? Or to adjust its speed? Happy to hack away at it if you point me in the right direction.

**Comment by jucor** [comment]
Gist created at [https://gist.github.com/jucor/fcec6ae17e8d11b3545924d646d61c60]. Now I just have to compile Blink's latest version -- I'm a morron, I hadn't noticed I'm still using v1.019.40. Duh me.

**Comment by jucor** [comment]
Finally bought the full app, instead of compiling and reinstalling every 7 days: couldn't wait to have access to XCode, and my certificate just expired, so there you go. Blink is definitely worth it, thanks @carloscabanero !

**Comment by jucor** [comment]
So, for anyone having the same problem, temporary workaround as suggested by @carloscabanero, with a Default theme *without* blinking cursor
1/ Go into config
2/ Appearance / Themes / New Theme
3/ Paste this URL: https://gist.githubusercontent.com/jucor/fcec6ae17e8d11b3545924d646d61c60/raw/51e3912963ba4247e9c4b544c39118ff4480dd8d/Default_noblink.js
4/ Give it any name you want.
4/ Done.

**Comment by carloscabanero** [comment]
Done!

**Comment by jucor** [comment]
High five! Thanks @carloscabanero  :)

**Comment by jucor** [comment]
(Naive question: do you know when it will hit the App Store? I've bought the paid version.)

**Comment by carloscabanero** [comment]
I'd say today. They have been really fast with approvals  :)

**Comment by goerz** [comment]
Are you also going to release it into TestFlight? That way, I don't have to switch to the App Store version of have the latest features.

**Comment by carloscabanero** [comment]
Yup, both should be pushed at the same time.

**Comment by carloscabanero** [comment]
fyi, v5 is already available for testers and currently In Review at the AppStore, so it shouldn't take long for everyone :)

**Comment by carloscabanero** [comment]
@goerz Just wanted to give a heads up. V5 was available for testers, Apple removed it when they approved the version to the Apple Store, submitted a new one, that they blocked because they requested a video of the App working, and now I'm waiting for the new one to be approved. Life can be wonderful sometimes.
