### ISSUE TITLE
Leading space causes command not found error

### ISSUE THREAD

**Issue by anjiro** [blinksh/blink#1243]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink 13.5.12
iOS 14.4

### Describe the bug

I use the Gboard soft keyboard with swipe typing. It *really* likes to add a space before a word. This extra space causes Blink to not recognize the command; e.g., instead of

    blink> config

I get 

    blink>  config

and the error that the command is not found.

**Comment by yury** [comment]
@anjiro thank you for report. 

I fixed that, should be ok in next version.
