### ISSUE TITLE
scp curl: (67) Authentication failure

### ISSUE THREAD

**Issue by prairie-guy** [blinksh/blink#1248]
### Checklist

- [X ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x ] Read the [docs](http://blink.sh/docs/)
- [x ] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

I am using the latest version of Blink available on the App Store. I am using iPadOS 14.4.2

### Describe the bug

 

- After several years of using Blink including `ssh-key` authentication for `mosh`, `ssh` and` scp` services, I now have authentication problems when using `scp` only. 

- To be clear, I can use `ssh` and `mosh` to log into my server as expected. (I have verified that there is no password embedded in my host setup.) Until recently, I had been able to use `scp` to transfer files to and from the server on both my iPad and iPhone. 

- Both return the same error: `curl: (67) Authentication failure`

- I generated new keys and transferred these to my server using the command: `ssh-copy-id id_alt `

- Nothing has changed on the server, which I can verify as I control it. (I have shutdown and restarted the server)

- This doesn’t seem to be `ssh-server` related as I am able to `ssh-key` log into my server from my iPad and iPhone using `Blink`.

- To repeat, I have used `scp` for years with no problems until now. 

```
blink> scp -v test1.txt some.where.net:/home/cdaniels/test1.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 73.247.90.51...
* TCP_NODELAY set
* Connected to some.where.net (73.247.90.51) port 22 (#0)
* SSH MD5 fingerprint: ea812b6cf2468c41d4914302436b4731
* SSH host check: 0, key: AAAAB3NzaC1yc2EAAAADAQABAAABAQDkHxNrZhm7j6WVnmuLaHNHxD8L7iNGVcQbldt4xvXKjD7n4HhsxC/73OcY2Hz8XJPyRW88roJMEEX6Nd0UBvr8sc5A9DhprhM53u+xysX7aJro1bADu/2zKPzzlGp3RxSKRQ+JbJy7oOZBlgz0n0AIdYMB2wQCu4TuJyrE5KNjL48er2fAWihPvRXviWL1BUAyWFPISeyh/4Y0u6xQlXGp2O4THeYo8ObtYYu1ga2KgRDr7IylZB4pb9qlMfBF+/UK0+qFeoqgdWNS44WUfvqlkFCCibMp7Lm99L9rLAUrcZvO5C8WIVsLtCrSaqo5kRhHUlPiaxHKm266UVJ+niAr
* SSH authentication methods available: publickey,password
* Using SSH private key file 'id_rsa'
* SSH public key authentication failed: Unable to extract public key from private key file: Unable to open private key file
* Failure connecting to agent
* Authentication failure
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (67) Authentication failure
blink> 
```

**Comment by carloscabanero** [comment]
Hi! We have replaced curl in favor of new scp and sftp commands. We are waiting to make this available on a new release, but it is already accessible at community.blink.sh. Thanks!

**Comment by prairie-guy** [comment]
Many thanks! I will try out community.blink.sh. I think that will be a great feature as the curl implementation has not been quite as clean as authentic scp. After Safari, Mail and Calendar, Blink is the next most important app on my iPad. It really let’s me use the iPad as a replacement to my MacBook Pro. Keep up the great work!
