### ISSUE TITLE
Smart keys never show up

### ISSUE THREAD

**Issue by ChaiTRex** [blinksh/blink#1249]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink v13.5.12.262
iPadOS 14.6
iPad Air 2 cellular

### Describe the bug

Smart keys never appear on on screen keyboard. No external keyboard is connected.

Smart keys should appear when no external keyboard is connected.

![32D19B2F-67EA-4116-ADA3-FCE5089FD890](https://user-images.githubusercontent.com/23159282/122656918-fa1e7b80-d12c-11eb-85f3-b273565cfa16.png)
![6EE9C554-2FA7-4EA9-B920-E83538C3CEB9](https://user-images.githubusercontent.com/23159282/122656927-073b6a80-d12d-11eb-93ed-36cdf3037764.png)

**Comment by yury** [comment]
@ChaiTRex please turn on Shortcuts in Settings.app -> General -> Keyboards.

**Comment by ChaiTRex** [comment]
Thanks, that worked.
