### ISSUE TITLE
Long lines are getting extra newline chars when copy-pasting

### ISSUE THREAD

**Issue by iq6gGsk7** [blinksh/blink#125]
I had to copy-paste a few ssh public keys when noticed the following. When you copy a very long line spreading multiple lines on the screen, when pasting you'll get this line back broken with newline chars to the width of the terminal window when copied.

This is how to reproduce it:

    # cat authorized_keys2

Contains a single ssh pubkey, spreads into 4-5 lines on the screen. Select and copy it!

    # vi test.txt

Paste it into this file for comparison

    # wc -l authorized_keys2 test.txt  
           1 authorized_keys2  
           7 test.txt

**Comment by iq6gGsk7** [comment]
It can be reproduced in both an ssh and a mosh session. I did the test above on freebsd but I bumped into the issue on a linux box.

**Comment by carloscabanero** [comment]
Thanks a lot for the report! This might be a regression as it was working previously, and I thought it was unchanged.

**Comment by iq6gGsk7** [comment]
The version I tested was 0.931.30
