### ISSUE TITLE
Cannot ssh to a local machine (Socket error: No such file or directory)

### ISSUE THREAD

**Issue by ping13** [blinksh/blink#1250]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink: v13.5.12.262. Mar  3 2021
iOS 14.6
Remote machine: Linux Mint 20.1 

### Describe the bug

I installed the app today and I cannot ssh to a machine in my local network (192.168.1.86). 

I can connect with the machine from my Mac and with clients like termius from my iPad. I can successfully `ping` my machine with Blink. However, I cannot ssh to the machine (not with configured settings or `user@192.168.1.86`

I can ssh to remote machines with Blink. I’ve restarted my iPad.

This looks similar to <https://github.com/blinksh/blink/issues/1044>, but since my machine is in my local network, this doesn’t apply (I think).

Here’s the log:

```
blink> ping 192.168.1.86
PING 192.168.1.86 (192.168.1.86): 56 data bytes
64 bytes from 192.168.1.86: icmp_seq=0 ttl=64 time=2.905 ms
64 bytes from 192.168.1.86: icmp_seq=1 ttl=64 time=5.498 ms
64 bytes from 192.168.1.86: icmp_seq=2 ttl=64 time=4.080 ms

--- 192.168.1.86 ping statistics ---
4 packets transmitted, 3 packets received, 25.0% packet loss
round-trip min/avg/max/stddev = 2.905/4.161/5.498/1.060 ms
blink> ssh -vvvvv 192.168.1.86
ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_socket_exception_callback: Socket exception callback: 2 (2)
ssh_socket_exception_callback: Socket error: No such file or directory
ssh_connect: current state : 9

Socket error: No such file or directory
```

Thank you!

**Comment by ping13** [comment]
Oh boy, I the error is in front of the screen. I assumed that the IP address was supposed to be on the top and the `HostName` would be the name of the machine. 

Maybe `HostName` in the dialog could be written clearer as `host  or IP address`?.


![image](https://user-images.githubusercontent.com/108406/124384361-198eda00-dcd1-11eb-9acb-008dbddf6da2.jpeg)

**Comment by carloscabanero** [comment]
Good small improvement, will do.

**Comment by carloscabanero** [comment]
We improved the placeholder. Keeping the Docs label to improve there as well.

**Comment by carloscabanero** [comment]
docs updated.
