### ISSUE TITLE
SSH config User option not working

### ISSUE THREAD

**Issue by rfkortekaas** [blinksh/blink#1252]
### Checklist

- [x] Using latest version from TestFlight 
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

- Blink 13.90.3 (299)
- IPadOS 14.6

### Describe the bug

When using the SSH config file in .ssh\config containing:

```
Host testhost
  HostName 192.168.0.10
  User testuser
  IdentityFile ~/.ssh/id_ed25519
```

And connecting with: `ssh testhost` the User option isn’t used.

When connecting with `ssh testuser@testhost` the public key authentication succeeds.

<details>
  <pre> ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey,password
ssh_agent_get_ident_count: Answer type: 12, expected answer: 12
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey,password
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey,password
password:
ssh_packet_userauth_failure: Access denied for 'password'. Authentication that can continue: publickey,password </pre>
</details>

**Comment by rankun203** [comment]
I’m having the same issue, my server has only publickey login method enabled, it’s showing 

```
ssh_packet_userauth_failure: Access denied for 'publickey'
```

For debugging purpose, I’ve tried other terminal apps on the same iPad and they works.

**Comment by carloscabanero** [comment]
Fixed on TF
