### ISSUE TITLE
Rending problem with ncurses updates

### ISSUE THREAD

**Issue by felipewd** [blinksh/blink#1254]
### Checklist

- [ x ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ x] Read the [docs](http://blink.sh/docs/)
- [ x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Running on IpadOS, blink version v13.5.12.262

### Describe the bug

Just started running Blink, which is awesome by the way, but I’ve noticed an unexpected behaviour. When using with `varnishstat`, if I scroll up/down, the rendering starts going haywire. Seems an issue with window-size calculation (my naive guess).

### Expected behavior

A correct update with no wrong rendering.

#### Screenshots.

A baseline screenshot (with no scroll, just the usual `varnishstat` update):

<img width="1366" alt="PNG Image" src="https://user-images.githubusercontent.com/547142/127787187-59837466-d5a9-42b9-9f56-0fabca8b84ce.png">

An after scrolling down

<img width="1366" alt="PNG Image" src="https://user-images.githubusercontent.com/547142/127787197-f915e183-04ef-4391-bcba-39baf3d9caf6.png">

**Comment by carloscabanero** [comment]
Hi @felipewd! Thanks for your report. Could you explain how you are connecting to the application? Is that ssh or mosh? Also, when you say "scroll", do you mean Blink's finger scroll, or the app scroll, or the app mouse scroll? I have never used varnishstat. Could you send a video? Thanks!
