### ISSUE TITLE
When working on a projected screen, bluetooth keyboard could not type in the Blink terminal

### ISSUE THREAD

**Issue by gp-wang** [blinksh/blink#1255]
platform: iOS 14
screen: projected to a TV 
input: a bluetooth connected keyboard

The feature to work on a projected screen is great. However, when projected to a screen, user can only type on the iPhone onscreen keyboard. The bluetooth keyboard could not type.

**Comment by carloscabanero** [comment]
You can change focus to the remote window by using Cmd-O. That way you can actually switch between the external and device.
