### ISSUE TITLE
Cannot get rid of arrow key/command key palette in portrait mode

### ISSUE THREAD

**Issue by ChaiTRex** [blinksh/blink#1258]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

* Blink 13.5.12.262
* iOS 14.7.1
* iPhone 7
* Logitech K380 keyboard attached via Bluetooth
* Disabled Smart keys, Show with external keyboard

### Describe the bug

The floating arrow key/command key is in the way when I'm trying to read when my iPhone is in portrait mode.

I have an external keyboard connected. I don't need the floating arrow key/command key.

Even when I don't have an external keyboard connected, these keys should be available at the bottom of the screen instead of blocking what I'm trying to read.

![6114A34E-9294-4800-8BD6-6CCD254D37C6](https://user-images.githubusercontent.com/23159282/129423769-a5aa914b-bd23-4e66-a0b6-67a24ff040f2.png)
![9D58C255-35DC-4D54-B6B9-3D8C3BC3F4FD](https://user-images.githubusercontent.com/23159282/129423777-f93f3c91-f7c5-4183-bf15-b864725755c3.png)

**Comment by carloscabanero** [comment]
This should be gone since 14.0 and 14.0.3
