### ISSUE TITLE
Smart keys are missing after using keyboard in other app

### ISSUE THREAD

**Issue by Alexey1100** [blinksh/blink#1259]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
v13.90.3 (TestFlight)
iPadOS 14.7.1

### Describe the bug

Steps to reproduce:
- Close Blink
- Use onscreen keyboard in Safari
- Open Blink

![image](https://user-images.githubusercontent.com/10757562/129453385-94837890-4df4-40d2-8bb2-14a2ed965187.jpeg)

**Comment by carloscabanero** [comment]
We fixed a bunch of bugs on keyboard for 14.0 and 14.0.3. This should be gone.
