### ISSUE TITLE
ssh Socket error: No such file or directory

### ISSUE THREAD

**Issue by aizenolly** [blinksh/blink#1262]
Blink: v13.5.12.262. Mar  3 2021
iPad 2021 Pro after up to 14.7.1(18G82)

Before update all works good, after update get issue:

blink> ssh -vvv my_host
ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_socket_exception_callback: Socket exception callback: 2 (2)
ssh_socket_exception_callback: Socket error: No such file or directory
ssh_connect: current state : 9

Socket error: No such file or directory

**Comment by Blogostef** [comment]
I face the same issue with iPadOS 14.7 (18G68)

**Comment by carloscabanero** [comment]
This is usually that the host is not accessible for some reason. Have you tried pinging it? Also, I would recommend moving to the TestFlight version (you can signup at community.blink.sh). We have been fixing a lot of bugs there towards a new release, and that may also help to have better feedback.

**Comment by carloscabanero** [comment]
Closing here
