### ISSUE TITLE
ssh-copy-id cannot be used from command history

### ISSUE THREAD

**Issue by rrgeorge** [blinksh/blink#1264]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- **Using testflight version**
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

13.90.3.316
### Describe the bug
After running `ssh-copy-id` you cannot call the command from history, because all the spaces have been turned into non-printable characters.

Run the command `ssh-copy-id id_rsa hostname`,
Press UP,
The command is now `ssh-copy-idrsa_hostname  `

To recall the same command

<details>
  <pre>
blink> ssh-copy-id id_rsa ra-horakhty
SSHSession:DEBUG:Connecting to --REDACTED-- port 22.
Connected to --REDACTED--
SSHSession:DEBUG:Server host key: --REDACTED--
SSHSession:DEBUG:Authenticating as --REDACTED--
SSHSession:DEBUG:Attempting authentication with publickey.
SSHSession:DEBUG:Authentication succeeded.
SSHSession:DEBUG:ssh_session_start: channel created
SSHSession:DEBUG:sending command: sh -c umask 077; test -d ~/.ssh || mkdir ~/.ssh ; cat >> .ssh/authorized_keys; test -x /sbin/restorecon && /sbin/restorecon .ssh .ssh/authorized_keys
SSHSession:DEBUG:exec request accepted
SSHSession:DEBUG:session finished with code 0
blink> ssh-copy-idid_rsara-horakhty
ssh-copy-id: command not found
blink>
</pre>
</details>

**Comment by carloscabanero** [comment]
Fixed for 14.0
