### ISSUE TITLE
Does the iOS app have a way to save commands and sync across devices?

### ISSUE THREAD

**Issue by Deihmos** [blinksh/blink#1265]
There is no trial so I can’t test it before purchase. Does this app have the ability to save frequently used commands and sync across devices? Thanks.

**Comment by carloscabanero** [comment]
Hi! We currently do not synchronize commands between devices. This is a feature that we get once in a while, so we may work on it at one point.

If you are interested to try out Blink, you can sign up for our community version on community.blink.sh

**Comment by NatashaKits** [comment]
Hi! We're doing some housekeeping and forgot to comment on and close this issue.
This feature was developed, here is the link about it https://docs.blink.sh/basics/snips
If you have any questions again, just reach out.
