### ISSUE TITLE
Items greyed out in link-files menu

### ISSUE THREAD

**Issue by albertquiroga** [blinksh/blink#1267]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink version: v13.5.12.262
iOS version: iPadOS 14.8

### Describe the bug

When using the `link-files` command, some filesystem entries like OneDrive are greyed out and therefore unusable even though they can be accessed regularly through the Files app

![IMG_0062](https://user-images.githubusercontent.com/5863660/133381483-96775b66-3a3e-42da-b918-0861537b0685.png)

**Comment by carloscabanero** [comment]
This, if I remember, is actually on their side. They need to enable a flag so that their files are made available to edit in place by other apps.

**Comment by albertquiroga** [comment]
Thanks for replying Carlos. Unfortunately I don't think that's correct, as I can use OneDrive for instance with any other files-API-enabled app like Lightroom, Documents or pretty much anything. It's only Blink that doesn't let me open it
