### ISSUE TITLE
Caret on keyboard toolbar doesn’t work for mosh escape

### ISSUE THREAD

**Issue by rrgeorge** [blinksh/blink#1268]
### Checklist

- [ x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ x] Read the [docs](http://blink.sh/docs/)
- [ x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
Blink 13.90.3.316
iOS 15

### Describe the bug
The caret on the smart key toolbar does not work for the mosh escape (ctrl+^).

The caret key on the smart toolbar should function for the mosh escape.

**Comment by carloscabanero** [comment]
Same goes for the underscore on top of the caret. It works with the regular keyboard, but not toolbar.

**Comment by carloscabanero** [comment]
Fixed, should be up and running on next TF.
