### ISSUE TITLE
List of all hosts / organisation

### ISSUE THREAD

**Issue by git-eri** [blinksh/blink#1271]
I think of a quick command to list all your saved hosts. I have alot hosts configured and cannot remember their names easily with currently about 20-25 hosts. Maybe there is a way to list all hosts in a manageable way, not just printing them seperated with spaces (would still be enough in the beginning.

It also could be handy to organise the hosts in folders to keep track of them and not loosing sight. And then list all hosts like a tree folder structure.
Just some thoughts i got using this awesome tool named blink...

**Comment by yury** [comment]
We now support search in hosts, also all hosts saved to generated file ~/.blink/ssh_config. Would it be enough?

**Comment by carloscabanero** [comment]
Closing as this one's been hanging here for a while. We support search and there is #1090 for groups.
