### ISSUE TITLE
MacOS scroll reversed when in alternate buffer

### ISSUE THREAD

**Issue by kjmph** [blinksh/blink#1279]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

I'm running Blink `Version 13.5.15 (264)` on an M1 Mac. I am using a mouse though, I don't have a trackpad.

### Describe the bug

When in alternate buffer mode, like in Emacs, the scroll down goes up, and the scroll up goes down. This is with natural scrolling turned off in settings.

I would expect that the cursor would move up or down in response to the scrolling. The actual mouse buttons detected are mouse-4 when going down and mouse-5 when going up.

I'm able to fix this, so both the iPad and Mac feel natural with scrolling. However, I can't run my own copy of Blink since the app signing won't let me access the same iCloud provision (and I store my hosts in iCloud fo access across my devices). I was hoping I could see this reflected up-stream?

Here is the patch I applied:

```patch
diff --git a/Blink/WebKit/WKWebView.swift b/Blink/WebKit/WKWebView.swift
index df41fe4..2fee65e 100644
--- a/Blink/WebKit/WKWebView.swift
+++ b/Blink/WebKit/WKWebView.swift
@@ -353,7 +353,16 @@ extension WKWebViewGesturesInteraction: UIScrollViewDelegate {
       
       let point = _scrollPoint ?? _scrollPointTrackpad ?? CGPoint(x: scrollView.bounds.size.width * 0.5, y: scrollView.bounds.size.height * 0.5)
       
-      _wkWebView?.evaluateJavaScript("term_reportWheelEvent(\"wheel\", \(point.x), \(point.y), \(0), \(dY));", completionHandler: nil)
+      var isiOS14 = false;
+      if #available(iOS 14, *) {
+        isiOS14 = true;
+      }
+
+      if isiOS14 && ProcessInfo.processInfo.isiOSAppOnMac {
+        _wkWebView?.evaluateJavaScript("term_reportWheelEvent(\"wheel\", \(point.x), \(point.y), \(0), \(-dY));", completionHandler: nil)
+      } else {
+        _wkWebView?.evaluateJavaScript("term_reportWheelEvent(\"wheel\", \(point.x), \(point.y), \(0), \(dY));", completionHandler: nil)
+      }
     }
   }
   
```

**Comment by carloscabanero** [comment]
Thanks a lot for the patch!! I was fighting with this myself. I will try to push it for this version ;)
