### ISSUE TITLE
Unicode characters mess up rendering in non-Menlo fonts

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#128]
I found that "wide" unicode characters shift the rest of the line. An example is the unicode "X" that I have to indicate an error in vim in the screenshot below:

![image](https://cloud.githubusercontent.com/assets/112306/18603280/1a660fc8-7c3e-11e6-8ec0-c9bad5da2b14.png)

Meanwhile, the cursor is not shifted: I pressed 'ga' in vim to show the info about the character under the cursor (bottom left corner), and it's showing a space, not 'T'. This makes it quite hard to work in this instance.

The problem occurs with both Source Code Pro, and Roboto Mono, but not the default Menlo font. Possibly related to #122?

**Comment by carloscabanero** [comment]
Chances are it might also be an issue with the specific font patching. Can you send me one that you know works for you and has the bold, etc... variants? The github powerline repo isn't patching bold, etc... for some of the fonts. We might just include different ones (except for Source Code Pro, that I'm starting to love :D)

**Comment by goerz** [comment]
I'm not quite sure what you mean. Do you mean which font I use on my laptop, e.g. in iTerm? That would be "Menlo Regular for Powerline". If I recall correctly it's something that I patched myself a few years ago.

As far as I understand there's no way to get user-defined fonts into Blink at this time, which would allow me to test for "working" fonts. Is this correct?

**Comment by carloscabanero** [comment]
This, I think, might be an issue with my font patches. I will try to fix it but we will enable custom themes and fonts too.

**Comment by carloscabanero** [comment]
Mentioned it on the other thread too. I have updated HTerm on the RAW version, and they seem to have fixed the issue. Let me know if you find anything so we can give them some feedback too :)

**Comment by carloscabanero** [comment]
Closing here as character width has been fixed, but still keeping an eye on #426.
