### ISSUE TITLE
Multiple Shells

### ISSUE THREAD

**Issue by j4ys0n** [blinksh/blink#1282]
Can we have multiple shell instances? 2-4, tiled shells would be awesome on the iPad Pro!

**Comment by snan** [comment]
Already works.

**Comment by j4ys0n** [comment]
@snan mind saying more? how can multiple tiled shells be achieved?

**Comment by snan** [comment]
On OS 14, have blink open. Then, from the icon bar att the bottom of the screen, hold and drag out another blink icon side by side with the first. You can also have a browser or other app instead. You can have them tiled side by side, or slid over. (Each with multiple tabs inside that you can switch between by swiping.)

On OS 15, that works but there is an additional way: tap the three buttons at the center top  of the screen.

Also, unrelated to all of that, there are, I've heard, a program called [tmux](https://github.com/tmux/tmux/wiki/Getting-Started) that can tile inside the terminal. This, I would guess, you'd run on your server. I've never tried it; I use Emacs which already has a split window mode.

**Comment by snan** [comment]
![IMG_0288](https://user-images.githubusercontent.com/309417/140638182-92d13b35-0108-4244-b8e0-38a3d6e9d5d1.png)

**Comment by j4ys0n** [comment]
right - yes i'm aware that you can do it with iOS features, but it would be nice to have that contained within the terminal app. or have the ability to install things like tmux easily.

**Comment by carloscabanero** [comment]
We may do this in the future, but with Tmux or Screen on the server things are already pretty good. Closing for now.
