### ISSUE TITLE
can’t show fontcase instelled font

### ISSUE THREAD

**Issue by ghost** [blinksh/blink#1285]
### Checklist

- [ x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ x] Read the [docs](http://blink.sh/docs/)
- [x ] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iOS 15.0.1 blink 13.5.14.246
### Describe the bug

I use fontcase install a .otf font, “pages” app can show my font,but blink can’t show.

https://docs.blink.sh/basics/customize

**Comment by bergtholdt** [comment]
Same here with some ttf Nerdfonts. They work in Pages, but are not shown in blink 14.0.3.361, iPadOS 15.1.

**Comment by carloscabanero** [comment]
In order for fonts to work in Blink, the "font" needs to identify itself to the OS as a Monospaced font. Sometimes, specially with Nerd fonts that are patched, that is rewritten (and some fonts are actually not monospaced anymore as some characters are actually wider).

We have a gallery, but maybe it would be a good idea to create another "Fonts Community", where people can add the tried and tested ones.

**Comment by remiconnesson** [comment]
Same here with Comic Mono from Toshi Omagari :( How could we make it work?

**Comment by carloscabanero** [comment]
Although iOS now kinda “supports” installing fonts, the process is still a pain and unfortunately in some cases you depend on the font description to the os. 

The “recommended” way to install fonts inside Blink is to still do it through a CSS. This has now been greatly simplified with tools like https://hellogreg.github.io/woff2base/. Upload it as a Gist, or even better yet, add it to our fonts library and then just pass the URL to Blink.

  https://docs.blink.sh/advanced/creating-fonts-and-themes.

**Comment by remiconnesson** [comment]
> Although iOS now kinda “supports” installing fonts, the process is still a pain and unfortunately in some cases you depend on the font description to the os. 
> 
> 
> 
> The “recommended” way to install fonts inside Blink is to still do it through a CSS. This has now been greatly simplified with tools like https://hellogreg.github.io/woff2base/. Upload it as a Gist, or even better yet, add it to our fonts library and then just pass the URL to Blink.
> 
> 
> 
>   https://docs.blink.sh/advanced/creating-fonts-and-themes. 

Thanks for tool and guidance, it worked! 

I had to convert the font to .otf to .woff2 first to then use the tool, and then it worked :) So happy thanks

**Comment by carloscabanero** [comment]
I can confirm this is working with macOS on our tests after installing proper fonts, so not an issue on our side. So yeah, if you have a font file don't even try to fight the OS, just convert it to CSS and continue with your life. Closing here.
