### ISSUE TITLE
the update to v14 seems to have wiped all my keys

### ISSUE THREAD

**Issue by sungo** [blinksh/blink#1289]
12” 2021 iPad Pro, running iOS 15, and latest App Store version. I don’t think there’s anything y’all can do but, when the app store updated blink for me, all my keys disappeared. They’re still listed in the hosts configs, until I click through to the list, but they’re not in the keys menu and ssh-add doesn’t know about them. 

Also, at the same time, the known_hosts file got blanked. It feels like iOS decided to burn whatever local storage blink uses. 

Again, don’t think y’all can do anything about it but I figured you (or folks doing google searches) might want to know.

**Comment by yury** [comment]
@sungo do you can your old files at ~/Documents/.blink ?

**Comment by sungo** [comment]
@yury the history file has history from before the upgrade. And yes, lookie there, it seems the keys file might have my old keys in there.  How do I get them out of there?

**Comment by yury** [comment]
Copy them from `~/Documents/.blink` to `~/.blink` and restart the app. (Kill it with task manager).

After that keys should be in Config.

**Comment by sungo** [comment]
🎉  That got them back! Thank you.

Quick Q. Y’all support SE keys now. If this were to happen again down the road, would this process also recover an SE key?

**Comment by yury** [comment]
So, 3 things are happening here.

1. iOS 15 pre launch app or launch app in background but without file system access. So some users from time to time got their settings “reset”  (loaded empty) (a).
2. We change file structure to support more features
   1. Before home folder was App/Documents and iCloud was linked there.
   2. After we set home folder Containers/home and link Documents and iCloud there.
   3. We wrote migration for that and also fix file permissions for issue (a). After settings are saved we apply attributes to these files, so we can read them in background without issues.
3. We tested a lot these things, but your migration got failed for some reason.

So after manually copy settings back, please do tiny changes in hosts/appearance/keys so they get saved with new permission attributes too.

After that all should be safe. And SE keys too.
