### ISSUE TITLE
“CMD + ,” with additional keys row stop work

### ISSUE THREAD

**Issue by Markmaster** [blinksh/blink#1290]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Latest app and iOS version. iPhone 11 Pro. 

### Describe the bug

Until the latest major release while I use Blink on my iPhone always worked the shortcut from the keys in additional menu on the iPhone. I use CMD + , which appears right after I press CMD, so O can go to settings more quicker. Not it stopped. Only work when I use comma from Apple keyboard. This is bad for me. You just broke things that was work for me. Please fix it. 

https://user-images.githubusercontent.com/4227967/137277013-87c7bad6-9de2-4540-84dd-e077709de983.MOV

**Comment by yury** [comment]
Fixed, will be released soon.
Sorry for delay, iOS 15 breaks many things in input for us.

**Comment by yury** [comment]
Closing, feel free to reopen if needed.

**Comment by Markmaster** [comment]
I can confirm. Fixed for now. Thanks.
