### ISSUE TITLE
Blink does an annoying "refresh" with the keyboard and terminal size when returning to the app

### ISSUE THREAD

**Issue by zorinlynx** [blinksh/blink#1292]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iOS 15.0.2
Blink 14.0.1 app store

### Describe the bug

When connected to a server, if you leave Blink and return, the keyboard does a refresh, changing the terminal size a few times. This is annoying and can also cause problems if the software you're using on the remote server doesn't like the terminal resizing.

Expected behavior would be to return to Blink exactly as it was when you left it with no refreshes or terminal size changes.

I have verified that this happens with both mosh and ssh sessions, and even when there's no connection at all (Just the Blink> prompt).

Here is a video that shows the issue:

https://www.icloud.com/sharedalbum/#B0TGfnH8tkD3cv;2EA9F61F-1F11-4C76-B209-81FF52400DDC

**Comment by carloscabanero** [comment]
There is an option inside Blink to avoid this scenario. If you do a three finger tap, press "Lock", for when you know this may cause an issue on the remote app. Unfortunately, with iOS there is no way for us to do this in any other way. Apps are required to adapt to the viewport, and if we didn't then things like screenshots and all those would be really messed up. Additionally, tracking the keyboard state would not be possible.
