### ISSUE TITLE
“agent refused operation” using Blink 14 agent forwarding

### ISSUE THREAD

**Issue by clhynfield** [blinksh/blink#1293]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

- Blink 14.0.1
- iPadOS 15.0

### Describe the bug

Given that I have…
1. Upgraded to Blink 14.0.1
2. Created a new Secure Enclave key
3. Assigned this new key to a Host (i2)

When I SSH to host i2 with agent forwarding enabled,

Then I should be able to SSH to localhost successfully using the agent;

But instead the SSH fails with the error message `sign_and_send_pubkey: signing failed: agent refused operation`. 

(I was able to SSH to localhost successfully using the agent in Blink 13 just last week.)

This failure occurs with both a Secure Enclave key:

<details>
  <pre>
blink> ssh -A i2
Connected to REDACTED
Linux instance-2 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64

~ clayton@instance-2
❯ ssh-add -l
256 SHA256:UwbmVrYQ7rW5dP9MSF7NLYmgvmfo/ALOIcbrKsApYR0  (ECDSA)

~ clayton@instance-2
❯ ssh localhost
sign_and_send_pubkey: signing failed: agent refused operation
clayton@localhost: Permission denied (publickey).
  </pre>
</details>

And a regular, v14-style RSA key:

<details>
  <pre>
blink> ssh -A i2
Connected to REDACTED
Linux instance-2 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64

~ clayton@instance-2
❯ ssh-add -l
2048 SHA256:zLiM+p8o0nZQ7lN5viRD/yLH6/nYZj+9N4SnVqZc8qg  (RSA)

~ clayton@instance-2
❯ ssh localhost
sign_and_send_pubkey: signing failed: agent refused operation
clayton@localhost: Permission denied (publickey).
  </pre>
</details>

**Comment by clhynfield** [comment]
I copied the non-Secure-Enclave private key into `~/.ssh/id_rsa` on host i2 and was able to successfully SSH to localhost there without using the agent, so the key works fine locally without the agent: 

<details>
  <pre>
blink> ssh i2
Connected to REDACTED
Linux instance-2 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64

~ clayton@instance-2
❯ ssh localhost
Linux instance-2 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64

~ clayton@instance-2
❯ 
  </pre>
</details>

**Comment by carloscabanero** [comment]
@clhynfield Although you may see the key there, it is locked by the constraints in the agent, so it is only used for login. You can add that key again to the agent if you want to use it forwarded (unconstrained) with ssh-add.

**Comment by carloscabanero** [comment]
We will allow in the future the AddKeysToAgent, so it will ask for your permission, and that step will be unnecessary.

**Comment by clhynfield** [comment]
Gotcha – thanks, @carloscabanero! 

Is there any way at this point to add a key that’s not saved as a file in the filesystem, such as a Secure Enclave key?

**Comment by carloscabanero** [comment]
Of course, just do ssh-add <key_name>. It does not matter if the key is in the Secure Enclave.

**Comment by clhynfield** [comment]
Oh, that’s rad (and a little unintuitive for this old Unix nerd)! 

Worked like a charm, just had to, as you instructed, use the *name* of the SE key I’d created, rather than a filesystem path:
<details>
  <pre>
blink> ssh-add id_ecdsa
Key id_ecdsa - added to agent.

blink> ssh -A i2
Connected to REDACTED
Linux instance-2 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64

~ clayton@instance-2
❯ ssh localhost
Linux instance-2 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64

~ clayton@instance-2
❯ 
  </pre>
</details>

**Comment by carloscabanero** [comment]
Yep, so the trick is that we are now enforcing all keys to be imported inside the app, and deprecating file based ones. That is just more secure and we will be able to do more things with them in the future.

**Comment by clhynfield** [comment]
Crazy-cool, can’t wait to see how this evolves. If y’all need help updating the docs, lemme know, and I’ll try to incorporate some of the above into at least a work-in-progress PR.

**Comment by adrusi** [comment]
Hi, it doesn’t seem like `AddKeysToAgent` is supported yet — or else adding it to the host ssh config doesn’t seem to work. Is this still on the roadmap?

**Comment by carloscabanero** [comment]
Still open, we didn't really get a lot of requests for it and looks like OpenSSH was working on some changes related to that and the constraints, so decided to wait.

**Comment by carloscabanero** [comment]
This is now out on 16.1.8!
