### ISSUE TITLE
All hosts configuration lost since last update

### ISSUE THREAD

**Issue by robinfdx** [blinksh/blink#1294]
### Checklist

- [X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iPad Mini 2021
iOS 15.0.2
Blink Version 14.0.1.352 

### Describe the bug

Since I updated the app with the last App Store version (14.0.1.352 ), I lost all of my host configuration.
I've try to close App -> no ok
I've try to reboot device -> no ok.

When i check the key configuration, I have all my configuration and work with ssh command.

![image](https://user-images.githubusercontent.com/1908692/137443405-8808029b-b952-4e44-a6b9-44ee9295e244.png)

**Comment by yury** [comment]
Hello @robinfdx 

See #1289 for details and fix.

We don't know why it happening yet. Did you have autoupdates on? or you manually update from App Store?

**Comment by vvv** [comment]
So [the trick ](https://github.com/blinksh/blink/issues/1289#issuecomment-942982547)is to copy ~/Documents/.blink to ~/.blink and restart the app (kill it with task manager).

<details>
<summary>The command, FWIIW</summary>

```sh
mkdir -p ~/_attic &&
    mv ~/.blink ~/_attic/ &&
    cp -r ~/Documents/.blink ~/
```

</details>

**Comment by robinfdx** [comment]
Hello @yury 

Thanks for your reply, and sorry I had not seen this issue.

In this iPad it's manual update (pull to refresh in the App Store).

I confirm that it works very well

**Comment by herjazz** [comment]
Can confirm same issue on iPad Pro

**Comment by sfatula** [comment]
Same issue, auto updated.

**Comment by yury** [comment]
@sfatula you auto updated to v14.0.2? Or v14.0.1?

**Comment by sfatula** [comment]
14.0.1, I see there is another update now. Mine was an iPad Pro 12.9

**Comment by yury** [comment]
Yep, 14.0.2 should be safer with updates…

**Comment by akamathdev** [comment]
I had this problem too when the app updated to 14.0.1 overnight as part of auto updates. Noticed this thread and manually upgraded to 14.0.2 and everything was back.

**Comment by kokofirstlove** [comment]
ΣℓĢÂ฿ẹℓᵧ

في الاثنين، ١٨ أكتوبر ٢٠٢١ ٢:٢٨ ص Aditya Kamath ***@***.***>
كتب:
