### ISSUE TITLE
Two finger swiping (left & right) doesn't work well

### ISSUE THREAD

**Issue by rekendahl** [blinksh/blink#13]
Swiping left and right to switch tabs doesn't work reliably. I can only successfully swipe right to go to an older tab. Swipe left only seem to move the active tab around and even sometimes leaving the window in a weird position:

![image](https://cloud.githubusercontent.com/assets/1612072/14268328/aa172b2a-faa7-11e5-9ebc-b8f60a30a585.png)

I can get out of this weirdness with a slight pinch too zoom gesture. 

In general I would like to disable the moving/zooming of the active terminal and leave swiping for swapping tabs.

**Comment by carloscabanero** [comment]
This one should also be fixed in the new version. Please let us know if you encounter it again. Will keep it open until that.

**Comment by rekendahl** [comment]
This seems to work about the same as before. Two fingers left/right work one or a couple of time but once a she'll get into resizing mode I can't seem to get out of it.

**Comment by carloscabanero** [comment]
Got it! So the gesture to move should be a single finger swipe. But yes, two fingers does something strange,  related to the iOS control. I will review what is causing this mess.

Thanks!



On Mon, Apr 11, 2016 at 3:01 PM -0700, "Robert Ekendahl" <notifications@github.com> wrote:












This seems to work about the same as before. Two fingers left/right work one or a couple of time but once a she'll get into resizing mode I can't seem to get out of it.

**Comment by carloscabanero** [comment]
This should be also fixed on next version.

**Comment by carloscabanero** [comment]
This should be fixed on v0.714. I will let you test it as I couldn't always replicate it. Please let me know if it doesn't. 👍

**Comment by BinaryBen** [comment]
I don't know about @rekendahl's experiences, but it still seems very buggy to me. It doesn't always register that I am trying to change, or doesn't always slide across smoothly/consistently.

**Comment by carloscabanero** [comment]
Can you take a screenshot or a quick video of what you are experiencing? It seems fine for me even in the simulator, but I'm too biased right now.

**Comment by BinaryBen** [comment]
After mosh crashed (wouldn't reconnect when I switched wifi connections), I tried to close the prompt to get a new one as all I had was the "Bye!" message after the standard outputs. I tried to close it with two fingers swiping down which worked as far as fading everything down and to black (though, not reliably), but didn't go further (see screenshot).

These are the sorts of bugs I am experiencing with the guestures as an example. I will try and get a video if I remember.

![image](https://cloud.githubusercontent.com/assets/12827556/16421301/0ec340dc-3d87-11e6-8ac1-694eb60d7d14.png)

**Comment by carloscabanero** [comment]
Don't worry about taking a video. Two fingers down not allowing to reconnect has been easy to replicate. Gonna fix. Thanks a lot for the report!

**Comment by carloscabanero** [comment]
This should be fixed on v0.916. Please let me know & feel free to reopen! :)

**Comment by root42** [comment]
Swiping still is very unreliable for me. I think I can't reopen this ticket, so will probably open a new one.

**Comment by yury** [comment]
Hi @root42,
are you swiping with two fingers? You can swipe with one finger.

**Comment by root42** [comment]
Mind. Blown. Thanks!!
