### ISSUE TITLE
Same window on iPad and external display when using AirPlay

### ISSUE THREAD

**Issue by c0ppelius** [blinksh/blink#1300]
**Describe your question**
I've read the docs and come to the following conclusion: it is not possible to simultaneously display the same Blink window on the device and the external display when AirPlaying. Is this correct? If not, how is this achieved? 

**Use case**
The screen is behind me and the device is in front of me, eg in a lecture. 

Thanks for any and all help.

**Comment by carloscabanero** [comment]
You need to set the iPad with mirror display. I think that is now part of the control center dashboard, once you have the iPad connected, you should be able to ask for mirroring.

**Comment by c0ppelius** [comment]
Thanks for reply! To connect to the Apple TV, I follow the directions [Mirror your iPhone, iPad, or iPod touch to a TV](https://support.apple.com/en-us/HT204289). When I do this, there are two windows open in Blink. One for the Apple TV and one on the iPad. I cannot get one to display to both iPad screen and the Apple TV output at the same time. 

Is this what you mean by mirroring? If not, please correct me.

**Comment by carloscabanero** [comment]
I have not tried to do mirroring instead of extension with the AppleTV, but let me try today and let you know.

**Comment by yury** [comment]
@c0ppelius there is blink setting for that. `config` command -> Appearance -> "External Display". Set it to mirror.

I'm closing this issue. Feel free to reopen if needed.

**Comment by c0ppelius** [comment]
Wonderful! Thanks.
