### ISSUE TITLE
Shortcut offset bar on portrait mode iPad Mini 

### ISSUE THREAD

**Issue by robinfdx** [blinksh/blink#1301]
### Checklist

- [X ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X ] Read the [docs](http://blink.sh/docs/)
- [X ] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iOS 15.0.2
Blink 14.0.2.354 (latest stable available on appstore)
iPad Mini 2021

### Describe the bug

Sometime (without understand why and reproduce this problem) i have a shortcut offset bar on portrait mode iPad Mini, for fix this problem i need to close app and reopen.

![73A56296-6B1A-4AD3-9944-D5D2A75B5CDC](https://user-images.githubusercontent.com/1908692/138491991-140f73f9-8c66-47fa-ae13-4e12c617f94a.png)

![9EAB64A5-0413-47B8-A907-C7B7E7DE876F](https://user-images.githubusercontent.com/1908692/138492048-b7fbc38a-3b43-42d9-bc05-c793ab4b7ed8.jpeg)

**Comment by carloscabanero** [comment]
This should have been fixed on latest release 14.0.3
