### ISSUE TITLE
Adobe fonts not available

### ISSUE THREAD

**Issue by mmphys** [blinksh/blink#1302]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink v14.0.2.354, iOS 15.0.2, Creative Cloud 6.2

### Describe the bug

Installed Adobe Mono fonts "BC Sklonar" and "Dico Mono Slab", which show as installed under settings, general, fonts, but these do not show up under settings, Appearance, Fonts in Blink config.

Fonts available

![image](https://user-images.githubusercontent.com/43034299/138521950-4c79d69d-4c3c-4df2-9f17-41452c9701a4.png)

![image](https://user-images.githubusercontent.com/43034299/138522021-7fdec79f-b6b5-49f4-90fa-32ba03c5eaf9.png)

**Comment by carloscabanero** [comment]
Hi! I do not have access to those fonts and I’m not sure how they are declaring themselves to the system. What we do is to request all the monospaced fonts installed. So my guess is that they are not identifying themselves as such, despite what the name may say.

If you have access to the fonts, I would try to install them separately. Sorry cannot really help much more than this.
