### ISSUE TITLE
SSH uses incorrect hostname when user contains an @

### ISSUE THREAD

**Issue by erwinvaneyk** [blinksh/blink#1303]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink: v14.0.2.354
iOS: 15.0

### Describe the bug

1. `ssh foo@bar@validhost.com` or `ssh 'foo@bar'@validhost.com`

Result/error: `Error connecting to argus-erwin-482.com. connError(msg: "Socket error: No such file or directory")`

It should connect to `validhost.com` with the user `foo@bar`. On both MacOS and CentOS' `ssh` is this is handled correctly.

**Comment by carloscabanero** [comment]
Hi! Yeah, it looks like we are not parsing that properly at the moment. Marked as a bug. As a workaround, you can use the -l flag that should let you pass a user in any format.
