### ISSUE TITLE
I don't know how to use command sftp

### ISSUE THREAD

**Issue by m8458246** [blinksh/blink#1304]
I use the command "sftp file user@server:~/sftp/" upload to server, showed "Copy failed. Fail(msg: "SFTP server: Permission denied")".
Then I use "sftp user@server:~/sftp/test ." download form server, it's ok.
Next I use other software(Mobaxterm on windows) test my sftp setting, it no problem download and upload. I also use a software on iPad which support sftp, no problem at all.
Now I don't know how to fix it, can someone help me? I don't know what the problem is.

**Comment by carloscabanero** [comment]
Hi! Sorry, not sure I follow exactly what the issue is.
To copy from local to remote
`sftp <source_path> <remote>:<remote_path>`
To copy from remote to local
`sftp <remote>:<remote_path> <local_destination> `

**Comment by m8458246** [comment]
My sftp setting in /etc/ssh/sshd_conf : "
Subsystem sftp internal-sftp
UsePAM yes
Match User ftpuser
	ChrootDirectory /home/ftpuser/
	ForceCommand internal-sftp
	AllowTcpForwarding no
	X11Forwarding no
"
Can I change some command to fix it?

**Comment by Arbitrageur** [comment]
I have the same issue.

Did you solve the problem?

I can log in the remote machine via ssh.
```
ssh remote
```

but scp or sftp failed.
```
touch test
scp test remote:~
```

Output:
```
Copy failed. Fail(msg: "SFTP server: Permission denied")
```

I tried it with '--verbose' option.
But it gives no information.

**Comment by carloscabanero** [comment]
Will look into why `verbose` is not giving any output.

It looks like you are connected and already contacting the SFTP server. There are a bunch of things that may be going on, like maybe the SFTP server does not have access to that location, etc...
Another thing you can try is to enable that host over the Files.app, just following this guide: https://docs.blink.sh/advanced/files-app
That can give us also more output if you follow the instructions, so we get to know what is going on:

> A log is automatically kept on .blink/fileprovider.log. If you need more information, set the LogLevel on the [SSH Config for the Host](https://docs.blink.sh/basics/hosts#ssh-config).

**Comment by Arbitrageur** [comment]
OK.
I changed the sftp config, changing root directory to home directory.
Now I can scp files.

And, also, I can access my home directory via Files.app.

But I can't open my home directory or any subdirectories in code.

I tried
```
code remotemachine:~
```
and
```
code remotemachine:~/projects/something
```

But Code shows no contents.

This is part of blinkCode.log file.
```
[info] Feb 17 2022, 21:50:12 FileSystem Registered mount 7 for xxx at blinksftp://remotemachine/~/projects/email-downloader
[info] Feb 17 2022, 21:50:14 FileSystem De-registering mount 7
```

**Comment by yury** [comment]
@Arbitrageur have you install blink-fs extension in vscode?

**Comment by Arbitrageur** [comment]
That's the missed part!

Now it works!
