### ISSUE TITLE
Does Blink no longer consider ssh default identities?

### ISSUE THREAD

**Issue by melomac** [blinksh/blink#1305]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Up-to-date Blink shell on up-to-date iOS 15 with multiple devices.

### Describe the bug

After some time not using Blink shell, I just noticed Blink is asking me for my password to access remote hosts on all my devices.

Investigations tend to reveal Blink isn't considering the default identities in `~/.ssh` to authenticate. I prefer using the default identity feature rather than storing my keys in Blink, so I can share the config between devices and keep per-devices keys.

Also, this doesn't look like specifying the full command `ssh -i ~/.ssh/id_ed25519 user@host` works either as ssh keeps asking me for a password 🤯

Is that regression expected?

**Comment by carloscabanero** [comment]
Hi! The change as you noticed, is that we do not support file based keys anymore, and require them to be imported inside Blink. You can still name them with the same standard name and they will be taken by default.

Reason for the change is that we were maintaining multiple subsystems for the keys, and having the keys as part of Blink allows us to offer them on other parts as well, like the new FileProvider, etc

Take into account imported keys are safer as well, as they are kept encrypted by the SecureEnclave, versus just files.

Sorry for the inconvenience. Will keep this to update the docs accordingly.

**Comment by melomac** [comment]
Oh! FileProvider is coming to Blink?! Neat. Apologies as I assumed keys would get synced. So no regression, just a better, safer, implementation: hat tip to the team.
