### ISSUE TITLE
SSH Multiple Ports Forwarding Stopped Working

### ISSUE THREAD

**Issue by zaripych** [blinksh/blink#1306]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581) 
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues) (looked at issues since September as I feel this one is related to recent SSH changes in v14)

### Configuration

`iOS 15.0.1`
`iPad Pro (gen 5)`
`v14.0.2.354`

### Describe the bug

I previously successfully been using a command to connect to my dev server and forward back a bunch of ports using single command. The command would look like this:

`ssh -p xx -L 3000:localhost:3000 -L 3001:localhost:3001 ... user@ip` - note that multiple port forwards passed.

The command would work perfectly when combined with `geo start` and give me all the web apps that I needed to access in Safari browser. They would open-up just fine.

After recent upgrade I started having issues where the ports weren't forwarded. I digged up a little and it seems only the latest forward works, while all the other forwards specified - do not. This looks like a regression.

### Working around the bug?

UPD: I've noticed something about being able to open forwards for existing connections, but the documentation on the subject seemed a little lacking. For anyone who also need multiple connections here is the workaround:

In first terminal:
```
ssh user@ip
```

In second terminal:
```
ssh -O forward -L port1:localhost:port1 user@ip
ssh -O forward -L port2:localhost:port2 user@ip
...
```
👍

UPD2: After the above workaround, even if you exit in the first terminal - closing the connection. The forwards keep working. Attempts to run `ssh -O stop ...` print out messages that `No connection for xx to control`

**Comment by carloscabanero** [comment]
Sorry about that. This is a regression caused from my side. Will fix soon.

**Comment by carloscabanero** [comment]
This was already fixed on previous TF. Also, we now support tunnels as part of ssh config settings, even dynamic forward.
