### ISSUE TITLE
SCP no longer working

### ISSUE THREAD

**Issue by Kezzsim** [blinksh/blink#1307]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug

SCP has stopped functioning for me within the past 3 months, I used to use it all the time to grab videos from YouTube and put them in my files but now when I try all I get is "File or directory not found". I know Blink is at fault here because I can run the command on a PC that's on the same network and it works fine like so:
<img width="856" alt="Screen Shot 2021-10-26 at 12 32 42 PM" src="https://user-images.githubusercontent.com/15878154/138922676-46cd30b8-70ad-42b6-bd6f-6ce0d30fe992.png">

But in Blink ever since the end of September this is all I get 
(running both the aliased command AND the exact same one I ran on the computer):
![IMG_6085](https://user-images.githubusercontent.com/15878154/138922921-ad6fd735-15cc-4b3e-804b-174a402440fd.jpg)

I re-ran the setup I followed to get SCP working, including logging into both hosts via SSH2 in order to get my keys regenerated / updated or whatever. That has not changed the output. 

So what changed in Blink that would cause this to happen?

**Comment by carloscabanero** [comment]
Hi Kari, we rewrote SCP, none of the ssh2 stuff is needed anymore. The (known) issue is that the destination needs to be the path, instead of the name of the new file. We will be changing this soon, I’m marking it as WIP.

So your line should be something like
`scp kezz@anemone.local:Public/file.mp4 .`

If you are on latest TestFlight, you can now also use it within the Files.app and just drag and drop or even watch if from there.

**Comment by Kezzsim** [comment]
Thank you @carloscabanero that was it
When I specify the location it can't just be the file name now, it has to be a destination!

It's working again just fine

**Comment by carloscabanero** [comment]
I’m reopening as this is actually a regression, and what you did should have worked. We should have this fixed soon.
