### ISSUE TITLE
which which command not found

### ISSUE THREAD

**Issue by egberts** [blinksh/blink#1308]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink 14.0.2
iOS 14.8
iPad 7,11

### Describe the bug

- Start Blink Shell app.
- Type in `which which`
- get an error.

show us the location of `which` binary file.

![image](https://user-images.githubusercontent.com/10352354/138992729-b37e01ac-3011-41b3-92ac-383413aeef7d.png)

**Comment by carloscabanero** [comment]
There are no binaries in Blink, so no way to really show any locations. Which does not make sense within our sandbox.
