### ISSUE TITLE
Tapping causes “Blink pasted from …” notification

### ISSUE THREAD

**Issue by dxmh** [blinksh/blink#1311]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

* iPadOS 15.0.2 (19A404)
* Blink: v14.0.2.354 (App Store). Oct 16 2021

### Describe the bug

Tapping the screen sometimes triggers the OS to show a “Blink pasted from …” notification.

The video below shows a three-finger single-tap on the background, followed by a one-finger double-tap on the prompt. In this example, both taps cause the notification to appear. However, in general use it seems to happen less consistently.

https://user-images.githubusercontent.com/60922914/139456950-c67d51c9-ba30-4087-8e9a-324d8e61db1d.mov

**Comment by yury** [comment]
Fixed in v14.0.4. Release should be out soon.

**Comment by yury** [comment]
I'm closing this, feel free to reopen if needed.
