### ISSUE TITLE
supporting scp -o

### ISSUE THREAD

**Issue by yoni206** [blinksh/blink#1313]
I would like to be able to run `scp` with the `-o` option, in order to provide a sever for the `ProxyJump` ssh option. Currently `-o` is not supported.

**Comment by carloscabanero** [comment]
We do not support a generic -o, but we do support ProxyJump now. I don't think we will be supporting -o options as that is complicating the command itself a lot. Unfortunately with sftp or scp we need to replicate the configurations and it is a bit of a pain.

If anyone needs -o, feel free to reopen.
