### ISSUE TITLE
Is MOSH bound to a single network interface?

### ISSUE THREAD

**Issue by zaripych** [blinksh/blink#1316]
**Describe your problem**
*MOSH*
I'm not sure if this is a bug or not. I've got a public IP I'm connecting to (but through a registered DNS). If I connect with my Wi-Fi down (ie using 4g/5g) - connection survives even as I move around the city long distances. But when I connect to a Wi-Fi the connection stops with a message "No route to host". The moment I turn off Wi-Fi connection comes back.

Sometimes it seems reasonable that I connect in an office with Wi-Fi and then I jump to train and as I travel back home I still want the connection to just work - but unfortunately it doesn't. When I'm back home I want it to pickup my home Wi-Fi.

(For some people the above might be actually unreasonable - they might say "read a book in the train" :) - but I'm spoiled like that).

It feels like Blink (or Mosh) remembers the network interface it was connected to and doesn't try to change it later on. Can this be possibly fixed in Blink?

**What you have tried and your configuration**

Weirdly, with my Wi-Fi disconnected and an active mosh session working in another tab I do `ping` and get this:
```sh
blink> ping XXX.xxx.XXX.xx
PING XXX.xxx.XXX.xx (XXX.xxx.XXX.xx): 56 data bytes
ping: sendto: No route to host
ping: sendto: No route to host
Request timeout for icmp_seq 0
ping: sendto: No route to host
Request timeout for icmp_seq 1
ping: sendto: No route to host
Request timeout for icmp_seq 2
```

Then I connect to Wi-Fi and do it again:
```sh
blink> ping XXX.xxx.XXX.xx
PING XXX.xxx.XXX.xx (XXX.xxx.XXX.xx): 56 data bytes
64 bytes from XXX.xxx.XXX.xx: icmp_seq=0 ttl=62 time=11.290 ms
64 bytes from XXX.xxx.XXX.xx: icmp_seq=1 ttl=62 time=7.091 ms
64 bytes from XXX.xxx.XXX.xx: icmp_seq=2 ttl=62 time=9.320 ms
...
```

BUT, my `mosh` connection is dead in another tab. 

**Expected behavior**
It should work across all network interfaces and switch between them?

**iPad Pro (5th gen)**
 - OS: 15.0.2
 - Version: v14.02.354

**Workaround**
I can setup two tabs, and then do some trickery on server side to share same buffers in both tabs (tmux/emacs) - one with Wi-Fi and another without Wi-Fi and switch between them, but I can imagine my other tab constantly pinging and trying to reach the server - draining my battery (possibly).

**Patreon link?**
Is there a link I can donate to? I'm using this product all the time and I think it's best of all and would like to reward the maintainers.

**Comment by yury** [comment]
Hello, 

It may be IPv6/IPv4 issue. 
When you are connected via LTE - you got IPv6 address of your machine. And your WiFi setup is not configured for IPv6, so connection can't go through.

We may provide configuration for mosh to use only IPv4 for establishing connection.

**Comment by zaripych** [comment]
Hey @yury - thanks! If this can be a flag of some sorts that we pass to `mosh` and it works - sounds great to me. 
I've checked and indeed I get an IPv6 address via LTE ... if I tell `mosh` to use only IPv4 would it work though? Not sure. 🤷‍♂️

**Comment by carloscabanero** [comment]
Closing here as it is being solved as part of https://github.com/blinksh/blink/issues/1316
