### ISSUE TITLE
Can’t seem to exit on iOS

### ISSUE THREAD

**Issue by chovyprognos** [blinksh/blink#1317]
**Describe your problem**
Using tmux can't seem to exit blink. Screen is unresponsive 

**What you have tried and your configuration**
Blink on iOS using mosh to connect o Ubuntu server and opening tmux 

**Expected behavior**
Can't exit the shell in blink

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

iOS latest 

**Additional context**

**Comment by chovyprognos** [comment]
iOS 15.1

**Comment by carloscabanero** [comment]
Thanks for the report. Can you be more specific on what you mean by "cannot exit Blink"? Does that mean that you cannot detach from tmux inside Blink?

**Comment by ralyodio** [comment]
I didn’t know about the three finger click.

**Comment by ralyodio** [comment]
You can close
