### ISSUE TITLE
Files App integration doesn't support ProxyJump configuration

### ISSUE THREAD

**Issue by Bluebie** [blinksh/blink#1318]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink 14.0.3, iPhone OS 15.1.1, iPhone 12 Mini

### Describe the bug

Files app integration appears to ignore ProxyJump configurations.

I have a home server, which is not accessible to the internet, and a front end proxy, which is available to the internet. To access my home server I need to ssh ProxyJump in to the front end, then ssh in to the internal server. This works well in Blink app, but when using the new Files app integration, connections to the internal server only work when my phone is on home WiFi. It behaves as if it's ignoring ProxyJump and always trying to connect directly to a lan hostname, even when the phone is on 4g remote internet. When not on home wifi, the authentication failure screen is triggered:

![image](https://user-images.githubusercontent.com/12768/142524806-c86e72e1-e7d4-4218-9672-5e874158d72a.png)

This limitation should be documented or fixed, as it's pretty maddening trying to debug it when the in app information seems like anything which works in Blink app should work in Files app, with the advice to test an ssh connection to the machine before returning.

**Comment by carloscabanero** [comment]
Fixing...

**Comment by carloscabanero** [comment]
Done! Available on TF
