### ISSUE TITLE
Support "--no-ssh-pty" for the embedded mosh client

### ISSUE THREAD

**Issue by reggiezhang** [blinksh/blink#1319]
The embedded mosh client cannot successfully connect to mosh-server for server running Dropbear.
The workaround is add --no-ssh-pty on mosh-client side per below issues:
https://github.com/mobile-shell/mosh/issues/464
https://github.com/mobile-shell/mosh/issues/819
https://github.com/mobile-shell/mosh/pull/524

**Comment by carloscabanero** [comment]
@reggiezhang Have you tried -T option? I will add it as --no-ssh-pty as well.

**Comment by reggiezhang** [comment]
@carloscabanero Tried it before with no luck. But it works right now. Thanks!
