### ISSUE TITLE
Command + B produces no output

### ISSUE THREAD

**Issue by raamdev** [blinksh/blink#1320]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink v14.0.3.370, iPad 11 Pro, iOS 15.1, Magic Keyboard

### Describe the bug

`Command + B` does not produce any output. If I use `showkey` inside Blink and press `Command + B` on my hardware keyboard, there's simply no output. By comparison, `Command + F` works as expected.

This seems to have broken sometime recently, as I had been using `Command + B` inside Emacs (via `mosh`) until recently with no problems (in Emacs, `Command + B` executes  `backward-word`). 

Is this no longer expected to work? Is there a workaround (maybe using Custom Presses)?

**Comment by yury** [comment]
Hello.

Can you gist your ~/.blink/kb.json ?

I think, I fixed cmd+b recently, but I need to know how did you map your kb.

**Comment by raamdev** [comment]
Hi @yury, thanks for the response. Here's my `~/.blink/kb.json`: https://gist.github.com/raamdev/0d5a8bf419dce488ff5676d0ce066255

**Comment by yury** [comment]
@raamdev Yep, fix confirmed. It is not released yet. We plan to push new version to TF this week. I can send you invite to TF.

**Comment by raamdev** [comment]
@yury thanks for confirming and for all your work on this project! A TF invite would be great: `raam@raamdev.com`
