### ISSUE TITLE
Files.app SFTP « Could not canonicalize path » errors with accented paths

### ISSUE THREAD

**Issue by alexandresoro** [blinksh/blink#1321]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

App Store - version 14.0.3

### Describe the bug

I have added two folders of mine in the Files.app. Browsing is working as expected, except that I am unable to open files that belong to folders that contain an accented character.
The issue seems to happen with any such folder and does not occur with other folders.
It also seems that I cannot open files that also contain accented characters in any kind of folder, so the issue may be affecting files too.

The reported error message is the following:
« Could not canonicalize path »

As far as I can tell, using the embedded sftp command in Blink causes no trouble and I am able to properly copy such folders/files on the device.

It may be worth mentioning that the server that I am trying to connect to is a personal server using Linux that is known for having a different unicode normalization (NFC) than macOS/iOS (NFD) . I mention it as I stumbled upon similar issues in the past with other apps.

Expected behavior:

I should be able to browse and download any kind of folder and file, regardless of them having accented characters or not.

**Comment by carloscabanero** [comment]
Can you send us an example a folder that is not working? I'm trying to replicate with no luck. I suspect there may be an issue when we replicate the structure locally.

**Comment by alexandresoro** [comment]
Apologies for the delay.

I managed to replicate it with a simple structure. I have attached a simple tar.gz file that contains a single accented folder. This folder contains a single text file.

[test.tar.gz](https://github.com/blinksh/blink/files/7794400/test.tar.gz)

If i decompress it as it is on my Linux server (running Arch), I reproduce the issue described above. I tried it on two servers, with no specific configuration and have the same issue.

So, the best way to try to reproduce is to simply unzip the attached file on a server.

If you don’t manage to reproduce it this way, I suspect that it might be related to a different handling of unicode decomposition between OSes.

If you can’t reproduce with this file, I have set up a way for you to access a remote server where the issue happens with this specific archive. Let me know how I can safely provide the access, if needed.

**Comment by carloscabanero** [comment]
Thanks for getting back to us @alexandresoro, and thanks for all the work trying to replicate the issue. I was not able to replicate it on a Mac, but I could on a Ubuntu server. Working on this now...

**Comment by carloscabanero** [comment]
Fixed, will be up on next TF. Please test.

**Comment by alexandresoro** [comment]
Hi,

I tried again with version 14.0.5 from the AppStore, and the issue seems fixed.

Thanks for the quick fix!
