### ISSUE TITLE
Error Connecting: authfailed(methods: [SSH.AuthAgent])

### ISSUE THREAD

**Issue by Gex2501** [blinksh/blink#1322]
So I’m getting the error when I use Blink. I’m able to connect just fine using iTerm2 from my laptop. My server is configured for publickey only and I have verified that I’m using the right keys in my authorized_keys file. Please see the screen shot. I get different errors whether I used the configured host shortcut or full ssh command. Please see the screenshot below.

![2C8F04FC-5201-4533-AE5C-9EFC99AF1923](https://user-images.githubusercontent.com/63863/143161603-7bec7475-7620-4f17-8791-66648225f157.jpeg)

**Comment by Gex2501** [comment]
I think I fixed my own problem. Seems my server can’t handle the keys generated by blink. So I create a key using the server and imported it to blink. Now it works. Hopefully this helps someone else.

**Comment by yury** [comment]
@Gex2501 what type of key you generated in blink?

**Comment by Gex2501** [comment]
I was just doing the default that came up when making a new key. RSA 4096 bits.

-Greg
