### ISSUE TITLE
Appearance settings aren’t working anymore

### ISSUE THREAD

**Issue by AronT-TLV** [blinksh/blink#1324]
V14.0.3.370

The screen background is black even though in config I have chosen “Solarized Light” and this used to work correctly.

The solarized screen shows up for a moment and then gets overwritten by a black background.

**Comment by carloscabanero** [comment]
Could you please record a short video so we can better see what you are talking about? Thanks

**Comment by AronT-TLV** [comment]
https://user-images.githubusercontent.com/22121571/144262516-3bbf1c8a-596e-4095-bdf8-6cb86d0049b6.mp4

I open app, turn on video recording, double tap for a new terminal, you briefly see the solarized light flash on and then you get a new black screen

@carloscabanero

**Comment by yury** [comment]
@AronT-TLV can you provide a link from where you did install “Solarized Light” theme. 

Also, if you reimport your theme - will it work?

**Comment by AronT-TLV** [comment]
@yury  I got if from the Blink gallery. Reimporting it seems to have solved the issue for now. Thanks!

**Comment by AronT-TLV** [comment]
Reimporting solved the problem. Thanks for the help.
