### ISSUE TITLE
SFTP behaves more like scp 

### ISSUE THREAD

**Issue by ahesford** [blinksh/blink#1331]
The built-in `sftp` command behaves more like `scp` than the OpenSSH `sftp` command. The `scp` command should accept a source and destination (either of them remote), copying the source to the destination non-interactively. The `sftp` command should behave like an FTP client: accept a single required argument (the remote host) and open an interactive prompt that allows browsing remote and local paths and performing file management operations throughout the session.

### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

- Blink 14.0.3.470

### Expected behavior
`sftp <remote>` should open an interactive session that allows navigating file hierarchies and transferring files to and from the remote host.

**Comment by carloscabanero** [comment]
We won't do this for now. You can browse the Host inside the Files.app, which gives better integration with the rest of the OS. As for an interactive SFTP, that was developed as a showcase for the protocol and a lot of people have always opted for the simplicity of scp when dealing with the CLI. All our copy commands take that route.

**Comment by ahesford** [comment]
In that case, can you shed some light on why Files integration only shows me a "You must authenticate" dialog rather than actually showing contents, or should I open a separate issue?
