### ISSUE TITLE
Can’t add ssh keys

### ISSUE THREAD

**Issue by jesusgollonet** [blinksh/blink#1332]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug

I just purchased and downloaded Blink for the first time in my iPad 6th generation with iOS 14. I open the config panel, open Keys section. I don't have a default key. Click on the + button but nothing happens. I would expect to be able to create a new key. 

I have tried both with a hardware keyboard and iOS keyboard in case it interfered with the menus, but there's no difference.

For reference I just did the same on my iPhone SE and I can see the add key menu

**Comment by yury** [comment]
Hmm… can you screenshot that screen with “+” button?

**Comment by yury** [comment]
I may be iOS 14 relegated… will check today on simulator

**Comment by yury** [comment]
Do you have planes to upgrade to iPadOS 15?

**Comment by jesusgollonet** [comment]
![image](https://user-images.githubusercontent.com/31100/145181255-c3f5d4d7-999b-47e0-85f6-cbb686f5a4a2.png)

**Comment by yury** [comment]
Also, can you try to long press on + ?

**Comment by jesusgollonet** [comment]
Long press doesn't change anything it seems. For the record, iphone is also on 14.8.2, and it does work there. I'm upgrading to iOS 15 now

**Comment by jesusgollonet** [comment]
Update to iOS 15 fixed it on my iPad. Thanks for the prompt help
