### ISSUE TITLE
Adding certificate to key prevents connection to non-certificate host

### ISSUE THREAD

**Issue by Apreche** [blinksh/blink#1333]
### Checklist

- [ x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ x] Read the [docs](http://blink.sh/docs/)
- [ x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink version v14.0.3.370
iPad OS15.1 on an iPad Pro 3rd generation 12.9"
iOS 15.1.1 on iPhone 12 mini

### Describe the bug

1. Create a new SSH key inside of Blink. (In my case I used ed25519).
2. Copy the public key into the authorized_keys file on a remote host. We'll call this "HOST A."
3. Add HOST A to the host entries in Blink, and configure it to use the new key.
4. SSH to HOST A, it works perfectly.
5. Copy the public key to another computer and sign it using a user_ca. 
6. Copy the new certificate to the iOS device and add it to the key in the Blink shell keys config area.
7. Add a new host entry in Blink. This will be HOST B. HOST B is configured to allow connections from keys with certs signed by the ca used in step 5. The authorized_keys file on HOST B is blank.
8. SSH to HOST B. It works perfectly!
9. SSH to HOST A. It doesn't work! There is an error that says `Error connecting to HOSTNAME. authFailed(methods: [SSH.AuthAgent])`
10. Remove the certificate from the key in the Blink config.
11. SSH to HOST A. It works!
12. SSH to HOST B, obviously it doesn't work because the cert is missing.

The expected behavior is to match the way OpenSSH works. If a signed certificate is present, of course it will be used to connect to a host when appropriate. However that key can still be used to successfully connect to other hosts using non-certificate authentication methods. The cert is simply automatically used when needed, and not used when not needed.

Sorry, I wanted to capture this as text, but it was a pain to copy such a block of text from my iPad to the PC where I'm making this bug report.

![Screenshot 2021-12-10 at 10 33 12 PM](https://user-images.githubusercontent.com/5847/145662357-bb0f3778-3f7e-48f7-88c0-15f50b1a7b76.png)

**Comment by carloscabanero** [comment]
Hi @Apreche! Thanks for the report. I was taking a look at it this week, and unfortunately the solution is a little bit dirty. It is really dirty on OpenSSH already. Considering how corner case this is, do you think it would be a big hassle to consider having two keys, one with the associated Certificate and one without? I think that would actually make more sense too from a cleanliness perspective. (Personal remark: I will do it if I have to, but I hate to garble code in order to support corner cases, that then will also make things a lot more difficult to test.)

**Comment by Apreche** [comment]
@carloscabanero It's not super important to me personally that this is fixed. I'm already working around it as you suggest.

I simply tested the functionality after #653 was fixed and noticed that it did not work the same way as OpenSSH does. I absolutely believe you when you say whatever OpenSSH is doing under the hood is a mess. Thanks for taking the time to look into it.

**Comment by carloscabanero** [comment]
Let’s go with that then. Will keep it open in case we have other ideas in the future. Thanks a lot for the help.

**Comment by carloscabanero** [comment]
No news or ideas on this for a while, closing.
