### ISSUE TITLE
Custom presses involving modifier keys no longer working

### ISSUE THREAD

**Issue by peppy** [blinksh/blink#1335]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink 14.0.5 (401)
iPadOS 15.x

### Describe the bug

I have three custom presses configured, but none work any more. Changing them to not involve the ctrl or opt keys does seem to fix.

- For the opt-bspc one, it sends bspc only (seemingly ignores)
- For the ctrl-tab one, it defocuses the blink window (I can see the blink cursor turn hollow) and sends nothing

![8CC837D3-4E81-41D3-A155-8280F85ABBE0](https://user-images.githubusercontent.com/191335/145700611-89b9f7eb-87ba-4119-9c91-3ebae3a47536.jpeg)

**Comment by yury** [comment]
It is fixed in v15.0.6. Should be out today

**Comment by peppy** [comment]
Huge thanks for this. I've almost reprogrammed my brain to use different keys as a result of this, but have only hit about 90% reliability in that department. Will test as soon as it hits testflight.

**Comment by peppy** [comment]
Can confirm this is fixed in the latest v15 testflight.
