### ISSUE TITLE
Blink code. How do we use it?

### ISSUE THREAD

**Issue by mrpher** [blinksh/blink#1336]
**Describe your problem**
I bought Blink after seeing [this video](https://www.youtube.com/watch?v=tPHjcsrKM9s) demonstrating exactly what I need: VS Code on iPad pro with Gitpod! 

But... I can't figure out how to use it, if it's even enabled, if not when it's coming out, and where the documentation might be.

Is this not available yet?

**Desktop (please complete the following information):**
 - OS: iPadOS

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11

**Additional context**

**Comment by carloscabanero** [comment]
Hi! That will be released very soon, but you can request early access and help us testing at community.blink.sh.
