### ISSUE TITLE
Parameters should not require space.

### ISSUE THREAD

**Issue by rsmck** [blinksh/blink#134]
I use non-standard ports but if you use (for example) `ssh -p7788 example.com` you get an error that failed to connect on port 22. However, `ssh -p 7788 example.com` works as expected.  

This is contrary to the usual expectations of POSIX option flags (An option and its argument may or may not appear as separate tokens. (In other words, the whitespace separating them is optional.) Thus, ‘-o foo’ and ‘-ofoo’ are equivalent.)

**Comment by carloscabanero** [comment]
This was completed on v1.101
