### ISSUE TITLE
FileProvider can hang indefinitely 

### ISSUE THREAD

**Issue by rrgeorge** [blinksh/blink#1340]
### Checklist

- [x ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x ] Read the [docs](http://blink.sh/docs/)
- [x ] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iOS 15.2
Blink 14.05.405

### Describe the bug

FileProvider can get indefinitely hung up on a file with no way to cancel or restart the download.

![C3049F56-1490-4924-B2B9-8F660314565B](https://user-images.githubusercontent.com/8526392/146585793-24b13c39-ff76-478c-957e-8e7fcfa4181f.jpeg)

FileProvider.log:
<details>
  <pre>
Dec 17 2021, 09:18:09 enumerator [info] NSFileProviderRootContainerItemIdentifier
Dec 17 2021, 09:18:09 enumerator [info] c2Z0cDpyYS1ob3Jha2h0eTp+/gos.module
Dec 17 2021, 09:18:09 enumeratorFor  [info] Enumeration requested
Dec 17 2021, 09:18:09 enumeratorFor  [info] Enumeration requested
Dec 17 2021, 09:18:09 enumeratorFor gos.module [info] Enumeration requested
Dec 17 2021, 09:18:10 enumeratorFor gos.module [error] Fail(msg: "Not a directory. - ")
Dec 17 2021, 09:18:14 enumerator [info] NSFileProviderRootContainerItemIdentifier
Dec 17 2021, 09:18:14 enumeratorFor  [info] Enumeration requested
Dec 17 2021, 09:18:15 enumeratorFor  [info] Enumerated 159 items
Dec 17 2021, 09:18:17 enumeratorFor  [info] Enumerated 159 items
 </pre>
</details>

**Comment by carloscabanero** [comment]
Few months ago we fixed what may have been provoking this issue. Unfortunately I do not think we can do anything with the control for Upload / Download within the Files.app. Issue is that Apple currently requires to take control of a URLSession, and that means we would have to "wrap" our calls through a HTTP server, making everything a lot more complicated. The new API has a different "Progress" which is a lot more convenient, but it is macOS only.

**Comment by rrgeorge** [comment]
I haven’t noticed the issue in a while, so it’s probably fixed.

**Comment by carloscabanero** [comment]
Excellent 🚀
