### ISSUE TITLE
iOS Files Integration - must specify user

### ISSUE THREAD

**Issue by pfriedland** [blinksh/blink#1341]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
14.0.3.370, iOS 15.1

### Describe the bug
Files app asks for authentication although all Blink instructions/documentation have been followed.
In my case, I have a default ssh user specified in Blink config.  When I explicitly set the username in the Blink host config, then the Files app no longer asks for authentication and works as expected.
### Expected Behavior
Files app does not ask for authentication when Blink default ssh username is specified.  When I explicitly specify the username in the Blink host config, then the iOS Files integration works as expected.

**Comment by carloscabanero** [comment]
We fixed this already on Blink raw.

**Comment by pfriedland** [comment]
great shell, I love it !! Can't wait for the Code integration.
