### ISSUE TITLE
Incorrect indentation is displayed

### ISSUE THREAD

**Issue by geometryolife** [blinksh/blink#1343]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
v 14.0.5 (405)
iPad OS 15.2

### Describe the bug
There should be no white space, but a top display.
![8FF8D3DA-8CB3-4F8E-8960-666C11C938C5](https://user-images.githubusercontent.com/54882546/147044838-cc1a808d-4e31-47e8-b728-6e464348d8f5.jpeg)

**Comment by yury** [comment]
@geometryolife is it first time or always for you?

**Comment by geometryolife** [comment]
> 



> @geometryolife is it first time or always for you?

Always.

**Comment by geometryolife** [comment]
This is often the case, especially when entering incorrect commands, or when the connection is interrupted, there is always a long indentation.

**Comment by yury** [comment]
Can't reproduce. Do you have like 100% steps to reproduce? It will help a lot.

**Comment by geometryolife** [comment]
> Can't reproduce. Do you have like 100% steps to reproduce? It will help a lot.

It is very sudden and also frequent. I don't know how to provide the complete steps. This doesn't happen when I'm plugged in to the server to work.
![48B99527-824D-45AD-BA76-0D28F73AF5BE](https://user-images.githubusercontent.com/54882546/147070121-46edd091-5f6c-46b8-9005-41ecac41e8ac.jpeg)

**Comment by geometryolife** [comment]
![F997CCCD-3C84-423C-B115-9BC1B115E4AB](https://user-images.githubusercontent.com/54882546/147071924-2f14c989-92dd-4626-8efc-f98a92d3798e.jpeg)
![AF0E23F0-97C6-462E-A2FB-395016A024A6](https://user-images.githubusercontent.com/54882546/147072181-4e2fca3a-ce6d-494b-bfc2-730dadfacfed.jpeg)
![479B58CC-8B62-4DA6-A237-A94338BBB672](https://user-images.githubusercontent.com/54882546/147072315-51d1712e-db44-4625-bf8f-06430a9d9976.jpeg)
I did some demos.

**Comment by yury** [comment]
Yep, ctrl+l broke for me too. Will look. Thank you.

**Comment by yury** [comment]
I fixed ctrl+l issue. Wondering why you can't cd to iCloud....

**Comment by geometryolife** [comment]
> I fixed ctrl+l issue. Wondering why you can't cd to iCloud....

Maybe it's the above impact, but now the problem doesn't arise.
