### ISSUE TITLE
Code integration is Awesome !!

### ISSUE THREAD

**Issue by pfriedland** [blinksh/blink#1344]
blink shell rocks with Code. My iPad just became my favorite hacking buddy!!

Merry Christmas, Happy New Year !!

**Comment by orangeluc** [comment]
Is the Blink code command still available? I couldn't use it.

**Comment by pfriedland** [comment]
It’s in the Apple Test Flight version. MS Code integration is pretty cool.
Of course now I need a larger iPad but I’m not complaining

**Comment by yury** [comment]
@pfriedland can you record short video of you usage? What lang/platform do you use?

**Comment by pfriedland** [comment]
I’ll try. I am doing mostly kubernetes and micro service development. So
Python, .yaml files, etc. The MS Code is not the full version - it’s a web
application. It has very good github integration. You simply create a new
window in Blink and type *code .* and it starts up.

Open Remote Repo:


work on files; commit/push to GitHub. Slide to server in Blink and do a git
pull.

**Comment by yury** [comment]
Cool. You can do `code https://github.com/owner/repo` too.

**Comment by andymac4182** [comment]
I have been playing with this and Gitpod. It is great to see this out. Definitely makes the Gitpod experience a lot nicer on the iPad.

**Comment by sylvoie** [comment]
I updated blink with last version. I touch Tab key to see all command. Code is there, but when I run code I receive this message :

code is unavailable in (App Store)

I need explication please?

**Comment by yury** [comment]
@sylvoie code command is not production ready yet. It is available for testing on Test Flight.

I think we should release it this month.

**Comment by sylvoie** [comment]
Ok thank’s

I can't wait to try it!

**Comment by yury** [comment]
Ok, we finally released Blink 15 with code. Closing this issue.
Feel free to reopen if needed.
