### ISSUE TITLE
Keyboard Transparency [Feature Req]

### ISSUE THREAD

**Issue by rsmck** [blinksh/blink#135]
A few other SSH clients I have previously used provide the option to use the full device screen area but render the keyboard semi-transparent (the level of which is adjustable in settings) allowing you to type over the session)

I'm not even sure if this is still possible (Apple may have blocked it with more recent keyboard changes in iOS) but if it is it'd be really useful for those of us using blink on smaller devices (iPhone)

**Comment by rsmck** [comment]
Hmm, from a little research I think this isn't possible now :( ... if you find a way it would be amazing but the functionality doesn't work in the older clients now under either iOS 9 or 10

**Comment by carloscabanero** [comment]
Yup, this sounds more like a pain to implement.
