### ISSUE TITLE
Prevent Sleeping

### ISSUE THREAD

**Issue by geometryolife** [blinksh/blink#1355]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
iPad OS 15.2
blink 14.0.5

### Describe the bug

**Keep display active when in terminal**

How to keep the terminal alive in the background?

I use termius, which can be set to prevent sleep, keep the ssh connected all the time. 
But blink doesn't seem to have such a switch to set.

**Comment by yury** [comment]
@geometryolife there is `geo track` command for that.

**Comment by geometryolife** [comment]
> @geometryolife there is `geo track` command for that.

@yury thank you.
I found the information in the wiki to be a bit outdated and may need you to correct it.
![3A7E986D-85EF-4A8C-AD19-6A87F9A1A073](https://user-images.githubusercontent.com/54882546/149723913-b7f68dcd-a9b8-42cf-b09c-a538e4841b6f.jpeg)
![E1EE6549-447C-4DF6-B61A-B0AD56892679](https://user-images.githubusercontent.com/54882546/149723916-9712c10d-5a36-42ef-8dca-28eceada292b.jpeg)

**Comment by yury** [comment]
Yep, this is outdated. Sorry

Here link to docs https://docs.blink.sh/advanced/advanced-ssh#persistent-ssh-connections-with-blink
