### ISSUE TITLE
Setting § to Esc stopped working after updating to the new version 14.0.5.418

### ISSUE THREAD

**Issue by yoni206** [blinksh/blink#1357]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

- Blink version: 14.0.5.418
- iOS version: 15.1
- Device: ipad pro

### Describe the bug
In my configuration, § was mapped to hex code 2B in order for it to serve as the escape key in my remote vim.
After updating, § just prints § on the screen. I tried remapping and it didn’t help. I also tried remapping it to “Press <the circle with the arrow which stands for escape>“ but still I get §.

<img width="515" alt="esc" src="https://user-images.githubusercontent.com/12624708/149748318-060c7c0c-eb44-410a-8c93-3209b315b5af.png">

**Comment by yury** [comment]
Confirmed. Working on solution...

**Comment by martinorob** [comment]
Same issue here.
Vim and Esc not usable with external keyboard

**Comment by yury** [comment]
I pushed the fix, but we need help with testing.

**Comment by martinorob** [comment]
I’m available for testing

Thanks

**Comment by yoni206** [comment]
Happy to test. How?

**Comment by yury** [comment]
drop me a letter at yury@blink.sh - will send you TestFlight invites. 
I think TestFlight version will be out today.

**Comment by yury** [comment]
Closing, feel free to reopen if needed
