### ISSUE TITLE
Cursor Keys - Inconsistent Behaviour

### ISSUE THREAD

**Issue by rsmck** [blinksh/blink#136]
I've not spent much time investigating this yet but something 'odd' is happening with the cursor keys (on the on-screen keyboard) in some remote applications.

In `nano` and `vi` they work as expected. However, In an app I commonly use - `sngrep` ( https://github.com/irontec/sngrep/ ) all of the cursor keys act as if the Escape key has been pressed prompting an exit from the application.

**Comment by carloscabanero** [comment]
Related to #146. And fixed already on next version.
