### ISSUE TITLE
Can’t start sftp

### ISSUE THREAD

**Issue by ghost** [blinksh/blink#1363]
I tried to use sftp but following error was returned.

blink> sftp “server”
Copy failed. LocalFileError(msg: “No such file or directory.”)

SSH to “server” by blink is OK and other device can establish sftp connection to “server”.
I’m using ssh-key generated by config not ssh-keygen
(because blink could not set passphrase and I could not find generated pub-key like id_rsa.pub).

How can I start sftp?

**Comment by carloscabanero** [comment]
Blink SFTP is not interactive and behaves like SCP. You need to specify a source and destination. You can enable "interactive" mode using the Files.app, with better integration with the rest of iOS, by going to the server and adding a location here: 

![IMG_0154](https://user-images.githubusercontent.com/536729/150335953-d01599ab-2fc7-429a-96de-e05e239f475d.jpeg)
