### ISSUE TITLE
Shift-TAB sends a regular \t with software keyboard on iPhone

### ISSUE THREAD

**Issue by eugr** [blinksh/blink#1364]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iOS 15.2, Blink 14.0.5.418 (App Store), iPhone 13 Pro Max

### Describe the bug

When using, for example, Emacs, tapping Shift on the software keyboard and then Tab "smart key" sends regular TAB character.
This can also be confirmed using `showkey -a` command - both TAB and Shift-TAB give me \t character.

However, when using on iPad (still with software keyboard!!!) which has TAB button on the built-in software keyboard, Shift-TAB works as expected and produces correct sequence: ^[[Z

Expected behavior: 

Send correct sequence: ^[[Z (also described in this ticket: #117)

**Comment by yury** [comment]
Thank you for report. 
Fixed. Will be in next release after v14.0.6.

**Comment by eugr** [comment]
That was quick, thanks! Waiting for the next release!

**Comment by yury** [comment]
Released. Closing. Feel free to reopen if needed.
