### ISSUE TITLE
Arrows and tab with modifiers send default sequence ignoring settings

### ISSUE THREAD

**Issue by jaclu** [blinksh/blink#1365]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink: v14.0.5.418
iPadOS: 15.2.1
External BT keyboard, tested with two different, same issue, also tested same version of Blink on iPhone with latest iOS, same issue

### Describe the bug

I can no longer define Custom Presets for any Shift, Ctrl, Alt, Cmd combination for arrows and tab keys, the default codes are sent regardless. This used to work until I don't know maybe a week or two ago.

In Keyboard Shortcuts, the default Shift-Cmd-Right for 'Next tab' is also no longer working, instead of the action, the default ANSI-sequence is sent: ^[[1;2C

Example: Define keyboard-Custom Presets
Shift-alt-right to send HEX: 41
This should send the letter: A
What is sent is the default sequence: ^[[1;4C

**Comment by yury** [comment]
@jaclu should be fixed in v14.0.6

**Comment by jaclu** [comment]
Indeed, thx for the quick turnaround!
