### ISSUE TITLE
ssh-copy-id does not take effect until Blink is restarted

### ISSUE THREAD

**Issue by jaclu** [blinksh/blink#1368]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink V14.0.6.426
iPadOS 15.2.1

### Describe the bug

After creating a default key id_rsa, then copying it to the host using ssh-copy-id id_rsa [hostname]
and logging in with password, adding the pubkey, connecting again with ssh [hostname] still asks for a password.
Trying it again gives same result.

Not until Blink is terminated and restarted is the pubkey being used for auth.

If fixable, that would obviously be preferred, if not, it would be helpful if a warning was displayed that a restart is needed.

**Comment by carloscabanero** [comment]
I'm unsure what was causing this issue as the remote is the one that needs to accept the public key negotiation first. We also changed all ssh authentication with Blink 15, etc... So closing, if this was a problem in Blink it has already been fixed with updates.
