### ISSUE TITLE
ssh-copy-id to not previously accessed host obscures warning message

### ISSUE THREAD

**Issue by jaclu** [blinksh/blink#1369]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink V14.0.6.426
iPadOS 15.2.1

### Describe the bug

blink> ssh-copy-id id_rsa hostname
SSHSession:DEBUG:Connecting to hostname [X.X.X.X] port yyyy.
Connected to hostname
SSHSession:DEBUG:Server host key: ECDSA 256 lLKvyt7+GvxcLMQf2A7rJHxjqRzbdSQ7loYPArJz= 
Are you sure you want to continue connecting (yes/no)?The authenticity of host hostname (X.X.X.X) can't be established.
ECDSA 256 key fingerprint is lLKvyt7+GvxcLMQf2A7Q7loYPArJz=

If you hit Enter guessing it would complete the procedure, you get a prompt:

Please type 'yes' or 'no':

When dealing with security answering yes/no without knowing what you are agreeing to, seems like a bad idea :)

I have used ssh for ages, and it still to me a while to figure out what this was about.

I guess this happens a lot when people install Blink, add a key and then try to deploy it.

It would reduce confusion if ssh-copy-id displayed a message before doing its thing in the line of:

If this is the first time connecting to a host, the host will want you to accept its host-key
If you see "Are you sure you want to continue connecting (yes/no)?" embedded in the output below, you need to type yes to proceed, thus accepting the hosts server-key for future access.

The key part visible above was generated using a random generator, just to keep the output somewhat representative, not related to any of my hosts...

**Comment by carloscabanero** [comment]
Fixed on 17.2.0
