### ISSUE TITLE
Cannot connect to server anymore: "Socket error: Connection refused"

### ISSUE THREAD

**Issue by neosimsim** [blinksh/blink#1374]
### Configuration

Blink v14.0.6.426
iOS 15.0.2
iPhone SE

I already tried to reboot my device and server and even reinstalled blink.

### Describe the bug
Things were working fine. Now Whenever I try to connect to my server I
get the following error.

```
blink> ssh -vvvv ssh.myhost.sh -p port
Setting up connection callbacks.
Starting connection to ssh.myhost.sh
ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
ssh_socket_exception_callback: Socket exception callback: 2 (61)
ssh_socket_exception_callback: Socket error: Connection refused
connError(msg: "Session Exception - Socket error: Connection refused")
Starting connection to ssh.myhost.sh
ssh_connect: current state : 9
Error connecting to ssh.myhost.sh. connError(msg: "Socket error: Connection refused")
Session deinit
```

Other client like FileExplorer are Working (SFTP).

**Comment by neosimsim** [comment]
Still does not work with Blink Shell & Code

**Comment by carloscabanero** [comment]
The connection refused usually means that the host could be resolved and contacted, but it refused to open a connection on that port. Can you try to do `ssh -p port host`? I was completely sure swift args library was working with parameters at the end, but I just tried myself and they were ignored. So maybe it is not contacting the right port.

**Comment by neosimsim** [comment]
That worked thanks. Even works with a configured host again. Maybe that was another issue caused by an iOS update.
