### ISSUE TITLE
Unable to select additional keys from settings->keys

### ISSUE THREAD

**Issue by rrtfm** [blinksh/blink#138]
Intent: Create a new RSA key and copy the public key via the settings->keys interface
Result: Once a new key is created it doesn't appear possible to successfully select the new key via the interface

Steps to repro:
- Create and save a new key via the settings->key interface
- Select, via the touch UI, the new key via the settings key interface
- Default key's info is shown via the "Key Info" screen
- Copying and comparing the public key confirms that the default key's info is being displayed

**Comment by carloscabanero** [comment]
Great catch. Don't know how we didn't catch this one :(

**Comment by carloscabanero** [comment]
Fixed on v1.101
