### ISSUE TITLE
Error Connecting: authfailed(methods: [SSH.AuthAgent])

### ISSUE THREAD

**Issue by billyjacoby** [blinksh/blink#1380]
### Checklist

- [ X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ X] Read the [docs](http://blink.sh/docs/)
- [ X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
14.0.7, iOS 15.3, iPhone 12 Pro

### Describe the bug
No matter what I do I cannot connect to a server using SSH authentication. I have tried generating a number of different keys, and even imported keys that were generated on a different device to no avail. I always get the same error:

Error Connecting: authfailed(methods: [SSH.AuthAgent])

**Comment by carloscabanero** [comment]
Could you send us the output from ssh -vvvv? How are you specifying the keys that you wanna get used for the server?

**Comment by billyjacoby** [comment]
So I was using the default id_rsa key, i learned my problem was that I wasn't passing in a username.

Should I have to pass in a username even though I have it set as the default user?

**Comment by carloscabanero** [comment]
No, it is related to the new changes on ssh/config, just fixed it. Thanks for the heads up. Should be out on next release.
