### ISSUE TITLE
ssh-agent failed to load in v15

### ISSUE THREAD

**Issue by michielappelman** [blinksh/blink#1383]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

v15.0.1.516 – Congratulations on the release BTW!

### Describe the bug

Running ssh-agent gives the following error:

```
blink> ssh-agent
Failed loading ssh_agent_main from MAIN, cause = (null)
ssh-agent: command not found
```

**Comment by yury** [comment]
@michielappelman in 15 you don't need ssh-agent as process anymore.

**Comment by michielappelman** [comment]
> @michielappelman in 15 you don't need ssh-agent as process anymore.

It seems like it doesn't indeed. Thanks for the clarification!

I was just following the docs, so that would probably be good to update. Perhaps also remove the `ssh-agent` command, or have it output the fact that you don't need it anymore when it is executed?

**Comment by yury** [comment]
@michielappelman, yep. Docs outdated in that parts. Thank for report.

**Comment by carloscabanero** [comment]
Docs already up to date.
