### ISSUE TITLE
Cannot migrate from v14

### ISSUE THREAD

**Issue by LC0117** [blinksh/blink#1384]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
iOS 15.3.1
Blink Shell 15.0.1

### Describe the bug
I've paid for v14. But using v15's "migrate from v14" failed.

![IMG_0108](https://user-images.githubusercontent.com/77481149/153633542-9abb5ae4-4c1c-4641-b38a-4b5931993670.PNG)

**Comment by carloscabanero** [comment]
Hi! Have you previously migrated from another device? If so, then do a "Restore Purchase" instead. If you are still having issues, please send us an email to hello at blink.sh.

**Comment by LC0117** [comment]
No, I tried several times on my iPhone and iPad to no avail.

**Comment by carloscabanero** [comment]
Ok, send us an email then and will help you there.

**Comment by macBender** [comment]
Hi

I’m having the same issue.  I’ve performed the same troubleshooting steps.

**Comment by yury** [comment]
Yep, we identified root of the issue. Will be fixed later today.

**Comment by macBender** [comment]
That works for me now
