### ISSUE TITLE
Blink 15 - cannot open any file in VS Code

### ISSUE THREAD

**Issue by Juggler00** [blinksh/blink#1389]
### Checklist

- [X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
Blink v15.0.1.516
iOS 15.3.1 (iPad Pro)

### Describe the bug

Was able to successfully transfer all data from v14. Verified I can still ssh into my local server. Enabled blink-fs extension and can see remote files on server. Ran “code .” and VS Code opens up.

From files.app, if I right-click on remote file and select “Code”, Blink does open showing VS Code, but the file never opens. Similarly, I cannot find any way to open a remote file directly from VS Code interface.

**Comment by Knightdriv3r** [comment]
Does your host alias have any capital letters?  I just reported a bug where code will not load folders in vscode if the host alias has any capital letters.  If your host alias has all lower case letters it works.  Not sure if your issue is related.

**Comment by carloscabanero** [comment]
So just to be clear, if you access the remote using `code host:path`, that is working fine and you can see the remote files. But if you try this through the Files.app, then Code opens but no files are shown, correct?

**Comment by Juggler00** [comment]
Unfortunately, even when I rune `code docker:/hdd12tbpool/docker/docker-compose.yaml` no file is open. VS Code editor is opened, but no files are.

**Comment by Juggler00** [comment]
After watching this video (https://www.youtube.com/watch?v=Cv-pSZkpIZ4) I figured out that you need to install an extension called "blink-fs". Once I did this, I am able to open remote files.

The documentation definitely needs to be updated!
