### ISSUE TITLE
Blink v15, code command and FILES.APP will not load folders when the host alias has any capital letters

### ISSUE THREAD

**Issue by Knightdriv3r** [blinksh/blink#1390]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink v15.0.1.516
iOS 15.3.1 (both iPhone 13 pro max and M1 iPad Pro)
MacOS 12.2.1 (Monterey)
code-server 4.0.2 (running on MacOS version above) 

### Describe the bug

vscode in Blink when accessing code-server on Mac will not load any folders when the alias for your configured host in Blink has any capital letters.  It seems to happen regardless of the location of the capital letter.  For example:  I had setup a host with an alias of CodeTest.  Any variation that has a single capital letter will not load folders in vscode in Blink.

After some trial and error I figured out that simply changing my alias from CodeTest to codetest fixed the issue and folders loaded in vscode in Blink from the code-server on the Mac as expected.

Folders should load in vscode in Blink even if the alias name of your host has capital letters.

**Comment by carloscabanero** [comment]
Thanks for heads up! Dumb mistake, will get fixed asap.

**Comment by samaklis** [comment]
Hi, I was wondering if there is any ETA for the fix of this issue.
Thanks

**Comment by yury** [comment]
@samaklis 

We think it is fixed. Can you provide your file paths and host name so we can reproduce it and write unit test for it.

**Comment by samaklis** [comment]
@yury the host alias is ubuntuExternal and the path /var/www/webdav 

On first access from the files app, it worked fine. Any subsequent access though got stuck in "loading files" and in addition there were no errors in the file  provider log. Interestingly enough the path ~ for the same host name worked fine. Renaming the host with all lower case fixed it.

**Comment by carloscabanero** [comment]
Looking into it.
