### ISSUE TITLE
Blink v15 - Error during v14 settings import

### ISSUE THREAD

**Issue by jorwex** [blinksh/blink#1391]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug

Upgraded to v14.0.9.440 and installed v15.0.1.516 on an iPhone 13 mini, then restored purchase to claim the Blink Classic plan on v15.0.1. 

Attempted new app's settings import feature and was presented with the following prompt:

```
Data Export
The new Blink.app is requesting permission to export your data. Do you want to continue? 
Cancel / Continue
```

Then the following message appeared:
```
Error
Error obtaining archive.
Error(description: "Could not read private key for id_rsa")
```

I have (1) key and (2) hosts on v14, and none of those settings are now available in v15. I did not have many settings customizations, so it is unclear if anything was successfully imported. 

This sounds independent from #1385 because nothing appeared to crash. 

This could be a duplicate of #1388, but there was no mention of other settings failing to import in that issue. 

Thanks for all of your hard work.

**Comment by carloscabanero** [comment]
Failure there means the archive on 14 was not generated, so nothing got imported. Now, the specific “could not read private key” error means that the key does not have the private key accessible. If I’m right, trying to read the private key from the UI should fail too. 

Have you recently changed devices? When recovering from iCloud backups, we have seen that sometimes the keys are not reachable anymore.

If that’s the case, then just delete the key and import without it. You will unfortunately need to generate a new one.

Let me know if this helpedz

**Comment by ThorkelAU** [comment]
I also had this problem.  However, there was no failure trying to copy the private key from the UI in Blink 14 - the private key copied fine onto the clipboard.  it only failed when using the copy settings functions from the new Blink.

Deleting the key allowed the transfer to complete successfully (and wasn’t a major problem for me, as it was an old key that I wasn’t using any more that was preventing the transfer).

**Comment by jorwex** [comment]
> Failure there means the archive on 14 was not generated, so nothing got imported. Now, the specific “could not read private key” error means that the key does not have the private key accessible. If I’m right, trying to read the private key from the UI should fail too.
> 
> Have you recently changed devices? When recovering from iCloud backups, we have seen that sometimes the keys are not reachable anymore.
> 
> If that’s the case, then just delete the key and import without it. You will unfortunately need to generate a new one.
> 
> Let me know if this helpedz

Using `Copy private key` prompted for FaceID, did not present any further dialogs/messages, but when I tried to paste in another app, the clipboard was empty. Does that mean the read failed? 

I did indeed change devices recently. 

Deleting the key and re-importing did indeed work!

**Comment by carloscabanero** [comment]
For readable keys that had public keys in a specific format, we fixed issues on latest release. If the key is not readable and cannot be imported, then there is nothing we can do. Please note we are not able to transfer keys between devices (yet), but this will be coming soon.
