### ISSUE TITLE
Blink 15 + VSCode: Job rejected for non app-bound domain

### ISSUE THREAD

**Issue by cvcore** [blinksh/blink#1392]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Version: `Blink v15.0.1.516 (App Store) Feb 9 2022`

Using code on cloud from GitHub Codespaces

### Describe the bug

When using GitHub codespaces inside Blink shell, I wasn't able to get the jupyter plugin working. It works however with Safari.

To reproduce, create a new codespace instance and install the `ms-toolsai.jupyter` plugin.
Then, open a `.ipynb` file. The following error will appear:

```
Error loading webview: Error: Could not register service workers: TypeError: Job rejected for non app-bound domain.
```

As a result, code cells can't be displayed:

![IMG_0383](https://user-images.githubusercontent.com/4695324/153746629-06e47498-21cc-450f-8758-98dfe4afa6e6.PNG)

The same error can also be triggered by opening a png image from vscode's file explorer.

After some search, I believe this is due to [WebKit's domain restriction](https://webkit.org/blog/10882/app-bound-domains/).

**Comment by cvcore** [comment]
Temporary solution:
https://github.com/blinksh/blink/blob/0fdae15520eef86b177d3a294721e9ab3dbe6f8e/Blink/TermView.m#L171
Set this line to `NO`

**Comment by yury** [comment]
Yep, we don't support all domains yet. We need to get "Browser entitlement" from Apple. We applied, but not get any response back yet.

**Comment by cvcore** [comment]
@yury Okay, but Jupyter isn't working even after disabling domain restrictions with `webViewConfiguration.limitsNavigationsToAppBoundDomains = NO`. 

In this case the plugin stuck in the empty document page, and in console log I found `Failed to load resource: the server responded with a status of 404 ()` when accessing `https://***.github.dev/assets/***/****/vscode-remote-resource?path=******&tkn=*****`

Also there is another warning showing `Ignoring user script injection for non-app bound domain.`

Not sure which one is the root cause.

**Comment by yury** [comment]
Script injection will not work without bound domain. That is why we need browser entitlement.

**Comment by cvcore** [comment]
I see, thanks!

**Comment by carloscabanero** [comment]
Leaving a note here. Last week we also opened an issue in Apple forums, as sometimes Apple engineers have helped others in our situation to move things forward. 

The issue is here https://developer.apple.com/forums/thread/700605. If someone else is interested, it may help to upvote or make a comment so we can get more attention. So far, nothing has changed.

Thanks!

**Comment by ninyawee** [comment]
I wonder meanwhile we are waiting for apple to response on this. Could blink has the option to not open codespace via Blink?

My jupyter notebook works just fine in the safari. 

I need to uninstall blink first, to add codespace home screen app. Then, reinstall blink and all keys.

**Comment by treyharris** [comment]
> I need to uninstall blink first, to add codespace home screen app. Then, reinstall blink and all keys.

Did you do this? Did it work?

I was trying to use Code for Jupyter and also had issues. Since I have a Linux box at home I was considering whether to host a kernel serving the same files, or if not, what.

**Comment by ninyawee** [comment]
> 

yes, it does work. Hosting the kernel is ok, but you won't get the benefit of vscode extensions like Github Copilot and strong intelisense

**Comment by yury** [comment]
![IMG_0210](https://user-images.githubusercontent.com/5250/176371025-dfe86bec-c145-4be9-9015-ccac719b7c8a.PNG)
