### ISSUE TITLE
Migrating from v14 to v15 on two iPads fails on second one

### ISSUE THREAD

**Issue by ppwaskie** [blinksh/blink#1393]
**Describe your problem**
I recently installed v15 of Blink onto one of my iPad’s last night, an iPad Air.  The verification of my full purchase of Blink v14 was transferred successfully, and I’ve been using that without issue.

When I installed v15 of the Blink app onto my iPad Pro today, I tried doing the same verification of my previous purchase.  It failed when trying to generate the token based on the receipt.  I was hoping that the app purchase would be honored across my devices that share the same iCloud account.

**What you have tried and your configuration**
Let us know what you have tried and the error messages you get.
1. I used Blink v14 to get to the v15 installer on my iPad Pro, installed it, and went into `config`.  From there when I went to upgrade using the Migration Assistant.
2. Step 2, Validating Receipt, errors out with Receipt Already Exists.
3. I still have the Free license on my iPad Pro

**Expected behavior**
I hoped that since I did purchase the app and have it installed on two iPads today with full features, that migrating to v15 on both iPads would also have the same licensing since I purchased that app.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iPadOS 15.4 (beta) on iPad Pro, iPadOS 15.3.1 on iPad Air
 - Browser: Using Chrome mostly
 - Version: I can look if needed

**Additional context**
Just curious if the licensing changed that there’s only one account-wide upgrade, or if any devices on my personal iCloud account can upgrade v15 Blink to the purchased version I’ve had since v14.

**Comment by carloscabanero** [comment]
Hi! As the receipt was already exchanged on one device, you just need to do a Restore Purchase on the second. We are improving the wording to make that more clear, pardon the inconvenience.

**Comment by ppwaskie** [comment]
Fantastic!!  I didn’t try that. I really appreciate the quick response.  Worked like a charm.

**Comment by carloscabanero** [comment]
We are on call the weekend to make the transition as smooth as possible.
