### ISSUE TITLE
 README.md compile instructions confusion

### ISSUE THREAD

**Issue by anand0xff** [blinksh/blink#1394]
First megathanks to **ALL** to have developed blink!!!!

Following README instructions: after 
## Build
![CI](https://github.com/blinksh/blink/workflows/CI/badge.svg)

1: git clone --recursive https://github.com/blinksh/blink.git &&     cd blink && ./get_frameworks.sh &&     rm -rf Blink.xcodeproj/project.xcworkspace/xcshareddata/

the next command puts me in the wrong directory so it fails...

2. cd blink
    cp template_setup.xcconfig developer_setup.xcconfig
cp: template_setup.xcconfig: No such file or directory

I did figure out after five or ten minutes that   
(a) I did have xcode,  
(b), what *.xconfigs are for   
(c) looking at the githup blinksh/blink.  
Then I realized I was in one directory too deep. 

Would a developer be willing to clarify this part of the readme somehow?   This sort of initial glitch can be offputting to a potential developer/contributor.

**Comment by yury** [comment]
Thank you, I tuned README a little bit.

Closing, feel free to reopen if needed.
