### ISSUE TITLE
Migration Assistant Fails 

### ISSUE THREAD

**Issue by pyrho** [blinksh/blink#1396]
I'm trying to ¨Migrate from Blink Shell 14 app", the first 2 steps (Verify receipt, Unlock Zero Cost) work fine, but the ¨Copy settings" fails (even when launched on its own (not via the Assistant), the app just crashes.

When I press on the "Unlock with $0 price" button, I get the Apple Pay prompt, double click the power button to validate, then the button transforms into a loader, but after loading goes back to the "Unlock with $0 price" button. And is stuck in that loop.

When trying to copy the settings from Blink 14, the hosts got copied alright, appearance and fonts too but not my SSH keys.

I also tried ¨Restore purchase" but it did not have any effect.

Versions: 
iPadOS 15.2.1
Blink v15.0.1.516

Thanks !

**Comment by gobigdave** [comment]
I'm seeing the same thing. When I run the migration process, it gets through the first 2 steps, but crashes while moving my data/config over. Hosts make it over, but no keys.

**Comment by carloscabanero** [comment]
Yep, we worked during the weekend to iron out these issues. Waiting for the AppStore to publish the new version.

**Comment by carloscabanero** [comment]
This should now be fixed on latest version.
