### ISSUE TITLE
Support setting `mosh --experimental-remote-ip=VALUE` via GUI

### ISSUE THREAD

**Issue by fingolfin** [blinksh/blink#1398]
By default, blink uses `mosh --experimental-remote-ip=local`. I have some hosts which I need to access via `mosh --experimental-remote-ip=remote`, always. It would be nice if I could save this in the host config, instead of having to retype this each time I want to establish a fresh mosh session.

**Comment by carloscabanero** [comment]
Implemented as part of fixing #1803. We will possibly branch TF to test this so we do not hold this from the AppStore until the next big release.

**Comment by yury** [comment]
Closing as implemented and released. Feel free to reopen if needed.
