### ISSUE TITLE
Mosh argument `--predictive=experimental` can be set via GUI but not via CLI

### ISSUE THREAD

**Issue by fingolfin** [blinksh/blink#1399]
These days, `mosh` has four prediction modes. From `mosh --help` on my Mac:
```
        --predict=adaptive      local echo for slower links [default]
-a      --predict=always        use local echo even on fast links
-n      --predict=never         never use local echo
        --predict=experimental  aggressively echo even when incorrect
```

All four of these are accessible via the Blink GUI, i.e., entering `config` and then editing the host configuration.

However, the `mosh` command in Blink's command line interface only supports the first three, but not `--predictive=experimental`.  Trying to pass this value results in an error: "Unknown prediction mode. Use one of: always, adaptive, never". Also `mosh --help` only lists the first three.

**Comment by yury** [comment]
Fixed help message for mosh command.
It is just `mosh help` issue.
If you pass `experimental` it will work.

Fix will be out soon. Closing this issue. Please reopen if needed.

**Comment by carloscabanero** [comment]
This is available on TestFlight build 747
