### ISSUE TITLE
VSCode Azure Repos - Cannot Open Remote Repo

### ISSUE THREAD

**Issue by jamessampford** [blinksh/blink#1400]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
Latest version Blink & iOS

### Describe the bug
Cannot seem to be able to sign into a Azure Repo; can sign into a GitHub repo just fine; just get a big white box - presumably the URL for authorisation hasn’t been whitelisted, but seeing the option is there by default in VS Code, would make sense to support it

![IMG_1408](https://user-images.githubusercontent.com/1376843/154147968-bf20f68f-0db1-400c-8b63-56e48af1564e.jpeg)

![IMG_1407](https://user-images.githubusercontent.com/1376843/154147999-3b04d785-692f-4007-85b3-f70a09bc6426.png)

**Comment by carloscabanero** [comment]
Need the browser entitlement for that domain. Closing here. Related to #1392

**Comment by jamessampford** [comment]
For reference, it is visualstudio.com

**Comment by yury** [comment]
Ok, we need recheck that. Adding to November's list.

**Comment by yury** [comment]
With latest blink it is working. Sorry for so late response.
![Image](https://github.com/blinksh/blink/assets/5250/4b80347e-8e39-4642-8304-76226c14c2d1)
