### ISSUE TITLE
Failed Migration, Validating receipt: Receipt already exists

### ISSUE THREAD

**Issue by pyrho** [blinksh/blink#1401]
# Description
After prior unsuccessful migration attempts (see https://github.com/blinksh/blink/issues/1396#event-6078017406), I downloaded the latest version and tried again, but this time I get a "Receipt already exists" error.

# What I have tried
- upon first try I was stuck in a "apple pay authorization" loop
  - As stated in #1396 I would get the "unlock with $0 price" button -> double click power button to authorize payment -> spin -> back to $0 price button
- uninstalling blink15 and trying again
- restore purchase
- try 5 times

# Versions
Blink 14.0.9.440
Blink 15.0.3.520
iPad pro m1 11"

Here is a video:

https://user-images.githubusercontent.com/145502/154157781-dfa9a0af-2940-4d32-962e-28a57c3e0b81.mp4

**Comment by lepri13** [comment]
I have the same issue as well, was stuck in unlock for free loop, tried to re install and it failed

**Comment by carloscabanero** [comment]
Hi! Sorry for the delay getting back here, not sure how we could have missed it. As mentioned in other similar issues, please contact us on support at blink.sh. We have a backup plan for these cases.

**Comment by pyrho** [comment]
Alright, I guess I'll close this then.
