### ISSUE TITLE
Files.app - Enumeration requested

### ISSUE THREAD

**Issue by stephencottontail** [blinksh/blink#1403]
**Describe your problem**

I have two droplets running Ubuntu 20.03 setup on Digital Ocean set up in `config` as `dev` and `jump`; `jump` acts as a jump host for `dev` and so in the configuration for `dev` I have set `ProxyJump` to `jump`. I can SSH into `dev` with this setup, but I wanted to be able to use Files.app integration as well, so I set it up following the instructions from [the docs](https://docs.blink.sh/advanced/files-app). When I attempted to visit the configured location in Files.app, I get an endless loading circle.

**What you have tried and your configuration**

* In `.blink/fileprovider.log`, I see these two lines repeated:

```
enumerator [info] NSFileProviderRootContainerItemIdentifier
enumeratorFor [info] Enumeration requested
```

* If I add `LogLevel DEBUG` to `SSH Config` for `dev`, I see these lines repeated in `.blink/fileprovider.log`:

```
Starting connection to (IP address)
SSH [log] ssh_connect: current state : 2
SSH [log] Session deinit
```

* I have verified that the line `Subsystem sftp /usr/lib/openssh/sftp-server` is uncommitted in `/etc/ssh/sshd_config`

**Expected behavior**

I expected to see my files in the droplet appear in Files.app

**Tablet (please complete the following information):**
 - OS: iPadOS 15.3.1
 - Blink Version: 15.0.3.520
 - iPad Pro 11-inch, second generation

**Comment by carloscabanero** [comment]
I fixed an issue in 526 that could have something to do with this. If still does not work...

From the logs it seems like a connection issue, it is not able to start the socket to the jump server. Do you see any "error" popping up in the Files.app? Or is it just spinning the wheel indefinitely? Try to do a `code <host>:<remote_path>` and let us know if that went through.
