### ISSUE TITLE
Failed Migration, only option is “close”.

### ISSUE THREAD

**Issue by graehu** [blinksh/blink#1405]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink version: 15.0.3.520
iOS version: 15.1

### Describe the bug

Upon clicking the “Start Migration” button within Settings->For Blink 14 Owners, my only option is to “close”.

I would expect something similar to the video posted here, but for migration to complete:

https://github.com/blinksh/blink/issues/1401

Here’s a screenshot of what I see:

<img width="1366" alt="PNG image" src="https://user-images.githubusercontent.com/858946/154836752-fd84ab96-3d15-499f-97eb-92e9bba9e2ed.png">

I expect this may have happened because I copied my settings before I tried migration, which appears to be the final step of migration. So perhaps it believes migration is complete.

Thanks in advance,
Graehu.

**Comment by graehu** [comment]
I uninstalled the new version of blink, re-installed it, and was able to go through the migration correctly. 

<img width="1366" alt="PNG image" src="https://user-images.githubusercontent.com/858946/154860242-485d0f33-eab2-4a52-8404-812ae48a045b.png">
 
The original problem still exists probably. I’m going to leave this open in-case someone else has the same issue.

Thanks,
Graehu.

**Comment by carloscabanero** [comment]
Thanks, I will add that to the docs. It is probably a weird state after the new update.

**Comment by carloscabanero** [comment]
Closing now as we updated docs.
