### ISSUE TITLE
Files.app missing Blink icon (for host location)

### ISSUE THREAD

**Issue by fal3nsh** [blinksh/blink#1407]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581) <-- Needs to be updated ! :p
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink: v15.04.524
iPadOS: 15.2.1
iPad Pro (11-inch), 1st gen

# Describe the bug

Files.app Blink's added location for a host is (still) missing an icon

# Expected behavior
Files.app should display a Blink icon.

# Capture
![IMG_0469](https://user-images.githubusercontent.com/93117491/155019315-27b2410b-981a-4317-b2fe-664de47462c5.jpeg)

**Comment by carloscabanero** [comment]
This is an issue with iOS. Nothing we can do. I unfortunately had the problem for like 2 months and at one point it just came back. I did not try switching to the old icon, but that may help.
