### ISSUE TITLE
Keyboard-Shortcuts: C-Tab & C-S-Tab can't be defined

### ISSUE THREAD

**Issue by jaclu** [blinksh/blink#1408]
They can be defined in Custom Presets, but since I wan't to bind them to next & prev tab that venue can not be used.

**Comment by yury** [comment]
Fixed. Will be out with next release.

**Comment by jaclu** [comment]
Thx for the quick solution!

**Comment by jaclu** [comment]
Btw If you want me to test that change, I wouldn't mind a TestFlight invite :)

**Comment by yury** [comment]
We will push new version as soon as beginning of next week. Just little bit out of schedule, sorry.
