### ISSUE TITLE
Synch Hosts settings between devices

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#141]
It would be neat to be able to synch the Hosts settings between different devices (iPad and iPhone, in my case), via iCloud. Not really a necessity, but it would add the convenience of not having to set up everything twice.

**Comment by carloscabanero** [comment]
Agreed, have to check if the keys on the iOS keychain are also synchronized somehow.

**Comment by carloscabanero** [comment]
Adding to the backlog. Lets start by synchronising Hosts + Keys, and then later on we can add other stuff :)

**Comment by dakira** [comment]
I would like to add that this should not be an all-or-nothing thing. I'm comfortable with syncing settings with the cloud but definately not my keys.

**Comment by carloscabanero** [comment]
Yup, we have almost completed the Hosts part and are testing it. Unfortunately iCloud sync is a mess, and we are trying to keep it as simple as possible without getting bitten by it :S

**Comment by mzvast** [comment]
I think this hosts sync feature is a most wanted, maybe through a binding blink account or somehow.

**Comment by carloscabanero** [comment]
We have it working already and will push to testers once we finish a couple things this weekend related to TouchID. Hopefully if all works well we will be able to push to everyone before the 23rd and will be in your device for Christmas.

**Comment by carloscabanero** [comment]
This is up on v3.0.21 :)
