### ISSUE TITLE
Files not saving using blink files and Blockquote app

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#1411]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink version `Blink: v14.0.8.437 (v14 Test Flight). Feb  7 2022`
iOS 15.3.1 on iPad Pro 12.9in 3rd gen
Blockquote version 2.0.0

### Describe the bug

When using blink files to map a filesystem on a remote Linux server, files edited in Blockquote are not saved. There is no notification that the file save has failed, leading to lost work.

Expected behavior: files saved on remote host.

**Comment by sbromberger** [comment]
This is also happening with the TexPad app.

**Comment by carloscabanero** [comment]
This should have been solved a while ago. Closing
