### ISSUE TITLE
Remote path is ignored for scp upload

### ISSUE THREAD

**Issue by tobyh** [blinksh/blink#1412]
I want to upload a file using scp from blink to a subdirectory on a remote host, but the file ends up in the home directory on the remote host.

### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink App Store version 15.0.5.526 and Blink TestFlight version 14.0.8.437 on iPadOS 15.3.1

### Command I used

```
blink> scp file.txt remote:subdir
```
where `file.txt` is an ordinary file and `subdir` is an existing directory on a configured host called `remote`.

I wrote it that way based on scp on *nix, and the [blink remote transfer tools docs](https://docs.blink.sh/advanced/unix-roundup#remote-transfer-tools).

### What I expected to happen

file.txt to be uploaded to the subdir on remote

### What actually happened

file.txt was uploaded to the home directory on remote, as if I had used the command `scp file.txt remote:`

### What else I tried

- Checking write permissions on subdir
- Quoting the destination (`scp file.txt "remote:subdir"`)
- Using a trailing slash (`scp file.txt remote:subdir/`)
- Using an absolute path (`scp file.txt remote:/home/tobyh/subdir`)
- Supplying a file name destination rather than a directory destination (`scp file.txt remote:subdir/test.txt` or `scp file.txt remote:test.txt`)

In every case I still ended up with the file in the remote home directory (`/home/tobyh`) and named `file.txt`

### Note on downloads

Remote paths do work with scp _downloads_. `scp remote:subdir/file.txt Documents` will take the file from the remote subdir and put it in the local Documents directory as expected.

**Comment by carloscabanero** [comment]
I will check.

**Comment by tobyh** [comment]
I tested this on the new TestFlight version 15.0.7.533. The specific issue is fixed, thanks. The following all now work as expected (although the file path in the output is a bit misleading):

```
# upload to relative path
blink> scp file.txt remote:temp
/temp/file.txt  6/6     0.00kb/S

# upload to absolute path
blink> scp file.txt remote:/home/tobyh/temp
/temp/file.txt  6/6     0.00kb/S

# upload to absolute path
blink> scp file.txt remote:~/temp
/temp/file.txt  6/6     0.00kb/S

# upload with no path
blink> scp file.txt remote:
/file.txt       6/6     -kb/S

# upload with different file name
blink> scp file.txt remote:temp/elif.txt
/temp/elif.txt  6/6     -kb/S
```

There are some regressions though:

### Upload multiple files

I was previously able to upload multiple files in one scp command, but it now only accepts two args 

```
blink> scp one.txt two.txt three.txt remote:
2 unexpected arguments: 'three.txt', 'remote:'
```

### Download from relative path

Relative paths used to work, but now I need an absolute path

```
blink> scp remote:temp/file.txt .
Copy failed. Fail(msg: "Could not canonicalize path - SFTP server: No such file")
blink> scp remote:~/temp/file.txt .
...A8BE32-F358-4513-BC13-CFEE624B3B04/home/file.txt     6/6     -kb/S
```
