### ISSUE TITLE
iOS Display Zoom makes SmartKeys bar on iPhone unusable

### ISSUE THREAD

**Issue by lukasbestle** [blinksh/blink#1416]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink 15.0.5.526 (App Store)
iOS 15.3.1
iPhone 13 mini

Enabled iOS "Display Zoom" in Settings > Display & Brightness > View

### Describe the bug

If iOS Display Zoom (larger UI) is enabled, the modifier bar with the SmartKeys is displayed too large and it is no longer possible to access the middle set of keys (tab etc.):

![IMG_E02C23F9B20B-1](https://user-images.githubusercontent.com/1595007/155895883-d7f1a301-e612-4bb1-9ec7-470ead36911b.jpeg)

Please adapt the SmartKeys bar to the zoomed display mode.

**Comment by yury** [comment]
@carloscabanero I believe you have same model. Can you test it on latest blink?

**Comment by carloscabanero** [comment]
I was able to reproduce it. It may probably be an issue on other phones under that mode too, and the simulator can replicate it. Will fix.

**Comment by yury** [comment]
@carloscabanero  Hmm, where is settings for zoom on simulator?

**Comment by yury** [comment]
ok, I found it under Developer menu in settings...

**Comment by yury** [comment]
I prepared two releases with fixes:

- v16.0.2 Build 617 for Test Flight
- v16.0.2 Build 618 for App Store

**Comment by yury** [comment]
Closing this issue. Feel free to reopen if needed.
