### ISSUE TITLE
It seems iCloud sync has never worked on my devices after upgrading 14 - 15, is that just for me or is that a global issue?

### ISSUE THREAD

**Issue by jaclu** [blinksh/blink#1417]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

V15.0.5.526
### Describe the bug
After adding a host where I was warned it was a duplicate name, I changed it to something else. After this My iCloud sync was empty except for the new host, which I deleted.

At this point I disabled iCloud sync on my iPhone, since I still had a valid host list there.

Various iPadOS & Blink restarts turning iCloud sync on/off later, host list was still empty. At that point I deleted and re-installed Blink.
Again several iPadOS & Blink restarts later still no hoses.

I opened Files and went to iCloud, no blink item was mentioned there, but by searching for blink several items were listed.
One file Blink (under 1k in size), one Folder Blink, with a date around 2021-10-xx probably last time I added a host, and one identically named folder Blink, from Feb 13 (Not 100% it could be +/- one day or so), when I belive I first installed Blink 15. This folder had the status of an up-arrow and "Waiting..." I deleted all three. And did the same on my iPhone, to make sure I did not have any out-of-sync iCloud items that might collide, unfortunately, I did not save a screenshot or realised that the Feb 13(?) date might have relevance.

After restarting my iPhone, I turned on syncing there again, since I thought this would be my sync source, and then went to the iPhones iCloud folder and searched for Blink again.
To my worrying surprise, I got what is in the below screenshot, what appears to be Blink unable to sync. At that point, I remembered that the previous "Waiting..." was the date of the Blink15 installation. Does this mean that sync has never worked in Blink 15?
I guess this would explain why I couldn't sync any hosts to my iPad, the bug that Blink lost all my hosts in the first place is a separate issue, but it has already been filed in #1413, so I focus on if there even is any syncing going on at all in Blink at all in its current state?

Up to this point, I had not added any hosts, and at the 15 upgrade point, I synced both devices from their 14 settings and had not given the functionality of the syncing any thoughts until now.

Oh and half an hour after the screenshot I have synced other stuff between my devices both ways via iCloud with success, only the Blink folder is stuck in Waiting... state.

Screenshot from my iPhone, Since it is not syncing I have not bothered to try to activate sync on the iPad.

![1BB5C830-E87D-4031-AF03-CECB0F8126E2_1_105_c](https://user-images.githubusercontent.com/5046648/155895661-a7a577b4-4a1d-4521-bf08-9d62bee5b87b.jpeg)

**Comment by carloscabanero** [comment]
Hi! Let's see if we can figure out what is going on. Two different problems though. File syncing on Files.app over iCloud is completely different from iCloud host syncing. For the former, try to do a `rm iCloud` in a shell to see if that resets things. That folder is outside of our control and syncing depends on the Files.app.

Now, for what we should be able to fix. First make a backup of .blink/hosts file in the device you want to use as "master" while we figure out what is going on. From what you explained, I guess that would be your iPhone.

Also, if the Host list comes from an imported Blink 14, please note that in the last version 526 (the one you have), we fixed an issue with iCloud imports. If you imported the hosts **before** that, we would recommend to perform the import again. So always make sure you create the list with the new version 526.

Unfortunately, if none of this works we enter into uncharted iCloud territory, as iCloud is a blackbox. We do not have many complaints and usually things fix on their own after a few back and forths and tests. What I would suggest is:

1. Disable iCloud on all your devices and after backing up .blink/hosts, delete it from all your devices.
2. Enable iCloud on a single device, and go back and forth opening the Hosts settings, restart the app, see if any Host from iCloud comes in. Delete it if it does. Delete the .blink/hosts file again.
3. Then on that single device with iCloud turned on, create a new host. Go back to the host list, and wait a few seconds. Turn on iCloud on a different device and go to the host list. Restart the app if it did not show up. And restart iCloud again.
4. If that single host went through, then copy the backup host to .blink/hosts. Do NOT remove the backup file just in case. The rest of the hosts should come through.

Hopefully the whole process should restart the iCloud database for you. On our side there is no rocket science. We have an iCloudID that should be empty, if that iCloudID is not empty then the host tries to sync from their database. Having an empty host list from your side should display what's in the DB. There isn't much we can do from our side, iCloud unfortunately does not give us all the tools we need and very very few cases like yours (2 last year) just require some magic on their side to work.

**Comment by jaclu** [comment]
Im still a bit stuck, procedure:
1. Ensured iCloud sync was offf.
2. tar cvfz .blink blink-config.tgz
3. scp the tar file to another computer
4. removed Blink 14 & 15 from both my devices
5. In Files app under iCloud searched for Blink, and removed all "Waiting..." blink items, as in the previous screenshot I sent on all my devices.
6. Since the config was for Blink 14, I installed Blink 14 on my iPad.
7. Started it and ensured iCloud sync was off.
8 Searched for "Blink" in Files iClod, found a waiting... item with the Blink 14 app icon...
9 stopped Blink to ensure it was not running by scrolling up and sliding it off the screen to remove it from the list of running apps
10 removed the Blink waiting item
11 Rebooted the iPad, Restarted Blink 14
12 Settings, ensured iCloud sync was off
13 Checked the Files app, and now the waiting... Blink 14 item was present again, not recent, in the iCloud drive tab, just to be clear, I was always referring to the iCloud Drive, not the Recents.

Question 1 You suggested to `rm iCloud` in a shell, I have both a-Shell and iSH that could do such a task, I didn't find any such option inside Blink 14. That sounds like potentially globally destructive, if I actively request to delete iCloud, would that not actually delete all my iCloud files? So would appreciate a bit of clarification on this step.

Question 2, The reason I tared the entire config was to hopefully save my 25 Custom Presets if taring the entire .blink hierarchy is a faulty approach, is there some possibility to save my presets? Either way, since Blink 14 creates a failing Blink item in iCloud even when not requesting to sync, how do I prevent that from happening. I was thinking that perhaps my initial trouble was that I didn't disable iCloud sync in Blink 14 as I Installed Blink 15 and synced Blink 15 from Blink14? Any suggestions?

 I removed both Blink 14 & 15 on both my devices. Before that I tared .blink from my working Blink 14

**Comment by jaclu** [comment]
"with the new version 526." Does not compute for me, neither Blink 14 nor Blink 15 has that sequence in their version strings.

Im still a bit stuck, procedure:
1. Ensured iCloud sync was offf.
2. tar cvfz .blink blink-config.tgz
3. scp the tar file to another computer
4. removed Blink 14 & 15 from both my devices
5. In Files app under iCloud searched for Blink, and removed all "Waiting..." blink items, as in the previous screenshot I sent on all my devices.
6. Since the config was for Blink 14, I installed Blink 14 on my iPad.
7. Started it and ensured iCloud sync was off.
8. Searched for "Blink" in Files iClod, found a waiting... item with the Blink 14 app icon...
9. stopped Blink to ensure it was not running by scrolling up and sliding it off the screen to remove it from the list of running apps
10. removed the Blink waiting item
11. Removed the Blink item from Recently Deleted on the iPad, on the iPhone there was no such item in Recently Deleted as could be expected.
12. Rebooted the iPad, Restarted Blink 14
13. Settings, ensured iCloud sync was off
14. Checked the Files app, and now the waiting... Blink 14 item was present again, not recent, in the iCloud drive tab, just to be clear, I was always referring to the iCloud Drive, not the Recents.

Question 1 You suggested to `rm iCloud` in a shell, I have both a-Shell and iSH that could do such a task, I didn't find any such option inside Blink 14. That sounds like potentially globally destructive, if I actively request to delete iCloud, would that not actually delete all my iCloud files? So would appreciate a bit of clarification on this step.

Question 2, The reason I tared the entire config was to hopefully save my 25 Custom Presets, all crafted with the painful conversion of esc-sequences into HEX. If taring the entire .blink hierarchy is a faulty approach, is there some possibility to save my presets? Either way, since Blink 14 creates a failing Blink item in iCloud even when not requesting to sync, how do I prevent that from happening. I was thinking that perhaps my initial trouble was that I didn't disable iCloud sync in Blink 14 as I Installed Blink 15 and synced Blink 15 from Blink14? Any suggestions?

**Comment by carloscabanero** [comment]
Apologies for not getting back to you earlier. 

I may not have explained myself clearly as it looks like we are still mixing iCloud sync for your Hosts, etc.. with the iCloud Files app. Two completely different things. My instructions were on how to try to fix the iCloud sync for your hosts. For that, you should only have Blink 15. iCloud sync will not import from Blink 14. So just use Blink 15 after all your settings and the receipt is imported. 

Question 1. Blink is also a shell so you can do `rm iCloud`. When you remove iCloud, you are only removing the iCloud File Storage in your account for the Blink folder, not the whole of your iCloud storage (Blink doesn't have access to that).

Question 2: Cannot explain the failed iCloud link on Blink 14. That is really an issue with the Files.app itself and you may be running into a bug with it. After importing all your settings from Blink 14 to Blink 15, feel free to delete Blink 14.

**Comment by jaclu** [comment]
That actually worked! I still have those waiting to sync in the Files app, but since it doesn't relate to any Blink sync issues, I will just ignore it. Since both devices now sync I will close this since on a practical level my issue is resolved
