### ISSUE TITLE
Code: cannot sign in to Github repository using SAML authentication (no redirect to identity provider JumpCloud).

### ISSUE THREAD

**Issue by cloudspinner** [blinksh/blink#1419]
### Checklist

- [ x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ x] Read the [docs](http://blink.sh/docs/)
- [ x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink Version: v15.0.5.526
iOS: 15.2.1 (iPad Pro 12,9 inch 5th generation)
Installed the blink-fs add-on in VS Code
SAML single sign-on provider: JumpCloud

### Describe the bug

I have a Github Codespace in a private repository of a Github organization that requires SAML authentication from identity provider JumpCloud.

**Steps to reproduce the issue**

1. Open codespace using `code [codespace-url]` in the new Blink 15 shell
2. When greeted with the Github message “Authenticate your account by logging into [my organization]’s single sign-on provider.”, press “Continue”
3. Get stuck on screen with message “You are being redirected to your identity provider in order to authenticate.” No redirects. (see screenshot)
4. Manually open link in the “If your browser does not redirect you back, please [click here] to continue”-message. This opens the authentication screen of my authentication provider (JumpCloud). (see detail for layout of link)
5. Fill in authentication data. This redirects to the organization page within Github with an unspecified error banner “Invalid SAML message:”

**Expected behavior**

After step 3 a redirect to the identity provider (JumpCloud), and a redirect back to VS code after authentication.

![Redirect](https://user-images.githubusercontent.com/36537951/155972678-63a2c5bc-e130-46a0-bc9b-1078dcee900d.png)

<details>
  <p>The link to the JumpCloud identity provider has the following layout:</p>
  <pre>https://sso.jumpcloud.com/saml2/github-com?RelayState=[snip]&SAMLRequest=[snip]</pre>
</details>

**Alternate steps**

A similar problem with SAML authentication redirection occurs with these alternate steps:

1. Open VS Code by typing `code` in the shell, without an url. 
2. Click on “Allow” when the message “The extension ‘GitHub Repositories” wants to sign in using GitHub” appears. (see screenshot)
3. Click on “Open” when the message “The browser interrupted the opening of a new tab or window. Press ‘Open’ to open it anywas” appears. (see screenshot)
4. Click on “Continue” when the message “Authorize Visual Studio to access GitHub” appears. (see screenshot)
5. Click on “Authorize” when the message “Single sign-on to your organization” appears. (see screenshot)
6. Get stuck on the same “You are being redirected to your identity provider in order to authenticate.” message as step 3 from the previous description.

![Sign in](https://user-images.githubusercontent.com/36537951/155983850-db1d1eaa-7e17-43eb-8c11-b5508cc5c037.png)

![interrupted](https://user-images.githubusercontent.com/36537951/155983812-2fef6130-2ee5-4794-b952-2275a824aa7d.png)

![Authorize visual code](https://user-images.githubusercontent.com/36537951/155984741-cd15b0ba-9040-4345-a7d3-a09c1e9bf447.png)

![SSO GitHub](https://user-images.githubusercontent.com/36537951/155986076-3256c2b9-7019-4e44-a52d-bf09512fee82.png)

![vs code redirected](https://user-images.githubusercontent.com/36537951/155987020-1c8b48a5-0b73-477c-b142-1ed5f9905c1e.png)

**Comment by carloscabanero** [comment]
Unfortunately, this flow will not work until Apple approves our request for the browser entitlement. They already got back to us, so we are getting close.

Related to #1392. Leaving open in case someone else has a similar issue.

**Comment by cloudspinner** [comment]
Fixed, since Apple approved the request for browser entitlement (https://developer.apple.com/forums/thread/700605). 👍
