### ISSUE TITLE
SSH port forwarding

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#142]
Now that Blink is on the App store and we may look to the future, I'm just going to put this feature request out here: SSH port forwarding

**Comment by carloscabanero** [comment]
Definitely another killer feature ;)

**Comment by sukima** [comment]
I think the Apple terms of service prevent this. However, since it is open sourced those who side load it could have port forwarding enabled. Just the production store version would need port forwarding disabled or it would be rejected by Apple. I think.

**Comment by goerz** [comment]
There are some apps on the app store (e.g. [vSSH](http://www.velestar.com/Pages/VSSHIOSPage.aspx)) that provide port forwarding

**Comment by jucor** [comment]
That would be great! [Termius](https://itunes.apple.com/us/app/termius-ssh-shell-console/id549039908?mt=8) has it, so I imagine it's not violating Apple's ToS. That and AgentForwarding are the two reasons I'm still using Termius occasionally.

**Comment by goerz** [comment]
I figured out a [workaround](https://michaelgoerz.net/notes/accessing-a-jupyter-notebook-server-through-reverse-port-forwarding.html) that allows me to connect the iPad to a jupyter notebook, so having port forwarding in Blink (and a built-in browser, #143) has become a little less pressing (but would still be a very nice feature)!

**Comment by rberenguel** [comment]
I'd love port forwarding, it's essentially the only way to access EMR backed Zeppelin notebooks

**Comment by lfxc** [comment]
+1   port forwarding would be excellent!

**Comment by carloscabanero** [comment]
Moving to libssh, we are rewriting a good chunk of the ssh client. If done well, these might come almost for free.

So how do we want this to work? Would the usual -L incantation be enough for a first release?

**Comment by jucor** [comment]
Yes, completely enough for first release!

**Comment by cwross** [comment]
Another related feature I'd love to see is dynamic port forwarding (ssh -D flag) using SOCKS5 proxy. Thanks!

**Comment by chernesk** [comment]
Would love to see the -D flag supported  as well. I'm also in favor of having a browser that I could swipe to so that I wouldn't have to deal with the iOS timeout of Blink when I'm in the browser.

My use case (it is crazy) is that I ssh into a corporate laptop that then has a vpn connection into my work. I can set up a -D SOCKS5 proxy so that I can get to all work websites from the tablet that I'm connecting with. While most of the use cases might not be as convoluted as this one, I run into similar things more often than not. 

Thanks!

**Comment by zhigang1992** [comment]
Is there a easy way to enable port forwarding in custom build? Try dig through the code and came up empty. :(

**Comment by jhuebner79** [comment]
So, how is this feature coming along?

**Comment by yury** [comment]
I think, it will be next major feature after current release. I will start this next week.

**Comment by manuyavuz** [comment]
Hi Yury,

I see that this issue is moved to `Done`. How can I try this feature? I'm using TestFlight version but ssh still don't have `-L` option.

**Comment by zhigang1992** [comment]
@manuyavuz I think the feature is there. Just not the help text.

**Comment by yury** [comment]
Hi @manuyavuz. 

Can you verify version in ‘help’ command?
It should be ‘Blink: v12.0.37. Oct 20 2018’

![GitHawk Upload by yury](https://i.imgur.com/mib5ABq.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by manuyavuz** [comment]
Hey @yury,

I did an update from TestFlight, now I have it. Sorry for wrong alarm.

Thanks for great tool!

**Comment by peterlewis** [comment]
Hey @yury,

Sorry if this is the wrong place to ask, but is there any chance I could get an invite to the TestFlight build please?

Using App Store version at the moment which is utterly fantastic and I’m keen to contribute to the development and testing.

Many thanks!

**Comment by yury** [comment]
Hi @peterlewis!
Just sent you invite to TF.

**Comment by peterlewis** [comment]
That’s splendid. Many thanks, @yury!

**Comment by rfn01** [comment]
It’s awesome to get forwards - Thanks!  I’ve used port forwards with the linux OpenSSH client, but am having trouble getting things working here.  Does the `-L` option in blink work like it does in OpenSSH?  Hints or suggestions?

**Comment by yury** [comment]
Hi @rfn01,

Yep -L should work as in OpenSSH. For instance `ssh -L 8081:localhost:8080 remote` will forward all requests to 8081 port on iOS device to remote localhost 8080

**Comment by hongtron** [comment]
Is there a way to configure automatic forwarding of ports for specific servers? I know that there is some limited support for `.ssh/config`, but it doesn't appear that `LocalForward` is one of the supported options.

**Comment by hronro** [comment]
@yury `-L` nor work for me

![27AAD09F-3B58-4DE4-A74A-5583DE01ABF5](https://user-images.githubusercontent.com/15059605/116825518-41bf6700-abc2-11eb-8d03-fb5eabf3cea1.png)

Any suggestions?

**Comment by yury** [comment]
@hronro 

Sorry for late response.

Two things here:

1. Try retype command (illegal option <?> usually indicates bad input) 
2. We have way better port forwarding and ssh client in general in our beta in TestFlight if you are interested in testing it, please email me your Apple ID, I will send you invite.

**Comment by carloscabanero** [comment]
Actually, go to community.blink.sh, and sign up there yourself. We should be able to get you up and running in less than a day ;)

**Comment by hronro** [comment]
@yury 
Thanks for your reply. I found it works after I change `127.0.0.1` to `localhost`, so I guess it's probably a bug related to the CLI arguments parser.

**Comment by keflavich** [comment]
I need to tunnel through a gateway (maybe a "bastion"?), i.e.:

`ssh -L port:remote:port host`

which looks like:

`ssh -L 1234:node1-b:1234 host`

in practice.  When I try this, I get:

```
ssh -L 1234:c0709a-s5:1234 hpg
The value '1234:c0709a-s5:1234' is invalid for '-L <L>': Missing <localport>:<bind_address>:<remoteport> for port forwarding.
```

If I give a string without a dash, it works - but it looks like the parser doesn't like the dash in the line?  Is this a bug?

**Comment by yury** [comment]
@keflavich 

Good catch... Fixed.
