### ISSUE TITLE
Files app integration not working on host with non-standard ssh port

### ISSUE THREAD

**Issue by travelingflwr** [blinksh/blink#1425]
### Checklist

- [ ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Issue present with TF versions of both 14 and 15 (latest) but has been an issue for some time.

### Describe the bug

Files app won’t enumerate folders for a host I have that uses 2222 for the SSH port.  It works for hosts that use port 22

Nothing of interest showing in the file provider log and I can see that 3 logins are successful whenever I attempt to access the files for the host. 

blink> cat fileprovider.log
Mar 03 2022, 09:13:22 enumerator [info] NSFileProviderRootContainerItemIdentifier
Mar 03 2022, 09:13:22 enumeratorFor  [info] Enumeration requested

**Comment by travelingflwr** [comment]
Added file provider log output.

**Comment by travelingflwr** [comment]
Also confirmed that sftp is working as expected:

blink> sftp hi3.txt pi.e:~/hi3.txt
/hi3.txt        0/0     -kb/S

**Comment by carloscabanero** [comment]
Hey Amy! Thanks for the report. Quick q, Im not able to replicate this myself (I work from a Build machine and I can connect to the 2222 port). I was wondering if this has may have anything to do with the issue we discussed about links?

**Comment by travelingflwr** [comment]
Update on this one.  The issue ended up being related to symlinks I had in my ~ dir on my pi.  I had a broken symlink present that prevented the filesapp to not work.  After removing the symlink all is good.

Might be one to add to support docs in case someone else runs into it.
