### ISSUE TITLE
Second display mouse support

### ISSUE THREAD

**Issue by DAmisonSSG** [blinksh/blink#1433]
When using the app over Airplay or HDMI on the iPad Pro I can have two screen one with VSCode (on the tv) and a shell on the ipad.

Two issues are 

1) Cant move my mouse from the ipad to the TV

2) When switching the views with shift+cmd+o the vscode screen is then blank on the iPad

Setup :- 
	- 	iPad Pro 12.1"
	- 	iOS 15.3.1
	- 	External display Apple TV and HDMI via usb C dock
	- 	Apple Magic keyboard with built in trackpad

Any ideas if this is expected behavior or an issue?

Thanks

**Comment by carloscabanero** [comment]
We have not optimized `code` command yet for external displays. Last year at WWDC we discussed with Apple that we would love to have access to the trackpad on the remote display. They requested to open a radar and we all know what happens with those. Depending on the resources we have, we may be able to continue improving the experience. Right now I am afraid this will have to be low priority.

**Comment by carloscabanero** [comment]
This was fixed with StageManager and this is as far as I think they can take it. Reading this in retrospective, I didn't see that one coming, lol 🤩
