### ISSUE TITLE
TF build: "head" shell command crashes blink on EOF

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#1434]
### Checklist

- [X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink 15.0.6.531, iOS 15.3.1

### Describe the bug

the `head` shell command, when typed by itself, will crash the shell when `^D` (EOF) is typed.

`head` should exit on EOF when run on STDIN.

**Comment by carloscabanero** [comment]
Fixed 17.3.0
