### ISSUE TITLE
Error display when using htop command

### ISSUE THREAD

**Issue by ducledev** [blinksh/blink#1435]
I’m using iPhone 13 Pro Max and ssh to server, then using “htop” command, but the upper part of the screen is covered, I can’t see the CPU and RAM parameters.

**Comment by yury** [comment]
Hello, 

Is it your fresh install to iPhone 13 Max or you restored/transfer app from backup or older device?

to change current tab layout - tap with 3 fingers, and tap fit/fill/cover.
To change layout for new tabs - config -> appearance -> default layout -> Fit.
