### ISSUE TITLE
External hardware keyboard - Space bar non-functional

### ISSUE THREAD

**Issue by mcondren** [blinksh/blink#1443]
### Checklist

- [X ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ X] Read the [docs](http://blink.sh/docs/)
- [X ] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Latest Blink 15 as of today (15.0.6.528).  IOS 15.4.  iPad Air 5
### Describe the bug

**What happens**
On-screen keyboard works as expected.  Space bar inserts space.  However when plugging in external keyboard to IPad via USB-C cable the all keys seem to work except for space bar.  Instead of inserting a space, space bar highlights the window in teal/blue.

**Expected behavior**
Space bar inserts a space with external keyboard.

**Comment by yury** [comment]
See https://github.com/blinksh/blink/issues/736

I think, it is the same in your case.

**Comment by mcondren** [comment]
That was it, thanks!
