### ISSUE TITLE
Cannot ssh via proxy on iPhone

### ISSUE THREAD

**Issue by anjos** [blinksh/blink#1444]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink version: v15.0.6.528
iOS version: 15.4

### Describe the bug

I have Blink installed on both my iPad and iPhone.  I use it to ssh to remote machines via a proxy.  The configuration is setup to do an iCloud sync.

I can successfully connect to any of the proxied hosts from the iPad.  I cannot connect to the proxied hosts on my iPhone.  On my iPhone, the while connecting to the proxied host, the ssh client asks for "Password:".   If I start the client on the iPhone with `-vvv`, and try to see what is going on, I observe:

```
blink> ssh -vvv proxiedhost
Setting up connection callbacks.
Starting connection to proxiedhost
ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_socket_connect_proxycommand: Executing proxycommand 'ssh -W proxiedhost:22 proxy'
ssh_socket_connect_proxycommand: ProxyCommand connection pipe: [21,22]
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 2
password:Starting connection to proxiedhost
ssh_connect: current state : 2
password:Starting connection to proxiedhost
ssh_connect: current state : 2
password:Starting connection to proxiedhost
ssh_connect: current state : 2
```

This will repeat forever until I CTRL-C.

I expect the client on the iPhone behaves the same as the client on the iPad.

**Comment by anjos** [comment]
PS: If I switch from the ProxyCommand to the ProxyJump setting on the iPad, then I can observe that both the iPad and iPhone will present the same connection issues, as reported.  If I, however, set the ProxyJump on the iPad to the proxy host and then set `none` to the ProxyCommand, then it works again on the iPad.  Not such luck on the iPhone - the same as narrated above reproduces.

**Comment by ChaiTRex** [comment]
This also happens to me. When I use no VPN, I connect fine. When I use the Cloudflare WARP VPN, it almost always does this.

A workaround is to use Mosh and to start the connection without the VPN and then, after connecting, turn the VPN on.

    blink> ssh -vvvv redacted
    Setting up connection callbacks.
    Starting connection to redacted
    ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
    ssh_connect: Socket connecting, now waiting for the callbacks to work
    ssh_connect: current state : 1
    -[IO stream:handleEvent:]: Received POLLOUT in connecting state
    socket_callback_connected: Socket connection callback: 1 (0)
    Starting connection to redacted
    ssh_connect: current state : 2
    Starting connection to redacted
    ssh_connect: current state : 2
    Starting connection to redacted
    ssh_connect: current state : 2
    Starting connection to redacted
    ssh_connect: current state : 2
    Starting connection to redacted
    ssh_connect: current state : 2
    Starting connection to redacted
    ssh_connect: current state : 2
    Starting connection to redacted
    ssh_connect: current state : 2
    Starting connection to redacted
    ssh_connect: current state : 2
    Starting connection to redacted
    ssh_connect: current state : 2
    Starting connection to redacted
    ssh_connect: current state : 2
    Starting connection to redacted
    ssh_connect: current state : 2
    Starting connection to redacted
    ssh_connect: current state : 2
    blink> Session deinit

**Comment by carloscabanero** [comment]
Closing as it is too old to repeat or track. We made a lot of changes to it since then and people are using PJ and PC without issues. Please re-open on Discussions if this is still a problem.
