### ISSUE TITLE
Unable to connect to ssh GitHub and other similar hosts.

### ISSUE THREAD

**Issue by Gex2501** [blinksh/blink#1448]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink: v15.0.7.536 (App Store). Mar 24 2022
iOS version: 15.4.1

### Describe the bug

Following instructions from this link I am unable to verify authentication. I have tried using the -v, -vv, and -vvv options but ssh output nothing. It give a connected to IP_ADDRESS message but nothing else like with normal client computers.
- https://docs.github.com/en/authentication/connecting-to-github-with-ssh/testing-your-ssh-connection

It should either give an error of authentication failing, or the message "Hi USERNAME! You've successfully authenticated, but GitHub does not provide shell access." And then disconnect. 

**Blink Output**
![Blink Output](https://i.imgur.com/jn0DE83.jpg)
**MacOS iTerm2 Output**
![MacOS iTerm2 Output](https://i.imgur.com/ulHcP58.jpg)

**Comment by carloscabanero** [comment]
Should be working on next TF.
