### ISSUE TITLE
Terminal not Diaplaying

### ISSUE THREAD

**Issue by anthonygualandri** [blinksh/blink#1449]
### Checklist

- [X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug

Terminal starts up when codespaces opened. 

![image](https://user-images.githubusercontent.com/12303932/161411724-93c41a9d-8d12-4ca3-a6db-86d76dc01b15.jpeg)

**Comment by carloscabanero** [comment]
This may have been fixed since we are now a browser. And in any other case, it would be an issue with Codeserver itself. Closing here.
