### ISSUE TITLE
Install from .vsix file

### ISSUE THREAD

**Issue by redvex** [blinksh/blink#1455]
VSCode on blink is great, I have my vscode on the go connecting basically to everything, the only thing I miss (or at least I don't know how to make it work) is the ability to load extensions downloaded from the marketplace. I tried to download on the blink home and open vscode from that folder but when I try to install from the vsix file nothing happens.

**Comment by mingjun97** [comment]
Not all VSCode extension are supportted yet. Blink adopt the broswer based VSCode which runs inside browser's sandbox and does not have node runtime. Some kind of extensions must have explicit support for browser based environment to be installed.

**Comment by carloscabanero** [comment]
Yep, @mingjun97 is right. I would suggest to ask the specific extension developers to port their work. Most of them should "just work", and more complex ones we will be able to make them work at one point as well, if we get enough traction on the project behind it.
