### ISSUE TITLE
LaTeX

### ISSUE THREAD

**Issue by dpo** [blinksh/blink#1457]
What would it take to be able to run (pdf)LaTeX & Co. in blink.sh?

Because it seems ios_system is included in blink, would a procedure along the lines of https://michaelgoerz.net/notes/editing-latex-on-the-ipad-with-ivim.html work here?

**Comment by carloscabanero** [comment]
You can compile Blink yourself and add the rest of the tooling for ios_system. We are not exploring that and it is unsupported.

**Comment by dpo** [comment]
Sorry and surprised to see such lack of interest.

**Comment by carloscabanero** [comment]
Sorry if that came out the wrong way. We need to keep ourselves focused and that is why we cannot support every feature. A-shell does a good job at that and we did not feel like replicating it. We are focused on other ways to make those applications work through remote machines.

**Comment by dpo** [comment]
That's too bad but I understand the need to stay focused. It would have been so much more awesome with VSCode... 😢
