### ISSUE TITLE
Files.app can’t authenticate Blink’s storage location

### ISSUE THREAD

**Issue by cansurmeli** [blinksh/blink#1459]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

**iPadOS:** 15.4.1
**Blink:** 15.0.7 (beta - although AppStore version had the same issue)

### Describe the bug

When I go to the Files.app on my iPad, I get a `Content Unavailable` message. In there, it doesn’t give a dedicated message but rather an ambiguous one of simply an unknown error occurred.

**fileprovider.log:**

```

Apr 18 2022, 10:29:49 enumerator [info] NSFileProviderRootContainerItemIdentifier
Apr 18 2022, 10:29:49 itemFor [info] NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
Apr 18 2022, 10:29:49 enumeratorFor  [info] Enumeration requested
Apr 18 2022, 10:29:50 enumeratorFor  [error] authFailed(methods: [SSH.AuthAgent])
Apr 18 2022, 10:29:49 enumerator [info] NSFileProviderRootContainerItemIdentifier
Apr 18 2022, 10:29:49 itemFor [info] NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
Apr 18 2022, 10:29:49 enumeratorFor  [info] Enumeration requested
Apr 18 2022, 10:29:50 enumeratorFor  [error] authFailed(methods: [SSH.AuthAgent])
Apr 18 2022, 10:29:49 enumerator [info] NSFileProviderRootContainerItemIdentifier
Apr 18 2022, 10:29:49 itemFor [info] NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
Apr 18 2022, 10:29:49 enumeratorFor  [info] Enumeration requested
Apr 18 2022, 10:29:50 enumeratorFor  [error] authFailed(methods: [SSH.AuthAgent])
Apr 18 2022, 10:29:49 enumerator [info] NSFileProviderRootContainerItemIdentifier
Apr 18 2022, 10:29:49 itemFor [info] NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
Apr 18 2022, 10:29:49 enumeratorFor  [info] Enumeration requested
Apr 18 2022, 10:29:50 enumeratorFor  [error] authFailed(methods: [SSH.AuthAgent])
Apr 18 2022, 10:29:49 enumerator [info] NSFileProviderRootContainerItemIdentifier
Apr 18 2022, 10:29:49 itemFor [info] NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
Apr 18 2022, 10:29:49 enumeratorFor  [info] Enumeration requested
Apr 18 2022, 10:29:50 enumeratorFor  [error] authFailed(methods: [SSH.AuthAgent])
Apr 18 2022, 10:29:49 enumerator [info] NSFileProviderRootContainerItemIdentifier
Apr 18 2022, 10:29:49 itemFor [info] NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
Apr 18 2022, 10:29:49 enumeratorFor  [info] Enumeration requested
Apr 18 2022, 10:29:50 enumeratorFor  [error] authFailed(methods: [SSH.AuthAgent])
```

## Expected behavior

When I go to the Files.app and choose Blink from the left, I should be able to see the contents.

**Comment by carloscabanero** [comment]
Apr 18 2022, 10:29:50 enumeratorFor  [error] authFailed(methods: [SSH.AuthAgent])

It cannot authenticate. If it is password, are you specifying it explicitly as part of the host config? Have you tried enabling logging for that connection? All that is explained at the docs.

**Comment by cansurmeli** [comment]
Yeah, you are right. I read the docs but I misunderstood the functionality of this Files.app integration even though the configuration screen is pretty obvious. My sillyness.

I thought to somehow connect to the Blink’s local storage. Anyways, I entered the password and all went well.

Thanks.
