### ISSUE TITLE
Italic support request

### ISSUE THREAD

**Issue by geometryolife** [blinksh/blink#1471]
The italic cannot work properly. Do you consider introducing some italic for `source code pro`?

**Comment by rpopic2** [comment]
![BABC886F-D23A-44F1-BD1E-96C78EE0FAB1](https://user-images.githubusercontent.com/8055265/167800339-670d6038-20a1-46af-868d-8094be808350.jpeg)
Hi,
Italic is already supported in blink shell.
It does work for source code pro and other fonts.
Screenshot above is vim on terminal without/or with multiplexer, with cterm=italic setting.

**Comment by geometryolife** [comment]
Think you, I probably know the reason because I used TMUX.
