### ISSUE TITLE
Themes switch independently

### ISSUE THREAD

**Issue by wmorgue** [blinksh/blink#1479]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iPadOS 15.5
Blink + Plan v15.0.7.536 from App Strore

### Describe the bug

I have several color themes.
Sometimes, after closing the window via `CMD + W`, the color theme changes randomly.

Settings —> Terminal —> Appearance —> Theme

In my case I use the `Seti` color theme and after closing the window by CMD + W the color theme changes to the higher `Tokyo Storm`.

![blink bug](https://user-images.githubusercontent.com/24982084/169004810-b7aed053-9c79-4161-a858-97fd145e17a1.png)

**Comment by rpopic2** [comment]
same here
