### ISSUE TITLE
Unable to ssh with blink “Socket error: disconnected”

### ISSUE THREAD

**Issue by v3moreno** [blinksh/blink#1486]
### Checklist

- [X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink iOS v15.0.7536 

### Describe the bug

I am trying to setup a remote server with Hetzner, following the instructions on blink docs. I did all the steps as the page says I am and getting the errors below.

<details>
  <pre>blink> ssh -v ubuntu-2gb-fsn1-1
socket_callback_connected: Socket connection callback: 1 (0)
ssh_socket_exception_callback: Socket exception callback: 1 (0)
ssh_socket_exception_callback: Socket error: disconnected
connError(msg: "Session Exception - Socket error: disconnected")
Error connecting to ubuntu-2gb-fsn1-1. connError(msg: "Socket error: disconnected")
blink> ssh2 -v ubuntu-2gb-fsn1-1
SSHSession:DEBUG:Connecting to 167.xxx.224.xx [167.xxx.224.xx] port 22.
Connected to 167.xxx.224.xx
SSHSession:DEBUG:Failed getting banner
Could not connect to host: Error establishing SSH session.
</pre>
</details>

**Comment by carloscabanero** [comment]
Sorry I missed your message. This looks like a simple connection issue when establishing the socket. I will close it here as it has been quite some time and we are now handling all these in Discussions.
