### ISSUE TITLE
Command-tabbing back to Blink causes unresponsive keyboard

### ISSUE THREAD

**Issue by jsit** [blinksh/blink#1487]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iPadOS 15.5.1, Blink version 15.0.7.536

### Describe the bug

I was switching between Safari and Blink using Command-Tab on an Apple Magic Keyboard, and sometimes when I came back to Blink, it would not be receiving input from the keyboard. I was in Vim, in GNU Shell, over SSH.

Long-pressing on the screen would fix this and they keyboard would work again.

**Comment by carloscabanero** [comment]
I'm unable to reproduce this at all when switching multiple times back and forth. I have even been working with Stage Manager and multiple windows back and forth at the same time on an external display, and I haven't had any issues with Blink's focus. I'm gonna close but please reopen if there is a consistent way to trigger this.
