### ISSUE TITLE
Error loading webview when browsing extensions

### ISSUE THREAD

**Issue by espennilsen** [blinksh/blink#1488]
### Checklist

- [X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink Version v15.0.7.536
IOS 15.5

### Describe the bug

No description loading when I view extensions and produces this error message: "Error loading webview: Error: Could not register service workers: TypeError: Job rejected for non app-bound domain."

Display the extension

![image](https://user-images.githubusercontent.com/86449/173204099-680bf441-1140-4d2f-94cc-b44a6db18536.png)

**Comment by worksofliam** [comment]
This is a known issue.

**Comment by carloscabanero** [comment]
Closing as fixed per reference
