### ISSUE TITLE
Source Control Empty

### ISSUE THREAD

**Issue by markpanado** [blinksh/blink#1492]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug

- Open vscode with command `code remoteserver:/example/path`
- `/example/path` is a git repository, can confirm in another blink terminal tab
- Added changes in `/example/path` via vscode
- No changes log in Source Control tab
- running `git status` in another blink terminal shows changes

### Expected behavior
- Source Control section should show the changes

### Screenshots
In blink terminal:
![](https://i.imgur.com/TbgfXHl_d.png?maxwidth=640&shape=thumb&fidelity=medium)

In blink vscode:
![](https://i.imgur.com/xhwu6sm_d.png?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by carloscabanero** [comment]
This is currently not supported by VS Code itself. We do not have access to the remote file system in that way, but maybe in the future. We will keep it as an idea within our Discussions in case someone may know.
