### ISSUE TITLE
Allow to link Folders in File App Integration

### ISSUE THREAD

**Issue by PhilipJonasFranz** [blinksh/blink#1498]
Currently, it seems that Blink only allows to share single files in the iOS files app. For example:

- Blink is connected to the remote via ssh.
- The remote exposes its home directory containing git repositories.
- On my local device, I want to open a git repository in [Working Copy](https://workingcopyapp.com/).
- Blink as a file provider is grayed out as it seems to be unable to share folders.

Ideally, it would be possible to open a folder from the remote that is shared via Blink. An alternative to this setup is to expose the locations via Samba. But because the samba implementation in the iOS files app seems to be lacking, this approach is not viable.

This page [Texpad Docs](https://www.texpad.com/docs/apps/managing-documents/ios/non-texpad-storage/using-files-app) describes the situation in more detail, starting from section 3.

**Comment by carloscabanero** [comment]
Is this related to https://github.com/blinksh/blink/issues/1499 ?

**Comment by PhilipJonasFranz** [comment]
I don’t think so. As I understand it, this issue is about linking files into Blink to edit them there with Code. What I want to do is expose files from a connected remote device (in my case a raspberry pi) in the files app via Blink, so other apps can use the provided files.

This functionality is already implemented (Hosts > Files.App > Add Location). This works fine and the folder can be accessed in the files app. However, when I try to link entire folders exposed by Blink in another app, say in the Texpad app, Blink is grayed out as a file provider. However, when I only link a single file, it works just fine.

**Comment by carloscabanero** [comment]
Thanks for the clarification.

**Comment by carloscabanero** [comment]
Will fix as part of #1717
