### ISSUE TITLE
DNS and Hostname resolution

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#15]
Accessing a server requires to introduce the IP, as in carlos@123.456.78.90

It would be great to support server name resolution through DNS, and also through .ssh/config file format. This is not consider a major issue as we will have autocomplete for the host, so the parameters of the server will be saved anyway.

**Comment by binaryben** [comment]
As a weird edge case, I am considering registering an emoji short domain for quick access to servers - any DNS/Hostname resolution may need to consider things like that.

**Comment by carloscabanero** [comment]
We now have DNS support and Bonjour with Back To My Mac included too. Feel free to test the emoji's case 💃 and open an issue if it doesn't work correctly.
