### ISSUE TITLE
VSCode menu clicks with iPad Magic Keyboard, Bluetooth mice or trackpads are unstable

### ISSUE THREAD

**Issue by thekeith** [blinksh/blink#1500]
- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read docs
- [x] Checked known issues
- [x] Tested with Magic Keyboard, wired and Bluetooth devices

Details:

* Using VSCode on Blink via the `code` command opens as expected
* VSCode mouse clicks work fine at first, but then any mouse clicks cause the menu to appear/disappear instantly
* Attempting to hold the mouse button to use the menu does not work either
* VSCode then becomes unusable until restarted
* Normal screen touches work without issue

_Will add steps to reproduce shortly, can’t type well because of cat on lap insisting on pets…_

**Comment by carloscabanero** [comment]
I think this is fixed in iOS17. Please reopen if there are still issues.
