### ISSUE TITLE
Clicking links in VSCode crashes blink

### ISSUE THREAD

**Issue by thekeith** [blinksh/blink#1501]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

* iPad OS 15.5 and 16 beta 3 (observed in both)
* Blink 15.0.8.542

### Describe the bug

Blink crashes when clicking a link shown through VSCode console or terminal. Does *not* include GitHub sign-in links.

### Steps to reproduce

1. Utilize any terminal command or extension that pops a VSCode dialog to open a link or creates a link that is clickable
2. Click link
3. Blink crashes

**Comment by yury** [comment]
I was thinking, it is only 16 beta 3. Will look tomorrow.

**Comment by yury** [comment]
really close to this one https://github.com/WebKit/WebKit/pull/1811

**Comment by carloscabanero** [comment]
Fixed on 15.0.9!
