### ISSUE TITLE
Special keyboard bar is not disappearing when connected with hardware keyboard. 

### ISSUE THREAD

**Issue by agluck3** [blinksh/blink#1513]
### Checklist

- [ X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ X] Read the [docs](http://blink.sh/docs/)
- [ X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink: 15.0.9.544
iPadOS 16 - Public Beta
iPadPro 12.9 inch M1
I am also using the more space option on the iPad if that is relevant. 

With the update to the public beta Blink has become pretty unstable in a lot of spots. (Code is behaving weird as well, but when I went back into stage manager things started working better) 
This is the main glaring issue though. When using hardware key the software control buttons (The special buttons that blink adds to the top of the apple keyboard) are not disappearing and it is taking up more of the already limited screen real-estate. 

I do not see anywhere in the config to disable the software keys either. That might be a quick fix option while a more permanent things is developed? 

When hardware keyboard is detected the special system keys should disappear. 

Happy to QA around this if it is a problem specific to the iPad pro.

**Comment by pcho** [comment]
You can turn them off in **Settings** > **Smart Keys** > **Show with external keyboard**. Hope this helps.

**Comment by vorband** [comment]
I can confirm this. iPad Pro 12,9 M1 on iOS 16 public beta, more space option. 

Unfortunately, the workaround from @pcho is not helping.

**Comment by jerryabramson** [comment]
I can also confirm the same bug on iPad Air Gen 5 (M1 chip) with iPadOS 16 Developer Beta 3

**Comment by jerryabramson** [comment]
And still present in beta 4.

Also reproducible in the Xcode iPad simulator running iPadOS 16.

I am on macOS Monterey, but the Xcode beta supports iOS/iPadOS 16.

The following trick is needed to get stage manager turned on for the simulator:

- https://developer.apple.com/forums/thread/708567

- xcrun simctl spawn booted defaults write -g SBChamoisWindowingEnabled -bool true

**Comment by carloscabanero** [comment]
Weird because I do not see it myself with iPad Air M1 and beta 3 or 4. I wonder what the difference may be between our setups. 

In any case, we are planning on redoing and refactoring a few things, this included.

**Comment by agluck3** [comment]
I can provide videos and screen shots if they are needed. I am also willing to do a quick zoom call if that is easier.

**Comment by agluck3** [comment]
> Weird because I do not see it myself with iPad Air M1 and beta 3 or 4. I wonder what the difference may be between our setups.
> 
> In any case, we are planning on redoing and refactoring a few things, this included.

Hey @carloscabanero are you using the “more space” option?

**Comment by agluck3** [comment]
Apple has introduces a lot of weirdness with the new window manager. It is getting better though.

**Comment by carloscabanero** [comment]
@agluck3 Not using the "More Space" option at the moment, as I think two betas ago they were still showing the wrong keyboard there. Did they fix that already?

I understand this was a more generic issue as @vorband seemed like it could not find an easy fix for it. @vorband , are you using the "more space" option as well?

**Comment by vorband** [comment]
Yes, I am using the "more space" option.
It was worse on Public Beta 1. As I just went to Dev Beta 4, it still ist somewhat strange, but usable with some minor glitches when resizing the windows.

**Comment by jerryabramson** [comment]
This indeed seems limited to the display option 'more space'.

With this option **not** enabled, things are ok with Blink.

However, another odd 'feature' of iPadOS 16 (currently on beta 4) is that copy/paste of keyboard contents between apps sometimes requires permission via a popup.

For some reason Blink asks this **every time**, which gets to be a bit much after awhile.

If someone has a branch for me to test, I can try it out on my setup (includes external display, keyboard, mouse).

**Comment by vorband** [comment]
I attached a screenshot running in stage manager on my iPad Pro M1. Blink is set *not* to show the smart keys when using the hardware keyboard.

The screenshot shows the "more space" option. 

![Scaled](https://user-images.githubusercontent.com/4286101/181833446-33107d5b-1709-4158-b368-7f4690eaea2a.png)

It is basically the same in the *regular* space option. 

I just noticed that when I disable the "shortcuts" toggle in the keyboard settings of iPadOS, I can remove the layer , but a grey layer is left which overlays the terminal. I am becoming more and more convinced that this is a beta issue, not  a blink issue. 

![Grey bar](https://user-images.githubusercontent.com/4286101/181834921-ed29a241-3fce-488a-bb56-6273bf0b73c1.png)

**Comment by jerryabramson** [comment]
The size of the Blink window has a big impact.

For a large medium size blink window:
![IMG_1740](https://user-images.githubusercontent.com/21062491/181837643-3d71ca0f-50a7-4b64-83dd-f75ee40ec2f2.jpeg)

For a small blink window:

**Comment by jerryabramson** [comment]
![IMG_1754](https://user-images.githubusercontent.com/21062491/181838187-55c0eb9b-634d-476b-9260-9d1a520f1fe4.jpeg)

**Comment by jerryabramson** [comment]
![IMG_1754](https://user-images.githubusercontent.com/21062491/181838717-a2e02f15-88b3-4803-bbd8-6db5087d60fd.jpeg)

**Comment by jerryabramson** [comment]
I think the underlying issue is that Apple is assuming that applications have windows with some sort of decorations or other artifacts to control them.

Since Blink is a pure 'terminal' with no real UI, they probably never tested anything like it.

I suspect this is a bug with the OS, and not the app.

**Comment by jerryabramson** [comment]
For this size it seems very clean:

**Comment by jerryabramson** [comment]
![CE038C0B-E721-4657-B530-E4F99F46E3D5](https://user-images.githubusercontent.com/21062491/181839349-69619b4c-ce09-4853-ab0e-abf2cd1d5cc0.jpeg)

**Comment by jerryabramson** [comment]
Except for the SEGV's (LOL).

**Comment by d34dh0r53** [comment]
Beta 3 is much better.  You can still see the special keyboard for a second but it hides quickly.

**Comment by carloscabanero** [comment]
As noted in the notes from TF, we tried to make this as pleasant as we can, but there are still cases when it still happens with Stage Manager. We have opened a few bugs to Apple, and now opened a DTS as well, in case they expect us to migrate to a different way of handling things.

We are keeping an eye.

**Comment by kaiiserni** [comment]
On iPadOS 16.1 “stable” the issue still remains. Most of the time the special keyboard bar just stays there, with the option disabled in settings… When you start playing with it, for example connecting and disconnecting the hardware keyboard a number of times, or resizing the window continuously in stagemanager, it does dissapear like it should after a while, only to appear again when you switch windows or even when you just open a new terminal tab…

**Comment by carloscabanero** [comment]
Have you updated Blink as well? We released Blink 16.0.0, and since our last TestFlight build a few weeks ago, when we changed the Smart Keys completely, we have not had any reports of this coming back either here or in Discord.
