### ISSUE TITLE
[Feature] Missing (?) arrow keys on virtual keyboard

### ISSUE THREAD

**Issue by g3rhard** [blinksh/blink#1520]
Hello,

I hope you are doing well :)

Sorry, I didn't found any similar issue - shortly I don't have additional row with special keys (screenshots attached in vertical/horizontal mode).
<img width="1024" alt="Screen1" src="https://user-images.githubusercontent.com/8848216/181729869-1474a902-ed88-485a-8a49-ae88ebd3bc55.png">
![Screen2](https://user-images.githubusercontent.com/8848216/181730235-7c598d2d-905b-49ef-ab41-5fb2b12d5cff.jpeg)

In Buffer Editor I have something like this:
![Screen3](https://user-images.githubusercontent.com/8848216/181730255-cbdd2e87-6905-44c2-b2f3-8d4c0c978450.jpeg)

Can it be added or maybe it's premium feature or I miss some configuration?

Blink version: 15.0.9.544 from App Store.

Best regards

**Comment by yury** [comment]
You should enable shortcuts in system settings.
Settings.app -> General -> Keyboard -> Shortcuts

**Comment by g3rhard** [comment]
Many thanks for you quick and helpful response!
Have a good day!
