### ISSUE TITLE
Telnet: hide password input from terminal (security issue)

### ISSUE THREAD

**Issue by Dentrax** [blinksh/blink#1535]
### Checklist

- [X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Default. iPad.

### Describe the bug

```
$ telnet 192.168.1.1
Login: admin
Password: mypassword
```

Hide password input from terminal. Or use `*` character.

**Comment by carloscabanero** [comment]
We do not implement Telnet ourselves and we just compiled the command as is. I think that telnet, the server is responsible to figure out what to echo to the user and how, based on this as well https://stackoverflow.com/questions/6380257/how-can-i-mask-user-input-when-telneting.

Happy to route this to ios_system in case it is not true.
