### ISSUE TITLE
conflict between app store privacy label and README

### ISSUE THREAD

**Issue by sneak** [blinksh/blink#1543]
The app store privacy label says unequivocally that data is not collected by this app.  Bravo!

However, the README in the repo suggests that crashes will be uploaded by something called HockeyApp.  That's data collection.

Which is correct?

**Comment by carloscabanero** [comment]
Thanks for the heads up! I corrected that. We used HockeyApp to collect info long time ago for our testing version. We do not collect anything tied to a user, except for Subscription information that we use RevenueCat for, and that at the moment is also completely anonymous. https://docs.revenuecat.com/docs/apple-app-privacy

**Comment by sneak** [comment]
Anything that uses a normal IP connection (that is, not Tor) is not "completely anonymous" as it includes the client IP which is city-level geolocation.

Can you confirm that the application does not contact you or any other service provider when used without a subscription?

**Comment by carloscabanero** [comment]
I can confirm that the app does not contact us in any way when used without a subscription or when you compile it yourself. We will update our privacy policy if this changes.

Note that your iOS device may still contact Apple in case of crashes (although I think this is opt-in). Just mentioning here as there is people who use Blink for highly critical jobs and want to point that too.
