### ISSUE TITLE
CHANGELOG outdated, yet website links to it

### ISSUE THREAD

**Issue by fingolfin** [blinksh/blink#1554]
On blink.sh there is a link saying [See What’s New on v15.0.6](https://github.com/blinksh/blink/blob/raw/CHANGELOG.md) which links to the `CHANGELOG.md` file in this repository. Alas, that was last updated 11 months ago, for 14.0.2.

Ideally the CHANGELOG.md would be updated, but baring that, perhaps at least the misleading link could be removed?

**Comment by carloscabanero** [comment]
We are working on updating all that now. I know it does not look good that we have not updated this yet, but we have prioritized going forward on what Blink can do over how we are showing it.

**Comment by fingolfin** [comment]
That's fine, but then I'd still suggest to make this clear: either by removing that link (at least temporarily), or at the very least, editing CHANGELOG.md to say "More recent changelog data is missing and will be added in the future" (of course only if you really intend to do that?)

**Comment by carloscabanero** [comment]
Fixed! Tools us longer than expected, as we were thinking what the proper way of doing this would be. We are now all in with Discussions, plus added `whatsnew` to the app as well.
