### ISSUE TITLE
All (or at least many) internal links for docs.blink.sh are broken

### ISSUE THREAD

**Issue by fingolfin** [blinksh/blink#1555]
Go to e.g. https://docs.blink.sh/basics/navigation or https://docs.blink.sh/advanced/code or really any of the pages I looked at (but I did not check all), and try to use one of the internal links, e.g. on the "Code" page there are links to the hosts and Files.app pages.

They lead to 404 error pages.

The URLs are clearly simply wrong: e.g. it links to https://docs.blink.sh/advanced/advanced/files-app.md instead of https://docs.blink.sh/advanced/files-app

I was about to submit a PR to fix (?) that one instance by editing `code.md`, but then I observed it on several other pages, and now I am wondering what the proper fix is: to edit the .md files (which I could do, though I don't know if it'll have the desired  or edit whatever software/script/config is responsible for this (I have no idea about Nextra.js, so I am afraid I couldn't help with that)

**Comment by fingolfin** [comment]
Aha, I just discovered https://github.com/blinksh/docs/pull/10 so presumably that's the fix and once it is merged this issue can be closed? Sorry for the noise

**Comment by fingolfin** [comment]
... except it only addresses one broken link, and not one of the ones I observed...

**Comment by carloscabanero** [comment]
We recently changed to Nextra and looks like the internal links were not properly generated by it. Will prioritize to fix this asap.

**Comment by carloscabanero** [comment]
Should be fixed now, thanks to @yury

I will do the changelog later today as well so we have a clean house.

**Comment by fingolfin** [comment]
Indeed. Thank you!
