### ISSUE TITLE
Taking over external display with ipadOS16 external display and stage manager

### ISSUE THREAD

**Issue by unlikelylass** [blinksh/blink#1556]
When ipadOS16 has stage manager on and an extended monitor connected, and blink is given focus on the ipad, the secondary display is also taken up with a full-screen blink window that cannot be given focus and does not mirror the main display.  As soon as another app is selected on the ipad, the external display returns to its stage manager view.

**Comment by carloscabanero** [comment]
Thanks for opening this issue! We are aware of this, Blink supports the "old" external displays and now the new Stage Manager. We will have to give an option to choose in case Stage Manager is supported in the device, and still keep the old way for older iPads or iPhones.

**Comment by lilithivey** [comment]
Was coming here to say the same. I'm on a 2021 ipad Pro and it's unfortunately the same here as well.

**Comment by yury** [comment]
it should be fixed on iPadOS 16.2 on MX devices.

Also we will release improvements in Blink 16.0.2.

**Comment by michaelrommel** [comment]
I have now the official release of 16.2 installed. How can I give the focus to the external monitor's window? The mouse pointer only moves to the external monitor when the second display is not controlled by the app, just by the OS.

**Comment by techiemac** [comment]
@yury I’m not sure if this is fixed in 16.2. I’m still seeing the same behavior with the following configuration:
iPad Pro version 16.4.1(a)
Blink version v16.1.7.748 (App Store)

**Comment by techiemac** [comment]
Update. It looks like this [discussion thread](https://github.com/blinksh/blink/discussions/1652) describes a fix from Yuri. With the display unplugged while using stage manager (not sure if the display being unplugged is relevant), I had to change the config->Appearance display settings to Mirror, modify another Appearance setting, click the back button to get the Mirror setting to “stick”. I then quit blink, plugged in the display, and blink is no longer taking over the external display.

**Comment by carloscabanero** [comment]
There is a continuation for this on #1748
