### ISSUE TITLE
Feature Request: Unix-like cal Command

### ISSUE THREAD

**Issue by jasonp019** [blinksh/blink#1557]
Good morning!  I’d like to respectfully request the addition of a Unix-like cal command to the blink.sh shell.  In my workflow, it’s helpful to be able to get a quick calendar like that provided by cal without having to break out of blink.sh and start another heavyweight app or go to the web.

I looked to see if there was such a request in github for blink.sh before making this request but I couldn’t find one.

Thank you!

Very sincerely,

Jason Pfeil

**Comment by carloscabanero** [comment]
This is discussed here: https://github.com/blinksh/blink/discussions/1547
