### ISSUE TITLE
$LANG not set with .blink/profile

### ISSUE THREAD

**Issue by harryhmtse** [blinksh/blink#1562]
### Checklist

- [x ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ x] Read the [docs](http://blink.sh/docs/)
- [ x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
iPadOS: 15.6.1
Blink: 15.0.9.544

### Describe the bug
Changelog from Version [12.5](https://docs.blink.sh/whats-new#changes-in-build-195) and #438 suggests that setting environment variables can be achieved through the .blink/profile file as keypair values.

If $LANG, $LANGUAGE, and $LC_ALL in .blink/shell 
```
LANG=en_CA.UTF-8
LANGUAGE = en_CA.UTF-8 
LC_ALL=en_CA.UTF-8
```
only $LANGUAGE and $LC_ALL are set to the defined variable, while $LANG will remain at the default en_US.UTF-8. 

However if $LANG is set in blink session via setenv, the variable is correclty set for the session.

Expected behavior 
setting $LANG in .blink/shell is set in the blink session

<details>
  <pre>
  blink> cat .blink/profile
  LANG=en_CA.UTF-8
  LANGUAGE=en_CA.UTF-8
  LC_ALL=en_CA.UTF-8
  blink> env
  CFFIXED_USER_HOME=/private/var/mobile/Containers/Data/Application/723FBD3D-A0CC-43C2-AD1D-35F3C24DB65D
  HOME=/private/var/mobile/Containers/Shared/AppGroup/B15E1BA1-3A30-4EB4-B487-7EB9B298C1B2/home
  TMPDIR=/private/var/mobile/Containers/Data/Application/723FBD3D-A0CC-43C2-AD1D-35F3C24DB65D/tmp/
  XPC_SERVICE_NAME=UIKitApplication:sh.blink.blinkshell[beb9][rb-legacy]
  PATH=/private/var/containers/Bundle/Application/33A87A78-FE33-4E41-82F6-F5BDC57581BB/Blink.app/bin:/private/var/containers/Bundle/Application/33A87A78-FE33-4E41-82F6-F5BDC57581BB/Blink.app/Library/bin:/private/var/containers/Bundle/Application/33A87A78-FE33-4E41-82F6-F5BDC57581BB/Blink.app/Library/bin3:/var/mobile/Containers/Data/Application/723FBD3D-A0CC-43C2-AD1D-35F3C24DB65D/Library/bin:/var/mobile/Containers/Data/Application/723FBD3D-A0CC-43C2-AD1D-35F3C24DB65D/Documents/bin:/usr/bin:/bin:/usr/sbin:/sbin
  XPC_FLAGS=0x0
  LOGNAME=mobile
  USER=mobile
  SHELL=/bin/sh
  __CF_USER_TEXT_ENCODING=0x1F5:0:0
  LANG=en_US.UTF-8
  LANGUAGE=en_CA.UTF-8
  LC_ALL=en_CA.UTF-8
  APPDIR=/private/var/containers/Bundle/Application/33A87A78-FE33-4E41-82F6-F5BDC57581BB/Blink.app
  PATH_LOCALE=/private/var/containers/Bundle/Application/33A87A78-FE33-4E41-82F6-F5BDC57581BB/Blink.app/locales.bundle
  TERM=xterm-256color
  CLICOLOR=1
  LSCOLORS=ExFxBxDxCxegedabagacad
  SSH_HOME=/private/var/mobile/Containers/Shared/AppGroup/B15E1BA1-3A30-4EB4-B487-7EB9B298C1B2/home
  DIG_HOME=/var/mobile/Containers/Data/Application/723FBD3D-A0CC-43C2-AD1D-35F3C24DB65D/Documents
  CURL_HOME=/private/var/mobile/Containers/Shared/AppGroup/B15E1BA1-3A30-4EB4-B487-7EB9B298C1B2/home
  SSL_CERT_FILE=/private/var/containers/Bundle/Application/33A87A78-FE33-4E41-82F6-F5BDC57581BB/Blink.app/cacert.pem
  PYTHONHOME=/var/mobile/Containers/Data/Application/723FBD3D-A0CC-43C2-AD1D-35F3C24DB65D/Library
  XDG_CACHE_HOME=/var/mobile/Containers/Data/Application/723FBD3D-A0CC-43C2-AD1D-35F3C24DB65D/Library/Caches
  XDG_CONFIG_HOME=/var/mobile/Containers/Data/Application/723FBD3D-A0CC-43C2-AD1D-35F3C24DB65D/Library/Preferences
  XDG_DATA_HOME=/var/mobile/Containers/Data/Application/723FBD3D-A0CC-43C2-AD1D-35F3C24DB65D/Library
  PYTHONEXECUTABLE=python3
  PYZMQ_BACKEND=cffi
  blink> 
  </pre>
</details>

**Comment by carloscabanero** [comment]
Fixed. Should be out on next TF
