### ISSUE TITLE
Swift Package Manager resolve fails with `BlinkBuild` repository not found error

### ISSUE THREAD

**Issue by kyujin-cho** [blinksh/blink#1563]
### Checklist

- [ ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug

When following build instructions described on README.md, `./get_frameworks.sh` command fails with error `fatal: repository 'https://github.com/blinksh/BlinkBuild/' not found`.

Command should work without error.

<img width="1296" alt="Screen Shot 2022-09-12 at 2 53 10 PM" src="https://user-images.githubusercontent.com/2904494/189582721-336793c9-4d13-4cac-9e53-8e0df98afe23.png">

<details>
<pre>
~/Projects/blink on raw ❯ ./get_frameworks.sh
warning: Usage of /Users/kyujin/Library/org.swift.swiftpm/collections.json has been deprecated. Please delete it and use the new /Users/kyujin/Library/org.swift.swiftpm/configuration/collections.json instead.
Fetching https://github.com/yury/Promise from cache
Fetching https://github.com/onevcat/Rainbow from cache
Fetching https://github.com/yury/FMake from cache
Fetched https://github.com/yury/Promise (0.63s)
Fetched https://github.com/onevcat/Rainbow (0.63s)
Fetched https://github.com/yury/FMake (0.63s)
Fetching https://github.com/yury/Spinner from cache
Fetching https://github.com/dominicegginton/Nanoseconds from cache
Fetching https://github.com/blinksh/swift-argument-parser from cache
Fetched https://github.com/yury/Spinner (0.57s)
Fetching https://github.com/yury/SSHConfig from cache
Fetched https://github.com/blinksh/swift-argument-parser (0.57s)
Fetching https://github.com/blinksh/BlinkBuild
Fetched https://github.com/dominicegginton/Nanoseconds (0.57s)
warning: skipping cache due to an error: Failed to clone repository https://github.com/blinksh/BlinkBuild:
    Cloning into bare repository '/Users/kyujin/Library/Caches/org.swift.swiftpm/repositories/BlinkBuild-7ba87af9'...
    remote: Repository not found.
    fatal: repository 'https://github.com/blinksh/BlinkBuild/' not found
Fetched https://github.com/yury/SSHConfig (0.64s)
Fetching https://github.com/blinksh/BlinkBuild
warning: skipping cache due to an error: Failed to clone repository https://github.com/blinksh/BlinkBuild:
    Cloning into bare repository '/Users/kyujin/Library/Caches/org.swift.swiftpm/repositories/BlinkBuild-7ba87af9'...
    remote: Repository not found.
    fatal: repository 'https://github.com/blinksh/BlinkBuild/' not found
error: Failed to clone repository https://github.com/blinksh/BlinkBuild:
    Cloning into bare repository '/Users/kyujin/Projects/blink/xcfs/.build/repositories/BlinkBuild-7ba87af9'...
    remote: Repository not found.
    fatal: repository 'https://github.com/blinksh/BlinkBuild/' not found
</pre>
</details>

**Comment by fuomag9** [comment]
Same issue but I get stuck with this before that:

```
error: 'xcfs': Invalid manifest
/tmp/blink/xcfs/Package.swift:2:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
```

**Comment by yury** [comment]
Fixed. Please run `./get_frameworks.sh` again.

**Comment by yury** [comment]
Closing, feel free to reopen if needed.

**Comment by kyujin-cho** [comment]
Thanks! Now `./get_frameworks.sh` is working without error. After this I face some errors from XCode complaining about missing `Machines` and `BuildCLI` (which probably originates from `BlinkBuild` module) but it can be fixed by removing and re-adding those dependencies on Blink build target page.
