### ISSUE TITLE
crash after too long input

### ISSUE THREAD

**Issue by boredjo** [blinksh/blink#1566]
### Checklist

- [ x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ x] Read the [docs](http://blink.sh/docs/)
- [ x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

I am using blink version 15.0.10.572 on iPad OS 15.6.1

### Describe the bug

When I put in a really long string as a command like:
``` 
blink> nPjkFpCXMsnPjkFpCXMsdS3AxKxbFIr2BlxI5mbLynnPjkFpCXMsdS3AxKxbFIr2BlxI5mbLynnPjkFpCXMsdS3AxKxbFIr2BlxI5mbLynnPjkFpCXMsdS3AxKxbFIr2BlxI5mbLynnPjkFpCXMsdS3AxKxbFIr2BlxI5mbLynnPjkFpCXMsdS3AxKxbFIr2BlxI5mbLynnPjkFpCXMsdS3AxKxbFIr2BlxI5mbLynnPjkFpCXMsdS3AxKxbFIr2BlxI5mbLyndS3AxKxbFIr2BlxI5mbLyn
```
Then blink crashes and loses all tabs 

 
 I would expect blink to throw an error like command too long

**Comment by carloscabanero** [comment]
Thanks for the report, and good catch! This is an issue with ios_system, checked on a-shell too. Given how this is a misuse and that we may probably move to a different way of doing things, we won't be prioritizing this at the moment. Hope you understand.
