### ISSUE TITLE
mosh-server is always invoked with -c 256

### ISSUE THREAD

**Issue by majick** [blinksh/blink#1569]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

default configuration

### Describe the bug

When blink invokes mosh-server it passes what seems to be a hard coded `-c 256` which completely disables 24 bit direct color.  The `-c` parameter is not accepted in the configuration UI nor at connection time.

The docs claim that Blink supports direct color modes, which it does given the recent hterm, but it can't actually be used without ugly hacks.

### Totally ugly workaround:

1. Make a wrapper script and chuck it in the user's `bin`

```
#!/bin/sh
exec /usr/bin/mosh-server new -s -c 16777216 -l LC_ALL=en_US.UTF-8
```

2. modify the host configuration's "Server" field to: `/home/user/bin/mosh-wrapper`

**Comment by carloscabanero** [comment]
If I recall, this does not have any impact on using true color. For that you have to compile mosh-server from mosh’ main branch. We do that ourselves already for Blink Build, and Blink Shell mosh client should support it out of the box.
