### ISSUE TITLE
how to use hosts configuration in terminal

### ISSUE THREAD

**Issue by zhuyiaachen** [blinksh/blink#157]
Please add some information to tell users how to use predefined hosts configuration in terminal. I'm using mosh to connect to server, but I must input ip address every time. I cannot find how to use predefined host name to simplify this action.

**Comment by carloscabanero** [comment]
Thanks a lot for your report. We'll add a comment on the Hosts sections to show how it has to be used. The information is already on the help for mosh or ssh, and it should just be as easy as doing "ssh or mosh [hostname]", as you do at your computer. You might have tried that already and there might be something more going on, please let me know!

**Comment by zhuyiaachen** [comment]
Great, it works now! Thank you carloscabanero for your help;-)

**Comment by carloscabanero** [comment]
Completed on v1.101
