### ISSUE TITLE
Selection with right click isn’t working

### ISSUE THREAD

**Issue by pcho** [blinksh/blink#1593]
### Checklist

- [x] Using latest TestFlight version, but AppStore also has this bug
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iPad Pro (12.9-inch) (4th generation), iPadOS 16.1 (20B5072b), Blink: v15.0.11.591 (Test Flight). Oct 10 2022

### Describe the bug

When selecting with mouse and using right button with context menu, selection disappears. Works fine with finger tap.

https://user-images.githubusercontent.com/41922527/195165555-030fb895-0b4a-4d97-82f4-7c330687fe2a.MOV

**Comment by yury** [comment]
Fixed in blink v16.1.4

**Comment by yury** [comment]
![IMG_0404](https://user-images.githubusercontent.com/5250/220908948-41bca41b-23f1-4cef-bf02-3fb173f90c43.jpg)
![IMG_0406](https://user-images.githubusercontent.com/5250/220908972-e09d7c26-2944-462d-be81-2cb1f15e854e.jpg)
