### ISSUE TITLE
Visual Artifact when running lunarvim/doomemacs

### ISSUE THREAD

**Issue by JeffLabonte** [blinksh/blink#1594]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug

I use lunarvim with `tmux` and mosh on debian. I simply have to configure `lunarvim` for rust. I can reproduce the issue by switching apps and coming back to blink. It happens especially when I have unit tests in rust.

![Screenshot 2022-10-11 at 8 20 07 PM](https://user-images.githubusercontent.com/9425955/195221438-e7ccd1eb-bd6e-472d-9825-9e009680f274.png)

**Comment by carloscabanero** [comment]
Looks like some issue with a sequence. Could you try if this also happens over SSH outside / inside tmux, and with mosh outside tmux?

**Comment by JeffLabonte** [comment]
Yes sure!

**Comment by JeffLabonte** [comment]
It only works when I am using ssh.

I have some weird colors when I am using mosh without tmux

![Screenshot 2022-10-11 at 9 15 29 PM](https://user-images.githubusercontent.com/9425955/195226952-cdfbacb4-de88-408c-bc39-4109a0dc720a.png)

**Comment by JeffLabonte** [comment]
@carloscabanero To me, it seems like there is something wrong with my `mosh` configurations. 

FYI, I also had this issue for a long time; I just didn't have time to create an issue on GitHub. I used VMs on DigitalOcean, AWS and now my own server. They all had this behaviour with DoomEmacs and LunarVim. Especially with Rust, since the editor adds this `Run | Debug` greyed-out text.

**Comment by carloscabanero** [comment]
This is definitely on Mosh side. May be related to #1617 

Revisit once we fix that.

**Comment by carloscabanero** [comment]
Hey, just a heads up that we updated Mosh a while ago. Closing here but feel free to reopen if this is still an issue.
