### ISSUE TITLE
Required Student License

### ISSUE THREAD

**Issue by hsayed21** [blinksh/blink#1597]
### How to get student license?

**Comment by yury** [comment]
Send email to hello@blink.sh

**Comment by hsayed21** [comment]
I send but no reply

**Comment by hsayed21** [comment]
@yury

**Comment by yury** [comment]
May be I missed that email, but I can't find it. Can you please send it again?

**Comment by hsayed21** [comment]
Sure

**Comment by hsayed21** [comment]
I send now
With subject: Blink Shell | Student Licence

**Comment by hsayed21** [comment]
@yury

**Comment by yury** [comment]
Still nothing....

**Comment by yury** [comment]
You can dm @Yury at discord 
https://discord.gg/RnNWvTdD

may be it will be faster

**Comment by hsayed21** [comment]
Ok
