### ISSUE TITLE
Suggestion: Adding system font support inside `browse`

### ISSUE THREAD

**Issue by pcho** [blinksh/blink#1599]
It would be awesome and useful if `browse` could access system fonts installed either by special apps or profiles. That would come super handy for Figma users. :)

**Comment by yury** [comment]
For Figma it will not work out of the box.

I did research a little bit in that area. To access system fonts you have to install `FigmaAgent`.

It is simple service that runs locally on your machine and respond to `https://figmadaemon.com:44960`.
Domain figmadaemon.com is pointing to 127.0.0.1.

So figma.com make following requests:

1. `curl 'https://figmadaemon.com:44960/figma/font-files?freetype_minimum_api_version=20' -H 'Origin: https://www.figma.com'` to get list of available fonts
2. `https://figmadaemon.com:44960/figma/desktop/can-open-url` (don't know for what)
3.  and finally request font itself ` https://figmadaemon.com:44960/figma/font-file?file=%2FSystem%2FLibrary%2FFonts%2FSupplemental%2FNotoSansLimbu-Regular.ttf&freetype_minimum_api_version=20`

So, it is not hard to implement that agent inside blink. We just need to understand that json structure.

**Comment by yury** [comment]
Note:

https://github.com/neetly/figma-agent-linux

and it is in Rust!

**Comment by carloscabanero** [comment]
I think we can close this as out of the scope of Blink.
