### ISSUE TITLE
Can't send ENTER inside tmux session

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#16]
Reported by @cirqueit

Also happens when using `fzf`. 
Nothing happens when normally it would enter the command typed in. This makes tmux not work.

**Comment by rekendahl** [comment]
This can also be seen in VIM's nerdtree where opening a directory by hitting enter doesn't work. I wonder what's causing it!

**Comment by carloscabanero** [comment]
Do you know exactly when does it happen on TMUX? Typing there works so I assume it must be during some special mode.

**Comment by rekendahl** [comment]
It's been intermittent for me. But I've been stuck with no enter in Vim for a full day now. I wonder if tmux server gets in a whacky state. 

I'd say lets test the next build and see if it's still there.

**Comment by carloscabanero** [comment]
It might be because I'm sending a newline feed, but should actually be a carriage return. D'oh!

**Comment by rekendahl** [comment]
That would do it!

**Comment by cirqueit** [comment]
Awesome. This plus the CAPS fix. Excited for the next build.

**Comment by rekendahl** [comment]
I think this is the. If and I realize that in VIM I rarely use enter. I tend to esc + O(pen) a lot for undo reasons. So now I think enter never worked!

Looking forward to next release!

**Comment by cirqueit** [comment]
Working great!

Think you can close this.

**Comment by carloscabanero** [comment]
Yeeeyyyy!!!!
