### ISSUE TITLE
Can’t Create _sk SSH Keys even though I have Blink+, with the program saying don’t have Blink+

### ISSUE THREAD

**Issue by kademahler** [blinksh/blink#1602]
I can’t seem to create or use _sk keys even though I have blink+, and have even restarted my device, etc. It keeps telling me I still need blink+. I also uninstalled and reinstalled the app.
![E5389F31-308B-4422-9DF5-774ABD14DEEE](https://user-images.githubusercontent.com/77070667/197849679-a51fc296-6b9b-4a6c-9928-8d7a9dc23859.png)
![CB3622EA-1F7B-4F4C-8855-46C2EBC855B8](https://user-images.githubusercontent.com/77070667/197849701-3f4b7cb3-05ee-475a-b199-bf6216325abf.png)
![A23FA8BD-ABAC-4F79-BC6E-B8E04B5E0884](https://user-images.githubusercontent.com/77070667/197849709-4959c1f7-9dae-496d-b1e3-3ca28302a95e.png)
![CD6041B1-B293-49AC-BCA7-9BFE9850F3B6](https://user-images.githubusercontent.com/77070667/197849720-4c139542-26db-4a3c-a233-99bb50c11f7f.png)

**Comment by yury** [comment]
Thank you for your report. Pushing v16.0.1 with a fix to App Store.

**Comment by kademahler** [comment]
This appears to be fixed in the new version. Thanks!
