### ISSUE TITLE
Closing the What's New window

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#1604]
We have received a few questions on Discord on how to close the What's New window. This is a new scene that will hopefully become popular on iPadOS 16, and that we may use in the future for other use cases. It can be closed sliding it down or using the three dots on top (the new window handle). 

Right now, and given how all the iPadOS 16 testing of Stage Manager and Window handling is going, it is just confusing. We will downgrade to a regular sheet.

**Comment by Lorn888** [comment]
why is my blink shell taking 100gb sorgage ?

**Comment by yury** [comment]
Hi @Lorn888.

Can you send screenshot of Settings.app -> iPad/iPhone Storage ->  Blink.

![IMG_0347](https://user-images.githubusercontent.com/5250/198230999-69c15e5c-9eb3-4847-8f04-4201aba4c2c9.jpg)

**Comment by Lorn888** [comment]
I have been using it with my raspberry. I downloaded stuff on my pi and than downloaded it in the files app via ssh. But even if I delete it the size just keeps growing. 
![image](https://user-images.githubusercontent.com/98765021/198249579-45734d8f-9e67-4644-9cef-0c29048fa840.jpeg)

**Comment by Lorn888** [comment]
![image](https://user-images.githubusercontent.com/98765021/198250896-0c269c73-3f21-433a-bbd0-0812aa04e324.jpeg)
Sorry The app itself is normal size but the contents seem to stay there even if I delete them

**Comment by yury** [comment]
No idea yet... investigating.

Do you use Files.app integration?

or may be you have hidden files on your home folder?

**Comment by Lorn888** [comment]
Here you can see my sorage before: 
![image](https://user-images.githubusercontent.com/98765021/198264108-e3bcd18e-20c0-4d79-a76c-1cb6a0e789d2.png)

Here I'm going to get black Adam file from my raspberry:

![image](https://user-images.githubusercontent.com/98765021/198264465-7254ecc9-d50f-4f64-83b1-251dd9876d66.png)
![image](https://user-images.githubusercontent.com/98765021/198264500-3ebba6c2-04f1-4635-b404-11496970c689.png)
![image](https://user-images.githubusercontent.com/98765021/198264831-aa8778cc-75e1-46dd-aef5-79a32ef63fec.png)

Here you can see space taken increased:
![image](https://user-images.githubusercontent.com/98765021/198264898-694cd029-e929-45af-bef2-a00af389be8b.jpeg)


Now I'm deleting the file:
![image](https://user-images.githubusercontent.com/98765021/198264921-a54c50dd-d5f3-4f79-a6e5-1f6014cb089a.png)

But storage stayed the same: 
![image](https://user-images.githubusercontent.com/98765021/198264953-aef0ce39-b3f0-49db-b729-a7d9d02aa826.jpeg)

**Comment by carloscabanero** [comment]
Blink keeps the files around until iOS claims back the storage. We may figure out a different way of handling this though. For now, the cache is stored in an upper directory, File Provider Storage. You can remove the cache manually, doing `rm -rf ../File\ Provider\ Storage`

**Comment by carloscabanero** [comment]
Please let's keep the discussions to the topic of the conversation. This was the What's New screen! ;)

**Comment by Lorn888** [comment]
Sorry for posting here and, thank you carlos, worked like a charm
