### ISSUE TITLE
iPhone 14 Pro Smart Keys bar issue

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#1605]
Reported from Twitter. Fixed on 16.0.1, but will keep an eye in case there may be other issues. Please let us know! Adjusting the keyboard bar requires some manual tuning and sometimes having access to the real device helps.

![image](https://user-images.githubusercontent.com/536729/198063017-63c6b93d-88cc-4b72-8532-941d4d23bde1.png)

**Comment by phonefixnicole** [comment]
But Smart Island is really attractive and its camera is also very attractive
