### ISSUE TITLE
Keyboard artifact when using Hardware Keyboard in Ipad Os 16.1 and Stage Manager

### ISSUE THREAD

**Issue by Leningrade** [blinksh/blink#1606]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues) 

Could be related to https://github.com/blinksh/blink/issues/1605#issue-1424219465 

### Configuration

Ipad OS 16.1
Blink 16.0.0.606

#### Issue
Smart keyboard (or other) is showing up half rendered when using a hardware keyboard when using stage manager. This issue disappears when opening  config (cmd+,)
The issue does not seem to be related with the option smart keys option "show with external keyboard".
The issue is present from the start of the app, and may disappear after changing stages. It later appears again.

#### Expected Behaviour
No artifacts should appear half rendered on screen. If smart keys are disabled, nothing should appear at all

![D31B9B9F-374C-4E61-94C2-887CB37CAA1D](https://user-images.githubusercontent.com/12130125/198081757-209ac50b-ad8b-40ad-8fd6-0282e97ee85b.png)
![AFCE5DCB-01AF-4894-A5B8-7A059F38E3FE](https://user-images.githubusercontent.com/12130125/198081766-71798bf7-0342-43d4-a1e0-80a061e9a0ef.png)

**Comment by yury** [comment]
Hello. That is know issue. But we can't fix that on our side. Only Apple devs can do that.

As a workaround for now - just slightly resize window.

We reported that issue to Apple.

Other apps also affected.

**Comment by Leningrade** [comment]
Thanks for the reply!

**Comment by carloscabanero** [comment]
Closing here as this was part of the 16 release and the issue seems to be already fixed by Apple.
