### ISSUE TITLE
Feature request: add `bc` calculator command to shell

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#1607]
`bc` is available in ios_system, and I frequently need to do arithmetic with blink shell output. Currently I have to switch to another heavyweight app to do a quick calculation; having `bc` would be a great convenience.

I think it’s just a matter of adding it here:

https://github.com/blinksh/blink/blob/1e7873a43e9a5988c6d3aeb4e979891881bdea86/Resources/commandDictionary.plist#L12

Thanks!

**Comment by yury** [comment]
Unfortunately this is not as easy as it seems.

1. It is one more dependency on bc_ios.xcframework
2. Our interactive input is not working well with that command



https://user-images.githubusercontent.com/5250/199418864-269650e5-4282-43e5-b81e-16e92d918102.MOV

I move that freature request to backlog for now.

**Comment by carloscabanero** [comment]
Done 17.3.0
