### ISSUE TITLE
SSH _sk keys cause out of memory error

### ISSUE THREAD

**Issue by kademahler** [blinksh/blink#1608]
### Checklist

- [ yes] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ yes] Read the [docs](http://blink.sh/docs/)
- [ yes] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iPad OS 16.1
16.0.1.616 app

### Describe the bug

SK keys cause out of memory error when use is attempted.
Server is running openSSH 8.9p1 on Ubuntu Server

Out of memory error

Prompt for hardware auth

![F4541545-E15A-43F6-8DB8-AC3474F68029](https://user-images.githubusercontent.com/77070667/198157355-41c4dc7d-47c3-484b-a92b-34608a21ef34.png)

**Comment by carloscabanero** [comment]
That usually happens if the signature process is cancelled at any point.

Is that passkeys or secure hardware keys? If it is hw keys, what brand and model is it? Was the prompt shown? Did you follow it or cancelled it at one point?

**Comment by kademahler** [comment]
> That usually happens if the signature process is cancelled at any point.
> 
> Is that passkeys or secure hardware keys? If it is hw keys, what brand and model is it? Was the prompt shown? Did you follow it or cancelled it at one point?

This happened for me on both a Yubikeys FIPS 5C and with passkeys. The screenshot above was a passkey attempt. No prompt was shown on either, so I didn't cancel anything.

**Comment by kademahler** [comment]
I’m completely unable to use any _sk key right now with this error, which is my only use case for this app. It never prompts for anything, it goes straight to the error shown.

**Comment by kademahler** [comment]
Update: this was the only key I had but if I manually define the key I’m using it worked for the passkey, despite it being the default name. That being said I’m still getting the same issue with my security key ssh key when I import it (ed2219_sk key)

**Comment by carloscabanero** [comment]
Ok, thanks for the update. I’m not sure if there is a bug here, trying to summarize what you are experiencing and I will try to replicate from my side:
- You created both a Passkey and a Secure Key. None were working at the start. Now thePasskey is working when you select it explicitly at the Host.
- Is the Secure Key “tap request screen” showing when you do the same? Or does it fail straight away? Can you send us a screenshot or part of the configuration of the host so we can see it?
- What do you mean by “when I import it “ed2219_sk key”? Is that a key from a different client that you are trying to import to Blink? Is that a FIDO secure key that you are trying to import to Blink? Is it just a key that you are creating inside Blink?
- You are also saying that you only have one key. Is that the Passkey? Are you trying to sign with the Secure Key, but maybe Blink does not have a reference to it anymore inside the Keys section?

Yubikeys are quite straightforward and there should be no issues 🤔. Let me know and I’m still thinking what may be going on.
