### ISSUE TITLE
So has the problem of freezing and crashing started to be solved?

### ISSUE THREAD

**Issue by phonefixnicole** [blinksh/blink#1611]
### Checklist

- [ ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ ] Read the [docs](http://blink.sh/docs/)
- [ ] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

**Comment by yury** [comment]
If you have any freezes and crashes - please record video.

**Comment by carloscabanero** [comment]
I think this is spam or a bot. The other messages from the user are something about a crease and no content.
