### ISSUE TITLE
Code can't open remote directory with one proxyjump

### ISSUE THREAD

**Issue by brentgryffindor** [blinksh/blink#1612]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink version: v16.0.1.616
iOS version: 16.1
iPad Pro 2022

### Describe the bug

I was able to open remote directory using code and map that directory in the File app for a remote server without any proxyjump. However, when I try to use code to open a remote folder with one proxy hop, it doesn't work. Mapping that folder to the File app also doesn't work. I was able to ssh into both remotes without any problems.

Thank you in advance! I really love the vs code integration in blink and hope it can work with my remote server.

Here is the error log from blinkCode.log, this is produced by `code lab:/home/brent/`
![error_log_1](https://user-images.githubusercontent.com/26558633/198498172-499074ba-a74b-45c0-97c6-58876e214d45.jpg)
Here is the error log from fileprovider.log
![error_log_2](https://user-images.githubusercontent.com/26558633/198498252-1df7357f-6c89-493e-a2af-22a9a3e6504c.jpg)

**Comment by carloscabanero** [comment]
Should be fixed on next TestFlight. Please try it out

**Comment by brentgryffindor** [comment]
Thank you! I'll try it out.

**Comment by yury** [comment]
I think we can close this one. Feel free to reopen if needed.

**Comment by akrz91** [comment]
after updating to v 16.0.2.622 I cannot open remote directory when reaching the server via proxy jump. It fails both on Files app and on `code server:<dir>` launch in shell.

It works fine for the direct connection to the server - when there is no jumping.
The ssh connection from shell for the server with jump also works fine.

BTW, is there any way of removing a Host once it was created?

@edit:
using iPad Pro with M1 (2021), iPadOS 16.1.1

**Comment by yury** [comment]
@akrz91 swipe to the left on host row in the list

**Comment by carloscabanero** [comment]
@akrz91 Can you send the first lines of ssh -vvv to the host, so we can see what the transform for ssh -W is?

**Comment by akrz91** [comment]
```
blink> ssh -vv a11
Starting connection to apl11.maas
ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_socket_connect_proxycommand: Executing proxycommand 'ssh -J  jump -W [apl11.maas]:22 kask'
ssh_socket_connect_proxycommand: ProxyCommand connection pipe: [172,173]
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: Socket connecting, now waiting for the callbacks to work
Starting connection to apl11.maas
Starting connection to apl11.maas
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
ssh_analyze_banner: We are talking to an OpenSSH client version: 8.2 (80200)
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
Starting connection to apl11.maas
ssh_kex_select_methods: Negotiated curve25519-sha256,ssh-ed25519,aes256-gcm@openssh.com,aes256-gcm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-256-etm@openssh.com,zlib@openssh.com,zlib@openssh.com,,
Starting connection to apl11.maas
ssh_init_rekey_state: Set rekey after 4294967296 blocks
ssh_init_rekey_state: Set rekey after 4294967296 blocks
ssh_packet_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
ssh_packet_newkeys: Signature verified and valid
Starting connection to apl11.maas
Connection succeeded...
Authenticating...
Trying none...
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
Trying publickey...
ssh_agent_get_ident_count: Answer type: 12, expected answer: 12
Connected to 
SHELL Opening channel
channel_open: Creating a channel 43 with 64000 window and 32768 max packet
SHELL Opening channel
ssh_packet_global_request: Received SSH_MSG_GLOBAL_REQUEST packet
ssh_packet_global_request: UNKNOWN SSH_MSG_GLOBAL_REQUEST hostkeys-00@openssh.com, want_reply = 0
ssh_packet_global_request: Invalid SSH_MSG_GLOBAL_REQUEST packet
ssh_packet_ignore_callback: Received SSH_MSG_DEBUG packet
SHELL Opening channel
ssh_packet_ignore_callback: Received SSH_MSG_DEBUG packet
ssh_packet_channel_open_conf: Received a CHANNEL_OPEN_CONFIRMATION for channel 43:0
ssh_packet_channel_open_conf: Remote window : 0, maxpacket : 32768
SHELL Opening channel
SHELL Request PTY
SHELL Request PTY
channel_request: Channel request pty-req success
Requesting Env Var LANG
Requesting Env Var LANG
channel_request: Channel request env success
Requesting Env Var TERM
Requesting Env Var TERM
channel_request: Channel request env failed
Error requesting Env Var TERM
SHELL Start
channel_rcv_change_window: Adding 2097152 bytes to channel (43:0) (from 0 bytes)
SHELL Start
channel_request: Channel request shell success
grow_window: growing window (channel 43:0) to 1280000 bytes
Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-126-generic x86_64)
```

**Comment by carloscabanero** [comment]
Thanks, my fault. I overlooked one thing during our test. Will fix and push before we have other major stuff.

**Comment by carloscabanero** [comment]
@akrz91 Should have been fixed on latest TF, and will be out on AppStore soon.

**Comment by akrz91** [comment]
yup! I confirm the update fixed the issue with jump ssh connection via Files app and in vscode :) Thanks!
