### ISSUE TITLE
Can't get past the whats new screen!

### ISSUE THREAD

**Issue by richardbrn** [blinksh/blink#1613]
Hello
Just upgraded to an M2 iPad Pro 12.9 and Blink won't let me get past the whats new screen
As soon as I open the app I get the screen as in the screenshot - how do I get past this screen?  Whatever I do it just opens up the feature details on Safari!

thanks
Richard

![IMG_1047](https://user-images.githubusercontent.com/75087283/198583348-19d8f673-cbd3-445b-8a57-54116cd6c123.jpeg)

**Comment by yury** [comment]
1. Update Blink to the latest version.
2. Tap 3 dots at the top and choose Close
3. Or Drag new Blink window from the dock.

**Comment by richardbrn** [comment]
> * Update Blink to the latest version.
> * Tap 3 dots at the top and choose Close
> * Or Drag new Blink window from the dock.

Thanks - 3 dots did it!

**Comment by yury** [comment]
Will should keep this issue open for few days, so other people could find it.

**Comment by KennethLavrsen** [comment]
I ran into same problem. Not very user friendly

**Comment by yury** [comment]
We improved that in 16.0.1.

**Comment by carloscabanero** [comment]
If this happened to get stuck on you in Blink 15, as it did with me right now, updating the app will not help. Do the three finger tap, or create another Blink window (tap on the Blink icon and then use the + button) and then close What's New.

Jeez, we got really ahead of stuff with this new type of windows. Apologies for the inconvenience.

**Comment by SpaceShipDev** [comment]
> I ran into same problem. Not very user friendly

No not at all actually, how the heck did this pass QA! I feel sorry for the folk still stuck, not using the app because of this and yet not searching to resolve it either due to #effort. Ugh, yes annoyed the life out of me.

**Comment by carloscabanero** [comment]
We launched a fix to revert this into a regular window the very same day, and we have kept this open in case anyone else found the same issue, which by now is extremely unlikely.

**Comment by SpaceShipDev** [comment]
I appreciate it, I've been waiting for a fix thinking thats what it would take because the swipe down has not been working for me, nor has force quit. Thanks anyway :)

**Comment by carloscabanero** [comment]
Yep, there has been a fix for more than three months now. Maybe you had updates disabled?

Anyway, it is probably time to close this. 👍🏼
