### ISSUE TITLE
Caret not visible in Code dialogs

### ISSUE THREAD

**Issue by acacar** [blinksh/blink#1615]
### Configuration

Blink 16.0.1; ipadOS 16

### Description

When using VS Code in blink, the caret (cursor) is invisible in dialogs (like the command palette, file open dialog etc.). This is true for both for local code instances, and for remote code instances like codespaces or code server. While not critical, being unable to see the caret makes writing into these dialogs very difficult and error-prone, so it is a quality of life problem. Furthermore, the dialog text field is not clickable, so you have to use arrow keys to blindly move the caret to the right place if you need to edit existing text there (e.g. to fix a file path etc.)

Here is what happens in VS code under blink:

![C33554CC-DBEE-4DEA-8055-63F662BCA8B8](https://user-images.githubusercontent.com/1941920/198826984-a6d7c397-2b03-44a5-a5e3-14f9f0cf1be4.jpeg)

No blue caret in the command palette dialog. 

### Expected behaviour

Here is the expected behaviour:

![96DEF6BE-5111-46B0-B37D-153286BCF00C](https://user-images.githubusercontent.com/1941920/198826957-bb6cbf3a-87a7-4a82-871d-f8fe44c7d664.jpeg)

This is the same VS Code server accessed through Safari on the same iPad. Note the blue caret in the text entry box in the command palette dialog.

The VS Code functionality in Blink shell has made coding on the go a delight for me, so thank you for this. This is currently the only thorn in my side when using code under Blink, and I'd be very happy if it got fixed, or if someone could let me know if there is a fix or workaround.

**Comment by yury** [comment]
Fixed.

Will be in 16.0.3

**Comment by acacar** [comment]
Thank you!
