### ISSUE TITLE
File provider is leaking storage.

### ISSUE THREAD

**Issue by yury** [blinksh/blink#1619]
Even if file is deleted after download, space used by Blink is not decreased.

Also If user deleted provider we should cleanup space.

**Comment by aikinai** [comment]
I guess I have the same issue? Blink was using over 8GB of storage. I deleted the app and installed from scratch and it's gone for now.

**Comment by carloscabanero** [comment]
Hey, sorry about that. We forgot to link to a workaround for this:

https://github.com/blinksh/blink/discussions/1601#discussioncomment-3954673

**Comment by carloscabanero** [comment]
We added a way to clean up the storage inside Blink (just remove the location inside hosts).

This will be fixed as part of #1717. Closing here
