### ISSUE TITLE
Blink crashes when opened on external display, or when Moved to External Display

### ISSUE THREAD

**Issue by ccsCoder** [blinksh/blink#1621]
### Checklist

- [ *] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ *] Read the [docs](http://blink.sh/docs/)
- [ *] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink: 16.0.1
iPadOS: 16.2.0 Beta

### Describe the bug
When trying to launch blink on the external monitor it crashes.
It also crashes when trying to launch the app on the ipad screen and then moving to external display

**Comment by thekeith** [comment]
Can verify. It keeps the space in stage manager along with the window size selector briefly before disappearing. App is shown as active but is unusable.

**Comment by yury** [comment]
Fixed.

Will be in:

- TestFlight v16.0.2 build 619
- App Store v16.0.2 build 620

**Comment by yury** [comment]
Fixed in v16.0.2 feel free to reopen if needed.
