### ISSUE TITLE
Having issues with the build.

### ISSUE THREAD

**Issue by rolurq** [blinksh/blink#1622]
### Discussed in https://github.com/blinksh/blink/discussions/1620

<div type='discussions-op-text'>

<sup>Originally posted by **rolurq** November  2, 2022</sup>
I was following the build guide and I'm stuck on running `./get_frameworks.sh`, it throws this error
```
error: 'xcfs': Invalid manifest
/Users/.../Projects/blink/xcfs/Package.swift:2:8: error: no such module 'PackageDescription'
import PackageDescription
```</div>

**Comment by carloscabanero** [comment]
Closing here as duplicate of already answered Discussion https://github.com/blinksh/blink/discussions/1620

**Comment by rolurq** [comment]
Discussion is not answered. Issue still exists.

**Comment by yury** [comment]
Yep, we moved that to discussions, so it more visible to people and may be someone could help.
