### ISSUE TITLE
App opens to black screen

### ISSUE THREAD

**Issue by GregoryMS** [blinksh/blink#1628]
### Checklist

- [ x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [ x] Read the [docs](http://blink.sh/docs/)
- [ x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink Version 16.0.1  | iOS version 16.1.1 | iPhone 13 pro
### Describe the bug

The app will only launch to a black screen. I have tried reinstalling the app and it will still open to a black screen. No input works at all and no onscreen keyboard. As such, no way to open config or function in anyway.

**Comment by yury** [comment]
Hello @GregoryMS 

Can I invite you to our Test Flight? to test  v16.0.2?

**Comment by GregoryMS** [comment]
> Hello @GregoryMS 
> 
> 
> 
> Can I invite you to our Test Flight? to test  v16.0.2?

That sounds good to me

**Comment by yury** [comment]
Please send me email to yury@blink.sh

**Comment by GregoryMS** [comment]
Still not working with latest update and testflight version

**Comment by GregoryMS** [comment]
I have solved the issue, I changed my theme via a Bluetooth keyboard then reinstalled the app. It would be great if there was a fallback feature to reset the theme when the on screen keyboard doesn't appear.
