### ISSUE TITLE
Shell unresponsive after switching apps

### ISSUE THREAD

**Issue by nibl** [blinksh/blink#1634]
After switching to other apps for a minute, and back, the keyboard no longer types into the remote shell. This did not used to happen.

Session has to be closed. Recent commands are also missing from history.

Blink 16.0.2, iPadOS 15.7.1

**Comment by carloscabanero** [comment]
Need more information to try to reproduce this. Is this ssh or mosh? Is it consistent after a specific amount of time? Are you using `geo` in the case of ssh? Are you roaming or switching networks (say Wifi and then maybe cellular even if you were not aware of the switch?) What can you see on the screen? Are other parts of the app still active - can you create more tabs, or having other tabs can you switch to them, three finger tap working? If you press enter a few times, do you see the shell back again?

**Comment by nibl** [comment]
Is this ssh or mosh?
ssh

Is it consistent after a specific amount of time?
No

Are you using geo in the case of ssh?
No

Are you roaming or switching networks?
No. Stable Wifi only

What can you see on the screen?
Display is frozen

Are other parts of the app still active?
I can switch to other open tabs. Can't remember about two finger tap. Three finger tap works, but "close" was not always available. It was inconsistent. 

If you press enter a few times, do you see the shell back again?
No.

Ctrl- works. Ctrl-D exits.

-----
The issue has not occurred in the past few days. I will close the issue, but maybe this info is useful in case it happens again or to someone else.
