### ISSUE TITLE
Hanging ^ Control Signal When Exit SSH

### ISSUE THREAD

**Issue by atarrh** [blinksh/blink#1637]
When CapsLock is set to send Ctrl as modifier in Blink config -> Keyboard settings, exiting an SSH session results in a continuous control signal (i.e., any other key input acts as if Ctrl is being held down) on the local blink shell.

Workaround: I have set my iPad’s Keyboard -> Modifier Keys -> Caps Lock Key setting to ^ Control, which overrides the Blink config setting.

As there is a workaround this is not a pressing issue for me.

**Comment by carloscabanero** [comment]
Thanks for the report! Yep, Caps as Ctrl is a better option on iOS system than Blink. We were just "hacking" it but our solution was the best we could do back in the day. Closing this as it will be part of #1371
