### ISSUE TITLE
Feature request: Add patch for cursor style handling

### ISSUE THREAD

**Issue by fecet** [blinksh/blink#1639]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug

Cursor style handling is a very old question for mosh, it's fixed by https://github.com/mobile-shell/mosh/pull/1167, but have not yet merged to release, can we add a patch to support it like https://github.com/archlinuxcn/repo/commit/f14aacd535932b80fbce040594bb0824fcc41ba0

**Comment by fecet** [comment]
Any thoughts?

**Comment by yury** [comment]
For me, I'd try to make smth that mosh merge that. So we can pickup it too.

**Comment by carloscabanero** [comment]
This is being worked on by Mosh itself https://github.com/mobile-shell/mosh/issues/352. Closing here.

**Comment by fecet** [comment]
> This is being worked on by Mosh itself [mobile-shell/mosh#352](https://github.com/mobile-shell/mosh/issues/352). Closing here.

I mention this, but that's PR still not being merged?
