### ISSUE TITLE
Prompt is off screen after SSHing

### ISSUE THREAD

**Issue by ghost** [blinksh/blink#1640]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

* 16.0.2.622
* iPadOS 15.7.1
* iPad Mini (5th generation)

### Describe the bug

Prompt is one line off top of screen (after clearing) when using an external keyboard. Repro steps:
* Attach external keyboard
* Open Blink
* Prompt is in correct location at top of screen (after clearing)
* SSH into my server (A VERY standard , largely unconfigured Debian 11 box)
* Prompt is one line off acreen (after clearing)
* Exit SSH session
* Prompt remains one line off screen (after clearing)

Video: https://d.pr/v/83WxVb

EDIT: This actually occurs for me both with and without an external keyboard being attached.

**Comment by carloscabanero** [comment]
I cannot reproduce this in my devices and I have also tried connecting to a Debian 11 box. Does Ctrl-l have the same result? Do you have any special setting on $TERM in remote or in local? Have you tried with an iPhone or another device?

**Comment by ghost** [comment]
@carloscabanero Just verified that this issue is still occurring for me. Nothing special in $TERM (just xterm-256color) and ctrl-l does not fix the issue. I do not have another device to test this on.

**Comment by ghost** [comment]
@carloscabanero Additinal info: I tested this out on a fresh Debian 11 Digitalocean droplet this morning and this issue is present there as well (which rules out this being caused by something weird on my local box).

Also note, if you watch to the end of the video, that the issue persists even after closing the ssh connection.

**Comment by ghost** [comment]
Huh, so this issue does NOT occur with mosh, only ssh.

**Comment by carloscabanero** [comment]
Ugh, I'm still unable to replicate this myself, even on a fresh Debian 11 on DO.

https://user-images.githubusercontent.com/536729/227391952-8a763904-7a3d-4442-bb1a-9c6958a40bd1.mp4

Is this still bothering you?

**Comment by carloscabanero** [comment]
Closing here as there was no response. Please reopen if necessary.
