### ISSUE TITLE
Blink can't import 1Password-generated Ed25519 SSH keys 

### ISSUE THREAD

**Issue by yury** [blinksh/blink#1647]
From TF Feedback:

> I can't import 1Password-generated Ed25519 SSH keys. Is it 1Password not generating what Blink needs or Blink not supporting Ed25519?

**Comment by carloscabanero** [comment]
I couldn't open an account in 1Password because something isn't working properly on their app. They are directing me to support. Im going to close here. We use OpenSSH so we are the standard, if someone has this issue again, let's ask to create an example key we can use. Closing

**Comment by VirtualWolf** [comment]
Just dropping a comment here in case it's helpful, I copied my 1Password-generated Ed25519 private key and was able to import it quite happily into Blink from the clipboard.
