### ISSUE TITLE
Blink crash when create new terminal

### ISSUE THREAD

**Issue by ghost** [blinksh/blink#1653]
2 fingers tap creates new terminal or 3 fingers tap and close terminal often crash application. Delete and reinstall application doesn’t help.

Configuration
v16.0.3.642
iPadOS 16.1.1
iPad Pro (12.9-inch) (6th generation)

**Comment by yury** [comment]
Should be fixed in v16.0.4.

Closing this issue. Feel free to reopen if needed.
