### ISSUE TITLE
M-<key> broken when caps lock is on

### ISSUE THREAD

**Issue by rinon** [blinksh/blink#166]
I map caps lock to control (thanks for the option, it works great). However, after I've toggled caps lock by using the control key, M-<key> shortcuts send unicode characters rather than the expected M-<key> sequence.

I understand that mosh can't currently turn off caps lock when leaving the app, but it would be nice to track state inside the app to fix M-<key> combinations.

**Comment by carloscabanero** [comment]
Do you have M- mapped to anything? Usually behavior of Alt on OSX/iOS is to actually print those Unicode characters.

**Comment by rinon** [comment]
Arrgh, I feel so stupid! I just remembered that my emacs config maps most of the M- unicode characters back to their normal M- keys on the remote side. I switched Alt -> Esc in blink and things work great now. So sorry for the noise! Loving blink so far.
