### ISSUE TITLE
Both the iOs menu and the VsCode menu are popped up when right click.

### ISSUE THREAD

**Issue by limerick1718** [blinksh/blink#1660]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)
There is no existing issues related to the right click behavior by far I searched.

### Configuration

Default configuration.

### Describe the bug

What I did: right click on VsCode editor.
Both the iOs menu and the VsCode menu are popped up.

Only the VsCode menu should be popped up.

![image](https://user-images.githubusercontent.com/20484572/208045767-7760c593-6fad-4e81-bc16-e2de73906ff0.jpeg)

I wonder could we some how implement different behavior for touch mode and the keyboard mode?
For touch mode, there should be the system’s right click menu; while for the keyboard and mouse mode, there should be the VsCode’s right click menu.

Please kindly advise!

Thank you very much and have a great day!

**Comment by yury** [comment]
Should be fixed in next release. Feel free to reopen if needed.
