### ISSUE TITLE
Feature Request: VS Code Server

### ISSUE THREAD

**Issue by agluck91** [blinksh/blink#1666]
Will there be any way to use the new official code-server? It is using a secure tunnel provided by microsoft, so I am not even sure if there is anything you can do. I would rather not use it in the web app, however it is a progressive webapp. 

https://youtu.be/q2viJSYyKio

**Comment by yury** [comment]
It is already supported. Just use `code` command without arguments. And signing with your GitHub account. And you are ready to go.

**Comment by carloscabanero** [comment]
I have been trying the new code-server inside Build with the tunnel functionality and they seem to be working great. Please reopen and provide us more information if this is still an issue.
