### ISSUE TITLE
Feature request: arrow key remapping

### ISSUE THREAD

**Issue by regisverdin** [blinksh/blink#1667]
Hi there! Not sure how many people use Karabiner here, but I normally use it to remap my arrow keys to right-cmd - i/j/k/l,  
and I've heard of other people doing the same. It keeps you from having to lift your hand over to the arrow keys. Unfortunately there is no Karabiner for iOS.

Any chance of adding this? It could be in the keyboard menu, like "remap arrow keys" and then you select the modifier key to hold to enable them.

I know this might be a niche thing, but if you try it I don't think you'll be able to go back.... it would make a huge difference in ergonomics when using an external keyboard with blink.

**Comment by yury** [comment]
Hello 👋 

You can do that already. (except you can't distinguish left and right cmd).

1. run show key command. Press arrows and you will see HEX for them. For, instance for left arrow:
```
^[       27 0033 0x1b
O        79 0117 0x4f
D        68 0104 0x44
```
2. Go to `config` ->  Keyboard -> Custom Presses -> Add. Press combo (cmd-left arrow) and on action choose hex code. Press back and type HEX value 1B4F44.

I know it is not best UX for setup that, but it is doable :)

**Comment by yury** [comment]
Closing. Feel free to reopen if needed.
