### ISSUE TITLE
Cannot access my private key

### ISSUE THREAD

**Issue by R7e98kva** [blinksh/blink#1677]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink 16.0.4.644

### Describe the bug

open the config menu -> Keys & Certificates -> select a key -> click ‘copy private key’

Expected: after authentication, the key should be in the clipboard and therefore it Schuld be possible to paste it
What happens: clipboard is empty

After my Hardware was stolen, blink seems to be the only possibility to get access to my backup and all my private data. It would be great to fix it.

**Comment by carloscabanero** [comment]
Hi! If I understand, you lost your previous device and are trying to recover in the new, is that right? Unfortunately, Blink does not keep backups of private keys for security reasons. Blink syncs the key names so you know what hosts to apply it to, but unfortunately no private keys.

Not sure how we can help though. Do you have any way to access or reset a root password in that server?
