### ISSUE TITLE
Show SmartKeys with iPad Pro Smart Keyboard connected.

### ISSUE THREAD

**Issue by MacDragon** [blinksh/blink#168]
Just had a play around, and unless I'm missing something, iPad Smart Keyboard really needs the extra keyboard line still displayed on screen, as it has no native esc key, or indeed page up/down etc.

**Comment by carloscabanero** [comment]
You can configure the ESC key as a modifier or key on the Keyboard section at the config. For example Alt as Esc for emacs, etc... Also in there you will find Page Up/Down as combinations with cursor keys (by default it is Cmd+Arrow).

This being said, I wanna add the option to display also the extra row, specially now that it looks better, as I think it might be useful sometimes.

**Comment by goerz** [comment]
I agree, but please make that optional, though. I personally prefer to do this by remapping the keys (especially CapsLock to Escape). Blink (miraculously) allows this possibility, and if anything, I'd love to see those capabilities extended (and also, make all keys auto-repeat, for I can easily scroll in vim with 'j')

**Comment by carloscabanero** [comment]
Agreed! 

Auto-repeat will be available for testers this Monday ;)

**Comment by MacDragon** [comment]
Ah, ok, the pg-up/down wasn't quite clear from the config screen description, but it does indeed appear to work, and using caps lock for esc is a decent enough workaround. But I still think it would be a good idea to give a toggle option for the bar at all times.

**Comment by 0xCMP** [comment]
I'm currently using blink right now and a bar would be useful. I'm trying to use blink to access a server and emacs on that server to do work. Some of these things are useful to have some kind of escape hatch.

**Comment by jucor** [comment]
Would love to have this, same use case as everyone in this thread :) Thank you for considering!

**Comment by carloscabanero** [comment]
Done on v5!

**Comment by jucor** [comment]
Yay! thanks @carloscabanero  :)
