### ISSUE TITLE
scp or sftp leads to a crash when called on a host with a ProxyJump

### ISSUE THREAD

**Issue by Gales-P** [blinksh/blink#1682]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink `16.0.4.643`
iPadOS `16.2`

### Describe the bug

Please follow the following steps.

- Create a host `remote_host` that is reachable only via a ProxyJump.
- Try copying something from the host using `scp` or `sftp` as follows:
```scp remote_host:<remote_file_path> <local_file_path>```

Blink will crash immediately.

**Comment by carloscabanero** [comment]
This was fixed a few releases ago. Please reopen if you still have issues.
