### ISSUE TITLE
ssh-add not working

### ISSUE THREAD

**Issue by rayzhudev** [blinksh/blink#1685]
When I run `ssh-add KEY_FILE`, it always returns the error `Key not found`. In addition, after typing `ssh-add`, it doesn’t autocomplete for files.

I’m trying to create an ssh key for Github. I’ve tried using the default method in the configuration via the gui, but when testing my key with `ssh -T git@github.com`, I get the error `Error connecting to github.com. authFailed(methods [SSH.AuthAgent]) `.

### Configuration

Blink Version: 16.0.4
OS: iPadOS 16.2

**Comment by yury** [comment]
Hello, we have a little bit different agent. `ssh-add` only works with keys in `config` -> `Keys & Certificates`.

So you need to import/create key in config.

**Comment by carloscabanero** [comment]
Improved documentation. Closing here.
