### ISSUE TITLE
Mounts in Files.app cannot handle hidden links to non-hidden files

### ISSUE THREAD

**Issue by Gales-P** [blinksh/blink#1687]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink: v16.0.4.643
iPadOS: 16.2

### Describe the bug

Let there be hidden “dot” files (e.g. `~/.bashrc`) in your host which are links to non-hidden files (e.g. `~/dotfiles/bashrc`). Mount that remote host directory in Files.app.

You will notice that the hidden links show up as non-hidden phantom files (e.g. `~/bashrc`) which cannot be opened. I get the following error message.
```
Operation Error
Fail(msg: "Could not canonicalize path
- SFTP server: No such file")
```

**Comment by carloscabanero** [comment]
We will be pushing this one to the new implementation with the Replicated Files Extension.

**Comment by carloscabanero** [comment]
#1717
