### ISSUE TITLE
Scrolling in self-hosted code-server with a trackpad is not smooth

### ISSUE THREAD

**Issue by Gales-P** [blinksh/blink#1688]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
Blink: v16.0.4.643
iPadOS: 16.2

### Describe the bug

If my mouse pointer is, say, at line `N` when I begin scrolling upwards in the editor (natural scrolling with a two-finger gesture upwards), the page will scroll until line `N-1` has scrolled out of the view and then the scrolling will abruptly halt even if I have more physical space on my trackpad to continue scrolling. That makes the experience of scrolling very janky and tedious.

#### Other scrolling issues 
Of course, there is no scroll inertia (which is rather essential for smooth scrolling). Moreover, scrolling does not work at all in the built-in terminal of code-server (the workaround is to use another Blink tab/window to access the remote shell).

**Comment by carloscabanero** [comment]
The scroll with inertia is on the code-server side and recent versions have been working better, but still didn't solve it. What we found is that whenever it gets stuck, you can reset it by doing the scroll really really slow again.

We will look into the terminal asap.
Tracking on #1404.
