### ISSUE TITLE
External screen's contents are fully accessible while Blink is autolocked

### ISSUE THREAD

**Issue by ChaiTRex** [blinksh/blink#1696]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iOS 16.3
iPhone SE 3rd generation
Apple Lightning to Digital AV (Lightning to HDMI converter)
Logitech K380 Bluetooth keyboard

Blink v16.0.4.644
Settings, Appearance, External Display: Scale
Settings, Auto Lock, Auto Lock: Enabled

### Describe the bug

When Blink autolocks while connected to an external display, the external display shows its contents and can be used via the keyboard if you switch from the Blink lock screen to another app and then back.

1. Set Blink to auto lock and to use the Scale mode for external displays
2. Connect to an external display and an external keyboard
3. Open VS Code on the external display and load some source code into it to edit it (alternatively, just leave it in the initial built-in Blink shell or connect to a Mosh server)
4. Switch to another app
5. Wait for over 10 minutes so that Blink autolocks
6. Switch back to Blink
7. Notice that you can see the contents of the external display's VS Code session but the keyboard doesn't change anything
8. Switch to another app
9. Switch back to Blink
10. Notice that you can now modify VS Code's loaded source file via the external keyboard

When Blink autolocks, both the iPhone screen and external display should not display the contents of VS Code or the terminal and should be unusable via the keyboard.

When Blink is initially switched back to after autolocking:

![54B2B2E1-2438-4397-8995-3BCE80554B20](https://user-images.githubusercontent.com/23159282/218194610-a06c5500-671a-44ed-ba77-e17d9efb0324.png)
![831ED615-C055-4D4B-88D5-03DBB6B77321](https://user-images.githubusercontent.com/23159282/218194607-832ff9cf-e85d-4e11-9c86-f43f3152bfc1.png)

After switching away from Blink to another app and then immediately back to Blink, I can add text via the external keyboard, like the `aaaaaa` near the bottom, with Blink still autolocked:

![C33ECEA9-AC01-4A89-B25D-8632FA9E77CA](https://user-images.githubusercontent.com/23159282/218194207-21a44fbb-ffae-40c5-9b6e-cccaca367d84.png)
![BA6D7267-8D43-45BA-B674-9B3FF5E6AD20](https://user-images.githubusercontent.com/23159282/218194210-6b8c4614-012d-4948-bf55-faee99377cc6.png)

This also works with the built-in Blink shell:

![5FAC26D2-5C94-4D09-BD6D-C5A840F989DF](https://user-images.githubusercontent.com/23159282/218196843-977f3d6e-001a-4e6c-9657-aca1bf1dc442.png)
![4B527EA5-C584-4786-A2FA-1A39B646F165](https://user-images.githubusercontent.com/23159282/218196845-cd231664-2686-4d5b-b993-6399b7759fe7.png)

**Comment by jgonggrijp** [comment]
I have this problem, too.

iPad Pro 3rd gen 12 inch with iPadOS 15.6.1
Blink v16.1.7.748
