### ISSUE TITLE
Feature request: Copy/Paste integration

### ISSUE THREAD

**Issue by rekendahl** [blinksh/blink#17]
It would be great to see iOS copy/paste integration.

It would be even greater if "clipboard" integration could work. In OS-X when I select/copy something in TMUX it automatically (through some TMUX configuration magic) gets copied to OS-X's clipboard. This is great for when wanting to share code quickly.

**Comment by carloscabanero** [comment]
New on v0.714 ;)

I wanted to make it work automagically but unfortunately in iOS you have to show a UIMenuController and it has to be approved by the user. Please reopen if you think there might be improvements ;)

**Comment by zhigang1992** [comment]
I think you can programmatically access system storyboard on iOS.

```swift
let pasteBoard = UIPasteboard.general
pasteBoard.string = "Paste me!"
```

Both setting and reading.

Do you think maybe we can reopen this? @carloscabanero

**Comment by zhigang1992** [comment]
The hard part would be somehow grabbing that data all the way across a remote server and inside of a tmux session. lol
