### ISSUE TITLE
No error message for lost private key?

### ISSUE THREAD

**Issue by JimDennis** [blinksh/blink#1712]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

v16.1.3.714

### Describe the bug
 
Attempting to ssh to my server in the cloud using my ssh keys fails (falls back to password auth, but fails on port with password auth disabled).

Generating a new key pair and pasting in the new pub key works

iPad has recently been replaced and the blink (and it's configuration)  were transferred in that process.

In config: Keys & Certificates, attempting to copy the private key seems to silently fail (leaves my copy buffer unmodified -- so my new pub key is still there).

I strongly suspect that the transfer/restore process from Apple did NOT copy secure enclave data and thus that the private key was lost (actually the old unit with the shattered screen still works, but ...)

Expected behavior: blink should detect when enclave data is missing or corrupted (perhaps store keys+hashes?) and give a morning.

**Comment by carloscabanero** [comment]
Fixed on 16.1.8. To be completed, added  #364 to our sprints.

**Comment by carloscabanero** [comment]
Fixed in two parts. Now you will get a warning in case the key cannot be found on the device so there are no false cases. And also, in case the keys file is restored from an iCloud backup, the iCloud keys will get an additional warning as well.

**Comment by JimDennis** [comment]
Thanks.
