### ISSUE TITLE
Cannot build due to com.apple.developer.web-browser entitlement

### ISSUE THREAD

**Issue by fuomag9** [blinksh/blink#1735]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

None relevant

### Describe the bug

I cannot build due to 

```
Provisioning profile "iOS Team Provisioning Profile: com.examplferfver4gfrgte.app" doesn't include the com.apple.developer.web-browser entitlement.
```

I should be able to disable the need to use the browser entitlement

![Screenshot 2023-03-25 at 11 49 14](https://user-images.githubusercontent.com/1580624/227712729-35952616-a23a-4440-bdb4-8bdf865d7fc4.png)

**Comment by smorkin** [comment]
Is this entitlement needed? According to Apple docs, https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_web-browser, this is for apps which can act as the default web browser on iOS, so e.g. Mozilla mobile uses it (see this bug, https://github.com/mozilla-mobile/focus-ios/issues/1781, where they deal with the same issue).

**Comment by carloscabanero** [comment]
This entitlement is needed for Blink Code. You can remove it and compile without it. Just take into account that you will have to use a tunnel if you use Blink Code with remote servers.
