### ISSUE TITLE
Bottom keyboard bar covering the terminal window

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#1738]
### Discussed in https://github.com/blinksh/blink/discussions/1737

<div type='discussions-op-text'>

<sup>Originally posted by **djsnipa1** March 28, 2023</sup>
I am unable to use Blink because when I use my external keyboard, the bottom of the terminal window gets covered by a keyboard bar. I’m using an iPhone SE with the latest version of Blink. Thanks for your help!

Here is my screen with the on screen keyboard. Notice the tmux status bar right above it. That is how I need it to look when I connect my external keyboard.
![B5711AC2-AC6E-40EC-94B3-D42FF6B39D05](https://user-images.githubusercontent.com/118037/228204503-c6b76084-1b7c-4d91-a191-ea8be0b535a8.png)

Here is what I’m trying to solve. The tmux status bar is completely covered. I’m unable to use neovim as well because of this.
![611E45D1-94F4-4B6D-9A4C-589DBA1BDEBF](https://user-images.githubusercontent.com/118037/228204857-856968ec-7a8c-4231-aa08-a3d4f9ac680c.png)
</div>

**Comment by mistakenideas** [comment]
I’ve noticed in the latest Testflight version (Version: 16.1.7 (747)) that the screen doesn’t immediately adjust/resize when using the built-in keyboard, so the keyboard covers the cursor position of an ssh/screen session. I need to rotate my device (iPad mini) for it to update correctly. Could this be related to this change or is it an independent issue?

**Comment by carloscabanero** [comment]
I think this may be unrelated, the previous one was fixed and released. I have not seen anything from my side. Can you send a screenshot?

**Comment by mistakenideas** [comment]
Okay thanks, I’ll enter a new issue to track this, see https://github.com/blinksh/blink/issues/1770

**Comment by yury** [comment]
This is should be fixed in latest 16.2.0 release and 16-cleanup and ios-17 branches.

Closing, feel free to reopen if needed.
