### ISSUE TITLE
Some settings require to press Save, but the user expects this to be automatic.

### ISSUE THREAD

**Issue by snan** [blinksh/blink#1742]
### Checklist

- [ ] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

V15.0.7.535 on iPad Pro 3rd gen 9.7 on OS 16.4

### Describe the bug

Blink Shell sometimes forgets my settings; theme, keyboard color, font, and preferred user.

**Comment by jgonggrijp** [comment]
I noticed that the external display setting always returns to "scale" after the app has crashed or after I manually purged it from memory. This might be the same issue.

iPad Pro 3rd gen with iPadOS 15.6.1
Blink v16.1.7.748

**Comment by carloscabanero** [comment]
If I recall, this should be fixed on Blink 16. If I manually close/purge the app, scaling setting still remains the same. It may be that you are still running iPadOS15?

**Comment by jgonggrijp** [comment]
Yesterday when I commented, I was still on iPadOS 15. However, shortly after that, I upgraded to iPadOS 16.5 (20F66). It didn't make a difference; no matter what I do, it always returns to "scale".

To be honest, this is the most problematic behavior of Blink for me. The separate window is giving me a lot of trouble and I cannot switch it off by picking "mirror", because that setting doesn't stick.

**Comment by carloscabanero** [comment]
Thanks for trying that out! I will do a review to see if I can find a path from the previous ones we patched that may not be covered and could be triggering this issue. One thing that may help, could you send me your `.blink/defaults` file? It does not contain any private information, but send it to carlos@blink.sh.

Thanks!

**Comment by jgonggrijp** [comment]
Sent it, you should have received an email. Thanks for looking into it.

**Comment by carloscabanero** [comment]
So the original issue should be fixed by now, after updating to Blink 16.

And for the second one, Blink needs to go back to the main config screen in order to save settings. I'm keeping this open as a reference for what to fix.

**Comment by carloscabanero** [comment]
This and the Default User should act more consistent now. Out on next TF 17.1
