### ISSUE TITLE
When building using precompiled binaries, frameworks have wrong path in project

### ISSUE THREAD

**Issue by smorkin** [blinksh/blink#1747]
### Checklist

- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

- Blink version: Latest code
- iOS version: 16.4
- Xcode version: 14.3

### Describe the bug

This is a brand new checkout, following the installation guide in the **Build** section of the _README.md_ file.

When opening the project file in Xcode, all frameworks from the _xcfs_ folder have the wrong paths: After running the commands as described in the **Build** section, the frameworks end up in e.g _xcfs/.build/artifacts/xcfs/awk/awk.xcframework_. However, in the current Xcode project they are configured to be at _xcfs/.build/artifacts/xcfs/awk.xcframework_, i.e. one level higher. The same goes for the _xcfs_ frameworks in the _curl_ios_static_ Xcode project.

Trying to build results in failure, due to not finding any of the mentioned libraries.

Fixing the path in the file inspector in Xcode for each of the libraries fixes the issue and compilation succeeds.

I do have fixed project files for the _Blink_ & _curl_ios_static_ projects, but I'm hesitant to do a pull request for them; I suspect this might result in failing to build the project if one builds everything from source rather than with the precompiled frameworks (my guess is that building from source will put them in the correct place, according to the project file). Perhaps a better way would be to change the _get_frameworks.sh_ script which fetches the precompiled stuff, but my swift knowledge is not good enough to understand how to change things so the frameworks are put where the Xcode project files expects them to be.

**Comment by mylukin** [comment]
1. use xcode open Blink.xcodeproj
2. click left folder, find Frameworks
3. find curl_ios_static/Frameworks
4. change xcframework path

**Comment by ezhes** [comment]
Another bad solution is to cd into the artifacts folder and just pull everything one level higher:

```
cp -r */*.xcframework .
```

**Comment by cyrilzakka** [comment]
The XCFrameworks don't seem to be in the Xcode project at all - how do I build them? @ezhes @mylukin

**Comment by yury** [comment]
@cyrilzakka ./get_frameworks.sh

**Comment by cyrilzakka** [comment]
@yury I tried that and get the error: 

```
/Users/cyril/Downloads/blink/Frameworks/ios_system/ios_system.xcodeproj: warning: Ignoring ENABLE_BITCODE because building with bitcode is no longer supported. (in target 'curl_ios' from project 'ios_system')
error: There is no XCFramework found at '/Users/cyril/Downloads/blink/Frameworks/ios_system/xcfs/.build/artifacts/xcfs/libssh2.xcframework'. (in target 'curl_ios' from project 'ios_system')
error: There is no XCFramework found at '/Users/cyril/Downloads/blink/Frameworks/ios_system/xcfs/.build/artifacts/xcfs/openssl.xcframework'. (in target 'curl_ios' from project 'ios_system')
/Users/cyril/Downloads/blink/Frameworks/ios_system/ios_system.xcodeproj: warning: Ignoring ENABLE_BITCODE because building with bitcode is no longer supported. (in target 'ios_system' from project 'ios_system')
** ARCHIVE FAILED **

Swift/ErrorType.swift:200: Fatal error: Error raised at top level: FMake.BuildError.unexpectedStatusCode
[1]    67299 trace trap  swift run --package-path xcfs build all
```

**Comment by yury** [comment]
@cyrilzakka please try snippets branch it is compatible with latest XCode. We push that soon in stable, once we release.

**Comment by cyrilzakka** [comment]
@yury very much improved - took me down from 21 build errors to 1: /Users/cyril/Downloads/blink-snippets/Blink.xcodeproj This Copy Files build phase contains a reference to a missing file 'MBProgressHUD.framework'.

**Comment by yury** [comment]
Yep, after switching branches, you should do `git submodule update` and also run `./get_frameworks.sh`.

**Comment by cyrilzakka** [comment]
Wrote up a bunch of fixes if anyone's interested but finally got it running!

```
git clone --recursive --branch snippets https://github.com/blinksh/blink.git 
cd blink git 
submodule update 
./get_frameworks.sh 
rm -rf Blink.xcodeproj/project.xcworkspace/xcshareddata/
 cp template_setup.xcconfig developer_setup.xcconfig nano developer_setup.xcconfig (edit the values)
 In Targets & Signing Capabilities remove iCloud, Keychain and Push Notifications
 In Blink > Blink > Blink (yellow icon, entitlement file) remove the web-browser line 
One last error: RevenueCat has a bug in version 4.25.3 that fails to build with an error concerning iOS 17 because the compiler flag fails to realize you’re not building for visionOS. So in Blink > General remove the visionOS platform and scroll down and remove RevenueCat in Frameworks, Libraries and Embedded Content. 
Now go to File > Add Package dependencies search for https://github.com/RevenueCat/purchases-ios.git, change to ‘Exact version’ set it to 4.25.2 and add to Project: Blink. Then File, Packages, Reset Package caches. 
Clear derived data. 
Clean Project and Build. 
 In BKHosts.h replace @import CloudKit; with #import <CloudKit/CloudKit.h>.  
If you get the error, no module RevenueCat found, go to  Blink > General > Frameworks Libraries and Embedded content and click the + button, search for RevenueCat and add it (only it).
```
It should now build!

**Comment by smorkin** [comment]
Thanks for the mention of the _snippets_ branch, it fixed all build errors for me after a clean checkout. On-screen keyboard on iPad is still unusable due to #1819 & #1770, but the build is now 100% for me without requiring any changes :)

**Comment by carloscabanero** [comment]
Should be all good now. We put a lot of effort on this and to clean up our own builds as well.
