### ISSUE TITLE
Blink crashes when connecting 

### ISSUE THREAD

**Issue by pslijkhuis** [blinksh/blink#175]
When I connect to my server which only allows key authentication without specifying a correct key. Blink crashes.

**Comment by carloscabanero** [comment]
Thanks for your message. Hmmm... that is weird, it should just reject with a message. Does it ask for the password too or does it crash before that?

**Comment by pslijkhuis** [comment]
It does ask for a password and when i enter it it crashes. You could try to
connect to www.slijkhu.is

**Comment by carloscabanero** [comment]
Thanks! I'm fixing this critical bugs right now, so that's very useful :)

**Comment by carloscabanero** [comment]
I'm trying to replicate this, but right after putting the wrong password, it fails with a "permission denied" (publickey,password), and that's all. Are you using ssh or mosh? What is the configured locale on destination?

**Comment by carloscabanero** [comment]
I couldn't replicate the issue. It might be part of what was fixed during last version too. Please reopen if you still experience it on v3. Closing here
