### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#1755]
- Good search engine for commands.
    - This can be fake at the moment. At one point we will have something that will search over all your snippets.
- Format for snippets & commands.
    - .sh 
```
# Name
# Description
Script (if working with text, you can always substitute using other apps.) 
```
- 
    - Text
        - Name text file
    - Enc (format .gpg? .enc?)
    - Groups:
        - .snippets/build/snippet1
        - .snippets/all/…
        - .snippets/
- Base collection of snippets.
- Special flows for design: creating snippets, selecting snippets, etc…
- Introducing a snippet in the shell. Helpers, clues & Autocompletion.
    - Research on other formats. How others are performing this completions, etc…
    - You may not want to perform autocompletion in a small window. If you are pasting a 
- (Quick Actions: Connect to a Host, Start configuration to a specific place, Changing styles, etc…)
    - Quick actions could perform automatic replacement.
- (Three finger, contextual menu replacement: Layout, New Window, Close Window.)

- Syncing. 
    - iCloud
    - Sharing between users (non-iCloud).
    - Shareable via email.
- AI input

```[tasklist]
### Snippets TODO
- [x] Rename flow
- [x] Delete flow
- [x] Create snippet flow
- [x] Final look and feel (themes)
- [x] Github source
- [x] User may want to force a refresh on snippets locations
- [x] Fixes for small devices
- [x] Initial Snips
- [x] Documentation
- [x] Snippets is Blink+ feature
- [x] Migration for shortcuts
- [x] Comments
- [x] Support iCloud as a Snippets location
- [x] rename snippets folders to snips
- [x] Support multi-line output
- [x] Open Snips locations in Files for editing
- [ ] Release
- [ ] History Snippets
- [ ] Indexes for other non-basic commands
- [ ] Sharing Snippets
- [ ] Snippets contexts? blink/code/remote shell
- [ ] Mark snippets as Dangerous
- [ ] File Extensions
- [ ] Passwords
- [ ] Messenger
- [ ] Add multiple locations. Add another Index and control the Ignore file
```

**Comment by carloscabanero** [comment]
@yury For the Create snippet flow, it may be interesting to make more obvious the snippet will be created with certain parameters. Something like: 
<img width="823" alt="Screenshot 2023-06-22 at 8 52 29 AM" src="https://github.com/blinksh/blink/assets/536729/4677ad3a-d5b1-489a-86c1-9ccdb918fa22">

**Comment by carloscabanero** [comment]
Few tweaks now that we have multiple Snippets Locations working:
- [x] Need some attributes (at least isReadOnly) for the locations.
- [x] Renames should happen within the same sources.
- [x] Errors during refresh.
- [x] Index Progress
- [x] Smarter GitHub refresh.
- [x] Progress visuals
- [x] Same Snippet name on different location. The content is still shown as the same even if it isn't. There is also no way at the moment to differentiate based on location. We should decide if we want to shadow them, as with Ignore we could have a good mechanism.
- [x] Cleanup tests.
- [x] Review code, cleanup try? and try! we used to force errors,  check bindings and published values (some unused?), etc...
- [x] Spaces vs tabs on snippets. We need to set on one as that will be the default for indexes. (@yury votes for spaces)
- [x] Cleanup the output (independently of multi-line?).
- [x] Fuzzy search mode is not showing some results sometimes. It sometimes requires some back and forth.

UI tweaks
- [x] On iPhone, replace Return with Next in template mode.
- [x] Snippets bar not showing with software keyboard.
- [x] Use arrow.clockwise for refresh
- [ ] ~~Keyboard bubble shows after dismiss. Other OSs too?~~

UX tweaks
- [x] When we Exit template mode, there is no cursor anymore.
- [x] Sometimes it is not obvious we are on Template mode. And it is not obvious how you switch between tags, or how to exit. Maybe add it at the bottom.
  - [x] We implemented two ways (color codes and a special mode). For final release we should get rid of one.
- [x] Hard to differentiate between Rename and Create
- [x] NSAttributedString issue on multi line snippets

Documentation
- [x] Notes for what a good Snip should look like, etc...
- [x] Intro. How to use the feature, etc...

Other notes
- We may want to come up with a different name as this is diverging from _snippets_.

**Comment by carloscabanero** [comment]
Crazy idea but maybe save on GitHub could generate a PR request?

**Comment by yury** [comment]
We have issue with NSAttributedString and `\t` and `\\`.

Original content len 65:
`  -H \'Content-Type: application/json\' \\\n\t-d \'@${local_file}.json\'`

After calling `Highlight.text(...)` resulting attributed string has different length 62:
`-H \'Content-Type: application/json\' \\ -d \'@${local_file}.json\'`

temporary fix [3dc67fa](https://github.com/blinksh/blink/commit/3dc67fae25cdefdbf1cb0262fc6647b6fab1dd19)

**Comment by yury** [comment]
Another issue with Tap to close gesture. It triggers when you tap/click on text area itself.

**Comment by carloscabanero** [comment]
> We have issue with NSAttributedString and `\t` and `\\`.
> 
> Original content len 65: ` -H \'Content-Type: application/json\' \\\n\t-d \'@${local_file}.json\'`
> 
> After calling `Highlight.text(...)` resulting attributed string has different length 62: `-H \'Content-Type: application/json\' \\ -d \'@${local_file}.json\'`
> 
> temporary fix [3dc67fa](https://github.com/blinksh/blink/commit/3dc67fae25cdefdbf1cb0262fc6647b6fab1dd19)

I think this is looking good disabled. Less distracting, so closing there.

**Comment by carloscabanero** [comment]
- [x] iCloud and refreshing content while offline. Things may time out, the reads will hang and snippets will take around 10 seconds to show up. We designed the system to serve in chunks. But then we waited as then they are sorted and all that.
- Process as they come, and let the flow decide how it aggregates them.
- Do not block on iCloud. Send the cached elements.

**Comment by carloscabanero** [comment]
- [x] With the snips search bar open, switching to a different application will crash the app. Sent debug logs from crashes to TF.
- [x] The SW enter key should work in the search view. It makes it easier to type and go.
