### ISSUE TITLE
Latest update put me back to a premigration state and does not recognize original license

### ISSUE THREAD

**Issue by reinversion** [blinksh/blink#1758]
For some reason after updating to the latest version the application is no longer functional.  Restore purchase button does not do anything and attempting to perform the migration again results in it being unable to verify my purchase receipt of version 14 now.  Originally purchased May 2020, and now I am stuck.

**Comment by carloscabanero** [comment]
Getting back to you over email already. If anyone has issues with the migration, just reach out to us over email as we may need some information regarding the purchase.
