### ISSUE TITLE
Intermittent crash on opening vim

### ISSUE THREAD

**Issue by danieldreier** [blinksh/blink#176]
I just bought Blink after reading the hacker news post, and am having a problem that makes it mostly unusable. I'm seeing frequent crashes, and the best way I can reproduce it is by:

1. Start blink
2. SSH to my shell server (FreeBSD 10.2)
3. Open a file with vim
4. Blink exits

Strangely, this only happens with vim -- using regular vi works. I've had other crashes that look the same but can't find other reproducible test cases.

I'd be glad to collect more data to facilitate troubleshooting, but I don't know what would be useful or how to enable more verbose logging in blink that might be useful for debugging.

For context, I'm running blink on an iPad Pro 12.9" on iOS 10.1.1 (14B100) and am using SSH key auth.

I feel frustrated to spend $20 on an app and have it unusably crash-prone for what seems like a very basic use case. My priority is to get it working because I otherwise really like Blink, but I'll ask Apple for a refund if we can't get a resolution figured out relatively quickly because I just can't use the application as-is.

**Comment by carloscabanero** [comment]
Hi Daniel! Really sorry that you are having this problem. We have a ton of Vim and Neovim users and  this is definitely a corner case. Do you have your Vim config somewhere to try to replicate it?

Thanks and apologies again

**Comment by danieldreier** [comment]
On that shell server I'm actually running totally stock vim, without a `.viminfo` file at all.

I just discovered that when I run vim inside tmux, Blink doesn't crash. That significantly reduces the impact of the problem for me - not sure if it's a useful clue.

**Comment by carloscabanero** [comment]
I will spin up a machine with FreeBSD and check what might be crashing it. Hope the hotfix with tmux works while I replicate it. It might be that tmux prerenders something. Is it ssh or mosh?

**Comment by danieldreier** [comment]
I'm using ssh.

I found another way to crash it with vim running inside of tmux. If I'm in vim insert mode and press option-; on the apple smart keyboard, blink immediately exits. Vim in command mode doesn't do it, and weirdly, I cannot reproduce that using the on-screen keyboard.

If you have problems reproducing it let me know and I'll spin up a freebsd box that I can give you access to, so I can verify it reproduces on my end.

**Comment by danieldreier** [comment]
Awesome! Thank you for getting on it so quickly!

**Comment by carloscabanero** [comment]
Sure, this is a critical bug, so I wanted to fix it as quickly as possible. I have good news, I have it localized and I'm working on a fix. Tomorrow should be out and after Apple's validation, probably on Tuesday in everyone's device :)

**Comment by carloscabanero** [comment]
Fixed on v3.0
