### ISSUE TITLE
Desconfiguration Blink app with multi sirenes

### ISSUE THREAD

**Issue by alohaguilherme** [blinksh/blink#1765]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug

When using the Ipad with two screens and opening blink app on the iPad desktop it opens the app on both screens, blocking the use on the second screen

**Comment by carloscabanero** [comment]
Implementing on #1748. Workaround on https://github.com/blinksh/blink/discussions/1740
