### ISSUE TITLE
O(n) issue with text buffering

### ISSUE THREAD

**Issue by agh** [blinksh/blink#177]
Had an accident where I pasted in a 4096-bit public key into Blink Shell and happened to notice some really interesting behaviour indicating a O(n) performance issue.

If you start with `blink>` and paste in a **really** long line of text from the clipboard, you will notice it goes _really fast_ for the first couple seconds, then slows, and gets (apparently) exponentially slower until the point where it is only adding one character every second or thereabouts.

Responsiveness for `CTRL+c` also seemed a little off, it took a significant number of cycles before Blink acknowledged that, and it seemed to kill and reset the whole pane, which may be expected?

**Comment by carloscabanero** [comment]
At the shell level, everything we type or paste is actually managed by iOS classes. Really weird behaviour, but definitely there. Will not prioritise this at the moment, but probably will have to soon anyway.

**Comment by yury** [comment]
Right now it seems to be fixed. Feel reopen if needed.
