### ISSUE TITLE
Missed transition?

### ISSUE THREAD

**Issue by WoxWik** [blinksh/blink#1775]
I just logged into the legacy app since I wanted to do dev on my iPad after a break and it’s saying I missed the boat on transition to the new app… is there a manual way to get me transitioned without having to pay again?

thanks.

**Comment by carloscabanero** [comment]
https://github.com/blinksh/blink/discussions/1783

**Comment by WoxWik** [comment]
@carloscabanero I made my request 2 weeks ago (which is before May 22nd). Are you saying you can help me?
