### ISSUE TITLE
GitHub Organisation Profile

### ISSUE THREAD

**Issue by agh** [blinksh/blink#178]
You've got a trailing dot in the organisation profile which is 404'ing users clicking through to your social presence on Twitter. Just wanted you to know! 😄 

<img width="645" alt="screen shot 2016-11-14 at 13 27 00" src="https://cloud.githubusercontent.com/assets/385878/20266481/2bcc938c-aa6e-11e6-896c-d827dcc12910.png">

<img width="777" alt="screen shot 2016-11-14 at 13 27 10" src="https://cloud.githubusercontent.com/assets/385878/20266487/2d62dd6e-aa6e-11e6-93df-4c4a57bdc2b2.png">

**Comment by carloscabanero** [comment]
Damn it Sam 😄  !! that explains so many things.... fixed now
