### ISSUE TITLE
Bigger blink build machine plans

### ISSUE THREAD

**Issue by yury** [blinksh/blink#1794]
[8GB machine requested](https://discord.com/channels/441939332442619905/856986776187306006/1120611794621300758)

**Comment by jaidetree** [comment]
This is fascinating. Tried codespaces, my app processes kept getting reaped due to memory or cpu usage. Had to upgrade all the way to the 16 gb to get a consistent experience. Running in a 4 gb blink build image and it seems to run just fine without being reaped so far.

**Comment by carloscabanero** [comment]
Keep us posted on how it is holding up! It may be that we are running nothing by default.
