### ISSUE TITLE
Error while installing blink-fs code extension

### ISSUE THREAD

**Issue by deviantintegral** [blinksh/blink#1796]
I’m trying to install blink-fs as suggested when running the `code` command. I get a notification that there was an error installing the extension, and nothing more. I looked around in the terminal for logs and didn’t find anything. Any suggestions?

<img width="1373" alt="image" src="https://github.com/blinksh/blink/assets/255023/f0f3f972-1406-4a74-a58a-a9376a60e0df">

**Comment by ZeidAqemia** [comment]
Samesies. No clue how to investigate this.

**Comment by carloscabanero** [comment]
Closing here for https://github.com/blinksh/blink/discussions/1795
