### ISSUE TITLE
Error while installing Blink-FS Extension

### ISSUE THREAD

**Issue by rbsns** [blinksh/blink#1797]
Hi,

Can’t install blink-fs extension on iPad.

I only got this error message from VSCode (bottom right of screen) and I don’t know how to give more feedback or get debug info:

![IMG_1857](https://github.com/blinksh/blink/assets/538733/63fb1b45-c6e4-4813-9793-94983643f4eb)

**Comment by carloscabanero** [comment]
Tracking this here https://github.com/blinksh/blink/discussions/1795. Will leave this open so we don't create more dupes
