### ISSUE TITLE
Weird color rendering with none Unicode characters

### ISSUE THREAD

**Issue by rekendahl** [blinksh/blink#18]
So in my verification log files I use "guy flipping a table" to highlight errors. 

In blink + vim the lines around it renders weirdly:

![image](https://cloud.githubusercontent.com/assets/1612072/14316522/6b9de94e-fbd1-11e5-81d3-e1105b822967.png)

I don't expect these black horizontal lines to show.

**Comment by carloscabanero** [comment]
This should be fixed on next release. I might send you a custom version to be sure

**Comment by rekendahl** [comment]
Yeah. I'm ready to test when you are! From what you described during chat I'm optimistic next release will solve a lot of issues!

**Comment by rekendahl** [comment]
Works as expected now

**Comment by carloscabanero** [comment]
Awesome! One less to go!
