### ISSUE TITLE
`--experimental-remote-ip=local` in Blink's mosh still performs an IP lookup remotely, resulting in an unexpected LAN address

### ISSUE THREAD

**Issue by ahrex** [blinksh/blink#1803]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink v16.1.10.772

### Describe the bug

I find it difficult to mosh to a target host that's in a LAN behind a bastion host. See the following diagram and legend:

```
                                   +------------------------+
                                   |         firewalled area|
                              +------------+                |
    +--------- #1: ssh ------>|bastion host|                |
    |                         +------------+                |
+-------------+                    |     |                  |
|external host|                    |     | #1: ssh          |
+-------------+                    |     v                  |
         |                         |  +-----------+         |
         +-------- #2: mosh --------->|target host|         |
                                   |  +-----------+         |
                                   |                        |
                                   +------------------------+
```

| host    | internal IP address | external IP address |
| ------- | ------------------- | ------------------- |
| bastion | 192.168.0.5         | 203.0.113.15        |
| target  | 192.168.0.10        | 203.0.113.20        |

In the above diagram, this is how I would connect to `target host` on a laptop:
```
mosh \
  --ssh='ssh -o ProxyCommand="ssh -W 192.168.0.10:%p %r@203.0.113.15"' \
  --experimental-remote-ip=local \
  -- \
  user@203.0.113.20
```

* the `--ssh` argument allows me to take path `#1: ssh` to `target host` to start `mosh-server`, and
* the `--experimental-repote-ip=local` + `203.0.113.20` allows mosh to take path `#2: mosh` past the UDP firewall exception

With the removal of `--ssh` in commit b38391cde, I find it difficult to direct a different control plane path for starting `mosh-server`.

May I ask that you re-enable the ability to use `--ssh` in the `mosh` command, or support the `ProxyCommand` or `ProxyJump` ssh options via another method?

Thanks!

**Comment by carloscabanero** [comment]
Thanks for the heads up! I will take a deep look at this next week. By any chance, did you try to configure a SSH host for this? That way it would be ssh itself dealing with all that configuration.

**Comment by ahrex** [comment]
> Thanks for the heads up! I will take a deep look at this next week.

You're welcome, and thank you!

> By any chance, did you try to configure a SSH host for this? That way it would be ssh itself dealing with all that configuration.

<details><summary>Yup; here are the relevant configs.</summary>

![IMG_7363](https://github.com/blinksh/blink/assets/1185340/ffe18577-f654-44e4-908a-a0e3456cd06f)

![IMG_7362](https://github.com/blinksh/blink/assets/1185340/3d701322-89e8-4796-8991-cd04ba1b7a3b)
</details>

The following work in Blink:

* `ssh bastion`
* `ssh target`
* `mosh bastion`

While this case fails:

* `mosh target`

I believe this fails because when the initial control plane ssh connection is established, [searching for the IP address of `target`](https://github.com/blinksh/blink/blob/6723196f6b443b63051b4719b6e1090927eb8a10/Sessions/MoshSession.m#L412) results in `192.168.0.10`, which is not accessible from the Internet.

Thanks again!

----

<details><summary>Edit: I've also tried the following `target` config to more closely match the initial problem description.</summary>

![IMG_7364](https://github.com/blinksh/blink/assets/1185340/71a28740-872b-4d1c-bcc7-78596860ce12)
</details>

The results were the same successes/failure.

**Comment by ahrex** [comment]
Looking at both [`mosh`'s source](https://github.com/mobile-shell/mosh/blob/c16108f0171b89fab98666be74a3298ed8aa2ced/scripts/mosh.pl#L337) and [`blink`'s source](https://github.com/blinksh/blink/blob/6723196f6b443b63051b4719b6e1090927eb8a10/Sessions/MoshSession.m#L412), I think the issue boils down differences in implementation of `--experimental-remote-ip=local`:

* `local` in vanilla `mosh` instructs the _external host_ to look up the IP address entered on the command-line, as seen by the Internet
  * this results in a lookup of `target`'s `HostName`, returning `203.0.113.20` ✅, while
* `local` in `blink` connects to `target` via the ssh control path, and asks `target` what its local IP address is
  * this results in the LAN IP of `target`, returning `192.168.0.10` ❌

Updating my original request, I do not think I need a re-introduction of the `--ssh` argument into Blink's mosh, but rather I would like that `--experimental-remote-ip=local` in Blink perform an IP lookup on the client device.

**Comment by carloscabanero** [comment]
Hey, thanks for the thorough explanation, you nailed it. We need to change the way we call our default option as it is not really "local". Our "local" is basically using our ssh API and command so we connect to the same host (a more straightforward approach than what mosh does with "proxy" to pass a ProxyCommand to ssh and read the IP back). "Local" as you noticed should just take the manually resolved from user@host.

I will fix it this week. Are you on TestFlight by any chance?

**Comment by ahrex** [comment]
Thanks for the eyes! I'll DM you my TestFlight email.

**Comment by yury** [comment]
Closing as implemented and released. Feel free to reopen if needed.
