### ISSUE TITLE
Clear cache in Blink, when using Files.app

### ISSUE THREAD

**Issue by tl87** [blinksh/blink#1807]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink: 16.1.10.772
iPadOS: 16.5.1
macOS: 13.4.1
Keyboard: None

One of my hosts has activated the integration to Files.app

### Describe the bug

One of my hosts is my NAS.

In Blink, under config > hosts > FILES.APP, you can integrate the host as a location i Files.app.

Every time you view anything, the first time, on the host from the Files.app, like pictures or videos, the cache for Blink will increase:

![image](https://github.com/blinksh/blink/assets/5989314/a3466188-8dda-4d47-8aa3-88f38c4cb66a)

I cannot find a way to clear the cache. Among things, I've tried to see if it was possible in Blink, the Files.app and I've also connect my iPad to my Mac, to see if you could clear the cache in that way. Only thing, that seems to maybe work, is if you delete Blink and then reinstall it, set up all hosts again, but that does not seem like a valid solution.

This is specifically a problem, if your iPad does not have alot of storage for cached files and this might not fully be a bug, as much as its a feature request.

**Comment by carloscabanero** [comment]
Hi! There are a few workarounds already. I will make sure to add them the the docs as well: https://github.com/blinksh/blink/discussions/1601

We have an issue to migrate to the new API as well, which would solve the core issue.

**Comment by tl87** [comment]
@carloscabanero thank you very much, and awesome that it will solved, when migrating to the new API.

@carloscabanero this fixed my issue, shall I close this issue?

**Comment by carloscabanero** [comment]
Left it open so this morning I could remember to add it to the Docs.

@tl87 By any chance did you check the docs at any point looking for this? I'm trying to see (until we fix the issue itself), if updating the docs would be enough, or where else we could give a heads up so this question does not pop so often.

**Comment by tl87** [comment]
I did a very quick search on docs and not the most thorough, I'm afraid, before submitting the issue. I can see now, that if I had just spend a few more seconds, searching the docs, I've would have found the answer - sorry :(

**Comment by carloscabanero** [comment]
Sorry for the confusion. I meant the docs here https://docs.blink.sh/advanced/files-app. I think we should add a note there about this just in case, but not sure if you found those. Maybe a link in the app to open that for info as well?

- [ ] Add a note in documentation.
- [ ] Add a link to open the information inside the app.

**Comment by tl87** [comment]
Oh okay, no worries. I'm not sure how many are affected by this "issue", but I think it would be a very good idea to add an entry to https://docs.blink.sh/advanced/files-app - or maybe just a link to https://github.com/blinksh/blink/discussions/1601

**Comment by carloscabanero** [comment]
This was finally added to the docs. Closing
