### ISSUE TITLE
Spin up VS Code Server in Build

### ISSUE THREAD

**Issue by Gbrothers1** [blinksh/blink#1808]
### Discussed in https://github.com/blinksh/blink/discussions/1727

<div type='discussions-op-text'>

<sup>Originally posted by **carloscabanero** March 23, 2023</sup>
A place for discussing how to [use VS Code Server as an editor in Build](https://github.com/blinksh/blink/discussions/docs.blink.sh/build-up/code_server).</div>

So I am having the an issue getting the code-server to even install, the install script “setup.sh” is consitently downloading a web page instead of binary. I believe this to be an issue with MS Visual Studio. Lmk if anyone else is having this issue or knows a fix ?

**Comment by carloscabanero** [comment]
Have you tried [this](https://www.reddit.com/r/BlinkShell/comments/13vrajt/comment/jmbdbpp/)? We will probably be doing our own script so we can tailor this better to our scenario.
