### ISSUE TITLE
(iPadOS 17) OS text cursor takes up a row, input echoes draw in wrong spot

### ISSUE THREAD

**Issue by alexsavage** [blinksh/blink#1811]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iPad Pro 10.5"
iPadOS 17.0 (21A5277j) - Public Beta
Blink 16.1.10.772
3rd party Bluetooth keyboard (TypeCase Flexbook)

### Describe the bug

An OS text cursor is often visible on the bottom row of the screen, in addition to the HTerm cursor. Sometimes this makes input come in the wrong column, or disrupts the number of rows on the screen after, e.g., typing `clear`.

Expected behavior would be for the text cursor to only be drawn in the Blink shell at all times, and for placement to remain consistent.

Here is a screenshot of typing "tmux" while in this state:

![IMG_0352](https://github.com/blinksh/blink/assets/9620751/03003e37-a32c-4f5e-b9c3-ecc9d2cd5893)

Let me know if I can help with any other details. Thanks!

**Comment by yury** [comment]
Hello @alexsavage .

Thank you for your report. I created tracking issue #1812 for all iOS/iPadOS 17 related issues.

**Comment by thekeith** [comment]
@alexsavage I’m seeing this issue too. It may also be affecting things like Micro editor’s use of the mouse to adjust splits

**Comment by carloscabanero** [comment]
Thanks for jumping in. We have a fix for this and should make it to next TestFlight. Will give everyone a heads up here so you can report back. Thanks!
