### ISSUE TITLE
Prepare for iOS/iPadOS 17 

### ISSUE THREAD

**Issue by yury** [blinksh/blink#1812]
This is tracking issue for all 17 released issues:

- [x] #1811 
- [x] #1821

**Comment by thekeith** [comment]
@yury adding #1821 to the mix as well

**Comment by yury** [comment]
@thekeith can I send you TestFlight build so you can try fix for that?

**Comment by thekeith** [comment]
Sure thing

**Comment by yury** [comment]
@thekeith  please email me (yury at blink.sh) I will send you invite.
