### ISSUE TITLE
iCloud Sync Does Not Work

### ISSUE THREAD

**Issue by ghost** [blinksh/blink#1816]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Latest versions of Blink & iOS / iPadOS.

### Describe the bug
icloud syncing does not work for me. Hosts entered on my iPhone never propagate to my iPad and vice-versa.

I have tried various combinations of the following:
* Uninstalling & then reinstalling the app on both devices.
* Toggling iCloud sync (in blink) on and off.
* Deleting the .blink/hosts file.
* Restarting my devices.

Does this feature just flat out not work?

**Comment by yury** [comment]
Hello @blerg-sh  can you try now?
We forget to deploy new iCloud DB scheme.
Now it should be fine.

**Comment by ghost** [comment]
Fixed! Thanks @yury !
