### ISSUE TITLE
Missing smart keys row on iPad when building from 16-cleanup source

### ISSUE THREAD

**Issue by smorkin** [blinksh/blink#1819]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink version: App built in Xcode using latest code for 16-cleanup branch
iOS version: 16.6

### Describe the bug

On iPads (iPad mini 6, iPad Pro 2019), the extra keyboard row above the normal software keyboard does not show. However, it does show up on iPhones.

Reproducible both on hardware and on Simulator.

Screenshot:

![Screen Shot 2023-08-08 at 16 59 46](https://github.com/blinksh/blink/assets/6247147/89470d15-7d1e-4724-aee8-ea9ae292b669)

<details>
  <pre> The bug seems to be in the sync(…) method in SmarterTerminput.swift when deciding if _setupAccessoryView() should be called or not</pre> If traitCollection.userFaceIdiom == .ipad, the setup is never called. If I change the code to always calling the method for iPads, the row appears as it should, but I suspect there should be some more checks rather than my brute approach → I don't want to commit this change as a pull request.
</details>

**Comment by smorkin** [comment]
Also checked with the _snippets_ branch, and the same issue exists there.

**Comment by yury** [comment]
I think we can close this (See #1770). Feel free to reopen if needed.
