### ISSUE TITLE
Can't restore purchase

### ISSUE THREAD

**Issue by lpelati** [blinksh/blink#1820]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug

I bought the stand alone version for about 20€ or so, I know it's discontinued but reading on the website I found out that people that bought it before it was discontinued can continue to use the version of the app that was purchased. I can't do that, I'm forced to buy a subscription.

**Comment by carloscabanero** [comment]
You can find the latest info there: https://docs.blink.sh/migration

The migration deadline expired a while ago.
