### ISSUE TITLE
(iPadOS 17) OS text cursor in VSCode appears or exhibits blocking behavior

### ISSUE THREAD

**Issue by thekeith** [blinksh/blink#1821]
### Checklist

- [X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

1. iPad OS 17 Beta 5 developer release
2. Latest version of Blink Shell 16.1.12.800

### Describe the bug

* In VSCode, the OS cursor will appear at different locations in the app based on where you click (eg: the “Welcome to Visual Studio Code” text on the welcome page)
* The OS cursor placement will be with text in the UX, as well as in/near/around graphical elements (such as icons or menus)
* In addition, the cursor seems to make some menus disappear on click unless the trackpad touch is more deliberate

This is related to #1811 but happens in VSCode; it may be the same underlying issue at fault

(Screenshots for this are tricky, if needed I’ll try and capture a screen recording of the issue)

**Comment by thekeith** [comment]
@yury test flight build seems to have resolved so you can close, but new issues have come up (will make a separate issue)

**Comment by carloscabanero** [comment]
Done
