### ISSUE TITLE
Can’t access Documents and ICloud on IPad 

### ISSUE THREAD

**Issue by carstenf** [blinksh/blink#1822]
I downloaded blink.sh to my IPad
Typed code .
VSCode opens and I installed Blink-FS
Now I can see Documents and ICloud, but below are now files/folders visible.
What do I need to change to access the files and folders below Documents and ICloud?

second issue, I can’t close code.
I tried cmd+w, cmd+shift+w, shift+cmd+w, no reaction.

im using iOS 16.6

**Comment by yury** [comment]
Hello @carstenf.

Can you email me (yury at blink.sh) ~/.blink/blinkCode.log ?

```sh
cat ~/.blink/blinkCode.log | pbcopy
```
and paste in email.

**Comment by carstenf** [comment]
I send it to you, got it?

**Comment by carloscabanero** [comment]
@carstenf we got the logs, thanks! Would you mind to attach here a screenshot of the structure as shown in VS Code at the moment? Thanks

**Comment by carstenf** [comment]
<img width="834" alt="image" src="https://github.com/blinksh/blink/assets/58643140/581ba04a-2e4d-4e66-b04d-0147563a9851">

**Comment by carstenf** [comment]
That screenshot is ok?

I tried as well to connect to a AWS EC2.
It was connected but I don’t even see a tree, the blue folder icon don’t respond at all.
Super strange.
…and as I said, I can’t quit the code windows, which should be shift+command+W.
I checked the settings and it is that command.
I tried to close a regular terminal and it working.
So it looks like everything with code . is not performing as expected.

**Comment by yury** [comment]
With Blink v16.2.0 we introduced new quick actions bar (double cmd) it has `close` tab action. We are working on improving VSCode shortcuts integration.

**Comment by carloscabanero** [comment]
Hey @carstenf, so I have been taking a look at the logs and your screenshot and I could not see anything wrong, but maybe it is unclear how the extension works.

On local, I see that the extension is actually already serving files, so it looks like it works as expected. Documents and iCloud directory are referring to your Blink Documents and Blink iCloud folder. If you do a `ls iCloud` or `ls Documents`, are they also empty or do they show any files? I think maybe you expect to show your full iCloud folder, but Blink does not have direct access to that. You can use the `link-files` command to link other file structures from other apps.

About the remote over AWS EC2, can you try to connect first using the Files.app? Make sure you specify a Key or Password as automatic login is necessary. And make sure the remote also has sftp enabled.

I'm moving this as a Discussion as it looks to me like this is more a Support request.
