### ISSUE TITLE
Solarized theme - bold as bright

### ISSUE THREAD

**Issue by Kamik423** [blinksh/blink#183]
I picked the solarized theme and it totally broke a lot of the colors. They appear all grey. Fortunately I had the exact same issue on iTerm on my mac before. It is being well described [here](http://www.mseri.me/on-iterm2-and-solarized-dark/). It would be great if you added a an option to turn off bold as bright colors.

Thanks

**Comment by carloscabanero** [comment]
Thanks for your report! I will review and check how we can fix that. For the time being, you can probably also just change the colors of the default theme from https://github.com/blinksh/themes and adapt them to your liking.

**Comment by yury** [comment]
@Kamik423 blink v10 have this option

**Comment by carloscabanero** [comment]
Closing
