### ISSUE TITLE
Cannot use Control-] in Dvorak layout

### ISSUE THREAD

**Issue by avysk** [blinksh/blink#1833]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Fresh-installed on new iPad (no custom configurations) blink 16.2.1
iPadOs 16.6

### Describe the bug

Every time I press Control-] I see = instead. This prevents me from entering, for example, telnet control character. I have solved problem by going to config -> Keyboard -> Custom Presses and defining that Control-] should produce hex code 1D (which is Control-]). I must say that Control-] works in other programs; for example, in iVim.

I would expect Control-] working out of the box.

**Comment by yury** [comment]
Hello @avysk.
What keyboard and language do you use? I can't reproduce this issue yet.

**Comment by avysk** [comment]
Airpad Air 5th generation, "magic keyboard", English with Dvorak layout.

**Comment by avysk** [comment]
Yeah, forgot: "international English" model of "magic keyboard".

**Comment by avysk** [comment]
If it helps, modifier keys are set as following in Apple settings:

- Caps Lock -> Escape
- Globe key -> Control (the problem I describe happens with real Control key, not mapped)

 Maybe it will help, if I say that ']' in non-Dvorak produces '='.

**Comment by yury** [comment]
Can you press ctrl-] in this key logger https://jsfiddle.net/yuryk/1vdmk8ws/ , press copy markdown button and paste here results that you have.

**Comment by avysk** [comment]
I see equal:

| n |    type |        code | key     |  kc | mods | repeat | l | comp | iType | data |
|--:|--------:|------------:|:--------|----:|-----:|-------:|--:|-----:|------:|-----:|
| 1 | keydown | ControlLeft | Control |  17 |    C |        | 1 |      |       |      |
| 2 | keydown |       Equal | ]       | 187 |    C |        | 0 |      |       |      |
| 3 |   keyup |       Equal | ]       | 187 |    C |        | 0 |      |       |      |
| 4 |   keyup | ControlLeft | Control |  17 |      |        | 1 |      |       |      |

As said, ^-] works in, for example, iVim. It also does not explain

- why Blink produces '=' not '^-='
- why my "fix" worked

**Comment by avysk** [comment]
Something is broken in underlying javascript?

**Comment by yury** [comment]
Yep, smth with safari....


typed text:

    

| n |    type |         code | key     |  kc | mods | repeat | l | comp | iType | data |
|--:|--------:|-------------:|:--------|----:|-----:|-------:|--:|-----:|------:|-----:|
| 1 | keydown |  ControlLeft | Control |  17 |    C |        | 1 |      |       |      |
| 2 | keydown | BracketRight | ]       | 221 |    C |        | 0 |      |       |      |
| 3 |   keyup | BracketRight | ]       | 221 |    C |        | 0 |      |       |      |
| 4 |   keyup |  ControlLeft | Control |  17 |      |        | 1 |      |       |      |

**Comment by avysk** [comment]
It was Microsoft Edge. I'll try Safari now.

**Comment by avysk** [comment]
The very same result in Safari.

**Comment by yury** [comment]
Yep, Safari javascript engine is only way to build browsers, so it would be the same...

**Comment by avysk** [comment]
I can also try the usual (non-Dvorak) layout and see if it helps.

**Comment by avysk** [comment]
Yes, switching to different layout helps, and in Dvorak ^-] produces =.

**Comment by avysk** [comment]
I just pressed ^-= in Dvorak (where ] usually is). Interesting results.


typed text:

    =

| n |        type |         code | key     |  kc | mods | repeat | l | comp |      iType | data |
|--:|------------:|-------------:|:--------|----:|-----:|-------:|--:|-----:|-----------:|-----:|
| 1 |     keydown |  ControlLeft | Control |  17 |    C |        | 1 |      |            |      |
| 2 |     keydown | BracketRight | =       | 187 |    C |        | 0 |      |            |      |
| 3 | beforeinput |              |         |     |      |        |   |      | insertText |    = |
| 4 |       input |              |         |     |      |        |   |      | insertText |    = |
| 5 |       keyup | BracketRight | =       | 187 |    C |        | 0 |      |            |      |
| 6 |       keyup |  ControlLeft | Control |  17 |      |        | 1 |      |            |      |
| 7 |      change |              |         |     |      |        |   |      |            |      |

**Comment by yury** [comment]
I think, I can implement workaround for this particular case.

Are any other issues with Dvorak layout?

**Comment by avysk** [comment]
I did not notice any other issues. I was using Blink and Dvorak for a long time (years) with iPad 3rd generation and "keyboard folio", and I think there were no problems with ^-] either. Maybe iPadOs got updated?

**Comment by avysk** [comment]
Let me check what ^-= actually produces (Control-[ works, though [ is in a place of -).

**Comment by avysk** [comment]
Control-= produces =, and it seems to work this way everywhere.

**Comment by yury** [comment]
Ok, I implement workaround for that case. Thank you for your help!

**Comment by yury** [comment]
@avysk  Can I send you TestFlight build, so you can try fix first? Turns out it is your kb layout + Dvorak layout. On US kb - I can't reproduce that.

**Comment by avysk** [comment]
Sure thing, just explain to me what I have to do.

**Comment by yury** [comment]
email me at yury@blink.sh - I will invite you to TestFlight when Apple review build.

**Comment by avysk** [comment]
Done.

**Comment by yury** [comment]
Ok, Got confirmation that it is fixed.
