### ISSUE TITLE
How to build the source code 

### ISSUE THREAD

**Issue by mikeiit** [blinksh/blink#184]
Hey all, 

Don't know if anyone heard about this problem before. I downloaded the pre-complied source code package. I opened the project in Xcode and built it. Failed. 

I changed the bundle ID to another random one. And signed with my personal apple account. ( in project general file). Built it. Failed again. The error message says 
========================================================================
The 'Apple Push Notification' feature is only available to users enrolled in Apple Developer Program. Please visit 
https://developer.apple.com/programs/ to enroll.
No profiles for 'Mike.Blink' were found:  Xcode couldn't find a provisioning profile matching 'Mike.Blink'.
Code signing is required for product type 'Application' in SDK 'iOS 10.1'
Code signing is required for product type 'Application' in SDK 'iOS 10.1'
Code signing is required for product type 'Application' in SDK 'iOS 10.1'
Unable to run command 'CpResource Blink.app' - this target might include its own product.
Unable to run command 'Touch Blink.app' - this target might include its own product.
Unable to run command 'Validate Blink.app' - this target might include its own product.
========================================================================

Did anyone have similar experience and how did you guys handle it? Please help. Thank you!

Mike

**Comment by ezzizzle** [comment]
Hi Mike,

I was able to get it to compile but I do have a developer account allowing the Push Notifications entitlement. You could try turning off the Push Notifications setting under the Capabilities tab in the general project file. I was able to build and run with this turned off.

Cheers,
Eric

**Comment by bryanforbes** [comment]
I was having problems building it last night, but tried again today and doing the following steps gave me a successful build on my iPad:

1. Ensure the project is closed in Xcode and quit Xcode
2. Discard any changes in the repo:
```
git checkout -- Blink.xcodeproj/project.pbxproj
rm -rf Blink.xcodeproj/project.xcworkspace/xcshareddata/
```
3. Open the project in Xcode
4. Before doing anything else, go into the capabilities for the project and turn off Push Notifications
5. Go to the General tab and change the bundle identifier to something that will work for your team
6. Stay in the general tab and select your team under the "Signing" section
7. Connect the device you want to build for and select it in Product -> Destination
8. Build and run on the device

**Comment by mikeiit** [comment]
Hey Eric and Bryan,

Thanks for looking this up. I got a Apple developer Account and got the
provisioning file and bundle ID from there and cloned the repository again.
Then the problem was solved. I haven't tried to build without an apple
developer account since then. But a lot of other people do get success in
this way as well.

Thanks again guys. Happy Thanksgiving!!

Mike

**Comment by carloscabanero** [comment]
In theory Apple provides a "free" developer account that allows to load a very wide general profile and compile the app in your device for 7 days. I tried to help mike but we were not able to make that work. Anybody had luck doing that? Please let us know so we can document it! :)

**Comment by bryanforbes** [comment]
I failed to mention: I have a free developer account and the instructions I posted work with it.

**Comment by carloscabanero** [comment]
Awesome! I will add it to our KB too :)

**Comment by Aktariel** [comment]
I'm having this issue as well, with a "free" developer account - except that I can't remove the Push Notifications capability. Instead, I have a message that says "9 Capabilities unavailable" and a button that's a web link comparing the free and paid dev account features.

I've tried bryanforbes' solution, and it did **not** work for me.

**Comment by carloscabanero** [comment]
@Aktariel what Xcode version are you using?

**Comment by Aktariel** [comment]
Xcode 8.1

**Comment by daylightbrightledlight** [comment]
I have a similar issue. I do not know what to do to get it working on my device.

**Comment by mainczjs** [comment]
Just a small update: In addition to the _Push Notification Capabilities_, I also had to remove the _iCloud and KeyChain Capabilities_, as they were not associated with my free Developer Account.

**Comment by crispinb** [comment]
I have it working with a nonpaid developer account by disabling:
- background modes -> remote notifications (unticked)
- keychain sharing (switch off)
- icloud (switch off)

**Comment by carloscabanero** [comment]
Could someone please send me a PR with that to update the BUILD file? Thanks!

**Comment by CelsoSantos** [comment]
I'm sorry to re-open this after almost a year, but somehow i can't build the app. I've pretty much disable all functionality and yet I keep getting an error that my personal account doesn't have push notifications support.

Now, I'm not an Apple Developer with a paid account, I did have one from university some time ago but not anymore.

Do I need to have a paid developer account in order to be able to build/test Blink with Xcode? I'm on the latest versions of everything (MOS, iOS and XCode)

Could someone please clarify?

Thanks

**Comment by goerz** [comment]
My understanding is that it should work without a paid account, but the app will only be signed to run for 7 days (which is pretty useless)

**Comment by CelsoSantos** [comment]
Agreed. The intent was to try to deploy something to the iPad to check the build/deploy process but I've never been able to really use XCode. It's such a mess, seems like disabling stuff doesn't really apply on the rest of the code, there's always some pending issue left and no easy way to navigate to the actual issue/error..

Thanks for the clarification.

**Comment by NightMachinary** [comment]
It does work, make sure to disable everything on a fresh clone that has not
its certificate changed to you. Redeploying to device is also pretty easy
if you have a WiFi network in home. I think you might even be able to
script the redeployment in that case, using third-party ios installers from
github.

**Comment by martinezhermes** [comment]
Any suggestions on how to compile this? I'm a developer and get 999+ warnings with 100+ error due to libssh I read the whole read me and cloned the repo with --recursive and the get_framework.sh, what do you guys do to deploy this?

**Comment by JTCodeDev** [comment]
I had the same issue, I was scratching my head on this for a long time. Eventually figured out that you can't build this of x86 or x64. So destination can't be an x86 ipad simulator. When I output to my lab device directly it compiled fine right away.

**Comment by martinezhermes** [comment]
> I had the same issue, I was scratching my head on this for a long time. Eventually figured out that you can't build this of x86 or x64. So destination can't be an x86 ipad simulator. When I output to my lab device directly it compiled fine right away.

Oh I see... let me try that again
