### ISSUE TITLE
Passphare rejected. DSA key

### ISSUE THREAD

**Issue by melo** [blinksh/blink#185]
Hi,

I was trying to use Blink but my passphrase (letters and numbers, no symbols) isn't accepted.

I paste the SSH key (a Putty-style key, with the --- BEGIN ---, --- END --- armor; the standard OpenSSH format was not even recognized), the key is accepted and I get asked for the passphrase.

I type the passphrase, and Blink just repeats the passphrase prompt. I type it again several times, same behaviour.

I used the same key with ssh-add and with Panic's Prompt 2 SSH client for iOS, both worked flawlessly.

How can I help to debug this further?

Thank you,

**Comment by carloscabanero** [comment]
Hi Pedro! Thanks a lot for your report! 

Keys should be recognised without issue as long as they are RSA keys. Would you mind to generate a new Putty public / private key pair that doesn't work for me so that I can test this further? Also, OpenSSH format keys should work as well, we currently use OpenSSL so there should be no problem there either.

Thanks!

**Comment by melo** [comment]
That explains it.. This is a DSA key.

Thank you.

**Comment by carloscabanero** [comment]
Yup, sorry about that. The minimum will be a RSA key, for security reasons. Hopefully adding ecdsa, etc... soon too :)

If this is something you need or thing might be useful feel free to add it as a new story :)

**Comment by melo** [comment]
I suggest only that you mention that somewhere :), that only RSA keys are supported.

Thanks,

**Comment by carloscabanero** [comment]
I will add this as part of the next milestone, changing a bit the copy on the webpage and within the app. Thanks!

**Comment by melo** [comment]
Another thing: you might want to link to the OpenSSH pages about deprecated dsa keys (which I had missed... :/ ):

* http://www.openssh.com/legacy.html (mentions "OpenSSH 7.0 and greater similarly disable the ssh-dss (DSA) public key algorithm. It too is weak and we recommend against its use.").

I could not find a more specific page on the OpenSSH project page, just some mailing list posts of some BSD and Linux distro's mentioning this move. Even the release notes for the version that deprecated DSA don't mention this which is odd.

* https://lists.freebsd.org/pipermail/freebsd-stable/2016-August/085171.html;
* https://www.gentoo.org/support/news-items/2015-08-13-openssh-weak-keys.html;
* http://security.stackexchange.com/questions/112802/why-openssh-deprecated-dsa-keys.

Thank you.

**Comment by carloscabanero** [comment]
This is actually great!! I will link to it also in the documentation we are working on. :)

**Comment by melo** [comment]
I checked the release notes, there is no mention of deprecating DSA at all https://www.openssh.com/releasenotes.html, that is weird...

But the legacy.html states that it will be disabled. DIdn't find anything else :).

On a separate note, using RSA keys works just fine :). Eagerly waiting for ECDSA and friends :)

Thank you!

**Comment by carloscabanero** [comment]
That is really confusing, might be worth giving a heads up to the openssh guys too.

**Comment by melo** [comment]
I just did that, sent an email about this discrepancy to one of their mailing lists.

**Comment by melo** [comment]
Just to document this fully :)

It is mentioned on the 7.0 release notes but under "DSS", not "DSA". That was why I didn't find it...

Via Darren Tucker on the OpenSSH Devel list:

> In the 7.0 release notes:
> 
>  * Support for ssh-dss, ssh-dss-cert-* host and user keys is disabled
>    by default at run-time. These may be re-enabled using the
>    instructions at http://www.openssh.com/legacy.html
> 
> DSS = Digital Signature Standard, DSA = Digital Signature Algorithm
> but they refer to the same thing.  Given that the SSH standards use
> ssh-dss, by rights keygen should refer to it as "dss" instead of "dsa"
> but that ship sailed long ago.

via http://marc.info/?l=openssh-unix-dev&m=148031715728078&w=2

**Comment by yury** [comment]
Hi @melo,

Sorry for late response but blink support DSA since v12.

Thank you.
