### ISSUE TITLE
I cannot make my ssh connect after version 17 upgrade

### ISSUE THREAD

**Issue by jk-gna** [blinksh/blink#1864]
I cannot make any SSH connect on blink iOS after upgrade version 17. Before the upgrade, it works pretty fine. How can I fix it?

**Comment by yury** [comment]
what is your ssh -vvvvv output?

**Comment by terhorst** [comment]
+1. v17.0 killed jump hosting for me. Regular ssh still seems to work. ~`ssh -vvvvv -J ...` outputs nothing.~ I wasn't using enough `-v`s. It get's stuck on the line:
```
ssh_socket_connect_proxycommand: Executing proxycommand 'ssh -W [192.168.0.1]:22 <jump_host>'
```

**Comment by carloscabanero** [comment]
Hi! Please check this thread https://github.com/blinksh/blink/discussions/1868, and make sure you update to the latest 17.0.1
