### ISSUE TITLE
Conflicting UX when creating private Keys makes it uncertain if they are backup up in iCloud

### ISSUE THREAD

**Issue by danielzen** [blinksh/blink#1865]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

* Blink v17.0.0.837 (Test Flight)
* iPadOS v16.6.1

### Describe the bug
I could go into greater detail but, put simply there is conflicting information and it isn't clear which is correct. See screenshots:

![IMG_0057](https://github.com/blinksh/blink/assets/1350534/54bb3320-0c0e-4023-8d9d-d1a3f2cdfaa2)
![signal-2023-09-19-211852_002](https://github.com/blinksh/blink/assets/1350534/46730e14-efa7-402f-ad84-ba9646171ea6)

**Comment by carloscabanero** [comment]
Hi Daniel! At the moment they are not backed up. The first prompt is from iOS itself. The key is actually in all your devices but we are just not backing up the "public part" of the key so the other devices can use it.

Closing here as it is already being tracked on #1574. I will see what we can do on this iteration.
