### ISSUE TITLE
ssh key files in iPhone

### ISSUE THREAD

**Issue by mikeiit** [blinksh/blink#187]
Hey guys,

Just tried to connect to a AWS Linux - ubuntu instance inside blink with SSH command. I did this in iPhone. However, i was wondering where we can put the key pair in iPhone. Anybody has similar experience? Or just I am not using the Blink right? 

Thanks happy thanksgiving weekend! 

Mike

**Comment by ezzizzle** [comment]
Hi Mike, I think you currently have two options. The first is to get a copy of the AWS private key on your iPhone, copy the contents into the iPhone's clipboard, then add a new key in Blink with the "Import from clipboard" option. The other option is to create a key in Blink (or use the default one), copy the public key and install that key into your AWS instance's "authorized_keys" file. 

Hope that helps, I'm only new to the project so there may be other ways to do this.

**Comment by mikeiit** [comment]
Hey Eric, 

Thank you! It works perfectly fine! I can connect to the instance just like what I did in my Mac! 

Mike

**Comment by carloscabanero** [comment]
Thanks for the message Mike, gave me the idea to  create an article in our future KB about how to do this :)
