### ISSUE TITLE
Password doesn't get saved on a new host

### ISSUE THREAD

**Issue by nriley** [blinksh/blink#188]
When adding a host with a saved password, the password doesn't save the first time I tap Save.

I get a message logged in UICKeyChainStore ("the key must not to be nil" [sic]).  If I go back to the host and retype the password, it saves.

Current Blink master (c9470707b5) on iOS 10.1.1, iPhone 6s and iPad Air.

**Comment by carloscabanero** [comment]
Thanks! Will fix asap :)
