### ISSUE TITLE
Shell Gestures don't work in Code, and alternatives hard to find.

### ISSUE THREAD

**Issue by danielzen** [blinksh/blink#1883]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
iPadOS 17.0.2
Blink 17.0.1.839 TestFlight

### Describe the bug
I am currently trying to navigate between 2 open `code` instances. And the only way I can figure out is to move to another app or the iOS homescreen, and then move back to Blink, at which point I can see the open instances. I can't get any other gestures or keyboard shortcuts to help me out.

### Expected behavior
It should be easy to navigate between open windows whether they be shells or Code.

**Comment by carloscabanero** [comment]
This is part of #1623. The way to do it atm is to use keyboard shortcuts, Cmd-Shift-[ ] will move you between them. This is another reason to migrate to a different and separated application.

**Comment by carloscabanero** [comment]
Did that do the trick @danielzen ?
