### ISSUE TITLE
Wrong error message on port not open

### ISSUE THREAD

**Issue by uvesten** [blinksh/blink#19]
When trying to mosh to a server that doesn't have the correct port forwards set up, blink says 
    
    Authentication by password failed

Instead of (like the standard mosh client) 

    mosh did not make a successful connection to host:port.

**Comment by carloscabanero** [comment]
Thanks for the heads up! I think this might happen before that. Would you mind running it with a --verbose and send us a capture to see where it might be breaking? Thanks!

**Comment by carloscabanero** [comment]
This should already be fixed. We now support an (almost) real ssh client on the background. Let me know if it doesn't work as it should.
