### ISSUE TITLE
Run mosh-client without ssh

### ISSUE THREAD

**Issue by chetan-reddy** [blinksh/blink#190]
A server I use doesn't have ssh, and i have to manually start a mosh-server instance, copy the MOSH_KEY and start mosh-client on my laptop like so:
MOSH_KEY=key_that_mosh_server_spits_out /usr/bin/mosh-client server_ip server_udp_port

I haven't been able to figure out how to run mosh-client directly on blink. Is it possible? If yes, please let me know how.

**Comment by carloscabanero** [comment]
Unfortunately we do not provide a way to introduce a mosh key separately. I will add this as a feature to our mosh command as it will prove useful in the future too.

Thanks for the report!

**Comment by PHCSJC** [comment]
I also hope run mosh-client without ssh

**Comment by chetan-reddy** [comment]
@yury since I created this ticket, my use case has changed a bit. I now have access to ssh on the server, but only via VPN. But mosh is available even without VPN. If I could provide a separate HostName for mosh and ssh, i would be able to use blink by:
1 - turn the VPN on
2 - have blink establish an ssh connection to the SSH HostName for launching the mosh-server
3 - have blink send the UDP packets to the MOSH HostName (resolves to a public IP)
4 - turn off the VPN and still have a working MOSH connection

Not sure which of  'Add mosh-client command' or 'Add separate MOSH HostName in addition to SSH HostName' is easier for you, but the latter would definitely be easier to use for me. The former would work too though.

**Comment by yury** [comment]
Here is demo what we got:
https://cdn.discordapp.com/attachments/441940293240225793/483927660540592138/IMG_0060.TRIM.MOV

**Comment by chetan-reddy** [comment]
That looks great @yury . Thanks for implementing this. Can the port and hostname be picked up from a stored mosh Hosts config, or do we have to supply them from the command line like you do in the demo?

**Comment by sweihub** [comment]
When I stopped the ssh server, the mosh refuses to work, so the mosh is not an replacement of SSH, it should not rely on ssh connection, but the keys are OK.

```
❯ mosh root@10.20.30.3
/usr/bin/mosh: Could not connect to 10.20.30.3, last tried 10.20.30.3: Connection refused
kex_exchange_identification: Connection closed by remote host
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
```

**Comment by alexbodn** [comment]
how is the key generated?
may it be generated by an OTP like Google authenticator?
