### ISSUE TITLE
Self installing mosh-server

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#1905]
This comes from user interviews. A lot of users keep SSH connections because they have no access to do a mosh installations on the server. We noticed other protocols would use the ssh connection to install a binary on the remote, then communicate through it. 

We have seen people request this on mosh itself:
- https://github.com/mobile-shell/mosh/issues/1006
- https://github.com/mobile-shell/mosh/issues/188

We also think this could help other people who want to use mosh in other "platforms". For example, [Tailscale + SSH]() can become Tailscale + Mosh. Or Codespaces and other Remote dev environments could easily update to a Mosh connection directly from the mosh-client.

**Comment by carloscabanero** [comment]
Two options were discussed for development:
- Create a pre-flow to install mosh-server through a script directly in the remote.
- Deeper integration through a ssh library.

The first has the advantage that the installation could be faster, but the disadvantage that the remote needs internet access.
The second one was a great fit for Blink as we can already control SSH and SFTP at the library level. The problem is static binaries for some platforms may be very heavy and installation may take a while.

**Comment by carloscabanero** [comment]
- [x] Mosh client using Swift.
- [x] Static Mosh bootstrap
  - [x] Enable different mosh bootstrap strategies.
  - [x] Create a Prompt to ask users if they want to go ahead with the remote installation.
- [x] Enable old mosh as mosh2 in case there are issues during testing.
- [x] Mosh Static binaries.
  - [x] Scripts. Most of the work has already been done by the mosh project itself.
  - [x] Git Workflows. https://github.com/blinksh/mosh-static-multiarch/
- [ ] Create a Snip as an alternative for installation server-side.

**Comment by carloscabanero** [comment]
Aberrant having a problem, via Discord: https://discord.com/channels/441939332442619905/442378162425298954/1176383501537390672

- [x] From feedback. Some users in high security environments cannot install external binaries on their own. Even doing so by mistake would cause them a lot of trouble. We should have a way to disable the dialog so that installing static-mosh is not offered and can be disabled and only re-enabled through a flag.

- [x] Aarch64 as Arm64 - support on RaspberryPi

- [x] `build mosh` fails (unknown -O flag)

**Comment by carloscabanero** [comment]
- [x] Crash logs from TestFlight. Mosh crashing on start. Apparently when it cannot resolve the host but the flow cannot complete. xcode://organizer/crashes/downloadPoint?adamId=1594898306&platformId=iOS&installPlatformId=iOS&analyticsPointId=D5sxsR477Q6kn8glQarB2L&bundleId=sh.blink.blinkshell.

**Comment by carloscabanero** [comment]
- [x] Mosh hanging at the end of session https://discord.com/channels/441939332442619905/441940293240225793/1192519720616857620

**Comment by carloscabanero** [comment]
- [x] Check #269 for new implementation

**Comment by carloscabanero** [comment]
- [x] Rename mosh2 (mosh legacy) to mosh1 as mosh2 seems to indicate that it is the new one.

**Comment by dueyfinster** [comment]
The link from release notes in the iOS app to this issue is broken - typo in "isues" in the url

**Comment by carloscabanero** [comment]
Thanks for the heads up, will fix it today.
