### ISSUE TITLE
pico, nano, emacs: anything but vi!

### ISSUE THREAD

**Issue by rcfa** [blinksh/blink#1911]
please, pretty please, include some lightweight or heavyweight editor that’s not ed/vi derived, they are my personal hell.
Anything will do: pico, nano, an emacs variant…

**Comment by carloscabanero** [comment]
Hehe, we have gotten this one a bunch of times. Everyone has their preferences but we want to keep the shell to a minimum. We will be including something soon. Closing here though as there are already discussions for the Idea https://github.com/blinksh/blink/discussions/1515, https://github.com/blinksh/blink/discussions/1583 and I think many others.
