### ISSUE TITLE
Cannot apply to back for school

### ISSUE THREAD

**Issue by gernophil** [blinksh/blink#1920]
Hey, I am a postdoc at a university and I wanted to apply for the back to school campaign. However, I cannot open your google docs form (see screenshot). Any other way to do this?

![image](https://github.com/blinksh/blink/assets/19264855/efc4d2b6-0c57-4673-b016-53fc4c0abd42)

**Comment by NatashaKits** [comment]
Thanks for reaching out. Our Back to School Campaign runs once a year, usually from September 1st to November 1st. Apologies if the website listing is a bit misleading, we will update this promptly.

Clicking on the website link, our documentation does stipulate these dates.

You are welcome to follow us on [Twitter](https://twitter.com/BlinkShell), or our [website](blink.sh) to be notified ahead of the next campaign opportunity.

Thanks

**Comment by carloscabanero** [comment]
Added for this iteration so we can fix the webpage.
