### ISSUE TITLE
blink crashes upon hitting arrows

### ISSUE THREAD

**Issue by xpbe0** [blinksh/blink#193]
in landscape mode on iphone7 (ios 10.1.1 14b150)
<img width="669" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/2191551/20751808/34612868-b6fe-11e6-9571-2813c07d61ab.png">

**Comment by carloscabanero** [comment]
Hehe, great catch!! Normally they are disabled, but for some reason after rotating they get re-enabled. Anyway, no reason to crash the app. Thanks for your report!

**Comment by xpbe0** [comment]
👍

**Comment by ezzizzle** [comment]
Hi Carlos. I'm happy to take a look at this if you like. Are you intending the buttons just to do nothing or would you like them to act like the left and right arrow buttons in the SmartKeys?

**Comment by carloscabanero** [comment]
Thanks for jumping in Eric! If we could make them behave like arrows, that would be best, but I will start by applying your fix to raw branch right now. It might be that there is no way to do arrows easily as those seem to control movement at a higher level than UIKeyInput :)

**Comment by ezzizzle** [comment]
You look to be right Carlos. Been playing with it for a while and couldn't get anything at the UIKeyInput level to detect or intercept the arrow keys. Looks like we would need to move it to a higher level to get anything - UITextInput? Annoying they don't work in the same way the hardware keys do.

Do you want me to keep looking and see if we can do something with UITextInput or would you prefer to have me look at something else given the arrow keys exist in the SmartKeys control?

**Comment by carloscabanero** [comment]
Thanks for taking a look Eric! I think the patch to avoid crashing is
enough, and as you said those keys are already on smart keys.

It would be great if you could take a look at #199 or if you wanna play a
little bit with JS, #67 or #171 are very interesting too. Let me know which
one you take to mark it with a WIP label, so we do not step on each other :)

I'm preparing a version before or right after Christmas, so we might be
able to fit any fixes or new stuff until Tuesday.
