### ISSUE TITLE
Focus not restored properly when switching back to Blink

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#194]
Reported by @mrrcollins on Twitter.

When switching back to Blink and having a Bluetooth connected, sometimes the focus is not restored. This happens specially when coming back from some apps like Telegram.

It might be that they do not easily give up the first responder status, but maybe we can make Blink enforce that in a better way, and still play fair with other apps specially on SplitView.

**Comment by mrrcollins** [comment]
I thought I'd add some additional information.

If you switch back to Blink from Telegram with either cmd-tab or double-tapping the home key, Blink does not have focus until you tap the screen. With Telegram it's every time, with iCabMobile it was hit or miss. 

Switching from Telegram to Blink through the home screen doesn't exhibit this behaviour.

**Comment by yury** [comment]
@mrrcollins it's strange :) I have opposite behaviour. Blink got focus right, but I have to touch input field in telegram to restore focus.
Tested with Blink v3.0.55.55. Dev 20 2016 from App Store. iOS 10.

**Comment by carloscabanero** [comment]
@yury I think this one has improved with your changes. Can we close?
