### ISSUE TITLE
Blink breaks out of mirror mode when SSH key forward confirmation dialog pops up

### ISSUE THREAD

**Issue by jgonggrijp** [blinksh/blink#1944]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

- Blink v17.1.0.854
- iPadOS 16.7.1
- External non-touch screen connected (non-touch makes this problem extra-problematic)
- Mirror mode
- Host-based agent forwarding with confirmation

### Describe the bug

Previously discussed here: https://github.com/blinksh/blink/discussions/1844#discussioncomment-6941917.

I log in to a host with `ssh -A`. The first time I need the forwarded key, the confirmation dialog comes up as intended. However, Blink breaks out of mirror mode while doing so, placing the confirmation dialog on the external screen (above a new Blink window). The external screen is non-touch, I cannot reach it with the mouse and the dialog does not respond to keyboard keys, so there is no way to respond to the dialog. I end up in a deadlock.

I have been working around this by first disconnecting the external screen, but this is only a very partial solution. As soon as I reconnect the external screen, the connection is lost, which breaks agent forwarding again. This means I have to disconnect the external screen every single time when I need to forward the key, which is excruciating.

**Comment by carloscabanero** [comment]
Thanks! Will mark this as critical so we can fix before release next week.

**Comment by carloscabanero** [comment]
Fixed. It was a tricky one, but we fixed it for this and other alerts. Should be out on v17.2.0.

**Comment by carloscabanero** [comment]
We should be all good now. Please reopen if you experience any other issues.
