### ISSUE TITLE
iOS version crashes on startup after recent beta update

### ISSUE THREAD

**Issue by dominickolbe** [blinksh/blink#1945]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink 17.1.0
iOS 17.4 (21E5184i) Developer Beta

### Describe the bug

App crashes and closes right after launch.

**Comment by carloscabanero** [comment]
Hi! Thanks for the heads up. We haven't been able to replicate this from our side. Unfortunately, also got nothing from crash reports, and asked around on our Discord to see if anybody else who updated is having the same issue. Is this still happening? Does it happen every time you open the app? Do you see anything on the screen before that?

**Comment by dominickolbe** [comment]
(video attached at the end)

I only noticed it after the second Developer update last week. Also on the same update on my ipad and there everything is working. Just re-installed the app, but still same issue.
Let me know if I can share more information somehow

iPhone 14 Pro

![IMG_30D97D3F0950-1](https://github.com/blinksh/blink/assets/6094725/d722b38e-a17e-4f17-9826-12160930cab7)
https://github.com/blinksh/blink/assets/6094725/3b190b40-1f40-46d1-9761-083b641ce8b4

**Comment by b-** [comment]
I have this issue, too. It instantly crashes on launch whether I use the latest version on the App Store, or either of the latest two available builds on TestFlight. 

I’m on an iPhone XS, running 17.4 developer beta. Same build as @dominickolbe iOS 17.4 (21E5184i)

I tried completely removing the app and reinstalling, both from the App Store and from TestFlight.

**Comment by carloscabanero** [comment]
Thanks for chiming in on this. Yeah, looks like we have it figured out and it is an issue on iPhone only as you confirmed. We will try to patch today and release with 17.2.0.
