### ISSUE TITLE
App is apparently not available in the Thai AppStore

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#1947]
Via https://discord.com/channels/441939332442619905/441940293240225793/1201599212996001822

**Comment by abdulatif1707** [comment]
It is not available at Uzbekistan AppStore too.

**Comment by carloscabanero** [comment]
Hi! Everything looks good from our side. Have you checked this? https://github.com/blinksh/blink/discussions/1955. We compiled it based on what worked for others before.
