### ISSUE TITLE
No Secure Enclave support on visionOS

### ISSUE THREAD

**Issue by shlevy** [blinksh/blink#1958]
[The Vision Pro copy](https://www.apple.com/apple-vision-pro/) mentions secure enclave, but Blink claims there is none on the device. Will need to dig further to see if it’s just not exposed to apps or if it’s purely a problem of running as an iPad app on visionOS.

![image](https://github.com/blinksh/blink/assets/487050/80b0caef-538a-4fe8-ac44-4349c3af1038)

**Comment by carloscabanero** [comment]
I can imagine this may be because we are not a native app and maybe there are some security provisions to run iPad apps. Thanks for the heads up.

**Comment by shlevy** [comment]
I’m not sure if this is due to switching to the Blink community edition or the visionOS 1.1 beta, but I was able to generate a secure enclave key.
