### ISSUE TITLE
Arrow keys don't cycle previous commands

### ISSUE THREAD

**Issue by 0xCMP** [blinksh/blink#196]
When I want to run a previous command using the arrow keys on the iPad Pro Smart Keyboard does not cycle back to the previous command.

**Comment by carloscabanero** [comment]
That's weird, what Blink version are you running? Cannot reproduce it :(

**Comment by 0xCMP** [comment]
You know what. Today now it's working. It goes in and out. Don't close the issue, I'll keep a closer eye out for it. I couldn't move up and down at all through the history. I'm not sure if I tried quitting

**Comment by fearoffish** [comment]
I just had this, the only way I fixed it was by closing blink (swiping up) and starting again.

**Comment by 0xCMP** [comment]
@fearoffish is that killing the app or just the session?

**Comment by fearoffish** [comment]
I wasn't in a session the last time it happened. So not sure. I just closed the app and swiped up on it in the app switcher.

**Comment by MacDragon** [comment]
Had this happen several times aswell, not spotted a pattern, but sometimes history just seems to not work.

**Comment by carloscabanero** [comment]
I think I might have it, does it happen after exiting a session? It looks like the terminal doesn't reset the raw mode correctly for linenoise. A hotfix for now for the time being is to use the emacs shortcut Ctrl+p or Ctrl+n.

**Comment by bergie** [comment]
@carloscabanero one way I can reproduce this is by opening a MOSH session, then running `killall mosh-server` on the machine I connected to. This drops me back to Blink's shell, but without history on arrow keys.

**Comment by carloscabanero** [comment]
This was due to issues with the Raw mode within Blink. It should have been fixed in v10.
