### ISSUE TITLE
`whatsnew` links to GitHub issues broken due to typos

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#1967]
### Checklist

- [x] ~Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)~ **Using TestFlight version** `v17.2.1.865 (Test Flight). Feb  7 2024`
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

N/A

### Describe the bug

The _**New Mosh Client**_ and _**Mosh1 just-in-case**_ items (at least¹) in `whatsnew` are broken because they lead to broken URLs like `https://github.com/blinksh/blink/isues/1905` (note the missing `s` in `issues`.

* * *
¹ And, I thought, one other, but I can’t find it now? For some reason, the links are opening in random Safari tab groups which is making it hard for me to systematically check them all)

**Comment by carloscabanero** [comment]
Fixed! I said I was gonna fix it through the week, but totally slipped. Done now. Thanks for the heads up / reminder ;)

Not sure about the opening in random Safari tab groups. I have seen that if you already have a link open in Safari in a tab group, it will take you there, and that throws me a curveball sometimes as I may have totally forgotten. Could that be the case?
