### ISSUE TITLE
When mosh exits it does not scroll to the bottom

### ISSUE THREAD

**Issue by 0xCMP** [blinksh/blink#197]
This is a couple issues.

1. When I exist mosh I can't tell (if I was using emacs or something) because the screen clears aren't respected properly.
2. It doesn't scroll to the new portion of the screen where the input is now
3. It doesn't auto scroll to the input when I start typing again.
4. There is no indication I'm not at the bottom visually (although, not sure if I'd like that changed, I'd rather fix the previous problems.)

**Comment by carloscabanero** [comment]
Sorry, I do not fully get what's the problem, would you mind attaching a screenshot so that I can see how it looks like after exiting emacs? Thanks!

**Comment by 0xCMP** [comment]
Sorry for the unclear issue. Basically when I exit Emacs it doesn't clear the screen like iTerm usually would. It also doesn't auto scroll the terminal output to the bottom when typing again. Usually what happens is I'm switching between screens and I decide to exit Emacs. But the window has scrolled. So I'm not sure if I actually exited Emacs. I have to scroll myself to see the current prompt again even though I can type in it before I can see it.

**Comment by carloscabanero** [comment]
I have seen this a couple times already, HTerm manages the scroll and creates this issues sometimes. I do not know what we can do from our side, but we will try.

**Comment by 0xCMP** [comment]
Maybe we make an issue upstream and link back here? I'm on my phone now but
if I remember I'll try to see if they have any existing issues about this
and link them here.

**Comment by cgull** [comment]
Some of this might relate to upstream Mosh too.  I confess the description isn't terribly clear to me either.

Mosh, unlike XTerm and other terminal emulators, doesn't have an alternate-screen mode, which allows full-screen applications to run and then restore the command-line screen that was showing before they ran.

But it also sounds like there are problems with screen scrolling and/or cursor positioning.  @0xCMP, is the text cursor visible on the screen when you exit Emacs?  When you mention "switching screens" are you switching Mosh/SSH sessions within Blink or doing something else?

I've noticed an issue in Mosh: sometimes, when you exit Mosh while running a remote full-screen application where the cursor is in the middle of the screen, your cursor ends up in the middle of the terminal window overwriting the stale text from your dead Mosh session.  But I *think* that's something different from what you're describing.

**Comment by cgull** [comment]
Could you capture a series of screenshots or a video illustrating this problem?

**Comment by cgull** [comment]
I've tried to reproduce this on Blink 4.23.  No luck.  Anybody have a simple way to reproduce this?

**Comment by carloscabanero** [comment]
This is what I could replicate:
1) Start emacs with external keyboard connected.
2) Exit emacs and turn on the software keyboard.
3) The screen moves but the redraw doesn't happen properly for that line. I can confirm this is an HTerm issue and not a Mosh one, although Mosh makes it more confusing in some cases as it doesn't properly restore the state. But anyway, HTerm side.

![img_0159](https://cloud.githubusercontent.com/assets/536729/22742496/efd200d2-ede4-11e6-869a-990bde189a59.PNG)

@0xCMP can you confirm this is what you were experiencing? Also, new version makes it better because the keyboard behaves more properly.

**Comment by 0xCMP** [comment]
I haven't tried it very recently, but I will tonight and try to get screenshots of what I mean.

The issue was mainly entering a full screen app (emacs in this case) and then exiting that app. For some reason the text of that full screen app isn't properly cleared (i.e. in iTerm, mosh or not, the text emacs or vim printed isn't displayed after exiting). Because it isn't properly cleared then I need to see the prompt to know if I've exited or not. Typing doesn't auto scroll so I need to scroll my self to make sure.
