### ISSUE TITLE
Meta key modifier not supported for Emacs use

### ISSUE THREAD

**Issue by 0xCMP** [blinksh/blink#198]
I wanted to use emacs and it's kind of difficult to get it to do what I want. I can use esc, but it's not the same as a true alt/meta key. 

In the terminal the option key (what I thought would be the meta key) simply prints out the unicode characters that you'd expect maybe somewhere else in iOS but not in a terminal and definitely not in Emacs. There are no options to tell Blink that I want the option key to be treated this way.

**Comment by carloscabanero** [comment]
Hi!! Thanksfor your message :)

If I understand correctly, Blink already supports that (I use emacs myself, so this feature was a must ;) ). Under settings>keyboard, tap on the Alt modifier and select Esc, that should make Alt behave like an escape modifier and not like the escape key.

Let me know if you think we can modify something on the experience to make that more obvious. I will prepare an article for our docs on "how to configure emacs" and "how to configure vim", so people can go straight there and learn a few more tips and tricks.

Thanks!

**Comment by 0xCMP** [comment]
Thanks, yea I tried it out and this works well. Maybe there should be some small text on that config screen which brings this to the user's attention?

**Comment by larme** [comment]
Hi @carloscabanero, it seems that if I map alt to esc it works as expect. But if I map cmd to esc then it will not work at all.
