### ISSUE TITLE
SSH does not support "ssh -l login name" 

### ISSUE THREAD

**Issue by ctschach** [blinksh/blink#1981]
### Checklist

- [X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Latest iOS version downloaded from the App Store...

### Describe the bug

If you look at the possible parameters for ssh on various unix distributions, you'll always see that there always:

`ssh [-l login_name]
`

The current version of ssh used in blink only support the

`ssh username@domain.com 
`

approch. However, for compatibility aspects it would be great to also support parameters like:

`ssh domain.com -l username
`

**Comment by carloscabanero** [comment]
We do have that flag and it is used in some configurations. Can you do `ssh -l <user> -G <host>` and check what the configured output is?

![image](https://github.com/blinksh/blink/assets/536729/9c12294d-9665-4a01-98c7-53bb1f6b1f57)

**Comment by ctschach** [comment]
Oh, you are right. Looks like I was running an older version. My fault. After updating to the latest from the App Store, I can now also use the "-l" version.

Thank and sorry....

**Comment by carloscabanero** [comment]
No worries, that's what we are here for. 

PS: It looks like you triggered a bug with parameters at the end of the command (due to a change in the Swift arguments parser). New versions should allow you to have parameters everywhere.
