### ISSUE TITLE
Imported theme fails to take effect. Error checking.

### ISSUE THREAD

**Issue by xpbe0** [blinksh/blink#199]
1/ config->appearance->add_a_new_theme
2/ fill_in: 'Borland', enter_url_address: 'https://github.com/blinksh/themes/blob/master/themes/Borland.js' -> Save
3/ <- Appearance
4/ selecting theme 'Borland' doesn't change the last selected default theme

(Pattern is the same for any other imported theme. Borland was used just as an example)

iphone7 , ios 10.1.1 (14B150)

<img width="509" alt="pastedgraphic-2" src="https://cloud.githubusercontent.com/assets/2191551/20891823/38134f7e-bb0c-11e6-9175-b8fc67da81bc.png">

<img width="360" alt="pastedgraphic-3" src="https://cloud.githubusercontent.com/assets/2191551/20891841/464a8490-bb0c-11e6-9422-86bacf23cb1b.png">

**Comment by LATBauerdick** [comment]
I'm having the same problem on an iPad Pro 12.9"

**Comment by carloscabanero** [comment]
Hi! You have to link to the "JS" file, which is the raw file on github. https://raw.githubusercontent.com/blinksh/themes/master/themes/Borland.js

I will improve the copy and add this as a "bug", because the system should know that it has received an html file, and not a JS file.

**Comment by xpbe0** [comment]
Hi Carlos, well excuse my stupidity of course loading .js.html file wouldn't work and as the 'raw' button disappears in github mobile version workaround would be:

`... config -> appearance -> add_a_new_theme -> Open_Gallery -> <FIND_THEMEJS_FILE>, switch to desktop view -> press 'raw', copy URL <- Appearance/Add_a_new_theme/Enter_URL_address`

However, .*.js.html file (IMHO) shall not be accepted as valid format to import
thanks a lot, 🍻 
/Pete

**Comment by carloscabanero** [comment]
This was already fixed on 4.0. We added checks on the .js and also autocorrection of the URLs when importing from GH.
