### ISSUE TITLE
Missing tab completion for `mosh1`

### ISSUE THREAD

**Issue by fingolfin** [blinksh/blink#1995]
There are still issues with the new `mosh` command. The suggestion is to use `mosh1` as a workaround.

But `mosh1` does not provide tab completion for server names which makes it much less convenient to use. But perhaps adding tab completion to it could be achieved with relatively little effort? (Naively spoken, my hope would be that the code implementing tab completion for `mosh` could just be slightly modified to also deal with `mosh1`)

**Comment by carloscabanero** [comment]
Will enable this for the time being. As you say, it isn't hard.

**Comment by l2dy** [comment]
I think it's just a one line change.

https://github.com/blinksh/blink/blob/e4bb980e1caa6cc15dad65d20c4953e9bcac4540/Blink/Complete.swift#L204

**Comment by fingolfin** [comment]
This works in the Testflight version, thanks
