### ISSUE TITLE
mosh doesn't execute optional command

### ISSUE THREAD

**Issue by rekendahl** [blinksh/blink#20]
With mosh you can run the following to launch tmux automatically (and detach other clients):

`mosh ekendahl@192.168.11.81  -- tmux attach -d`

This command works in `term` but `blink` seems to ignore the command part. It will connect to the machine but not issue the command.

**Comment by carloscabanero** [comment]
Already fixed, please reopen if it doesn't work as it should! Thanks again Robert ;)
