### ISSUE TITLE
Support new M4 iPad display sizes

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#2009]
Via https://discord.com/channels/441939332442619905/441940293240225793/1240131069433348116

**Comment by xaeroseven** [comment]
👍

**Comment by prairie-guy** [comment]
Assume this includes new iPadPro M4 as well . . .

**Comment by anomaly256** [comment]
> Assume this includes new iPadPro M4 as well . . .

Yep, only the pros are on M4 at this stage.

I'm not able to view the discord link - does this report include the bug regarding the layout (cover/fit/fill) being ignored and text truncated at the top of the screen?

If not I'll open a new issue about that
(ref: https://www.reddit.com/r/BlinkShell/comments/1ct7i0h/ipads_rounded_corners_cuts_text_in_blink/ )

**Comment by carloscabanero** [comment]
Yes, this should cover all the cases, Reddit issue included.

We should have this on 17.3.0 right before WWDC, but if anything happens, may release a patch sooner than that.

**Comment by chrisbennight** [comment]
Discord link does not work for me - just gives a "no text channels error"

**Comment by ghost** [comment]
@carloscabanero Any uodates on when a fix for this will be released?

**Comment by carloscabanero** [comment]
TF today and everyone over the weekend-Monday, once approved.

**Comment by ivahos** [comment]
I just downloaded v17.3.0.903 and it still do not work on my 13” M4 imac pro. Still get text cut by the corners and when I double press command the layout option is missing from the shortcut bar. Changing the default layout in Settings - > Appearance does have no effect on new terminal screens.

**Comment by ivahos** [comment]
The 905 build works now apart from one small nitpicking issue on the 13” m4 ipad pro. It looks like the offset from the top left corner of the screen is a couple of pixels to short. The b in the blink prompt looses a pixel or 2 at the top. Other than that it works great now.

**Comment by carloscabanero** [comment]
@ivahos Are you having any issues with the Software Keyboard? Is the Smart Keys bar showing properly?

**Comment by ivahos** [comment]
> @ivahos Are you having any issues with the Software Keyboard? Is the Smart Keys bar showing properly?

I am using the magic keyboard (a hw keyboard)

**Comment by carloscabanero** [comment]
Would you mind to disconnect it and let me know if those are showing properly? I cannot replicate in the Simulator and want to make sure it is working and displaying as it should. Thanks!

**Comment by ivahos** [comment]
> Would you mind to disconnect it and let me know if those are showing properly? I cannot replicate in the Simulator and want to make sure it is working and displaying as it should. Thanks!

It actually gets a little worse with the SW keyboard
Here are 2 screenphotos (since the screenshots dont show the curved display)
https://webserver.webhotel.au/IMG_0827.jpg (with hw keyboard)
https://webserver.webhotel.au/IMG_0828.jpg (with SW keyboard)

**Comment by carloscabanero** [comment]
Sorry, the screenshots are not working :(

**Comment by ivahos** [comment]
> Sorry, the screenshots are not working :(

Sorry, wrong machine. 
https://webby.webhotel.au:8443/IMG_0827.jpg (with hw keyboard)
https://webby.webhotel.au:8443/IMG_0828.jpg (with SW keyboard)

**Comment by ivahos** [comment]
As you see in the 2nd screenphoto the b looks more like a o. Reconnecting the hw keyboard does not revert the shift to the pre-detachment state. I have to force quit blink and restart to get back to the 1st screenshot state 

The font size also make a difference. 
It looks like the text starts to high up on the display. when I use Cmd+- to make the font smaller if I go far enough the first lines b disappears behind the curve and the 2nd lines b starts to loose the bar in the b

edit2 
I made another screenphoto of btop running in a tmux session with a very small font. It shows the problem also happens at the bottom of the display. 

https://webby.webhotel.au:8443/IMG_0829.jpg. Sorry about the sharpness and the dirty screen

**Comment by carloscabanero** [comment]
Thank you for the thorough testing! I think the issue is that although the resolution and corners in these devices has changed slightly, they haven't changed the insets themselves. I will try to adjust from our side. 

Thanks again!!

**Comment by carloscabanero** [comment]
Fixed now. So although new OLED iPads have an effective usable size of 20 px more, that means the radius is also slightly bigger so you need to adjust the margins and make them bigger by around 3 pixels. It is more dramatic on the "safe fit", where you almost go down a half line just to make the left and right margins 0. Anyway, fitted to pixel perfection ;)

This was before
<img width="127" alt="Screenshot 2024-06-13 at 4 37 46 PM" src="https://github.com/blinksh/blink/assets/536729/e8be51e5-937f-4ee8-800f-7a8e75d117dd">

This is after
<img width="136" alt="Screenshot 2024-06-13 at 4 38 06 PM" src="https://github.com/blinksh/blink/assets/536729/1207a8f7-3b79-441f-803c-0a2ad6e8b435">

**Comment by ivahos** [comment]
> Fixed now. So although new OLED iPads have an effective usable size of 20 px more, that means the radius is also slightly bigger so you need to adjust the margins and make them bigger by around 3 pixels. It is more dramatic on the "safe fit", where you almost go down a half line just to make the left and right margins 0. Anyway, fitted to pixel perfection ;)
> 
> This was before <img alt="Screenshot 2024-06-13 at 4 37 46 PM" width="127" src="https://private-user-images.githubusercontent.com/536729/339545532-e8be51e5-937f-4ee8-800f-7a8e75d117dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMTczODYsIm5iZiI6MTcxODMxNzA4NiwicGF0aCI6Ii81MzY3MjkvMzM5NTQ1NTMyLWU4YmU1MWU1LTkzN2YtNGVlOC04MDBmLTdhOGU3NWQxMTdkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QyMjE4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzgwYmEyZGJiNDIyZTUxOGY0MWVkZWVjNDc2MTU0YWMxZThlNTcxMWE5YWJiMTI4MjdlZGVlNWUwYWQ0YzEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.is8l4pYDOlEgXsti86Z3t-t80AAay1xTqm4-ucU1UJo">
> 
> This is after <img alt="Screenshot 2024-06-13 at 4 38 06 PM" width="136" src="https://private-user-images.githubusercontent.com/536729/339545566-1207a8f7-3b79-441f-803c-0a2ad6e8b435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMTczODYsIm5iZiI6MTcxODMxNzA4NiwicGF0aCI6Ii81MzY3MjkvMzM5NTQ1NTY2LTEyMDdhOGY3LTNiNzktNDQxZi04MDNjLTBhMmFkNmU4YjQzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QyMjE4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWJlZDJkMTgxYjJhZWYyZTFmMDcxNzU3ZWI3MWFkYThiMzk1ZGI5NGEwYWNmZmEyZTdiMWYyZDQ2MGIyYTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7TEQiBGmhVo-F6Lv4eoBEmbwEItgqxjUrGUFdbC_Ek8">


When will this update reach testflight?

**Comment by carloscabanero** [comment]
I pushed a few hours ago. Let me know.

**Comment by ivahos** [comment]
> I pushed a few hours ago. Let me know.

Thanks for the fix. Looks much better now. No clipping of characters at the top and no clipping at the bottom unless you make the font size so small that the characters are unreadable anyway :)

**Comment by carloscabanero** [comment]
Thanks for confirming. Looks like we are wrapping up for release then (yay!).

**Comment by carloscabanero** [comment]
Done 17.3.0
