### ISSUE TITLE
Add ProxyCommand to ssh

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#203]
Implement the ProxyCommand parameter to specify a command to use to connect to a server. This is useful (almost a requirement) in conjunction with Agent Forwarding and an ssh-agent #81.

**Comment by carloscabanero** [comment]
First mentioned on #139

**Comment by RevREB** [comment]
I seriously need this, Every server I need to access in behind a bastion servers. I know its hard to prioritize functions but I am willing to bounty this. Seriously, Im in for $200, ($300 if it works with a standard ssh config file, dont wanna have to define the proxy rules over and over again). I'm serious! What can I do to get this is accelerated and into a patch ASAP?

**Comment by RevREB** [comment]
no seriously! https://www.bountysource.com/issues/40003463-add-proxycommand-to-ssh

**Comment by brandonshough** [comment]
Bump!!!!!

**Comment by carloscabanero** [comment]
I have this working but it needs ssh agent forwarding to be really useful. For mosh that would require us to catch up with the latest version. @RevREB do you have the keys on the other server?

**Comment by carloscabanero** [comment]
I can confirm I have now ProxyCommand up and running, working on the Agent and the rest of the client. Fingers crossed to have this before holidays!

**Comment by AZLisme** [comment]
need this feature badly.

**Comment by RevREB** [comment]
@carloscabanero sorry for the delay in responding, and I look forward to playing with the work you've done (when might the changes be included in the iOS store version), but to answer your question... No, there would not be private keys on the "bastion" host.

**Comment by brunodeatlanta** [comment]
Looking forward to this.

**Comment by carloscabanero** [comment]
This comes next ;)

**Comment by mgbaozi** [comment]
Really looking forward to this, Is there any update about this and “agent forwarding”?

**Comment by RichardBronosky** [comment]
I do believe you will be the first ios product on the market to support ProxyCommand. That should motivate you. I would state that in your app store description "above the fold"!

**Comment by brunodeatlanta** [comment]
Really looking forward to this!!
	





On Tue, Apr 17, 2018 at 4:45 PM -0400, "Bruno Bronosky" <notifications@github.com> wrote:












I do believe you will be the first ios product on the market to support ProxyCommand. That should motivate you. I would state that in your app store description "above the fold"!

**Comment by jinie** [comment]
I'll be looking forward to this. As for being the first, the dead iSSH (https://web.archive.org/web/20120415035140/http://www.zinger-soft.com:80/iSSH_features.html) had a feature where you could forward ports via ssh, which would then be available to other apps on your iOS device.
This was extremely useful, i.e. mapping a port to an internal web server, then using safari to browse it via ssh.

**Comment by RevREB** [comment]
@carloscabanero is there any movement on this? It’s the only thing stopping me from doing my whole job from an iPad.

**Comment by yury** [comment]
@RevREB we are working on libssh, so we are close to ProxyCommand and port forwarding.

https://cdn.discordapp.com/attachments/441940293240225793/463731449615613953/IMG_0511.TRIM.MOV

**Comment by saptarshiguha** [comment]
I saw that video. Can’t can’t wait enough to see this and proxycommand. Such an excellent ssh app

**Comment by yury** [comment]
Here is demo of ProxyCommand

https://cdn.discordapp.com/attachments/442023972138123276/469899397820579840/ScreenRecording_07-20-2018_19-11-42.MP4

**Comment by saptarshiguha** [comment]
Perfect! Looking forward to trying it out. An aside: recently i learned about

```
ControlMaster auto
ControlPath ~/.ssh/sockets/%r@%h-%p
ControlPersist yes
```
The bastion host requires me to use MFA (duo) to login. Before i added this to the config, i had to enter my DUO prompt on my phone with every ssh access. Now wiht this in my config, as long as the first SSH session is open, i dont get MFA prompts anymore.

So nice.

Would blink support this for this version or in future?

**Comment by yury** [comment]
Oh, interesting. For next release we will try to add support for iOS 12 sms codes suggestions feature. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yury** [comment]
But, yes. With new ssh command architecture it is not very hard to implement. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saptarshiguha** [comment]
awesome! I might even upgrade to a 12"! For the record, my ssh/config is

```
Host hala
     User sguha
     HostName hala1.x.y.z
     ProxyCommand ssh ssh.A.B -W %h:%p
     ControlMaster auto
     ControlPath ~/.ssh/sockets/%r@%h-%p
     ControlPersist yes
```

When i execute `ssh hala`, i get the following [mfa prompt](https://screenshots.firefox.com/BJkaA3qZ0LQfBLLo/null). When i enter '1', the DUO app on my IOS phone pops up asking me to accept. Once accepted, the ssh login completes and i'm in.

(for the record, the above image will expire in 14 days). 

Currently this works with blink very nicely, `Control*` options allow me to do this just once (as long the first connection is kept open).

Cheers and *thanks* for all the hard work.

**Comment by MasahiroMorita** [comment]
How can I configure .ssh/config on blink app?
I really want to use ProxyCommand function!

**Comment by yury** [comment]
Hi @MasahiroMorita,

ProxyCommand is only available in TestFlight beta versions. No config support yet. Only with `ssh -o "proxycommand=..."`

**Comment by rfldn** [comment]
I would love the extra mile to ProxyJump, that would help working with bastions and such.

**Comment by aphecetche** [comment]
Any ETA for when this (most wanted I must say ;-) ) feature will land in the App Store version of the app ?

**Comment by yury** [comment]
Hi @aphecetche,

My ETA is next week :)

But it would be great if you can help us test beta version on Test Flight. I can send you invite on your GitHub email if you don't mind.

**Comment by aphecetche** [comment]
@yury sure I can try to test it, please send the invite.

**Comment by yury** [comment]
@aphecetche sent you invite.

Run `ssh-agent` in one tab, `ssh-add <id>` and then try to connect.

**Comment by aphecetche** [comment]
Thanks. How should I give my feedback ? Here on github ?

**Comment by yury** [comment]
Here or at [discord](https://discord.gg/ZTtMfvK)

**Comment by saptarshiguha** [comment]
May i also get an invite? I would like to try with my setup.

**Comment by yury** [comment]
Hi @saptarshiguha, just sent invite to you.

**Comment by saptarshiguha** [comment]
I did install the test flight and i'm writing this (having uninstalled previous versions)
```
ssh -o "proxycommand=ssh -q bastion.Foo.net nc %h %p 2>/dev/null" hala
```

I also tried

```
ssh -o "proxycommand='ssh -q bastion.Foo.net nc %h %p 2>/dev/null'" hala
```

but in both cases i got  

```
usage : ssh [....]

```

**Comment by yury** [comment]
Yep, `2>/dev/null` broke params.

ssh -o "proxycommand=..." ...

**Comment by saptarshiguha** [comment]
Thanks. I tried

```
ssh -o "proxycommand=ssh -q bastion.Foo.net nc %h %p " hala

which prints `(yes/no):` and control is returned to the blink prompt. Usually the equivalent 

```
 ssh -o ProxyCommand='ssh -q bastion.Foo.net nc %h %p' hala
```

sends me DUO prompt on my phone which i need to accept.

**Comment by yury** [comment]
Please try

```sh
ssh -o "proxycommand=ssh -q -W %h:%p bastion.Foo.net" hala
```

**Comment by saptarshiguha** [comment]
same result

**Comment by yury** [comment]
Can you make screenshots? from blink and other terminal?

It should be something like on this screenshot?
![8563174e-93ad-45b2-9fd6-de6612f148e5](https://user-images.githubusercontent.com/5250/46555030-cb173b80-c8ea-11e8-912c-904aef203cfb.jpeg)

**Comment by saptarshiguha** [comment]
Yes, 

From my laptop here is the screenshot (note the `-W %h:%p`  syntax does not work).
<img width="1391" alt="screen shot 2018-10-05 at 1 11 42 pm" src="https://user-images.githubusercontent.com/113324/46557881-41db1700-c8a0-11e8-9b1c-89eec755f205.png">

(i've blanked out hostnames)

When i press enter, i get the following prompt on my phone

<img width="529" alt="screen shot 2018-10-05 at 1 09 35 pm" src="https://user-images.githubusercontent.com/113324/46557785-f0cb2300-c89f-11e8-8577-df7b558a6107.png">

I accept and you see i'm logged in.

On the iPad (not yet ios12, the version prior), you can see the following image
<img width="1112" alt="screen shot 2018-10-05 at 1 07 35 pm" src="https://user-images.githubusercontent.com/113324/46557826-12c4a580-c8a0-11e8-9af4-058bf74eb966.png">

`hala` is in Hosts and corresponds to the same host as above. Moreover even if i enter some incorrect hostname(at the end, the bastion is still correct), i get the same response.

hope this helps.

**Comment by aphecetche** [comment]
Hi,

I’m a bit at lost. My first test is pretty simple : 

Host linode-ui
  User laurent
  Hostname 178.Xxx.yyy.zzz

But I can’t connect using a simple ‘ssh linode-ui’

I assume this is because I misunderstood something obvious ;-)

 A) is the .ssh/config supposed to be read ?
B) if it is, where do the keys are supposed to come from ? (From config or from the .ssh directory)

**Comment by yury** [comment]
Hi,

`.ssh/config` is not supported yet. You need to run `config` command and add host and keys there.

**Comment by aphecetche** [comment]
Ok, so I’ve misunderstood how far the functionality I’d need is already available. 

I mean, if I need to get host+keys in config (as now) + type by hand the -o « proxycommand= .... » then that’s not quite what I had in mind ;-) 

Guess I’ll have to wait a bit more then...

**Comment by saptarshiguha** [comment]
I updated via testflight and eager to try it out again. How do i go about editing .ssh/config on the ipad?

**Comment by yury** [comment]
We currently do not fully support .ssh/config. You should use ‘config’ command. 
config -> hosts -> <your host>  -> ProxyCmd

**Comment by yury** [comment]
Hi @saptarshiguha,

Yes, if your sshd don't allow port forwarding, then you should use nc.

In ProxyCmd you should write `ssh -q bastion.shared.xyz nc %h %p`. (without `2>/dev/null`)

But before you go to your host ssh to your bastion directly.
It will prompt you for host keys acceptance. You should accept it.

Then try connect to host with proxy command.

**Comment by saptarshiguha** [comment]
Thanks much. 

1. I did ssh into bastion - accepted keys (so that's where the yes/no was coming from) got returned to blink prompt

```
ssh bastion
Connected to x.y.z.x
```

but returned to blink prompt (i..e not in remote terminal). If  i ssh into bastion from my desktop I get
(along with a DUO prompt)

```
Autopushing login request to phone...
Success. Logging you in...
```

Similarly if i ssh into hala, i just get returned to blink prompt.

**Comment by yury** [comment]
Yes, it should return to blink.
But now try to connect to your host with ProxyCmd thought bastion.

**Comment by saptarshiguha** [comment]
that too returns to blink. I'm also  free to chat on Discord. I can join there if thats better

**Comment by saptarshiguha** [comment]
1. One should have an host entry for the bastion e.g. my entry has `Host` field "bastion" and `HostName` "bastion.foo.boo.net". SSH into this host once.

then

2. I have an entry for my bastion in Blink config with the `Host` field called "bastion". For the host which requires a bastion e.g. "hala" in the above discussion , i have the following for the `ProxyCommand` setting

```
ssh -o "RemoteCommand=nc %h %p 2>/dev/null" -q bastion
```

previously i was using the bastion's `HostName` field. 

This *works* for me with DUO MultiFactor Auth too.

Thanks so much!!
