### ISSUE TITLE
Blink iOS creates an always-empty `snips` folder in `On My iPhone` local storage, even when snips storage is set to iCloud on a fresh install

### ISSUE THREAD

**Issue by jimmy-zhening-luo** [blinksh/blink#2061]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

#### Version

- Blink v18.0.1.940
- iOS 18.0.1

##### In-App

- iCloud Sync: On
- Snips →
  - Default Location: iCloud Drive
  - Blink Snips Index: Off
- X Callback URL: On

##### iCloud

- Blink: On
- iCloud Drive →
  - Blink: On

##### iPhone

- Blink →
  - Document Storage: iCloud Drive

#### Repro Steps

1. Install `Blink` on a fresh iPhone. _(If needed, configure `Blink` according to settings above)_
2. Launch `Blink` and create a snip.
3. Launch `Files` app and navigate to `iCloud Files` → `Blink` → `snips`. Verify the presence of your newly created snip.
4. In `Files` app, navigate to `On My iPhone`.

#### Expected Behavior

Local `Blink` folder is hidden because there's nothing in it.

#### Actual Behavior

Local `Blink` folder is visible, because there's a single empty folder in there called `snips`, which always contains 0 snips.

__If the `snips` folder is deleted, `Blink` automatically creates a new one on next launch.__

##### ✅ iCloud Drive

![iCloud Drive: correct behavior](https://github.com/user-attachments/assets/fb7fe914-ad06-405b-9dc8-88b0813b8c92)

##### ❌ On My iPhone

![On My iPhone: wrong behavior](https://github.com/user-attachments/assets/a42b88f1-a6dd-4298-af9c-f79cf30c1e54)

**Comment by carloscabanero** [comment]
Hi! Even though you see snips as 0 items, that is because iOS is hiding the dot files and folders. There is a .github folder as the Snips library is downloaded from GitHub automatically and updated from there: https://github.com/blinksh/snippets.

**Comment by jimmy-zhening-luo** [comment]
Why is the GitHub folder present even though I have the "use snips library" option turned off?
