### ISSUE TITLE
File.app integration not working in latest TestFlight build on iPadOS 17

### ISSUE THREAD

**Issue by mistakenideas** [blinksh/blink#2069]
Blink version: 18.1.0.949
iPadOS version: 17.7.1

When navigating to a previously configured Blink host share in Files.app, the popup has a formatting issue (step 3) and shows an error message, not sure if this is intentional?
![IMG_3474](https://github.com/user-attachments/assets/b101e75d-5b65-4f3d-8d8e-7a68aabcbcd3)
.
Removing these old shared folders and recreating them also doesn’t work. After creating a new shared folder (and in the latest release getting a popup ro ‘turn on ’)  I get this message when navigating to it in Files.app: Content Unavailable - The folder contents could not be displayed because of an unknown error. 

SSH and SCP to these hosts continues to work as before. But am now unable to use Files.app integration or test this or the replication functionality. 

I’ve tried setting LogLevel DEBUG2 in the SSH CONFIG for the host but have no messages in .blink/fileprovider.log since before this update. 

I’m still on iPadOS 17.7 if that makes any difference? I don’t have another device to compare to behaviour on iPadOS 18. 

_Originally posted by @mistakenideas in https://github.com/blinksh/blink/discussions/2067#discussioncomment-11202712_

**Comment by carloscabanero** [comment]
@mistakenideas Have you enabled the "Replicated" toggled when creating the Provider? There are only two initial operations going on at the start, establishing the ssh connection and listing the root folder. SFTP / SCP do not require password, correct?. Are you listing "home" ~/ as-is? In case it is a different folder, is it the right one?

The dialog is from the previous version and unfortunately it isn't displaying errors properly yet for the new one. Logs are currently disabled as well. I will prioritize to improve this so we can get you up and running again.

**Comment by mistakenideas** [comment]
Thanks for the extra info @carloscabanero that’s reassuring to know.
I was very confused and assumed I had missed something in trying to get the logs.

- I’ve tried with and without ‘Replicated’. Same result. 
- SFTP/SCP is working from within blink without prompting for a password (hosts are configured using keys, one keychain and another passkey)
- I’ve tried “home” ~/ as well as subfolders

P.S this isn’t an issue for my usage of the app, so please don’t reprioritise on my account. I have got used to using sftp. But I am happy to do what I can to help track down the problem here.

**Comment by carloscabanero** [comment]
The next TF version should add a validation step within the app that should help us with this. Will ping you here once it is out.

**Comment by mistakenideas** [comment]
Apologies for not getting back to you earlier on this. 
In an interim build (963) the new file provider seemed to be working while the old one was not. There were some oddities but I didn’t have time to dig into testing and describing them. 
In the latest build (965) it all seems to ‘just work’. So I’ll close this issue.
