### ISSUE TITLE
Some ssh exec commands not working properly.

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#207]
ssh foo@bar 'ping 8.8.8.8' doesn't work. Works without '', output doesn't provide a carriage return and crashed on CTRL+C.

![czhohfow8aaawdw jpg-large](https://cloud.githubusercontent.com/assets/536729/21125222/fb66fe8a-c0b1-11e6-9290-fcbdca4b92a8.jpeg)

**Comment by yury** [comment]
Hi @carloscabanero!

Thank you for feedback :)

I think it is fixed. 

![6c8f343a-9321-4a05-b030-8f800eba420d](https://user-images.githubusercontent.com/5250/53976741-ab45a700-4118-11e9-9938-35d8ae9eb67e.jpeg)
