### ISSUE TITLE
scp does not work with ProxyJump

### ISSUE THREAD

**Issue by mhoran** [blinksh/blink#2075]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink: v18.0.1.940 (App Store). Oct  4 2024
iOS: 18.1.1

### Describe the bug

When using the `scp` command with a host behind a `ProxyJump` I get the following error:
```
Copy failed. connError(msg: "Socket error: disconnected")
```

I can `ssh` to the same host just fine. Interestingly, neither the proxy host nor the destination host show any errors in the logs. It seems this connection isn’t even making it off my device (though I haven’t debugged further than logs; I can pull a network dump if requested.)

`scp` to/from a host behind `ProxyJump` should work.

**Comment by carloscabanero** [comment]
This should work but, nonetheless, there is a new clteaned up path on TestFlight for this, so it does not make sense to debug this at the AppStore. Are you on TF by any chance?

**Comment by mhoran** [comment]
I'm not on TF yet, but I just applied. I tried to build myself but something is wrong (seems the frameworks aren't loading in my simulator.) I'll keep poking at it...

**Comment by carloscabanero** [comment]
Send me your email over DM on Discord or at carlos at blink.sh and I will add you when we release the next Build, so you can test this properly. Thanks!

**Comment by mhoran** [comment]
Confirmed this is fixed in the TF build — thanks!
