### ISSUE TITLE
Weird focus behavior in split screen mode

### ISSUE THREAD

**Issue by rekendahl** [blinksh/blink#21]
Blink acts unexpectedly in split screen mode. For example if I have Blink and tweetbot up in split screen and I'm typing in tweetbot then I can't simply touch blink to regain focus (this is what I can do with other apps).

Instead I need to either dismiss the keyboard bar at the bottom (from tweetbot) and then touch or use cmd+tab to reselect blink.

**Comment by goerz** [comment]
This seems to work fine for me, on an iPad Pro 13 inch (both with the Apple Smart Keyboard and the Software Keyboard)

**Comment by carloscabanero** [comment]
This should be fixed on v0.916. Please let me know & feel free to reopen! :)

**Comment by lukebrowell** [comment]
Using version 0.927  when using Remotix in left split and Blink in Right Split, Blink steals keyboard focus from Remotix (even when last touch has been to remotix screen), preventing keyboard input on remotix app. This issue does not occur with other apps in right split (e.g. Notes).
