### ISSUE TITLE
Locale not available

### ISSUE THREAD

**Issue by IMF2000** [blinksh/blink#210]
Update 3.0 appears to have bricked it.

![img_9122](https://cloud.githubusercontent.com/assets/4673216/21287688/84c8cce8-c469-11e6-979c-8548fcd9ed82.PNG)
![img_9124](https://cloud.githubusercontent.com/assets/4673216/21287689/84dd286e-c469-11e6-93cf-87d626843cb6.PNG)
![img_9121](https://cloud.githubusercontent.com/assets/4673216/21287691/84f61b6c-c469-11e6-92be-65fa1a75688a.PNG)
![img_9123](https://cloud.githubusercontent.com/assets/4673216/21287690/84e1d27e-c469-11e6-8698-9ae860d2c6f1.PNG)

**Comment by IMF2000** [comment]
As a work around I added the en_US.utf8 locale to the server.

**Comment by agkozak** [comment]
Yes, I'm having this problem on four different CloudLinux share hosting accounts.

**Comment by carloscabanero** [comment]
Blink now enforces a clean Unicode environment on destination, as Mosh requires it too. The result is the same as in terminal app and others. If this is causing trouble on machines, I will roll back in a couple days and make it optional.

**Comment by agkozak** [comment]
Keeping it optional would be great. I can't always adjust the locale on some of the servers I use.

**Comment by strowger** [comment]
+1 here, removed the hockeyapp test version this morning and installed the app store one and immediately couldn't log in with the same error as imf2000 reported.

Same workaround as he suggested also fixes it for me and functionality appears to be retained (ie I can still type £ :-)

**Comment by carloscabanero** [comment]
I will unroll this today so that we can have the fix asap. Sorry about any problems this is causing you.

**Comment by carloscabanero** [comment]
Rolled back and on master branch and the AppStore for download. Please let me know if you find other issues, closing here :)
