### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xMrWhite** [blinksh/blink#213]
Mosh is GPL, which means it can't be released in the app store. I'm not going to report this anywhere else, but you are on very shaky ground with the app store version. This project and allowing devs to install it is fine of course.

**Comment by geoffmacintosh** [comment]
The mosh people disagree with you, it seems. 

https://github.com/mobile-shell/mosh/issues/198

**Comment by xMrWhite** [comment]
I did not see that you had linked your own mosh library with a license amendment in COPYING.iOS.
