### ISSUE TITLE
Cursor shape change.

### ISSUE THREAD

**Issue by giulioungaretti** [blinksh/blink#22]
It would be super awesome to implement that! 
For example vim-insert mode and vim normal mode. :D

**Comment by carloscabanero** [comment]
Actually, it appears that what doesn't support cursor change currently is Mosh :( 
https://github.com/mobile-shell/mosh/issues/352

We would have to talk to them on how feasible this would be.

**Comment by carloscabanero** [comment]
We have this already (hterm) and it only depends on sending the right esc sequence. Under ssh it will work, under mosh unfortunately not yet.

**Comment by gabzim** [comment]
any change this will get implemented? I often look at cursor shape to know if I’m in insert mode, it’s not huge but it would certainly be nice to have this working

**Comment by jg-rc** [comment]
this is something that is stopping me to fully feel comfortable using, cursor shape was a small detail that helped my productivity. i would be awesome to have it
