### ISSUE TITLE
Cursor disappears when moving around in vim, back spacing on command line

### ISSUE THREAD

**Issue by calmh** [blinksh/blink#220]
It seems that after a cursor move the cursor blink sequence is restarted in the "off" position. That means that when repeatedly arrowing around in vim, for example, the cursor is continuously off and thus invisible. You must stop moving to let the cursor appear.

**Comment by yury** [comment]
@calmh There is an option for that now now - config -> Appearance -> Cursor Blink

Blink: v4.024.1

**Comment by calmh** [comment]
I cloned the repo, built and installed, but I don't see this option?

**Comment by yury** [comment]
@calmh `next` branch?

**Comment by calmh** [comment]
Ah.

**Comment by calmh** [comment]
Yep, that solves it by disabling blink. It would still make sense, I think, to start the blink cycle in the "on" state rather than the "off" state, making this a non-issue even with a blinking cursor.

**Comment by carloscabanero** [comment]
Got it now, weird that hterm doesn't have that. Will try to fix before final release of this version ;)

**Comment by carloscabanero** [comment]
Fixed on new version. :)
