### ISSUE TITLE
No visual feedback on "Copy Public Key" button

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#221]
A very minor UI bug: for the "Copy Public Key" and "Copy Private Key" buttons in the "Key Info" section of each key, there is no visual feedback on tapping the button, even though it does in fact work to copy the key. There *is* visual feedback on a slightly longer tap and hold, but I've been confused by the button looking like it wasn't working for short taps.

**Comment by carloscabanero** [comment]
Agreed, this would be nice to have.

**Comment by yury** [comment]
Wow, 5 years!

https://user-images.githubusercontent.com/5250/154645849-13b8f497-f6a8-4207-bc45-4ba930af3959.MOV

Closing.
