### ISSUE TITLE
Feature request: export COLORFGBG

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#222]
I've been playing around with switching between light and dark color schemes, and I've set up vim on the server to react to the COLORFGBG environment variable to set up colors. On iTerm on the Mac, this variable is set and I can easily configure SSH to export it to the server.

I'm assuming Blink is aware of its color scheme as well, so I was wondering if it might be possible to add an option to forward that variable to the server through COLORFGBG as well (assuming the server has been configured to receive environment variables of course)

This might be related to #204

**Comment by carloscabanero** [comment]
It is, and it should be a must.

**Comment by yury** [comment]
As far as I understand `COLORFGBG` is old way to detect colors. Modern terminals allow to query colors with OSC 10/11 (foreground/background). NeoVim seems to use it.
I have added support for reading colors in blink.  Will be in next release.
One step further for dynamic themes.

**Comment by goerz** [comment]
Does that work inside tmux?

**Comment by yury** [comment]
Yep, it does. You just need to wrap them in tmux prefix (`\x1bPtmux;\x1b`) and suffix (`\x1b\\`).
So

```sh
printf '\x1b]11;?\x07'
```

becomes

```sh
printf '\x1bPtmux;\x1b\x1b]11;?\x07\x1b\\'
```

**Comment by carloscabanero** [comment]
We already have the OSC 11, https://unix.stackexchange.com/a/245568. There does not seem to be a standard way to do this and basically apps choose one or another depending on what is available. So closing here as I do not think we may implement COLORFGBG if the other one is valid.
