### ISSUE TITLE
No onscreeen keyboard after unlocking with fingerprint

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#224]
When starting Blink (beta version) when it is not already active in memory and unlocking it by fingerprint, the resulting screen looks like in the following screenshot:

![img_0069](https://cloud.githubusercontent.com/assets/112306/21657646/3b5f3e6c-d291-11e6-85d7-b9624e284933.PNG)

That is, the onscreen keyboard is missing, making the app is inoperable in this state. The problem is fixed by either closing and re-opening Blink, or by rotating the iPad to change the screen orientation.

**Comment by Harwood** [comment]
I've seen the same behavior on both my iPhone 6s Plus with fingerprint unlock and my iPad 2 with keypad lock. 

Tapping above the keyboard to close it and tapping a second time to reopen the keyboard also works as a fix.

**Comment by carloscabanero** [comment]
Confirmed that it is fixed on Yury's branch. Will be up on next raw.

**Comment by carloscabanero** [comment]
This should now be fixed on v4.021. Let us know if there is still any weird behaviour, and otherwise we will keep it for the next release.

**Comment by goerz** [comment]
Everything is working fine now in the latest beta, as far as I can tell

**Comment by carloscabanero** [comment]
Yup, closing here.
