### ISSUE TITLE
CLI is case sensitive

### ISSUE THREAD

**Issue by cgull** [blinksh/blink#225]
`help` is valid but `HELP` is not.

This is a minor issue though.  Possibly more trouble than it's worth, especially if i18n.

**Comment by yury** [comment]
I think CLI should be case sensitive like any other cli (non windows)

**Comment by carloscabanero** [comment]
Yup, at least for now I think we will leave it as is. I will kill linenoise in favour of something that actually works, hopefully mid-term. Closing here :)
