### ISSUE TITLE
Shortcut for Paste disappeared

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#229]
There used to be a shortcut ctrl+v to paste (see #52). This shortcut seems to have disappeared in the move of the shortcut prefix from ctrl to cmd, so there's no way to paste by keyboard shortcut at the moment (I frequently paste passwords from 1Password into a sudo prompt).

Since #52 is still open, this might already be on the radar, in which case feel free to close this issue.

**Comment by carloscabanero** [comment]
Thanks again Michael. Will fix before release :)

**Comment by carloscabanero** [comment]
Fixed on v5 too.

**Comment by goerz** [comment]
Was this supposed to be working already in the new version that I just from TestFlight? It doesn't seem like CMD+v or CTRL+v does anything at the moment.

**Comment by carloscabanero** [comment]
Sorry about the delay. You are right, I didn't have my best day when pushing that one.

It will be out tomorrow.
