### ISSUE TITLE
config dialog blocks airplay terminal

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#230]
With the new "AirTerminal" (pretty cool!), it seems that typing "config" on the airplay terminal pops up the configuration dialog on the airplay screen. Since there's no touch on that screen, there's no way to get rid of the dialog again. I would suggest to either ignore the "config" command on an airplay terminal, or to show the resulting dialog on the "main" (iPad) screen.

**Comment by yury** [comment]
@goerz nice catch :)

**Comment by carloscabanero** [comment]
Fixed on v5
