### ISSUE TITLE
Different font size on iPad and connected external display

### ISSUE THREAD

**Issue by BinaryBen** [blinksh/blink#232]
I had a go at connecting up a display and using the ⌘+O to change focus. Working well for the most part, but the font is way to small on the external display and I can't seem to find any way to change it.

If it doesn't already exist, could it be possible to change the font size for both screens independently? This feature looks really promising from a workflow point of view and for showing presentations (showing a non-interactive copy of a shell on a projector for example).

Also, if it was possible to combine this with split screen and browser support, this set up would be really powerful (a combination of up to three terminals/browsers and another app such as Dash in split screen for example)

**Comment by goerz** [comment]
I've had luck with the keyboard shortcut (cmd-shift-=) to increase the font size on the external display.

However, I just noticed that this shortcut does not seem to be mentioned in the documentation or settings, which is probably a UI bug.

**Comment by BinaryBen** [comment]
Ah excellent, I'll give that a go next time the family gives up the TV ;)

Can we please have it then so there is a `⌘+...` shortcut that works on both iPad and external display (preferably the same, just change whichever has focus). I just tested `⌘+⇧+=` on the iPad display without success.

**Comment by yury** [comment]
@BinaryBen actually it works independent now. 

increase: cmd+shift+=
decrease: cmd+-

**Comment by carloscabanero** [comment]
Well, that is a good point, remembering also the external window settings. We will see how often people uses it to consider implementing it at some point.

**Comment by kkk669** [comment]
Every time I open a new tab, I must increase its font size. That is very annoying. Please could you re-consider adding the settings for an external display.

**Comment by mettlerr** [comment]
I second the request to add a feature which lets Blink remember the font size set on the external monitor. I am using the LG UltraFine 4K Display connected to my iPad Pro, and by default the font size is way WAY too small, and I always have to increase it manually everytime I open a new tab or window on the external monitor. Font Size 15 is very good on my iPad, but WAY too small on the LG display, for example...
