### ISSUE TITLE
Edit: Was a Persistent Connections Issue

### ISSUE THREAD

**Issue by BinaryBen** [blinksh/blink#236]
TestFlight Build: v4.024.1 Jan 24

Whenever I need to enter my fingerprint, I need to reconnect to the server. I can set up a persistent session with tmux/et. al., so not a major problem for me - but still a nuisance. Let me know what else you need to know to diagnose what's causing it?

**Comment by carloscabanero** [comment]
Hi Ben! I guess there is nothing with TouchID, and it is just probably iOS locking the application. Does it happen more often than before?

**Comment by keisisqrl** [comment]
On v5.0.1 from the App Store this affects mosh sessions as well. Could there be a way to resume those?

**Comment by BinaryBen** [comment]
Sorry for the delay in replying. As far as I am aware, it happens every time without fail. Haven't had a chance to test the latest update on TestFlight though.

**Comment by BinaryBen** [comment]
I just turned off Touch ID because it was getting frustrating, and the problem persists as you suspected @carloscabanero. Should have tested earlier, but yeh, it has nothing to do with Touch ID. Every time I lock the device or open a different app it disconnects a standard ssh session (haven't tested mosh - but @keisisqrl mentioned it's happening there as well?)

This might need a bug label now? Not sure
