### ISSUE TITLE
F10 collides with text-resizing key with default keymap

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#241]
By default, ⌘1 through ⌘9 produce F1 through F9. The docs suggest that should work for ⌘0 producing F10 too, but in fact, that is masked by another key that resizes text. You can access F10 by changing the keys to something else, like ⇧⌘, but I think the docs shouldn't incorrectly suggest that ⌘0 itself will produce F10, since it won't.

**Comment by carloscabanero** [comment]
Fixed on new version, we will have ⌘= for reset.
