### ISSUE TITLE
Force IPv4 SSH connection when starting Mosh session

### ISSUE THREAD

**Issue by dlundquist** [blinksh/blink#247]
Presently mosh only supports IPv4, so when connecting to a hostname with both A and AAAA DNS records and IPv6 connectivity is available the SSH connection is established over IPv6 and mosh-server reports an invalid IP address: `mosh-server: Bad IP address (2db8::5054:ff:fe1b:e25d)`. This can be avoided by adding `AddressFamily inet` OpenSSH configuration directive. Blink requires equivalent functionality to connect to dual stack hosts.

**Comment by cgull** [comment]
Mosh has supported IPv6 since version 1.2.5, released mid 2015.  Upgrading the mosh install on your server will resolve this problem.

**Comment by dlundquist** [comment]
Ah, thanks for that information. Pulled mosh from Debian Jessie-backports and it works fine.

**Comment by carloscabanero** [comment]
Thanks for jumping in @cgull :)
