### ISSUE TITLE
Forwarding keys

### ISSUE THREAD

**Issue by 0xCMP** [blinksh/blink#248]
I'd love a way to have some keys on my iPad and choose to forward those keys to the server I'm connecting to. That way I can use things like [Bastion Hosts](https://en.m.wikipedia.org/wiki/Bastion_host).

I'd be best if I could simply use `-A` to tell SSH to forward my keys so it's like ssh on *nix systems.

**Comment by yury** [comment]
We have added `ssh-agent` command and `ssh-add`, and `ssh -A` is supported now too.
