### ISSUE TITLE
Support image display (imgcat)

### ISSUE THREAD

**Issue by xinan** [blinksh/blink#249]
iTerm 2 has this feature that supports the display of images:
https://www.iterm2.com/documentation-images.html

I wonder if it is possible to have this on Blink. It would be cool!

**Comment by nrcharles** [comment]
I second this.

**Comment by goerz** [comment]
None of these things work inside a remote tmux session, do they?

**Comment by nrcharles** [comment]
imgcat will work with tmux integration mode.

**Comment by ZenBrayn** [comment]
> imgcat will work with tmux integration mode.

@nrcharles just out of curiosity does this mean you got it working with Blink on iOS (e.g using some remote server with the the iTerm 2 tmux integration tools installed)?

On this kind of set-up, I can see the image fine on my Mac with iTerm 2, but just get a blank line with Blink.  Thanks!

**Comment by yury** [comment]
![image 2018-02-02 16 15 27](https://user-images.githubusercontent.com/5250/35735041-48eac504-0834-11e8-9792-9b31d7c0996d.jpg)

**Comment by carloscabanero** [comment]
This should be already working on v9.308 under ssh!

**Comment by ZenBrayn** [comment]
Great! Thank @carloscabanero and @yury.  I tracked down the hterm-show-file.sh script on GitHub and it's working great in Blink on iOS now.

**Comment by carloscabanero** [comment]
Interesting how we could use this also to transmit files between both machines and visualize them in other apps. I will open another issue for that. Thanks everyone!

**Comment by goerz** [comment]
I'm very impressed that this works out of the box even with tmux!!!

It doesn't seem to work with mosh though (but you write "working under ssh", so you probably know this). Is this a fundamental limitation, or are there plans to extend this to mosh as well?

**Comment by saptarshiguha** [comment]
Unfortunately, i couldn't find the file hterm-show-file.sh . Where is it located?

**Comment by sbromberger** [comment]
Having this work under mosh would be so awesome.

**Comment by subokita** [comment]
This would be great to have, since I've been using Blink as my main shell while working with TensorFlow, the ability to see the image displayed by matplotlib would  make Blink really popular among data scientists / AI / ML engineers.

**Comment by dragon788** [comment]
I just did some testing and the hterm-show-file.sh works extremely well under screen, displaying images that most of the other terminal tools just gave up on, but anything newer than tmux 2.4 breaks that script and most others (though the Python version of imgcat can handle smaller images pretty well even in tmux but it doesn't know how to do things properly for screen).
