### ISSUE TITLE
Secure key exchange methods are not supported

### ISSUE THREAD

**Issue by tstm** [blinksh/blink#25]
With a properly secured openssh daemon I get the following error message (on the server):

fatal: Unable to negotiate a key exchange method [preauth]

On the iPad the error message is just:
DEBUG: Session start failed with code: 18446744073709551611

Either one of these Kex methods should be supported for secure operations:
curve25519-sha256@libssh.org
diffie-hellman-group-exchange-sha256

**Comment by carloscabanero** [comment]
This should be coming on the next test release :)

**Comment by carloscabanero** [comment]
This should be already fixed. We are using diffie-hellman-group-exchange-sha256 from libssh2. Thanks for the report!
