### ISSUE TITLE
Moving from pop over to full screen not resizing.

### ISSUE THREAD

**Issue by MacDragon** [blinksh/blink#250]
Just been using blink ( TestFlight ) alternately as pop over session with safari, and then switching to full screen via home screen, and first time it comes up full screen it still displays terminal as same size as pop over and doesn't resize ( briefly flashes up terminal size same as pop over too ), going back to home screen and entering second time triggers the resize. Running latest iOS beta, so can't verify not related in some way to that.

**Comment by MacDragon** [comment]
Further, the indicator that pops up to show current terminal size seems to be breaking and permenantly displaying after a while if switching in and out.

**Comment by carloscabanero** [comment]
Hi! Thanks for reporting this, I will try to replicate the issue on the first message. About the second, the indicator not disappearing, is that in the last version (5.028)?

**Comment by MacDragon** [comment]
Yes, this is on very latest version too. It does initially disappear as it should, haven't been able to determine exactly when it starts sticking yet.

**Comment by MacDragon** [comment]
Ok, a bit of further experimenting. Using four finger gesture to switch between blink and safari a few times seems to reasonably reliably trigger the sticking size notification.

**Comment by carloscabanero** [comment]
Done
