### ISSUE TITLE
Feature Request: Option to allow storage of key passphrase

### ISSUE THREAD

**Issue by OolonColoophid** [blinksh/blink#254]
Hi there

Unless I'm missing something, it looks as though it isn't possible to store key passphrases. I understand this might be a security measure, but I'd be happy to drop down the security level for a little more convenience.

Cheers

Ian

**Comment by carloscabanero** [comment]
We are working on backend things and it includes this part. We will hopefully have an agent soon :)

**Comment by OolonColoophid** [comment]
Thanks, Carlos.
