### ISSUE TITLE
Smart Keys don't appear when ext.kb is turned on after app launch

### ISSUE THREAD

**Issue by myfi463** [blinksh/blink#255]
- Turn off external bluetooth keyboard
- Launch Blink Shell (v5.28.2 (2) via TestFlight)
- Onscreen keyboard + Smart Keys appear (pre-configured to "Show with external keyboard")
- Turn on external bluetooth keyboard
- Onscreen AND Smart Keys disappear
- Go into config and exit to force Smart Keys to appear

**Comment by carloscabanero** [comment]
This should be easy to fix. Thanks for the heads up!

**Comment by carloscabanero** [comment]
Done!
