### ISSUE TITLE
Leave smart keys always open

### ISSUE THREAD

**Issue by medihack** [blinksh/blink#256]
When smart keys are switched on I think it would be much better if those always stay open. In my opinion it is not very helpful (even annoying) when copy & pasting that it slides out and the whole screen gets shifted.

**Comment by carloscabanero** [comment]
Hi! Thanks for the message. We are currently focused on backend things, and I don't know how easy everything related to copy/paste is (basically the hierarchy of views is what is going on here). Will try to see if we can do a quick fix before revamping the UI.

**Comment by carloscabanero** [comment]
Done in v10.
