### ISSUE TITLE
Color codes mess up font metrics with Roboto Mono

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#257]
This may or may not be related to #128. I have checked, and the issue is exactly the same on the last version I got from HockeyApp, so this has been a problem for some time.

Here are some screenshots to demonstrate the issue. First, just a simple one showing the issue in Roboto Mono:
![00_roboto](https://cloud.githubusercontent.com/assets/97895/24056715/23c6b4f2-0b1b-11e7-8dd3-6945762469fe.png)

When the problem occurs, **the font appears to be rendered wider than expected;** it trails off the screen (as a comparison in Source Code Pro in a moment will show) and the cursor is rendered to the left of the expected place.

To show where the cursor originates when set to Roboto on a new shell:
![01_roboto](https://cloud.githubusercontent.com/assets/97895/24057162/c802813a-0b1c-11e7-86f4-541236ccd4ca.png)

Now, switching to Source Code Pro:
![02_source code pro](https://cloud.githubusercontent.com/assets/97895/24057176/d2439206-0b1c-11e7-9f81-2d5a1e8be379.png)
You can see that the right-hand edge (with the current working directory, `(~)`) is now visible, and the cursor is back in the correct place.

Interestingly, changing to other fonts _and then back to Roboto Mono_ causes the metrics to change (though not rectify). For instance, switching to Fira Code and back:
![03_roboto](https://cloud.githubusercontent.com/assets/97895/24057345/6d664ec2-0b1d-11e7-9c61-592828f72fd6.png)

Here's where it gets weird: if I exit and open a new session, still in Roboto Mono, the issue seems to rectify itself:
![04_roboto](https://cloud.githubusercontent.com/assets/97895/24057426/b54f8f00-0b1d-11e7-8aed-61ddf25475c2.png)
(Note that the missing date is due to my disabling it as shown in a later screenshot; these screenshots are a bit out of order. But the `(~)` is present on the upper line, so you know it is drawing the entire screen width.)

Now it gets _really_ weird: if I force-close Blink and then reconnect to the very same `tmux` session, here's what I see:
![05_roboto](https://cloud.githubusercontent.com/assets/97895/24057581/385964de-0b1e-11e7-97fb-b54dbeb3eeb2.png)
The issue has returned!

Playing around, I discovered the following:
- Changing fonts before changing back to Roboto Mono causes various effects, but none are quite correct.
- Changing color themes restores the _broken_ (too wide) behavior.

Both of these are across all Blink windows. I wondered if this had something to do with my complex prompt:
![06_roboto](https://cloud.githubusercontent.com/assets/97895/24057689/94b94898-0b1e-11e7-9c80-e699353e9a71.png)
![07_roboto](https://cloud.githubusercontent.com/assets/97895/24057693/9d824998-0b1e-11e7-8fb9-1a0b0592b7f5.png)
![08_roboto](https://cloud.githubusercontent.com/assets/97895/24057699/a3bc417e-0b1e-11e7-9f89-1afe30642244.png)

So my prompt does seem to have something to do with it, but it appears to be the ANSI color codes, not the terminal-movement codes to draw the `RPROMPT` on the right. (Note: this prompt is about 15 years old and predates my ability to assume Unicode availability, so it isn't an ideally-written prompt. I've not had time to re-write it into something more modern.)

A final interesting datapoint that may help nail this down: both metrics can be active at once in separate windows. Since I was in a `tmux` session, I opened one:
![09_roboto](https://cloud.githubusercontent.com/assets/97895/24057825/23b042e0-0b1f-11e7-93be-31c3daf18678.png)

and then I opened a new Blink window and connected _to the same session_. Flicking between them, the first was wrong, as above, but the second was right (or nearly so; the slight misalignment of the rightmost characters on the two lines never resolved, and may be a mistake in the actual character glyphs in that font):
![10_roboto](https://cloud.githubusercontent.com/assets/97895/24057844/37ebe110-0b1f-11e7-8314-c765d40395aa.png)

So:
1. Opening a new window fixes the metrics issue _for that window_.
2. Switching fonts _to_ Roboto Mono from another font causes the issue on all windows.
3. Changing color themes causes the issue to return on all windows.
4. Closing the initial window causes the problem to stop until one of the two triggers just mentioned happens, until Blink is force-quit, whereupon it returns.

I hope this is helpful in diagnosing. I'll be happy to send you any diagnostics or screenshots you want.

**Comment by treyharris** [comment]
(Oh, and if you're wondering how I didn't notice this before, it's because I have generally used Source Code Pro. I was just trying the other font options because I didn't like how it looked for one particular type of code I was writing.)

**Comment by carloscabanero** [comment]
They are both related, and they are all related to a problem with "not really monospaced" fonts causing problems on HTerm: zeit/hyper#740. I'm hiring people on the backend side of things, but no one yet on the frontend, so I cannot really prioritise this in any way until we are done with the backend work :(. But if someone is up to the task just let me know, we can definitely do something if the right person comes to us.

**Comment by carloscabanero** [comment]
I'm updating HTerm on the RAW branch, and according to them, the issue might actually be fixed :D

Let me know!

**Comment by amcgregor** [comment]
\o/ I've been having all sorts of trouble getting Monofur Powerline working with powerline symbols and unicode extensions; a particularly hairy issue has been determining if a wide symbol is two or two and a half (not joking) fixed characters wide, such as the "bullet" symbols used in this screenshot:

<img width="484" alt="screen shot 2017-06-08 at 20 23 26" src="https://user-images.githubusercontent.com/76750/26955954-6ad1df26-4c88-11e7-8f62-4db427c0aa9d.png">

This particular issue shows up way more when using Vim, as I use wide Unicode symbols as tab leaders, where the symptom is typically the opposite: the width of the background color rendered is "eaten" and shorter than the line should actually be.  The more visible indentation leaders, the more gets eaten.

Looking forward to the HTerm bump!

**Comment by carloscabanero** [comment]
This should have been fixed in v10. We have made a few changes on our own to HTerm that improve rendering greatly. Please open a new one if you see anything else.

Thanks @treyharris & @amcgregor !!!
