### ISSUE TITLE
keys not working after return from config

### ISSUE THREAD

**Issue by jra** [blinksh/blink#261]
After closing config, only upper and lower case characters, numbers, and control commands work.

Special characters, delete, return, tab, ... do not work.

Restarting the app fixes the keyboard, though going to config and returning to the prompt breaks it again.

Sometimes, after 10s of seconds, the keys will start working again, though not usually.

Hardware: 
iPhone 7
bluetooth Apple keyboard (A1314)

iOS 10.2.1
Blink: v5.028.1. Feb 28 2017

**Comment by carloscabanero** [comment]
This was fixed long ago, I think on 7
