### ISSUE TITLE
Ctrl-m sends unmodified m

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#267]
Perhaps related to #263 but perhaps not: Ctrl-m sends "m".

There's a workaround, in that the return key is _also_ Ctrl-m, but Ctrl-m should work as well. (Ctrl-i works as TAB, for instance, and Ctrl-Spacebar works as Ctrl-@.)

**Comment by carloscabanero** [comment]
hmmmm.... good catch, as I always have Cmd+m I didn't notice this one, it works if you have Ctrl mapped somewhere else though.

**Comment by carloscabanero** [comment]
This seems to be a bug on iOS. Have to test more thoroughly, the shortcut is defined but iOS doesn't capture it as such and only sends the "m" key. If it was a collision with another iOS shortcut, as I originally thought, then the m wouldn't even get sent. Still exists on iOS11 though.

**Comment by satoru-takeuchi** [comment]
I encountered this problem too. 

Just FYI, when I used Termius, an other ssh/mosh client, C-m works file. Unfortunately I don't know how it bypasses the iOS bug which you said. Hmm...

**Comment by carloscabanero** [comment]
It is apparently working on last iOS and last Blink version. Blink is sending 0x0d for Ctrl+m
^M       13 0015 0x0d

@satoru-takeuchi would you mind sending me your keyboard config settings? thanks!

**Comment by satoru-takeuchi** [comment]
> It is apparently working on last iOS and last Blink version. Blink is sending 0x0d for Ctrl+m
> ^M 13 0015 0x0d

Unfortunately it doesn't work for me.

> would you mind sending me your keyboard config settings?

OK, here it is.

```
- HW model MPHH2J/A
- smartkeyboard: JIS Keyboard 
- iOS 11.0.3
- Blink 8.026
- Settings->Keyboards->Hardware Keyboard
   I can toggle the following two modes by the earth button
  - English (United States): U.S.    # I use this mode for Blink
  - Japanese -Kana: U.S

  - Auto-Capitalization: off
  - Auto-Correction: off
  - "." Shortcut: off

  - Caps Lock Switch to/from Latin: off
```

Please let me know if you need more information.

**Comment by carloscabanero** [comment]
Sorry @satoru-takeuchi, I was referring to the Blink Keyboard settings. I'm trying to figure out if due to your configuration there is something colliding with the Ctrl+m shortcut.

**Comment by satoru-takeuchi** [comment]
@carloscabanero Sorry, I misunderstood. I found Ctrl+m doesn’t work if auto-repeat is enabled.

**Comment by carloscabanero** [comment]
Great catch @satoru-takeuchi! Thanks for keeping an eye on it. It is really weird but I could definitely replicate myself. It looks like something weird on iOS. I will review and see what I can do.

**Comment by zevlg** [comment]
Ctrl-m also sends plain m for me.  Logitech slim combo keyboard, auto-repeat enabled.

Cmd-m (with Cmd generating Ctrl) sends ^M

**Comment by yury** [comment]
Still an issue on iOS 12 :(

**Comment by kek** [comment]
Thanks for the workaround @satoru-takeuchi.

I also noticed that pressing caps lock did not enable capital letters inside Blink (however, it turned on caps lock globally, i.e. in other apps). When I turned off auto-repeat in Blink, caps lock started to function as expected. My caps lock is set to the default settings (because of #4).

**Comment by yury** [comment]
@treyharris,
Not yet, it is iOS issue and I can't find workaround for it.

**Comment by yury** [comment]
Beta 5 seems to fix that !

**Comment by kek** [comment]
I don’t experience this problem anymore in iPadOS 13.0 (17A5547d). I don’t need to use the workaround of turning off auto-repeat.

**Comment by satoru-takeuchi** [comment]
I confirmed that this problem disappeared in iOS 13.1.1!
