### ISSUE TITLE
HARD to access blink command list from existing session

### ISSUE THREAD

**Issue by kleynjan** [blinksh/blink#268]
Use case:
* using blink on iOS device without physical keyboard 
* one session, already logged in and running...
now... I know that I can type "help" to get a list of my blink commands.

Only: where do I type "help", given that I have a terminal session going...?
- if I happen to forget that I should use a two-finger tap??? (how the hell should I remember that?)
- and if there's no "cmd" key on the virtual iOS kbd that I can do a cmd-T with...

Suggestions: 
=> show the blink> screen when using a single-finger left-right swipe (when the list with existing sessions is exhausted?) 
=> provide a "cmd" key on the on-screen iOS kbd

Cheers
-Peter

**Comment by carloscabanero** [comment]
Thanks for the suggestions Peter! I think we are gonna be changing Blink so that the terminal behaves more like Quake Terminal, and allows you to run another set of commands on that space, what would fix this problem too.
