### ISSUE TITLE
How does Blink handle UI Resize?

### ISSUE THREAD

**Issue by BinaryBen** [blinksh/blink#27]
Obvious cases being changing from split screen to full screen. But also, what happens when you rotate a device from landscape to portrait and vice versa?

I am wondering if this will affect using tmux or similar and would appreciate some indication from current users if possible.

**Comment by carloscabanero** [comment]
I will make you a video once I'm done with the release, but it works great. I've been working also in a couple methods to change the font size with a pinch. One is more "real time", but not super smooth, the other is smoother but doesn't give you an idea of where things will be positioned.

**Comment by carloscabanero** [comment]
You can test it already yourself ;)

**Comment by BinaryBen** [comment]
Awesome! Where do I grab the beta download?

**Comment by carloscabanero** [comment]
You should be able to access from HockeyApp

**Comment by BinaryBen** [comment]
Odd, not showing up on the apps tab. Will DM you on Twitter.

**Comment by carloscabanero** [comment]
Closing here as it isn't an issue. Reopen if you see any strange behaviour later ;)
