### ISSUE TITLE
h/w keyboard (re)connection doesn't resize terminal

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#270]
An illustration: I begin with my iPad Pro keyboard connected:
![file_000](https://cloud.githubusercontent.com/assets/97895/25720974/d81189f0-30dc-11e7-9794-191417122fcc.png)

I then disconnect the keyboard, causing the soft keyboard to pop up and the terminal to resize:
![file_001](https://cloud.githubusercontent.com/assets/97895/25720992/e3491be4-30dc-11e7-9805-de93b0d59c96.png)

Then I re-connect the keyboard:
![file_002](https://cloud.githubusercontent.com/assets/97895/25721013/f41a00b4-30dc-11e7-91d2-e144cff90292.png)

At this point, this size (leaving room for the now-absent soft keyboard) is frozen unless I switch to another window/shell and back (including by hitting ⌘T then ⌘W). It doesn't resize back to full-screen as it should.

**Comment by bradleyjones** [comment]
also affected by thie seems related to #264 so I left my comments on that issue

**Comment by carloscabanero** [comment]
Fix is coming. Closing here.
