### ISSUE TITLE
iPad Pro keyboard d/c shouldn't resize window immediately

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#271]
Following up from #270: I frequently follow these steps when I want to charge my iPad Pro:
1. Disconnect the Smart Keyboard and fold it back up so it's a cover again
1. Plug in the iPad Pro and turn its screen off

Unfortunately, if I then want to resume later, the window has been resized. So to do this properly I actually need to remember to switch to Home or a different app besides Blink before disconnecting the keyboard.

This is hard to remember every time. So perhaps there could be an option so that keyboard disconnection doesn't resize the window immediately, but instead requires a touch of something (say on the toolbar)? Then I could put my iPad into the charging doc (which requires disconnecting the keyboard) with Blink running, then take it out, reconnect the keyboard and reactivate Blink, and be back to the terminal layout I started with.

**Comment by yury** [comment]
Hi @treyharris
We can't detect kb disconnect. But v12.3 has layout lock feature.
![GitHawk Upload by yury](https://i.imgur.com/aG3VYaI.jpg)

So you can lock you terminal layout (it works per session) and it will not resize.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by treyharris** [comment]
@yury Was there a regression? I can't find the layout icons anymore:

![img_0504](https://user-images.githubusercontent.com/97895/51352541-e5c98680-1a7b-11e9-8cbe-25181eea58d1.jpeg)

Since I didn't use them often, I'm not sure when I lost them. If there's a setting for it, I can't find it....

**Comment by yury** [comment]
@treyharris layout modes and lock icon are in your control panel. (swipe two fingers up).

![3496b09a-2467-48db-81bd-5d90f1bf4835](https://user-images.githubusercontent.com/5250/51368403-4ac6c000-1b00-11e9-899c-1ddfae853141.jpeg)

**Comment by yury** [comment]
I think we can close this. If you don't agree - please reopen.
