### ISSUE TITLE
Key-based authentication no longer works

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#274]
Ever since the TestFlight version expired and I had to revert back to the App store version, key-based authentication no longer works. The relevant lines from `ssh -vvv ...` are:

    SSHSession:DEBUG:Attempting authentication with publickey.
    SSHSession:DEBUG:Could not find public key files.

I verified that the public key as it shows up in the key-config dialogue is still the same as before. I would assume that I can get around this by deleting the key and creating a new one, but I'd hate having to distribute new keys to all my servers.

**Comment by carloscabanero** [comment]
That is really weird, maybe bc they are identified as different apps by the App Store. I'm not sure I can fix that one, but I will push a new TestFlight today as unfortunately the next Blink is still on hold :(

**Comment by goerz** [comment]
Is it not possible to push a new version to TestFlight that's identical to the previous version? Even if you're delayed on a new "real" version, it would still be nice if you could keep the test-version alive.

**Comment by goerz** [comment]
I re-installed the Testflight version, but it didn't fix the problem. Probably, the private key just got corrupted in some weird way. This is not a big deal, I'll just have to create a new keypair. Unless other people are having similar problem, this is probably not a reproducibel bug but a one-time error; feel free to close the issue. I'm not sure there'd be any way to investigate this further.

**Comment by goerz** [comment]
I haven't been able to reproduce any problems since resetting my key and updating to the latest TestFlight version, so I'm just going to close this at this point.
