### ISSUE TITLE
SSH tunnels

### ISSUE THREAD

**Issue by zeeMonkeez** [blinksh/blink#276]
My servers are only accessible through SSH tunnels. I haven't found a way to configure those. Is it possible?

**Comment by natcl** [comment]
Would love this too !

**Comment by awesomedu** [comment]
if u run on the simulator , when u enter the shell activity, u can press "command + , ", the setting activity will turn out . but I find many ways to run the default settings, can't solve the way to ssh with a name & password.  by the way , the password when I typed in ,and turn back the 'add host' activity  , it always show the 'nil' . if u meet these problem , share it ,brother.

**Comment by carloscabanero** [comment]
It has been possible to this for a while, but we are now also offering the -J option. Please checkout #1168

**Comment by natcl** [comment]
Nice ! Does this also work via the config file by using the ProxyJump command ?

**Comment by carloscabanero** [comment]
It should! We still have to add it to the UI though.
