### ISSUE TITLE
Hide keyboard and resize terminal

### ISSUE THREAD

**Issue by scottleibrand** [blinksh/blink#277]
In Termius, I routinely use the "hide keyboard" key to hide the onscreen keyboard and resize the terminal window to use the screen real estate thus freed up to tail logs. It seems that Blink has a hide keyboard key (in landscape mode only) but does not resize the terminal to use the screen space freed up by hiding the keyboard. It would be most excellent if that were possible.

**Comment by amcgregor** [comment]
Possible duplicate, or related to: #264

**Comment by scottleibrand** [comment]
I don't think I'm seeing any of the symptoms of that bug: I have never seen Blink fail to use all the space above the keyboard. This is more of a feature request to make full use of the screen when the keyboard is hidden.

**Comment by amcgregor** [comment]
A hotfix for #264 (ref [this comment](https://github.com/blinksh/blink/issues/264#issuecomment-307232446)) is being prepared.

While from the user perspective this may seem like a "new feature", the ability to hide the keyboard and make use of all available space was previously possible.  The symptom matching the behaviour of sidebars leaving void space behind (the keyboard being a "side bar" at the bottom of the screen, in terms of layout) would leave me curious if this hotfix fixes your issue, too.

Would you be able to test out a development build, once ready?

**Comment by carloscabanero** [comment]
I was thinking the exact same thing. This should actually be fixed with the new version, but please let us know if you where thinking about something else.

**Comment by scottleibrand** [comment]
Ok, I'm happy to test.  Is the new version with that fix going to be ready in the App Store (or via Testflight) soon?  Or would I need to compile it myself with Xcode?

**Comment by carloscabanero** [comment]
On both soon, just pushed to the App Store. Probably TestFlight sooner.

**Comment by scottleibrand** [comment]
Cool.  If you'd like to add me to TestFlight, I'm scottleibrand@gmail.com there.

**Comment by Aktariel** [comment]
I would also be thrilled and willing to help test the beta build as well. I have a 9.7” iPad with an external keyboard and Blink’s resizing/not resizing behavior has been driving me batty.

**Comment by carloscabanero** [comment]
This has already been confirmed to work, and with the issues from TouchID fixed too, we are again on both AppStore and TestFlight queue :)

**Comment by johnutz-self** [comment]
I would be interested in testing this fix as well.

Also I see reference to a blink shell mailing list but I can not find a means to subscribe, could somebody inform me of how I can be added to it or add myself?
Tax!

**Comment by carloscabanero** [comment]
It should already be on TestFlight! :)

Please test it and let me know, we are waiting for approval in the broad channel, so we can wait! Enjoy

**Comment by Aktariel** [comment]
How do I sign up to be a TestFlight channel? I've got a couple of other apps I'm testing through there already, this one would be fabulous!

**Comment by amcgregor** [comment]
I was trying to avoid a me-too posting, but the ball has been set in motion, there.  nyvpr_ng_tbgupnaql_qbg_pbz (rot-13)? @Aktariel Requires the Apple ID-associated e-mail address, I believe.

**Comment by carloscabanero** [comment]
Hey, if you wanna access TestFlight, shoot me an email to cc at blink.sh with your email account and I will set you up. I'm unfortunately super busy these days but already thinking about what's next inside Blink and would love to have you on it ;)

**Comment by carloscabanero** [comment]
This was already fixed on 7, so closing here.
