### ISSUE TITLE
Strange first terminal with red cursor

### ISSUE THREAD

**Issue by jason-green-io** [blinksh/blink#278]
I open up the app and was greeted with this: ![img_0920](https://cloud.githubusercontent.com/assets/2853489/26823297/07d06490-4aa5-11e7-8ac3-816360c6fae7.PNG)

I can create another terminal that has the usual `blink>` prompt, and the strange one stays. Can't interact with it.

**Comment by carloscabanero** [comment]
That is hterm, maybe a hiccup on the JS during initialisation. Does that happen regularly?

**Comment by jason-green-io** [comment]
Once in a while, not sure how to reproduce.

**Comment by carloscabanero** [comment]
this is definitely HTerm booting up. We could improve it by modifying the defaults instead of "applying" them. It is, interestingly, related to #282 .

**Comment by carloscabanero** [comment]
Improved the way hterm loads should have made this disappear.
Closing!
