### ISSUE TITLE
shifted cursor

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#280]
The new TestFlight version introduced a bug for me: As the output of some commands is printed, the cursor in blink shifts down. `ls` does this, but also just typing `mosh` at the Blink command line, see the following screenshot:

![img_0094](https://user-images.githubusercontent.com/112306/27061218-4406d434-4fb0-11e7-83f1-23150237fb58.PNG)

repeating the command adds another line to the shift. `CTRL+L` resets the cursor temporarily.

**Comment by yury** [comment]
Also have this issue on master. (Was thinking it was my issue while I'm upgrading htremjs)

**Comment by carloscabanero** [comment]
I've been using it for a while and I have only experienced a problem with the cursor doubling width, that is also fixed with "zooming in/out". Does that happen everytime or is it after introducing a few commands?

**Comment by goerz** [comment]
It happens every time. However, as @yury pointed out, it is fixed by any kind of change in the display font size (`cmd+=` etc, or pinching).

**Comment by goerz** [comment]
It seems the bug occurs only when the font size is not the default 15px (I'm using 13px). That might be why it slipped under the radar.

**Comment by goerz** [comment]
Actually, scrap that last comment: It does happen even for 15px font size (but just going into Settings fixes it for some reason, temporarily).

**Comment by carloscabanero** [comment]
We are checking a new version, so closing here as it isn’t relevant at the moment.
