### ISSUE TITLE
confusion about font size/zoom level

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#282]
I'm slightly confused about font size in Blink (after hitting `⌘=` as part of investigating #280):

In the "Appearance" settings, I have "Font Size" set to a comfortably small 13px. This is the size of any newly created terminal. I was surprised to find that `cmd+=` changes the font to what looks like 15px. Do I assume correctly that this is the "factory default"? I would find it more intuitive if `⌘=` went to the font size I have in the settings (resetting from any kind of manual pinching or `⌘+`/ `⌘-`).

I was also slightly confused by the terminology used in the help-overlay (press and hold 
`⌘`) where the description uses the word "zoom". I think it would be better if "Zoom in" 
→ "Increase Font Size", "Zoom out" → "Decrease Font Size", and "Reset Zoom" → "Reset Font Size".

Hypothetically, Blink *could* also have a "zoom" independent of font size, which would presumably be continuous (not in px steps) and also affect graphics that Blink could show in the future, cf. feature request #249. Taking this tangent a bit further, it would would actually make sense to me if pinching was zoom, while the keyboard shortcuts `⌘+`, `⌘-`, and `⌘=` modify the font size (incidentally, these shortcuts are missing in the output of `help`). In any case, I don't think Blink currently has that kind of zoom, so the help text should be adjusted.

It might be nice if the current font size was shown alongside (under) the terminal size in the overlay that pops up when switching terminals or resizing.

**Comment by Riprock** [comment]
I would definitely find ⌘= bringing me back to the font size in config useful. I work with a big font size but often make it smaller to fit more columns in for `ls`, `ps`, `top` &c.

**Comment by ickc** [comment]
I found this behaves differently than in many macOS applications: often the time, `⌘-`/`⌘=` decrease/increase the size, and `⌘0` bring it to original.

**Comment by dmitryzykov** [comment]
@yury 
Up for this issue.

**Comment by yury** [comment]
@carloscabanero 
Since we can remap shortcuts now, can we make it as mac os x default?
