### ISSUE TITLE
Integrate grabbing remote clipboard

### ISSUE THREAD

**Issue by samdmarshall** [blinksh/blink#284]
Hi, first off i want to say that this is a fantastic app. So far the only thing i feel like I am missing compared to working onOS X or linux is that there isn't any way to fetch the contents of a remote clipboard. While there is copy+paste functionality built into this app, that doesn't quite bridge the gap when you need to copy a file or large amount of text that would be hard to select. For this purpose I use [`clipper`](https://github.com/wincent/clipper) to move clipboard contents between my local and remote machines. Do you think you would be able to integrate some adaptation of this tool into blink so that i could easily grab a remote file and move it into a local editor on my iPad and vice-versa?

**Comment by yury** [comment]
Actually with ssh it should work...

**Comment by andrewarrow** [comment]
I find myself often doing this to get around this:

1. cp textfile to /www/html
2. From safari goto https://mydomain/textfile
3. Drag and select the entire thing and click copy

But I would love a 1 command line option like:

1. Addtoclip textfile

And boom, the whole text file is just magically on your clipboard ready for pasting.

**Comment by yury** [comment]
Hi @andrewarrow.

What is your server? Ubuntu or mac os x? or smth else?

**Comment by andrewarrow** [comment]
I mosh from this ipad to a ubuntu linux box.

**Comment by yury** [comment]
Bad news:
Sorry, mosh doesn't support remote clipboard sequencies yet. 

Good news:
In latest TF version you can run following command:
`ssh host cat path/to/file | pbcopy`

**Comment by yury** [comment]
Side note:
Under ssh with tmux, copy should work with ssh clipboard sequencies.
