### ISSUE TITLE
[feature req] tab-complete for registered hosts

### ISSUE THREAD

**Issue by samdmarshall** [blinksh/blink#285]
It would be nice to have tab completion for the names of hosts that have been registered with blink. I think this would be a minor enhancement that would the initial experience a lot more friendly.

**Comment by ThomasHerrlin** [comment]
This seems to be related to and possibly a subset of feature request #43 "Command completion"

**Comment by carloscabanero** [comment]
We use line noise and it only allows us to do that much. But I'm planning a simple new interface, more like the Quake Console if you guys remember, that could be called from anywhere too.

**Comment by carloscabanero** [comment]
v10!

We will take this further in a future version though.
