### ISSUE TITLE
Import of SSH from clipboard crashes app.

### ISSUE THREAD

**Issue by arronmabrey** [blinksh/blink#29]
@carloscabanero 

Original twitter conversation 
https://twitter.com/arronmabrey/status/743090112314118144

Here is the header of my private key
```
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: DES-EDE3-CBC,4F7143239EF7C02F
```

When I try to import the key into blink the app crashes. Running on an iPad Pro. iOS 9.3.x

**Comment by arronmabrey** [comment]
I had originally used the "copy my key" feature in Prompt, and that crashed the blink app. I thought maybe it was some extra junk in the clipboard from Prompt. But sadly I tried copying via another way that I was more confident in, and it still crashed blink.

**Comment by carloscabanero** [comment]
This should now be fixed on 0.716!

OpenSSL_add_all_algorithms isn't a deprecated function, whatever they say in the docs ;)

**Comment by arronmabrey** [comment]
Thanks!!

**Comment by carloscabanero** [comment]
Hi Arron! Can yo please confirm it works now in your scenario too? Thanks!

**Comment by arronmabrey** [comment]
@carloscabanero Yes it's working!

**Comment by arronmabrey** [comment]
@carloscabanero however now that I have finally started a mosh session in blink. The arrow keys are not working. I tried going into the `config` to check the "keys" setup, and maybe adjust the mappings but the "keys" portion of `config` doesn't seem to work either.

**Comment by arronmabrey** [comment]
@carloscabanero should I open another issue for that?

**Comment by carloscabanero** [comment]
The "keys" setup not working is a known issue, it is basically disabled until we finish that part (probably during next week to complete everything). 

The arrow keys are a different story, strange that they do not work. Do you have any special setup or require a special mapping on them? Do they work while on Blink Shell?
