### ISSUE TITLE
[feature request] Ctrl + R - search history

### ISSUE THREAD

**Issue by bmillington** [blinksh/blink#290]
Is it possible to implement Ctrl + R searching of history? 

I really appreciate what you guys are trying to achieve with this, I think for people who work on a large amount of servers this is SO much better than other options out there! But I rarely remember hostnames or IP's due to the sheer number of them so being able to search would be brilliant.

**Comment by goerz** [comment]
See #43

**Comment by yury** [comment]
works in v11.0
