### ISSUE TITLE
Emojis disappear and confuse the cursor position

### ISSUE THREAD

**Issue by fffergal** [blinksh/blink#292]
Symptoms are best case Emoji don't appear at all (0 width), worst case the cursor starts getting confused because a process (vim) is handling emoji widths and mosh isn't.

This is a long running thing on mosh, see https://github.com/mobile-shell/mosh/issues/234 and https://github.com/mobile-shell/mosh/issues/612 and https://github.com/mobile-shell/mosh/issues/361. It sounds like it is caused by the client having a version of libc which doesn't know the width of emojis. The problem is really bigger than that, it should be expected that different machines have different definitions and rendering still works, but it's not easy because nobody knows what other machines are using. Mosh on the server sending the data might use one defintion, the running process on the server might be handling different width characters in its own way, and mosh on the client could have separate definition again.

That said, maybe Blink can link against an up to date libc and it will work in the common cases again? That said I have memories of it being really hard to use a separate libc to the system because everything uses it… Maybe just use a different wcwidth implementation?

Also maybe libc is up to date enough and this is caused by something completely different!

**Comment by carloscabanero** [comment]
Emojis were working properly before. Behaviour now is weird, even in ssh or in the normal term.

**Comment by carloscabanero** [comment]
V10!
