### ISSUE TITLE
mosh-server needs UTF-8 native locale to run (SSH works fine)

### ISSUE THREAD

**Issue by QasimK** [blinksh/blink#294]
I can SSH into my server just fine, but when I attempt to mosh in I get the following error:

![img_0001](https://user-images.githubusercontent.com/10064144/27549827-42872db2-5a95-11e7-9914-441191d1ba69.PNG)

The output of `locale -a` is:

```
c
en_GB.utf8
POSIX
```

There doesn't seem to be a way to configure Blink's locale to something other than en_US.utf8, which I assume would be the solution.

**Comment by carloscabanero** [comment]
Mosh requires to have both UTF of local and remote. Blink supports it by default, so you only have to configure your remote to use UTF too ;)

**Comment by carlosvigil** [comment]
I got this error as well and my locales are set to UTF-8

**Comment by QasimK** [comment]
@carloscabanero The server locale is set to UTF as indicated by the output of `locale -a`. Do you have another reason to think that the server does not support UTF, or a way to confirm this?

**Comment by QasimK** [comment]
@carloscabanero There is at least one other person encountering this error. Do you believe this is a duplicate issue, or do you have a way for me to confirm that Blink is at fault here?

**Comment by QasimK** [comment]
@carloscabanero After further investigation I managed to fix the problem but I believe Blink could be adjusted to work more seamlessly.

In this case I enabled `en_US.UTF-8 UTF-8` in `/etc/locale.gen` - however I already had `en_GB.UTF-8 UTF-8` enabled. It appears that Blink forces the use of en_US.

Am I perhaps just missing a configuration setting in Blink?

**Comment by pjgoodall** [comment]
Does not work connecting to an ubuntu 22.04 cloud image. 
If I have to configure it - I would like clear instructions. I do not normally have to touch this configuration.

without much understanding I ran `sudo locale-gen en_US.UTF-8` and then had successful login. 
I'm not sure what would happen with any other locale.

**Comment by pjgoodall** [comment]
Does not work connecting to an ubuntu 22.04 cloud image. 
If I have to configure it - I would like clear instructions. I do not normally have to touch this configuration.

**Comment by carloscabanero** [comment]
Hi! Please open a new support request with the specific issues you are having. This issue is closed. 

(What you did in there is generate a locale, which probably means your Ubuntu is in a different base language than English or very barebones.)
