### ISSUE TITLE
No shifted äöü Umlauts on German iPad keyboard without 'Smart Keys'

### ISSUE THREAD

**Issue by lispm** [blinksh/blink#296]
I have new iPad Pro 12.9 with Apple's Smart Keyboard, German version. Release iOS, no beta iOS.

The smart keyboard has ÄÖÜ umlaut keys. 

With the  'smart keys / show with external keyboard'  option on it works as expected:

* small äöü by default and large ÄÖÜ with shift key pressed

When the 'smart keys / show with external keyboard' option is off, then it displays only the small äöü, even with the shift key pressed.

I would expect that small and large umlauts work for both options. Right?

**Comment by carloscabanero** [comment]
Fixed on v7!

This had to do with Auto Repeat capturing the accented key, so unfortunately we had to make auto repeat an option.

Test it and let me know :)

**Comment by lispm** [comment]
Blink: v7.0.1. Jul 11 2017
Sorry, I don't see any changes. ÄÖÜ uppercase umlauts only work with Smart Keys, show with external keyboard ON.

**Comment by yury** [comment]
ref #467
