### ISSUE TITLE
blink resolves foo.local addresses for ssh but not for mosh

### ISSUE THREAD

**Issue by zxaos** [blinksh/blink#297]
Set up a host in blink with a `foo.local` hostname. Let's call it ExampleL. Connection with ssh works, and manually connecting with mosh to user@foo.local works, but mosh-ing to the alias does not:

```
blink> ssh ExampleL
Connected to [IPv6 address]
$
```

```
blink> mosh ExampleL
zsh:1: command not found: foo.local
Did not find remote IP address
blink>
```

```
blink> mosh someUser@foo.local
Password:
$
```

**Comment by docwhat** [comment]
Try appending a `.` to the DNS name, to prevent recursive lookup.

e.g. `mosh docwhat@nitrogen.local.` and `ssh docwhat@nitrogen.local.`

Works for me.

**Comment by awesomedu** [comment]
brother , how to run a command like "ssh to tangtang@192.168.0.104", if I have a host Ip ,name , password ,how to run a single command to ssh to remote server, many thanks

**Comment by carloscabanero** [comment]
You can run a remote command with just 

ssh tangtang@192.168.0.104 -- <command>

**Comment by carloscabanero** [comment]
@zxaos Let us know if that worked and feel free to close here. It is connecting as it is sending you a message from zsh.

**Comment by zxaos** [comment]
Unfortunately that didn't help.

After changing the host to `foo.local.`

```
blink> ssh ExampleL
Connected to [IPv6 address]
$
```

```
blink> mosh ExampleL
zsh:1: command not found: foo.local.
Did not find remote IP address
blink>
```

```
blink> mosh someUser@foo.local.
Password:
$
```

**Comment by carloscabanero** [comment]
I think you just have it misconfigured. On the Host configuration, under Mosh section, make sure the "Server" part is empty. That is the path to the mosh-server command. The problem is that you probably dropped foo.local there and then it is trying to run it as a command, that's why you receive "zsh command not found". I have to rename that. Sorry for the inconvenience.

**Comment by zxaos** [comment]
Ohh... I wondered why I was being asked to specify that twice. 😅 

Thanks! That fixed it!
