### ISSUE TITLE
Lots of empty tabs created in background

### ISSUE THREAD

**Issue by jsravn** [blinksh/blink#299]
I'm not quite sure how to reproduce this yet. But occasionally when alt-tabbing between blink and another window, like safari, I'll go back to blink and there will be many new empty shell windows created. Not quite sure what causes this though, because I don't think I'm pushing cmd-t that much.

**Comment by carloscabanero** [comment]
Could it be using the two finger tap or not touching the screen at all?

**Comment by samdmarshall** [comment]
I've had this happen a bunch, all without touching the screen.

**Comment by goerz** [comment]
I've also had this happen, but only on rare occasions.

**Comment by kimolas** [comment]
I could be totally wrong, but it may have to do with iOS not focusing the switched-to app after using Blink. I've had Blink create extra tabs when I tab-switch from it to Safari and use CMD+T to create a new tab in Safari. Sometimes, creating a new Safari tab will fail because the keyboard focus is still on Blink.

**Comment by hkjn** [comment]
I also experience this, several times per day.

I am not touching the screen, but rather using CMD+TAB to switch back to Blink, causing many dozens of new windows to appear, with the only fix to kill Blink and start it again.

**Comment by carloscabanero** [comment]
I experienced this within emacs, as it is sending multiple “transpose” (Ctrl+t). I will do a code review on how we handle first responder flow.

**Comment by hkjn** [comment]
If the root cause is difficult to find / fix, maybe a workaround would be to rate-limit creation of new Blink tabs? I don't think anyone intentionally wants to create more than one new tab per second..

**Comment by bergie** [comment]
I'm seeing this happen in two ways:

* When tabbing back to Blink, a new tab is created, but screen is shown kind of "half-way" between the two tabs (original, in-use tab shown in about 30% of screen on left, the new unwanted tab using the rest of the space)
* More rarely, when tabbing back to Blink, tons of new tabs are created. Sometimes it doesn't kill the app and I can close the tabs one-by-one, and sometimes the app becomes unresponsive as others have reported

iPad Pro 10" with smart keyboard and iOS 11.

**Comment by yury** [comment]
@bergie thanks for detailed feedback. 

I think, I fixed multiple empty tabs and "half-way" terms. It turns out, that iOS still sends keyboard actions to the app even if it is inactive. That is why we got empty tabs and broken transitions.
