### ISSUE TITLE
Apple keyboard bar hides bottom of terminal

### ISSUE THREAD

**Issue by rekendahl** [blinksh/blink#3]
Blink will, most of the time, not resize the terminal window to take into account the apple keyboard bar. Since the TMUX status bar and even command line is down there it gets impossible to see what's typed!

Here is an example image:
![img_0022](https://cloud.githubusercontent.com/assets/1612072/14187508/678292bc-f751-11e5-8d20-abf736a5156a.PNG)

Compare to iTerm:

![screen shot 2016-03-31 at 2 42 31 pm](https://cloud.githubusercontent.com/assets/1612072/14187515/789f4040-f751-11e5-85c8-109e50a4188e.png)

**Comment by carloscabanero** [comment]
We will probably remove that bar, but even then, we have to ensure it is displayed properly. It will also solve current problems with SplitView.

**Comment by rekendahl** [comment]
It also happens when changing window inside TMUX (which is weird to me). I have ALT+P/N to switch TMUX panes and the first pane seems always correct but once I go into another TMUX pane (i.e redraw whole screen) then it seems off and not stable to get back

**Comment by rekendahl** [comment]
With the latest release this works somewhat better. On my first TMUX window it looks correct (look at bottom TMUX bar):

![image](https://cloud.githubusercontent.com/assets/1612072/14268486/7e0e74dc-faa9-11e5-87bd-cf0334aaaa72.png)

When I switch to the 2nd window the bar (and I think) the bottom line if the terminal are out side of screen area:

![image](https://cloud.githubusercontent.com/assets/1612072/14268503/a702ad2c-faa9-11e5-9a18-5b693de39feb.png)

When I switch back to the first window it resizes correctly. This behavior is consistent. Works for first window in TMUX and is off for all other Windows. Dismissing the bar etc seem to have no effect

**Comment by carloscabanero** [comment]
Fixed in next release
