### ISSUE TITLE
Bluetooth keyboard doesn't work on first try

### ISSUE THREAD

**Issue by Riprock** [blinksh/blink#30]
When switching to Blink after using the Bluetooth keyboard in another app, it doesn't work. I've found you can use a Bluetooth keyboard by bringing up the soft keyboard while in the app (by turning Bluetooth off and tapping a few times) then reconnecting the Bluetooth keyboard whilst still in app.

Update: tapping somewhere near the top of the screen actually makes the Bluetooth keyboard work too! Don't have to disconnect. Tapping anywhere else doesn't work.

**Comment by carloscabanero** [comment]
This one is driving everyone crazy. Apologies for that. It is actually a problem with the focus on the terminal. I got so used to tapping the terminal that I didn't really realise this was a problem. I'm working on it to communicate better when Blink doesn't have the focus, and also being more friendly on obtaining it after swipes, etc... so we reduce the number of taps. 

Nothing to do with Bluetooth keyboard really, sorry again. 

Thanks for the report!

**Comment by carloscabanero** [comment]
This should now be fixed and be a lot better. Please let me know.
