### ISSUE TITLE
Caps lock as both ctrl and esc

### ISSUE THREAD

**Issue by basepi** [blinksh/blink#301]
First of all, this project is amazing! In seconds it solved almost every issue I was having with Prompt 2. I love it!

I was especially pleased to find out that I could map caps lock to ctrl, and also use it as an escape key. However, this feature is not quite acting like I expect it to.

It seems to send a `^[` on downpress, whether I use it as ctrl or not. This messes up some things like tmux interactions. If I try to do `^b` to trigger tmux commands, it sends `^[^b`, which appears to confuse tmux and it doesn't treat it as a prefix. (I've verified these results with `showkey -a`)

Is there any way we could get the `^[` on key release instead? And only if the key was not used in conjunction with any other key? This is how I have caps lock set up on my mac with karabiner elements -- short press alone sends escape on key release. Long press or press in conjunction with any other key sends ctrl.

Runnin version 5.028 from the app store (latest as of the day this issue was posted) on the public iOS 11 beta, using the smart keyboard from the logitech slim combo.

Keep me posted if you need any more information.

**Comment by mvandermeulen** [comment]
+1 Also would love to see this functionality.

**Comment by dseuss** [comment]
Is there any progress on this point?

**Comment by listcrawler** [comment]
Bumping with another request to get this working.

**Comment by dseuss** [comment]
It used to kind of work in older versions of Blink, but the most recent version broke it. Is there any plan on reviving this?

**Comment by yury** [comment]
Next version will allow it.
