### ISSUE TITLE
Disable smart quotes, emdashes, etc.

### ISSUE THREAD

**Issue by docwhat** [blinksh/blink#302]
Whenever I type via my “smart keyboard” (the official apple keyboard case) on my iPad Pro 12.9” (2nd gen), I get:

- “smart” open and closed double quotes.
- “smart” open and closed single quotes.
- double-dash becomes an emdash `–`

I suspect this is an option in the settings of iOS someplace, but I can’t find it.  Either way, it seems like blink should never default to the smart quote stuff being turned on.

PS: I’m using iOS 11 beta, which I _hope_ isn’t the cause of the problem.

**Comment by docwhat** [comment]
Hrm... this may be an iOS 11 thing: https://stackoverflow.com/questions/44932863/ios-11-disable-smart-quotes

**Comment by docwhat** [comment]
So after some experimentation, it looks like the option is "Smart Punctuation" under "General" in the system preferences.

I would prefer to leave it on as it makes pretty typography most of the time; I'll turn it off for the moment.

**Comment by yury** [comment]
Sure, it is new iOS 11 feature. Confirm.

We can't fix it in release, since API to disable "smart dashes" in app is only available in new iOS (beta).

**Comment by docwhat** [comment]
But when iOS 11 is released you can?

**Comment by yury** [comment]
Sure

**Comment by blink-currents** [comment]
This has been fixed on latest Blink, and we are awaiting approval for iOS 11 release. Hope it happens at some point today / tomorrow latest.

**Comment by carloscabanero** [comment]
Closing here
