### ISSUE TITLE
How to run the settings("command + ',' ") in shell?

### ISSUE THREAD

**Issue by awesomedu** [blinksh/blink#308]
find too much ways to run the settings( contains the host , ip , password) ,but can't solve the way to handle it ,many thanks for ur response.

**Comment by awesomedu** [comment]
I add a host , then filled the "HostName , User Password", then save it ,  how can run this settings in the shell?

**Comment by goerz** [comment]
I'm not sure I comprehend your comments, but if you're asking how to obtain the settings dialogue by typing a command instead of using the shortcut `cmd + ,`, that command would be `config`.

**Comment by awesomedu** [comment]
hey, brother goerz, glad to see ur reply. I'm an Asian,my english is not very good,may be my question is not described clearly.
1.I want to ssh via the name & password.
2.so ,I enter the 'command + ',' to open the setting's activity, after I configure the settings (include the host , host name , ip , password ), then I save it.
3. after I do all these above , I restart the simulator to run the project , it also shows the 'blink> ' on the simulator screen, should I Manually to type some ssh command to run the settings? does it  have the function that automatically run those settings above?

**Comment by goerz** [comment]
Yes, you have to run the same `ssh` command that you would use on any computer, that is, `ssh user@host`, or `mosh user@host` if you have mosh installed.

**Comment by carlosvigil** [comment]
To run your config:
`ssh "host"`
`mosh "host"`

It's written in lightly under "Host" setting
