### ISSUE TITLE
How to use custom ssh port? it always go to 22

### ISSUE THREAD

**Issue by yury** [blinksh/blink#31]
![img_0066](https://cloud.githubusercontent.com/assets/5250/16109943/6ef857dc-33bc-11e6-9caa-13e686fe0c2b.PNG)

**Comment by carloscabanero** [comment]
Hi Yuri! I had to disable custom ssh parameters, but if you download v.0.716, you will be able to do it with -P and -I for identity. Please reopen if you consider it isn't fixed. :)

**Comment by yury** [comment]
Yep, it works now. Thanks
