### ISSUE TITLE
Feature Request: Release VimIOS as partner app

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#315]
If #281 is ever merged into the Blink app, it would be beyond awesome if a version of VimIOS that's in the same app group as Blink could be released onto the app store ("Vim for Blink"). It wouldn't have to be much beyond the current most advanced forks of VimIOS, although I suppose there could be some enhancements integrating it even more tightly with Blink ("open in place"), and maybe with the new capabilities of iOS 11 (Files app?).

I would be more than happy to spend another $20, just to get around the 7-day restriction of sideloading without a paid developer account (and $99 per year for the dev account just to get vim seems steep).

See https://github.com/larki/VimIOS/issues/7

**Comment by goerz** [comment]
Oh, and mapping Caps-Lock to Escape (https://github.com/larki/VimIOS/issues/6) would be an *extremely* welcome enhancement

**Comment by carloscabanero** [comment]
I have no problems releasing this as a separate app ourselves, free, and even giving some resources from our Continuous Integration and Deployment servers to continue improving it.

But I need someone to maintain Vim @holzschu?

**Comment by goerz** [comment]
With the way iOS11, ios_system, and iVim have evolved, I think this problem is completely solved at this point, and the issue should be closed.

**Comment by yury** [comment]
Here an [example](https://youtu.be/v-DEEJTCbaM) for readers.

**Comment by holzschu** [comment]
This is great, bit my version says: "open: command not found".

**Comment by yury** [comment]
We came up with this idea couple hours hours from now :)

So it will be in next release ;) I hope, today

**Comment by goerz** [comment]
`open` is exactly the command I was hoping for, for consistency with MacOS. This is great!
