### ISSUE TITLE
Software keyboard intermittently displays excess margin on bottom

### ISSUE THREAD

**Issue by kimolas** [blinksh/blink#316]
Version 7.0 just pushed to the App Store has a new bug with the software keyboard. If a new tab is opened, the virtual keyboard will display a margin on the bottom, both in landscape and in portrait. 

Using iPad Pro 10.5". 

![img_0068](https://user-images.githubusercontent.com/4828831/28193944-d30c4288-680e-11e7-9ece-b3270bc02986.PNG)
![img_0067](https://user-images.githubusercontent.com/4828831/28193945-d31adaf0-680e-11e7-86ec-4efe939e1af9.PNG)

**Comment by carloscabanero** [comment]
Thanks for opening it. This is on iOS11 unfortunately. It does it intermmitently on other apps too. Will try to figure out what is going on in case we have to do anything from our side.

**Comment by kimolas** [comment]
@carloscabanero Ah, I've been using my Smart Keyboard mostly so I hadn't noticed. Sounds like something that Apple will take care of, then, hopefully. Thanks!

**Comment by carloscabanero** [comment]
This is fixed on iOS11, but sometimes I still see it in other apps. Looks like Apple might still have some work to do ;)
