### ISSUE TITLE
Blink isn't in my country

### ISSUE THREAD

**Issue by RoXuS** [blinksh/blink#320]
I wanted to buy Blink, but it seems that it is not available in my country (france), could you do something about it? I can build it myself but I would like to buy it.

Thx

**Comment by cijianzy** [comment]
You can download the source code and build by yourself.

**Comment by goerz** [comment]
I don't see any reason why Blink shouldn't be in every country's app store. Compiling apps yourself is not a realistic option unless one has a paid developer account (apps stop working after 7 days).

**Comment by carloscabanero** [comment]
Created #355 for that. We need to fulfill a document for the french crypto regulations. Unfortunately the link to download the document seems to not work :S https://www.ssi.gouv.fr/en/regulation/cryptology/how-to-submit-an-application/

Any help on translating, etc... would be appreciated.

**Comment by jibaku** [comment]
The download link is working for me https://www.ssi.gouv.fr/uploads/2014/11/crypto_declaration-demande_autorisation_operations_annexe1_v2.pdf but it seems you need to open the file with the official acrobat reader.

**Comment by carloscabanero** [comment]
For the record in case someone has the issue (maybe from a different project). The webpage doesn’t work in any reader or browser or anything. Introduce the name on Google and downloading the latest version did the trick for us. Will keep open until they get back to us just to document the full process.

**Comment by carloscabanero** [comment]
This was done a while ago :)
