### ISSUE TITLE
Keyboard stops working after openning IOS Apps in Airplay mode

### ISSUE THREAD

**Issue by carlos-solis** [blinksh/blink#324]
While I am in Airplay mode and open other IOS apps, the keyboard in the airplay monitor stops responding. The blink screen in the Ipad screen Workflow fine.

**Comment by yury** [comment]
Will look at this

**Comment by yury** [comment]
Tested today a lot. Do you have multiple tabs on airplay screen? Did you tried cmd+o and cmd+[/]?

Did'n noticed anything strange....

**Comment by carlos-solis** [comment]
The keyboard does not respond to any command. I noticed that this happens after being moving around other apps with split view.

**Comment by carloscabanero** [comment]
This should have been fixed on 10. Please reopen if you are still seeing it!
