### ISSUE TITLE
Keyboard settings crashes

### ISSUE THREAD

**Issue by jgstroud** [blinksh/blink#326]
On public beta 3, blink crashes when you open the Keyboard settings menu.  This seems to be introduced by commit 9ce4c2e895aad227f0a27c1a6be30ff2081e9de7.  Rolling back fixes the issue.

**Comment by javanut13** [comment]
This is caused by a missing `break` statement on line [154](https://github.com/blinksh/blink/blob/9ce4c2e895aad227f0a27c1a6be30ff2081e9de7/Settings/ViewControllers/BKKeyboard/BKKeyboardViewController.m#L154) of `BKKeyboardViewController.m`. I came across this and fixed it in my PR #312.

**Comment by jgstroud** [comment]
That fixes it.  Thanks.

**Comment by carloscabanero** [comment]
Fixed
