### ISSUE TITLE
Blink create new tabs (ocassionally)

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#327]
When I do switch to another application (ipad pro with smart keyboard), blink generates multiple tabs and becoming non-responsive:

![screenshot](https://dl.dropbox.com/s/s7b1xcjvr5pf6eu/Photo%2022-07-2017%2C%2014%2041%2059.png)

**Comment by goerz** [comment]
Duplicate of #299

**Comment by carloscabanero** [comment]
Closing here, tracking the other one.
