### ISSUE TITLE
iPad only mosh issue with saved host: command not found

### ISSUE THREAD

**Issue by joech4n** [blinksh/blink#328]
I have a host 'a' saved for SSH and Mosh. iCloud sync is enabled. Both protocols work fine on iPhone. On iPad, however:

- Mosh connections fail but SSH works
- Using Mosh with FQDN and IP both work, so it seems to be an issue with the hostname configured in Blink on iPad only?

Example output on iPad :

    blink> ssh a
    Connected to 1.2.3.4
    Last login: Mon Jul 24 03:33:57 2017 from somewhere.domain
    [user@domain ~]$ exit 
    logout
    
    blink> mosh a
    bash: 1.2.3.4: command not found
    Did not find remote IP address

**Comment by goerz** [comment]
You probably put something in the "server" field in the Mosh-section of the configuration of the host. This field is not supposed to contain the IP address of a the server, but the mosh-server-exectuable. The `HostName` in the SSH section is used both for SSH and Mosh. The `Server` in the Mosh-section should almost always be the default `mosh-server`.

This is a long-standing UI-bug: the field really needs to be renamed in the configuration.

**Comment by joech4n** [comment]
That was it! Thank you!
