### ISSUE TITLE
Custom fonts & themes

### ISSUE THREAD

**Issue by vshvedov** [blinksh/blink#33]
Is it possible to use completely custom fonts in Blink? My eyes would be really grateful for PragmataPro.

**Comment by carloscabanero** [comment]
It will be possible. Blink supports WebFonts, so you will be able to add them even if not included in the package ;)

Not only that, but we will also support Custom themes and people sharing them online (hopefully!)

**Comment by Riprock** [comment]
Pragmata Pro is my fave too, but tough to include in apps as it is paid for. WebFonts could work if the user has somewhere on the web to put their font. Already discussed, but weighing in anyway.

**Comment by carloscabanero** [comment]
Hi @Riprock!! Let me know if you had a chance to try the next custom themes and fonts. Would love to see a screenshot of Pragmata Pro!  :)

**Comment by Riprock** [comment]
I've been loyally using the paid for version :D been meaning to switch back to try this. Will post a screenie.

**Comment by Riprock** [comment]
Was checking myfonts and saw this: 
![img_0256](https://cloud.githubusercontent.com/assets/148789/20169234/34cff1ac-a71e-11e6-8a42-dbfdd210c3a2.PNG)
I know the file menu thing is tricky because of sand boxing (is that right?) but what about however this works?

**Comment by Riprock** [comment]
Looks nice!
![img_0260](https://cloud.githubusercontent.com/assets/148789/20173962/8fdf60d6-a733-11e6-9ec6-ef269ad069b8.PNG)
The tip about using gist for HTTPS is appreciated.

**Comment by Riprock** [comment]
Oh yeh I noticed the cursor for Solarized Dark doesn't show up well when you switch to light mode (like I do in Vim). I made a theme with a magenta cursor and slight different opacity and now I can get rid of line and column highlights again :)

https://gist.githubusercontent.com/Riprock/683649ae7c946323331aaec812bb8dbc/raw/3ff3a7b855c0a2aefd1028addae436e9ced21aa9/solarised-dark-magenta-cursor.js

I'm not sure how common using both light and dark is, might be worth updating the built in one.

**Comment by carloscabanero** [comment]
Veery Cooool!!!!! Definitely checking Font Extensions to improve this.

Also, it looks like salaried dark/light is actually a common thing to do :) Related issue #144, I will include your theme in the next version :)

**Comment by carloscabanero** [comment]
Added #209. Closing here!
