### ISSUE TITLE
Failure to examine libssh2_userauth_authenticated leads to failure to use "none" authentication.

### ISSUE THREAD

**Issue by MakeItGreatAgain** [blinksh/blink#330]
per the libssh2 docs: https://www.libssh2.org/libssh2_userauth_list.html:
> "Send a SSH_USERAUTH_NONE request to the remote host. Unless the remote host is configured to accept none as a viable authentication scheme (unlikely), it will return SSH_USERAUTH_FAILURE along with a listing of what authentication schemes it does support. In the unlikely event that none authentication succeeds, this method with return NULL. This case may be distinguished from a failing case by examining libssh2_userauth_authenticated."

The blink code never does this check, thus "none" authentication is broken.  This can be confirmed by attempting to connect to my public Multics host:

`blink> mosh dps8@m.trnsz.com`
`No userauth list`

This will succeed as expected in Prompt, Reflection, PuTTY, and OpenSSH, but fails in blink and ChromeOS mosh/ssh due to the same bug of never checking libssh2_userauth_authenticated.

**Comment by carloscabanero** [comment]
Thanks for the report! Added to backlog

**Comment by MakeItGreatAgain** [comment]
Wanted to mention the new SSH code now fixes this bug.  If the old client isn't code isn't coming back it would be safe to mark as resolved.  If the old client will stick around, it should still be fixed, I'd say.

**Comment by yury** [comment]
No plans to bring old client back. It stay as backup for sometime. Need to iron down some corner cases.
