### ISSUE TITLE
[Feature request/idea] xterm as alternative to hterm? https://github.com/sourcelair/xterm.js

### ISSUE THREAD

**Issue by MakeItGreatAgain** [blinksh/blink#332]
https://github.com/sourcelair/xterm.js is available which is a full port of xterm and "better" in a few ways to hterm that might deserve a look - it's free and there a few other projects now switched or provide it as an hterm alternative.

**Comment by goerz** [comment]
Curses support looks interesting! I remember that's what was keeping @holzschu from compiling the terminal-version of `vim` for inside the Blink shell.

**Comment by yury** [comment]
experimenting... looks nice so far

https://www.youtube.com/watch?v=-4-7aXvsIe8

**Comment by holzschu** [comment]
This looks beautiful. Makes me want to try it.

**Comment by yury** [comment]
More progress

https://youtu.be/V3me_ZEKxsg

- [x] selection
- [x] links
- [x] cursor blinking
- [ ] colors
- [ ] fonts

**Comment by yury** [comment]
Old themes works in compatability mode with xterm.sj

**Comment by yury** [comment]
PR #338

**Comment by carloscabanero** [comment]
We will start testing this and see if it is worth changing for us too.

**Comment by yury** [comment]
Turns out patched hterm.js outperform xterm.js. So we decided to stay with hterm.

**Comment by yury** [comment]
This is what we got.
HyperJS on xterm, Blink on hterm with reactjs:

https://www.youtube.com/watch?v=YcwXdypE6HU
