### ISSUE TITLE
Scrolling doesn't work when using mosh

### ISSUE THREAD

**Issue by WisdomWolf** [blinksh/blink#334]
It seems that scrolling does not work when using mosh.  Actually I don't think that mouse events are passed through at all when using mosh.  I am using tmux on the remote side and have `set -g mouse on` in my .tmux.conf.  I've confirmed that scrolling via the mouse works as expected when using mosh from other clients, which leads me to believe that the issue is on the blink side.

**Comment by mvandermeulen** [comment]
How are you using a mouse on IOS?

**Comment by WisdomWolf** [comment]
I'm not using a mouse, but I assume that touching the screen to scroll is done by simulating mouse events.

**Comment by kimolas** [comment]
This is not an issue with Blink. This is just how Mosh works. Personally, I get around this by always running inside tmux, and using tmux's scrollback.

**Comment by carloscabanero** [comment]
@kimolas is correct. Mosh doesn’t have scroll (it basically work like snapshots, sending only required changes between screens). That’s why it is so fast and works well in snappy connections. Supporting mouse events is a different story that we are also starting to prioritize.

Cheers and thanks for the message!

**Comment by WisdomWolf** [comment]
For some reason I thought that mouse events were communicated when using ssh session, but it appears that the real issue is that mouse events in general aren't working presently.  kimolas apparently missed the part of my issue where I described that I'm using Tmux configured to support using a mouse to scroll.

**Comment by sejmann** [comment]
I second this.  I mosh to tmux and have mouse mode on, and have bound WheelUpPane to allow scroll wheel to view the tmux saved buffer.  This works great from the desktop, but not from Blink.  It would be really great if we could access the buffer from Blink without using the keyboard (CTRL+B "]" up up up...)

**Comment by tiagoefreitas** [comment]
second this, mosh is not usable on mobile without tmux, but we need a way to emulate touch scrolling on tmux or screen

**Comment by carloscabanero** [comment]
We have had mouse events over Tmux and Mosh for a few years now as described here. Mouse events were done when we did all the Hterm patches. To enable Mosh + Tmux + mouse or scroll with touch, try:

https://github.com/blinksh/blink/discussions/1933
