### ISSUE TITLE
Unable to build Blink on Xcode 9b5

### ISSUE THREAD

**Issue by jasondinh** [blinksh/blink#336]
`blink/Sessions/SSHSession.m:630:11: Implicit declaration of function 'select' is invalid in C99`

`blink/Sessions/SSHSession.m:630:11: Declaration of 'select' must be imported from module 'Darwin.POSIX.sys.time' before it is required`

I'm getting these errors when trying to build Blink on Xcode 9b5. I've cloned everything recursively and ran `./get_frameworks.sh`.

**Comment by razvn** [comment]
Hi to fix it add 
````
#include <sys/time.h>
````
at the top of 
`blink/Sessions/SSHSession.m`

Then it will work. Have done it.

**Comment by jasondinh** [comment]
@razvn Thanks, that works.

I made a PR here: https://github.com/blinksh/blink/pull/337

**Comment by yury** [comment]
Ok, I think we ok to close this.
