### ISSUE TITLE
Typing two dashes in the shell prompt erases the first dash typed

### ISSUE THREAD

**Issue by jaderfeijo** [blinksh/blink#343]
Steps to reproduce:

1. Open a new Blink shell
2. Type the `-` character
3. Type a second `-` character

Result:
Both `-` characters will disappear

Expected result:
User should be able to type 2 dashes into the command prompt

**Comment by DavidNielsen** [comment]
If you are on iOS 11 this is a known issue. You can work around it (and other input issues) by disabling Smart Punctuation (Settings.app General->Keyboards).

See https://github.com/blinksh/blink/blob/master/BUILD.md under Changelog for version 7.0

**Comment by jaderfeijo** [comment]
Thank you for the reply @DavidNielsen. Indeed I am running Blink on iOS 11. Completely forgot to mention that.

Thanks for the workaround, I just tried it and it works like a charm 👌🏼
