### ISSUE TITLE
ssh forwarding support

### ISSUE THREAD

**Issue by Roger-luo** [blinksh/blink#347]
I have two severs and server B is connected to server A, which has an IP for ssh. So hope there could be support for ssh configs like

```ssh config
Host A
  HostName 122.222.32.24
  Port 22
  User username

Host B
  HostName Delta101
  User username
  ProxyCommand ssh -o 'ForwardAgent yes' A 'nc %h %p'
```

**Comment by carloscabanero** [comment]
Duplicate of #203. We will rebump all this ones.

**Comment by Roger-luo** [comment]
Cool, thanks!
