### ISSUE TITLE
iOS 11 keyboard doesn’t seem to type single quotes

### ISSUE THREAD

**Issue by ejheil** [blinksh/blink#348]
I’m always getting some kind of smart quote when I use the software keyboard — or even the Smart Keyboard!  No doubt some new helpfulness from Apple, but it’s kinda a problem when you’re logged in at a Unix terminal.

**Comment by javanut13** [comment]
This is apparently resolved and will be published soon: https://github.com/blinksh/blink/issues/302

In the meantime you can disable this option in the iOS keyboard settings

**Comment by ttelford** [comment]
@ejheil : Double quotes are affected the same way.

As is -- (which gets transposed to an en-dash '–')

So until the update, it's definitely worth disabling "smart punctuation" in settings.

**Comment by carloscabanero** [comment]
The tester from Apple asked a few questions about the app, as they sometimes do. Hopefully it will go forward in the next few hours. Apologies for the delay :(

**Comment by carloscabanero** [comment]
The patch applies to dashes, quotes and “smart space deletion” so we should be fine.

**Comment by carloscabanero** [comment]
Closing here ;)
