### ISSUE TITLE
Can’t type double dashes

### ISSUE THREAD

**Issue by wls** [blinksh/blink#349]
Went to try to type `node --version`, from iPad using iOS 11 and both mosh and ssh from inside Blink converted the character to a single — . 

Ideally Blink should have a way to work around Apple's Keyboard "Smart Punctuation" as this sequence of characters occurs often in command lines, while at the same time N-dashes and M-dashes are also valid UTF-8 characters needed in certain input.  Flipping to Settings to toggle system keyboard modes between command prompts and editors seems excessive.

_I'm not sure what the right thing to do actually is in this case, other than just disabling the default setting in iOS._

**Comment by javanut13** [comment]
This will be fixed soon when the new version for iOS 11 comes out: https://github.com/blinksh/blink/issues/302

**Comment by ryskin** [comment]
Waiting, can’t work on iPad (

**Comment by ryskin** [comment]
It's ok, need to disable smart punctuation in settings

**Comment by carloscabanero** [comment]
The new version has already been for more than 4 days in Review. There is a message saying that they are having problems "We are currently experiencing processing issues. Build processing may be delayed." But the Build was already processed long ago, so it shouldn't have anything to do. 

I will try to contact them and see where things are at.

**Comment by fakewaffle** [comment]
I received the update in the App Store and have verified that I can type `—` without it being converted.

**Comment by carloscabanero** [comment]
We can close this with 8.026
