### ISSUE TITLE
Cap lock as ctrl and esc issue

### ISSUE THREAD

**Issue by lookskywalker** [blinksh/blink#354]
I’m using spacemacs hybrid model.
That means I use vim command for navigation and emacs command at insert mode of vim.
In that case I use many emacs command like ctrl + (a, e, f, b...).
I use both cap lock as ctrl and esc. 
In my use case, I found out that when I press cap lock, client first send esc and then cap lock works as ctrl.
In my mac environment, if I press and hold cap lock, I does not send esc.
Easy it possible to make it like that?
Or did I missuse the blink shell?

**Comment by carloscabanero** [comment]
Hi! Thanks a lot for your message.

I think that currently that might not be possible, but maybe together we can come up with a solution or workaround. What is going on is that the flow of events, given by iOS, is to trigger on KeyDown. Blink then interprets this as an ESC pressed, and iOS might even send other events if you then for example press an “a”. This is a great for most of the cases, but not for your very specific scenario.

I unfortunately do not think we have a way to detect the keyUp event, and trying to track a state of KeyUp - KeyDown in a bool is just not going to work. My suggestion is that you try to set a different key, like Cmd as Ctrl (I find this one very useful in emacs myself). But let me know if you have any other ideas and we will consider them!

Thanks again!

**Comment by joshuarubin** [comment]
Just wondering if there might be better support for this now.

**Comment by yury** [comment]
In Blink v13.1 you can assign `caps lock` as mod to `control` and `caps lock` `up` action to esc.
`Up` action will trigger only if no output was generated.
