### ISSUE TITLE
Release on French AppStore

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#355]
Found some documents that will fill out. My French is a bit rusty, but probably good enough for this 😄 

https://stackoverflow.com/questions/14170121/aes-256-encryption-apple-itunes-export-restrictions
http://www.ssi.gouv.fr/en/regulation/cryptology/
https://www.legifrance.gouv.fr/jo_pdf.do?id=JORFTEXT000030255024
https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=LEGITEXT000005789847&dateTexte=#LEGIARTI000006421577

**Comment by jibaku** [comment]
Do you need some help on this ticket ?

**Comment by fjolliton** [comment]
Any progress regarding this issue?

**Comment by carloscabanero** [comment]
They finally got back to us, twice on the declaration. One they said it was on its way, and the second one they said Blink is exempted of control by category 11 Annex I of decree 2007-663.

I’m contacting Apple today but the plan is to release again for v10.104

**Comment by fjolliton** [comment]
Wonderful. It's now available in the french App Store!

Thanks for taking the time to resolve this issue.
