### ISSUE TITLE
App keyboard shortcuts don't seem to work anymore

### ISSUE THREAD

**Issue by samdmarshall** [blinksh/blink#356]
With the last two app store updates it seems that i've been unable to use the `copy` and `paste` keyboard shortcuts anymore. I can still perform the action by using the little popover that appears after a selection happens but not from the keyboard directly like I use to.

**Comment by carloscabanero** [comment]
Thanks for your report Samantha! What do you have setup as shortcuts? Is there any other combination that might collide with that one? If you can send me a screenshot of your keyboard settings that would be perfect. Bunch of thanks as always!

**Comment by bergie** [comment]
I'm seeing this with no customized keyboard shortcuts. Occasionally `CMD-v` and `CMD-p` stop working.

**Comment by samdmarshall** [comment]
@carloscabanero i have no custom shortcuts setup; previously i saw little icons appear on the screen when i copied content using `cmd-c` on my smart-keyboard; however that doesn't seem to work anymore. I can only perform the copy operation by using the popover.

**Comment by yury** [comment]
@bergie I fixed cmd-c, but cmd-v seems to be working ok for me...

**Comment by bergie** [comment]
@yury this seems somewhat non-deterministic. Sometimes they work, sometimes they don't.
