### ISSUE TITLE
Mapping Cmd to Esc does not work as an Emacs Meta key

### ISSUE THREAD

**Issue by leathekd** [blinksh/blink#358]
With Cmd remapped to Esc and typing `M-x` (i.e. `cmd-x`) in Emacs I'll instead see `C-x` in the echo area.  I found #198 and Alt does appear to work as a proper Meta key while Cmd does not.

Just in case I've also tried with `emacs -Q` and found the same behavior.

(I'm using an older Apple bluetooth keyboard, model A1314, if that could affect things.)

**Comment by wuliuxiansheng** [comment]
I have the same issue and I hope this can be fixed since I am using cmd as Meta key all the time.

**Comment by yury** [comment]
This should be fixed in 10 release
