### ISSUE TITLE
Keys don't seem to work

### ISSUE THREAD

**Issue by dakira** [blinksh/blink#36]
What I tried:

1. Copied an existing key to clipboard. Added it to blink (blink did accept my key passphrase). 
2. Created a new key in blink, copied the public key to clipboard and added it to the authorized_keys file on my server manually.

In both cases I was asked to enter the password for the user account.

**Comment by carloscabanero** [comment]
Did you add the -I option to indicate the key to use? Only if called id_rsa it will be used by default.

**Comment by dakira** [comment]
Hey. After your comments I got it to work. Both -l and renaming the key to id_rsa work fine. It is odd, though, that I get the passwort prompt at all, as password authentication is disabled on the server. Using mosh on my PC I can make the following observations:

- given I have multiple arbitrarily named private keys, mosh (or SSH?) picks the right one for the server I'm connecting to and asks me the passphrase. If I enter the wrong passphrase the connection drops (in Blink I get a password prompt after the passphrase prompt even though password authentication is disabled)
- if I don't have a suitable key, the connection immediately drops (Permission denied (publickey)). With Blink, I still get a password prompt.

Is it possible to ask the SSH server whether to use key or password auth?

Also: the usage of -l and naming the key id_rsa is not obvious. If only one key exists, I'd default to that.

**Comment by carloscabanero** [comment]
Thanks for your four detailed response, I agree and will mark as bug to fix on next version. Blink defaults to password even if the server didn't return it, I had to force it before and forgot to remove it. Will be fixed on next version.

About using just whatever key exists as default, I'm not a fan of passing a key to a server that didn't request it, even if we do not support agents or other possible corner cases at the moment. I'd say id_rsa is the known behavior, and once we have Hosts configuration (similar to .ssh/hosts), it should simplify everything too.

**Comment by BinaryBen** [comment]
Semi related - Hopefully some kind of identity and key management is the next priority after SSH? That is what is keeping me from deleting my default WebSSH iOS app. :)

**Comment by goerz** [comment]
I would propose that in the dialogue for generating new keys,  the "Key" field ("Enter a name for the key") should be pre-filled with the default `id_rsa` value. Also, the message "Default key must be named 'id_rsa" should turn red (or be otherwise highlighted) if the default name is changed, to make it clear that the key will not be used by default.

**Comment by carloscabanero** [comment]
Closing as this isn't a bug anymore, and the proposal by @goerz will be fixed on #91 
Have to decide whether "repurposing" issues like this one is better than creating new ones, to not loose the comments and participants.
