### ISSUE TITLE
Alignment issue when using double-width glyphs

### ISSUE THREAD

**Issue by xguerin** [blinksh/blink#363]
Hello there,

It seems that the cursor position is not handled right when double-width glyphs are used. For instance:

![0a8fbba3-0c66-4b41-8c70-9809b3cb0a7c](https://user-images.githubusercontent.com/73404/31579843-3e1e0b8c-b10d-11e7-82d3-ee0bc6a2dddb.png)

Each line with a misalignment contains 2 double-width glyphs each: the arrow and the directory icon. When the directory icon is removed:

![12866aa5-2bdf-43fd-b92a-fa34ff237447](https://user-images.githubusercontent.com/73404/31579865-f589e584-b10d-11e7-93c7-b32fe9c28831.png)

And then when the arrow is defaulted:

![f215d321-fe47-4bf7-9a06-b38ea8f545c5](https://user-images.githubusercontent.com/73404/31579867-00d4d354-b10e-11e7-8fb2-bddf2fcd0297.png)

Other terminals consider double-width character as single-width character and allow for overwrite. Maybe a similar solution can be used here.

**Comment by goerz** [comment]
Is this through mosh, or through ssh? I've had similar problems when connecting through mosh; it seems like the version of mosh on the server has some influence on this.

**Comment by xguerin** [comment]
It’s through SSH.

**Comment by carloscabanero** [comment]
This is really weird because in theory, hterm handles double width glyphs properly. I will keep an eye, but @yury is currently working on migrating to xterm.js that in theory has per-character alignment (this is one of the biggest issues with hterm currently). So the move there should fix this. Sending to the icebox to revisit later.

**Comment by yury** [comment]
Test Flight version should solve this.

**Comment by carloscabanero** [comment]
Hi @xguerin, we just released v9.308 on TF which should fix this. Would you mind to test and let us know if this is solved from your side too? Thanks!

**Comment by xguerin** [comment]
Hey there ! I would love to. I sent you guys my appleID over twitter some time ago to get access to TF but never got into it. Just let me know how I can test that for you.

**Comment by carloscabanero** [comment]
Closing here but still Related to #426.
