### ISSUE TITLE
Use system fonts

### ISSUE THREAD

**Issue by xguerin** [blinksh/blink#366]
Hello there,

Would it be possible to also use system fonts in addition to CSS ones ? I am a user of PragmataPro and it seems it would be the only way for me to use it (I was able to install it through system profiles).

Thanks,

**Comment by yury** [comment]
@xguerin can you try to to use `local("font-name")` in css instead of bundle it?

**Comment by carloscabanero** [comment]
Hi @xguerin! Would you mind sending me an email to cc@blink.sh with your info to add you on TF? I cannot find you on Twitter. Thanks!

**Comment by carloscabanero** [comment]
Done on v10

**Comment by xguerin** [comment]
@carloscabanero I am just coming back to the iPad platform for work and I am back using blink pretty heavily. I don’t recall having ever received the invite for TestFlight; is it still possible to be part of the beta? I am now on twitter @xrguerin. Thanks !

**Comment by carloscabanero** [comment]
Send me your email to Carlos at blink.sh
