### ISSUE TITLE
Change blink Caps as Esc works, but also enables capital letters in vim using Apple Smart Keyboard

### ISSUE THREAD

**Issue by cwerner** [blinksh/blink#370]
Hi

I‘m not sure if this is a bug or intended? I mapped the CapsLock key to ESC for vim. I use a Apple Smart Keyboard (german layout).
My problem is that CapsLock sends ESC but also seems to trigger the regular CapLock mode.

Is there a way around this?

I‘m on TestFlight/ raw.

Cheers,
Christian

**Comment by yury** [comment]
In `modifier mappings` section set `CapsLock` to `None`
In `special keys` section set `Caps as Esc` to `on`

That should help in blink app. But yes, it will switch caps lock in other apps.

**Comment by chrwerner** [comment]
Thanks.

Was using this successfully, but Is it possible that things fail in split mode in iOS11? I have not really found a pattern yet, but I definitively have the problem in splitview. I‘m on the newest iOS11 beta if this matters in any way.

Cheers,
C

**Comment by jpz** [comment]
Hi, I find the same issue - iPad Pro with Smart Keyboard, with settings exactly as @yury suggests above.  In vim, capslock now functions as the ESC key, but the case changes when I press it.

**Comment by orb** [comment]
I am having this problem.  My settings:  Caps lock off in settings. Caps lock switch to/grom latin off in settings.  Caps lock mapped to ctrl in app.

This has been work fine. However, last night I was playing with settings to try and solve the auto-capitalization problem. I turned caps lock on for a bit and it's off now. However, no matter what I do, the caps lock key does both ctrl and the caps lock functionality in blink.  I've set and reset all the related settings and shutdown the ipad.

**Comment by basepi** [comment]
This used to work for me. It was a little finnicky -- each time I switched to Blink I would have to disconnect and reconnect my smart keyboard in order to get caps lock to stay off when I used it as ctrl. However, recently this has broken, and no matter what I do, caps lock as ctrl doesn't disable the caps lock functionality, even just in Blink. It's a big quality of life problem, as I've used caps lock as ctrl for years.

**Comment by yury** [comment]
@basepi can you send screenshot of  you KB settings?

**Comment by basepi** [comment]
![a5cf049f-b301-431d-a615-4449ffe5e0ca](https://user-images.githubusercontent.com/702318/36695100-80d94748-1afd-11e8-93e3-081e0f998d79.jpeg)

**Comment by basepi** [comment]
caps lock to ctrl is the important rebind for me. I haven't used the ctrl key on the bottom row of the keyboard in years. :)

**Comment by yury** [comment]
@basepi still can't reproduce :(

Can you make screen shot of you KB settings in Settings app. (Punctuation and etc)

**Comment by yury** [comment]
Ok, catch it!

I will fix it. But to quick fix for you - enable autorepeat.

**Comment by basepi** [comment]
Unfortunately I have auto-capitalization turned off and autorepeat enabled already. So we may not have found the root cause yet. I tried messing with each of those settings and have been unable to get the issue to go away.

**Comment by basepi** [comment]
I should note that I'm using a smart keyboard. Oddly enough, even with key repeat enabled, my keys don't repeat. I wonder if that setting is limited to bluetooth keyboards? In which case, this could indeed be the issue, because I can't enable auto-repeat for my smart keyboard.

**Comment by yury** [comment]
@basepi Found another thing on our side :)

Can you send screenshot of you screen? Do you have visible smartkeys?

**Comment by yury** [comment]
Keys repeat should work with smart keyboard. I use only that KB. 

Need to know about you KB config in settings.app.

**Comment by basepi** [comment]
Aha! Turning off visible smart keys seems to have worked! I never even considered that might be the problem.

With smart keys disabled I'm back to a working state. Would you still like me to screenshot my keyboard config in settings.app?

**Comment by yury** [comment]
Yep, I still need your settings. I'd like to figure out why autorepeat keys option doesn't work for you. They are awesome!

**Comment by basepi** [comment]
Hardware keyboard settings:

![2626d581-88c4-48e3-ba7b-426b49184dc4](https://user-images.githubusercontent.com/702318/36742800-d48b1a62-1ba5-11e8-8366-6a157d852343.jpeg)

General keyboard settings

![884bc7a6-0b39-46d8-9764-1fd6815cb14d](https://user-images.githubusercontent.com/702318/36742814-de148b72-1ba5-11e8-9c65-427633e8c1f4.jpeg)

Accessibility keyboard settings

![5f2ed81f-a9b4-43d9-aa35-d7d72cc2e4e2](https://user-images.githubusercontent.com/702318/36742829-e7aea3de-1ba5-11e8-8503-24b67c92739d.jpeg)

**Comment by yury** [comment]
I can't believe it! With your settings they stoped working for me to!!

Thanks a lot.

**Comment by basepi** [comment]
Glad you could reproduce! Hopefully you'll be able to work around it. But at least disabling smart keys makes it so I can do work again. Caps lock was killing me!

**Comment by jlmcgehee21** [comment]
I hate to bring this back to life, but I'm having a very similar issue.  I'm using an M1 iPad Pro, on iPadOS 14.6

I have the desire to use CapsLock as Escape on release, and as CTRL for a modifier.

If I set the CapsLock key in settings.app to map to anything other than CapsLock, it seems Blink does not capture the key press at all.

With the settings below, it _mostly_ works, but I still get issues within Blink where the CapsLock key works as CapsLock, particularly, exiting insert mode in Vim, then trying to `:w`, I instead get `:W`.  Any ideas how if this is a bug, or how I could eliminate this behavior?

![6821AE1F-A28B-4922-A05D-769C70B0778C](https://user-images.githubusercontent.com/8727616/127756976-97fcfa59-8a10-4097-a323-edb27f18ab97.png)
![5FF9CE48-5DB4-4417-A611-3EE74DF0CDD5](https://user-images.githubusercontent.com/8727616/127756977-1d7b6bb2-8cd3-4747-9079-b91a324ca6d7.png)
![5BE453C2-5667-4EDC-963E-32697A2F06D5](https://user-images.githubusercontent.com/8727616/127756979-55ae94a7-d7f0-4f91-b221-96c652f6ead5.png)
