### ISSUE TITLE
Screen mirroring with Lighting-HDMI cable

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#374]
I were tried blink using apple cable: https://www.apple.com/shop/product/MD826AM/A/lightning-digital-av-adapter;

Shortly: blink ssh does not use iPad screen mirroring.

There is following issues (I can record short video)

- as I do start blink, everything goes to the connected HDMI screen, the application catching its full resolution and properties and creating one window on iPad screen and second one on HDMI.
In meantime I can control it, everything is fine;

- then if I click with two fingers, and opening an new tab, it opens only on iPad screen. I can type exit and leave it, however from this moment I can't never back to the HDMI screen and control session that exists there;

- additionally, because blink do not use iPad screen mirroring, I only can control it with keyboard on HDMI screen. That is not issue but I can't switch controls.

Is there any way to switch between screens in blink ssh? It would be wonderful to have such option or configuration option to use iPad screen mirroring.

I have recorded gif:
![2017-10-27 11_47_00](https://user-images.githubusercontent.com/26776/32098333-a01f56f2-bb0c-11e7-84cf-ab50c396cfcf.gif)

**Comment by yury** [comment]
did you tried `cmd+o`

**Comment by andrius** [comment]
Thank you @yury, it works. However it is still not perfect, for example I do see smart keyboard line on external display, shading two bottom lines of text. It is disabled in settings. Another thing is screen resolution, on external screen I have to increase font size, but that's only possible through settings, I have to hit `Cmd + ,`, after save blink restarting

**Comment by yury** [comment]
You can tune font size with `cmd+shift+=`

Will fix smart keyboard line on non touchable screen.
Thank you for your feedback.

**Comment by carloscabanero** [comment]
On v10, closing here.

For 13 and up maybe a better way to handle the other screen would be in the new “Control bar”. Will keep an eye on that.
