### ISSUE TITLE
Replay kit support ?

### ISSUE THREAD

**Issue by Maxim-Filimonov** [blinksh/blink#375]
Hi,
I really enjoy using blink and I'm thinking of live streaming coding with it on YouTube. Unfortunately, at the moment there is no direct support of repay kit in blink which means that iOS 11 screen recording should be used instead which has couple of drawbacks:

- inability to use camera - streams are way more interesting with persons face
- No direct streaming to YouTube app(can be worked around using Omlet arcade)

Thoughts on the direct streaming support?

**Comment by carloscabanero** [comment]
This is a great idea, and @yury thought about it a while ago, don't know if he took a look at it.

**Comment by yury** [comment]
Hello. We added `facecam` command, so you can stream to any platform with 3rd party apps and be on the screen.
