### ISSUE TITLE
Scroll momentum doesn't work

### ISSUE THREAD

**Issue by tbodt** [blinksh/blink#377]
When you have a terminal with a lot of output and you flick to try to scroll, it only moves until you take your finger off the screen, and then it stops. It should keep going until momentum runs out.

**Comment by carloscabanero** [comment]
Would love to have this one too. Unfortunately it might be difficult due to the way HTerm is optimized. Will keep an eye if anyone has an idea

**Comment by tbodt** [comment]
I think it would require either modifying hterm or not using hterm.

**Comment by tbodt** [comment]
```css
x-screen {
    -webkit-overflow-scrolling: touch;
}
```
Actually this gets me most of the way there.

**Comment by tbodt** [comment]
There's a sort of flickering when you try to scroll though. Fixing that wouldn't be so easy.

**Comment by carloscabanero** [comment]
Hmmmmm... found this https://gist.github.com/bdalziel/3005482

**Comment by tbodt** [comment]
It's not flickering in that sense, you can see the rows scrolling before they get moved back to where they should be.

**Comment by yury** [comment]
new version is not 100% but very close.

**Comment by yury** [comment]
side note: 
We have tried native safari touch scroll. But it turns out it is very memory heavy and it crashed on big file cats. 

So we go to JS implementation.

**Comment by goerz** [comment]
More than good enough as far as I'm concerned!

**Comment by yury** [comment]
Ok, lets close it for now. May be WWDC will show us some interesing.
