### ISSUE TITLE
Can't see zsh-autosuggestions under Solarized theme

### ISSUE THREAD

**Issue by YujiShen** [blinksh/blink#381]
Under iTerm2 (macOS)
![image](https://user-images.githubusercontent.com/4230496/32410029-3c9a8d9e-c18e-11e7-83cc-f1e09780cd91.png)

Under Blink
![image](https://user-images.githubusercontent.com/4230496/32410066-c9f150ce-c18e-11e7-89cc-e3656bcaf922.png)

**Comment by javanut13** [comment]
I use zsh-autosuggestions in blink without any trouble. I’d guess you may have your ‘TERM’ set differently, or something similar?

**Comment by YujiShen** [comment]
@javanut13 I set `TERM=xterm-26color`, does this cause the problem? What should I set? Thanks!

**Comment by YujiShen** [comment]
I found this is a problem with themes. This Solarized one (preinstalled), can not see suggestions at all. Other themes works fine, although some of them are not very easy to see...

So I change the issue title.

**Comment by YujiShen** [comment]
Because Bright Black color is base03 which used by auto suggestions and is same as background color, so suggestions can not be seen. Refer to this issue [mbadolato/iTerm2-Color-Schemes - Text gets invisible while running mocha](https://github.com/mbadolato/iTerm2-Color-Schemes/issues/59).

I create a [gist for patched theme](https://gist.github.com/YujiShen/dcc2060a5be119bf712f77942bae9e22/raw/9099b9ad0127058f36baabbd76b94faa63acea85/Solarized%2520Dark.js), which change bright black to base01, and tweak the value of cursor. Here is the screenshot:

![image](https://user-images.githubusercontent.com/4230496/32420389-9cfa8b84-c257-11e7-9b71-1e834a5b72b0.png)

**Comment by carloscabanero** [comment]
Thanks for the Gist, I will apply it to next Blink. About changing cursor color font, this is an issue with HTerm and unfortunately they apply transparency. You can change the cursor color though in the cursor_color variable, make it brighter so that it contrasts better too.

This might be resolved if we move to xterm.js
