### ISSUE TITLE
Support for id_ed25519 OpenSSH keys

### ISSUE THREAD

**Issue by nathanielvelez** [blinksh/blink#383]
I use an id_ed25519 key to login to my development server. If I try to add this key to Blink it doesn't recognize it. 

http://blog.siphos.be/2015/08/switching-openssh-to-ed25519-keys/

**Comment by borrible13th** [comment]
Duplicate of #60

**Comment by carloscabanero** [comment]
Yeah, we are implementing ed25519 now, should be available soon. Closing as dup.
