### ISSUE TITLE
Tab indicator does not disappear

### ISSUE THREAD

**Issue by javanut13** [blinksh/blink#385]
Occasionally when using Blink, the tab/ window size indicator doesn't disappear after the timeout. This seems to happen most often when switching back to Blink. This happens both with ssh and mosh.

It will disappear when a new tab is created, but doesn't disappear after moving back to the original tab.

I don't have a reliable set of steps to reproduce, sorry.

**Comment by carloscabanero** [comment]
I fixed the same bug a while ago and the maintainer isn't taking my PRs on this. I will see if I can replicate and fix, I have also seen it myself.

**Comment by carloscabanero** [comment]
#407

**Comment by sssilver** [comment]
Please, this is sucking the living soul out of me... it’s pretty major problem that makes it annoying to work on daily basis, all the time.

![the bug](https://i.imgur.com/i16iP5d.png)

**Comment by yury** [comment]
@sssilver is this App Store version or Test Flight one?

**Comment by sssilver** [comment]
The app store version; I didn't do anything funky. Just bought the app and mosh'ed to my server.

**Comment by yury** [comment]
New version with the fix is on it's way.

**Comment by sssilver** [comment]
Thank you so much -- this is fantastic!

**Comment by carloscabanero** [comment]
@sssilver new version should be out early next week unless we find a crazy issue, but send us an email if you would like to have access through TF. Thanks!

**Comment by carloscabanero** [comment]
Fixed on 10!
