### ISSUE TITLE
UI - iPhone X "notch" and rounded corners are not properly handled

### ISSUE THREAD

**Issue by craSH** [blinksh/blink#386]
On the iPhone X, the terminal UI still behaves as though it's a full rectangular screen without the notch or rounded corners. As such, the first few lines (and last few on the bottom) are clipped from either the rounded corners or space taken up by the notch.

I unfortunately can't attach a screenshot because screenshots capture the entire virtual display area, but if it's helpful I can get a photo of the situation added.

It looks like an open PR (https://github.com/blinksh/blink/pull/380) may resolve this issue (sorry I didn't notice it before, I only searched issues).

**Comment by elliot-wood** [comment]
I’m also getting this on my iPhone X.

Have you tried entering the “config” menu, then leaving it. That seems to be a workaround, and causes the terminal to be pushed down just below the notch.

Scrolling is a bit janky, though: depending on how exactly you scroll you’ll either scroll through the scrollback buffer or push the terminal back up.

**Comment by carloscabanero** [comment]
Fix is already on the AppStore and we are awaiting approval ;)

**Comment by craSH** [comment]
Just grabbed the new version from the AppStore, looks good - thanks & closing!

**Comment by christianbur** [comment]
I can still confirm the behavior described by craSH on my iPhone XS (blink: v13.0.155. Oct 29 2019), I thought the problem was fixed?

**Comment by yury** [comment]
@christianbur we have 3 modes to fit/fill/cover screen. Tap with 3 fingers on the screen and try different options. 

![6094DBA7-0773-4A1C-B514-53053A2BF061](https://user-images.githubusercontent.com/5250/71600682-22916f00-2b61-11ea-92dd-21bdbaca1925.jpeg)
