### ISSUE TITLE
Often crashes when going back to app

### ISSUE THREAD

**Issue by Duvel** [blinksh/blink#387]
Often when I just return to the app to continue a session, I find that it crashes right after TouchId. I need to use screen to be able to continue working on a ssh session.

Please let me know, which info you need. I have a iPad Pro 10,5 with the Smart Keyboard.

**Comment by yury** [comment]
in v9 also?

**Comment by Duvel** [comment]
I opened the issue after the release of version 9 as I wasn’t seeing any difference, but I guess I see some improvement now. When blink returns to a lost ssh session because of absence, it now seems to return to the prompt.

**Comment by Duvel** [comment]
Just had a random crash, loosing my session...

**Comment by goerz** [comment]
I've also been seeing this with increasing frequency, lately

**Comment by yury** [comment]
Will try to find out the issue in crash logs tomorrow. Sorry about that.

**Comment by carloscabanero** [comment]
Fixed on v10.

Related to ssh restore crashing.
