### ISSUE TITLE
paste does not working properly for multi-line text

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#391]
It actually glues multi-line text to the single line. I have tried both Cmd-V and paste

Example:

```
require 'rubygems'
require 'ffi-rzmq'
require 'msgpack'
```

It works with another editor

![6323db9e-0913-4eab-ba5d-00a4fcf1a9e6](https://user-images.githubusercontent.com/26776/32827381-49f31568-c9ec-11e7-8260-3ed12a28b472.png)

![72ae64fd-966c-47c4-9364-84b64d040655](https://user-images.githubusercontent.com/26776/32827382-4a0b295a-c9ec-11e7-95f0-d52346b06a44.png)

**Comment by carloscabanero** [comment]
Don’t fully understand. I just tried this on emacs and it is working fine. Does it still happen?

**Comment by andrius** [comment]
Yes, I simply copied multi line text, ssh-ed with blink and then we’re
tried to paste with vim and nano. I am getting single long line

**Comment by stokkes** [comment]
Any work on this? I copy/paste text so much in my SSH sessions and the formatting gets all messed up, it makes it very difficult to use Blink. I've had to go back to Prompt/Coda for a lot of stuff even though I prefer Blink, it was just too impeding on the work.

**Comment by yury** [comment]
Thanks for feedback. Will be fixed in next release.

**Comment by yury** [comment]
v11.0 released!
