### ISSUE TITLE
Can’t minimize keyboad on iPhone SE

### ISSUE THREAD

**Issue by ryn1x** [blinksh/blink#394]
On my iPad I have the option to minimize the on-screen keyboard, but on my iPhone SE I do not. When watching something like weechat it would be great to have the extra screen space when not actively needing to type.

**Comment by carloscabanero** [comment]
As absurd as this is, we never realized that the iPhone keyboard didn’t have the option to collapse. We should enable collapse on scroll instead of a separate button.

**Comment by carloscabanero** [comment]
Done in v10! Two fingers down will close the keyboard on iPhone :)
