### ISSUE TITLE
Join beta without needing to tweet

### ISSUE THREAD

**Issue by ickc** [blinksh/blink#396]
Hi, I don’t tweet. Could you provide a simple way for people like us to join the beta? I understand you might want the attractions from Twitter, but please at least provide an alternative to those who don’t like social networks (well, GitHub is already the best social network... and that’s why you’re here, right?) If you don’t want to pollute the issue tracker here, just open another repo soly for requesting beta.

**Comment by carloscabanero** [comment]
Hi! Just send me an email to raw@blink.sh and I will get you started. I will update the docs too.
