### ISSUE TITLE
BT keyboard not recognised if already connected

### ISSUE THREAD

**Issue by fergusb** [blinksh/blink#397]
Launching Blink with the Apple BT keyboard already connected results in no keyboard input possibility. 
Workaround: switch off keyboard, quit Blink, relaunch Blink, switch on keyboard

—
IPad Air 2, IOS 11.1.2

**Comment by carloscabanero** [comment]
Thanks a lot for opening this issue @fergusb. Can you please try to switch to a different app and then back to Blink when this happens? I think this is actually an issue with iOS11.

**Comment by fergusb** [comment]
Switching between apps has no effect; I still have to switch off the keyboard, type something in blink, then reconnect the keyboard.
Unfortunately, blink is the only app that has this problem.

**Comment by carloscabanero** [comment]
@fergusb this should be fixed already on 10. I’m closing here but let us know and we can reopen ;)
