### ISSUE TITLE
Problem with Ctrl + Space as a key binding.

### ISSUE THREAD

**Issue by BinaryBen** [blinksh/blink#40]
This may not be Blink specific, but I can't seem to use C-Space (^@, Ctl + SPACE) to be recognized by my server. I am trying to set it as a binding for the Tmux prefix.

In debugging, I have used `cat` and tried to press Ctrl + SPACE expecting ^@ as the output, but it doesn't appear. Can this be replicated by anyone else using Blink?

To be clear, I can set other bindings as the prefix in Tmux.

**Comment by carloscabanero** [comment]
Unfortunately C-Space is reserved by iOS, and it should take you to "Spotlight". I've been successful remapping everything else (We have full Cmd usage, except for Cmd-Space, and also Alt/Option), while nobody else does. But this one is driving me crazy too (Ctrl - Space in emacs for selection). Those who map CAPS to Ctrl will have it on next release. Everyone else should just map to something else.

If anyone has an idea to go around it, I'm glad to give it a try :)

**Comment by BinaryBen** [comment]
Sorry, not sure I am following. Is Ctrl+Space equivalent to Cmd+Space on iOS and/or Blink? I hadn't actually tried using Cmd in Tmux where it's set as Ctl+[letter] - I will test that now.

**Comment by carloscabanero** [comment]
I've been taking a look at this and unfortunately couldn't come up with a solution yet. Both Cmd-Space and Ctrl-Space are system shortcuts. There is a chance of fixing this for the Apple keyboard, as it has a special key for changing language, it seems that it frees the Ctrl-Space, but no (legal) way for the Cmd-Space. 

I will keep it open as a back burner to check what other options we might have before release.

**Comment by BinaryBen** [comment]
I've been looking into it as well and I think you're right about ⌘–Space being unable to be made available in iOS.

From what I've read, I think Ctrl–Space can be made to work, but haven't figured out how yet. 

Thanks for keeping it in mind. It might be a good idea to start a doc somewhere for a future manual that keeps track of limitations ("⌘–Space bindings are unavailable due to iOS keyboard restrictions" for e.g.)?

**Comment by carloscabanero** [comment]
Should be fixed in next version

**Comment by roangel** [comment]
@carloscabanero , is this solved for the last version of iPad iOS? If that’s the case, no doubt I’ll purchase the app.
