### ISSUE TITLE
iPad Software Keyboard has extra space under keys

### ISSUE THREAD

**Issue by s8m2s** [blinksh/blink#401]
On iPad Pro 10.5 inch. After you hide the on screen keyboard, and then bring it back up, there is an extra row of space under the keyboard. This reduces the amount of screen space you have for the shell.
![3944c474-4fa5-4bbe-8b7b-d9f517b15a5d](https://user-images.githubusercontent.com/1937285/33410875-5b7477ae-d550-11e7-8841-4937853f1fa8.png)

**Comment by nicolinuxfr** [comment]
Same on an 9.7 inch iPad Pro.

**Comment by kimolas** [comment]
Was supposed to have been fixed: 

https://github.com/blinksh/blink/issues/316

**Comment by carloscabanero** [comment]
It is still an issue with iOS but we might have to find a workaround. If you open or switch to Blink, the keyboard is fine. If you close the keyboard and reopen it, the gap shows.

**Comment by yury** [comment]
Fixed!
