### ISSUE TITLE
Cmd-c captured by shortcuts when assigned to Ctrl

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#402]
Introduced with the latest changes on shortcuts. Behavior should be that when you configure a Cmd as Ctrl, Cmd-c sends Ctrl-c sequence instead of copy

**Comment by zevlg** [comment]
Note: Cmd-z also does not work for some reason, when Cmd is assigned to Ctrl

**Comment by zevlg** [comment]
Cmd-<space> also opens search box instead of sending Ctrl-<space>, when Cmd is assigned to Ctrl

**Comment by yury** [comment]
@zevlg CMD-SPACE is system wide shortcut. Apps can't modify it :(

**Comment by carloscabanero** [comment]
Yep, unfortunately that’s a common one on emacs to do a mark, but what I do is to just use regular Ctrl for that one. It takes a bit to get used to but is the best we can do.
