### ISSUE TITLE
Can not input with Chinese keyboard

### ISSUE THREAD

**Issue by axelburks** [blinksh/blink#403]
Can not input with Chinese keyboard. And can not see the words that I input, maybe because of the smart keys block it.

**Comment by carloscabanero** [comment]
Thanks for your message @suisr9255. Is this associated to #206 ?

**Comment by carloscabanero** [comment]
Hi @axelburks! We implemented this feature in TF, please let us know if it is working for you :)

If you don’t have access to TF, send us an email or private message on Twitter and we will get you rolling, thanks!

**Comment by axelburks** [comment]
It works correctly now. Thanks.

**Comment by carloscabanero** [comment]
Ready to launch then
