### ISSUE TITLE
Xcode 9 Build Fails: "No such module UICKeyChainStore"

### ISSUE THREAD

**Issue by dmzimmerman** [blinksh/blink#404]
After following the instructions to clone the repo and all dependencies, opening the Xcode project in Xcode 9, and changing the bundle ID, team signing setup, and capabilities setup to use my paid developer account, I cannot build the project: it complains (in file `UserDefaultsPasscodeRespository.swift` that it cannot import `UICKeyChainStore` because there is no such module.

Certainly, the module is there - I can see it both in the Xcode project (under "Frameworks") and the filesystem. I've tried a few things to fix it (changing framework search paths, etc.), but nothing has helped. Assistance (or a fix to the Xcode project file) would be appreciated...

**Comment by zhigang1992** [comment]
I think the app is iOS only, and somehow the scheme supports building for Mac.
You have to set the scheme to a iOS target.

**Comment by carloscabanero** [comment]
Did that help @dmzimmerman? I will try to remove the Xcode scheme for Mac too.

**Comment by dmzimmerman** [comment]
I thought I had set it for an iOS target; I'll try it again and see.

**Comment by jonfink** [comment]
I'm also experiencing this problem with XCode 9.2

I did notice that the UICKeyChainStore.xcodeproj was initially set to a macOS deployment target. I fixed this so that it has an ios deployment target but I'm still getting the same error...

**Comment by jonfink** [comment]
I think this has something to do with the framework search order. Ended up fixing it by adding:

`$(PROJECT_DIR)/Frameworks/UICKeyChainStore/Lib/build/Debug` 

to the top of the Framework Search Paths for the Blink project. Not sure if this is the right fix or not, but there were a bunch of other UICKeyChainStore directories listed in the actually compilation command - just none with the actual framework...

**Comment by yury** [comment]
I think we can close this.
Recursive clone and `./get_frameworks.sh` should work now.

**Comment by ybizeul** [comment]
Using Xcode 10.1, I have the exact same issue. Can we open this again @yury ?

I deleted the repository and followed the build instruction again just to make sure I have everything vanilla.

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/182035/50589157-d1836800-0e85-11e9-9298-8dbf0474e04c.png">

I had it before and fixed it somehow but I don't remember how, probably by fixing some framework search path.

According to default build settings, the `UICKeyChainStore ` framework is built in `~/Library/Developer/Xcode/DerivedData/Blink-aanyagaovcogddaohvraxcyfceba/Build/Products`

**Comment by yury** [comment]
Hi @ybizeul,

Here is my steps:

1. ` git clone --recursive git@github.com:blinksh/blink.git blink-build-test`
2. `cd blink-build-test`
3. `./get_frameworks.sh`
4. `open Blink.xcodeproj`
5. In `General` project settings change bundle ID and team.
<img width="1134" alt="screen shot 2019-01-02 at 3 11 48 pm" src="https://user-images.githubusercontent.com/5250/50591462-e3becf80-0ea0-11e9-8783-7553986bccf1.png">
6. In `Capabilities` project settings remove Carlos identifier from iCloud and check yours.
<img width="1134" alt="screen shot 2019-01-02 at 3 13 55 pm" src="https://user-images.githubusercontent.com/5250/50591506-3f895880-0ea1-11e9-9b8a-fc64c496db72.png">

**Comment by ybizeul** [comment]
Yes, these are the steps I followed, well documented under `https://github.com/blinksh/blink/blob/raw/BUILD.md` but that's the error I get.

**Comment by ybizeul** [comment]
Anything @yury ?

**Comment by yury** [comment]
Not yet. At first I was thinkging you where cloning without `--recursive` and I tried that, but get different error.

**Comment by ybizeul** [comment]
Yes I did the recursive, and UICKeyChainStore target builds fine, but it seems Blink target doesn't find its way to the build

**Comment by yury** [comment]
Hi @ybizeul 

While I was fixing build I got error as yours.

Problems is that you have `Mac` as build device by default.

<img width="492" alt="screen shot 2019-01-17 at 3 34 26 pm" src="https://user-images.githubusercontent.com/5250/51319220-82d0f300-1a6d-11e9-8450-b0963c2839fd.png">

But you should switch to either you device or 'Generic iOS device'

<img width="687" alt="screen shot 2019-01-17 at 3 35 53 pm" src="https://user-images.githubusercontent.com/5250/51319286-abf18380-1a6d-11e9-97ed-12bdbffb91fd.png">

**Comment by ybizeul** [comment]
Looks like that solved it ! Thanks !
