### ISSUE TITLE
Hostname autocompletion feature request

### ISSUE THREAD

**Issue by zevlg** [blinksh/blink#405]
It will be cool to have hostnames autocompleted on <TAB> keypress, as it is done in regural shells.  So having for example host “kuzrpi3” configured, I’d like to type

blink> mosh ku<TAB>

And having kuzrpi3 autocompleted for me

Thanks

**Comment by goerz** [comment]
I'd include that in #43

**Comment by carloscabanero** [comment]
Thanks! You can actually do that now on Spotlight, and auto completion is coming. Closing here as duplicate then.
