### ISSUE TITLE
Blink leaves detached mosh sessions on remote host

### ISSUE THREAD

**Issue by tonilampela** [blinksh/blink#411]
After some period of time when launching Blink app it forgets the existing mosh session which results in long run to multiple detached mosh sessions on the remote host. Is this something that can be fixed in Blink?

**Comment by samdmarshall** [comment]
I am noticing this as well, it is definitely not ideal.

**Comment by carloscabanero** [comment]
Working on this as part of #59, and we already have it working internally ;)

Closing here.
