### ISSUE TITLE
Terminal dimensions badge in the middle won’t disappear

### ISSUE THREAD

**Issue by sssilver** [blinksh/blink#414]
The square badge that displays the terminal dimensions won’t disappear when Alt+Tabbing to Blink. It’ll only go away if I pinch to adjust the terminal font size.

I’m using the Apple Smart Keyboard with the iPad Pro.

**Comment by javanut13** [comment]
Duplicate of #385

**Comment by carloscabanero** [comment]
Fixed on 10!
