### ISSUE TITLE
Have to tap on-screen on iPad Pro with external keyboard connected to allow input to start

### ISSUE THREAD

**Issue by snorbaard** [blinksh/blink#416]
Using iPad Pro 10” with Apple Smart Keyboard. I’ve found that when I open Blink, the prompt appears, but the keyboard is not used until I actually tap on the screen.
It’s an annoyance, but not a critical bug,but interrupts an otherwise smooth workflow.

**Comment by zevlg** [comment]
same story with logitech slim combo keyboard and ipad pro

**Comment by jason-green-io** [comment]
I'm getting this with a Bluetooth keyboard on an iPhone 6s. Seems focus isn't restored when going into `config`

**Comment by yury** [comment]
@jason-green-io your are on Test Flight version on App Store?

**Comment by jason-green-io** [comment]
I am on TestFlight

**Comment by snorbaard** [comment]
May I have an invite to the testflight version of the app, please

**Comment by zevlg** [comment]
Is it possible to download Test Flight version somehow?, I have no mac to build from sources :(

**Comment by edgauthier** [comment]
I’m seeing this on test flight build 9.230 and 9.308. I’m also seeing this on the iPhone as well. After initial launch, you have to tap the screen to trigger the keyboard to come up and begin typing, as opposed to being in a state ready to type the first command.

**Comment by carloscabanero** [comment]
@snorbaard @zevlg send me an email to cc at blink.sh and I will get you rolling ;)

**Comment by carloscabanero** [comment]
@edgauthier do you mean iPhone with Bluetooth keyboard? I’m unable to replicate this with any of my setups anymore :(

**Comment by edgauthier** [comment]
@carloscabanero No bluetooth Keyboard in the iPhone case. Just commenting that it seems to be the same behavior on iPhone. When launching Blink, after the TouchID auth, the terminal doesn’t have focus. A tap is needed to give focus, which enables typing on the iPad via a keyboard, or triggers the virtual keyboard on iPhone (and presumably the same with the iPad virtual keyboard, but I don’t have my iPad with me at the moment to reporoduce).

**Comment by edgauthier** [comment]
To be honest, I can’t recall if this changed with the new rounds of beta. I feel like this has been the behavior for a while now.

**Comment by carloscabanero** [comment]
@edgauthier, you were very right. The TouchID thing was the difference. We fixed it in v10, but it also happens after closing Settings. These details are important for a smooth experience, so I won’t close yet.

**Comment by yury** [comment]
`cmd+o` shortcut will focus in/out in v12.3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yury** [comment]
Closing, if cmd+o is not enough feel free to reopen.
