### ISSUE TITLE
Custom fonts don't work in latest TestFlight version 9.224 (1)

### ISSUE THREAD

**Issue by fffergal** [blinksh/blink#418]
First thing I noticed was my custom font wasn't being used. Checked the config and the font was listed. Tried toggling a few times but nothing changed. Tried deleting the font and adding it again, but still didn't change. When I installed the App Store version again, everything worked fine.

**Comment by yury** [comment]
@Riprock can you share link to your custom font?

**Comment by Riprock** [comment]
Yep, but you have to promise not to use it ‘cos it’s payed for. https://gist.githubusercontent.com/Riprock/c9c6270d9b5cd5962baf6ac8fe23f657/raw/e77e740536d346615fa4f281e93baa63cc7761c1/pragmatapro.css

**Comment by vectorstorm** [comment]
I'm having this same behaviour, perhaps coincidentally with exactly the same font, although I've added it using the src: url('<url>', format('truetype')); syntax, instead of embedding the font data directly into the css file.

Going by my webserver logs, Blink downloads the css file, but never seems to download the font files themselves.

**Comment by yury** [comment]
@Riprock 
Ok, I don't know how it is working in app store version. Your css seems to be broken with \n in base64 data.
I did join all the lines in one line and it works like a charm.

https://gist.githubusercontent.com/yury/f5a76a6cb8756a10cc44a581598c2cf0/raw/98fd18c9344a933393a7c5d46352d8c59da0100b/pragmatapro.css

**Comment by yury** [comment]
Actually if you have installed any font with ios profile (for example with Fonteer app) you can use simple css:

```css
@font-face {
  font-family: 'Cutive Mono';
  src: local('Cutive Mono');
  font-weight: normal;
  font-style: normal;
}
```
https://gist.github.com/yury/806613e6f6d3dab8c96cfe834f37d5ef

**Comment by Riprock** [comment]
Ah, did not know Blink was compatible with profile fonts now cool. Interesting about the new lines, worked the first time I tried it so didn't think more about it.

**Comment by yury** [comment]
@Riprock, @vectorstorm next version will allow you to select any monospaced font on you system without custom css.

**Comment by vectorstorm** [comment]
Sounds good;  I'm looking forward to that!

**Comment by Riprock** [comment]
That would be brilliant!

**Comment by Riprock** [comment]
Yeah educated myself and really data URIs in CSS should have slashes before the new lines. Interesting it used to work, but maybe this shouldn't be called bug?

**Comment by yury** [comment]
@Riprock please test your font installed with profile. It should appear in fonts list now.

**Comment by zevlg** [comment]
JFYI: There is script to generate css files for blink - https://github.com/zevlg/py-scripts/blob/master/gen-blink-font-css.py

**Comment by Riprock** [comment]
@yury That's excellent, sorry I didn't try it before my TestFlight was being a bit slow. It works great!

**Comment by yury** [comment]
So, I think we can close this issue.

**Comment by yury** [comment]
@fffergal Sorry for offtopic, but what version of font you are using? Mono, Mono with liga, Not mono with liga?

**Comment by fffergal** [comment]
It's full Pragmata Pro mono (so no ligatures) but not with the bold and italic variants.
