### ISSUE TITLE
Keyboard shortcut and french layout

### ISSUE THREAD

**Issue by psaintemarie** [blinksh/blink#419]
Hi,

Using a french bluetooth keyboard, I can't use the default (and unchangeable) keyboard shortcut to **_Switch to shell number N_**.

I also can't use the Blink shortcuts such as:

* **_Previous Shell_**  `Key + [`
* **_Next Shell_**  `Key + ]`

The `]` and `[` characters are not easily usable on french keyboards.
And by default, the numbers are not accessible, you need to do `shift+key` to get to the numbers.

You can take a look at [this page](https://support.apple.com/en-us/HT201794) for default keyboard mapping.

Cheers!

Using v9.224.1 through Testflight.

**Comment by carloscabanero** [comment]
Thanks a lot Philippe and great catch! Can I ask you how you usually change tabs in Safari?

**Comment by carlos-solis** [comment]
I have the same problem with a Spanish keyboard.

**Comment by drbarrett** [comment]
cmd-alt-N doesn’t change views with my US keyboards, and cmd-[] moves forward and backwards, not cmd-shift-[]. This is with 9.230.1

**Comment by yury** [comment]
Actually, help shows default KB shortcuts. Next version will show actual shortcuts.

**Comment by phdoerfler** [comment]
This is also a problem with the Apple Magic Keyboard with German layout. Neither Cmd+0-9 nor Cmd+[] work.
On a German Apple keyboard [] is entered via `Option + 5` for `[` and `Option + 6` for `]` respectively.
Ideally we could remap those keys ourselves.

**Comment by bey2lah** [comment]
Still a problem with the iPad Pro Smart Keyboard with German layout.
Cmd+Shift+[] won‘t work on my German Keyboard.
Custom remapping would be great as suggested by @phdoerfler .

**Comment by SteffenDE** [comment]
This is an issue for me as well with the German Magic Keyboard. Is somebody working on a fix?

**Comment by yury** [comment]
In Blink v13.1 you can assign any combo to any command.
