### ISSUE TITLE
Allow comment for Keys

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#42]
When exporting a key from Blink, it does not have a trailing comment, e.g.

```
 ssh-rsa AAAAB...idtMZlnWy3trQ== goerz@blink_ipad
```

I would propose to add a 'comment'  field in the Key Settings (underneath Name) that allows to define this comment. If not such comment is defined, I think at least the Name should be used as the comment.

**Comment by goerz** [comment]
I didn't realize that "Name" was actually the filename for the key (and should generally be `id_rsa`). That means that obviously, the Name should not give the default for the comment. It also makes a separate Comment field more relevant.

**Comment by carloscabanero** [comment]
Sold! Will add another text field for this, with a default to the user@device.

**Comment by carloscabanero** [comment]
PT #122598341

**Comment by carloscabanero** [comment]
- [ ] Add a new section on Settings > Key > Create Key called "Comment". Fill by default with "user@device" name. The user must be the default user from BKDefaults. If the device name cannot be guessed, use Blink. 
http://stackoverflow.com/questions/8261961/better-way-to-get-the-users-name-from-device
- [ ] Save comment as part of the BKCard object as an optional parameter.
- [ ] Append the comment at the end of the BKCard publicKey method.

**Comment by carloscabanero** [comment]
Done!
