### ISSUE TITLE
cmd-+ locks screen resizing in 9.230.1

### ISSUE THREAD

**Issue by drbarrett** [blinksh/blink#423]
If I try to resize the screen with cmd-+, it jumps to a default size and won’t get bigger than that. cmd - will make it smaller, but cmd + goes back to the same size.

When this happens the pinch gesture won’t make the screen larger or smaller.

However, if you press cmd - one or more times followed by a pinch in either direction the problem is cleared until cmd + is pressed again.

**Comment by yury** [comment]
Yep, that problems is that shortcuts are:
- `cmd -` smaller
- `cmd shift +` bigger
- `cmd +` default

**Comment by yury** [comment]
Fixed. 
Thank you for feedback.

**Comment by drbarrett** [comment]
It's working for me in the latest beta.
