### ISSUE TITLE
Garbled screen

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#426]
I'm having serious problems with completely garbled screens in the latest beta, especially in the combination tmux/(neo)vim/unicode

For example, my screen may look like this:
![0cbb987e-f7a9-488f-8f0e-e872a235bb6d](https://user-images.githubusercontent.com/112306/35750991-dc24872a-0824-11e8-9102-318762873a93.png)

Hitting CTRL+L sufficiently often will sometimes make the screen look the way it's supposed to:
![52dacd2e-af10-40e3-8adc-c5f876c1bb3e](https://user-images.githubusercontent.com/112306/35751050-0bf84a2c-0825-11e8-8166-d95e1dd98aaa.png)

This is using ssh. The problem is even worse when using mosh (I've always had rendering problems with mosh as soon as there are non-trivial unicode characters, even when using mosh from my Macbook; sadly, it makes mosh almost unusable for me, making me fall back to ssh unless I have a truly bad network connection).

The garbling is primarily caused by scrolling in vim (screen-wise, or half-screen-wise), or by switching tmux panes. Actually, garbling can happen even when I don't do anything: text fragments will just appear on the screen randomly.

Since the garbled screen was not workable at all, I switched back to the App Store version of Blink. Then, today, I decided to give the beta another try (and write this bug report). Surprisingly, immediately after re-installing the beta, I couldn't reproduce the problem. But then, I switched to another app for a few minutes. When I switched back to Blink, I found that the ssh connection had been disconnected (and in fact, the Blink screen was garbled). After reconnecting ssh, the garbling problems are back in general. Reconnecting, killing sessions, or even force-quitting and restarting Blink does not fix the problem.

I'm using Source Code Pro. My tmux and vim configurations are at https://github.com/goerz/dotfiles/blob/linode/HOME/.tmux.conf and https://github.com/goerz/vimrc, respectively. If needed, I can also give you some Julia source code files that contain non-trivial unicode.

**Comment by carloscabanero** [comment]
Thanks Michael for the thorough explanation. Would you mind sending me your Julia files too? I'd like to see if this is hterm to blame or what.

**Comment by goerz** [comment]
https://github.com/goerz/blinkissue426

The file shown in the screenshot is in `./test/run_single_node.jl`. If you can't reproduce the problem, I can also arrange for you to have temporary direct access to my user account on the machine I'm connecting to. That'd have to be live-supervised though (through [tmuxpair](https://github.com/goerz/tmuxpair)), so you'd have to hit me up by DM on Twitter to coordinate that.

**Comment by yury** [comment]
@goerz thanks a lot for your feedback. Didn't noticed that. But I'm able to reproduce it with tmux panes and scroll.

Seems to be hterm issue. But I will try to fix that on monday.

**Comment by carloscabanero** [comment]
Hello again @goerz, we could replicate this cases thanks to your scripts and we think we have nailed it in v9.308 for, both ssh and mosh. Actually we saw that it still fails in other iOS terminals, so thanks for the heads up! Please confirm and hopefully we can close.

**Comment by goerz** [comment]
It seems much better now! I'm still seeing some small problems with the screen redraw when switching into Blink from another app (SSH). As an example, I've recored the following video:

https://vimeo.com/255225563 (password: blink)

It's not reliably reproducible behavior, but mostly I've been managing to trigger the problem when copying text in Safari before switching back with cmd+tab. Only one tmux pane is affected. The only thing I've found to restore the proper rendering is to change the font size of the terminal.

It's pretty manageable. Not something that would keep me from updating. But still, maybe it's fixable.

I have a train ride tomorrow which will give me a good chance to also test the mosh protocol under real life conditions (mobile notework with spotty service)

**Comment by goerz** [comment]
I've been testing mosh under adverse conditions (on the train), and it's been absolutely rock solid. I'm actually not seeing any kind of unicode problems, which is a first! Mosh on the iPad now works better now than from my Macbook, which is quite mindblowing!

This is shaping up to be Blink's best release ever (so far)! 👍

**Comment by goerz** [comment]
You could close this in favor of  #437. I think it's really a separate issue from the original issue.
