### ISSUE TITLE
Unstable SSH connection

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#427]
I might be imagining this, but I have the feeling that SSH connections are considerably less stable in the latest beta than in the current app store version. For the most part, I used to be able to leave the Blink app to browse Safari for a considerable amount of time, and then switch back to Blink to find my SSH still intact.  I often rely on SSH if my network connection is reasonably stable, because mosh has always given me a lot of problems with unicode.

With the latest beta, switching away from Blink for as little as two minutes will generally cause the connection to crash. As I reported in #426, this also seems to lead to problems with garbled screens.

**Comment by carloscabanero** [comment]
Thanks again. That is correct. As ssh connections cannot be restored, they are now being reset more often. We should probably use some heuristic for this scenarios, to not touch ssh almost at all but still save and restore mosh every time we can.

**Comment by carloscabanero** [comment]
A fix should be out on v9.307.3. Please let us know!

**Comment by carloscabanero** [comment]
Hi @goerz , it was v9.308 in the end. If you have time I would love to know if we can close this. Connections now for ssh should live for as long as iOS maintains the socket. We have improved also mosh in you case for #426 so hopefully you can upgrade.

**Comment by goerz** [comment]
Looks like it's working fine now! I'll be keeping an eye on it for the next few days...

**Comment by goerz** [comment]
By the way, and just out of curiosity: what does the "RTT" tag mean?

**Comment by goerz** [comment]
With mosh, I can confirm that the connection survives both re-installing Blink and rebooting the iPad, which is absolutely crazy!

After the reboot, the screen rendering was a bit messed up (somewhat similar to the video I linked in my recent comment for #426), which was fixed by changing the font size temporarily.

**Comment by yury** [comment]
I think we can close this issue. Lets keep #426 until we solve it.
