### ISSUE TITLE
Fix weird light spot on icon

### ISSUE THREAD

**Issue by relapi** [blinksh/blink#428]
![icon](https://user-images.githubusercontent.com/23083813/35984159-7028ddca-0cb9-11e8-8889-bfacc543515b.png)

**Comment by carloscabanero** [comment]
Hahaha! I hate that too, but it was a wink to our old designer who was feeling very strongly about it. We will tune up our logo and webpage soon.

**Comment by yury** [comment]
https://sketch.cloud/s/71JKw
