### ISSUE TITLE
Cmd mappend to Esc

### ISSUE THREAD

**Issue by zevlg** [blinksh/blink#429]
Got unexpected behaviour when Cmd is mappend to Esc:

`Cmd-a` generetes `^a` (Ctrl-a) instead of `^[a`, same for `Cmd-X` and `Cmd-V` - they generates codes as if Ctrl is pressed instead of Esc

Looks like a bug to me

I use blink from AppStore, thanks

**Comment by yury** [comment]
@zevlg thank you for feedback.  Yep, I fixed that just today. 

Unfortunately, this fix didn’t make it to latest TF. So it will be in next App Store release. Which is very very soon.
