### ISSUE TITLE
Command completion

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#43]
It would be great to have some tab completion for the `blink>` commands. Ultimately, full readline support (e.g. searching in previous commands via `ctrl-R`) would be great

**Comment by Riprock** [comment]
Ctrl-r especially could be great. Better than favourite connections.

**Comment by carloscabanero** [comment]
Awesome! Great to have other opinions, I agree that for a terminal, commanding the interface is better than navigating it. Reverse search makes a lot of sense, and I don't think it is very difficult to add to line noise (probably someone already did).

**Comment by kitserve** [comment]
A bit of a 'me too' comment here, but I would find it useful if autocompletion was added for mosh/ssh, ssh keys and registered hosts, and also if support for ^R, ^W, ^U and ^Y was added.

**Comment by tbrowder** [comment]
I enjoy this feature, so why is this issue shown in github as open?

**Comment by goerz** [comment]
readline support would go a bit further than just host completion.

But I agree that the current version of blink already has nice completion, so I don't think of this issue as a very high priority.

**Comment by yury** [comment]
ok, we have ctrl-r now. Closing.
