### ISSUE TITLE
When internet connectivity isn’t working no hosts are shown

### ISSUE THREAD

**Issue by nielsk** [blinksh/blink#433]
I sync blink via icloud (I bet that the problem is dependent on that). When I am connected with OpenVPN to the VPN of the office, my iPhone does have internet connectivity problems (dns works, but I cannot connect to most services). In that case all hosts vanish in Blink until I close the OpenVPN-connection when they immediately reappear. 
Whenever i configure during that „offline“-time a host that existed before, I will get shown a sync-conflict with iCloud even when the hosts are identical.

**Comment by nielsk** [comment]
iPhone 7
iOS 11.2.5
Current beta (how about adding somewhere the version of the app in the app)

**Comment by yury** [comment]
@nielsk help command show version at the top.

**Comment by nielsk** [comment]
Blink: v9.230.1. Jan 30 2018

**Comment by nielsk** [comment]
I just saw that there is an update available. The problem persists:

Blink: v9.308.1. Feb  8 2018

**Comment by Duvel** [comment]
+1

**Comment by carloscabanero** [comment]
Closing. Not relevant anymore. Please reopen if you see this again.
