### ISSUE TITLE
Synthetic bold breaking rendering

### ISSUE THREAD

**Issue by fffergal** [blinksh/blink#434]
Hello, I notice 9.308 (1) introduced synthetic bold. I know because my vim syntax uses bold, but my font face has never had a bold variation installed and it use to render as not bold on Blink, but now it is rendering as bold so it must be synthetic. Unfortunately the synthetic bold widths are not the same as the normal widths and it's breaking rendering. See the screenshot, there are some places where characters are clipped, and I made one line start witht he same thing as a bold line and it quickly goes out of sync.

Thanks,

![82e87e3c-21d2-4af2-b914-2228655d286f](https://user-images.githubusercontent.com/148789/36074502-798f09c6-0f38-11e8-85a3-a9a4db198fae.png)

**Comment by yury** [comment]
@fffergal we added more options to Appearance config:
- enable bold (auto, on, off)
- bold as bright (on/off)

this give you more control how bold is rendered.

**Comment by fffergal** [comment]
Sounds perfect, thanks!

**Comment by yury** [comment]
@fffergal  can you confirm that it works for you in latest App Store version?

**Comment by fffergal** [comment]
Yep. Auto seems to do the right thing for my font too (not use bold), and moving it to "on" makes it use bold.

I accidently unsubscribed in TestFlight while moving to AppStore version… can I please get another invite?

**Comment by carloscabanero** [comment]
@fffergal Just sent you a DM!

Closing here :)
