### ISSUE TITLE
Left and right Cmd

### ISSUE THREAD

**Issue by zevlg** [blinksh/blink#435]
I have Logitech Slim Combo keyboard, which has Cmd keys around space button
```
[i18n][Ctrl][Alt][Cmd][    space    ][Cmd][Alt]
```

I want left `Cmd` to generate `Ctrl`, and right `Cmd` to generate `Esc`.  Is it possible in iOS at all?

thanks

**Comment by carloscabanero** [comment]
Thanks for your message! Unfortunately iOS doesn’t currently support or differentiate between left or right. These are the ones currently supported https://developer.apple.com/documentation/uikit/uikeymodifierflags, but hopefully that could change :)

Will keep it here in the icebox as a reference.

**Comment by yury** [comment]
in Blink v13.1 you can remap left and right cmd/alt/ctrl
