### ISSUE TITLE
occasional screen cropping when resuming session

### ISSUE THREAD

**Issue by drbarrett** [blinksh/blink#437]
In 9.308.1 most of the time when I reopen a mosh session, the screen restores normally. Occasionally the right edge of the screen is cut off and is filled with whatever color is near the lower right corner. I'm causing this by opening the terminal, doing a brief bit of work, closing blink and coming back and reopening blink after 10-20 minutes. If it happens it usually takes 4-6 times to occur.

This is similar to the old rotation problem, but that has been a non-issue for awhile now.

setup:ipad pro 10.5, up to date ios

![img_0054](https://user-images.githubusercontent.com/408923/36174218-a26ca4a0-10d9-11e8-8e90-6d5af2006226.png)
![img_0055](https://user-images.githubusercontent.com/408923/36174219-a50461da-10d9-11e8-85c1-d53e02ff88fd.png)

**Comment by goerz** [comment]
I think that's the exact same effect I was showing in that video on #426

**Comment by drbarrett** [comment]
Yeah, I agree although I’ve had more trouble reproducing it than you did in the video.

**Comment by goerz** [comment]
It's not easily reproducible for me either. I just let the the screen recording run for a while and then cropped the video.
