### ISSUE TITLE
Mosh client does not work with non-US locale

### ISSUE THREAD

**Issue by bchallenor** [blinksh/blink#438]
The mosh client [appears to hardcode](https://github.com/blinksh/blink/blob/05af591c005ac7e397bf6cc2a4bb631bfe1b1cc3/Sessions/MoshSession.m#L250) `LC_ALL=en_US.UTF-8`. This breaks connections to servers with other locales (e.g. `en_GB.UTF-8`):

```
The locale requested by LC_ALL=en_US.UTF-8 isn't available here.
Running `locale-gen en_US.UTF-8' may be necessary.

mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment ([no charset variables]) specifies
the character set "US-ASCII",

The client-supplied environment (LC_ALL=en_US.UTF-8) specifies
the character set "US-ASCII".

sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Ideally this would be configurable, but failing that, my guess is that a default to `[NSLocale currentLocale]` would be more likely to be correct than `en_US`?

**Comment by QasimK** [comment]
I previously reported this in #294

**Comment by carloscabanero** [comment]
Fixed. We provide through the LANG variable the environment to the remote. If you need to configure it to something else, you can either use setenv or use .blink/profile file, which will apply the environment variables to the session. Note we are only passing LANG and TERM by default, if you need any other, please use ssh -o flag.
