### ISSUE TITLE
Opinion - Why include audio transport controls?

### ISSUE THREAD

**Issue by s8m2s** [blinksh/blink#441]
In ios the native ios audio transport controls are just a swipe into control or notification center. From a customer prospective, one of the things that differentiate blink from other clients is its stripped-down simplicity in favor of performance and minimal ui. 

The recent addition of transport controls seems a slight continuance at the possible expense of blinks philosophy. Obviously, this is a minor gripe in what is otherwise a great update.

**Comment by goerz** [comment]
I must have missed it. What is this new “transport control” feature?

**Comment by s8m2s** [comment]
Swipe up with 2 fingers. Paste in there too

**Comment by yury** [comment]
@s8m2s thanks for response.

We added that to stream line workflow. Switching to iOS control center to rewind or to skip to next is very long task, especially if you are on smartkb. 

We will put something more useful in our control panel if we had something. 
Stay tuned... :)

**Comment by yury** [comment]
Hi @s8m2s, can you take a look at #523 ? Is this any better for you?

**Comment by yury** [comment]
No more music controls. In v12.3 layout and lock controls instead.
