### ISSUE TITLE
Blink 10.3 breaks Swiftkey autocomplete

### ISSUE THREAD

**Issue by strowger** [blinksh/blink#442]
I'm running Blink 10.3 - dated Feb 12 2018 - the current/latest version offered by the app store.

This version introduced a bad bug for me - the behaviour of autocomplete within the Swiftkey keyboard changed.

The bug happens when autocomplete is offered after a word is partly-typed with errors.

For example, I want to type "fascinating". I type badly so I enter"fasz" and these keystrokes are forwarded over the mosh connection to the remote host; I see them echoed back to me.

I then accept the autocomplete suggestion of "fascinating" by tapping it above the keyboard.

In the previous versions of blink, the keystrokes entered over the mosh connection to the remote host would be taken back - I'm not sure whether swiftkey or blink was emitting backspaces, but one of the two was - and replaced by the autocomplete suggestion, so I would see "fascinating" on my screen.

In the current/new version, the keystrokes entered over the mosh connection to the remote host are not taken back, so I see "faszcinating" on my screen.

Please return to the previous behaviour :-(

**Comment by yury** [comment]
@strowger thank you for your feedback. Sorry we break a flow for you. Will try to fix is in next release.

**Comment by yury** [comment]
Should be fixed in next TF version

**Comment by strowger** [comment]
Testflight has just offered me 10.015(1) and I have installed it, but it still suffers the same problem.

**Comment by carloscabanero** [comment]
Hi @strowger, hope things are going great! I just pushed 10.021 to TF that should have this fix. You should be able to download it once it passes the review. Thanks!

**Comment by strowger** [comment]
Chaps,

Thank you for the updates. Will report once TF offers me 10.021.

Use blink heavily and greatly appreciate your work.

**Comment by strowger** [comment]
Seems fixed in 10.021.

Thank you.
