### ISSUE TITLE
Xcode 9.3 beta/iOS 11.3 beta: "Too many arguments to function call, expected 7, have 11" in MoshSession.m

### ISSUE THREAD

**Issue by jaytay79** [blinksh/blink#443]
I'm trying to build Blink for iOS 11.3 beta for the first time today but it's failing with the above error pointing to "[self.sessionParameters.key UTF8String]" in MoshSession.m (line 227)

```
  mosh_main(
            _stream.in, _stream.out, _stream.sz,
            &__state_callback, (__bridge void *) self,
            [self.sessionParameters.ip UTF8String],
            [self.sessionParameters.port UTF8String],
            [self.sessionParameters.key UTF8String],
            [self.sessionParameters.predictionMode UTF8String],
            self.sessionParameters.encodedState.bytes,
            self.sessionParameters.encodedState.length
            );
```

**Comment by carloscabanero** [comment]
Yep, that’s because my build server went to hell and I’ve been compiling all the pieces by myself. Unfortunately I haven’t updated the precompiled frameworks script, but I will do that tomorrow.

**Comment by jaytay79** [comment]
Ah that makes sense, I noticed that the PasscodeLock framework didn’t appear the first time I tried to build so I fixed that one manually thinking it was an issue at my end 🙂

**Comment by mcapelle** [comment]
Hi, do you have any news on this subject?

**Comment by lyosha** [comment]
ditto

**Comment by jaromirrivera** [comment]
This happens with Xcode 9.2 as well.

**Comment by mremond** [comment]
Yep, same issue here. Did you find which older tag should work?

**Comment by carloscabanero** [comment]
Hey, I fixed it yesterday as I put the CI server up and running again. 

If you want get_frameworks to do the work for you, please just select the “raw” branch from Blink. I won’t provide a fix on get_frameworks for current master, but if you take the precompiled binary from https://github.com/blinksh/build-mosh/releases/download/1.3.2-8cd6688/libmoshios-1.3.2-8cd6688.framework.tar.gz, it should work too.

Let me know if you have any other problems and once done please close.

**Comment by lyosha** [comment]
Builds and runs from "raw" branch. Thanks!

**Comment by carloscabanero** [comment]
Closing
