### ISSUE TITLE
Ctrl-Alt+<key> generates nothing

### ISSUE THREAD

**Issue by zevlg** [blinksh/blink#444]
Combination of `Ctrl+Alt+<any-key>` generates nothing :(

For example by pressing `Ctrl-Alt-p` I was expecting to get `^[^P`, as if I press`Caps Ctrl-p` (with enabled “Caps as Esc” option in config), but got nothing instead

I use v10.3 from appstore.  Thanks for the awesome update btw!

**Comment by yury** [comment]
seems to be same as  #99

**Comment by yury** [comment]
Turns out it is not same as #99 :(

**Comment by zevlg** [comment]
Everything seems to work, except for `Ctrl-Alt-d`, it sends nothing

I have `Ctrl` bound to `Cmd`

**Comment by zevlg** [comment]
@yury do you have any ideas why `Ctr-Alt-d` is not working when Ctrl is bound to Cmd ?

**Comment by yury** [comment]
@zevlg cmd-alt-d is iOS wide shortcut to bring up dock. I don't think we can override this, same thing with cmd-space :(

**Comment by zevlg** [comment]
Argh, understood, thanks
