### ISSUE TITLE
Convert to Swift

### ISSUE THREAD

**Issue by relapi** [blinksh/blink#449]
This’ll probably be required at some point, plus it opens the project up to a bigger pool of potential contributors.

**Comment by nanzhong** [comment]
I'd love to work on this. Are there any objections to start rewriting individual classes in swift and slowly porting it all over?

**Comment by yury** [comment]
Since swift 5 is ABI stable. Any port to swift PRs are accepted. We will try to add new features implemented in swift too.

Closing this issue as a very general. Feel free to reopen.
