### ISSUE TITLE
Hosts configuration

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#45]
It would be great to have a way to configure "shortcut" names for servers, and default usernames (similar to the settings that are normally done in `~/.ssh/config`. This would mean one could only have to type

    blink> mosh webserver

and blink would expand `webserver` to e.g. `goerz@webserver.michaelgoerz.net`

**Comment by carloscabanero** [comment]
This is coming on next release. We will start by having "Hosts" configuration, probably in the future extending with wild cards to mimic some of the .ssh/config functionality with hierarchies of rules.

![image](https://cloud.githubusercontent.com/assets/536729/16386526/460aaae0-3c91-11e6-8eb8-d63f48566d45.jpeg)

**Comment by carloscabanero** [comment]
Done on v0.927. Let me know what you think!

**Comment by goerz** [comment]
Looks great! (except that I'm having problems with mosh, see #106)
