### ISSUE TITLE
"No userauth list" error when server accepts NONE authentication

### ISSUE THREAD

**Issue by daniel-formlabs** [blinksh/blink#450]
https://linux.die.net/man/3/libssh2_userauth_list says,

"Send a SSH_USERAUTH_NONE request to the remote host. Unless the remote host is configured to accept none as a viable authentication scheme (unlikely), it will return SSH_USERAUTH_FAILURE along with a listing of what authentication schemes it does support. In the unlikely event that none authentication succeeds, this method with return NULL. This case may be distinguished from a failing case by examining libssh2_userauth_authenticated(3)."

But https://github.com/blinksh/blink/blob/master/Sessions/SSHSession.m#L469 just emits an error instead of checking.

**Comment by carloscabanero** [comment]
Fixing on next version with libssh

**Comment by 0xCMP** [comment]
Still seeing this on latest version from the App Store. Trying to connect to `ssh brow.sh` to test it out and I'm getting `No userauth list`

**Comment by yury** [comment]
Got it working with ssh2!

`ssh2 -o compression=no brow.sh`

![img_0525](https://user-images.githubusercontent.com/5250/42818863-a243fef4-89da-11e8-9cf3-1b5c77a6c66a.PNG)

**Comment by yury** [comment]
`ssh brow.sh` should work now.
