### ISSUE TITLE
mosh-client encoding problem  

### ISSUE THREAD

**Issue by scotty1373** [blinksh/blink#451]
Today when i changed my mac language to English(U.S.) , I find out that mosh-client can't recognize the encoding. the error report as follow.

###
The locale requested by LC_CTYPE=UTF-8 isn't available here.
Running `locale-gen UTF-8' may be necessary.

The locale requested by LC_CTYPE=UTF-8 isn't available here.
Running `locale-gen UTF-8' may be necessary.

mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment (LC_CTYPE=UTF-8) specifies
the character set "US-ASCII",

The client-supplied environment (LC_CTYPE=UTF-8) specifies
the character set "US-ASCII".

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
Connection to 192.168.31.218 closed.
/usr/local/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
###

Mosh can be used normally before i changed my mac language. I think the result which cause the issue is the system coding format, actually i still have no ideal to solve this problem.

**Comment by carloscabanero** [comment]
Hi! Please change language encodings to UTF (I’d do the all). Mosh requires (very smartly) to do that to avoid precisely this encoding problems.

Thanks!
