### ISSUE TITLE
shift-tab does not work

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#453]
[One of my vim plugins](https://github.com/JuliaEditorSupport/julia-vim#latex-to-unicode-via-tab-key) uses the key-combination shift-tab to convert latex sequences to unicode (in command mode in vim). In Blink, this does not work. The combination seems to have the same effect as pressing tab by itself: it inserts `^I`. Actually, this by itself is also different from what happens when I do the same thing on my laptop (a tab key does nothing there).

You can reproduce this by using my [vimrc](https://github.com/goerz/vimrc), opening a new file in vim, `:set ft=julia`, and then `:/\alpha<shift><tab>` which is supposed to produce `:α`, but produces `:\alpha^I` instead.

**Comment by yury** [comment]
@goerz thank you for your feedback.

It is already fixed and will be available in next TF.

Ref #117

**Comment by goerz** [comment]
I can confirm this working in today's Testflight release.

**Comment by lev-kusanagi** [comment]
Shift + tab doesn't work again, it seems.

I've tested this on the most recent version, built with Xcode from the repo obtained via the commands:
git clone --recursive https://github.com/blinksh/blink.git && \
cd blink && ./get_frameworks.sh

**Comment by yury** [comment]
Hi @lev-kusanagi,

Just test it and it works for me. What kb you are using?

**Comment by lev-kusanagi** [comment]
Hi @yury thanks for your reply. I’m using the Thinkpad Bluetooth keyboard with Trackpoint.

https://www.amazon.com/ThinkPad-Compact-Bluetooth-Keyboard-TrackPoint/dp/B00C32FWJC

**Comment by yury** [comment]
Hi @lev-kusanagi,

Please run `showkey` command and paste output here.

And if it possible, please check it other apps. For instance, in numbers.app `tab` selects next cell and `shift+tab` it selects prev cell ([see video]( 
https://youtu.be/3stppvNyi6c)). Does it work with you kb?

**Comment by lev-kusanagi** [comment]
showkey outputs:
When pressing just the tab key:
 \t      9 0011 0x09
When pressing shift + tab: 
^[      27 0033 0x1b
[        91 0133 0x5b
Z       90 0132 0x5a

Yes, in numbers.app, tab selects the next cell and shift+ tab selects the previous cell.

Thanks again for the help.

**Comment by yury** [comment]
So, everything seems ok to me.

What app within blink don't work properly with `shift+tab`? I tested with zsh completions.

**Comment by lev-kusanagi** [comment]
Hi @yury, the probem occurs while using emacs, sorry I forgot to mention that.

Specifically, I noticed the problem while using org-mode.

**Comment by yury** [comment]
Hmm, I'm not emacs user. But when I try to press shift+tab in emacs it prints `<backtab> is undefined` (Don't even know what mode I'm in :) ). So emacs see that shortcut and recognize it for me.
Didn't setup anything, just `brew install emacs`.

/cc @carloscabanero  as emacs guru :)

**Comment by lev-kusanagi** [comment]
@yury Ah- emacs in ubuntu 16.04, i forgot to mention! 

Still- Interesting! <backtab> sounds better than what I get (i types out a Z right now :D) 
@carloscabanero te invocamos! ayuda por favor :) My emacs brother :D

**Comment by yury** [comment]
Oh, I forgot, I have installed emacs24 on ubuntu and I get <backtab> is undefined too...

I don't think we should create new issue. Carlos will answer as soon he have time.

**Comment by carloscabanero** [comment]
@lev-kusanagi I was actually going to suggest you to try using org-mode. In my case it is collapsing the sections. Can you do a `M-x describe-key` and see what it returns? In my case, within org-mode:

```
<backtab> runs the command org-shifttab (found in org-mode-map), which is an                                                                   
interactive compiled Lisp function in ‘org.el’. 
```

**Comment by lev-kusanagi** [comment]
thanks @carloscabanero ! app is crashing on launch now, even after rebooting. will post the result of describe key after i sort that out! (any tips welcome of course)

**Comment by lev-kusanagi** [comment]
@carloscabanero M-x describe-key outputs "M-["

**Comment by lev-kusanagi** [comment]
@carloscabanero also, in org-mode as well, Alt + Enter (M-RET) produces just "RET" in M-x describe-key

**Comment by yury** [comment]
Hi @lev-kusanagi,

How did you fix crashes? And may be you know what cause it?

Thank you.

**Comment by lev-kusanagi** [comment]
@yury Sorry, I've been traveling! I haven't solved the crashes, it still happens. I think I'm going to rebuild and reinstall it, and hope for the best. Is there already an issue for this? Otherwise I should open one.

@carloscabanero does that output from M-x describe-key make any sense? That's probably the reason it isn't working.

**Comment by yury** [comment]
Hi @lev-kusanagi,

Yep, please try latest from `raw` branch. And if it crashes for you, please feel free too create new issue. 
Thank you.

**Comment by lev-kusanagi** [comment]
@carloscabanero I suppose the question is- which terminal do you use?
