### ISSUE TITLE
Strange issue with entering spacebar

### ISSUE THREAD

**Issue by neutralinsomniac** [blinksh/blink#454]
I’m on Blink 10.021 on a latest gen iPad running iOS 11.2.6. I’m experiencing an issue on Blink (whether in the bare Blink shell, SSH, or mosh), where randomly my spacebar types what appears to be a space, and then immediately a backspace after. This is more prevalent with repeated successive presses of the spacebar. I can link to a video of the issue if you are unable to reproduce it. This happens with the software keyboard _and_  a Logitech Folio bluetooth keyboard. Please let me know if there’s anything I can provide to help.

**Comment by yury** [comment]
@neutralinsomniac  thank you for feedback.

This is already fixed. And will be good in next TF version.

Thanks again.

**Comment by goerz** [comment]
Same problem here. What's the ETA for the next TF version? Because it's driving me a little nuts ;-)

**Comment by yury** [comment]
New tf version should be right today

**Comment by yury** [comment]
Actually it is published, so waiting for Apple servers.

**Comment by carloscabanero** [comment]
Just got approved :)

**Comment by goerz** [comment]
Yes, just got it, and I think I can confirm that the space bar issue has been resolved! 👍

**Comment by yury** [comment]
This can be closed now
