### ISSUE TITLE
Please update the Fira Code font

### ISSUE THREAD

**Issue by ylluminarious** [blinksh/blink#455]
Fira Code had a [new release](https://github.com/tonsky/FiraCode/releases/tag/1.205) a few days ago, with some nice features. It'd be great to see it in Blink.

**Comment by yury** [comment]
@ylluminarious thank you for feedback.

Already, updated! Will be on next release.

**Comment by ylluminarious** [comment]
@yury Thank you! Should I close this or leave it open till the next release?

**Comment by yury** [comment]
Lets keep it open for release notes.

**Comment by yury** [comment]
@ylluminarious do you have access to TF version?

**Comment by ylluminarious** [comment]
@yury What do you mean by "TF" version? Do you mean the new version of Fira Code?

**Comment by yury** [comment]
Sorry, Test Flight version of Blink :)

**Comment by ylluminarious** [comment]
Oh, ok. On my device, I currently have version 8.026 installed.

**Comment by yury** [comment]
why not 10? 10 is awesome!

**Comment by ylluminarious** [comment]
Heh, good question. I've been meaning to... but I've been putting off the build for a while now since I sometimes have build issues. Just too much to do and not enough time  :tired_face:
But 10 does look great so I'll update soon.
