### ISSUE TITLE
Emoji Characters Breaks “Cursor Forward”

### ISSUE THREAD

**Issue by cwis-public** [blinksh/blink#456]
I am using Blink v0.10.3, from the App Store. I have recently upgraded to NeoVim and have experienced weird bugs with it: sometimes, characters are being drawned with an incorrect offset on-screen, which makes the experience unusable. 

I have been able to reduce the problem to the following: there seems to be a bug with Blink, not handling correctly the “Cursor Forward” ANSI command on lines that contain an emoji character.

I can reproduce the problem by performing the following steps:

1. Log-in to a mosh server, on Debian 9.3
2. Run the “reset” command
3. Run the following command:
`echo -en "\033[2J \033[1;1H👻hello\033[Cworld\033[2;1H"`

The `echo` commands does the following:

1. Clear the display
2. Jump to line 1, column 1
3. Write `👻hello`
4. Execute “Cursor Forward”
5. Write `world`
6. Jump to line 2, column 1

When I run the following from macOS Terminal, I get the expected result:

![bbccf3cf-7d3d-4982-96c9-191553c0e882](https://user-images.githubusercontent.com/18751999/36938935-608e827a-1f29-11e8-94f3-34bfc9a248e0.jpeg)

However, when I run it from Blink, I see an additional space character between `hello` and `world`:

![fcba8b0a-ba16-418d-9346-894cb56ce6bf](https://user-images.githubusercontent.com/18751999/36938913-d672d726-1f28-11e8-8254-0614529a47db.jpeg)

Note that, sometimes, the character just before `world` is not a space, but another character, such as `~`. I am not familiar with how Blink handles this, but it might be that the bug is related to the fact Emoji characters are two-characters wide, as far as the cursor is concerned, and maybe a “spurious” character is inserted when VT commands ask for the cursor to be moved.

Please let me know if there is anything I can do to help you pinpoint this issue.

**Comment by yury** [comment]
Hi, @cwis-public. Thank you for you response.

Don't have debian server. I have tested on ubuntu, os x.  Works fine.

**Comment by cwis-public** [comment]
Hi @yury, I have just tested my reproductions steps against Ubuntu and you are correct nothing bogus happens.

I have tweaked my steps a little bit and I can reproduce something weird on Ubuntu:

1. Log in to your Ubuntu instance, and prepare a shell script:

```
cat > cursor-forward.sh <<EOF
#!/bin/bash 
reset 
echo -en "\033[2J \033[1;1H👻hello\033[Cworld\033[2;1H" 
EOF
```

2. Next, create a new Blink tab (double-finger tap), log in to your Ubuntu instance and execute `bash cursor-forward.sh`. If you are as succesfull than I am to reproduce the problem, you should see the following output:

![392a9c62-a4d7-4a8f-b892-8d8c1a290ddc](https://user-images.githubusercontent.com/18751999/36944575-d7f86274-1f9f-11e8-9b37-da53495d3735.jpeg)

Notice that this is slightly different from the output I have on my Debian server, for some reason I don't fully understand: this time, the “cursor forward” appears not to move the cursor.

I have tested this on Ubuntu 16.04.03 LTS: 
 
```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

If you still can't reproduce my issue, would you be able to share the output of `lsb_release -a` so that I can try looking for reproduction steps that work on your system?

Thanks!

**Comment by yury** [comment]
Yep, now I have it too. Will look today. Thanks!!!

**Comment by yury** [comment]
@cwis-public 
I confirm, that I can reproduce this with your script in blink, but I have bad news.
I have same result in Terminal.app too :(

I debugged, and mosh send wrong cursor coordinates.

**Comment by yury** [comment]
<img width="574" alt="screen shot 2018-03-04 at 6 47 10 pm" src="https://user-images.githubusercontent.com/5250/36947424-7ca65ace-1fdc-11e8-8ac1-b749682b12dc.png">

I think it is mosh version.

**Comment by cwis-public** [comment]
I think it's partly my fault, I've been trying to reduce the initial problem I had in neovim, and found another, unrelated, issue. My initial bug was with the “neomake” neovim plugin, which I have configured to display the “ghost” emoji as a warning sign. When I do this, vim sometimes mangles the line with the ghost emoji when “cursor forward” happen. This makes editing such lines highly inconvenient, because there is an offset between where neovim thinks the characters are, and where they really are according to Blink.

I have been trying to find out steps to reproduce the problem, and I think I have partly found a culprit: it seems that running mosh on my Debian 9.3 is way less stable than running the same setup on my Ubuntu 16 server. For some reason I don't fully understand, Ubuntu handles emojis better than Debian. (Can this be related to the glibc version they use?)

There is, however, an issue that I am able to reproduce only on Blink.  I have uploaded a ZIP file with the relevant `script` logs here: 
https://drive.google.com/open?id=1QAv4mGmw8CLbDN3YxI1IigUM0-aKL3i6

To replay my files:

```
scriptreplay --timing=time log
```


Here is what I am trying to do in the shell:

1. Edit a JS file with warnings, so that Neomake display ghost emojis as signs:

![24b77bce-8970-4b2d-8ced-fc81ede103f3](https://user-images.githubusercontent.com/18751999/36949517-e49e83f6-1fe9-11e8-96df-c84417f522f2.jpeg)

2. Hit “Control-L” to have neovim redisplay. (Hitting ^L is not the only way to reproduce the bug, but it is the easiest.)
3. With Terminal.app, everything displays as expected. However, in Blink, there is some confusion in what gets displayed:

![0759296f-b347-406c-b079-1fbc168a040b](https://user-images.githubusercontent.com/18751999/36949531-00fbf506-1fea-11e8-9bf8-b5fe05394c32.jpeg)


Based on your knowledge, do you think this is an issue with Blink?

**Comment by cwis-public** [comment]
Oops, I forgot to update the sharing permissions of the zip file. I think the link is now public!

**Comment by yury** [comment]
Hmm, replay didn't work for me well :(

May be you can setup docker image with your setup? (you grant access for short time). It will speedup things.

If I can repro that - I will fix that. Sorry for unusable experience.

**Comment by yury** [comment]
Side note, just FYI, we remapped C-L in mosh to C-^ C-L.

**Comment by yury** [comment]
Ok, seems to me wcwidth works differently on server, iOS and os X :(

Sequences mosh sends to us on iOS

First draw:
```
muse strict\"\x1b[0m;\x1b[?25l\r\n\x1b[0;30m\x1b[48;5;248m👻\x1b[0m\x1b[48;5;81mhello\x1b[3;9H\x1b[0m= 42;\r\n\x1b[0;34m\x1b[48;5;248m
```

After refresh: (note [0m= = 42)
```
muse strict\"\x1b[0m;\x1b[K\r\n\x1b[0;30m\x1b[48;5;248m👻\x1b[0m\x1b[48;5;81mhello\x1b[0m= = 42;\x1b[K\r\n\x1b[0;34m\x1b[48;5;248m
```

We need to figure out how to be on par with os x client.

**Comment by yury** [comment]
The main problem, is that wide char tables should be synced on client and server to work properly.

Mosh devs are working on syncing wide chars tables between client and server. I hope they will release it soon.

iOS client and OS X client have different implementations of wcwide too.

I will try too look, how to make iOS client wcwidth to match OS X wcwidth. 

You solution mask Ctrl-L case but not solves root of problem. If only Ctrl-L is bothers you - we remapped client and server screen refresh to Ctrl-^ Ctrl-L in next version.

**Comment by cwis-public** [comment]
FWIW, I don't have any issues with ^L *per se*. My real issue is that, when editing files with Neovim/Neomake, when warnings appear, Neovim redraws the row to include the “ghost emoji” sign, and the characters starting with the first space on that row are displayed with an offset, making edits uneasy. I was suggesting we reproduce this bug with hitting ^L because it appears that the code used by Neovim to handle ^L is the same than the one being used when warnings/errors are added, making the issue simpler to reproduce.

As far as I understand, the following happens:
1. I open the file for the first time. Neovim redraws the line where the signs are added, starting with the emoji at position 1.
2. Mosh-server catches that the lines needs redrawing, and is sending the full line.
3. When I decide to edit the file and Neomake detects some warnings/errors, or when I hit ^L, Neovim redraws the line, but using different ANSI commands. This time, all the spaces are drawn with “Cursor Forward”
4. When mosh-server sees the terminal changed, it creates a delta of cells that needs to be sent to mosh-client. This time, mosh-server decides to send partial rows, and this is what triggers the bug: for some reason, the partial row cannot be interpreted by Blink, and characters end up being displayed at a bogus location. 

My “fix” works because disabling sending complete row always work.

One last thing: you said you believed the root cause could be of different semantics for `wcwidth` on macOS/iOS. I have just tested on both platforms and `wcwidth(L'👻')` returns `-1`. I am not too familiar with the source code of Blink/mosh, I assume this is handled with using some “defaults” width? 

Also, I have tweaked the source code of `Display::put_row()` to include a `Position Cursor` command before every cells being drawn: (this is in `terminaldisplay.cc` from mosh-server)

```
// BEGIN
char tmp[ 64 ];
  snprintf( tmp, 64, "\033[%d;%dH", frame_y + 1, frame_x + 1 );
  append( tmp );
frame.append( tmp );
// END
frame.append_cell( cell );
```

I would have expected that force positioning the cursor would help fix incorrect width computations on iOS: since I know the cells calculated in mosh-server are correct, I would have expected that sending all these cursor positioning commands would help sync the client with the server. 

However, this did not fix anything, and made the offset bug even worse (both lines with emojis were off, other lines were not impacted).

**Comment by yury** [comment]
@cwis-public we got new rendering on TF version, can you check if is any better for you?

**Comment by cwis-public** [comment]
Unfortunately I think I'll have to wait for the next version in the App store, as I've not cloned/compiled Blink on my Mac. I'll let you know!

**Comment by cwis-public** [comment]
@yury, I just saw your tweet regarding the new release of Blink. Congrats for the hard work!

Regarding this issue, however, the problem regarding displaying emojis is still there. I am using mosh 1.3.2 on the server, let me know if you think I should switch version, or if there is anything I might do on my side.

**Comment by carloscabanero** [comment]
This should have been fixed a while ago after a deep rewrite on hterm side, etc... Closing here.
