### ISSUE TITLE
Keybord shortcuts for switching tabs

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#46]
It would be great to have keyboard shortcuts in addition to all gestures. For switching between tabs (gesture swipe-left, swipe-right), I would propose `cmd-shift-[` and `cmd-shift-]`, i.e. the same shortcut that e.g. safari uses to switch between tabs

**Comment by yury** [comment]
Vote for this. Can't create new tab with gesture either.

**Comment by BinaryBen** [comment]
+1

**Comment by BinaryBen** [comment]
Can't edit my previous +1 to include a better comment on mobile:

Given a similar tab like system, the more it mimics safari in use when it comes to keyboard shortcuts, the better imho. 

I think you certainly made the right choice when it comes to gestures, but power users already use the keyboard and it would be great to have the same shortcuts available.

**Comment by yury** [comment]
Could anybody explain how can I create another tab in current version?

Tried tap with to fingers - nothing is happening

**Comment by BinaryBen** [comment]
That sounds like a bug then? A single tap with two fingers should do it?

**Comment by yury** [comment]
https://m.youtube.com/?#/watch?v=0ERjG7YDKE4

**Comment by carloscabanero** [comment]
Hi @yury ! That's really weird, also because the pinch or two finger scroll was removed since 0.714. Can your confirm you are at least running that version?

**Comment by yury** [comment]
Just reinstalled Version 0.722 (23) – same thing.

iPad pro 9.7. iOS 10 beta 1

**Comment by carloscabanero** [comment]
Gonna install iOS 10 and try to replicate.

**Comment by yury** [comment]
@carloscabanero UPDATE:

ok, with iOS 10 beta 3 tap with two fingers do create new tab now :)

But two finger swipe left/right (switching tabs) doesn't work yet.

**Comment by yury** [comment]
Another update. iOS 10 beta 3 switching between tabs is working (kind of)....

**Comment by yury** [comment]
Added in PR #219 

cmd+alt+N for direct shell. cmd+shift+[/] for scroll nav

**Comment by carloscabanero** [comment]
This should be up and running on v5 :)
