### ISSUE TITLE
Constantly crashing when trying to copy text

### ISSUE THREAD

**Issue by iantervela** [blinksh/blink#463]
This was working fine, but now after the latest update when I'm ssh > screen and trying to copy a piece of a JSON file, the app crashes consistently after holding down on it trying to select it.

**Comment by yury** [comment]
Hmm, interesting...
Did you try to select part of the url or path? in json?

**Comment by yury** [comment]
Ok, it should be url without host :(

**Comment by iantervela** [comment]
It's strange, it seems to almost want to work but when I'm trying to just select a customer's email that is inside of a JSON array then a few hashes down, it just totally crashes and kills my ssh session. Seems like it's new on 11.2.6. I rebooted, reinstalled. and nada. 

Any way I can grab the logs?

**Comment by yury** [comment]
I'm on it. Fix is almost ready.

**Comment by carloscabanero** [comment]
I will push a version in a few hours to fix this bug, it may take a while more for Apple to accept it though.
