### ISSUE TITLE
Regarding autocomplete...

### ISSUE THREAD

**Issue by dwest100** [blinksh/blink#466]
I see that autocomplete is present. For instance, if I type “mosh “ , autocomplete shows “server” which is a host I have configured.
But how do I accept that and continue :) Space bar eliminates it, return ignores it...do I still have to type “server”??

**Comment by carloscabanero** [comment]
Just tab, and if you are on an iPhone, the ->| symbol.

**Comment by dwest100** [comment]
Yep I tried that with no reaction on the screen. I’m in iPad PRO, current iOS rev, and using an external Logitech keyboard. I also tapped the tab symbol on the screen keyboard to no avail.

**Comment by carloscabanero** [comment]
Hmmmm that's weird and I cannot reproduce it. I wonder what your device may be sending then. Could you please do a showkey -a in one of your servers and see what sequence it is being sent?

**Comment by dwest100** [comment]
Keyboard tab is sending 9 0011 0x09.

**Comment by dwest100** [comment]
Tab key in blink screen keyboard sends 9 0011 0x09 as well.

**Comment by zevlg** [comment]
@dwest100 I think you should type first letter ‘s’ and then press TAB. Looks like Blink does not autocompletes on empty string and single choice

**Comment by dwest100** [comment]
@zevig, yes that works! Thanks!

**Comment by carloscabanero** [comment]
Good catch @zevlg. Closing here!
