### ISSUE TITLE
Alt+Shift+<key> generates special characters

### ISSUE THREAD

**Issue by zevlg** [blinksh/blink#468]
If I press `Alt+9` it generates `^[9` as expected.  However if I press `Alt+Shift+9` it generates `·` instead of expected `^[(`, same for any `Alt+Shift+<key>` combinations

I’m using Blink from appstore with logitech keyboard

**Comment by yury** [comment]
Good catch! Should be in next release.

**Comment by ereslibre** [comment]
@yury Thank you! :)

**Comment by net** [comment]
Will this be released soon?

**Comment by yury** [comment]
Hi @net,

We just released v11.0
