### ISSUE TITLE
Smartkeys bar even when hardware keyboard attached

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#47]
It might be good to have an optional Smarkkeys bar even when a physical keyboard is attached. This bar should include function keys. It should not be active by default (blink should keep its full-screen userinterface as much as possible), but should be accessible through the options, a shortcut, and/or a gesture (e.g. swip-up)

**Comment by carloscabanero** [comment]
#122978021

**Comment by carloscabanero** [comment]
Done already on v5.
