### ISSUE TITLE
Problem with official Apple HDMI Adapter

### ISSUE THREAD

**Issue by robinfdx** [blinksh/blink#471]
Hello,

I have issue with official Apple HDMI Adapter, you can see the video bellow : 

https://www.youtube.com/watch?v=077rZxb5JA8&feature=youtu.be

When i have plug the adaptateur and i launched blink, i have two separates shell on each screen (ipad-> master and external -> slave). when i wrote in my keyboard it appears in the slave screen per default. The config screen appears  only in the master/ipad screen.

I have other issue (with the Apple HDMI Adapter too) with the keyboard, when i disconnect my bluetooth keyboard and i want use the software keyboard, i have just the shortcut bar display, no software keyboard.  

It's normal ?

I think it's better in recopy mode only, no ?

**Comment by yury** [comment]
Hi @robinfourdeux.

Thank you for your feedback.

Focus on external (slave), I think is good thing. Some people don't get it that is additional screen, and blame that it just blank.

About config: Config is touchable control. So there is no point to show it on external display. 

Last thing about shortcut bar - will try to fix that.
