### ISSUE TITLE
How does a blink user get help?

### ISSUE THREAD

**Issue by tbrowder** [blinksh/blink#473]
Not everyone loves twitter.  I am used to IRC or mailing list for discussions and help.  I hate to open an issue for questions but I will if I must.

Even a Google Group would "help!"

I love blink (on iPad) in spite of this issue!

**Comment by goerz** [comment]
How would the developer feels about a [gitter chat](https://gitter.im)? It integrates very well with Github projects, and is very easy to set up. Pretty close to IRC.

**Comment by goerz** [comment]
Alternatively, for a Q&A, [Discourse](https://www.discourse.org) might be good. But then, I think the Github issues are probably sufficient.

**Comment by yury** [comment]
Lets try discord  https://discord.gg/AauNTMG

**Comment by zevlg** [comment]
Discord is 10 people rooms only, no?  Maybe public supergroup in telegram?

**Comment by yury** [comment]
@zevlg can you link to that limit? can't see anywhere.

[Large communities out there already](https://blog.discordapp.com/open-source-and-discord-b7466080fbf2)

And yep, we are using telegram internally, but it is a little bit not convenient to use for me right now.

**Comment by zevlg** [comment]
https://support.discordapp.com/hc/en-us/articles/223657667-Group-Chat-and-Calls

```Keep in mind, group DMs have a limit of 10 users. If you want to party with all of your numerous friends more than 10, just make a server! ```

**Comment by yury** [comment]
@zevlg thanks. We created server, so we can have big parties. Try it :)

it have slack compatible hooks and understands GitHub webhooks too.
