### ISSUE TITLE
Command key sticks after Command-Tab

### ISSUE THREAD

**Issue by abrookins** [blinksh/blink#476]
Hey y’all! Amazing product. Still happy I purchased it.

One problem I’ve had for months on iOS 11, with a 10.5 inch iPad Pro, is that after using Command-tab to switch into Blink from another app (any app, it seems?), the Command key occasionally ‘sticks,’ for lack of a better word. Here are some facts I think I know for sure by now:

- I can tell that the Command key is ‘stuck’ (not physically, of course) because typing a key like comma, by itself, opens the configuration panel. That is, a single comma press is interpreted as Command-comma

- It’s a software-level stickiness. After Command-tabbing back out of Blink, the key won’t be stuck in another app, like Safari

- Often switching back out of Blink is enough, but sometimes I have to quit the app

- The issue has happened with three different Bluetooth keyboards (currently the Logitech k811), and I also reproduced it with a wired USB keyboard attached via adapter — so it’s not Bluetooth-specific

- Curiously, the issue never happens with Apple-made apps

-  I’ve also reproduced the issue with Pythonista, so it’s not Blink only and may be a flaw with sticky ghost modifiers given to apps after Command-tabbing

Anyway, this is pretty annoying. When combined with another similar issue, where I have to tap the screen to begin using an external keyboard after switching into Blink, it really interrupts my dang flow.

**Comment by carloscabanero** [comment]
This seems to be, unfortunately, a bug on iOS. It happens to me also between safari and notes, and sometimes even shows the shortcuts list with no way to remove them. 

We should probably open an issue to Apple.

**Comment by abrookins** [comment]
I hope this kind of stuff is on their list of things to do while they focus on quality. 🤦‍♂️

**Comment by carloscabanero** [comment]
Also, what happens in my case, just pressing the cmd alone makes it get back to normal. I never had to restart the app. Only in cases when the key gets stuck in all apps, and not even cmd+tab works, I have to restart the iPad.

**Comment by abrookins** [comment]
The problem for me, specifically with Blink, is that I use Vim — I’m always
in Vim — and my leader key is comma. So every time this happens, which
feels as often as every other time I switch into the app, the settings
panel opens. But the settings panel can only be closed by tapping, there
doesn’t seem to be a way to do it from the keyboard, so in addition to
fiddling to get the key unstuck, I have to tap away this screen.

It’s amazing to me that Apple shipped iOS with this flaw in a machine
marketed with its own special keyboard — and still hasn’t fixed it. I’m
also surprised to hear that you have the problem (and relieved it’s not
just me) because I haven’t been able to find anyone describing it by
searching on google.

**Comment by carloscabanero** [comment]
What I would suggest so that it doesn't trigger the shortcut on you all the time, is to change the shortcut key within Blink to something else. You can do that on config > keyboard > shortcuts, just define the sequence that works better for you. At least that would prevent Blink from opening the settings all the time.

And about how often it happens, I have even seen it getting blocked on Notes and just creating new notes all the time (I live in emacs and Ctrl-n is very common too). I will try to open an issue with them.

**Comment by abrookins** [comment]
Awesome. Great idea - I’ll try remapping that key!

**Comment by yury** [comment]
It is fixed in v12.4
Turns out we where grabbing focus while in background.

**Comment by dmitryzykov** [comment]
@carloscabanero 
Hi, have you created that above-mention issue in apple?
If that public can you send a link to it or if not tell apple reaction to that issue.
It seems that i having this issue with the latest ipad os 13.3

**Comment by peppy** [comment]
I am also seeing this with the latest iPadOS release and wondering if there's a radar paper trail or otherwise (obviously this isn't an issue specific to blink). I can't seem to find much talk about it online, even though it's a super annoying issue.

**Comment by peppy** [comment]
This has been fixed in iPadOS 14 Beta 1!!

**Comment by abrookins** [comment]
Are you sure? I’ve already encountered both long-standing keyboard bugs -
blank keyboard in Spotlight search and just hit the stuck Command key
button bug as well (but not in Blink).

**Comment by peppy** [comment]
@abrookins when you hit it, did you have a "pullover" style multitasking app present? that's one case i'm still seeing weird behaviour.
