### ISSUE TITLE
Backspace to generate ^? instead of ^H

### ISSUE THREAD

**Issue by zevlg** [blinksh/blink#479]
Many terminals have option for backspace key.  For example xterm has
```
XTerm*backarrowKey: false
```
to make backspace send `^?` instead of default `^H`

Iterm2 also has similar configuration option.  It would be nice to have on in blink as well

**Comment by yury** [comment]
@zevlg just for my education, what is use case for that mapping?

**Comment by zevlg** [comment]
This is the practical way to distinct `Ctrl-h` and `backspace` keypresses.

However, I rechecked and found that blink does send ^? on backspace!  I was in screen configuration which does remapping ^? to ^H

sorry for inconvenince

**Comment by yury** [comment]
Thank you, closing then...
