### ISSUE TITLE
Persistence in sessions when the connection is lost

### ISSUE THREAD

**Issue by izafnat** [blinksh/blink#481]
After having a connection for more than half a day and going through several networks, including the mobile network, when I disconnected, the old connection appears to persist.

For example:

![image](https://user-images.githubusercontent.com/38222310/38521675-00e7c62e-3c0c-11e8-9591-542966273a86.png)

**Comment by goerz** [comment]
running `killall mosh-server` on the host will get rid of the hanging processes. Still, this shouldn't happen in the first place.

**Comment by yury** [comment]
@izafnat did you kill blink with control center? 
Mosh sessions should be persisted even if you lost connection unless you kill blink.

**Comment by izafnat** [comment]
Only the connection was closed, and the blink prompt appeared again, but since yesterday at 10:00 PM I managed to persist the session until this hour without problems.

I do not have a control center as such for mosh, the server is a debian text mode.

**Comment by carloscabanero** [comment]
Not relevant now. Please reopen if necessary.
