### ISSUE TITLE
Alt+Shift as Blink hostkey problem

### ISSUE THREAD

**Issue by tpielok** [blinksh/blink#482]
Hi, I‘m working on an ipad with blink from the appstore.
I can only use Alt+Shift as Blink hostkey when Cmd ist assigned to None.
If I map Cmd to Ctrl, Alt+Shift stops working.

**Comment by yury** [comment]
Hmm, interesting...
I think it is related to #468 
But Cmd mapping should change anything...

**Comment by yury** [comment]
Should be ok in latest Blink versions.

Closing, feel free to reopen if need.
