### ISSUE TITLE
Underline attribute not regarded

### ISSUE THREAD

**Issue by zevlg** [blinksh/blink#488]
Cells with underline attribute renders without underscore
 
![6ed87f79-56c8-4b77-9494-33193cfded5b](https://user-images.githubusercontent.com/850077/39075895-e2c79b1c-4500-11e8-9d33-5a4c3013e02e.jpeg)

I’m actually very happy with this behaviour, but I suppose underlined text should be underscored by default

attrs.sh - https://gist.github.com/zevlg/ccb1b1bf60aa74d7995d86b7c6bac677

**Comment by yury** [comment]
@zevlg thanks again for feedback

Fixed.

![img_061b25225ae0-1](https://user-images.githubusercontent.com/5250/39082657-72603d02-455f-11e8-9be4-9910eac5aa39.jpeg)

In next version you will be able to tune underline with custom css.

```css
span.u {
   -webkit-text-decoration: none !important;
}
```

Also you will able to tune color of underline (ref #425):
```css
span.u {
   -webkit-text-decoration-color: red !important;
}

**Comment by yury** [comment]
What is interesting, is that hidden is shown :(
