### ISSUE TITLE
Ctrl+<digit> sends unmodified digit

### ISSUE THREAD

**Issue by zevlg** [blinksh/blink#489]
Ctrl in combination with digit sends unmodified digit.
If Ctrl is bound to Cmd then nothing is send at all

Many terminals send control chars according to next table:
```
Ctrl-2 -> ^@
Ctrl-3 -> ^[
Ctrl-4 -> ^\
Ctrl-5 -> ^]
Ctrl-6 -> ^^
Ctrl-7 -> ^_
Ctrl-8 -> ^?
```

It would be nice to have the same in blink

**Comment by yury** [comment]
@zevlg thanks!
Will be in next release.

**Comment by yury** [comment]
Should be in v11.0
