### ISSUE TITLE
crash on backspace after unicode character

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#49]
The app crashes when entering any non-ascii unicode character (e.g. an umlaut, or an emoji) at the `blink>` prompt, followed by a backspace/delete.

**Comment by carloscabanero** [comment]
This is related to https://github.com/mfikes/planck/issues/30 and https://github.com/antirez/linenoise/issues/25. I will figure out a solution so that it doesn't break for release, looks like UTF8 support is still in progress on linenoise. PT #122984391
