### ISSUE TITLE
List available shell commands in help

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#491]
I'm very excited to see #281 show up in the beta!

Since I've lost track of all the various commands Nicolas has added to `ios_system`, it might be good to just list all of them in `help` inside Blink.

**Comment by holzschu** [comment]
`curl, scp` and `sftp` are in `ios_system`. If they are not available as commands in the beta, that's an issue. That may be related to the app being stripped before shipping.

**Comment by yury** [comment]
`curl https://raw.githubusercontent.com/holzschu/ios_system/master/Resources/commandDictionary.plist | grep key` :)

**Comment by goerz** [comment]
@yury Awesome, thanks!

If only that command worked from *inside* Blink ;-)

Joking aside: `curl`, `scp`, an `sftp` are in that list, and they also tab-complete inside of Blink, but then pressing Enter give "command not found". It's the same for `ctags`, too (not that I'd find `ctags` overly useful inside Blink). Anything else I've tried works.

Since this seems to be a genuine bug, and separate from wanting a list of available commands, I'll open a separate issue.

**Comment by carloscabanero** [comment]
@goerz actually Yury is right, I just run that command Inside Blink! 😄 We are not limiting the commands in any way. The issues are more like scp not integrating hosts and things like that! I'm trying to think what may be going on...

**Comment by goerz** [comment]
@carloscabanero I'm confused by your comment. You ran @yury's `curl` command inside Blink and it didn't give you a "command not found"? Do you mean on your version directly compiled from XCode? In that case, the commands just got lost on the way to Testflight.
~~~
blink> curl https://raw.githubusercontent.com/holzschu/ios_system/master/Resources/commandDictionary.plist
curl: command not found
~~~

**Comment by holzschu** [comment]
Yes, see my reply in #494: commands added using `replaceCommand` (that's `curl`) do not work in TF, but they work in sideloaded versions.

**Comment by yury** [comment]
@goerz yep, turns out TF and dev versions are different :( Will try to fix that as @holzschu has suggested.

**Comment by yury** [comment]
`<tab>` will list all available commands.
