### ISSUE TITLE
Corrupted private keys

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#492]
Installation of the latest beta (I *think* from the previous beta, not the app store version), seems to have corrupted my private keys. This has happened before (#274). As a result, when I try to log in to a host, I'm being asked for my password. In Settings >Keys, there is an `id_rsa` listed, but tapping "Copy private key" crashes Blink.

Deleting the existing key and creating a new one solves the problem: I can log in with key-based authentication again, and "Copy private key" works. But of course, I'll have to update the `authorized_keys` on all hosts, so I wouldn't mind avoiding this in the future ;-)

**Comment by edgauthier** [comment]
I’m seeing the same issue.

**Comment by nielsk** [comment]
Same issue here…that will be some work to replace the key everywhere… -.-

**Comment by MacDragon** [comment]
Had this occur too, though I note that downgrading to appstore version and key worked again for me, so it was failing to read it correctly for some reason. Could it be due to switching between appstore and test flight versions and secure storage not being compatible or similar?

**Comment by jason-green-io** [comment]
I'm still getting this in 10.303. Also, trying to import a key from clipboard seems to default to creating a new key.

**Comment by yury** [comment]
Ok, found origin of an issue.

TF version accidentally have wrong keychain-access-group.
Should be fixed in next release.

**Comment by goerz** [comment]
So obviously the latest TF update  that fixes this issue (306) again breaks the keys that I created with the broken version 303 (because the keychain-asccess-group changed again).

I should have realized the first time that there's a workaround to move the same private key between the versions. If like me you have upgraded to 306 and find your keys not working:

- downgrade back to the pervious version 303 in Testflight
- export the private key to the clipboard, and maybe paste it somewhere temporary so it doesn't get lost accidentally (I use the Gladys clipboard manager)
- In Testflight, update to the latest version 306 again
- Delete all keys in Blink
- Import the private key from the clipboard/Gladys

This definitely beats having to set up new private keys everywhere (which gets especially annoying since most of my hosts are set up to only accept key-based authentication, so changing keys involves using another computer)

**Comment by yury** [comment]
Hi @goerz,
Sorry for my mistake, but it is good TF catch. 
Hope this never happen again.

**Comment by yury** [comment]
I think we can close this
