### ISSUE TITLE
feature request: pbcopy, pbpaste

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#495]
Once #494 is closed, I was wondering if it might be possible to add commands equivalent to `pbcopy` and `pbpaste` on the Mac. This feature request actually might more generally be for @holzschu's `ios_system`. 

For example, just now I wanted to create a gist from a file I have an a remote host. My imagined workflow would be to just open a new tab in Blink, scp the file to local storage, put it on the clipboard with `cat <filename> | pbcopy`, switch to the browser, and paste it there. This is actually pretty much what I'd do on a Macbook.

I'd hope that implementing this would be easy (otherwise I wouldn't even ask). A more advanced version would have ssh commands connect directly to local pipes (`ssh user@host cat <remotefile> | pbcopy`), but that seems very non-trivial.

Also, with all the amazing work that's happening on Blink these days, you should seriously consider #448

**Comment by goerz** [comment]
In the meantime, I'm working around this with the Files app and Gladys, which allows to copy an entire file to clipboard.

**Comment by yury** [comment]
Yep, I requested that commands [right a way](https://github.com/holzschu/ios_system/#35).

Nicolas already implemented them. 

Also, I thought [thead, tail](https://github.com/holzschu/ios_system/issues/37) and [sort, unique](https://github.com/holzschu/ios_system/issues/38)

**Comment by yury** [comment]
Hi @holzschu,

Do you plan to make 2.1 tag and build frameworks for download?

**Comment by holzschu** [comment]
Hi @yury, 
since these are small changes, I've updated the 2.0 release with the new commands.

**Comment by yury** [comment]
Hmm, got it. But it is hard to track how to update commands.plist

**Comment by holzschu** [comment]
Good point. I'll be more careful in the future. 
Note that you can always update commands.plist before ios_system is updated. If a command is defined in commandDictionary.plist but the dynamic library is not available, ios_system will just reply "command not found" (it will be a little more talkative if `sideLoading == false`).

**Comment by yury** [comment]
released!

**Comment by holzschu** [comment]
Well, no, because `$(command)` is not implemented. You might be able to run `pbpaste | ssh x some command`.
