### ISSUE TITLE
Shortcut for switching tabs

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#496]
Would it be possible to have the shortcuts `cmd-shift-]` and `cmd-shift-[` for switching tabs (the same shortcuts as e.g. in Safari)?

I'm actually a little confused, because somehow I thought that these shortcuts might have been there in the past, and disappeared recently? Because otherwise, it seems odd that I wouldn't have opened this feature request already a long time ago.

**Comment by goerz** [comment]
Never mind, the shortcut exists, but it's `cmd-]`, and `cmd-[`, as gets displayed when holding the cmd key. Has this changed recently? Maybe the version with shift could do the same, just for consistency with Safari?  The shortcut should also appear in the output of the `help` command.

Feel free to close if you want to stick to just `cmd-],[`

**Comment by yury** [comment]
Actually it works this way for a long time (may be from the start of that shortcuts). See similar issue #419.

I'm ok to change it to cmd+shift+[] by default. It should fix #419 too.

In general we need to find a way to set any shortucts to actions.

**Comment by sylvoie** [comment]
Hi,

I’m working on iPad Pro with an French Apple keyboard. The character « [ » and « ] » are accessible by option key (option+9 or option+0). I tried different combinations and shortcuts are’nt working.

In Safari, shortcuts are ctrl-tab and ctrl-shitf-tab to move between tabs.

Is-it possible to choose keys combinations for shortcuts? 

Thank’s

**Comment by yury** [comment]
@sylvoie we are working on new keyboard system, it should solve this.

**Comment by yury** [comment]
Hi @b00giZm,

New keyboard system will take some time. So any quick fix and PR is welcomed. 
PRs are always welcomed.
