### ISSUE TITLE
Scrolling inside of mosh not working correctly

### ISSUE THREAD

**Issue by sambadevi** [blinksh/blink#499]
I’m not sure if this is an actual problem with blink, but when I am connecting with mosh I can’t scroll correctly.

Steps to reproduce:
- Login with mosh
- enter some commands
- enter a command with a large output
- try to read the output, the screen will scroll just a tiny bit before your previous commands are visible (content from the large output gets cut off)

**Comment by yury** [comment]
Yep, this is limitation of mosh protocol.  You have to use tmux or screen to get scroll working

**Comment by sambadevi** [comment]
I am using mosh with tmux and still have the exact same issue. Is there any fix or config setting to avoid this?

**Comment by goerz** [comment]
I think @yury meant that you have to use tmux's own scrollback feature (`ctrl+b [`)

**Comment by sambadevi** [comment]
Ah I see, that's working for me!
