### ISSUE TITLE
Support for ALT+Arrows

### ISSUE THREAD

**Issue by rekendahl** [blinksh/blink#5]
I have TMUX configured to have ALT + UP/DOWN/LEFT/RIGHT arrows to be mapped to resizing my TMUX windows. (Seemingly) all other ALT combination works. Can you add support for ALT + Arrow Keys please?

**Comment by carloscabanero** [comment]
Could you please do a showkey -a in your normal setup and let me know what sequence you receive? I see that Xterm is actually sending something different than iTerm. These and function keys are actually sequences that should be customisable in settings, but I want to at least ship with something.

**Comment by rekendahl** [comment]
I don't know if this mapping works on Linux. I have never tried it. And on my Mac I don't have 'showkey'...

**Comment by carloscabanero** [comment]
And this is fixed my friend!! Please let me know how it works, it should also allow for special combos like Shift+Ctrl+Alt and what not :)
