### ISSUE TITLE
IOS App Always Frozen, No Reaction

### ISSUE THREAD

**Issue by zhaohui0923** [blinksh/blink#501]
![img_1348](https://user-images.githubusercontent.com/39145884/39852829-4d9a3f62-5451-11e8-9da9-0a8eca413033.png)

Hardware: Ipad pro 10.5, Smartkeyboard
Software: ios 11.3, Ubuntu 18.04

When use vim in blinksh, some part of the app shows a blue rectangle area, and the app got fozen without any reaction.

I've tried a lot. When I turn off "ale linter",  everything is ok, But when I turn it on and edit some cpp files, blinksh got fozen frequently.

below is my ale config part in .vimrc

----------
 let g:ale_cpp_clang_executable = "/usr/bin/clang++-6.0"
 let g:ale_cpp_clangcheck_executable = "/usr/bin/clang-check-6.0"
 let g:ale_cpp_clangtidy_executable = "/usr/bin/clang-tidy-6.0" 
 let g:ale_open_list = 1
----------

**Comment by yury** [comment]
Hi @zhaohui0923,

Thank you for feedback.
It seems to be memory leak in JS renderer. It is hard to setup all things the same as your env.  Good news that we have new renderer in next version and I think it will cover your case.
Can we invite you to TestFlight to ensure that this issue is gone?

**Comment by zhaohui0923** [comment]
@yury I'm glad to join the TestFlight.
My email is 295493195@qq.com.

**Comment by yury** [comment]
Hi @zhaohui0923, you should be invited to TF now. Waiting for feedback.

**Comment by yury** [comment]
@zhaohui0923 can you record video? It would help a lot.

**Comment by yury** [comment]
I will close that issue, feel free to reopen.
