### ISSUE TITLE
Microsoft Word (docx) files are incorrectly associated with Blink

### ISSUE THREAD

**Issue by ericnchen** [blinksh/blink#502]
**Hardware/Software**
- iPad (2018)
- iOS 11.3.1
- Blink 10.306 (2)

**Description**
Opening a ``docx`` file (e.g., from Files) without Word installed launches Blink. When Word is installed the ``docx`` file opens up in Word normally.

**Reproduce**
Delete the Word app and try to open a ``docx`` file from Files.

I see no reason at all why a ``docx`` file should ever launch Blink so I think this is a bug with file extension association?

**Comment by yury** [comment]
We released 11.26 with the fix.

**Comment by yury** [comment]
We don't have any file association in blink now.
Closing this issue.

Thank you!
