### ISSUE TITLE
Cmd + h returns to home screen after mapping to Ctrl

### ISSUE THREAD

**Issue by harryleesan** [blinksh/blink#506]
Hi,

I have mapped `Cmd` to `Ctrl` in the keyboard config, however, `Cmd + h` (which should be `Ctrl + h`) takes me to the home screen. 

I am using an external keyboard (Apple Magic Keyboard). On-screen keyboard does not have this issue.

**Comment by Harwood** [comment]
`Cmd + h` is a system level shortcut that takes precedence over app level configurations.

**Comment by harryleesan** [comment]
So there is no way around it then... thanks! Closing issue.
