### ISSUE TITLE
Try to authenticate with all available keys

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#51]
It appear that Blink will use key-based authentication only if this is requested explicitly with the `-i` options for SSH, respectively `-I` for mosh. This is different from how mosh/ssh work on my laptop, where it tries all available keys for authentication when ssh/mosh is invoked without options. Blink should either behave in the same way, or document the need to use `-i`/`-I` explicitly.

Also, it would seem feasible to add an option the the Key configuration for setting a "default" key, or "try all keys". In addition, or alternatively, a Hosts section in the config (to be implemented) could associate specific keys with specific hosts.

**Comment by goerz** [comment]
Duplicate of #36?

**Comment by carloscabanero** [comment]
Yup, lets continue the discussion there.
