### ISSUE TITLE
Menlo font has ligature problems

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#511]
When using the menlo font, it uses undesriable ligatures, e.g. for "fi". This causes the rendering to break:

![917d6a59-ceca-4083-b4f4-bad9659a3472](https://user-images.githubusercontent.com/112306/40563212-fd85dba2-6031-11e8-8c41-65d2ae2d18bf.png)

I've also had the ligatures actually be inserted into the actual files, which is even worse, because the code stopped running ;-)

**Comment by yury** [comment]
Hi @goerz,

We just release 11.0 and it should be ok. 

Feel free to reopen if you find any issues with that.
