### ISSUE TITLE
Multiple spaces inbetween command and arguments

### ISSUE THREAD

**Issue by zevlg** [blinksh/blink#513]
In latest TF version I’ve got next problem:  if I insert multple spaces between `ssh` command and hostname blink will raise error, such as:

```
blink> ssh   wrk
Could not connect to host: ssh: connect to host  port 22: Operation not permitted
```

With mosh I get next:

```
blink> mosh    wrk
Could not connect to host: ssh: connect to host  port 22: Operation not permitted
Did not find remote IP address
```

if single space is inserted inbetween command and hostname, then ssh/mosh works well

**Comment by yury** [comment]
v11.0 is out with the fix. Thank you.
