### ISSUE TITLE
echo on mode in Blink shell

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#515]
Currently, the Blink shell has echo off when typing standard input.

## Steps to reproduce

1. Open a new window.
2. Run `cat > testfile`
3. Type some arbitrary text, press return, then ⌃D.
4. Run `cat testfile`

## Expected results:

```
blink> cat > testfile
this is a test
^D
blink> cat testfile
this is a test
blink> 
```

## Actual results:

```
blink> cat > testfile
blink> cat testfile
this is a test
blink> 
```

**Comment by yury** [comment]
Yep, it will be greate.

**Comment by yury** [comment]
Status update
https://youtu.be/0lkLCyzPKnQ

**Comment by yury** [comment]
Pushed Blink 13 build 152 to TF with a fix.

**Comment by yury** [comment]
Blink 13 is out.
