### ISSUE TITLE
Feature request: interactive editor

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#516]
Right now, `awk` and `sed` are provided, but there doesn't appear to be ann interactive editor. BusyBox provides `vi` and `ed`, and `ex` is another very small interactive editor (`ed` and/or `ex` might be easier to implement since they are line-oriented rather than full-screen visual).

**Comment by goerz** [comment]
I think the intended workflow for now is to use the `open` command to open files in-place in iVim

**Comment by bradleyjones** [comment]
It would be nice if we could provide some user defined aliases so rather than ‘open filename’ & click on iVim, we could just do ‘vim filename’. That may make it slightly friendlier.

**Comment by vorband** [comment]
although I remember it working correctly using the „open in vim“, currently changes in vim are no longer reflected in the file in blink (TF v12.3.70) 
Hence I would like to support this feature request for native vim support in blink. :)

**Comment by yury** [comment]
`ed ` will be in next release.
https://youtu.be/0lkLCyzPKnQ

**Comment by daonb** [comment]
Great :beer: 

I’m splitting hairs here, but why not ex? Is it related to [Ed, man! !man ed](https://www.gnu.org/fun/jokes/ed-msg.html) ?

**Comment by carloscabanero** [comment]
Closing here. Added Vim on 17.3.0 https://github.com/blinksh/blink/discussions/1515
