### ISSUE TITLE
Would like option to generate Esc *by itself*

### ISSUE THREAD

**Issue by anahata0108** [blinksh/blink#520]
With many of the apps that I want to use in Blink (e.g. vi), being able to type *just* Esc would be very handy. I have tried the various `foo as Esc` options, but none of them actually generate Esc when I type the key by itself. I'm using an Apple Smart Keyboard on a 10.5" iPad Pro with iOS 11.4, if it matters (though it's never worked in any version of iOS or version of Blink). Am I missing something, or is this just not supported?

**Comment by yury** [comment]
Hi @masochist,

Please try the following settings:

![eb59e2b1-d71e-4d0c-9dec-595e7540810c](https://user-images.githubusercontent.com/5250/40888934-4de3839c-6767-11e8-96ea-e3887d4d75ed.jpeg)

`Caps as Esc` actually maps `Caps Lock` to just `Esc`.

**Comment by masochist** [comment]
Ah, the one setting I didn’t try because I’ve always used Caps Lock as Ctrl for about 10 years now… :) Is it possible to add something like “Alt as Esc” as well, for those of us who prefer Caps Lock as Ctrl?

**Comment by yury** [comment]
Hmm, only `Shift as Esc` will aslo work for now :(

**Comment by masochist** [comment]
How can I meaningfully use that, though? I tried it and it took over both Shift keys, which is pretty important. What’s the use case for that feature? I realise this is getting off topic for the original ticket.

**Comment by yury** [comment]
I don't find it useful too, but emacs-ers use it some home :)

I just checked, we can implement `Alt as Esc` too, but it will work only as singe key, all alt+<key> combos will be captured by `Alt as Esc`. Will this solution work for you?

Also, I need to /cc @carloscabanero  here :)

**Comment by masochist** [comment]
I think that would be useful for me, what I’m basically trying to get is the functionality I have with iTerm on my Mac. Thank you for looking into this!

**Comment by javanut13** [comment]
In case you (or anyone else) aren't aware, `C-[` (control + `[`) sends an escape, which is handy if you're using Vim though Blink with a Smart Keyboard case.

**Comment by masochist** [comment]
I am aware of that, yes. I was just hoping for a single keystroke like I’m used to on my Mac / other machines.

**Comment by spangenberg** [comment]
Having `Alt as Esc` could be handy indeed, none of the configurations work for me either so far.
I was also thinking what about allowing the ` key as Esc, since on the Apple official keyboards that‘s where Esc should be. And if I need to type ` I have to do some nonsense like Option + `
Sure seems complicated but so do all the other options.

**Comment by carloscabanero** [comment]
The shift or Caps as Escape should still work. They take a little bit to respond because usually iOS is waiting to see if there is any other key pressed, but after half a second they should send an escape. We will keep this in mind as we go.
