### ISSUE TITLE
Mosh vim unresponsive after alt-tabbing on iPad Pro

### ISSUE THREAD

**Issue by geoyws** [blinksh/blink#521]
When alt-tabbing quickly, mosh vim becomes unresponsive. Happened twice. Trying to confirm if it’s not Blink’s fault by running tests.

**Comment by yury** [comment]
It may be that cmd key is “stuck”. 
Try to press just cmd or switch language when it happen again.

**Comment by geoyws** [comment]
Alright will let you know if it happens again. Things seem to be fine now. Will try the cmd key etc.

**Comment by geoyws** [comment]
@yury You’re right, apparently the cmd key was stuck!

**Comment by yury** [comment]
Ok, just leave a note that it is dup of #476
