### ISSUE TITLE
New control panel proposal

### ISSUE THREAD

**Issue by yury** [blinksh/blink#523]
No one (except me) uses music player controls (#441 and from feedback from discord). iOS 12 introduced same as iPhone gesture for iOS Control Centre and now it is really easy to control music.

I was thinking what would be useful and came up with 2 features we can add to our control panel instead of music controls.

- plus button for new session.
- lock terminal size button (will reduce resized in split mode)

<img width="360" alt="screen shot 2018-06-05 at 1 55 45 pm" src="https://user-images.githubusercontent.com/5250/40972069-37a73a30-68c8-11e8-90d3-469a1dcd1dea.png">

But then I was thinking that we can do even more with long presses/force touches.

- long press button - will open new terminal with same ssh/mosh connection (copy current session)
- long press on paste button - will show quick pasteboard (can be useful with software keyboard)

<img width="547" alt="screen shot 2018-06-05 at 1 56 36 pm" src="https://user-images.githubusercontent.com/5250/40972090-4f3623b4-68c8-11e8-90a7-be5b537739f8.png">

Feedback is needed :)

**Comment by s8m2s** [comment]
Definitly more relevant funtion than the audio controls. 

I Like the idea of being able to lock the terminal size. I’m assuming that would alow you to scroll?

Is the past long press a history or a way to assign a shortcut to snippits?

**Comment by yury** [comment]
Good idea for snippets shortcuts...

**Comment by goerz** [comment]
How about showing thumbnail views of all the open tabs in that space, as a switcher? This would be in addition to a small row of buttons at the bottom, from @yury’s proposed screenshot.

I’d actually also love to see the thumbnails while switching between tabs with the swipe or shortcut

**Comment by superstructor** [comment]
The long press options (copy current session / pasteboard) would be very useful for me 👍

**Comment by yury** [comment]
Closing, since we will honor 3 finger tap
