### ISSUE TITLE
ssh-copy-id not working (testflight version)

### ISSUE THREAD

**Issue by bradleyjones** [blinksh/blink#525]
Blink: v10.329.1. May 29 2018

Trying to use ssh-copy-id I’ve noticed 2 problems:

1. ssh-copy-id on to a box not previously connected to:
![e51dc1b5-6fc6-4aea-bac5-3a9cf3ff42c1](https://user-images.githubusercontent.com/2159185/41042873-a112a91e-699a-11e8-8884-67a52194a739.png)
Freezes the application as it seems to print [yes/no] forever

2. ssh-copy-id to a previously connected box it skips past the enter password field (does not give the option to input text and says connection failed)
![b1cd414c-3c5f-4073-9eb2-5acd67282b91](https://user-images.githubusercontent.com/2159185/41043248-6863eda2-699b-11e8-8d07-ac957d184880.jpeg)

**Comment by yury** [comment]
Hi @bradleyjones,

Thank you for your feedback. We will try to fix that to our 11.1 fix release.

**Comment by yury** [comment]
Hi @bradleyjones, we pushed new version to TF with the fix.
