### ISSUE TITLE
How possible would it be to get a copy of krypton running in blink?

### ISSUE THREAD

**Issue by chrisportela** [blinksh/blink#526]
Krypton is a tool which moves all your SSH authentication to your phone and into it's Secure Enclave. I've been using this for talking to servers on my Pixelbook via it's recent Linux Container support and on my Macbook at work.

Blink seems to support almost everything needed to make this work except the `kr` command itself being installed. It's open source and written in Go (static) so I'm curious how "hard" is adding `kr` compared to adding all the recent Unix commands we added and would Blink be interested in doing this (i.e. If it's something Blink is willing to add and support)?

**Comment by yury** [comment]
It is interesting,

Just leave links here:

https://github.com/kryptco/kr
https://github.com/kryptco/krypton-ios

**Comment by Pyrepenol** [comment]
Would love to see this, but I'd be worried it be a security issue having both a compatible terminal and the krypton auth app on the same device. Someone smarter than me would know better about that.

**Comment by carloscabanero** [comment]
Closing. Krypton never caught up, but it was a great idea, maybe too early?
