### ISSUE TITLE
Suggestion: Blink should save state after users close the application

### ISSUE THREAD

**Issue by geoyws** [blinksh/blink#528]
This is so that in case the machine gets restarted or if your kids close the application, your Mosh session will still be alive, along with your other open terminals etc.

**Comment by elliot-wood** [comment]
Do you mean when Blink is closed by sliding up it’s “card” on the app switcher?

I’d definitely +1 this, since I find that too easy to do on the iPad accidentally. However, I’m not entirely sure it would be possible. It’d depend on how Blink handles mosh state.

**Comment by yury** [comment]
Just note:

Currently blink session restoration is based on iOS app restoration mechanizm. iOS drops app state snapshot if user kills app (swiping up app from in app switcher).

**Comment by ChaiTRex** [comment]
Blink should be able to record to disk the basic parameters of its connections when those connections are made (except perhaps for the SSH key passphrases which would need reentry) and then restore the connections from that disk record when the app is started again after killing it.

**Comment by carloscabanero** [comment]
This has been now pretty good over the years. Even updating iOS won't kill your mosh session. Closing.
