### ISSUE TITLE
arrow-keys not working inside curses apps

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#53]
I'm observing a strange effect of the up- and down-arrow keys not working in certain curses apps. This is true both for the arrow keys on an Apple Smart Keyboard, as well as for the on-screen software keyboard. The arrow keys work fine in the (remote) shell, and they also work inside of vim. They do not work, however, for at least some "curses" apps, e.g. `htop`, `mc`, and `ncdu`. The keys do something, (e.g. in `htop`, both the up and the down arrow increase the niceness value), just not the right thing.

The behavior is the same when connecting via mosh or ssh. I have tried this on several different servers. When connecting via ssh from my laptop and starting any of the programs, the arrow keys work fine.

**Comment by carloscabanero** [comment]
Good catch! Didn't know about this one although I experienced it in less and just attributed it to some configuration gaps. Looks like a bug on the terminal app mode. PT #122990701.

**Comment by carloscabanero** [comment]
This should be fixed on v0.916. Please let me know & feel free to reopen! :)
