### ISSUE TITLE
Auto Lock Crashes Blink

### ISSUE THREAD

**Issue by scruffydan** [blinksh/blink#531]
I recently decided to reset my iphone x and restore from a backup. Once the restore had finished I noticed Blink would crash and send me back to the springboard on launch. I deleted the app and re-installed it, and started setting up from scratch. It worked. Until I decided to enable the Auto Lock feature (a must for me since I leave my Mosh session open in the app). As soon as I turned on Auto Lock the app would crash on launch or when switching to it from the multi-tasking menu.  The only way to get back into the app at that point was to delete it and re-download it from the app store.

I am running an iPhone X on iOS 11.4 using the latest version of Blink recently downloaded from the app store.

**EDIT:** I should add that Auto Lock was working without issues before I reset my phone.

**Comment by yury** [comment]
Hi @scruffydan,

Thank you for your feedback.
Should be fixed in next release.

**Comment by yury** [comment]
We released 11.26 with the fix.

**Comment by scruffydan** [comment]
I confirm it works.

Thanks!

**Comment by jbeker** [comment]
I just compiled from `master` and I am seeing this exact behavior again. Enabled auto-lock. After first time switching away from app and coming back it crashes immediately. Only solution is deleting and reinstalling the app.

**Comment by yury** [comment]
@jbeker fix in 11-stable and in raw branches. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jbeker** [comment]
@yury thanks. I will try it out. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
