### ISSUE TITLE
Can only SSH Login First Time with Blink to new Server

### ISSUE THREAD

**Issue by devpixde** [blinksh/blink#532]
I have a new Ubuntu linode server. Using blink on iPad i can only Login once. After First Login and Logout i can't Login any more. Message: Authentication by password failed. Login on Terminal on Mac is no Problem though. New Shell does Not help.
When i setup another brand new linode Server its the same again: Login is only possible the First Time.
Not sure if this is a bug or a userproblem.

==============================

May be i found the reason:
I allways reselected the command with the up key.
ssh user@xxx.xxx.xxx.xxx

After i typed each letter of the command again it worked. This is very strange because there is no visible difference and what is even more wired: I now can even login when i select the older commands with the up can which did not allow login before.

**Comment by carloscabanero** [comment]
This was fixed a long long time ago. It was actually an issue with the text input. It would look the same to the terminal but not when parsing the command.
