### ISSUE TITLE
Using ^L to clear the screen in Blink’s built-in shell temporarily changes the terminal’s linefeed handling

### ISSUE THREAD

**Issue by myount** [blinksh/blink#536]
Clearing the screen using ^L while using Blink’s built-in shell causes the terminal to treat LF as only LF and not CRLF until the next command prompt is printed:

![b08cc061-188b-4821-ba6e-539d88cf5c00](https://user-images.githubusercontent.com/637064/42420806-973b58ba-8299-11e8-8d79-40c77873ccea.gif)

This only happens when using ^L to clear the screen; it doesn’t happen with the `clear` command.  It also doesn’t seem to affect subsequent ssh or mosh sessions (presumably because those reconfigure the terminal themselves).

**Comment by yury** [comment]
Hi @myount.

Thank you for bug report. Will be fixed in next release.
