### ISSUE TITLE
Support for 2FA using YubiKey OTP over NFC

### ISSUE THREAD

**Issue by Harwood** [blinksh/blink#539]
Yubico recently released an SDK that could be a nice feature add, perhaps in conjunction w/ key forwarding #248.

https://www.yubico.com/2018/05/yubikey-comes-to-iphone-with-mobile-sdk-for-ios-and-lastpass-support/

**Comment by catomann** [comment]
Any traction on this?

**Comment by pasuder** [comment]
As per following doc https://developers.yubico.com/SSH/Securing_SSH_with_FIDO2.html OpenSSH 8.2p1 supports keys bound with Yubikey using FIDO2. Would be that possible to use with blink? 😃

**Comment by carloscabanero** [comment]
This will be our way to go https://twitter.com/BlinkShell/status/1570427813819486212?s=20&t=UoLIPGrXWsQiTw2lZrhgqA

Related to #635 

Closing here
