### ISSUE TITLE
Cannot Mosh by Alias 

### ISSUE THREAD

**Issue by SeattleRex** [blinksh/blink#542]
I have the latest App Store version of Blink on an iPad Pro, iOS 11.4.1.

I can ssh to my remote hosts (via hostname, IP, or alias), I can mosh by IP address, but I cannot mosh to them via configured alias.  When I try to, it gives me the following output:

-----

zsh:1: command not found: [IP address of remote host]
Did not find remote IP address

-----

In my host configs, the 'hostnames' are IP addresses, and not hostnames, so there should be no DNS resolution taking place.

FWIW, I have a Linksys 1900ACS and IPv6 is disabled.

Just in case, I nuked the .zshrc files on the remote servers in case something was wonky upon connect.

Not a big deal, I just mosh via IP now, I'm just reporting it in the event it provides a clue to some other problem.

Thanks.

P.S. By "configured alias", I mean the string that is in the "Host" field in the host configuration section.

**Comment by pierot** [comment]
I have the exact same behaviour.

**Comment by achimnol** [comment]
I just encountered the same behavior, both for ssh and mosh.
It had been worked well until a few days ago, and I did not change any configuration.

**Comment by carloscabanero** [comment]
Closing. Does not apply anymore and it should work with no issue.
