### ISSUE TITLE
Switch screen location between iPad screen and HDMI secondary screen

### ISSUE THREAD

**Issue by dirv** [blinksh/blink#544]
When I connect my projector to my iPad, Blink opens a new screen, leaving my existing Blink screen on the iPad. I would like to be able to use my existing Blink screen on the projector, but there’s no way to switch to that screen in Blink.

This is a bit frustrating as I use tmux within a mosh connection. What I have to do at the moment is close the existing screen and then do “mosh <machineId> -- tmux attach” which is fine but it’d be great if I could just switch around the screens instead.

**Comment by yury** [comment]
Yep, good catch. There is cmd+shift+o shortcut to move session to other screen. But it doesn't work right now. Will fix.

**Comment by dirv** [comment]
Great news, thanks!
