### ISSUE TITLE
Avoid default key combination for home/end, page up/page down?

### ISSUE THREAD

**Issue by martinweiss** [blinksh/blink#545]
I use a HHKB Pro2 with my iPad. I am used to the mapping of the keyboard (Fn+...). That is, I'd like to use the standard Home/End, Page Up/Page Down, instead of Ctrl+arrows...

Is this possible?

**Comment by yury** [comment]
Can you run showkey command, type your combos and paste result here?

**Comment by martinweiss** [comment]
Funny thing is that Home/End/Page Up/Page Down also doesn't work on my Realforce 104...

And delete also seems not to work.

**Comment by yury** [comment]
Does any fn combo works in other apps? Seems ios doesn’t recognize them.

**Comment by martinweiss** [comment]
It seems like they don't. I guess that explains it then. Thanks for responding.

**Comment by yury** [comment]
NP, sorry for that issue. iOS behaves a little bit on it’s own.

**Comment by martinweiss** [comment]
Indeed. No matter what, I still really like Blink so far. Great job :)
