### ISSUE TITLE
Split screen of two terminal sessions?

### ISSUE THREAD

**Issue by Bowiemb** [blinksh/blink#547]
Is there anyway to have a split screen of two terminal sessions?

Thank you. 

My best,
Michael

**Comment by yury** [comment]
Hi Michael, currently we don't support that :(

You can use tmux or screen for now.

**Comment by ekloster** [comment]
Tmux works within the same system, but would love to see this as a feature to have sessions side by side to multiple systems.

**Comment by yury** [comment]
That is on the list :) stay tuned

**Comment by yury** [comment]
little status update
![IMG_0074](https://user-images.githubusercontent.com/5250/57681933-6028a280-7639-11e9-9d85-dd7e0994df20.PNG)

**Comment by jzellis** [comment]
If I understood correctly, iPadOS will allow you to split screen multiple instances of the same app. If so, that would solve this problem, right? I use tmux on my servers but I'd really prefer native iTerm-style pane splitting, just because I constantly forget the keyboard shortcuts for tmux.

**Comment by NightMachinary** [comment]
I think it still needs to be implemented by the app though.

**Comment by yury** [comment]
I think you will be able drag out panes to different windows and put them back. But yes, app should have panes.

**Comment by carloscabanero** [comment]
Based on how iOS has evolved, we won't be doing this. Implementing a window manager from our side isn't worth the time. Feel free to reopen as an Idea on Suggestions and if it gets some traction, we could reconsider based on use cases.
