### ISSUE TITLE
How to delete host?

### ISSUE THREAD

**Issue by M-M-M-M** [blinksh/blink#549]
When I start config, I didn’t find a way to delete an host. I got some conflicts with iCloud synchronization and even with save from iCloud or from local this is not doing anything: duplicates remains...

**Comment by yury** [comment]
Hi @M-M-M-M, 
With swipe from right to left on hosts screen you should be able to delete hosts.

**Comment by M-M-M-M** [comment]
Thank you @yury 

I have deleted host entry from my 3 devices. 

Then I have created with same name on one of the device but it still displayed with a conflict and I cannot resolve it.

**Comment by yury** [comment]
This should be fixed in latest version. Closing, feel free to reopen if needed.
