### ISSUE TITLE
Occasional unpainted pixels

### ISSUE THREAD

**Issue by fffergal** [blinksh/blink#55]
When scrolling around in vim I sometimes get this vertical line of pixels not painted in the background colour. I remember it happening more when scrolling up. 
![image](https://cloud.githubusercontent.com/assets/148789/16425113/e9e9db9e-3d5a-11e6-88ae-467bb1669587.png)

**Comment by carloscabanero** [comment]
I already saw this one and think I might have solved it already. Will wait for next version. 
PT #123424451

**Comment by yury** [comment]
I think this can be closed
