### ISSUE TITLE
mosh can't connect if ssh port not 22

### ISSUE THREAD

**Issue by lev-kusanagi** [blinksh/blink#551]
mosh --ssh="ssh -p 12345" doesn't work.

Thanks!

**Comment by lev-kusanagi** [comment]
neither does -P 1234

**Comment by yury** [comment]
Hi @lev-kusanagi 

Use `-P` parameter to specify ssh port.

`mosh -P 12345 ...1st`

**Comment by lev-kusanagi** [comment]
Thanks, sorry I thought that didn't work, but it does.
