### ISSUE TITLE
broken colors in remote tmux

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#552]
In the newest 12.0 beta build, I'm seeing broken colors, inside a tmux session only:
![b344c272-db0e-47cd-aea2-fbba9bb750fb](https://user-images.githubusercontent.com/112306/45268016-b9a25700-b444-11e8-9b72-6707c94a6553.png)

The value of `$TERM` inside tmux is `screen-256color`.

outside of tmux, things look normal:
![3f5e8d08-64fb-4eff-a6e1-6f933e53d475](https://user-images.githubusercontent.com/112306/45268018-c7f07300-b444-11e8-84e9-e2ef52eeff44.png)

The value of `$TERM` is `xterm`

This worked fine in previous versions of blink (including the current app-store version).

**Comment by yury** [comment]
Hi @goerz 

Very good catch. I have `export TERM=screen-256color` in my `.zshrc`, so I didn't noticed that issue.

Next TF version will be with the fix.

**Comment by goerz** [comment]
Looks good in current TF! Feel free to close.
