### ISSUE TITLE
[Feature request] x-callback-url api and shortcuts

### ISSUE THREAD

**Issue by drewcassidy** [blinksh/blink#553]
With the addition of Siri Shortcuts and the Shortcuts app to iOS it would be useful to have an x-callback-url api for running commands, for example to test connection to a server or open a new mosh/ssh connection. The callbacks can be performed by Apple’s own shortcuts app, or from other apps with that functionality like PCalc

**Comment by SteffenDE** [comment]
I‘d love to see a Shortcuts integration. While there already is a native way to run an SSH script, there is no way to authenticate using SSH keys. So having a „Run Script via SSH“ using Blink would be a very nice feature!

**Comment by drewcassidy** [comment]
yup, and possibly keep an interactive session open after running the script

**Comment by NightMachinary** [comment]
It’s also useful for emergencies; I can just say “blink fire” and it’ll start the appropriate script to deal with it. It’ll also be very useful if Blink could feed location to the script.

**Comment by MidnightRocket** [comment]
Hi, I am a bit confused. It seems this feature was implemented in 12.8. And in version 13.3 the configuration for x-callback-url appears in the config menu. But I can not seem to get it to work. When I make a call on "blinkshell://run?key=SECRET&cmd=ls" nothing happens, except blink opened. No command is executed. 
I would really appreciate some clarification as to whether or not this feature is fully implemented.

**Comment by yury** [comment]
We disabled it for now. Will restore soon.

**Comment by tomminux** [comment]
> We disabled it for now. Will restore soon.

Any precision on “when”?

**Comment by idagroup** [comment]
I'm anxious to see this return as well. We could finally use Blink in conjunction with RoyalTS

**Comment by javierdemartin** [comment]
x-callback-url has been re-added to the codebase (#1061) it'll be available in the coming future (can't exactly tell when). Will be working on adding Shortcuts integration in the future :)

**Comment by ventz** [comment]
@javierdemartin @yury could you push it to TestFlight?

**Comment by javierdemartin** [comment]
We can’t give you an estimate right now because of some other ongoing work. Possibly in the coming weeks, I’ll ping you once it’s up.

**Comment by ventz** [comment]
Thanks!!

**Comment by javierdemartin** [comment]
@ventz Current App Store Version 13.5.5 restores this

**Comment by ventz** [comment]
@javierdemartin Thanks. Tested it as soon as I saw it push to TestFlight (works! :))
It's fantastic for Siri Shortcuts automation and being able to execute commands.
