### ISSUE TITLE
Does Blink from App Store support python?

### ISSUE THREAD

**Issue by frodeaa** [blinksh/blink#555]
I have tried to follow the instruction from https://github.com/blinksh/blink#packages
but no success

I was looking to install ```awscli``` into blink, is that possible?

**Comment by yury** [comment]
Hi @frodeaa,

No, app from App Store doesn't support python yet. You have to build it from [Nicolas fork](https://github.com/holzschu/blink)

**Comment by frodeaa** [comment]
ok, thanks

**Comment by daftano** [comment]
@yury Is that still current?

**Comment by jjarava** [comment]
Is this still the case? Need to rebuild and install?

Any hope for a change in the near future or should I look into getting a developer cert etc...

**Comment by goerz** [comment]
If you do add Python support, I'd strongly prefer Python 3 over Python 2 (although I known that @holzschu wants Python 2 for mercurial).

**Comment by jjarava** [comment]
If python support is added to the “out of the box” (ie AppStore) version, I’d also somewhat prefer 3, but 2.7 is also better for me than having to compile and “side load” :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by daftano** [comment]
why not both? 😋
I am looking for Python 3. If feasible to add both would be excellent as well as possibly a lot of extra work. So having to choose I'll second python3.

**Comment by holzschu** [comment]
So, to answer a few of the questions : 
- there is already an app on the AppStore that does Python3 (Pythonista). I understand that it's not as good as having python3 inside blink, but it's still a good alternative.
- I originally couldn't make python3 and python2 run together in ios_system because all commands and variables were living in the same memory space. It could be worth re-testing now that we have frameworks.

**Comment by jjarava** [comment]
I’d like to give a **+1** to Pythonista, it’s a great app. 

In the topic of efforts, _personally_ I believe it’d be more impactful to sort things so as the “App Store” version could ship with `python` and `lua` (having both would be unique AFAIK) than trying to shoehorn both 2.7 and 3 at the same time.

**Comment by daftano** [comment]
@holzschu I would focus any effort in adding Python 3, instead of delivering both versions.

Personally speaking only version 3 is relevant for me (and I'm upgrading inherited projects to 3 as well)

**Comment by ColdGrub1384** [comment]
@jjarava For Lua, I made an app: https://develobile.com/luade/

**Comment by holzschu** [comment]
So, https://github.com/holzschu/python3_ios appears to be working (with `subprocess`, too).
Since we're now using frameworks, it even coexists peacefully with python2, which is great. 
The only bad news is it needs OpenSSL 1.1. Available to all sideloaders.

**Comment by wolterlw** [comment]
any updates on Python support?
can those of us without a Mac use this feature?
