### ISSUE TITLE
scp failes with curl authentication failure error

### ISSUE THREAD

**Issue by goura** [blinksh/blink#556]
Hi,
I'm trying to `scp` to one of my servers using the command args format
`scp example.json user@host:example.json`,
but I get `curl: (67) Authentication failure`.

I have public key authentication setup and can ssh into that host without passwords from Blink.

I'm using the App Store version.

**Comment by goura** [comment]
Supplied -v to scp and it seems like it passed it to curl.
I have a default key set by Blink `config` (id_rsa) but it seems like that key is not used.

(Personal information masked)
```
blink> scp -v example.json example.jp:aaa.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying XXX.YY.ZZ.40...
* TCP_NODELAY set
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to example.jp (XXX.YY.ZZ.40) port 22 (#0)
* SSH MD5 fingerprint: fffffae6f33a6d5bbd1f1091ffffffff
* SSH host check: 0, key: AAAAB3NzaC1yc2EAAAADAQABAAABAQDV8sqzh3iJV9S3l0
.....
qK7qtCQpDOZ7lBNFQuuHBZ4Jg603hwDAycSePD925k47ZXboFUB
* SSH authentication methods available: publickey,password
* Using SSH private key file ''
* SSH public key authentication failed: Unable to extract public key from private key file: Unable to open private key file
* Failure connecting to agent
* Authentication failure
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (67) Authentication failure
blink> 
```

**Comment by yury** [comment]
Hi @goura,

Can you try to add example.jp as a host in config and specify key for that host in config?

**Comment by goura** [comment]
Hi @yury, 
I added example.jp as a host in config, and explicitly set it to use `id_rsa`, restarted Blink, but still getting no luck. Having the same error and getting the same log as:
> * Using SSH private key file ''

**Comment by yury** [comment]
Hi @goura,

Are you sure that you press 'Save' on the host configuration when you set key?
I'm able to copy with this syntax:

`scp example.json example.js:~/aaa.json`

**Comment by NyaMisty** [comment]
So why don't close the issue if your problem is solved? ;)

**Comment by goura** [comment]
@NyaMisty Let me try closing it then 👍

**Comment by huos3203** [comment]
> Supplied -v to scp and it seems like it passed it to curl.
> I have a default key set by Blink `config` (id_rsa) but it seems like that key is not used.
> 
> (Personal information masked)
> 
> ```
> blink> scp -v example.json example.jp:aaa.json
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying XXX.YY.ZZ.40...
> * TCP_NODELAY set
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to example.jp (XXX.YY.ZZ.40) port 22 (#0)
> * SSH MD5 fingerprint: fffffae6f33a6d5bbd1f1091ffffffff
> * SSH host check: 0, key: AAAAB3NzaC1yc2EAAAADAQABAAABAQDV8sqzh3iJV9S3l0
> .....
> qK7qtCQpDOZ7lBNFQuuHBZ4Jg603hwDAycSePD925k47ZXboFUB
> * SSH authentication methods available: publickey,password
> * Using SSH private key file ''
> * SSH public key authentication failed: Unable to extract public key from private key file: Unable to open private key file
> * Failure connecting to agent
> * Authentication failure
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> * Closing connection 0
> curl: (67) Authentication failure
> blink> 
> ```
i use `scp demo.txt hostname:~/example.txt`,but log curl: (67) Authentication failure
