### ISSUE TITLE
The whole app just broke after installing a theme

### ISSUE THREAD

**Issue by SilverEzhik** [blinksh/blink#558]
Hi, just got this app, but after trying to add this theme generated by terminal.sexy, the app started only displaying a black screen with a keyboard. 

```js
t.prefs.set('background-color', "#000000");
t.prefs.set('foreground-color', "#c5c8c6");
t.prefs.set('cursor-color',     "#c5c8c6");
t.prefs.set('color-palette-overrides', ["#282a2e","#a54242","#8c9440","#de935f","#5f819d","#85678f","#5e8d87","#707880","#373b41","#cc6666","#b5bd68","#f0c674","#81a2be","#b294bb","#8abeb7","#c5c8c6"]);
```

This theme file is invalid (no underscore after prefs), but breaking the whole terminal like that, requiring reinstalling the app is... pretty bad.

**Comment by yury** [comment]
Hi @SilverEzhik,

Where did you find this syntax for theme (it is outdated)? We need to update that place :)

We support terminal.sexy json format. Take a look at [wwdc16.js theme](https://github.com/blinksh/blink/edit/raw/Resources/Themes/WWDC%2016.js).

**Comment by yury** [comment]
Can't find any place with this syntax.

You script will work if you replace with`prefs_`

```js
t.prefs_.set('background-color', "#000000");
t.prefs_.set('foreground-color', "#c5c8c6");
t.prefs_.set('cursor-color',     "#c5c8c6");
t.prefs_.set('color-palette-overrides', ["#282a2e","#a54242","#8c9440","#de935f","#5f819d","#85678f","#5e8d87","#707880","#373b41","#cc6666","#b5bd68","#f0c674","#81a2be","#b294bb","#8abeb7","#c5c8c6"]);
```

But this syntax is deprecated.
Please you syntax as in wwdc16 theme or with `term_set`

```js
term_set('background-color', "#000000");
term_set('foreground-color', "#c5c8c6");
term_set('cursor-color',     "#c5c8c6");
term_set('color-palette-overrides', ["#282a2e","#a54242","#8c9440","#de935f","#5f819d","#85678f","#5e8d87","#707880","#373b41","#cc6666","#b5bd68","#f0c674","#81a2be","#b294bb","#8abeb7","#c5c8c6"]);
```

**Comment by SilverEzhik** [comment]
Yeah, I went and double checked and the missing underscore was my fault. I'd still leave this bug open considering how badly things broke, though :V

**Comment by yury** [comment]
Yep you are right, that is bad UX. 
Sorry for that.
Will fix it.

**Comment by yury** [comment]
Ok, app will show alert now. And try to fallback to defaults. So you can go config and change the theme.

![img_0081](https://user-images.githubusercontent.com/5250/46399430-55e81280-c700-11e8-92d7-2ad8103fcf78.PNG)

**Comment by yury** [comment]
Thank you. Closing this.
