### ISSUE TITLE
Delete key not working on a Bluetooth keyboard

### ISSUE THREAD

**Issue by SilverEzhik** [blinksh/blink#559]
Hi, I have a Microsoft Wedge Keyboard, but it appears that the delete key is not working in Blink with it - it does work in other apps, though. Anything I can try to fix that?

**Comment by yury** [comment]
Hi @SilverEzhik,

Can you run blink `showkey` command, press delete key and paste output here?

Thank you.

**Comment by SilverEzhik** [comment]
Not getting anything when I press the delete key there.

**Comment by yury** [comment]
Hmm, I will try to get windows bluetooth kb with `del` button tomorrow. And will look.

**Comment by yury** [comment]
Hi @SilverEzhik,

Fill will be in next release:
https://youtu.be/tgGefvqottU

Thank you for reporting this issue.

**Comment by SilverEzhik** [comment]
Thanks for the quick fixes!
