### ISSUE TITLE
forwarding using -A doesn't seems to work for v12.0.33

### ISSUE THREAD

**Issue by thariman** [blinksh/blink#562]
to recreate from blink prompt
ssh -A -p 60888 -i KEYID username@host "ssh -vT "git@gitthub.com"

on the server side:
/usr/sbin/sshd -Ddd -p 60888 |& tee -a blink12.0.33wA.out

From the sshd log maybe the error is at 
debug1: channel 2: new [accepted auth socket]
channel 2: open failed: administratively prohibited: 

using prompt2 the session successfully create channel2.

**Comment by yury** [comment]
Hi @thariman,
Can I close this in favor of #563

**Comment by thariman** [comment]
Does forwarding depend on ssh-agent on blinksh implementation?

**Comment by yury** [comment]
`ssh-agent` and `ssh-add` commands are ported from OpenSSH

**Comment by thariman** [comment]
On Ubuntu, you can do ssh -A without ssh-agent/ssh-add but it will ask for the passphrase.

**Comment by thariman** [comment]
seem that blink ssh -A implementation depend on ssh-agent/ssh-add
close this in favor of #563
