### ISSUE TITLE
How to use ssh-agent

### ISSUE THREAD

**Issue by thariman** [blinksh/blink#563]
Hi,

How do you use ssh-agent in blink shell?
In a Linux shell I usually do:

#eval `ssh-agent`
#ssh-add
   type key password
then login using ssh

Thank you

**Comment by yury** [comment]
Almost same here

run in one tab `ssh-agent` (Currently ssh-agent can't run in background)
in other tab run `ssh-add <key-name from config>`
then `ssh ....`

**Comment by thariman** [comment]
Do I need to open another tab for ssh -A?
When I run ssh in another tab it still ask for the key password.

**Comment by yury** [comment]
Hmm,

It should work with two tabs: (one for ssh-agent, other with ssh-add and then ssh)

**Comment by thariman** [comment]
On my iPad it stuck after ssh-add it asks the passphrase but didn't return to blink prompt.

**Comment by yury** [comment]
Hi @thariman!

ssh-agent/ssh-add works for newly created keys within `config`. As far as I understand you use key from `.ssh/` folder or old key (pre blink 12) with passphrase.

Few questions to be on the same page:

- If you just `ssh host` blink prompts you for passphrase from key?
- How do you add your key? ssh-keygen or with config->keys?

I general, I think problem with a key with passphrase and prompt for it. I will try to fix this tomorrow.

**Comment by thariman** [comment]
HI @yury 
If I just ssh host it will ask passphrase via cli/blink prompt
I also create a new key pair via config-keys and ssh-keygen same behavior stuck at add-key
If I run ssh-add first with old key via config->keys it will prompt for passphrase via GUI

by the way this run on Ipad Pro IOS 12.1 beta2.

I'm going to fresh install blink by removing and install after updating to beta 3 will let you know the result.

**Comment by thariman** [comment]
After removing blink update to beta3.
Create new key via config->keys.   It didn't ask for any passphrase during creation.
Login to host using ssh host no problem
Login to host using ssh -A able to login but not to github
run ssh-agent open new tab run ssh-add keyname same issue stuck
exit from config often got blank screen no blink> prompt

**Comment by thariman** [comment]
Hi @yury,

Tried on ios 12.0 iphone.
Create config>keys
ssh-agent. new tab
ssh-add keyname
stuck

Thanks

**Comment by thariman** [comment]
Hi @yury 
After updating to build 34:
using existing keys
ssh-agent new tab
ssh-add keyname
ssh -A hostname
login to linux box.
after doing ssh -vT git@github.com
it crash after it finish scrolling.

Since then.
Unable to ssh to the host.
typing ssh hostname
get connected to hostname message
back to blink prompt

try to remove blink restart ipad install blink
using default id_rsa
now stuck at ssh-add
on another tab doing ssh hostname
get connect to hostname message
but back to blink prompt

Do you have any other test to try?

**Comment by yury** [comment]
Hi @thariman,

What key type do you use? DSA/RSA/ECDSA/Ed25519 ?

**Comment by thariman** [comment]
the default that is created when first install, RSA.

and the one that work briefly was created on build 33 RSA/4k bit.

I’m tempted to recover my ipad to 12.0 currently running ios 12.1 beta 4

Thank you

**Comment by thariman** [comment]
Hi @yury 
Did a downgrade to 12.0.1
fresh install blink
able to ssh to host
upgrade to build 34
able to ssh to host
Several test I did:
ssh-agent -> new tab -> ssh-add id_rsa  -> stuck

config->new key (RSA/4096)  name AI3
ssh-agent -> new tab -> ssh-add AI3 -> stuck

ssh -A -i AI3 -p 822 name@hostname
at prompt run ssh -vT git@github.com
run with the usual git@github.com: Permission denied (publickey)  # I haven't add AI3 key to github

ssh-agent -> new tab   skipping ssh-add since it usualy get stuck
ssh -A -i AI3 -p 822 name@hostname
at prompt run ssh -vT git@github.com
stop at
OpenSSH_7.6p1 Ubuntu-4, OpenSSL 1.0.2n  7 Dec 2017
....
....
 debug1: expecting SSH2_MSG_NEWKEYS
 debug1: SSH2_MSG_NEWKEYS received
 debug1: rekey after 134217728 blocks
^C  exit
run ssh -vT git@github.com  again it. crash blink

**Comment by thariman** [comment]
Hi @yury 

Testing result on build 35:
import AI2 key with passphrase.
ssh-agent -> new tab -> ssh-add AI2
ssh -A AI2
able to login
ssh -vT git@github.com
successful login to github using key
run again ssh -vT git@github.com
blink crash

Also, blink never ask passphrase again even during ssh-add

Thank you

**Comment by thariman** [comment]
sorry press the wrong button

**Comment by yury** [comment]
Yep, reproduced.

**Comment by yury** [comment]
Hi @thariman,

When you import key in blink keys, app stores your key in Secure Enclave so you don't need passphrase anymore.

I was able to reproduce and fix crash. Pushing build 36 (will send it only for you) please take a look.

**Comment by thariman** [comment]
How long does it take to build and show up at tf?

**Comment by yury** [comment]
20-30 mins if everything is ok :)

**Comment by thariman** [comment]
not yet, hitting refresh nothing :(

**Comment by thariman** [comment]
Hi @yury

The testing result on build 36:

ssh-agent -> new tab -> ssh-add AI2
ssh -A AI2
able to login
ssh -vT git@github.com
a successful login to github using key
run again ssh -vT git@github.com multiple time. all good
try git clone my private repo include Git LFS with 100 MB file.  Worked fine.
try git push/pull worked fine.

Thank you.

Now if possible please don't cache the passphrase.

**Comment by thariman** [comment]
Extra security.  To comply with what you know and what you have.

Thank you.

**Comment by lohitv9** [comment]
Hi,

I have just downloaded blink from AppStore and tried to do the same. It does not seem to work.

1. ssh-keygen ( with passphrase)

2. Edited .ssh/config to always refer the above key for every host as below:
Host *
User test01
IdentityFile key_v1

3. ssh-agent ( it starts running in background )
4. New tab
5. ssh-add key_v1 ( it prompts me for password and once successful - it says identity added successfully )
6. ssh <host> ( it again asks me for password )
7. ssh -A <host> (It asks me for password here too)

I really wish not to enter password every time, and would like to just enter once during ssh-add.
May i know if this could be fixed?

Thank you
