### ISSUE TITLE
Feature request: rsync

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#567]
Issue #565 asks how to scp folders.

Since other OpenSSH commands have been ported, a non-curl-based `scp` including the `-r` flag is probably straightforward to port.

But `rsync` is even better for synchronizing files with another host, since it supports deltas, progressive downloads, various speedup strategies, dry runs, etc.

While the [official rsync from Samba](https://rsync.samba.org/) is GPLv3, there's a clean reimplementation of an iOS rsync library called [acrosync-library](/gilbertchen/acrosync-library) under the RPL license. It hasn't been updated in quite some time, it looks like, but I see users of it that are in active development, so presumably it still works.

**Comment by NightMachinary** [comment]
It would be a great idea to add an auto-sync feature to Blink, so that some directories of a host can be added to a sync list, and running `sync hostname` (in Blink) would sync those paths with BlinkFolderOniPad/hostname/syncing-paths. This allows easy cross-use of files on the remote server and iPad, allowing the two to complement each other. 
PS: Should this be a new issue? :D

**Comment by treyharris** [comment]
@NightMachinary I'd say yes, it should be a new issue; on other platforms, `rsync` can be used for auto-synchronization via scripting, but it isn't sufficient by itself, so without a shell programming language in Blink, this feature being added alone wouldn't get you what you want.

**Comment by NightMachinary** [comment]
I don’t need auto-synchronization. I am content with running one “rsync -P
x@x:synced .” whenever I need to sync.

**Comment by drpump** [comment]
Would love to see this. Better still, since Blink already implements a file provider, it could potentially  have hooks to automatically rsync when files are updated (assuming I have understood the iOS file provider capabilities).

**Comment by TobiaszCudnik** [comment]
The `rsync` binary alone would be enough. You can ship `code`, means you for sure can ship rsync. Thx.

**Comment by carloscabanero** [comment]
We already ship sftp with --update flag that will provide copy on timestamp change between different folders. That is what I am using at the moment. Rsync is very complex and unfortunately the license is GPL, which is incompatible with ours. Give this a try.

Closing here as I don't think we will every have the bandwidth. But if anyone needs any other extra feature from rsync, or has ideas on how to improve the algorithm, let us know and we can give a try to specifics.

**Comment by supRy** [comment]
@carloscabanero - one feature I've been wanting from rsync is --remove-source-files. This essentially implements a move operation which verifies the destination has the file in full before deleting. This can be helpful for two reasons:
1. iOS doesn't support moving between file systems. So I can't just do it from within the files app.
2. If I use sfpt, it can be time-consuming to verify that each file was successfully transferred, then delete it manually from the source. An interrupted sftp session could leave the destination in an indeterminate state where not all files have been transferred completely. The rsync --remove-source-files works essentially as a combination of copy, verify, remove.

I just started using Blink by the way and I'm loving it!

**Comment by carloscabanero** [comment]
That should be doable. Please open a new issue and we will figure it out.
