### ISSUE TITLE
chmod missing?

### ISSUE THREAD

**Issue by yourcelf** [blinksh/blink#568]
The README in this repo lists `chmod` as an included utility, but after installing Blink v11.26 from the app store, it appears that utility is missing.

At any rate, I believe I need to change the permissions of the ssh key file I copied into blink's .ssh directory to 600 for the `ssh` and `mosh` utilities to accept it. Any tricks for getting these permissions changed without chmod?

**Comment by yury** [comment]
`chmod` is only for sideload (manual compile) app. 

Within Blink it is recommended to store you keys under `config` -> `keys`. (It is more secure)
You can quickly copy your key with `cat ~/.ssh/your_key | pbcopy` on your macbook and import it from clipboard from `config` command -> `keys` -> `+` -> `Import from clipboards`. (if you have shared clipboard enabled between your devices)

**Comment by yourcelf** [comment]
Thanks, that got me there.  I don't have a macbook.

Since I'd already copied the private/public keypair into blink's folder space, I used `cat id_rsa | pbcopy` from within blink to get it into the clipboard.  It appears that setting an SSH passphrase is required, so I did that, and was able successfully use the key.

I hadn't seen the `config` utility before -- I guess there is a note on it way down in the README in regards to setting up keys, but no mention of it on https://blink.sh or in the app store description.  That could be a might more discoverable for new users. :)

It does seem that keys in the `.ssh/` directory (such as those created by blink's own `ssh-keygen` at the command line or copied there manually) aren't usable by the ssh client.  Or at least, even after I managed to fiddly-hack to get the permissions right, `ssh -i .ssh/id_rsa me@myserver.com` still didn't seem to use the key.

**Comment by yury** [comment]
Yep, you are right. So many things we need to document.

We need to make some intro screens and put updated documentation on the site and app store description. But we are working on that. Stay tuned we are almost ready for Blink v12.

And yes, ssh -i <path/to/key> will work in next version.

Anyway, thank you for your feedback.
Happy sshing :)

**Comment by sireebob** [comment]
why was this ever removed? why pay for an app to have fewer features?

it would be nice to be able to create and execute scripts to run common remote commands with fewer steps involved. the bin subfolder is already in PATH presumably for that purpose, but that's not helpful if scripts can't be made executable.

**Comment by sireebob** [comment]
oops never mind, it looks like scripting isn't really possible at the moment anyway. deleting these comments

**Comment by drewwells** [comment]
how do we use these keys with ssh-agent? If I load keys with Files, then I can not add them to ssh-agent due to permissions. If I load them into the weird gui config, then they are not accessible on the terminal
