### ISSUE TITLE
External monitor support

### ISSUE THREAD

**Issue by juneoh** [blinksh/blink#570]
Thanks in advance for being my no. 1 app.

Steps to reproduce:
Use blink while connected to a lightning to HDMI cable for external monitor.

What happens:
The external monitor works but the iPad's screen goes blank, with occasional crashes.

I love the blink shell for everyday work. But when I use the shell while lecturing, this bug forces me to use other apps in such occasions.

**Comment by thariman** [comment]
Same issue on build 36

**Comment by yury** [comment]
Hmm, can't repro with AirPlay ....
Goes to sleep and back ok.

**Comment by juneoh** [comment]
Here's the requested screenshot. Running the latest iOS and the app on 10.5 iPad pro.

![eb053fbb-68ba-4ccb-a518-8591f776dc23](https://user-images.githubusercontent.com/18067322/47347231-ca074c00-d6e9-11e8-8d58-6030437db5d6.png)

Also, here's a photo of the reproduced problem. Note that this is *after* I had unlocked the app using Touch ID. Perhaps the problem occurs in combination the passcode lock feature?

![68045d00-f281-4f49-9cfe-48414fe813bc](https://user-images.githubusercontent.com/18067322/47347255-d2f81d80-d6e9-11e8-86df-c3984b2cdb61.jpeg)

**Comment by yury** [comment]
OK, I think issue in pin code screen.

**Comment by juneoh** [comment]
Thank you for such a quick reply. Not to make a burden, but I've registered another pin code screen issue, for a remote chance of being related.

**Comment by thariman** [comment]
I tried by disabling auto lock.  But the screen between external monitor and ipad seems to be out of sync.  
For example Input at the blink prompt show up at external screen but output at ipad screen.

**Comment by yury** [comment]
@thariman, yep this is behavior by design. AirPlay screen is additional screen with independent shell. So you can use both screen independently. Use cmd+o to switch focus between screens and cmd+shift-o to move shells between screens.

**Comment by thariman** [comment]
@yury  I'm using HDMI cable not AirPlay.

**Comment by thariman** [comment]
Cool nice to have an independent shell on each screen.

**Comment by thariman** [comment]
Fix on build 38 with screen lock with an external display.  Thank you.
Just wondering if it possible to have blink showing on the external monitor and another app on the iPad screen?

**Comment by yury** [comment]
Not yet. But is cool feature to have
