### ISSUE TITLE
Session Lost When Switch to Other App or Temporarily Lock Screen (iPad)

### ISSUE THREAD

**Issue by ahter** [blinksh/blink#574]
I just bought Blink and I am really enjoying it.

However, when I switch to another app in iPad or need to lock the screen for a 30 seconds or so, the SSH connection is gone. Blank sceeen waits for me and I have to login again etc...

This might be a setting issue as well but I wasn't able to find the right setting/documentation anywhere.

Any help would be highly appericated.

**Comment by yury** [comment]
Hi @ahter.

Glad that you like the app. If you can, we recommend to use mosh session. It will keep you connection even after device reboots and ip changes.

For ssh timeouts we have new `geo track` command. It will keep app running in background for the longer time (with a little bit pressure on the battery ofc). We are planning to push next version this with or on Monday...



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yury** [comment]
I think we can close. Please reopen if needed.

Thank you.
