### ISSUE TITLE
mosh issues (ios12)

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#577]
There is many issues after I've upgraded to the ios 12

 I use blink daily, it is my main tool which I use 90% of my work time (and I currently working only on ipad pro)

Since update to ios 12 there is connectivity issues.

mosh often losing connection. Then sometimes it still keep it open as you can see from video, sometimes screen freezes without mosh notification (that blue ribbon at top);

Very often after I close blink to tray and reopen it, window keep resized (again you can see that on video, it were full-screen);

![812f92ea-325e-4742-b77d-d49e14d7eccb](https://user-images.githubusercontent.com/26776/47655282-f9580600-db8c-11e8-84e5-79fba94e484a.gif)

**Comment by yury** [comment]
Hi @andrius,
What version of blink are you using?

`help` command prints the version at the top.

**Comment by andrius** [comment]
Blink: v11.26.1. Jun 26 2018

**Comment by andrius** [comment]
update. I have same issues with mosh and ssh on 12.1 too. either with `geo track`. Even worse: in this mode, in a while, blink does re-execute `ssh host`, it is not what I expecting, not kind of keepalive

**Comment by prenaux** [comment]
For what its worth I also had a bunch of disconnection / lost connections issues this afternoon - first time I really spend using Blink.

Blink: v12.1.43. Nov  2 2018 on an iPad Pro 2018, 12.9", iOS 12.1

Another issue is the fact that the themes are never applied and font size is ignored. Either that or config isn't saved - but I doubt that's the problem since my Caps Lock -> Ctrl mapping stays around.

Overall Blink is still usable - and better than all the terminal apps I bought - but there's indeed a bunch of stability problems that look like issues with iOS 12.

**Comment by yury** [comment]
@prenaux themes and fonts applied only for new windows. We did that to optimize performance.

**Comment by prenaux** [comment]
Trying to repro the theme thing... it works now after I killed and restarted Blink... I'll file an issue if I manage to repro later.

**Comment by prenaux** [comment]
Blink just froze again and I lost all my mosh sessions again :( definitly not stable on iPad Pro / iOS 12.

**Comment by yury** [comment]
:( use it everyday on iOS 12. no issues yet. Will investigate...

**Comment by prenaux** [comment]
Let me know if there's anything I can do to help diagnose. Maybe its because my mosh-server is on macOS?

**Comment by yury** [comment]
Oh, that could be it. I know that for sure!

macOS keeps machine awake only for ssh connection. Mosh session doesn't keep it awake, so it goes to sleep and closes networking.

I didn't find a way to keep it awake with mosh, so I connect with ssh in one tab and do mosh in others.

**Comment by yury** [comment]
But it doesn't close mosh sessions. If you connect with ssh again, all mosh session should be restored.

**Comment by prenaux** [comment]
Mmm, but it never dies while I'm working on it, only when Blink is in the background. As far as I can tell my mac doesnt go to sleep - I disabled all sleep because I run servers on it. But I'll try to open a tab with a regular SSH connection, we'll see if it helps.

**Comment by andrius** [comment]
@yury my almost daily issue with mosh is that it resizing window size so I cannot control it until i force quit it and restart blink. I dont know why. Font? I use PragmataPro. and tmux all the time.

Sometimes blink also increasing vertical space between letters, sometimes change everthing to bold.

Getting same with ssh with only exception that it is less reliable, even with geo tracking on

**Comment by yury** [comment]
Hi @andrius,

PragmataPro is very heavy font even with latest update (Especially with ligas). I will try to improve the speed of zooming.

For now I did a lot of mosh state optimization and fixes. Will try to push another TF version today. v12.2 build 49

**Comment by prenaux** [comment]
@yury Can we get test builds from TestFlight?

**Comment by yury** [comment]
Sure, ping me at yury.korolev@gmail.com

**Comment by prenaux** [comment]
Done, thanks.

**Comment by yury** [comment]
@prenaux just sent you invite.

**Comment by prenaux** [comment]
Got it thanks. Should I put any potential feedbacks here, or do you prefer if I use the "send feedback" button in TestFlight?

**Comment by yury** [comment]
It is better here or at [discord](https://discord.gg/4CsR3P)

**Comment by prenaux** [comment]
Noted.

I just had a crash - and lost my mosh sessions. It seems to happen frequently in this configuration:  I have Safari on the left and Blink on the right + Slack as an overlay. The iPad goes in sleep mode, and it crashes after I unlock the iPad. Maybe its running out memory and closing because of that?

This happened three times today (afternoon of work). I wouldnt really mind this too much if there was a way to restore the mosh sessions - even by typing a command. In theory mosh + screen solves the problem, but `screen` breaks the input and output in various way which make it not very usable - I have the same issue with screen on regular macOS / Linux machines so that's not really a Blink thing.

I'm hoping you're getting some core dump from the TestFlight version. Let me know if I can do anything more to help diagnose/debug the issue.

**Comment by yury** [comment]
@prenaux  thank you for detailed report.

Do you have only mosh sessions? how many of them? Is it possible that you have ssh session too?

**Comment by prenaux** [comment]
@yury  I use only mosh, because ssh doesn't resume its not very useful for my use case. I have at least two mosh sessions on, most of the time 3 or 4.

**Comment by prenaux** [comment]
@yury Ctrl+Space doesnt work anymore for me in the latest TestFlight build, makes Emacs unusable.

**Comment by prenaux** [comment]
ooohh, ok there's a "Grab Ctrl+Space" option now.

**Comment by prenaux** [comment]
can we have a "Grab Ctrl+Arrow" options? that's the only thing that doesnt work for me... I've remapped to other shortcuts and can work around it, but if there's a way that's even better...

**Comment by yury** [comment]
Yep, by default ctrl+space is reserved for language switch on hardware kbds.

I will look on ctrl+arrow - it should work by default.
What it should output?
Can you check ctrl+arrow in blinks `showkey` command?

**Comment by prenaux** [comment]
ctrl+arrow output (Up/Right/Down/Left), they start with 27/0033/0x1b:
```
blink> showkey
Press any keys - Ctrl-D will terminate this program.
^[       27 0033 0x1b
[        91 0133 0x5b
1        49 0061 0x31
;        59 0073 0x3b
5        53 0065 0x35
A        65 0101 0x41
^[       27 0033 0x1b
[        91 0133 0x5b
1        49 0061 0x31
;        59 0073 0x3b
5        53 0065 0x35
C        67 0103 0x43
^[       27 0033 0x1b
[        91 0133 0x5b
1        49 0061 0x31
;        59 0073 0x3b
5        53 0065 0x35
B        66 0102 0x42
^[       27 0033 0x1b
[        91 0133 0x5b
1        49 0061 0x31
;        59 0073 0x3b
5        53 0065 0x35
D        68 0104 0x44
```

**Comment by prenaux** [comment]
CapsLock + Arrow leads to no output at all with "showkey". Capslock is mapped to Ctrl in the preferences.

**Comment by prenaux** [comment]
So the clarify the issue I'm referring to is, on the iPad cover keyboard:
- Ctrl+Arrow works
- Capslock+Arrow, with Capslock assigned to Ctrl, doesn't work

**Comment by carloscabanero** [comment]
We extended this issue. Capslock as Ctrl + Arrow should work as many versions ago. Please open a new issue if this comes back.

Closing here.
