### ISSUE TITLE
Can't Connect through USG Gateway

### ISSUE THREAD

**Issue by drewcovi** [blinksh/blink#579]
USG Gateway disables ICMP by default. 

Is ICMP required for blink?

I'm able to ssh into my home machine without trouble in Prompt (by Panic) and any other terminal on my Mac.

Seems a strange limitation. Mosh connects without trouble on mac as well, so it doesnt seem ICMP should be a requirement.

**Comment by yury** [comment]
Hi @drewcovi.

No, ICMP is not required for blink. 

What version of blink are you using? (`help` command prints version). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by drewcovi** [comment]
@yury whew. I'm struggling to understand why I can successfully ping my domain (I've now enabled ICMP), but in Blink I can't mosh or ssh from outside my LAN. I keep receiving:
`Could not resolve host address`

If I try to ssh/mosh directly to the ip address, it gives failures on UDP ports (both TCP and UDP are forwarded).

**Comment by drewcovi** [comment]
Blink: v11.26.1. Jun 26 2018

**Comment by drewcovi** [comment]
@yury it also claims
`Did not find remote IP address`

**Comment by drewcovi** [comment]
yargh. disregard.

User error or perhaps UI/UX bug.

I definitely had the fields mis-mapped in config.

**Comment by drewcovi** [comment]
I didnt even have the mosh server field populated largely due to the placeholder text seemed confusing.

*Host* should probably be *Alias* and HostName should probably just be *Host* but thats just me 😄
