### ISSUE TITLE
After upgrading, Blink does not authenticate

### ISSUE THREAD

**Issue by ttelford** [blinksh/blink#581]
My SSH Keys all have passphrases.

I can no longer connect, and there is no prompt for the passphrase.

ssh -v gives me:

socket_callback_connected: Socket connection callback: 1 (0)
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.9p1 Debian-1
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.9p1 Debian-1
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.9 (70900)
blink: setting socket keepalive: 1
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,gssapi-keyex,gssapi-with-mic

**Comment by yury** [comment]
Oh, that is regression. 

Please use ‘ssh2’ instead of ‘ssh’

**Comment by yury** [comment]
Not sure if github sent my previous reply. 

This is regression.

Please use `ssh2` command instead of `ssh`.

**Comment by ttelford** [comment]
And if I use Mosh most of the time?

**Comment by yury** [comment]
As a fix for now, you can reimport your key. I will try to fix your problem tomorrow.

**Comment by yury** [comment]
@ttelford 
can  you please do `ssh -vvvvv` too.
It will spits more debug info.

**Comment by ttelford** [comment]
blink> ssh -vvv pilot
ssh_connect: libssh 0.7.90 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.9p1 Debian-1
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.9p1 Debian-1
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.9p1 Debian-1
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.9 (70900)
ssh_connect: current state : 4
ssh_packet_socket_callback: packet: read type 20 [len=1076,padding=6,comp=1069,payload=1069]
ssh_packet_process: Dispatching handler for packet type 20
ssh_knownhosts_algorithms: server pilot.pariahzero.net:22 has ssh-rsa in known_hosts
ssh_client_select_hostkeys: Changing host key method to "ssh-rsa"
packet_send2: packet: wrote [len=508,padding=8,comp=499,payload=499]
packet_send2: packet: wrote [len=44,padding=6,comp=37,payload=37]
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=1116,padding=8,comp=1107,payload=1107]
ssh_packet_process: Dispatching handler for packet type 31
ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
packet_send2: packet: wrote [len=12,padding=10,comp=1,payload=1]
ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
crypt_set_algorithms2: Set output algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
crypt_set_algorithms2: Set input algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
ssh_packet_newkeys: Signature verified and valid
ssh_connect: current state : 7
blink: setting socket keepalive: 1
packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_socket_callback: packet: read type 6 [len=28,padding=10,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [len=44,padding=4,comp=39,payload=39]
ssh_packet_socket_callback: packet: read type 51 [len=60,padding=15,comp=44,payload=44]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,gssapi-keyex,gssapi-with-mic
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,gssapi-keyex,gssapi-with-mic
blink> ssh -vvvvv pilot
ssh_connect: libssh 0.7.90 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.9p1 Debian-1
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.9p1 Debian-1
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.9p1 Debian-1
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.9 (70900)
ssh_connect: current state : 4
ssh_packet_socket_callback: packet: read type 20 [len=1076,padding=6,comp=1069,payload=1069]
ssh_packet_process: Dispatching handler for packet type 20
ssh_knownhosts_algorithms: server pilot.pariahzero.net:22 has ssh-rsa in known_hosts
ssh_client_select_hostkeys: Changing host key method to "ssh-rsa"
packet_send2: packet: wrote [len=508,padding=8,comp=499,payload=499]
packet_send2: packet: wrote [len=44,padding=6,comp=37,payload=37]
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=1116,padding=8,comp=1107,payload=1107]
ssh_packet_process: Dispatching handler for packet type 31
ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
packet_send2: packet: wrote [len=12,padding=10,comp=1,payload=1]
ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
crypt_set_algorithms2: Set output algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
crypt_set_algorithms2: Set input algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
ssh_packet_newkeys: Signature verified and valid
ssh_connect: current state : 7
blink: setting socket keepalive: 1
packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_socket_callback: packet: read type 6 [len=28,padding=10,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [len=44,padding=4,comp=39,payload=39]
packet_send2: packet: wrote [len=44,padding=4,comp=39,payload=39]
ssh_packet_socket_callback: packet: read type 51 [len=60,padding=15,comp=44,payload=44]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,gssapi-keyex,gssapi-with-mic
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,gssapi-keyex,gssapi-with-mic

One of the lines may be repeated due to copy/paste errors

**Comment by yury** [comment]
thank you

**Comment by andrius** [comment]
same with me (i use mosh all the time, but in any case it asking for password, no matter ssh or mosh)

**Comment by yury** [comment]
@andrius even with v12.1 ?

**Comment by andrius** [comment]
@yury yes, and much worst is that clipboard copy does not work properly (both on ssh/ssh2)

**Comment by andrius** [comment]
I've generated ssh key using blink, populated it to the server, but still ssh and mosh does not working

**Comment by ttelford** [comment]
RSA:  now working
ED25519:  now working
ECDSA: nope. See below.  (ssh_userauth_request_service: Failed to request "ssh-userauth" service)

blink> ssh -vvvvv tick date
ssh_connect: libssh 0.7.90 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.4p1 Raspbian-10+deb9u4
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.4p1 Raspbian-10+deb9u4
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.4p1 Raspbian-10+deb9u4
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.4 (70400)
ssh_connect: current state : 4
ssh_packet_socket_callback: packet: read type 20 [len=1076,padding=6,comp=1069,payload=1069]
ssh_packet_process: Dispatching handler for packet type 20
ssh_knownhosts_algorithms: server tick.pariahzero.net:22 has ssh-rsa in known_hosts
ssh_client_select_hostkeys: Changing host key method to "ssh-rsa"
packet_send2: packet: wrote [len=508,padding=8,comp=499,payload=499]
packet_send2: packet: wrote [len=44,padding=6,comp=37,payload=37]
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=604,padding=8,comp=595,payload=595]
ssh_packet_process: Dispatching handler for packet type 31
ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
packet_send2: packet: wrote [len=12,padding=10,comp=1,payload=1]
ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
crypt_set_algorithms2: Set output algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
crypt_set_algorithms2: Set input algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
ssh_packet_newkeys: Signature verified and valid
ssh_connect: current state : 7
blink: setting socket keepalive: 1
packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_socket_callback: packet: read type 6 [len=28,padding=10,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [len=44,padding=4,comp=39,payload=39]
ssh_packet_socket_callback: packet: read type 51 [len=44,padding=19,comp=24,payload=24]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password
blink: import key ECDSA
ssh_pki_import_privkey_base64: Trying to decode privkey passphrase=false
packet_send2: packet: wrote [len=412,padding=7,comp=404,payload=404]
ssh_packet_socket_callback: packet: read type 51 [len=44,padding=19,comp=24,payload=24]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password
Password:

**Comment by yury** [comment]
Thank you @ttelford. I will check that key type.

**Comment by netengineer0** [comment]
I am having the same issue. I have fresh install of OpenBSD 6.4 that is producing the same output.


ssh_connect: libssh 0.7.90 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.9
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.9
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.9
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.9 (70900)
ssh_connect: current state : 4
ssh_packet_socket_callback: packet: read type 20 [len=1076,padding=6,comp=1069,payload=1069]
ssh_packet_process: Dispatching handler for packet type 20
ssh_knownhosts_algorithms: server 192.168.20.127:22 has ssh-ed25519 in known_hosts
ssh_client_select_hostkeys: Changing host key method to "ssh-ed25519"
packet_send2: packet: wrote [len=508,padding=4,comp=503,payload=503]
packet_send2: packet: wrote [len=44,padding=6,comp=37,payload=37]
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=188,padding=8,comp=179,payload=179]
ssh_packet_process: Dispatching handler for packet type 31
ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
packet_send2: packet: wrote [len=12,padding=10,comp=1,payload=1]
ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
crypt_set_algorithms2: Set output algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
crypt_set_algorithms2: Set input algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
ssh_packet_newkeys: Signature verified and valid
ssh_connect: current state : 7
blink: setting socket keepalive: 1
packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_socket_callback: packet: read type 6 [len=28,padding=10,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [len=44,padding=9,comp=34,payload=34]
ssh_packet_socket_callback: packet: read type 51 [len=60,padding=14,comp=45,payload=45]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password,keyboard-interactive
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password,keyboard-interactive
ssh_userauth_kbdint_init: Sending keyboard-interactive init request
packet_send2: packet: wrote [len=76,padding=17,comp=58,payload=58]
ssh_packet_socket_callback: packet: read type 51 [len=60,padding=14,comp=45,payload=45]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password,keyboard-interactive
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password,keyboard-interactive
Permission denied, please try again.
ssh_userauth_kbdint_init: Sending keyboard-interactive init request
packet_send2: packet: wrote [len=76,padding=17,comp=58,payload=58]
ssh_packet_socket_callback: packet: read type 51 [len=60,padding=14,comp=45,payload=45]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password,keyboard-interactive
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password,keyboard-interactive
Permission denied, please try again.
ssh_userauth_kbdint_init: Sending keyboard-interactive init request
packet_send2: packet: wrote [len=76,padding=17,comp=58,payload=58]
ssh_packet_socket_callback: packet: read type 51 [len=60,padding=14,comp=45,payload=45]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password,keyboard-interactive
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey,password,keyboard-interactive

**Comment by yury** [comment]
Ok, found original issue with [ECDSA](https://gitlab.com/simo5/libssh-mirror/commit/a14a80f35fe600206373a757a7fb29c950aa7227)

**Comment by yury** [comment]
@ttelford, @netengineer0 we have release 12.2 to Test Flight, I would love you to take a look at it before it get published to App Store. (If it possible ofc)

Thank you

**Comment by ttelford** [comment]
I’d be happy to test - is there a prebuilt binary to test, or am I compiling from Source? (Not a problem either way, but I’m as lazy as the next guy...)

**Comment by yury** [comment]
@ttelford can't find your email to send you invite to TF :(

**Comment by yury** [comment]
@ttelford sent invite. Thank you

**Comment by ttelford** [comment]
ECDSA: Works
RSA: Works
ED22519: works

I am seeing some terminal formatting errors; though they are only from blink directly; once a connection is established, it looks good.

(Ssh -vv)


Or the blink prompt not returning to the left column:

**Comment by ttelford** [comment]
I think this issue can be closed
