### ISSUE TITLE
Bring back the old icon, please!

### ISSUE THREAD

**Issue by masochist** [blinksh/blink#583]
I miss the old Blink icon. It was dark and fit in with the other dark icons I've used (Pythonista, Apollo, CARROT, Fiery Feeds, Overcast, etc.). The new icon is this strange turqouise that doesn't have any connection to what the app does (namely display grey text on a black screen). At the very least, a choice of icons would be good.

**Comment by goerz** [comment]
I definitely prefer the old icon, too. +1 for making the icon user-selectable.

**Comment by yury** [comment]
hehe, I was the first one who was agains. But after couple days I really like it. It is very warm and stand out. Just give it some time :)

**Comment by masochist** [comment]
I don't think that "giving it time" will help. I do not like the new icon and time won't change that.

**Comment by goerz** [comment]
That turquoise is extremely jarring. Providing multiple icons should be relatively straightforward, no? You could even make it an in-app purchase, the way PCalc does ;-)

**Comment by avysk** [comment]
The new icon is absolutely horrible.

**Comment by yury** [comment]
it is awesome. just give it a day.

**Comment by avysk** [comment]
It kinda fits the last completely broken update of the program but it doesn’t mean that this acidic color is awesome :)

**Comment by levex** [comment]
Why not just give the user the choice? :-)

If I did any iOS development I'd submit a PR that would give the user the choice.

**Comment by masochist** [comment]
I've given it a day, I still hate it. Can we get it changed back, please? Or at least a choice? No one in this thread is in favour of the new icon except you, @yury. Did you design it? Is that why you're so attached to it?

**Comment by avysk** [comment]
I have given it a day. It sucks as strongly as before.

**Comment by goerz** [comment]
If that was a gallery of icon choices, I would definitely recommend adding "old-style" versions of these, too: black icon with colored circle/slash (which would include the old icon)

**Comment by andrius** [comment]
I still love black, from proposed ones green also fine (the second one icon from the left)

**Comment by yury** [comment]
![img_0122](https://user-images.githubusercontent.com/5250/48066041-83334f00-e1dd-11e8-85ff-06484996768e.jpg)

**Comment by plakat** [comment]
I, too, prefer the old icon (after several days even ;-)
B und able to choose from some option would of course be nice, but overall it's really a minor thing. First and foremost Blink is immensely useful to me, whichever color it's icon may show.

**Comment by yury** [comment]
I love new icon, but we have added alternate (old one) under config-> appearance

**Comment by masochist** [comment]
Hi,

Thank you *so much* for listening to your users on this. Seriously. It shows that you value us, and in turn, we value you. ❤️

I do have a quick question, though. Can you explain what the RTT label means? :)

**Comment by carloscabanero** [comment]
Ready to test :)

**Comment by victoraugust** [comment]
Is there a link to join TF so that I can switch back to the old icon :) ?

**Comment by yury** [comment]
12.2 is on review in App Store. So it will be public in couple days. (I hope on Monday)

**Comment by yury** [comment]
Closing the issue.
