### ISSUE TITLE
mouse scroll in tmux sessions

### ISSUE THREAD

**Issue by saptarshiguha** [blinksh/blink#584]
I have `set -g mouse on` in my tmux session. On MacOS this allows me to use my mouse to scroll up and down the tmux window.  On blink i need to use the keyboard to scroll and cannot use the mouse.

Could this feature be added?

**Comment by andrius** [comment]
I'll comment on this: mouse actually works, i.e. I can click on tmux and vim tabs. But that's how it react on touches

**Comment by saptarshiguha** [comment]
mouse touch to select a tmux tab works. But the scrolling doesn't. I don't know if this is a bug, but would be nice to have.

**Comment by yury** [comment]
It is not a bug. It is not implemented yet. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NyaMisty** [comment]
It seems that only mousedown and mouseup are implemented, so can we have the mousescoll event implemented? 
mosh doesn't support scroll back, so the tmux scollback history is quite essential :(

**Comment by saptarshiguha** [comment]
Thanks @yury . Willing wait to when you get a chance to implement this. I'm already comfortable with the tmux key controls, this would be a nice to have .

**Comment by botanicus** [comment]
I'd love to see this one as well.

If it's not anywhere near on top of the roadmap, I'd at least like the scroll disabled for tmux, because I tend to move it constantly, for instance when I pull down from the top to see the notifications, very often I move my tmux which is rather annoying.

Thank you for all the great work! Blink is my main work tool these days, I do all my coding on there.

**Comment by treyharris** [comment]
Can someone please edit this issue so that it reads "tmux" and not "tux"?

**Comment by sdotz** [comment]
Would love this feature.

**Comment by yury** [comment]
2f pan gesture is terminal wheel now

**Comment by JeremyIglehart** [comment]
I'm super excited for this feature.  Every time I see the badge for the App Store I think - "Did they update Blinksh!?" :)

Just wanted you to know that there are some of us out there excited for this feature :)

**Comment by yury** [comment]
Hi @JeremyIglehart this feature is implemented in blink v13.0.

Set `set -g mouse on` on tmux config and you will be able to scroll tmux panes with 2f.
Set `set mouse=a` in vim and you will able to scroll in vim too.

Closing this issue. Feel free to reopen if needed.
