### ISSUE TITLE
Reimporting SSH key results in different fingerprint

### ISSUE THREAD

**Issue by levex** [blinksh/blink#587]
Unless I'm mistaken, the SSH public key fingerprint should be the same when I re-import the SSH private key.

Steps to reproduce:

* Select a key
* Copy Private key to clipboard
* Go back the Keys screen
* Tap `+` sign and Import from Clipboard
* Name it whatever and the two keys will have different fingerprints.

Hitting this on Blink v12.1

**Comment by randomtask2000** [comment]
I have experienced this issue as well when setting up a new iOS device from iCloud.

**Comment by levex** [comment]
Also worth noting that a fresh key's fingerprint does not match the output generated by `ssh-keygen -E md5 ...`

Fixing this would be great as I find it much harder to keep track of my keys without proper fingerprinting.

**Comment by carloscabanero** [comment]
This was a problem with LibSSH2. We now work with keys on OpenSSH directly. Closing.
