### ISSUE TITLE
Unable to switch languages when using external keyboard

### ISSUE THREAD

**Issue by solarfl4re** [blinksh/blink#588]
Using Apple’s Magic Bluetooth keyboard on my iPad Pro, I’m unable to switch languages using Ctrl-Space. I have to open the software keyboard and tap the globe to switch (to Russian, for example).
But after switching from the software keyboard, ‘Shift’ on my physical keyboard doesn’t do anything; to type a capital letter, I have to open the software keyboard, tap shift, and then type.

I hope this is something that can be fixed :)

**Comment by yury** [comment]
Hi @solarfl4re. 

Yep, confirming this issue. I think we should add an option to disable ctrl-space sequence.

**Comment by andrius** [comment]
same issue here. I did not realised earlier, because do need english for most of time in ssh

**Comment by yury** [comment]
Thank you for you feedback. Will be fixed in next release.

**Comment by andrius** [comment]
that works now in current version. I just upgraded my ipad and currently don't yet have smart keyboard, so using apple bluetooth keyboard. I can switch language pressing Control-Space. BUT! When I switch to the russian language, I cant enter capital letters

**Comment by yury** [comment]
Hi @andrius,

Can you post screenshot of your kb settings?

**Comment by andrius** [comment]
> Can you post screenshot of your kb settings?

Happy New Year and here it is:

![settings](
https://dl.dropbox.com/s/jd9t3z2zvyieahs/Photo%2002-01-2019%2C%2012%2011%2020.gif)

and issue:

![low-case letters with pressed shift](
https://dl.dropbox.com/s/ldn8pgolnqwdwn9/20190102_120910.GIF)
