### ISSUE TITLE
SSH vs SSH2 Connection closed by authenticating user [preauth]

### ISSUE THREAD

**Issue by schwartz1375** [blinksh/blink#593]
After the upgrade to 12/12.1 I get a Connection closed by authenticating user [preauth] on the server when using ssh, ssh2 works as expected thus also breaking mosh.  The server running Ubuntu 18.04.1 LTS with Duo Security configured.  Mosh and SSH via the CLI work as expect on Mac OS 10.14

**Comment by yury** [comment]
Hi @schwartz1375 
I think I fixed that already, but to make sure, can you post output from `ssh -vvvvvv host`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schwartz1375** [comment]
output from ssh -vvvv on blink v12.1.43 
ssh_connect: libssh 0.7.90 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.1
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.1
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.1
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.6 (70600)
ssh_connect: current state : 4
ssh_packet_socket_callback: packet: read type 20 [len=1076,padding=6,comp=1069,payload=1069]
ssh_packet_process: Dispatching handler for packet type 20
ssh_knownhosts_algorithms: server [REDACTED]:22 has ssh-ed25519 in known_hosts
ssh_knownhosts_algorithms: server [REDACTED]:22 has ssh-rsa in known_hosts
ssh_client_select_hostkeys: Changing host key method to "ssh-ed25519,ssh-rsa"
packet_send2: packet: wrote [len=516,padding=4,comp=511,payload=511]
packet_send2: packet: wrote [len=44,padding=6,comp=37,payload=37]
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=188,padding=8,comp=179,payload=179]
ssh_packet_process: Dispatching handler for packet type 31
ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
packet_send2: packet: wrote [len=12,padding=10,comp=1,payload=1]
ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
crypt_set_algorithms2: Set output algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
crypt_set_algorithms2: Set input algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
ssh_packet_newkeys: Signature verified and valid
ssh_connect: current state : 7
blink: setting socket keepalive: 1
packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_socket_callback: packet: read type 6 [len=28,padding=10,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [len=44,padding=6,comp=37,payload=37]
ssh_packet_socket_callback: packet: read type 51 [len=28,padding=12,comp=15,payload=15]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey

**Comment by yury** [comment]
Hmm, it is a little different. And output of `ssh -G host`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schwartz1375** [comment]
_printaddress no
_printconfiguration yes
compression yes
compressionlevel 6
connectionattempts 1
connecttimeout 20
exitonforwardfailure no
forwardagent no
forwardx11 no
hostname [REDACTED]
identityfile Ubuntu
kbdinteractiveauthentication yes
loglevel info
numberofpasswordprompts 3
passwordauthentication yes
port 22
pubkeyauthentication yes
requesttty auto
serveralivecountmax 3
serveraliveinterval 0
stricthostkeychecking ask
tcpkeepalive yes
user [REDACTED]
