### ISSUE TITLE
Text clipping on round edges on the new iPad Pros

### ISSUE THREAD

**Issue by premist** [blinksh/blink#594]
New iPad Pros(11, 12.9 inch) have rounded edges on the screen, and Blink shows text without margin so it appears clipped.

Using latest App Store version of Blink Shell(version 12.1).

![44e142dc-57ad-461b-aa7a-1d2134e232ee](https://user-images.githubusercontent.com/291078/48111489-0e235080-e295-11e8-9828-10ad88f61796.jpeg)

**Comment by xipher1** [comment]
Yes, adding a setting to add some padding to sides and top would be great.

**Comment by s8m2s** [comment]
An option to show the system status bar would also resolve this.

**Comment by yury** [comment]
Update:

Can't wait you to try new layout modes:
![img_4139](https://user-images.githubusercontent.com/5250/49329037-9b9f4b00-f58a-11e8-8434-856f70810304.jpg)

**Comment by s8m2s** [comment]
> Update:
> 
> Can't wait you to try new layout modes:

How did you handle the corners on the top edges?

**Comment by yury** [comment]
We have 3 modes (you can set default in config->appearance or change form control panel):

- Cover (edge to edge)
- Fill (space at top and bottom)
- Fit (5pts on all sides)

**Comment by sbromberger** [comment]
When will this be available as an app store update? I can't wait to give it a try!!!

**Comment by yury** [comment]
12.3 should be available for public TF

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by s8m2s** [comment]
how do we get access to the TestFlight builds?

**Comment by sbromberger** [comment]
I'd love an TF invite code if you have one. I use blink on a daily basis.

**Comment by yury** [comment]
I need your emails. You can dm me at discord or mail me yury.korolev@gmail.com

**Comment by sbromberger** [comment]
12.2 build 57 is currently the latest on TF.

**Comment by yury** [comment]
Hmm, it is still on review :(

**Comment by yury** [comment]
Ok, 12.3 should be available on TF

**Comment by premist** [comment]
Just updated Blink to 12.3 on my iPad Pro and it works wonderfully. Thank you! 🎉 
![29b970e5-ed04-45fc-ba01-d935cde833bd](https://user-images.githubusercontent.com/291078/49643809-09031e00-fa5a-11e8-85db-fe8316b51005.png)

**Comment by dgraziotin** [comment]
Sorry to resuscitate this, but with Blink v12.4.81. Jan  7 2019 and the iPad Pro 12.9” 2018, I have the rounded corners graphical issue.

**Comment by yury** [comment]
Hi @dgraziotin, what layout mode do you use?

Swipe 2 fingers up to show blink's control panel.
Fit and Fill modes should make margins.

**Comment by dgraziotin** [comment]
Apologies. I am kinda new to the app and missed out on these options. It works fine 👍. Thank you!
