### ISSUE TITLE
Blink shortcuts won't work when Cmd is used for Esc modifier

### ISSUE THREAD

**Issue by netj** [blinksh/blink#595]
Blink shortcuts (Cmd+T, Cmd+W, Cmd+O, Cmd+[ and ], etc.) doesn't seem to work when Cmd key is mapped to a modifier.
**It'd be nice if all the Blink app shortcuts would still work and the rest of the keys to be modified with Cmd.**

Somewhat related to #298.  Changing Blink shortcut to any combo excluding Cmd doesn't seem to work, so it's an exclusive choice over Cmd keys: Blink app shortcuts vs. terminal modifier

**Comment by welpo** [comment]
I'm having the same issue.

Even when setting the Shortcuts trigger to something like Alt, it's impossible to trigger them as long as Cmd is mapped to a modifier (Ctrl in my case).

**Comment by yury** [comment]
In blink 13.1 you can customize shortcuts.

Closing this issue. Feel free to reopen if needed.
