### ISSUE TITLE
New iPad Pro home bar (bottom) overlaps extended keyboard

### ISSUE THREAD

**Issue by noahkiss** [blinksh/blink#598]
Using an external keyboard with extended functionality enabled results in an overlap with the new omnipresent home bar.

**Comment by sbromberger** [comment]
Also, the first line is cut off in the upper left hand corner due to the new rounded display.

**Comment by s8m2s** [comment]
this also messes with the ability to swip to other apps by dragging left or right on the home indicator, since the section of the smart keys is also swipeable.

**Comment by yury** [comment]
@ccarter-cs do you use external kb or software on screen kb?

With external kb you can turn off smart keys via `config` -> `Smart Keys` -> `Show with external kb` option.

**Comment by ccarter-cs** [comment]
@yury Using the apple hardware keyboard. I'm talking about the little bar that was introduced on Iphone X and the 3rd gen ipad pros (AFAIK). I believe it is called the home indicator. It doesn't impact me physically, but it is an eyesore on my beautiful Emacs setup. Here is someone pointing directly at what I'm talking about. https://i2.wp.com/9to5mac.com/wp-content/uploads/sites/6/2017/11/home-indicator.jpg?resize=2500%2C0&quality=82&strip=all&ssl=1

**Comment by sbromberger** [comment]
Thanks! It’s causing a bit of a UI problem for the new iPads. 

Also, semi-related - the top line of text is cut off on the upper left and right corners due to the new rounded screen. Is there a separate issue to track this? (On mobile now)

**Comment by yury** [comment]
@sbromberger yep, #594

**Comment by yury** [comment]
Will be fixed in next release

![2DD27AF5-2431-48CE-A3C9-5F7D7C6EEDA3](https://user-images.githubusercontent.com/5250/64067819-8188bb00-cc37-11e9-864c-455f996c1186.png)

**Comment by yury** [comment]
We have pushed first public test flight release with this fix.
