### ISSUE TITLE
Copying private SSH key crashes the app

### ISSUE THREAD

**Issue by philippbosch** [blinksh/blink#599]
Upon tap on the  „Copy Private Key“ button in settings the app just crashes. 

Blink 12.1.43

**Comment by philippbosch** [comment]
I'm pretty sure I imported it from the clipboard. But that was a long time ago.

**Comment by philippbosch** [comment]
Copying the public key works btw, just not the private one.

**Comment by rfn01** [comment]
I’m having the same issue, and might know how to recreate.  I did an iCloud backup and then restored to a new iPad.  The new iPad crashes on copy private key.  The new iPad also can't authenticate.  Perhaps the private part of the key doesn’t survive a backup / restore?

I still had the old iPad, so I deleted the key on the new iPad, copied the private on the old iPad, and imported from clipboard on the new iPad.  This got everything working again - authentication and copy private both now work on the new iPad.

**Comment by Alnilam** [comment]
Same issue as @rfn01 from 1.5 years ago...

Using v13.5.1.237 . After moving from old device to new device, Blink shows existence of my id_rsa key, will copy the public key, but fails to use the key and crashes the app when, via config>keys>id_rsa, I attempt to copy the private key. 

Sadly, I don't have my old device and may have just lost significant connectivity into my remotes if this isn't recoverable :( Would have been nice to have been warned, given the option to store keys in icloud or keychain, or not misled by the artifact of the maybe-now-gone-forever showing up in config.

**Comment by neoighodaro** [comment]
Still have this issue. Is there a plan for this?

**Comment by carloscabanero** [comment]
Just to clarify and give a heads up on how we will proceed. Blink does not synchronize keys between devices. We do have a disclaimer inside the iCloud section where we mention that we do not. The default keys are always created on each device as part of Blink setup. 

The original issue talked about breaking when copying the private key, this may have been a bug back then but definitely not now as far as we know. In any case, all this code is being rewritten as we speak as we are changing the underlying key infrastructure.

We also have a way to securely sync keys between devices, but it is not available just yet.

Closing here.
