### ISSUE TITLE
iCloud sync of hosts doesn't seem to work

### ISSUE THREAD

**Issue by minoskt** [blinksh/blink#600]
I enabled blink's iCloud Sync through `config` on both my iPad and my iPhone, but the Hosts are not synced. I tried deleting all hosts and adding them as new entries but still getting the same result.

I tested this using the latest version of blink 12.1 and iOS 12.1. I am a new user so maybe I am missing something.

**Comment by comfortablynick** [comment]
I am likewise not getting anything at all over iCloud sync. I turned it on on both devices as soon as I downloaded the app.

Loving the app, but I'd like to have my devices sync settings.

**Comment by yury** [comment]
Ok, we forgot to publish new iCloud schema to production. Will be fixed today.

**Comment by mdecaro** [comment]
iCloud synching not working for me.  Where is the iCloud schema?

**Comment by stueja** [comment]
Same for me. config > iCloud Sync > switch on. Go back to Settings: iCloud Sync is off. 
How can I enable iCloud Sync?

**Comment by yury** [comment]
@stueja please update to blink 13.5.5 we temporary disabled iCloud in 13.5.4

**Comment by stueja** [comment]
Excellent, and lightning fast. Thank you very much!
