### ISSUE TITLE
mosh hangs forever (ios12)

### ISSUE THREAD

**Issue by kurko** [blinksh/blink#601]
Blink: v12.1.43. Nov  2 2018

Running mosh, it either freezes there forever or gives me error below. I have to then kill the app and reopen.  I was able to connect only once.

When I ssh into the server and run `mosh-server`, it gives me a port, which I try to then use (in the hosts configuration I change the UDP port).

```
blink> mosh myserver
Failed binding to xxx.xxx.xxx.xxx:60010
Error binding to IP xxx.xxx.xxx.xxx: bind: Address already in use
Failed binding to 0.0.0.0:60010
Error binding to any interface: bind: Address already in use
Network exception: bind: Address already in use
Did not find remote IP address
```

I killed the `mosh-server` instances via SSH (`ps auxf|grep mosh`). I still get this error though. `mosh-client` isn't available in blink so there's nothing more I can do to debug.

Anything I can do to fix this?

**Comment by carloscabanero** [comment]
Closing as old.
