### ISSUE TITLE
ALT key

### ISSUE THREAD

**Issue by mitermayer** [blinksh/blink#603]
How can i use ALT combinations as a modifier within blinksh ? 

I have been trying to use the ALT combinations with my external keyboard folio 2 on the 2018 ipad pro without success

**Comment by yury** [comment]
Hi @mitermayer 

By default alt is not configured as any modifier, but you can change that in `config` -> `Keyboard`. 

![GitHawk Upload by yury](https://i.imgur.com/8DwSc2T.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
