### ISSUE TITLE
How to set TERM environment variable?

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#604]
I’d like to configure blink so that my remote host recognizes `xterm-256color-italic` as my `TERM`. Is there a way to do this in blink config?

**Comment by igorlima** [comment]
Have you tried:
```sh
setenv TERM xterm-256color-italic
```

later, type the following to make sure if the env var was set properly:
```sh
env
```

The command `env` will display all environment varriables set

**Comment by yury** [comment]
Messed up with GitHub comment. But [this commit](https://github.com/blinksh/blink/commit/9226db94e5fbb151933fc35b29e590091207181a) fixes that.

**Comment by sbromberger** [comment]
Thanks! I’ll give it a try.

**Comment by yury** [comment]
It will be in TF 12.4 build 81 soon

**Comment by yury** [comment]
Hi @sbromberger.

v12.4 is out with the fix. Please reopen if something not ok for you.

Thank you.

**Comment by sbromberger** [comment]
Thanks, @yury ! I can confirm that the `TERM` environment is passed. Is there a way to set it per-host in the config so I don't have to remember to `setenv` for each new blink window?

**Comment by yury** [comment]
Hi @sbromberger,

Lets do it as another issue?

**Comment by sbromberger** [comment]
Ref #676
