### ISSUE TITLE
After latest testFlight, CTRL+SPACE brings up emoji 

### ISSUE THREAD

**Issue by saptarshiguha** [blinksh/blink#606]
Hello,

I updated to 12.2.47 and now when in emacs CTRL+SPACE which starts a selection now brings up the emojis and keyboard choice!!
Moreover, "grabbing CTRL+SPCE" option in blink doesn't seem to save that option so not sure how to use.
What could i remap CTRL+SPACE to in emacs to make this work in the interim?

**Comment by yury** [comment]
Grab ctrl+space option should work. Can you try to set this option and restart blink?

**Comment by saptarshiguha** [comment]
this is what i mean. I enter settings, check the box, go back and press the X on the top left.
![5c1221de-fcd7-42c2-ab2e-f10aa73b6804](https://user-images.githubusercontent.com/113324/48286635-22915580-e41b-11e8-88be-ebec3432b1f7.jpeg)

When i type config again, that box is *not* checked .

**Comment by yury** [comment]
My fault. Fixed

**Comment by saptarshiguha** [comment]
Super! Thanks much. Meanwhile I had set ctrl+q as my selection key in emacs and was getting used to it. Good to have alternatives.

Looking forward to the test flight update.

**Comment by kek** [comment]
I’m not sure if it’s right to comment here or to open a new issue. But in iPadOS 13.0 (17A5547d), this seems to happen again. Control-space doesn’t go through to the application but rather switches input languages, regardless of ”Capture control-space” setting. A workaround is to disable all alternative input languages and the emoji input method under the keyboard settings of system preferences.
