### ISSUE TITLE
Updates to support new 2018 iPad Pro models

### ISSUE THREAD

**Issue by s8m2s** [blinksh/blink#608]
The new 2018 iPad pro’s have rounded screen corners that cut off the on screen text when the prompt is at the top of the screen. 
![img_4829](https://user-images.githubusercontent.com/1937285/48301769-3394a200-e4c1-11e8-846a-a24f8b5a3cbc.jpeg)

If the smart keyboard folio is attached. the smart keys get covered by the home indicator.
![img_4831](https://user-images.githubusercontent.com/1937285/48301826-d6e5b700-e4c1-11e8-914e-00d38919870d.jpeg)

**Comment by s8m2s** [comment]
duplicate issue.
https://github.com/blinksh/blink/issues/594
https://github.com/blinksh/blink/issues/598

**Comment by yury** [comment]
Why do you need smart keys with folio KB? Just interesting...

**Comment by s8m2s** [comment]
> Why do you need smart keys with folio KB? Just interesting...

esc, key... but yeah I just disabled it and remapped the caps lock to esc.
still there shoud be some ui accomodation for this if the option to keep the smart keys whith ext keyboard exists.

**Comment by yury** [comment]
Thank you for your feedback.

We are working on new smartkeys. I think we will deliver it next week. Still waiting for my iPad Pro.
