### ISSUE TITLE
Support for newest mosh (256 colors)

### ISSUE THREAD

**Issue by moxuz** [blinksh/blink#609]
Hi,
In current mosh-stable 256 color support is not implemented. Would it be possible for the user to configure Blink to use the newest dev version of mosh from the mosh repository? This supports 256 color and fixes a lot of color issues with regards to vim themes on remote servers.
(Or could Blink support this by default? I ask for maybe a user configurated option since it’s not yet in stable so I doubt it could be the Blink default).
Thanks!

**Comment by NightMachinary** [comment]
I suggest waiting for the full 24-bit color support.

**Comment by ineghi** [comment]
Any news on this ?

**Comment by yury** [comment]
Progress update:

![IMG_0076](https://user-images.githubusercontent.com/5250/57702370-97fa0f00-7666-11e9-8d34-905cc9fbb20b.PNG)

**Comment by aanari** [comment]
Awesome! Is this coming in the next release?

**Comment by yury** [comment]
We should release this week.

**Comment by aofei** [comment]
Hi @yury, I'd like to know if the next release will solve the problem in the pic below?

Solarized Dark Blink+Mosh+Tmux+Solarized Dark Vim

![fullsizeoutput_9e2](https://user-images.githubusercontent.com/5037285/59558629-06950880-9029-11e9-8898-dc280cab716e.jpeg)

**Comment by aofei** [comment]
Update:

The workaround I'm using now is to place `let g:solarized_termtrans=1` in `.vimrc`, which I found from [here](https://github.com/altercation/vim-colors-solarized#option-details) and [here](https://github.com/altercation/vim-colors-solarized/issues/138). And this workaround causes the color displayed by Blink to be inconsistent with macOS Terminal. Note that Termius doesn't have this problem, so I'd love to know why.

**Comment by treyharris** [comment]
From this thread I was thinking the TestFlight version that just dropped (12.9 Build 105) would have this, but maybe not, or maybe there’s something more that must be configured by the user on one end or the other?

ssh:
![IMG_0741](https://user-images.githubusercontent.com/97895/59858151-6d2b6680-9348-11e9-9f39-f1d38c492b89.png)

mosh:
![IMG_0742](https://user-images.githubusercontent.com/97895/59858171-73b9de00-9348-11e9-92ee-335de9127de5.png)

(The script I’m using is [here](https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh); it’s using the `^[48;2;<r>;<g>;<b>m` form for background color, which seems to be the most common and the one that’s also demonstrated in the AWK script posted by @yury above.)

**Comment by yury** [comment]
@treyharris you have to install mosh server from master too. (`brew install --HEAD mosh` on macOS)

**Comment by treyharris** [comment]
@yury Oh! I thought from the earlier commit that 1.3.2+ was what was required. Okay, I’ll give that a try.

**Comment by treyharris** [comment]
@yury Perfect!

Formerly:
```
Package: mosh
Version: 1.3.2-2build1
...
```

Now:
```
Package: mosh
Version: 1.3.2+1354-0ppa~ubuntu18.04.1
```
![IMG_0744](https://user-images.githubusercontent.com/97895/59860755-81be2d80-934d-11e9-9abb-d5a9c7a2b771.jpeg)

**Comment by yury** [comment]
Ok, closing this issue. Feel free to reopen if needed.
