### ISSUE TITLE
Only "keys" option in config works (build 0.722 (24))

### ISSUE THREAD

**Issue by strowger** [blinksh/blink#61]
Hi,

Thank you for adding me.

I can start blink OK and type "config". The menu appears and I can select "keys" and successfully create a key, copy it to the clipboard, etc.

None of the other options in "config" work. If I hit "hosts", "appearance", "keyboard", "shortcuts", or "about", the option goes grey but does not open.

Cheers

**Comment by carloscabanero** [comment]
Not an error, will clarify on next version.
