### ISSUE TITLE
Powerlevel9k

### ISSUE THREAD

**Issue by jiahao-shen** [blinksh/blink#611]
The zsh theme of my host is powerlevel9k.When Iogin,it shows messy code although I import the awesome terminal font and powerline.

**Comment by yury** [comment]
Hi @jiahao-shen,

Can you post screenshot?

**Comment by jiahao-shen** [comment]
This is my .zshrc file.I changed many fonts, but it always shows messy code.
![7cd81083-7f7d-44a3-a3a9-15fb0a37b579](https://user-images.githubusercontent.com/29255648/48388738-63e47680-e735-11e8-8eb6-121a9b60ea2d.png)
![b6828533-6bc5-43e5-8de3-fc0505e36aa6](https://user-images.githubusercontent.com/29255648/48388739-647d0d00-e735-11e8-98a5-021a313619d0.png)
![5c23d357-9bb3-40ff-bd0f-02122ceae175](https://user-images.githubusercontent.com/29255648/48388741-6515a380-e735-11e8-957c-9d78954f2b71.png)

**Comment by jiahao-shen** [comment]
I import the [font-awesome](
https://fontawesome.com/),but it cannot render successfully.The css file is 
https://use.fontawesome.com/releases/v5.5.0/css/all.css.

**Comment by jiahao-shen** [comment]
Thank you,i will try and reply to you later.

**Comment by jiahao-shen** [comment]
Thank you very much.I have solved by installing fonts through AnyFont APP.

**Comment by yury** [comment]
Closing?

**Comment by jiahao-shen** [comment]
Yes, you can.

**Comment by carloscabanero** [comment]
Should we get rid of the old CSS way of doing things? It was great but now maybe just providing instructions or a way to install a font would be best
