### ISSUE TITLE
Request: better arrow key alternative

### ISSUE THREAD

**Issue by MasonProtter** [blinksh/blink#613]
So currently if you’re using the onscreen keyboard, navigating with the arrow keys above the keyboard is not ideal. One better solution I saw implemented was in [iSH](
https://github.com/tbodt/ish) where they just have a single button which you drag in the direction you want the arrow key to be pressed. If you drag and hold, it’ll press repeatedly and the further you drag, the faster it repeats.

**Comment by yury** [comment]
Yep, will try to implement that.

**Comment by MasonProtter** [comment]
Loving the app by the way!

**Comment by yury** [comment]
Status update:

https://youtu.be/TCU8NK8w8Rc
