### ISSUE TITLE
Commands should work if typed with the first letter as a capital

### ISSUE THREAD

**Issue by strowger** [blinksh/blink#62]
ie "mosh" works at your commandline, so should "Mosh".

This is friendly for people with automatic capitalisation set up on their keyboards.

Low-priority/nice-to-have.

**Comment by goerz** [comment]
My understanding is that automatic capitalization is under the control of the application (and obviously, Blink or any other terminal app should not have anything like auto-capitalization or corrections)

**Comment by strowger** [comment]
I thought it was in settings>general>keyboard

I am often wrong.

Swype seems not to respect the system-wide setting anyway.

**Comment by carloscabanero** [comment]
We have auto capitalization disabled at the app, which I think is how it has to be on a terminal. Imagine otherwise the mess once you get to the remote machine ;)
