### ISSUE TITLE
Allow to forbid private key export

### ISSUE THREAD

**Issue by timothybasanov** [blinksh/blink#622]
It would be nice to be able to lock private keys on a device. 
Ideally in a way that would permanently lock the keys to a device-specific key bag. 

Rationale: Just like private keys to say bitcoin wallets private keys should not be exportable. I do not want to risk of losing access to my servers just because somebody had my iPad in an unlocked state for a minute. There are no audit logs or traces, so it’s impossible to tell if my keys were stolen.

**Comment by carloscabanero** [comment]
Closing here. The app can be locked and we have special keys like SE keys that will block this.
