### ISSUE TITLE
Private key names cause merge problems with iCloud sync

### ISSUE THREAD

**Issue by timothybasanov** [blinksh/blink#623]
I use different private keys for different devices, so I can revoke them separately. 
Blink has a very convenient feature to sync up hosts configuration to allow me to access same hosts from all devices. 
Private key name is a field in a host config and it causes merge conflicts between devices. 

Workaround: rename keys after creation to make them match. Actual key name within a public key would not be updated, so you still can copy and paste to authorized hosts.

**Comment by carloscabanero** [comment]
Sorry to re-open an old topic, but I was revisiting all the keys issues.

This is by design, the idea is that you create different keys but with same name under different devices. You can use the comment to differentiate them.
