### ISSUE TITLE
File tab-completion doesn't escape whitespace or other illegal characters

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#627]
To reproduce:

1. Create a local file (any method) with a filename containing spaces.
1. Attempt to operate on it with any command, e.g. **`open My`** + **`⇥`**

#### Expected result:

The completion is filled in a format that can be used,  e.g., `open My\ Playground.playgroundbook` or `open 'My Playground.playgroundbook`.

#### Actual result

The completion is filled in bare without escaping or quoting, so that the arguments are misinterpreted: `open My Playground.playgroundbook`.

Other illegal or ambiguous CLI characters need escaping as well, such as fileglob operators (`*?[^]`, etc.). Filenames may also include newlines but that may need a different solution—I've been able to create such a file, but except for using the `*` glob (which wouldn't work if there were multiple matches), I have no way to operate on it.

**Comment by yury** [comment]
Blink 13 is out with a fix.
