### ISSUE TITLE
Error “Did not find IP address “

### ISSUE THREAD

**Issue by daverose** [blinksh/blink#628]
Can’t connect t Digital Ocean droplet with mosh installed. The nslookup utility and ping locate the correct IP. I am able to connect using other computers. I paid for the app thinking it is fully baked. Is this not the case?

**Comment by yury** [comment]
Hi @daverose,

Blink is fully baked, but I think you have to install mosh server on your droplet. (`apt-get install mosh` for ubuntu).

**Comment by daverose** [comment]
Hi Yury , it is and I can mosh into it from other computers without issue.

**Comment by yury** [comment]
Don’t know how I have read your issue (sorry for that).

Can you share your config for host?

For instance,

![2cfbd62c-9589-48f7-b0e6-59166f10710d](https://user-images.githubusercontent.com/5250/48969364-a39d3f00-f00e-11e8-91ab-54c014e3ba96.jpeg)

So, I use `mosh office` to connect to my office iMac.

**Comment by daverose** [comment]
Thanks for helping Yury.

**Comment by yury** [comment]
Hi @daverose,

Does mosh works for you if you use (-2 flag) `mosh -2 <host>`.

How do you add key to blink? (`config` -> keys or ssh-keygen)

**Comment by daverose** [comment]
It does not and the behavior is slightly different than when I use the
terminal on my Mac. It seems to first try shh and then mosh. The password
request seem to be for an ssh user ID rather than the key's password.
Shouldn't the prompt text say something like "Please enter the passphrase
for the ssh key"?

**Comment by paulgit** [comment]
I had the same issue and running `mosh -2` or `ssh2` seems to solve the issue. But what has changed? Is it possible to make this the default behaviour, typing `-2` is a little inconvenient.

**Comment by yury** [comment]
Hi @paulgit,

We really want to track down that issue with ssh command. Because new ssh is more advanced (proxy command, direct/reverse port forwarding, compression, ssh agent) and we want to keep it.

Can you provide logs from `ssh -vvvvvvvv host`?

**Comment by paulgit** [comment]
Hi Yury, I am not really confused. For days I have not been able to connect, saw this issue and did the work around. Now I am able to connect to *some* of my servers normally.  I have no idea why.

Once I can get a log for you I will post it.

**Comment by daverose** [comment]
Guys,

I think that it’s having a problem with my key being encrypted. I’m still not able to connect. This is an iPad Pro 11” with iOS 12.1 

ssh_packet_socket_callback: packet: read type 31 [len=188,padding=8,comp=179,payload=179]
ssh_packet_process: Dispatching handler for packet type 31
ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
packet_send2: packet: wrote [len=12,padding=10,comp=1,payload=1]
ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: Processing 208 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
crypt_set_algorithms2: Set output algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
crypt_set_algorithms2: Set input algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC input algorithm to hmac-sha2-256
ssh_packet_newkeys: Signature verified and valid
ssh_packet_socket_callback: Processing 192 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 7 [len=156,padding=14,comp=141,payload=141]
ssh_packet_process: Dispatching handler for packet type 7
ssh_packet_ext_info: Received SSH_MSG_EXT_INFO
ssh_packet_ext_info: Follows 1 extensions
ssh_packet_ext_info: Extension: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
ssh_connect: current state : 7
blink: setting socket keepalive: 1
packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_socket_callback: packet: read type 6 [len=28,padding=10,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [len=44,padding=8,comp=35,payload=35]
ssh_packet_socket_callback: packet: read type 51 [len=28,padding=12,comp=15,payload=15]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
blink: using auth methods attempt: 1 of 5
blink: import key id_rsa
ssh_pki_import_privkey_base64: Trying to decode privkey passphrase=false
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
packet_send2: packet: wrote [len=1148,padding=15,comp=1132,payload=1132]
ssh_packet_socket_callback: packet: read type 51 [len=28,padding=12,comp=15,payload=15]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey
blink> 

Thanks,
Dave Rose

**Comment by daverose** [comment]
Yury,

I’m pretty sure I created it with ssh keygen on MacOS 

If the key is encrypted, where do you put the PW, because I put it in the password section of the config and it didn’t work. I tried it without the key PW to see if I get a prompt, but no prompt.

**Comment by treyharris** [comment]
@daverose Please see https://github.com/blinksh/blink/issues/522#issuecomment-440684397 — because keys are stored in the Secure Enclave, the additional layer of password protection isn't supported specifically for ed25519 keys (note they use a different type of password encryption than RSA or DSA keys with different semantics—for instance, an ed25519 key's password can be of any length).

You can use `ssh-keygen -p -f ${keyfile}` on Linux or macOS to remove the password (enter the old password, then hit enter twice), or you can use an RSA or DSA key with a password. Given how Blink stores the password for you in the latter case, I'd suggest just unencrypting the ed25519 key. (If you use it on other hosts where you need the password, you can copy it before removing the password or you can remove the password and then set it again after you've copied it into Blink.)

**Comment by gregorybclark** [comment]
Did this get solved?  I am having the same issue today. 

Blink is completely not working for me now

**Comment by Felias1701** [comment]
Hi there,

i’m having this issue as well on my iPad and a local server. I have 2 users that are set up identically, ssh-keys being setup using Blink. 

The weird thing is: I can connect to the server without a problem with one user, while the other gets “did not find ip address”. I connect to the users with separate hosts configured in Blink, that are identical except the username and key-file.

Any ideas would be well appreciated.

**Comment by carloscabanero** [comment]
These are usually configuration issues. Is this still an issue? Are you able to connect using ssh to that server?

**Comment by Felias1701** [comment]
thank you for your reply. I'll check again and report back if it's still persistant.

**Comment by pimoore** [comment]
I’m having this issue and error connecting with a key, but I can successfully connect to that same machine/IP address with the same key in Secure Shellfish?

**Comment by iDuuck** [comment]
I have the same problem. Logging in as root is working. Logging in as a user is not.

**Comment by carloscabanero** [comment]
I don't think there is an issue anymore with this.

The "Did not find IP address" means that mosh-server could not be initialized at the server, and the IP parameters could not be found. Unfortunately that is the standard mosh message for this error, which is confusing. As we have a layer, I will try to improve it from our side.

If you are having this issue, please try to:
1. Connect using ssh to the same server / user.
2. Figure out if mosh-server is reachable by the user. Try to execute ssh <server> -- mosh-server and see if anything is returned.
3. Normally, mosh-server is installed in the regular path. On MacOS, with package managers, that is not true and it may end up in an /opt/whatever/bin. In that case, configure the Mosh-server parameter inside settings, or pass it as a flag.

I'm closing here so we do not mix any issue, but feel free to open a new one.

One more thing, moving to the community.blink.sh version is recommended, as the latest and greatest is there for now while we complete testing.

Thanks!!
