### ISSUE TITLE
ctrl key is hard to use on phone

### ISSUE THREAD

**Issue by strowger** [blinksh/blink#63]
The ctrl key is at the very left of the screen and quite small.

screen/tmux users use ctrl extensively.

The small button is hard to hit, especially if using a phone which is in a protective case of some sort. It is also easy to accidentally execute an ios swipe-from-left when pressing ctrl.

A larger/wider button might be good. 

This is probably a low-priority issue.

**Comment by carloscabanero** [comment]
Yup, my idea is to have the other helper keys collapse. Will improve after release.

**Comment by joeshaw** [comment]
Related to this, you have to hold down the ctrl key to send a key combo.  This is a bit different from most on-screen keyboards where these kinds of keys enable a mode.  (for instance, the shift key.)  It took me a while to figure this out.  You might want to consider making it sticky until the next keypress, like shift.

**Comment by carloscabanero** [comment]
I like the continuous press a lot more because on emacs we are all the time with Ctrl pressed. It resembles better the real keyboard behavior. I will make it so that a single tap leaves it pressed, but a long tap will release after key is up.

**Comment by carloscabanero** [comment]
- [ ] Turn the non-modifiers section into a scrollable view of keys to make better use of space.
- [ ] Make the Non-modifiers section bigger, and add the ESC key to the left stack area (between Ctrl and Alt).
- [ ] Remove button styling (no rounded borders) to give sense of better spacing. Maintain the same background colors when not selected. Show the button with rounded borders shape in blue after tapping.

**Comment by carloscabanero** [comment]
Completed on v1.101. Please let me know if you think this can still be improved :)
