### ISSUE TITLE
ECDSA Key Generation Ignoring Bit Length

### ISSUE THREAD

**Issue by jaydenk** [blinksh/blink#632]
Selecting ECDSA as a key type ignores the bit length when a new key is generated, generating only 256-bit keys. Selecting 384 or 521-bit length keys result in 256-bit keys.

**Comment by jaydenk** [comment]
![79ccab9c-321c-4973-acb8-c0b75f6559b2](https://user-images.githubusercontent.com/7180754/49080625-2edb3680-f294-11e8-944f-d93c7a2b57a6.jpeg)

**Comment by jaydenk** [comment]
![img_0318](https://user-images.githubusercontent.com/7180754/49080696-5fbb6b80-f294-11e8-8496-4a832cb591cb.GIF)

**Comment by yury** [comment]
Hi @jaydenk.

Thank you for your finding 👍 .
Actually 256 and 384 working as expecting, but 521 bit parameter value is [handled wrong in libssh](https://gitlab.com/libssh/libssh-mirror/blob/master/src/pki_crypto.c#L561)

I have added temporary workaround. And I will report that issue to libssh team.

**Comment by jaydenk** [comment]
Ah! So it does. That'll teach me for tapping without looking. 

Thanks @yury

**Comment by yury** [comment]
Hi @jaydenk.

We just released v12.4 with updated libssh (with the fix).

Closing the issue.

Thank you.
