### ISSUE TITLE
Hitting Ctrl+Space twice in local “blink>” shell caused crash when “Grab Ctrl+Space” is enabled

### ISSUE THREAD

**Issue by hayamiz** [blinksh/blink#633]
Hi,

I found that hitting Ctrl+Space twice in local “blink>” shell caused crash when “Grab Ctrl+Space” is enabled.
Hitting Ctrl+Space, then Enter, also caused crash.

When I’m in a ssh session or a mosh session, hitting Ctrl+Space never causes crash so far. It seems that the problem is only about local shell. Usually I’m 100% in a mosh session and practically there is no problem, but I just report it FYI.

Several example key strokes that caused crash:
* `[Ctrl+Space][Ctrl+Space]`
* `[Ctrl+Space]foobar[Ctrl+Space]`
* `[Ctrl+Space][Enter]`
* `[Ctrl+Space]foobar[Enter]`

My environment:
* Blink: v12.2.57. Nov 16 2018
* iPad Pro A1701 with Smart Keyboard (JP)
* iOS 12.1

Anyway I’m a great fan of Blink Shell and would like to appreciate your great work :)

**Comment by yury** [comment]
Fixed in recent versions.

Closing, feel free to reopen.
