### ISSUE TITLE
bad access when piping `cat`

### ISSUE THREAD

**Issue by balboah** [blinksh/blink#637]
On iPad Pro, running:
`cat .inputrc | cat > foo` results in crash with `EXC_BAD_ACCESS`.

Discovered this while trying to figure out how to transfer files to remote. Got scp working after doing the quirks listed in https://github.com/blinksh/blink/issues/564  (ssh2 and full path)

Version ebc1b01e with remote notifications etc turned off for the free developer account.

**Comment by treyharris** [comment]
I can duplicate this issue. Just running `echo hello | cat | cat` is sufficient to cause an immediate app-crash (though `echo hello | cat` does the right thing).

**Comment by holzschu** [comment]
Found. It was an issue with static variables inside a function, so it was specific to the `cat` command (I did check multiple pipes with `grep`, but not with `cat`). Fix with commit b3868b0 in `ios_system`, will be in release 2.1.

**Comment by yury** [comment]
Hi @balboah,

v12.4 is out with the fix. Closing the issue.

Thank you.
