### ISSUE TITLE
Does Blink have something similar to .bashrc? 

### ISSUE THREAD

**Issue by MuhammadAbdElGani** [blinksh/blink#638]
Does Blink have something similar to .bashrc? script or the ability to add a script that will run automatically every  time the app launched? 

currently, whenever i want to launch the app i need to execute the following to run python: 
setenv PYTHONHOME .....
setenv PYTHONPATH ......

and then run
python example.py

i wonder if i can add this three command to a file inside Blink container , and Blink will then do all the work for me 
i already found how to  deal with setenv from AppDelegate.m, all i need is to found a way to run a command automatically whenever the app launched (e.g running curl)  . however i dont like this way, because in this case  i need to maintenance a patch of Blink in our project. but will be happy to hear also a solution for this  in case what i'm asking for (in the title) is not offered  by Blink

**Comment by yury** [comment]
No, currently blink doesn't have rc. But any PR would be welcomed.

**Comment by yury** [comment]
Yep, now blink supports `~/blink/profile` file for basic envs var setup. (But you need to restart app)

Thank you!

**Comment by hiroshima-devs** [comment]
@yury I created a `~/.blink/profile` and wrote an alias but to no avail. Any more step?

**Comment by yury** [comment]
I think it is for ENV vars only, not for aliases... 
cc @carloscabanero

**Comment by carloscabanero** [comment]
We only support ENV variables, and not aliases. For aliases we have Snips, and something new coming up on Blink 19.
