### ISSUE TITLE
Shell navigation shortcut behavior improvements

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#641]
The shortcut overlay:
![img_0494](https://user-images.githubusercontent.com/97895/49345428-ae7d5280-f652-11e8-897c-a4e424060775.png)
suggests that ⌘-0 should be first and ⌘-9 should be last. And ⌘-0 does change to the first tab in most tab-oriented apps. But in Blink, ⌘-1 is first and ⌘-0 is tenth.

It's possible you also might want to adopt the tab behavior from apps like Chrome and Vivaldi where
1. Tabs are zero-indexed so that ⌘-0 always refers to _first_
1. ⌘-9 always refers to _last;_ when you have 11 tabs, ⌘-9 goes to the 11th tab, when you have 30 tabs it goes to the 30th, etc. This is useful when you accumulate a large number of tabs/shells to have a way to jump to the end without repeatedly pressing ⌘-].
1. There is _rollover_: pressing ⌘-[ on the first tab cycles to the last, and pressing ⌘-] on the last tab cycles to the first.

**Comment by yury** [comment]
Hi @treyharris,

I added `Switch to last tab`, `Next tab (cycling)` and `Previous tab (cycling` commands. So we new shortcut system you can map them to combos you want.

Will be in Blink v13.1.187
