### ISSUE TITLE
Pwd / root path iPadPro

### ISSUE THREAD

**Issue by proportional** [blinksh/blink#642]
I just installed Blink in my iPad Pro 3rd gen through the app store. When get the following output for the pwd command [edited, (after `cd iCloud` , apparently the only folder )]

`/private/var/mobile/Library/Mobile Documents/iCloud~com~carloscabanero~blinkshell/Documents`

I’d like not to have Carlos Cabañero’s name (App developer) not to be in the path.
Is there any way to customize this ?

**Comment by goerz** [comment]
I think that's just the way the iOS file system works

**Comment by levifig** [comment]
> I think that's just the way the iOS file system works

This is correct. Blink's filesystem (and any other app's, for that matter) is sandboxed inside Blink's local cache folder, which is named automatically by iOS based on the bundle identifier (which has that "reverse domain name" format, except it substitutes the dots with tildes, for syntax reasons).
