### ISSUE TITLE
Nerd fonts support

### ISSUE THREAD

**Issue by mikelxc** [blinksh/blink#643]
I was connected to a Linux server that has SpaceVim and nerd fonts set up locally. However, I was not able to view the icons that requires a nerd font.
I went on to install the nerd font using the app using an embedded css (https://soociao.com/meslo.css). The app recognizes it and installed it locally. However, after the installation, the app loading speed decreased dramatically and the icons are still not able to display properly.
![765bfa4f-179e-4833-acf9-ceaa32269c2e](https://user-images.githubusercontent.com/20431963/49423669-3acc6a00-f766-11e8-8d4a-ec4bf7c740fc.png)
![491c3918-9e7b-44ef-b4f7-a518a9ce82bd](https://user-images.githubusercontent.com/20431963/49423670-3b650080-f766-11e8-85dc-048b291fb277.png)

**Comment by yury** [comment]
Hi @mikelxc,

I have fixed regular expression for detecting font-family. But this font has wrong line height for glyphs and we can't fix it in web view font rendering.

You can get it working in current version if you put `font-family` on separate line [like in this font](https://raw.githubusercontent.com/blinksh/fonts/master/Ubuntu%20Mono.css).

**Comment by yury** [comment]
Related issue #498

**Comment by mikelxc** [comment]
Thank you for your information. 
![156beaff-988b-4628-81e7-006d84dcf9e0](https://user-images.githubusercontent.com/20431963/49461336-6892cc80-f7c1-11e8-8746-119ab4c720fd.png)
Icons are working right now
