### ISSUE TITLE
Mosh screen history broken

### ISSUE THREAD

**Issue by sylvoie** [blinksh/blink#646]
Hi,

I took a look of already open issues, did’nt find that one. I need your help?

When I use mosh and I « cat » a script « UTF-8 Unicode text executable » file, I’m not able to get screen/session history to see the top of the file that is longer than my screen.

I « cat » the same file in ssh, and i’m able to scroll the screen and get history.

Thank’s

Sylvain

**Comment by yury** [comment]
This is how mosh is currently works, see  mobile-shell/mosh#122

You can run screen or tmux to get scroll back working.

**Comment by sylvoie** [comment]
Ok thank you.

**Comment by yury** [comment]
Since this is how mosh is working right now I close this issue.
