### ISSUE TITLE
Feature Request: Support for a document picker to open another app’s folder

### ISSUE THREAD

**Issue by kkk669** [blinksh/blink#647]
I would like to open another app’s directory by a document picker and then modify files using built-in command line tools on Blink. I believe it makes Blink Shell more powerful tool.

[LibTerm](https://github.com/ColdGrub1384/LibTerm) already supports the feature, like this: https://youtu.be/1roN-P3xNO0

**Comment by yury** [comment]
Hi @kkk669,

[Blink supports that](https://twitter.com/WorkingCopyApp/status/1002304522176356352). But it is more advanced than OpenTerm. It doesn't switch your home folder but mounts other folder inside. 

Command called link-files.

**Comment by kkk669** [comment]
@yury I’m sorry. I didn’t know that. Thank you.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
