### ISSUE TITLE
mosh asks to trust the host key before displaying it

### ISSUE THREAD

**Issue by cjay** [blinksh/blink#648]
Title says it. Hashed host key is displayed after answering yes/no. Can be reproduced by deleting or moving .ssh/known_hosts.

Also, it seems blink decided by itself to use ed25519 with a host that was already in known_hosts with rsa, resulting in the question to trust the host key when I didn't expect it. It made me think someone was trying a MITM attack..

**Comment by yury** [comment]
Hi @cjay,

v12.4 is out with the fix. Feel free to reopen issue if you find it is not working for you.

Thank you.
