### ISSUE TITLE
Allowing to map „^" as ESC (Germany keyboard layout)

### ISSUE THREAD

**Issue by rverton** [blinksh/blink#649]
It would be really nice if we could also use the „^"-key as an ESC key. This key is on the same position on the german keyboard as the backquote key for the English keyboard layout.

![Germany Keyboard Layout](https://www.arktis.de/media/image/f5/07/d4/ipad-pro129-keyboard.jpg)

I‘m reposting this as an issue because I don’t know if this is getting attention in the closed PR.

_Originally posted by @rverton in https://github.com/blinksh/blink/pull/619#issuecomment-443507442_

**Comment by vorband** [comment]
this would be greatly appreciated. 👍🏻

**Comment by j4mie** [comment]
And similarly on the UK 2018 version the top-left key is this:

![image](https://user-images.githubusercontent.com/6988/50226887-4b9ef180-039c-11e9-84de-522519b4bdb4.png)

It would be great if that could be Escape! 😄

**Comment by vorband** [comment]
maybe it would make sense to have a custom config option which allows the user to enter a certain character which is then mapped to esc? 
I guess apple has several keyboard layouts floating around...

**Comment by yury** [comment]
Ref #694 here too

**Comment by darthdeus** [comment]
@j4mie Actually I think the UK layout is the same as the Czech one I posted in #694. Not that it's bad (actually it's good for me, since I'm probably the only person with a Czech layout who cares about this hehe), just pointing it out since I found it interesting :)

**Comment by vorband** [comment]
@yury: any chance of implementing this? Using caps lock as esc has some quirks, as it sets the caps lock status globally, so every time I end up with CAPITALS WHENEVER I SWITCH BACK FROM BLINK TO ANOTHER APP:::: (scnr)  ;)

**Comment by yury** [comment]
Hi @vorband.
It is on the list.

`cmd+.` also works as esc. And it is iOS system wide shortcut for ESC. May be it could work for you for now.

**Comment by vorband** [comment]
@yury: Thank you, this works for now. I did not know this was a system wide shortcut. I will try to remember this now! 👍 
However, it would be great if the user could choose his “esc” character, so any keyboard could be used, regardless of the local layout.

**Comment by perelin** [comment]
+1 custom ESC

**Comment by shaps80** [comment]
> Hi @vorband.
> It is on the list.
> 
> `cmd+.` also works as esc. And it is iOS system wide shortcut for ESC. May be it could work for you for now.

I did know about this but there a lot of scenarios where it doesn’t work and is generally less accessible/learnable.

I +1 for a custom key as I also have the UK keyboard with a ‘§’ which I NEVER use. 😬😬

**Comment by yury** [comment]
Closing this issue. Feel free to reopen if needed.
