### ISSUE TITLE
mosh produces spurious "Did not find remote IP address" messages

### ISSUE THREAD

**Issue by strowger** [blinksh/blink#65]
Most failed connection attempts with mosh produce a "Did not find remote IP address" message, even if this was not the error.

For example if you type "mosh poo" (or any other syntactically invalid commandline) it will say "Could not parse user@host info" - the real error - and then "Did not find remote IP address".

**Comment by carloscabanero** [comment]
The thing is that Mosh internally calls SSH, and mosh expects to find the MOSH IP message. I will clarify the message but I think the original one also has this problem.

**Comment by carloscabanero** [comment]
This is the message for real mosh:
/usr/bin/mosh: Could not connect to XX.XXX.XX.XX: IO::Socket::INET: connect: No route to host
ssh_exchange_identification: Connection closed by remote host
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).

**Comment by jojule** [comment]
I had the exact same problem. Was able to fix it by removing and reinstalling Blink.

**Comment by carloscabanero** [comment]
Just leaving here for reference. This is usually an issue with connecting over ssh, or finding the mosh-server command. Try connecting over ssh first.

**Comment by frankielc** [comment]
On my particular situation, mosh in Cygwin, I had to use `--experimental-remote-ip=remote`.

`./mosh --predict=always --experimental-remote-ip=remote frankie@192.168.5.2`

Leaving it here in case someone Googles into here; also the [original post](https://wasteofserver.com/ssh-mosh-and-tmux/) with more details.
