### ISSUE TITLE
I didn’ get the mosh key on some network

### ISSUE THREAD

**Issue by bertpubble** [blinksh/blink#650]
I cannot connect to remote host on some network. When I tried to connect with verbose/debug command. I found that not return the MOSH KEY back.

First, I tried to connect via 4G (Cellular)
![26b41ad0-6223-40d9-bb01-c75e80d740f2](https://user-images.githubusercontent.com/19281825/49692705-c5acca80-fb93-11e8-9863-e158ed7f378e.jpeg)

Second, I turned off the Cellular data and connect via WiFi.
![fad5a9c7-7af9-493b-b5b6-39836e65d143](https://user-images.githubusercontent.com/19281825/49692706-c5acca80-fb93-11e8-914d-c393294a60ec.jpeg)

I just switched to blink. Previously, I used Termius and I can connect to all my remote host (via my WiFi) without problem.

**Comment by yury** [comment]
can you repeat this with mosh -2 flag?

**Comment by yury** [comment]
interesting message with ssh_known_hosts file.

**Comment by bertpubble** [comment]
@yury I will test it on the WiFi that has a problem tomorrow. will let you know the result asap.

**Comment by bertpubble** [comment]
When I used -2 option, I can connect it like a charm. 
There are 2 lines in known_host file as below.
![1f7f498f-f47f-4060-b4bc-85da9068ddb0](https://user-images.githubusercontent.com/19281825/49708432-33bfc300-fc62-11e8-812c-91635a3014ec.jpeg)

But I have no idea about why it choose to connect via ssh2 command when I’m on some network and use ssh1 command on some network without any different configuration.

**Comment by carloscabanero** [comment]
Closing. Please reopen if still shows.
