### ISSUE TITLE
SSH connect timeout

### ISSUE THREAD

**Issue by gusennan** [blinksh/blink#651]
Hi, 

I'm trying to connect to one of my Fedora-based servers, which I can connect to from a linux terminal without issues.  I had a similar issue with Termius and bought Blink on the App Store hoping it was a Termius issue, looks like it wasn't :)  Anyway, when I run ssh -v <instance> I get:

    socket_callback_connected: Socket conection callback: 1(0)
    Connect timeout.

When I try the ssh2 command instead of ssh, it says:

    Unable to exchange encryption keys
    Could not connect to host: Error establishing SSH connection.

Maybe they're related? Any troubleshooting help would be appreciated.  Thanks!

**Comment by yury** [comment]
Hi @gusennan,

Can you post more verbose output here (`ssh -vvvvvv host`) ?

**Comment by gusennan** [comment]
Hi Yury, here it is: 

ssh_connect: libssh 0.8.5 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
Connect timeout

**Comment by gusennan** [comment]
A bit more information: 

I'm able to connect to the server when I'm in the same subnet, but not when I'm in a different subnet using Blink.  When I'm using OpenSSH on Linux, the subnet I'm on doesn't matter as the server's publicly available.  This indicates to me that the network admin is filtering out something that is a characteristic of Blink's connection and not OpenSSH's.

**Comment by yury** [comment]
Interesting...
Current state: 2 indicates that socket is able to connect, but nothing is comming from that socket to continue...

**Comment by yury** [comment]
Can you try to turn off compression. `ssh -o compression=no host`

**Comment by gusennan** [comment]
> ssh_connect: libssh 0.8.5 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.9
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.9
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.9
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.9 (70900)
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
ssh_client_select_hostkeys: Changing host key method to "ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,ssh-rsa,ssh-dss"
packet_send2: packet: wrote [len=644,padding=9,comp=634,payload=634]
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4

**Comment by yury** [comment]
Ok, this is a little bit better! 

I think I fix similar issue today. We want to publish new build on test flight (v12.4) today or tomorrow. 

Can I invite you to beta testers on TestFlight?

**Comment by gusennan** [comment]
Sure.  nathan.guerin _at_ gmail

**Comment by yury** [comment]
Sent. Hope v12.4 will be on tf tomorrow.

**Comment by yury** [comment]
Hi @gusennan, can you test `ssh -v compression=no host` on v12.4?

**Comment by gusennan** [comment]
Hi Yury, has the timeout changed?  It no longer times out, but rather hangs when doing:

Ssh -vvvvv -o compression=no host

Ssh_connect: Socket connecting, now waiting for the callbacks to work
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
Socket_callback_connected: Socket connection callback: 1 (0)
Ssh_connect: current state : 2

**Comment by gusennan** [comment]
Is there anything I could look at from the server side that might be helpful in diagnosing what's going on here?

**Comment by yury** [comment]
In next TF version we updated libssh to 0.8.6, it could help.

**Comment by coppercash** [comment]
Hi.
I encountered something similar.
But it seems I am already using libssh@0.8.7.
To be more detailed, I use cellular network.
And it happens usually after I disconnect with `exit`, which causes me unable to reconnect.
Here is what I got:

```
blink> ssh -vvv -o compression=no ?.?.?.?
ssh_connect: libssh 0.8.7 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.2 (70200)
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
ssh_client_select_hostkeys: Changing host key method to "ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss"
packet_send2: packet: wrote [len=668,padding=7,comp=660,payload=660]
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_connect: current state : 4
…
ssh_connect: current state : 4
Connect timeout
```

**Comment by yury** [comment]
Hi @coppercash,

If you restart the app - everything is connecting ok?

**Comment by coppercash** [comment]
I tried to reproduce the problem, but it does not happen every time.
I will leave another message to let you know if restarting the app helps.

**Comment by carloscabanero** [comment]
This should all have been fixed since our big ssh rewrite a while ago.
