### ISSUE TITLE
Display glitches

### ISSUE THREAD

**Issue by leftspin** [blinksh/blink#654]
Hi, I'm getting lots of display glitches. Sometimes what I'm typing will disappear, sometimes the prompt will completely disappear and no amount of keyboard input will bring it back. Also, sometimes as I'm typing it spits out text that was output from previous commands. Here's a video of disappearing text: 
https://share.icloud.com/photos/00ZLS_zyFCFJ85-O0NLgtG3Uw

I'm using it on an iPad Air, iOS 12.1.1. The host side is a mac on Mac OS X Mojave running zsh.

**Comment by yury** [comment]
Hi @leftspin 
Can't see your photos/videos.
Since the original issue we did a lot of work to remove many glitches in rendering.

I'm closing this issue, but feel free to reopen if needed.
