### ISSUE TITLE
Mutated vowels (e.g. ‘Ü’) do not work with an external keyboard

### ISSUE THREAD

**Issue by rverton** [blinksh/blink#657]
When using an external keyboard like the Apple Smart Keyboard with a german layout, it is only possible to insert a lowercase mutated vowel (ü). Pressing Shift+ü also results in a lowercase character. This also happens for ä/ö. When using the onscreen keyboard, it does work.

**Comment by yury** [comment]
Hi @rverton.

New 12.4 is out with the fix. Please confirm it is ok for you and please close the issue if so.

Thank you.

**Comment by rverton** [comment]
Works for me, thanks a lot.

**Comment by strmd** [comment]
This issue persists for me. Blink 12.5, Apple Smart Keyboard for iPad Pro 10.5, Swedish layout.

My primary use of Blink is to use Emacs, but mapping Caps Lock to Ctrl (Modifier Mappings, Special Keys) I lose the ability to enter uppercase å, ä and ö.

**Comment by strmd** [comment]
@yury Should I open a new issue? They seem very related to me.

**Comment by yury** [comment]
Hi @strmd,

Yep, I'd better open new one instead of reopening this issue.
