### ISSUE TITLE
Map Ctrl as escape

### ISSUE THREAD

**Issue by albertmichaelj** [blinksh/blink#659]
Thanks for all of y’alls hard work on Blink! I love the app, and I’m using it regularly. However, I have (what I think at least) is a pretty minor feature request. I would like to be able to map Ctrl to Esc (not the modifier key, but the special key). I use Caps Lock as Ctrl (for emacs like keybindings), and I don’t like the behavior of setting Caps Lock as both Esc as a special key and Ctrl as a modifier key (I find it to be extremely wonky). I also need the shift key, so I can’t make shift the escape key. If I set Ctrl as the Esc modifier key, it won’t actually escape things (like the Byobu cop mode), it just modifies the next keypress.

Can we add an option to set Ctrl as Esc (special key), just like we have the option to set Caps Lock and Shift as Esc (special key)?

If so, this would make Blink the perfect iOS terminal emulator for me! Thanks!

**Comment by xipher1** [comment]
It would be ideal to be able to set any key(s) as Esc. Ideally i’d like `` ( 2 `’s ) to be escape, as I often need to use all the other k;eys.

**Comment by yury** [comment]
In Blink 13.1 you can do that.
