### ISSUE TITLE
Can't get escape to work with iPad Pro + Smart Keyboard

### ISSUE THREAD

**Issue by scottfwalter** [blinksh/blink#660]
I've configured escape to be mapped to both the caps lock and escape key.   However when I am in "vi" neither the caps lock nor option key will take me out of insert mode.

Am I doing something wrong?

**Comment by yury** [comment]
Hi @scottfwalter,

Can you try settings as on screenshot?


![dc791fb3-82ea-44e8-a1cf-53fbda29f1f4](https://user-images.githubusercontent.com/5250/50373032-a37e6800-05e9-11e9-8937-d75f2f2bab01.jpeg)

**Comment by scottfwalter** [comment]
Doh!  That was it.   I was setting the modifier for CapsLock and not the special keys toggle.  Thanks for the help.

**Comment by yury** [comment]
Yep, it is a little bit confusing...
