### ISSUE TITLE
Switching host back to default port doesn't stick

### ISSUE THREAD

**Issue by efroemling** [blinksh/blink#661]
I just ran into an issue where I created a new host and accidentally assigned it a custom port and then found that reverting it to default doesn't properly save.

Repro steps:
- create a new host with name 'test' and any random hostname
- assign it a custom port of 12345
- hit save
- edit 'test' again and delete the 12345; the default faded '22' should reappear.
- hit save and then completely back out of the config UI
- bring up the config UI again and go back to edit 'test'
- 12345 will appear as the port

Hope this is helpful!

**Comment by yury** [comment]
Hi @efroemling,

This issue is fixed.

Thank you.
