### ISSUE TITLE
bling-show-file freezes ssh connection

### ISSUE THREAD

**Issue by DixonCider** [blinksh/blink#663]
I used the blink-show-file.sh file provided in the twitter post attempting to open a image file on a remote server (https://gist.github.com/yury/1e1db54f5a35a804604b1ae1b2657b51).
When executed, the ssh connection froze and a white dash appears in the center of the screen.
(https://imgur.com/a/DFMmnt4)

**Comment by yury** [comment]
Hi @DixonCider,

Fix will be in next release. (After Apple holidays :)

**Comment by sbromberger** [comment]
Just an aside - will this ever be possible over mosh?

**Comment by yury** [comment]
They have support for remote clipboard, but not images yet  (as far as I know)

/cc @cgull

**Comment by yury** [comment]
Hi @DixonCider,

v12.4 released with the fix.
Closing issue. Feel free to reopen it if it doesn't work for you.

**Comment by DixonCider** [comment]
@yury Works like a charm! Btw is it suppose to work with tmux yet?
