### ISSUE TITLE
Ctrl + Alt (option) not working

### ISSUE THREAD

**Issue by kidpollo** [blinksh/blink#666]
Dont know if its related to https://github.com/blinksh/blink/issues/262 but I cant do ctrl + alt + [whatever] combinations. Those are quite important for me :P

**Comment by yury** [comment]
Hi @kidpollo,

Can you show your mappings? ctrl and alt :)

**Comment by kidpollo** [comment]
https://share.icloud.com/photos/0nElZk_Pih6ik9PQXU9TnvbTA

**Comment by yury** [comment]
Hmm, you don't have anything mapped to alt as modifier.

What do you expect to be with ctrl+alt+char?

**Comment by kidpollo** [comment]
There are a few Ctrl+alt+ char commands I use in emacs

**Comment by yury** [comment]
Hi @kidpollo,

I think you should set alt as esc modifier.

Anyway /cc emac @carloscabanero guru.

**Comment by kidpollo** [comment]
I just noticed that if I use the smart keys my ctrl+option commands work.
Thet dont work when I do ctrl+alt+{char} on a hardware keyboard. NOTE that
ctrl+{char} commands do work on a hardware keyboard.

**Comment by yury** [comment]
Hi @kidpollo,

I think you should  map alt as ESC

![891954cb-25ae-4cda-ab76-017fb6389929](https://user-images.githubusercontent.com/5250/50658974-1bff0480-0fac-11e9-8bdc-d28b002ecf33.jpeg)

**Comment by yury** [comment]
Yep, if you want hardware kb to work the same as smart keys bar, just map set `alt` as `esc` key modifier. You can verify it by running `showkey` command.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by carloscabanero** [comment]
The modifier for Alt transforms it into Emacs' M-key. So M-x, etc... would be Alt-x. Is that what you are looking for?

**Comment by yury** [comment]
Closing. Feel free to reopen if needed.
