### ISSUE TITLE
Application background colors show “seams”

### ISSUE THREAD

**Issue by casey-chow** [blinksh/blink#668]
I’ve noticed that when I use utilities that set background colors through the shell, the background seem to show seams or spaces (for lack of a better term). For example, this is the output of `printf %b '\e[41m' '\e[8]' '\e[H\e[J'`:

![ccf023eb-f936-49fd-b1c6-d4320930169a](https://user-images.githubusercontent.com/378216/50624071-67e97500-0eea-11e9-94b3-c1d340e84803.png)

As you can see, there’s small lines of black between each row of characters. Is there any existing way to address this?

**Comment by yury** [comment]
It is font dependent.
For instance, with Fira Code I got solid red screen.

**Comment by casey-chow** [comment]
Ah, interesting and can confirm. Is there a way to hack the font CSS to decrease the line spacing?

**Comment by yury** [comment]
Nope, one prop could work (`font-size-adjust`) but mobile safari doesn't support it :(

**Comment by yury** [comment]
@casey-chow, what font is that?

We have changed font measurment a little bit. So in v12.8 build 93 should be ok. But still I need to check.

**Comment by casey-chow** [comment]
This was Inconsolata.

**Comment by yury** [comment]
With build 93 and Inconsolata:
![IMG_0269](https://user-images.githubusercontent.com/5250/54512098-22263f80-4964-11e9-8086-9c2f3f8a5e5d.PNG)

**Comment by yury** [comment]
Closing, feel free to reopen if something is wrong.
