### ISSUE TITLE
blink should display the screen geometry

### ISSUE THREAD

**Issue by strowger** [blinksh/blink#67]
When the window is resized - either by popping up the keyboard or by pinching to adjust the font size - blink should provide a way for the user to see how many columns*rows they have on their display.

This is very useful when trying to use a shared screen session with a desktop computer, as it allows the window on the desktop to be made the same size as the mobile.

**Comment by strowger** [comment]
for my reference perhaps as much as anything else:

with the swype keyboard installed and displayed, the smallest text i'm comfortable with gives a 115x47 window.

with the system keyboard (which is smaller), the same size text gives a 115x51 window.

with no keyboard displayed at all (long single-press on screen), this is 115x84

**Comment by carloscabanero** [comment]
This is easy, will do.

**Comment by nriley** [comment]
Ideally any change to the geometry should do this (including rotation, adjusting split screen on iPad, etc.)  Perhaps this could just be added to the existing popup display of the current session name and the pagination dots.

**Comment by carloscabanero** [comment]
Done on v5!
