### ISSUE TITLE
Show error message when ssh key is missing

### ISSUE THREAD

**Issue by docwhat** [blinksh/blink#671]
1. Create a new host entry.
2. Set the ssh key to an existing ssh key.
3. Save
4. Rename the existing ssh key from step 2 to something different.
5. Try `ssh <host>`

I would expect that I would get an error message about the SSH key being missing.  Or at least a warning.

Instead, the login just fails for no obvious reason.

This may be related to #665

**Comment by carloscabanero** [comment]
This was fixed with iCloud messages. Closing here.
