### ISSUE TITLE
ssh proxy chain

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#672]
It is possible to add proxy to access host, but that does not working with chain,

For example, this is my setup and I need two proxies here:

```
blink → vps → raspberry pi with autossh and reverse tunnel to the vps → macbook
```

I can access RPI with blink by specifying ProxyCmd for related host in settings, but I can't access macbook by specifying rpi3 in ProxyCmd for macbook, logs below:

```
blink> ssh -vvv macbook12-rpi3
ssh_connect: libssh 0.8.5 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_socket_connect_proxycommand: Executing proxycommand 'ssh -W macbook12.local22 rpi3'
ssh_socket_connect_proxycommand: ProxyCommand connection pipe: [34,35]
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
ssh_connect: current state : 2
callback_receive_banner: ssh_protocol_version_exchange: 
callback_receive_banner: ssh_protocol_version_exchange: Socket error: disconnected
ssh_socket_exception_callback: Socket exception callback: 1 (0)
ssh_socket_exception_callback: Socket error: disconnected
ssh_connect: current state : 9

Socket error: disconnected
```

Update:

Settings for `rpi3` and `macboook-rpi3`:

![rpi3](https://user-images.githubusercontent.com/26776/50765549-834fd980-1276-11e9-866b-e8ddd59ca580.jpeg)

![macbook12-rpi3](https://user-images.githubusercontent.com/26776/50765591-a4b0c580-1276-11e9-8f80-8ead8d152dc8.jpeg)

**Comment by yury** [comment]
Hmm, there is should be `:` between`%h and %p`.

`ssh -W %h:%p host`

**Comment by andrius** [comment]
Yes it works, but now I am wondering why I had possibility to login to the `rpi3`, which is "localhost" and behind proxy. Anyway, sorry for issue, please close it!

**Comment by yury** [comment]
Could you repro that? May be `:` was there?
