### ISSUE TITLE
js connect to ssh

### ISSUE THREAD

**Issue by xiongxiongjiang** [blinksh/blink#673]
Hello,when I read your code,I find that the command execute by ```_webView evaluateJavaScript: jsScript```，then it call ssh.m.But I don't know how can term.js connect to SSHClient. Could you plz tell me?

**Comment by yury** [comment]
Hi @xiongxiongjiang,

TermDevice sends terminal sequences with `term_write` and `term_write_b64` from term.js.
Terminal sends signals (resize, copy, and other) with `_postMessage` from term.js and handled TermView in `userContentController:(WKUserContentController *)userContentController didReceiveScriptMessage:(WKScriptMessage *)message`.

If you are looking in WSS implementation, you can take a look at [our attempt](https://github.com/yury/blink/commit/222bce64e07d8de2cad1d885eebc7a8979c9f27a).

This is web socket implementation for communication (a little bit outdated)

**Comment by xiongxiongjiang** [comment]
Thank you very much!
Oh i know the web just in charge of show UI,are this code call to SSHClient?
```
- (void)write:(NSString *)input
{
  NSUInteger len = [input lengthOfBytesUsingEncoding:NSUTF8StringEncoding];
  write(_pinput[1], input.UTF8String, len);
  if (_echoMode) {
    if ([input isEqualToString:@"\n"] || [input isEqualToString:@"\r"]) {
      return;
    }
    write(_poutput[1], input.UTF8String, len);
  }
}
```
I guess there'er something in ```write(_pinput[1], input.UTF8String, len);```

**Comment by yury** [comment]
There is also ViewStream. Witch writes to webview anything coming out from streams.

**Comment by xiongxiongjiang** [comment]
I clone you project and checkout branch ws-experiment，then I execute ./get_frameworks.sh and 
update submodule，it can be run. There are Xcode error: 

Showing Recent Messages
:-1: Multiple commands produce '/Users/xurong/Library/Developer/Xcode/DerivedData/Blink-aetupmxrrshrrpgsykefiqxwvgne/Build/Products/Debug-iphoneos/Blink.app/Info.plist':
1) Target 'Blink' (project 'Blink') has copy command from '/Users/xurong/Desktop/blink_wss/blink/Frameworks/PasscodeLock/PasscodeLock/Info.plist' to '/Users/xurong/Library/Developer/Xcode/DerivedData/Blink-aetupmxrrshrrpgsykefiqxwvgne/Build/Products/Debug-iphoneos/Blink.app/Info.plist'
2) Target 'Blink' (project 'Blink') has process command with output '/Users/xurong/Library/Developer/Xcode/DerivedData/Blink-aetupmxrrshrrpgsykefiqxwvgne/Build/Products/Debug-iphoneos/Blink.app/Info.plist'

so sad :(

**Comment by yury** [comment]
Yep, it is outdated code. Just for reference... Sorry

**Comment by xiongxiongjiang** [comment]
So  how can i fix it? plz plz plz

**Comment by xiongxiongjiang** [comment]
If it didn't influence the wss connect ,I could ignore it.

**Comment by yury** [comment]
What you are trying to achieve, may be we can support that in main branch. Can you please tell you use case.

**Comment by xiongxiongjiang** [comment]
My English is not very good... We use HTTP for routing，SSH is not as flexible

**Comment by xiongxiongjiang** [comment]
I use SocketRocket in your latest project,and copy the file fterm.h && fterm.m, then createPTY in TermController.My socket is connected,but I don't know how to use it to control termView.

**Comment by yury** [comment]
Ok, here what you can do.

Lets build wss `url` command:

1. copy say.m to wss.m
2. remove all code except say_main function.
3. rename say_main to wss_main.
4. register wss_main in blinkCommandsDictionary.plist (copy and fix say section)
5. now if you type wss url wss_main will be called.
6. grab thread_stdout and thread_stdin in some local vars.
7. create and connect  SRWebSocket (let called webSocket)
8. set webSocket delegate. in `didReceiveMessageWithData` you should write data to thread_stdout
9. then create reader from thread_stdin (let say dispatch_source). 
10. send everything from thread_stdin (dispatch source) to webSocket#sendData
11. create semaphore and signal it in webSocketDelegate#didClose
12. wait semaphore at the end of wss_main

You can publish branch somewhere, so I can take a look.

**Comment by xiongxiongjiang** [comment]
Thanks for your reply.
Could you please leave a online contact?

**Comment by yury** [comment]
@xiongxiongjiang can we close this issue? :)

**Comment by xiongxiongjiang** [comment]
sure!Thx again.
