### ISSUE TITLE
mosh flags are ambiguous with certain mosh server versions

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#674]
the mosh flags passed appear to be
```
new -s -c 256 -l LC_ALL=en_US.UTF-8
```

However, on mosh version 1.3.2 built from source, the `-s` flag is now ambiguous:

```
Option s is ambiguous (server, ssh, ssh-pty)
```

which causes mosh sessions to fail.

**Comment by sbromberger** [comment]
oops. That should've been `mosh-server`. Sorry for the false alarm.

**Comment by danielson317** [comment]
I'm getting this issue. What was the resolution?

**Comment by danielson317** [comment]
This appears to be a real bug. If you have the mosh "command" filled out with the path to your mosh server as the tool-tip indicates it will throw this error. I was able to just remove the path to fix.

Can this be reopened?
