### ISSUE TITLE
ssh-add can not load ec keys

### ISSUE THREAD

**Issue by TypedLambda** [blinksh/blink#681]
The ssh-add command fails to load ecdsa and ed25519 keys. RSA and DSA keys work fine. 

`ssh-add test2`

`Error loading key "test2": invalid format`

**Comment by yury** [comment]
Update:
ed25519 keys are working if the generated with `ssh-keygen` or copied to `~/.ssh/`
ed25519 is not working with libssh exported keys (blink config -> keys)

**Comment by martinpaljak** [comment]
Can't there be a simple "also store in .ssh" option for the visual UI config ?

**Comment by yury** [comment]
@martinpaljak we prefer not to store keys in file system but store it in Secure Enclave.

**Comment by martinpaljak** [comment]
Me too, but I understand that none of the "small" keys (read: ec, especially the ones which could be agent-capable) can be stored there?

**Comment by yury** [comment]
All ecdsa will work in next release. Only remaining issue with ed25519. I reported to libssh team. Hope they fix it soon.

**Comment by martinpaljak** [comment]
Cool! Are those keys then kept in the secure enclave? Will it be possible to run ssh-agent without fiddling with a second terminal?

**Comment by yury** [comment]
For ssh-agent forwarding you still need to run ssh-agent in the tab for now

**Comment by martinpaljak** [comment]
(elliptic) keys kept in the secure enclave (like sekey) + fingerprint and/or PIN activation of those keys + ssh-agent forwarding via a simple checkbox in config

These are the features I hope blink will get, which would make it a real powertool

**Comment by yury** [comment]
Ok, ed25519 fix [landed in libssh](
https://gitlab.com/libssh/libssh-mirror/commit/128015bb1795898ef83460f0387eacc9b10ed798). 

Waiting for release

**Comment by yury** [comment]
v12.7 released. Should be ok there.

**Comment by mcg** [comment]
Still have "invalid format" trying to add a ed25519 key to ssh-agent. Should this be fixed?

**Comment by yury** [comment]
@mcg sorry, I messed up with libssh update. Turns out that fix didn't make to release. We have to wait.

Sorry for false alarm :(

**Comment by yury** [comment]
Ok, @mcg.

Sorry again :) but I was to fast to response. It actually should work in v12.7. One note though. 
You have to reimport key in keys.  Actuall bug was in internal export.

![0930A989-8531-4DCC-B48E-45EB0CE7CB28](https://user-images.githubusercontent.com/5250/54258744-9cc21a00-4574-11e9-83f9-aed07390a04f.jpeg)

**Comment by mcg** [comment]
Re-imported and it worked great. Thanks!

**Comment by yury** [comment]
Cool, closing.

Thank you!
