### ISSUE TITLE
Unable to use ssh with ngrok

### ISSUE THREAD

**Issue by ironwall** [blinksh/blink#683]
when I have set up my ngrok server, I cannot use ssh(blink) to link my personal computer
like
ssh  usrname@0.tcp.ngrok.io -p xxxxx
it returns Socket error: Unknown error:-1

**Comment by ironwall** [comment]
Perfect, it works. Another question, how can I make a nerd fonts(Source code pro nerd font) by using existing .ttf file?

**Comment by yury** [comment]
You need to install that fonts via app (Any Fonts, All Fonts etc). And it will be available in fonts list in blink.

Other option is to use css font (but is not very performant).

Closing original issue.
