### ISSUE TITLE
Ssh-agent does not seem to work for keys with passphrase

### ISSUE THREAD

**Issue by lohitv9** [blinksh/blink#685]
Hi,

I have just downloaded blink from AppStore and tried to do the following. It does not seem to work.

ssh-keygen ( with passphrase)

Edited .ssh/config to always refer the above key for every host as below:
Host *
User test01
IdentityFile key_v1

ssh-agent ( it starts running in background )

New tab

ssh-add key_v1 ( it prompts me for password and once successful - it says identity added successfully )

ssh host ( it again asks me for password )

ssh -A host (It asks me for password here too)

I really wish not to enter password every time, and would like to just enter once during ssh-add.
May i know if this could be fixed?

I see that, this was raised before and was fixed in 
https://github.com/blinksh/blink/issues/563

However it does not work for me.

Thank you

**Comment by lohitv9** [comment]
I have just tested using an other method.

I had copied the key that i had made using ssh-Keygen into config->keys ( where it asked me for passphrase)

I then tried:
Ssh-agent
New-tab
Ssh-add key_v1 ( did not ask for password )
Ssh host ( did not ask for password )

I can work with this, and will reopen another issue in case i would like to work as above.

Thank you.

**Comment by yury** [comment]
Hi @lohitv9,

config->keys is preferred way to store keys (keys are stored in Secure Enclave on device and not file system).

But `ssh host` (auth) do not use agent for now. Only for forwarding... 
I will work on that soon.

Thank you.
