### ISSUE TITLE
Please add more mappings

### ISSUE THREAD

**Issue by yefeiyu** [blinksh/blink#686]
Could you add some others mappings in the 'keyboard-MODIFIER MAPPINGS' :
add 'shift' to 'control' (and/or other keys),
add 'Menu' (or 'Application') to 'shift' (and/or other keys),
add the origin 4 keys of 'Ctl, Alt, Command, Capslock' mappings more, such as 'shift, Ctl, Al\
t, ESC'.
Thanks a lot.

**Comment by nmattia** [comment]
A few more that would be amazing:
* `§`/`±` -> backtick/`~`
* “open drive” (opens keyboard in blink) -> delete key

**Comment by yury** [comment]
@yefeiyu you should be able to remap almost all keys in blink v13.2. (Except Menu).

@nmattia you can remap §/± in latest blink. We don't have API to rebind "Open Drive" key :(

Closing this issue. Feel free to reopen if needed.
