### ISSUE TITLE
TERM does not get passed from .profile/env to mosh session

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#687]
I did a `setenv TERM xterm-256color-italic" > .blink/profile` and confirmed that when I used `ssh` to connect to my host, the `TERM` environment variable was passed. However, when I use `mosh` to connect, the environment variable does not appear to be passed.

**Comment by yury** [comment]
Hi @sbromberger,

Good catch.

As far as I understand mosh-server supports [only one and sets it itself](https://github.com/mobile-shell/mosh/blob/fecd4ee29b7e7a6b63c60e2e52940d050e18a99b/src/frontend/mosh-server.cc#L556)

**Comment by sbromberger** [comment]
Ah, thanks. I should've looked first. Sorry to have bothered you with this.
