### ISSUE TITLE
Feature request: PageUp / PageDown keys please

### ISSUE THREAD

**Issue by strowger** [blinksh/blink#69]
PgUp/PgDn are very useful with screen/tmux.

It would be helpful to have a way to send these without a hardware keyboard.

**Comment by strowger** [comment]
Perhaps a possible way to do this would be for swiping up /down at one side of the display to send PgUp/PgDn.

**Comment by carloscabanero** [comment]
Blink will have a way for you to create special commands and what to send. I think this fits on that. I don't know if providing a default sequence from the start. This might be related to #8

**Comment by carloscabanero** [comment]
Duplicate of #8
