### ISSUE TITLE
Add more customization options for Escape mapping for different layouts

### ISSUE THREAD

**Issue by darthdeus** [blinksh/blink#694]
The current settings allow to map backquote as Esc, which even though is a great option, does not work for all keyboard layouts. For example, on the Czech layout shown below, if I use regular US keybindings, I’ll have the backtick `` and tilde `~` on the right of the left shift, but the regular tilde spot is mapped to `§±` (the one above Tab, on the left of 1).

To be more specific, I assume that the option to map backtick to Esc was to map the key on the top-left of the keyboard. But in my case this is `§`.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/KB_Hungary.svg/420px-KB_Hungary.svg.png)

I do realize that this is a very specific request, but at the same time I would expect other people using the iPad to have some weird layouts that might appreciate a similar option. I’m not sure if this can be implemented in a general way.

**Comment by mantissa7** [comment]
I have the British keyboard and the key in the top left of my Smart Folio is §. I would very much like to use this as the esc key as the backtick for me is next to shift, but I use backticks a lot in JavaScript string literals so I need this key.

**Comment by sylvoie** [comment]
I used an other SSH client that was using screen gesture to capture ESC key. It was userful to double touch screen with finger to escape in VI. Is-it possible to consider this feature?

**Comment by yury** [comment]
@sylvoie,

What device are you using?

On iPads there are a lot of unused space on toolbar when KB is attached. So I was thinking to use that space as ESC by default... What do you think?

Here is a demo: https://youtu.be/AyGFoCN2eb8

**Comment by sylvoie** [comment]
Hello,

Thank for your answer. I’m using iPad Pro 10.5 with french Apple keyboard.

The ESC key on Blink Smart Keyboard doesn't work well. I don’t know why, but sometime I have to touch 3 times, sometime 2 times and sometime 1 time the key « ESC » to escape in VI.

I watched you video and curiously, your Smart Keyboard is different than mine. See attached picture.
![4150E54F-0325-4E70-B13E-651A4B700C4C](https://user-images.githubusercontent.com/3700343/62576151-49759e80-b86a-11e9-9777-5b1c2d8d2f66.png)

I prefer your Smart Keyboard than mine, because ESC is at the left side. 

I watched your example, and I think that your suggestion is a good idea. But I prefer to be able to hide the Smart Keyboard, get more space and need to double touch the screen anywhere to escape from VI. Is-it difficult to implement?

Thank’s

**Comment by sylvoie** [comment]
Hello Yury,

I think more about it, and I realize that I like the Smart Keyboard I’ve seen in your video. The « ESC » key at left will be more usable. If you can add keys like copy/cut/paste, it will be awesome. 

Escape, copy, cut, paste, {, }, [, ], ~, previous tab, next tab, left, top, bottom, right

If I can get stability from the « ESC » key where sometime I need to touch 2 times to escape VI, I will be happy.

Thank’s

**Comment by yury** [comment]
Hi @sylvoie,

If you noticed - there is cmd button at the right. So idea is to make cmd+x/c/v to work on software KB and other shortcuts too (cmd+t, cmd+w, etc).

Also, this kb can react to selection changes and show copy/share icons.

Anyway, new smart kb system will be customizable :)

**Comment by sylvoie** [comment]
Hi Yury,

You are right and it’s my mistake. Sometime I can’t use my external keyboard. In that situation, I get difficulty to copy paste a command from Notes app with my finger at the prompt. The Smart Keyboard doesn’t have « CMD » key to let me cmd-v. That the reason I suggested keys copy/cut/paste explicitly. Anyways, I looking forward to use the new Smart Keyboard. 

Great job.

Thank’s again

**Comment by yury** [comment]
Do you know, that you can two finger swipe up, to get control center in blink with (paste button :) ?

**Comment by yury** [comment]
French layout on iPad 10.5
<img width="878" alt="Screenshot 2019-08-08 at 16 23 54" src="https://user-images.githubusercontent.com/5250/62706859-fd0c9900-b9f8-11e9-88fb-996a56f42077.png">

**Comment by kek** [comment]
I do not believe this feature would be as valuable as one would think at first glance, since it’s probably a simple task to map § or ` to the desired function in the application program (which is certainly Vim in this case). https://github.com/blinksh/blink/issues/770#issuecomment-519836705

**Comment by sylvoie** [comment]
Hello Yury,

Very nice and looking forward to use this next release, I mean new Smart Keyboard.

Thank’s

**Comment by sylvoie** [comment]
Hello Yury,

Thank you for this new version that work very well. For now, smart key « ESC » works well. The only glitch is the fact that smartkey « ESC » doesn't appear on my Smart Keyboard.

Thank’s

**Comment by yury** [comment]
@darthdeus 

can you type first 3 top most letters on your kb here https://jsfiddle.net/yuryk/1vdmk8ws/embedded/result/

and also full fourth row.

Something like this gist https://gist.github.com/yury/19c4f5b02afb86a8307130daa8529f26

**Comment by yury** [comment]
@sylvoie please check Settings.app -> Keyboard -> Shortcuts options. (It should be on)

**Comment by yury** [comment]
In Blink v13.1 you can map § to esc in `config->keyboard->Custom Presses`
