### ISSUE TITLE
Siri shortcut for `mosh hostname` runs `mosh`.

### ISSUE THREAD

**Issue by toph-allen** [blinksh/blink#695]
When opening Blink via a Siri shortcut for `mosh hostname`, the app opens up and runs `mosh` instead. This occurs whether the app is already open or not.

**Comment by yury** [comment]
I'm closing this as a duplicate.

See #592.

But please, can you record a video (how you create shortcut and trigger it). I can't reproduce, but really want to fix that issue.

Thank you!
