### ISSUE TITLE
Resizing tmux windows with keyboard shortcuts

### ISSUE THREAD

**Issue by saptarshiguha** [blinksh/blink#696]
I use tmux on a Linux host. This is `tmux.conf`

```
bind -n S-Left resize-pane -L
bind -n S-Right resize-pane -R
bind -n S-Up resize-pane -U
bind -n S-Down resize-pane -D
```

When using blink, these keyboard shortcuts are respected when i use a hardware keyboard, however i can't seem to make it work using the IOS keyboard.

**Comment by yury** [comment]
on iPad with iOS build in keyboard it should work in Blink v13.2. 
It will not work with third-party kbs like GBoard since it doesn't send down event for shift.

Closing this issue. Feel free to reopen if needed.
