### ISSUE TITLE
Expose BlinkSH Filesystem in Files App

### ISSUE THREAD

**Issue by derekbelrose** [blinksh/blink#697]
Would it be possible to expose the BlinkSH filesystem in the Files App?

Even better, would it be possible to expose sftp  file systems?

**Comment by yury** [comment]
Hi @derekbelrose.

Blink actually expose two folders to Files App.
1. Home folder (~) - you can find it under Files App -> Locations -> On My iPhone/iPad -> Blink
2. iCloud (~/iCloud) - you can find it under Files App -> iCloud Drive -> Blink

**Comment by derekbelrose** [comment]
Thanks for pointing those out!
