### ISSUE TITLE
Blink ssh configuration

### ISSUE THREAD

**Issue by drkohel** [blinksh/blink#699]
I’m trying to configure ssh in the blink shell.  After a first successful use, ssh switched to the default ssh -1 (does anyone use protocole 1 anymore?), and I have to explicitly call ssh2 instead of ssh.  Secondly, scp fails with an authentication failure. It fails to authenticate the system id_rsa public/private key pair, and doesn’t fall back to asking for a password. Finally, I want to get passwordless login working but ssh (or rather ssh2) seems to only want to use the default system id_rsa rather than any of my identity files that I placed in .ssh and specify in .ssh/config.

Perhaps I could work around the problem if I could get access to the system id_rsa.pub file, but I don’t know where it is stored or how to extract it.

Finally, much of the FAQ and responses are a few years old (as of 2019).  Previously ForwardAgent was not supported, but is this still the case?  This would a feature request that I would rank highly. I think I’m missing some basic documentation on blink and its current features.

**Comment by yury** [comment]
Hi @drkohel,

`ssh` and `ssh2` both use `ssh 2 protocol`. Difference is that `ssh` use [libssh](https://www.libssh.org) and `ssh2` use [libssh2](https://www.libssh2.org). This libraries are totally independent and not versions of each other.

For password-less sign in import your keys with `config` command (keys section)

scp will also work. (but with one note. You should ssh2 to that host first once to update known_hosts file)

**Comment by videoMonkey** [comment]
I didn’t see a response to the status of `ForwardAgent`, is that working? Coming?

**Comment by yury** [comment]
ssh -A is supported, but you have to run ssh-agent in separate tab for now. See #873

**Comment by videoMonkey** [comment]
I guess I didn’t search hard enough in the issues. This covers things, thanks!

—Jamie
