### ISSUE TITLE
Siri shortcut for deleted server still appears

### ISSUE THREAD

**Issue by toph-allen** [blinksh/blink#700]
While I was testing for #592, I created a dummy server, which now still appears in Spotlight search results as an available shortcut.

I’m not sure the exact way that Blink manages its donated actions, but it can probably delete them, per this page: [Deleting Donated Shortcuts | Apple Developer Documentation](https://developer.apple.com/documentation/sirikit/deleting_donated_shortcuts).

Let me know if there’s anything helpful I can provide.

**Comment by yury** [comment]
`config delete-activities all`  removes all shortcuts,
In theory, you can also run `config delete-activities "mosh host"`, but for some reason it is not working.

**Comment by yury** [comment]
Closing, feel free to reopen if something is wrong.
