### ISSUE TITLE
Cursor offset for some fonts is wrong in build 93

### ISSUE THREAD

**Issue by toph-allen** [blinksh/blink#702]
Some fonts, but not all, have the wrong offset for the cursor. The offset for each character typed is too large, placing the cursor to the right of the text.

- The built-in PragmataPro is wrong. Different, user-installed Pragmata Pro (using AnyFont profile) seems ok.
- SF Mono is wrong.

![IMG_0788](https://user-images.githubusercontent.com/3117884/54537102-4f74ec80-4968-11e9-85ae-8241c1da4679.png)
![IMG_0789](https://user-images.githubusercontent.com/3117884/54537103-4f74ec80-4968-11e9-829e-fab030b9b88b.png)
![IMG_0790](https://user-images.githubusercontent.com/3117884/54537104-4f74ec80-4968-11e9-9d7b-2769dbd657f5.png)

**Comment by yury** [comment]
Oh, what version of iOS do you have?

**Comment by toph-allen** [comment]
I've attached a .zip of the font that doesn't work for me. I see the same thing on my phone, too.

[SF Mono.zip](https://github.com/blinksh/blink/files/2979202/SF.Mono.zip)

**Comment by yury** [comment]
Tested your font. Works ok for me. I have installed regular, bold, bolditalic and regularitalic. (With build 93).

![873FECC3-3926-4F83-8FE6-57C11ABE43B3](https://user-images.githubusercontent.com/5250/54547233-680bf380-49b6-11e9-9915-87a4f39bb9b6.png)

Should be smth different. It can be iOS version. I'm on latest stable iOS v12.1.4

**Comment by toph-allen** [comment]
Is the last "f", inside the box cursor, part of the typed string, or is it a completion? If it's not a completion, then that screenshot is exhibiting the exact issue I talked about. With SF mono, the cursor (box) lags slightly behind where it should be, with the built in PragmataPro, it advances ahead of the typed string.

I am on iOS 12.2. However, Blink Shell build 91 still displays all fonts totally fine (I reinstalled it just now to check), whereas Build 93, which introduced the new font size measuring algorithm, exhibits the issue.

Build 91 PragmataPro
![IMG_0792](https://user-images.githubusercontent.com/3117884/54549219-003ab600-4980-11e9-820b-883992b84b71.PNG)

Build 93 PragmataPro
![IMG_0791](https://user-images.githubusercontent.com/3117884/54549234-07fa5a80-4980-11e9-987b-476e04908fc1.PNG)

Build 91 SF Mono
![IMG_0794](https://user-images.githubusercontent.com/3117884/54549262-134d8600-4980-11e9-8eca-88ffb590599d.PNG)

Build 93 SF Mono
![IMG_0793](https://user-images.githubusercontent.com/3117884/54549272-18123a00-4980-11e9-9824-38e0c4c366b4.PNG)

**Comment by toph-allen** [comment]
Just a brief update: This still occurs in the latest 12.2 beta.

I was also mistaken earlier: It does *not* occur with the built-in Pragmata Pro font, only with the user-installed Pragmata Pro font. (I checked by uninstalling the profile through which that font was provided

It thus seems that this issue occurs, as far as I can tell, only with typefaces I installed myself via AnyFont.

**Comment by yury** [comment]
Ok, build 94 should calculate width right too.

**Comment by yury** [comment]
Hi @toph-allen,

Does build fix that issue for you? This is blocker for current release.

(Still can't repro this issue myself)

**Comment by toph-allen** [comment]
I only see Build 93 on TestFlight — I’ll update this as soon as I see Build 94

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toph-allen** [comment]
The issue appears unchanged for me on Build 94 — I re-installed Build 93 and took a screenshot with the same text on screen, and the cursor position was identical

![IMG_0803](https://user-images.githubusercontent.com/3117884/54680350-05167b80-4ae0-11e9-8a49-98ef33e225a7.png)
![IMG_0804](https://user-images.githubusercontent.com/3117884/54680351-05167b80-4ae0-11e9-9fc8-33e596e38c54.png)

**Comment by yury** [comment]
Hmm, can you send me that font? yury.korolev@gmail.com

**Comment by toph-allen** [comment]
Yes, will do when I get off the subway :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toph-allen** [comment]
Sent — plus some thoughts about what might be at the root of the issue.

**Comment by yury** [comment]
Ok, so what I have found about this issue.

Since build 93 we start to use 
[Canvas#measureText](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText) to get real glyph width and height. It fixes line height for nerd and iosevka fonts. It works well on iOS 12.1 with both bundled and system wide installed fonts.

But turns out that method is broken under iOS 12.2 beta6.

Possible solutions:

1. Try to build with XCode beta and see if it helps. (It could actually and I will try tomorrow)
2. Drop iosevka font support (I really really don't want to do that)
3. Report bug to apple and hope they fix it. (But I'm thinking they broke it intentionally, so browsers couldn't finger print on fonts or smth like that)
4. Implement fallback to system wide fonts and detect size via dom element size. (That approach doesn't work well with nerd and iosevka fonts, but since we budnle iosevka in the app it will survive).
5. Release as is and hope iOS 12.2 release will have fix for that.

**Comment by toph-allen** [comment]
Good job tracking it down. I guess there's no harm in checking with Xcode beta, but it does sound like something that would be part of automatic tracking prevention.

If you fall back to using DOM element size, how badly will Iosevka look? I guess it would be possible to just use the canvas method for Blink-provided fonts DOM element size as a fall-back for system-installed fonts, at least until it gets fixed.

**Comment by yury** [comment]
Yep, I will fallback for dom size in case of system wide installed font. Stay tuned.

**Comment by toph-allen** [comment]
Confirmed that Build 97 fixes — or successfully works around — this issue 🙌

**Comment by yury** [comment]
Thank you! Closing this issue.
