### ISSUE TITLE
Iosevka font Powerline symbol size

### ISSUE THREAD

**Issue by comfortablynick** [blinksh/blink#703]
Thanks so much for adding Iosevka in build 93! 

One issue I noticed was the size of Powerline symbols with this font. They are built into the base font, so I was surprised they weren't rendering correctly. 

I have a script that turns Powerline symbols on/off depending on terminal width.  Here is how Iosevka (regular, default font) looks on hterm on Windows (Chrome SSH extension):

![Hterm-Iosevka](https://i.imgur.com/JW94gQW.jpg)

And here is how it looks on Blink: 
![Blink-Iosevka](https://i.imgur.com/3GSBbpA.jpg)

This is Fira Code on Blink, which appears as expected:
![Blink-FiraCode](https://i.imgur.com/QsaJA7V.jpg)

You can see how the Iosevka Powerline symbols are incorrect on Blink. This may not be able to be fixed, but I wanted to submit it just in case it can.

**Comment by yury** [comment]
Hi @comfortablynick,

I was playing with build paramaters of that font. And simply forget to revert changes. Build 95 (I hope final for 12.8) would have full sized glyphs.

**Comment by yury** [comment]
Tested with [this script](https://gist.github.com/gdetrez/5845092)
![363CD9D7-1E93-4033-B3A5-AA322279C9F2](https://user-images.githubusercontent.com/5250/54663183-6d218d80-4af1-11e9-9907-e1bf1984c429.jpeg)


Thank you for feedback!
