### ISSUE TITLE
Wrong font selected in config

### ISSUE THREAD

**Issue by Kamik423** [blinksh/blink#704]
When another font is selected in `config` it changes only after a restart of the app.
However the `config` will still display "Source Code Pro" no matter what.
This can be achieved by selecting a font, going back to settings and tapping on appearance again. No matter what font was selected, the indicator is now next to "Source Code Pro".

**Comment by yury** [comment]
Hi @Kamik423.

What version do you use?

Appearance (font and theme) changes only for new terminals. You don't need to restart app, you can just open another session. (Cmd+T or 2 finger tap). Or just close current session (CMD+W or 2 finger up and trash icon)

**Comment by Kamik423** [comment]
I am on the latest TestFlight beta.

Can you try selecting a different and recognizable font (I used Courier New), going back to settings and opening the appearance menu again? The font is then deselected for me.

**Comment by yury** [comment]
Oh! Yep, with `Courier New` I can reproduce it. Other fonts working fine.

Thank you.

**Comment by Kamik423** [comment]
From what I can tell (I cannot identify all the fonts) I can get the font to change, just not get displayed properly.

The one I noticed it with first was DejaVu Sans.

**Comment by yury** [comment]
All system wide installed fonts loose selection. 
Fixed in build 96.

Thank you!

**Comment by yury** [comment]
Closing, feel free to reopen if something is wrong.
