### ISSUE TITLE
Sometimes, blink display 'u' letter as greek 'mu'

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#705]
![IMG_1476](https://user-images.githubusercontent.com/26776/54820736-6f761a00-4ca0-11e9-8849-3229b5ad49d9.jpeg)

**Comment by yury** [comment]
Hmm, is it mosh or ssh? What font is that?

**Comment by andrius** [comment]
debian stretch, mosh with pragmata pro. Another example with `ls -lai`:

![IMG_1480](https://user-images.githubusercontent.com/26776/54865583-d579a480-4d67-11e9-868b-c58429cc5d7a.jpeg)

**Comment by vees** [comment]
I can also recreate this any time there is a digit followed by a space and a u in a mosh session to Raspbian.

**Comment by dmd** [comment]
ssh as well - not limited to mosh. Nor to any specific remote host. Any time Blink displays `/\d us/` it converts the u to mu.

**Comment by yury** [comment]
Oh, yep. Turns out it is Pragamta Pro font thing. Able to reproduce just by typing `1 us` in blink shell (without any mosh or ssh session).

Can't repro with Iosevka or Fira Code.

**Comment by dmd** [comment]
Ha, yep. Agreed this is essentially a Pragmata Pro bug, not a Blink issue.

**Comment by yury** [comment]
Ok, I disabled contextual alternates for Pragmata Pro Mono (without ligatures).
https://docs.microsoft.com/en-us/typography/opentype/spec/featurelist

Next release will include that fix.

**Comment by andrius** [comment]
Looks like issue with PragmataPro, I getting same symbols with Termius SSH too

**Comment by yury** [comment]
v12.9 is out with the fix. Closing. Feel free to reopen.

**Comment by dmd** [comment]
This bug is still present in v13.0.155.
