### ISSUE TITLE
Black borders with Lightening-HDMI cable

### ISSUE THREAD

**Issue by coppercash** [blinksh/blink#708]
Hi.
Thanks for creating Blink, it is awesome.
I searched for similar issues, but saw none mentioning my problem.
I have an official Apple Lightening-HDMI cable.
When I connect with it and open Blink, I get an independent shell on an additional screen. That part is fine (and cool).
But there are black borders on all the four edges.
However, if I connect with AirPlay, there is no border at all.
Moreover, I think it is not my monitor that causes the trouble. Because if I play videos with the cable, I get a border-free view.

![Blink with Lightening-HDMI cable](https://user-images.githubusercontent.com/3679052/55124598-c157ed80-5141-11e9-8a96-3fc096733f6f.JPG)
Blink with Lightening-HDMI cable

![Blink with AirPlay](https://user-images.githubusercontent.com/3679052/55124757-53f88c80-5142-11e9-90d6-50324eedb88e.JPG)
Blink with AirPlay

**Comment by yury** [comment]
Hmm, very interesting. Super interesting that you have KB there.

**Comment by coppercash** [comment]
Yeah…
The keyboard is not always on the bottom.
It appears in the middle of the screen sometimes.
However it doesn't bother me, because it disappears once I connect my bluetooth KB.
The black borders do bother me.

**Comment by ppereza** [comment]
I have the same problem with my monitor

**Comment by yury** [comment]
Hi @ppereza and @coppercash,

What monitors do you have? (model, resolutions etc)

**Comment by kkk669** [comment]
Same here.
![GitHawk Upload by kkk669](https://i.imgur.com/DLUNG5y.jpg)

My display is LG 24UD58-B, and its resolution is 4K (3840x2160). It's connected to my 3rd generation 12.9" iPad Pro with a DisplayPort to USB-C cable.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kkk669** [comment]
In my case, the keyboard is sometimes on the bottom or on the side like the photo below.

![GitHawk Upload by kkk669](https://i.imgur.com/XuBE3Gr.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yury** [comment]
🙈

**Comment by yury** [comment]
Added option to control overscan compensation:

![IMG_0046](https://user-images.githubusercontent.com/5250/57177899-be9f9500-6e71-11e9-8e66-3ce2a1dd6de4.jpg)

`none` or `scale` should help.

**Comment by kkk669** [comment]
@yury It works. Thank you.

**Comment by ppereza** [comment]
Same to me. Thanks.

**Comment by yury** [comment]
Ok, v12.9 is out. Closing this issue.
