### ISSUE TITLE
Cannot connect to OpenSSH with hardened key exchange

### ISSUE THREAD

**Issue by rcarmo** [blinksh/blink#709]
I have a few servers that have tweaked key exchange configurations, and Blink fails to connect to them with the following message:

```
kex error : no match for method mac algo client->server: server [hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com], client [hmac-sha2-256,hmac-sha2-512,hmac-sha1]
```

The relevant bits of the OpenSSH configs on those hosts are all variants of this:

```
      HostKey /etc/ssh/ssh_host_ed25519_key
      KexAlgorithms curve25519-sha256@libssh.org
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
```

Is there any plan to support these key exchange mechanisms? Otherwise I can’t use `mosh` for about half of my new machines.

**Comment by yury** [comment]
Hi @rcarmo ,

Yep, we are waiting for new libssh release (0.9) with support of encrypt-then-mac. Patch is already there. 

Ref #616 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yury** [comment]
Ok, closing this issue. (Fixed in latest release)

Feel free to reopen if needed.
