### ISSUE TITLE
"URL scan" feature 

### ISSUE THREAD

**Issue by strowger** [blinksh/blink#71]
URL scan is offered by the android "connectbot" app. It searches the terminal screen for strings which start "http[s]://", lists them, and allows them to be opened in the browser with one tap. 

Would be a nice feature to have.

**Comment by carloscabanero** [comment]
I will see if at some point we can add HyperTerm support which also based on HTerm. If that is the case, then all kinds of crazy stuff and plugins will be doable and we will gain a bigger community to contribute to this side of the terminal :)

**Comment by joeshaw** [comment]
I have a suggestion for a potential shorter-term workaround with the iOS share sheet:

Right now you can select text and one of the options is "Share" -- would it be possible to add a share sheet action to "Open in Safari" the selection?  Then you could select a URL and open it relatively easily, without needing to copy it to the clipboard, switch to safari, paste it, etc.

It'd be nicer of course if you could do one tap, but this is something I do often enough that any improvement would be nice.

**Comment by carloscabanero** [comment]
This is a great solution until I figure out a better way, and should be easy to implement after release. In line with the suggestion for hterm, which is a good sign https://bugs.chromium.org/p/chromium/issues/detail?id=209181

**Comment by strowger** [comment]
That's not a bad suggestion but I find that *actually selecting the desired text* is very time-consuming compared to getting it opened in another tab.

I don't find the "double click" handler mentioned in that link to work for me - whether (on iOS) that should work by long-press, hard-press (3d-touch) or double-press, I'm not sure - but none of those seems to highlight links for me.

**Comment by joeshaw** [comment]
Yeah, selecting the text is a little bit jarring because it causes the keyboard to be dismissed and the entire viewport expands to fit the area and your text is no longer under your finger.  I wonder if it's possible to prevent the keyboard from being dismissed automatically?  (I guess probably not on the iPhone at least, which doesn't have a keyboard dismiss button.)

**Comment by strowger** [comment]
Agreed. Part of the problem with selection is indeed that the first tap/press makes the keyboard hide, which makes the screen redraw, which (in my usage) moves the text I'm trying to highlight to a different place on the screen.

I then sometimes get a selection box with 4 draggable handles (which is impossible to use because I can not move the "side" handles inwards from the sides of the screen), and sometimes get a selection with draggable "start" and "end" handles (which is usable). 

I often find that dragging the start or end handles on the latter type of selection, causes it to transform into the former.

I frequently have to paste entire lines of text (from the former type of selection) into an editor, and manually strip the material before & after the URL, before attempting to open the URL.

I would really like blink to be able to recognise URLs :-)

**Comment by carloscabanero** [comment]
I think improving selection for devices that the keyboard goes up and down all the time will improve the situation dramatically. I could try to avoid the keyboard from being dismissed, but in the iPhone it already has some weird behaviour (that's why you have to tap twice, and is something that doesn't happen in the iPad). The other option to make that better would be to try avoid the text from dropping down after the resize.

On the emulator interpreting the URLs, the problem is the one mentioned at the HTerm link. Changing the URLs means we would have to insert other anchor tags so that the browser identifies it properly, and that clashes with the text attributes. There could be some alternatives, maybe:

- Disable any special rendering for links so they get the rendering from everything around them, but still make them react to "tap to open".
- Make selections smarter, when you start over a URL to try to select all of it.
- Have a special gesture that could trigger a "url hunting" mode.

All of them would not be trivial to do.

**Comment by strowger** [comment]
The HTerm link says: "A double-click handler was added a few weeks ago the attempts to select url-shaped text.  The selection will be automatically copied to the clipboard, so it's easy to paste it into a browser window.  (You can also drag the selected text to a target window.)"

Do we have a way to invoke this functionality from Blink? It sounds perfect.

**Comment by carloscabanero** [comment]
Unfortunately we are not able to capture clicks in the terminal. But, here is what I found. If you have a selection on any part of a URL, then the function to expand it to the whole works perfectly (it actually expands to paths or routes of any kind). 

The idea would be to:
1 - Select any part of a URL. The Menu with Copy | Paste | Expand, etc... will open
2 - Press on Expand to get the full URL or path.
3 - Press on Open in Safari or add a Safari option at the Share menu.

What do you think?

**Comment by strowger** [comment]
That sounds like it would be a big improvement.

Could it be made to do both things with one tap - ie "expand to full URL or path and copy this to the clipboard" and/or "expand to full URL or path and open this in Safari". Could this be configurable?

I use chrome instead of Safari would and like the browser it opens in to be configurable, rather than defaulting to "Open in Safari", but I suspect I'll be the only one wanting this.

**Comment by joeshaw** [comment]
FWIW, several apps I use have both "Open in Safari" and "Open in Chrome" share sheet actions, and they're configurable so it's easy to remove one if you don't ever use it.

**Comment by carloscabanero** [comment]
The "expand and copy" or "open" can definitely be done. But then you wouldn't have access to the share sheet as joeshaw mentioned. I think separate and atomic actions are best in this case. We can start with that and then continue improving it.

**Comment by IMF2000** [comment]
Please could URL handling be looked at, ala prompt ssh, where clicking on a URL opens it in Safari with one tap?

Copy and paste of URLs is very hit and miss and quite infuriating :-)

Keep up the good work.

**Comment by tonilampela** [comment]
Just begun to use Blink today and just cursing why I didn’t try this earlier. However, only few minutes in I noticed that the URLs are not clickable (like in Prompt for example). Hopefully this feature is still on the roadmap.

**Comment by carloscabanero** [comment]
It is, we are moving away from HTerm and this will definitely be there. Hopefully we will be moving faster soon.

**Comment by Riprock** [comment]
This issue has the RTT label, is it the right place to report issues with the URLs beta feature?

If so I notice it doesn't deal with URLs that go over multiple lines well. It just tries to open the first line.

Also am I right in think it works by selecting any part of the URL, and it gives you the option to open to whole URL?

**Comment by yury** [comment]
Yep, it is right place.

Right now blink try to recognize url on intersection of first line of selection and selection itself. So yes, you can select any part of url.

Confirmed, multiple line urls should not work now.

**Comment by fffergal** [comment]
Cool. I use a big font size so most URLs go over multiple lines. Hope the feedback is useful.

**Comment by carloscabanero** [comment]
Thanks @fffergal!! Will keep it open until we can iron that out ;)
