### ISSUE TITLE
ios_system call from xcall not found?

### ISSUE THREAD

**Issue by michaelkrieger** [blinksh/blink#713]
/blink/Blink/Commands/xcall.m:33:10: fatal error: 'ios_system/ios_system.h' file not found
#include "ios_system/ios_system.h"

Meanwhile, ls -l Frameworks/ios_system/ios_system/ios_system.h 
-rw-r--r--  1 michael  staff  2279 27 Apr 13:21 Frameworks/ios_system/ios_system/ios_system.h

Even tried copying it down a level.  What am I missing here?

**Comment by yury** [comment]
Hi @michaelkrieger,

You should run `git submodule init` and `git submodule update`

**Comment by michaelkrieger** [comment]
Just did that.  No difference.

Tried doing a get_sources.sh for in the ios_system folder as well.

**Comment by yury** [comment]
`./get_frameworks.sh` should help.

**Comment by michaelkrieger** [comment]
If I just do the submodule init/update, I get errors about ios_system.h not being found as noted above (but from the blink sources)

If I do get_frameworks.sh I get the same error.

If I do get_frameworks.sh (as you suggest), I get error: Build input file cannot be found: '/Users/michael/Documents/XCode/blink/Frameworks/ios_system/curl/curl/src/tool_main.c'

If I then do ./get_sources.sh, then libssh isn't found

Ugh.

**Comment by yury** [comment]
Just tried

```
git clone --recursive git@github.com:blinksh/blink.git
cd blink
./get_frameworks.sh
```

And everything is ok for me. (As well as with travis)

**Comment by yury** [comment]
Hi @michaelkrieger,

Can we close this? Or you still have issues?

**Comment by yury** [comment]
Ok, closing... Feel free to reopen if needed.
