### ISSUE TITLE
FEATURE REQUEST: ssh config wildcards and optional hostname

### ISSUE THREAD

**Issue by derekbelrose** [blinksh/blink#720]
Normally, I would have something like the following in my ssh config file:

Host *.domain.tld
  User uname
  IdentityFile ~/.ssh/identity_file.pem
  ProxyCommand ssh uname@jumpoff.domain.tld nc %h %p

Host jumpoff.domain.tld
  User uname
  IdentityFile ~/.ssh/identity_file.pem
  ProxyCommand none

Then I can type ‘ssh www.domain.tld’ and it jump through jumpoff.domain.tld as a bastion host.  

The configuration dialog seems to make this impossible.  Is there another way of making this happen in Blink?

**Comment by derekbelrose** [comment]
This, also, allows me to define more hosts that same ProxyCommand statement.

**Comment by derekbelrose** [comment]
I assume the Host dialog acts as the ssh config file. If so, can it be modified to not have the HostName be required?

If so, then maybe wildcards in the Host setting would work.

**Comment by yaccin** [comment]
I would vote for the same feature request, as I would have to add hundreds of hosts, where several new hosts will be added on a reguar basis

**Comment by brandonshough** [comment]
This would be really nice....

**Comment by yury** [comment]
In blink v15 you can edit .ssh/config and use wildcards
