### ISSUE TITLE
Feature request: ssh port forwarding

### ISSUE THREAD

**Issue by nmattia** [blinksh/blink#730]
Would be great to support ssh port forwarding. E.g. one could forward a remote port to the iOS device with:

> ssh -R 12345:localhost:12345 xx.xx.xx.xx # remote IP

Blink seems to be able to open ports on the iOS device already:

![B56E09F6-6F05-4267-A326-625FA5A085EA](https://user-images.githubusercontent.com/6930756/58759671-3246c780-852e-11e9-9c79-fdd7d80054fc.png)

However I’m unable to connect to the remote when using the command above (connection refused). Looks like `ssh -R` is not opening the port.

**Comment by yury** [comment]
Hi @nmattia 

I think, you want ‘-L’ flag

**Comment by nmattia** [comment]
You’re absolutely right! Thanks.
