### ISSUE TITLE
Paste required selection 

### ISSUE THREAD

**Issue by bdillahu** [blinksh/blink#735]
Was trying to copy from another app and paste into a password prompt - couldn’t get paste button to appear. Found I had to click on existing text, not in the blank area.

Worked then.

**Comment by kkk669** [comment]
From this fall's iOS 13 and iPadOS 13 , you can use three-finger gestures to copy and paste text.

https://www.apple.com/ios/ios-13-preview/features/

**Comment by yury** [comment]
Hi @bdillahu, in iOS 12 you can swipe 2 fingers up to reveal control panel and tap `paste` button

**Comment by yury** [comment]
We will handle 3 finger tap

**Comment by kkk669** [comment]
@yury In iOS13, 3 finger tap is already used by the system to show this new menu. Is it OK?

![E7D66BB0-CF4F-4AD3-98BC-D2444C36F9AD](https://user-images.githubusercontent.com/601636/64072563-e68df080-cccb-11e9-808c-d8a9c06b369d.jpeg)

**Comment by yury** [comment]
@kkk669 
Yep, I just want to show our control panel in same design at the bottom and remove copy/paste from it.

**Comment by yury** [comment]
@kkk669 
like this

![IMG_AF4C2AC026CC-1](https://user-images.githubusercontent.com/5250/64186188-162d2c00-ce77-11e9-87b1-8a29d3648195.jpeg)

**Comment by kkk669** [comment]
@yury I like it so much. Thanks.

**Comment by yury** [comment]
Closing this one. Feel free to reopen if needed.
