### ISSUE TITLE
Spacebar suddenly didn’t work?

### ISSUE THREAD

**Issue by nchase** [blinksh/blink#736]
I encountered a weird bug where my spacebar stopped working. I thought it might have been unique to the Blink session that I was in, but I had the same issue in new sessions that I tried to open too. All other keys appeared to work (and naturally, all other apps worked). The issue went away after I closed and re-opened Blink.

**Comment by Zolotkey** [comment]
I just got a new iPad Pro and Logitech keyboard for Blink/work. I am noticing the same issue here. I can't get my space bar to work. Do you need logs?

**Comment by yury** [comment]
@Zolotkey do you have full keyboard control on in settings?

**Comment by Zolotkey** [comment]
I do, and that seems to be the issue. Once I turn that off I get my space back.

**Comment by yury** [comment]
Ok, yep. Go to Settings.app -> Accessibility -> Full Keyboard Access -> Commands -> Activate and change `Space` to `shift + space` or other shortcut.

**Comment by Zolotkey** [comment]
Thank you @yury!

**Comment by carloscabanero** [comment]
Documented https://github.com/blinksh/blink/discussions/1923
