### ISSUE TITLE
incorrect vim colors while using mosh and termguicolors vim option is enabled

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#737]
If you will add `set termguicolors` to the .vimrc (required by some themes, also nvim support it out of the box); the terminal colours in mosh won't be correct (everything is fine while using ssh connection)

**Comment by aanari** [comment]
Second this! Can you please ship latest mosh and not 1.3.2 (or make this an option in the app to pick your version)?

**Comment by yury** [comment]
It is already in the raw branch
We will release new version with master mosh this week.

**Comment by theseanl** [comment]
Still waiting for a release..

**Comment by yury** [comment]
Hi @theseanl,

Could you help us to test TestFlight version? Please email me at yury.korolev@gmail.com - I will send you test flight invite.

**Comment by theseanl** [comment]
Any update on this? No changes with testflight versions..

**Comment by yury** [comment]
Hi @theseanl,

What mosh server version do you use? You should install mosh from master branch.

**Comment by theseanl** [comment]
I'm running mosh-server 1.3.2.

**Comment by yury** [comment]
Hi @theseanl,

This is not enough. You should build it from master. See #609

**Comment by theseanl** [comment]
Ah, my bad, I was somehow running from release versions. Things are good in master branch. Please delete above comments :)

**Comment by yury** [comment]
@theseanl if you agree, I want to leave them for history and other people having same issue.

**Comment by delvedor** [comment]
Hello! I'm having this issue as well, every looks fine over ssh, while if I use Mosh and `set termguicolors`, the colors are all wrong.

I'm using the latest available version in the App Store of Blink.

**Comment by yury** [comment]
@delvedor what mosh version do you use?

**Comment by delvedor** [comment]
`mosh 1.3.2 [build mosh 1.3.2]`, freshly installed on Ubuntu via `apt-get`.

**Comment by yury** [comment]
@delvedor yep, you should install not released mosh from master to get true colours working. See #609

**Comment by delvedor** [comment]
Gotcha, thanks!

For posterity, you should install the latest mosh in Linux via:

```
$ git clone https://github.com/mobile-shell/mosh
$ cd mosh
$ ./autogen.sh
$ ./configure
$ make
# make install
```
