### ISSUE TITLE
Blink local shell does not present under iOS 10.3.3

### ISSUE THREAD

**Issue by jamesluberda** [blinksh/blink#739]
Hello,

Sometime within the last few months, one of the updates to Blink that I downloaded to two of my older devices caused the app to no longer present a shell/prompt on load. It does not crash, and I can access the menu, but still cannot access the (local) shell. The affected devices are:

iPad Pro 9.7" iOS version 10.3.3
iPhone SE iOS version 10.3.3

It does work on my 2017 iPad Pro 12.7" iOS 12.1.

Blink version is 12.8. I have recycled the affected devices and deleted and redownloaded the app to no avail. App store still says iOS 10 is supported and did not raise any flags on re-download that my version of iOS was incompatible or offer me the option of downloading an older version.

Again, to be very clear, this isn't a connectivity issue; I cannot even get as far as typing characters into the local Blink shell itself, i.e. no opportunity to type "ssh" or "mosh."

I hope there will be a simple fix, or you will see something I missed, but if this is not something to be looked into much further, or you cannot reproduce the issue, as a last ditch solution, is there any chance I might be able to get access to an older ipa?

Thank you,

James

James Luberda

**Comment by gnome-terminal** [comment]
The same problem here, my device is IPhone 7 Plus(IOS 10.3.2)

**Comment by jamesluberda** [comment]
After researching further, while I cannot pinpoint the version of Blink which broke under iOS 10.3.x, it appears that the last time I am certain Blink worked under iOS 10.3.x was September 2018, just before the big Nov 2 2018 update to version 12. It is possible that Blink was still working until one of the updates delievered after Nov 2, but I cannot confirm that.

HTH

**Comment by jamesluberda** [comment]
I downloaded the new release of Blink for iOS, 12.9, dated July 1, for my 10.3.x devices (after deleting the existing 12.8 versions). Unfortunately, the described issue remains, and the app store documentation still says iOS 10.x is supported, and still allows me to download the latest, even though it will not run properly.

I am sorry I do not have a development environment to try to contribute to resolving this issue. Again, if it is at least possible to have the app store kick back to an older release of the app for devices running 10.x, that would be something.

**Comment by jamesluberda** [comment]
On to Blink 12.10. App description still says iOS 10.0 or later supported, but still does not work on my 10.x devices.

**Comment by javierdemartin** [comment]
Closing this as the current version in the App Store supports iOS 13.2 or higher.
