### ISSUE TITLE
Blink crashing 1 second after start

### ISSUE THREAD

**Issue by botanicus** [blinksh/blink#741]
I can no longer use my Blink, because it keeps crashing just an instant after I launch it (see [video](https://www.dropbox.com/s/p6rxrf2tbx73a86/2019-06-13%2012.57.13.mov?dl=0)).

It happens every single time and I cannot get rid off it. I tried:

- To close the app (swipe it up from the app switcher view).
- Force restart my iPad.

None of this help.

I NEED BLINK FOR WORK, please advise urgently.

I do not want to reinstall it, as I suspect I'd loose my SSH private key.

I suppose there should be an error handler which on error tries to kill the session (or all the sessions) and start fresh. But always start.

**Comment by yury** [comment]
Hi @botanicus what version is that? TF or from App Store?

**Comment by yury** [comment]
@botanicus You can try install from Test Flight and then install from App Store - keys would be lost that way.

**Comment by botanicus** [comment]
Hey @yury, I'm not actually sure, as I switched iCloud to a different user, I suppose it might be an older TestFlight, but I cannot verify it.

My new user doesn't have access to TestFlight: could you please invite me? It's `james_c_russell at icloud.com`

I'll try to upgrade from there and see.

Thanks!

**Comment by yury** [comment]
Sent

**Comment by botanicus** [comment]
Thanks @yury, it fixed it (build 100 from TestFlight).
