### ISSUE TITLE
Wrong colors when using dark mode in iOS13

### ISSUE THREAD

**Issue by hpetersen** [blinksh/blink#742]
Hi @yury 

Had dark mode enabled today, and noticed that the tableViews is not acting right.
I will look into the code on Monday and see if I can fix this and make an pull request.

![9FE9C419-BED4-4056-9D2C-47683CA03EDB](https://user-images.githubusercontent.com/1536105/59524423-27981500-8ed4-11e9-8009-bd3e3dce66d5.png)
![A29EEA18-C165-47FE-859B-55FEDAE8541A](https://user-images.githubusercontent.com/1536105/59524425-27981500-8ed4-11e9-9c3c-5bd3fe5701fe.png)

**Comment by shaps80** [comment]
I'd like to work on this if no one else is @yury ?

**Comment by hpetersen** [comment]
Give it a shot @shaps80
I do not have the time right now as i have vacation in Italy with my 2 kids.

**Comment by yury** [comment]
@shaps80 yep, shoot

**Comment by shaps80** [comment]
The wife and son are aching for a holiday so we’re planning a little one kid August. But we my current contract is coming to an end I’ve got a little time. Love this app and love to contribute. 

Cheers for the warm welcome and support guys. I’ll update soon. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yury** [comment]
We have [dev](https://discord.gg/3ktm6WK) channel at discord. So we can help there faster.

**Comment by yury** [comment]
Fixed in next release

**Comment by yury** [comment]
Blink 13 is out. Thank you.
