### ISSUE TITLE
Feature Request: Add IOS Share Option to Copy/Paste menu when highlighting text

### ISSUE THREAD

**Issue by gsilvers** [blinksh/blink#743]
IOS offers a “share” button where rather than just clipboard you can pass into other apps via a share extension. Would be great to grab output from my remote box and “share” it to notes etc without leaving the app.

**Comment by treyharris** [comment]
Duplicate of [Feature request: "Share <url>..." selection menu action #636](/blinksh/blink/issues/636)

**Comment by shaps80** [comment]
I will open a PR tomorrow.
![4F82AA0E-0100-473D-A208-94E464AD68EB](https://user-images.githubusercontent.com/251310/61010784-a7988a00-a36f-11e9-8016-4cbf0a4853f4.jpeg)

**Comment by yury** [comment]
Implemented in Blink v13.1
