### ISSUE TITLE
Change `pwd` default behavior to use tilde

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#744]
Referencing #642 — the issue mentioned there was just about the real path of the root directory including the package name—which, as noted, is default iOS behavior and can’t easily be changed.

But there is another answer here: follow the behavior of some UNIX shells where the `pwd` builtin gives the “friendly” format; to get the “real” path, you can run `/bin/pwd` or `realpath $(pwd)`.

### Current output

```
blink> cd tmp
blink> /bin/pwd
/private/var/mobile/Containers/Data/Application/2D261802-E19A-43DC-8C9F-5733E4A828AF/Documents/tmp
blink> pwd
/private/var/mobile/Containers/Data/Application/2D261802-E19A-43DC-8C9F-5733E4A828AF/Documents/tmp
```

### Expected output

```
blink> cd tmp
blink> /bin/pwd
/private/var/mobile/Containers/Data/Application/2D261802-E19A-43DC-8C9F-5733E4A828AF/Documents/tmp
blink> pwd
~/tmp
```

Since Blink already deals with `~` in shell input, this seems like reasonably consistent behavior.

### Alternative

Since Blink currently ignores leading directories before command names (so that `pwd` and `/bin/pwd` and, for that matter, `NONEXISTANT/pwd` or `/private/pwd`), solving in exactly this way may not be possible (or desirable).

If so, I’d suggest a flag: `pwd -L` give the long `/private/var/mobile/Containers/...` version, but `pwd` give the friendly `~/...` version.

**Comment by holzschu** [comment]
For consistency, you'd probably want output from all commands to replace `/private/var/mobile/Containers/...` with `~/...`.
It can be done.

Or would that be only for `pwd`?

**Comment by treyharris** [comment]
> For consistency, you'd probably want output from all commands to replace `/private/var/mobile/Containers/...` with `~/...`.
> It can be done.
> 
> Or would that be only for `pwd`?

I _think_ only for `pwd`. Here’s my reasoning:
1. One might copy paths like that from Blink for use in other iPadOS programs. They may not handle `~` at all; and if they do, their notion of `~` will not match Blink’s.
2. `pwd` in conjunction with `cd` is meant to be used to abbreviate paths for the current interactive session only.
3. It’s generally considered best practice to use relative paths when they can be used portably because they share a common root (for example, in Git repositories), but absolute paths when they can’t. As I mentioned in no. 1 above, this is a case where there isn’t portability.
