### ISSUE TITLE
Blink crashes on iPadOS beta 8 when external monitor is connected

### ISSUE THREAD

**Issue by Schr3da** [blinksh/blink#745]
Hey, 

tried out the latest beta of iPadOS and discovered once you connect a external monitor the app closes unexpected. 

Steps to reproduce:

- Install iPadOS beta 2 on your iPad Pro 11 inch
- Connect an external monitor to the iPad
- Start Blink
- App will close unexpected

kind regards

**Comment by CN-Ping** [comment]
Having the same issue using public beta2/dev beta3.

**Comment by tdegrunt** [comment]
Same, but does work with split views / slide up with other apps. Also added this to another ticket, doing this seems to alleviate the issue overall.

**Comment by jakeunltd** [comment]
+1 I’m having the same issue here. On the latest developer beta for iPadOS on an 11” iPad Pro and it crashes every time. I have to disconnect the monitor to use blink.

**Comment by yury** [comment]
Yep, window on external display can't be first responder anymore :(

We have to rethink input system in that case. We are working on that.

**Comment by szawinis** [comment]
+1 I’m also having this issue on my 3rd gen 12.9 iPad Pro with the latest iPadOS beta installed.

**Comment by ltchurch88t** [comment]
+1 same here and hoping for a quick update as its killer not having that connection anymore!

**Comment by yury** [comment]
Update: Apple made big change to external screens. We can't put input on external window.
We have solved that, but only for next release. 
It should be available in TestFlight this week. We are testing and polishing it.

But again, it is not quick fix that we can back port to Blink 12. Sorry about that.

**Comment by yury** [comment]
Hi @jakeunltd, sure. Please email me your Apple ID at yury.korolev@gmail.com

**Comment by njuaplusplus** [comment]
Hi @yury, I can still only install the app of 109 version in TF. I wonder how I can update the version.

**Comment by yury** [comment]
Hi @njuaplusplus,

We do internal testing and polishing as much as we can. I hope, we will start pushing to public TF early next week.

**Comment by yury** [comment]
Finally pushed to public TF!

**Comment by njuaplusplus** [comment]
Hi yury, everything seems working greatly for the TF version, except for the caps as ctrl function.
I can use caps as ctrl in vim, but not outside of vim. For example, caps+c will send a c to the console instead of canceling the execution.

**Comment by yury** [comment]
Closing original issue. Feel free to reopen if needed.
