### ISSUE TITLE
Esc key mapping not working iPadOS-beta 2

### ISSUE THREAD

**Issue by Schr3da** [blinksh/blink#746]
Currently the esc key mapping on the ipad does not work

**Comment by Schr3da** [comment]
As a current workaround I recommend to modify your .vimrc by adding a new key mapping for esc.
I personally added the following key mapping in my .vimrc on my host system. 

> imap <C-q> <ESC>

as a result I'm able to esc from insert mode 👍

**Comment by yury** [comment]
As a current workaround cmd+. still works for me (it is system wide shortcut for ESC on iOS)

**Comment by 0xApe** [comment]
Also Caps lock to ctrl or esc does not work on iPadOS PB1

**Comment by yury** [comment]
PB1 == B2.

I hope they push B3 today

**Comment by yury** [comment]
B3 🤞

**Comment by yury** [comment]
Nope ;(

**Comment by ericboehs** [comment]
I just tested as well. :( Not working for me either (beta 3).

**Comment by spiritphyz** [comment]
> As a current workaround cmd+. still works for me (it is system wide shortcut for ESC on iOS)

Oh, I never knew about `Cmd+.` even though I’ve been using Blink for years. 

Could you add this shortcut to the help screen for Blink that shows up when you press and hold the `Command` key when an external keyboard is attached? This could aid in discovery of this very handy shortcut for Vim users.

**Comment by ericboehs** [comment]
Caps as Ctrl is what I'm needing.

**Comment by jramapuram** [comment]
Here for the Ctrl as Caps as well. Emacs without Caps is misery.

**Comment by yury** [comment]
Beta 5 fixed all the things!
