### ISSUE TITLE
Nothing but black screen and crash launching on ios13 on Xr.

### ISSUE THREAD

**Issue by MacDragon** [blinksh/blink#747]
Using either testflight or app store version, on Xr I'm getting nothing but a black screen launching for some reason, but working on iPad.

**Comment by yury** [comment]
beta2 or 1?

**Comment by MacDragon** [comment]
Same behaviour on both for me.

**Comment by perelin** [comment]
Same behavior for me but on iPad. 
iPad Air 2019, iPadOS Public Beta (13.0)
Can I somehow help resolving this?

**Comment by yury** [comment]
@perelin Can you try Test Flight version? (email me at yury.korolev@gmail.com)

**Comment by perelin** [comment]
@yury : the Testflight version works! thanks for the quick reply and support!

**Comment by MacDragon** [comment]
This appears fixed in iOS beta 3.
