### ISSUE TITLE
I can not use blink when I update the ipads to 13 beta2

### ISSUE THREAD

**Issue by yefeiyu** [blinksh/blink#751]
please update `blink` , thanks.

**Comment by yury** [comment]
Hi @yefeiyu,

Is it blank screen or what happened?  Can I send you TestFlight version, so you can check our next release?

**Comment by petermbenjamin** [comment]
For what it's worth, I am on iPadOS developer beta 2, which is the same as public beta 1, and I do not have any issues.

@yefeiyu - can you provide more information?

**Comment by shaps80** [comment]
No issues for me either.

**Comment by Higgcz** [comment]
I’m on public beta 1 and Blink stopped working today, it just showed blank screen, however after restart it’s seems okay for now. @yefeiyu Did you try to restart your iPad?

**Comment by shaps80** [comment]
FYI I can’t get Blink running on by the 3 now

**Comment by shaps80** [comment]
Hmm no idea what's going on here but its working again.

**Comment by alump** [comment]
I can’t get Blink to start with Public Beta 2. I think I had same issue with Public Beta 1, but then at one day it started to work (was really slow to start still). Not sure what made it work. This time i tried to uninstalling blink, and restarting iPad, but no luck.

**Comment by shaps80** [comment]
So about an hour ago Beta 3 didn't work for me again but now it is. I wonder if there's something during the app startup that's getting blocked or something. iCloud sync perhaps? I don't know if its Beta specific but there's definitely 'something' going wrong. 

Next time its happening I'll try and pull the code and run it through dev so I can maybe provide more info.

@yury Is it relatively easy to setup the project in Xcode myself?

**Comment by yury** [comment]
@shaps80 it should be very easy to build it. But be aware it only works on devices (not simulators).

I think I know where problem is (it is in our control panel).

**Comment by alump** [comment]
Yes, I think it's iCloud issue. Disabled iCloud for Blink (System Settings -> Apple ID -> iCloud -> Unselect Blink)... and now my Blink starts, and fast.

**Comment by shaps80** [comment]
😂 Welcome to my club. Interestingly its working fine today. Most of the time its great to be honest.

@yury on that note, I actually can't bring up the control panel with 2 finger swipe up as suggested in the help. I don't even know what it is 😂

**Comment by shaps80** [comment]
Just tested 

> 😂 Welcome to my club. Interestingly its working fine today. Most of the time its great to be honest.
> 
> @yury on that note, I actually can't bring up the control panel with 2 finger swipe up as suggested in the help. I don't even know what it is 😂

So just tried the app on iOS 12 I see what you're talking about now. Yep that does not work at all on iOS 13 ;)

**Comment by tdegrunt** [comment]
Have the same issue, but it will work if I use slide-over and drag Blink in a safari window for example.

**Comment by petermbenjamin** [comment]
So, I just updated to iPadOS Developer Beta 4 and got the blank screen.

**Comment by yury** [comment]
I think we can close this issue. Please reopen if needed.
