### ISSUE TITLE
iOS 13 multiple window support

### ISSUE THREAD

**Issue by shaps80** [blinksh/blink#753]
Hi,

I have always wished for a split-pane style feature in this app but realise that might be outside the core-goals of this app.

That being said with the new multiple window support in iOS 13, this is a feature where Blink would shine.

I wanted to start the conversation (as I couldn't find an existing one?) to determine any issues that might arise in getting this feature into the app.

I'd be keen to get involved in making this happen but I'm less familiar at the moment with some of the inner workings to know what areas need assessing? Help would be appreciated :)

**Comment by yury** [comment]
Hi @shaps80,

We are currently working on that feature. We decided try new SwiftUI for that. So I'm in the middle of learning it :)

Previous prototype was build on collection view. See #547

**Comment by shaps80** [comment]
Awesome! Yeah you can do it with either SwiftUI or not. I found a nice little sample that shows both working alongside each other which is cool. I'm excited for this feature. I use `tmux` for now but it would be nice move the 'window' side of things into iOS and just handle Panes through `tmux`.

Thanks for quick reply. I'll wait patiently then :)

**Comment by yury** [comment]
Please share that little sample if possible :)

**Comment by shaps80** [comment]
Sure. Its a great little example that even shows how to use NSActivity instances to spawn new windows programmatically. Super simple too. You'll see how little code there is.

https://github.com/TwoLivesLeft/BehindTheScenes/tree/master/BehindTheScenes

These WWDC videos are also a worth skimming through.

https://developer.apple.com/videos/play/wwdc2019/212/
https://developer.apple.com/videos/play/wwdc2019/258/
https://developer.apple.com/videos/play/wwdc2019/259/
https://developer.apple.com/videos/play/wwdc2019/246/

**Comment by yury** [comment]
![C83103E8-B61D-4340-A542-B58E991CE8E1](https://user-images.githubusercontent.com/5250/60659478-2700f780-9e5e-11e9-9d12-52178fde553a.png)

**Comment by shaps80** [comment]
Want!

**Comment by shaps80** [comment]
Out of curiosity did you also build any drag-and-drop support into this approach?

**Comment by yury** [comment]
Not yet. Working on new state restoration for mosh.

**Comment by yury** [comment]
Progress update
https://youtu.be/qpAmgaZ-GPg

**Comment by shaps80** [comment]
AMAZING! :) Cannot wait for this!

**Comment by shaps80** [comment]
Now all we need it `tmux` integration so I can automatically generate a vertical split into a new window! Guessing that's problematic :)

**Comment by yury** [comment]
We pushed v13b130 to public Test Flight.

(Finally)

**Comment by jzalger** [comment]
Any docs on how to get going with the Test Flight?
