### ISSUE TITLE
[Feature Request] Additional key mapping for escape

### ISSUE THREAD

**Issue by jimcroft** [blinksh/blink#754]
On a number of non US English keyboard layouts (International English, British English, and most if not all European language layouts) the key to the left of the number row is “§” rather than “`”. 

That character is pretty niche and hardly used but its location would make it a great key to map escape to if possible.

Mapping this top left “§” to key escape and caps to ctrl would make physical iPad keyboards feel much more like my laptop and desktop setups.

**Comment by jimcroft** [comment]
PS. Looks like this is a duplicate of 

https://github.com/blinksh/blink/issues/694
https://github.com/blinksh/blink/issues/649

So a bit of demand for this feature.

**Comment by shaps80** [comment]
@yury is this potentially within scope (easy enough) for an external contribution? This app has made my year on the iPad Pro so I'd love the opportunity to give back.

**Comment by yury** [comment]
@shaps80 sure! We love PRs!

**Comment by shaps80** [comment]
@yury Not sure the best place to discuss this so I'll start here.

I've pulled the repo, run `./get_frameworks.sh`

Now I don't have your signing so updated to use my own for development and disabled iCloud.
Is that the recommended approach you've been using?

**Comment by yury** [comment]
Yep, signing is an issue. You have to disable iCloud. If you find better way - please let me know.

Raw branch is latest (think of it as a master branch).

For issues/tasks - you can just tell me that you are working on it. Right now there are not so many contributors. So I don't think will be any conflicts.

Swift is totally fine now. I tried to implement some things with it, but step on includes cycle, so just be aware of that.

Also note, that raw branch is iOS 13 only, so feel free to use modern things like SwiftUI and don't think about backward compatibility.

**Comment by shaps80** [comment]
Oh nice so this version won’t support iOS 12? That’s great. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yury** [comment]
We want to build the best experience on iOS 13 as quickly as possible.

**Comment by yury** [comment]
Blink v13.1 is out with a fix.
You can now assign any combination to esc config->keyboard->custom presses.
Feel free to reopen if needed.
