### ISSUE TITLE
Crashes when redirecting output to a file

### ISSUE THREAD

**Issue by dkubert** [blinksh/blink#756]
ls > output.txt  wget http://www.cbc.ca > output.txt cause crashes every time that I've tried them. 

System info: iPad Pro 11", iOS 12.3.1

**Comment by knilb** [comment]
Same issue (I just downloaded Blinksh app from the App Store on Aug 15) - any command output directed to local file causes Blink to crash every time.

cat known_hosts > output.txt
awk '/arbornet/' known_hosts > myhosts.txt

System info: iPad Pro 10.5, iOS 12.1.4

**Comment by yury** [comment]
Fixed in latest TF version

**Comment by grayfall** [comment]
Has this issue been patched in the App Store version? It doesn't seem so.

**Comment by inzel** [comment]
Also experiencing this issue

**Comment by yury** [comment]
@inzel we fixed that. Pushing hard to push v13 to app store. (ETA this week)

**Comment by dkubert** [comment]
That’s great news! Thanks!
