### ISSUE TITLE
specific port ignored

### ISSUE THREAD

**Issue by alqa-dash** [blinksh/blink#759]
Hello,

Blink ignores -p parameter and tries to connect to the default port 22 instead of specified in command line as argument

**Comment by yury** [comment]
Hi @alqa-dash,

`ssh` command doesn't ignore `-p`. For `mosh` you should use `-P`.

**Comment by alqa-dash** [comment]
Hm, you're right. I tried to connect using custom port when application was started from Xcode and I got "timed out" error. But now without Xcode I managed to connect to desired port. Thank you for great application!

**Comment by alqa-dash** [comment]
One more question in addition (not sure I need to create new issue): do you plan to add ssh port forwarding in config section? This is not very convenient to type is each time on iPhone screen.

**Comment by yury** [comment]
No in plans yet... I think it is good candidate to issue, so we can track that.

**Comment by alqa-dash** [comment]
There was already such proposal "Feature request: ssh port forwarding #730" early in June. But it was closed with reply "..one can use -L option.." :)

**Comment by yury** [comment]
As I understood it is about `-R` vs `-L` no?

**Comment by alqa-dash** [comment]
yes, -R for remote port forwarding, -L for local accordingly.

**Comment by yury** [comment]
Yep, but not about configuration in Settings.
