### ISSUE TITLE
SSH port forward yields "ssh: illegal option -- ?"

### ISSUE THREAD

**Issue by jtdaugherty** [blinksh/blink#760]
Version: 12.9.108

Steps to reproduce:
* Create a host profile, call it `myhost`
* Run `ssh -L 8001:localhost:8001 myhost`

Result:
```
ssh: illegal option -- �
usage: ssh [-aCGVqTtvx]
           [-F configFile] [-i identity_file]
           [-l login_name] [-o option]
           [-p port] [-L address] [-R address]
           [-W host:port]
           [user@]hostname [command]
```

**Comment by yury** [comment]
It might be smart punctuation thin. Minus replaced with unicode symbol

**Comment by jtdaugherty** [comment]
I checked and Smart Punctuation is currently disabled.

**Comment by shrop** [comment]
I ran into this issue today. Same results as originally reported.

**Comment by shrop** [comment]
For clarification, my issue was trying SSH -N and the -N really may not be supported. All good except I did see some strange unicode characters in the illegal operation message, but that seems unrelated to this original issue.

**Comment by carloscabanero** [comment]
This should all be fixed on next Blink. Including -N ;)
