### ISSUE TITLE
Blink doesn't work at all on latest iOS 13b4

### ISSUE THREAD

**Issue by MakeItGreatAgain** [blinksh/blink#765]

**Comment by MakeItGreatAgain** [comment]
Just shows a black screen, never the terminal.

**Comment by Schr3da** [comment]
Same here :(

**Comment by thecolorchanges** [comment]
can confirm, using testflight build

**Comment by spiritphyz** [comment]
I have the paid version. The app was working fine in beta 3 but not in beta 4.

**Comment by pangerc** [comment]
Does it work for anyone at all on b4?

**Comment by carloscabanero** [comment]
I couldn’t test myself yet, but it looks pretty bad.

**Comment by glberen** [comment]
Doesn’t work for me either

**Comment by carloscabanero** [comment]
This one seems to be they changed something on WKWebView and broke our rendering, so probably falls on our side. We have been making a lot of changes there so maybe we can import and fix if we figure out what is going on.

**Comment by petermbenjamin** [comment]
Not working for me on iPadOS Developer Beta 4.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jaromirrivera** [comment]
It’s not working for me as well... all we get it a blank screen.

**Comment by yury** [comment]
Yep, smth changes in WKWebView

```
2019-07-18 09:56:19.122133+0300 Blink[255:3633] Received an unexpected URL from the web process: 'file:///var/containers/Bundle/Application/1B01499D-33F1-4BCC-84A5-ADF56758A2A6/Blink.app/term.html'

Received an unexpected URL from the web process: 'file:///var/containers/Bundle/Application/1B01499D-33F1-4BCC-84A5-ADF56758A2A6/Blink.app/term.html'
2019-07-18 09:56:19.122199+0300 Blink[255:3633] [Process] 0x12c813418 - WebPageProxy::Ignoring request to load this main resource because it is outside the sandbox
```

**Comment by Iguana9999phil** [comment]
Yup also not working for me, I'm on the testflight build. Gave me a change to test Termius and after an afternoon, a frustrating one, I will be gratefull if a new build can be pushed asap. MISS BLINK ;-)

**Comment by yury** [comment]
Just push v12.10 on TF with a fix.

**Comment by Iguana9999phil** [comment]
How long does it take for it to show up? Shows 12.9 for me

**Comment by yury** [comment]
I think it should be there now. Try to pull to refresh.

**Comment by Iguana9999phil** [comment]
Yeah still not showing up on TF for me either.

**Comment by yury** [comment]
Ok, status update. 12.10 on TF review.

@pangerc it is in 12-stable branch

**Comment by Iguana9999phil** [comment]
Apple still need to review it even on TF? Thought TF bypassed the whole review process.

**Comment by yury** [comment]
<img width="661" alt="Screenshot 2019-07-18 at 13 49 00" src="https://user-images.githubusercontent.com/5250/61451783-e2e41b80-a962-11e9-963f-f38d863df036.png">

**Comment by Iguana9999phil** [comment]
Yury; post wasn't that I don't believe you, I'm just surprised that Apple does reviews for TF builds. Didn't know that, thought they only did review for when it goes on the AppStore.

**Comment by yury** [comment]
Sometimes it is super fast, sometimes no...

**Comment by Iguana9999phil** [comment]
Guess Apple changed their own rules because in the overview of TF on their page it states only the first build gets a review, typical Apple.... (Yes I'm frustrated with Apple at the moment for many other reasons and this adds to it)

**Comment by thisishuey** [comment]
> How can one get on TF? Can’t see 12.10 in the repo :(

@yury Are there instructions somewhere for requesting to be a beta tester?

**Comment by yury** [comment]
Oh, just email me at yury.korolev@gmail.com

**Comment by thisishuey** [comment]
@yury excellent, thanks!

**Comment by yury** [comment]
Status update:
TestFlight version is still waiting for review. 
App Store version is in review now!

**Comment by yury** [comment]
Another status update:
TF still waiting for review
AppStore released

**Comment by petermbenjamin** [comment]
Updated to Blink v12.10 on the AppStore and it seems to be working again for me.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yury** [comment]
Ok, closing this issue.
