### ISSUE TITLE
Shortcuts not working in current Raw branch

### ISSUE THREAD

**Issue by jaydonhansen** [blinksh/blink#766]
Launches into Blink but does nothing after pressing shortcuts button for a shortcut configured for Blink Shell “run: ssh moss” (the hostname). Current settings include username/password configured for a standard SSH host connection in iOS 13 beta 4, current raw 12.10.

Here is my host config:

![FFC2CBEB-4F98-4B6C-8BBF-AE7B24BA7E7F](https://user-images.githubusercontent.com/49255230/61571085-59545b00-aad4-11e9-9715-0372a6771cc6.jpeg)

**Comment by nriley** [comment]
This still appears to be broken with the final version of 13.0.  Trying to launch via a shortcut opens Blink to a blank screen.

**Comment by carloscabanero** [comment]
Closing as old. This was probably not properly encoding the space.
