### ISSUE TITLE
Can no longer cd into iCloud directory - permission denied.

### ISSUE THREAD

**Issue by idvorkin** [blinksh/blink#767]

**Comment by idvorkin** [comment]
I just upgraded to iOS 13, and my iPad can no longer cd into the iCloud directory. It gets permission denied.   What’s curious is tab completion looks like it will work.  Screen shot:


![](https://pasteboard.co/Ip2zdSx.png)

IMAGE:https://pasteboard.co/Ip2zdSx.png

**Comment by yury** [comment]
Yep, confirmed. 

Will look. Thank you.

**Comment by yury** [comment]
Fixed in b6!

Thank you for heads up!
