### ISSUE TITLE
Regression: `> file` syntax causes crash

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#769]
Trying to create a file (for `scp`’ing up to a remote host, for example) using the `>` operator causes a crash in the most recent TestFlight.

E.g., the expected (and actual until recently) behavior:
```console
blink> cat > myfile
typing stuff
pasting more stuff with ⌘V
ending with ⌃D
^D
blink> 
```
would create the file `myfile` with the contents given above.

But now:
```console
blink> cat > myfile
```

crashes Blink _immediately_ upon pressing Return after that command. However—if it does not exist, an empty `myfile` is still created.

**Comment by yury** [comment]
It is working now in TF 13b130

**Comment by treyharris** [comment]
Interesting, I just got a TestFlight notification of an update for a new version to test, but I still have the issue.

I’m not entirely sure that I’m getting the installation, though; it used to be that tapping this notification would take me to Blink in TestFlight, where there would be a blue Update button that would then turn to Open (like in the App Store). But for the past two versions, when I’ve opened TestFlight I’ve seen the expiration timer reset (right now it says “90 days”, when I know a week or so ago it said thirty-something, but no Update button presented. Since the expiration was updating, I was guessing TestFlight now installs in the background, but now I’m not sure.

`help` says:

```console
blink> help

Blink: v12.10.109. Jul 18 2019
...
```

so I’m not entirely sure I’m getting updates.

**Comment by yury** [comment]
Oh, Blink 14 is iOS 13 only.

**Comment by yury** [comment]
Blink 13 is out!
