### ISSUE TITLE
cap and ctrl doesn’t work on iPadOS

### ISSUE THREAD

**Issue by charleszheng44** [blinksh/blink#772]
Hardware: iPad pro, smartkeyboard
OS: iPadOS
Problem: after upgrading to iPadOS, blink doesn’t recognize ctrl and cap anymore (on both virtual keyboard and external keyboard)

**Comment by nanzhong** [comment]
I think this is related to https://github.com/blinksh/blink/issues/732.

tl;dr is that Apple introduced a regression in how `UIKeyCommand`s handle the alpha shift (caps lock) modifier.

I've got a link to a patch that works if you can build and install blink yourself.

**Comment by yury** [comment]
We are holding this patch since it use private api. Patiently waiting for the fix from apple.

**Comment by charleszheng44** [comment]
Thanks, @nanzhong.

**Comment by charleszheng44** [comment]
Waiting for the official fix from apple. #732 provides a quick fix.

**Comment by yury** [comment]
Beta 5 fixes kb!
