### ISSUE TITLE
unmapped capslock key not ‘capslocking’

### ISSUE THREAD

**Issue by ssgam** [blinksh/blink#773]
on ipad pro 2018 and apple’s smart keyboard folio.

the capslock key is not remapped to anything,
so am expecting that it works as capslock: entry of uppercase of characters ...

it is not ... 

outside of blink, capslock is capslock ; ie: works correctly ...

wasn’t paying attention to this before (started using this
more frequently), found i cannot capslock and then key in
bash environment bars in upper ... (unless shift key is pressed
as well)

**Comment by carloscabanero** [comment]
Couldn't replicate. Does this still happen to you?
