### ISSUE TITLE
Nslookup no echo

### ISSUE THREAD

**Issue by sn00pster** [blinksh/blink#775]
Issuing a nslookup command results in a prompt, but no echoing of any text input, although it does accept the text and perform the lookup showing the results.

**Comment by tdobes** [comment]
This also occurs when starting “telnet” in interactive mode (no parameters): commands are interpreted, but not echoed back to the console.

**Comment by yury** [comment]
telnet and nslookup will work in interactive mode in next release

https://youtu.be/0lkLCyzPKnQ
