### ISSUE TITLE
After git clone --recursive https://github.com/blinksh/blink.git && \ cd blink && ./get_frameworks.sh，how to run it?

### ISSUE THREAD

**Issue by WQDev2013** [blinksh/blink#776]

**Comment by yury** [comment]
1. You can't run it on simulator
2. You should disable cloud storage and change team and app identifier (see https://github.com/blinksh/blink/blob/raw/BUILD.md#compiling)
3. Choose right build target and device and hit CMD+R

**Comment by WQDev2013** [comment]
> * You can't run it on simulator
> * You should disable cloud storage and change team and app identifier (see https://github.com/blinksh/blink/blob/raw/BUILD.md#compiling)
> * Choose right build target and device and hit CMD+R

I run it on device,still one hundred undefined symbol error occurs. does it need add any libs in addition

**Comment by yury** [comment]
Hmm, can you post screenshot with errors in Xcode?

**Comment by WQDev2013** [comment]
> Hmm, can you post screenshot with errors in Xcode?
I remove the libssh2.a which I add when I run it on simulator,undefined symbol error be solved，thanks you very much!

<img width="269" alt="image" src="https://user-images.githubusercontent.com/13076989/62115601-44a16f80-b2eb-11e9-8b76-71f223122424.png">

**Comment by yury** [comment]
Yep, you should disable iCloud and change bundle id to your team. 

Select blink target -> Signing & Capabilities.

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/5250/62116289-9a155680-b2c2-11e9-9c1e-1d887de53433.png">

**Comment by WQDev2013** [comment]
not found iCloud
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/13076989/62117317-4a4c8480-b2ee-11e9-9670-07d16ef336e7.png">

**Comment by WQDev2013** [comment]
Unfortunately, I didn't find iCloud
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/13076989/62117442-8384f480-b2ee-11e9-9cba-8900cd2bb625.png">

**Comment by yury** [comment]
Hmm, 16 capabilities unavailable..... What link it opens when you press learn more at the bottom?

**Comment by WQDev2013** [comment]
https://developer.apple.com/support/app-capabilities/

**Comment by yury** [comment]
So it seems to me, that you are not member of Apple Developer Program.

**Comment by WQDev2013** [comment]
You are great. Thank you for your patient help. My personal account is not member of Apple Developer Program。when I change it to my company account,it works
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/13076989/62118650-a1ebef80-b2f0-11e9-966d-26386951b3d6.png">

**Comment by yury** [comment]
Ok, cool. Closing then.

Thank you!
