### ISSUE TITLE
Supporting blink development

### ISSUE THREAD

**Issue by jwr** [blinksh/blink#779]
Is there a way to support sustainable blink development? Github Sponsors perhaps, or other ways?

I like Blink, but unfortunately without general keyboard mappings (like in Terminal or iTerm2, where an arbitrary sequence can be assigned to every key combination) and with some bindings forced (function keys, cursor keys, built-in blink keys) it is useless for working in Emacs. I would really like to use Blink, but I can't: my Emacs has too many commands that use multiple modifiers (like Cmd-Shift-F, Ctrl-Cmd-➡️, Cmd-1 and similar).

I can describe in detail what is needed, but I thought I'd ask first if there is a way to support development.

**Comment by yury** [comment]
We are working on this. iOS 13 gives us a lot of work to do, but that on the list too. I’m working on brand new SF kb right now. But in general, we also redo our key bindings too

**Comment by jwr** [comment]
Well, my use case is always with a hardware keyboard and the problem with Blink is that it has many built-in keybindings and that it can't accept arbitrary keybindings that generate arbitrary sequences (like Terminal and iTerm can).

But in any case, the question is still valid: I realize that a one-time purchase isn't enough for sustainable software development, so is there a way to set up recurring donations?

**Comment by carloscabanero** [comment]
Hi @jwr! Thanks a lot for your message. Please check out https://github.com/blinksh/blink/issues/448#issuecomment-521436913 

I would really love to get your take on it. :)

**Comment by carloscabanero** [comment]
Closing here. The way to support Blink development now is through subscriptions, which reflects better the on-going work we are doing.
