### ISSUE TITLE
Should Ctrl-C from blink prompt exit?

### ISSUE THREAD

**Issue by joeshaw** [blinksh/blink#78]
Blink 0.916.25

If you hit `ctrl-c` from a `blink>` prompt, it prints `Bye!` and the terminal is no longer responsive.

This seems like a bug to me, or at least a usability problem.

Swiping down with two fingers does close it, but if you hadn't run `help` previously you wouldn't know this, and you'd be stuck.

**Comment by goerz** [comment]
This is closely related to  #44

**Comment by carloscabanero** [comment]
Yup, fixing #44 would fix this one too. Unfortunately #44 isn't as obvious as I thought. I'm trying to replicate the normal terminal behaviour, and need to send a signal somewhere for it to be closed.

Closing here then. Let me know if you have a different idea or suggestion than triggering the automatic closing behaviour after "Bye!"
