### ISSUE TITLE
The pinch-to-zoom gesture problem

### ISSUE THREAD

**Issue by aofei** [blinksh/blink#783]
I often inadvertently perform the pinch-to-zoom gesture that cause the font size to change, then I have to use the "Zoom In (Command-+)" or "Zoom Out (Command--)" shortcuts multiple times to revert the changes. Or I can only restart the app or create a new tab to get the results I want. All of these solutions aren't ideal.

So I suggest that we should change the behavior of the "Reset Zoom (Command-=)" shortcut to reset the font to the size set by the user in the "Settings-Appearance" instead of the default size of the system.

Or we can provide an option to disable the pinch-to-zoom gesture.

**Comment by yury** [comment]
We improved pinch-to-zoom gesture a lot. It not triggered so ofter now.

**Comment by aofei** [comment]
Of course, I believe that you have made a lot of improvements. We all thank you for that. ❤️ However, I think it might be better to have a switch here. At least for users like me, the pinch-to-zoom gesture isn't that needed, no offense.

**Comment by yury** [comment]
We pushed Blink 13. Please take a look.

**Comment by aofei** [comment]
The first change I found is that the CapsLock->Ctrl mapping no longer works after upgrading to Blink 13...

And the pinch-to-zoom gesture seems to have improved. Well done! 😊

**Comment by yury** [comment]
iOS really messed up with KB in v13 :( We filled a lot of radars.

**Comment by aofei** [comment]
This CapsLock->Ctrl mapping is one of the features I need most. And I use Blink every day, now I have to go back to my MBP for my daily work. So I'm really hope that this problem will be fixed soon. 😊

![screenshot](https://user-images.githubusercontent.com/5037285/67851115-abc9fc80-fb44-11e9-9fc3-ce9c0444dad0.jpeg)

**Comment by yury** [comment]
Can you show your kb config screen in blink? I have it working now...

**Comment by aofei** [comment]
![screenshot](https://user-images.githubusercontent.com/5037285/67851523-9bfee800-fb45-11e9-8ae1-686cf6a8f07a.jpeg)

Nothing changed compared the previous Blink version.

**Comment by andrius** [comment]
@aofei try to completely remove blink and restart ipad... I had issues in microsoft office with licensing and only complete purge + reboot helped... something get cached;

@yury my issues get fixed after these steps (Ctrl as Esc worked and cmd - arrows get fixed

**Comment by aofei** [comment]
@yury 

Please see this: https://twitter.com/aofeisheng/status/1189876693231534080

And thanks to @andrius, I just tried to completely remove Blink 13 and restart the iPad and then reinstall it, but the problems still exists. 🥺

**Comment by yury** [comment]
@aofei if you just press caps lock once and try to enter symbols again. Is it normal?

**Comment by aofei** [comment]
So I just relaunched Blink and then switched the CapsLock multiple times. I found out that if I don't press the CapsLock or just press once (or just remove the mapping), then everything is fine.

Anyway, it seems that this problem is related to the CapsLock->Ctrl mapping problem.

**Comment by yury** [comment]
Closing, origin issue is fixed :)

Thank you.
