### ISSUE TITLE
Blink shell black screen on iOS 13 beta 7

### ISSUE THREAD

**Issue by jhanstra** [blinksh/blink#785]
I’ve seen this in other issues but I’m getting a blank screen with the latest 12.10 version on iPad OS 13 beta 7 and can’t do anything. I’m a new Blink user and super excited to try it though! Developing on an iPad is blowing my mind.

**Comment by yury** [comment]
Working on that...

**Comment by jhanstra** [comment]
Update: it's working on iPad OS 13 beta 8! 🚀
