### ISSUE TITLE
ssh-copy-id requires an identity file, but i don't know what it is

### ISSUE THREAD

**Issue by joeshaw** [blinksh/blink#79]
Blink 0.916.25

```
blink> ssh-copy-id
Usage: ssh-copy-id identity_file [user@]host
```

I'm not sure what my identity file is in blink.  I guessed `~/.ssh/id_rsa.pub` but got `ERROR: No identities found.`

Key management would be nice (I see that #50 is somewhat related to that, but I'd love to be able to add/retrieve my own keys in blink) but without that it'd be nice if `ssh-copy-id` knew to use the built-in key for that.

**Comment by carloscabanero** [comment]
Well, this means the behaviour is definitely unclear.

I think completing the help message with what to do and how to act next would help this case. So for example, if you do not have keys, "please go to config and create keys for your profile". If you have keys, then probably listing them could be nice too.

**Comment by joeshaw** [comment]
Ah, you're right.  I missed config completely for some reason.  Maybe color highlighting the command names in `help` would help?

Importing keys is always tough.  I like that you have a copy-from-clipboard -- will you be able to add them from iTunes at some point?  The issue I have with `ssh-copy-id` is that I have password auth turned off on many of my hosts, so I can't copy the key there without a key.

**Comment by joeshaw** [comment]
Just saw [on twitter](https://twitter.com/BlinkShell/status/765582813336858624) that `config` was missing from `help` on the previous version, which happened to be the first version I ever used.  So I didn't miss it and I'm not crazy. :)

You can feel free to close this then, now that that's fixed.

**Comment by carloscabanero** [comment]
I don't think we will be able to import them from iTunes, and here is why. Blink stores the public and private keys separately for security reasons. While the public key is stored on a normal file, the private key is stored on the iOS keychain for the device. Theoretically, that is actually a lot safer, because it avoids backups, it can only be reached from the device, etc... In the future I would like to add other systems to copy this secure information.

I will divide this into two other small stories to create a default id_rsa key, and also to improve the information on the help message.

**Comment by joeshaw** [comment]
Thanks for the information, and I appreciate that the private keys are stored in the keychain.

A couple of thoughts I had about key management:

Would it be possible to still copy from iTunes, but when Blink sees the private key there, import it into the keychain and remove it from the iTunes location?  (I'm ignorant of how the actual copy-from-iTunes mechanism works.)  The window of the keys being visible would hopefully be pretty small in that case.  I can understand if you still didn't want them on the device at all, in case of backups happening.

I like the idea of having a default key generated when you first use Blink.  Could it be made fairly easy to share the public key using the iOS share sheet?  That way I could email or airdrop myself a copy to more easily put it on the hosts I access most often.
