### ISSUE TITLE
Connecting to macOS (locale issue)

### ISSUE THREAD

**Issue by Sjors** [blinksh/blink#790]
I'm using Blink on an iPad with the region set to The Netherlands (nl_NL) to connect to an iMac with the same locale (Mojave 10.14.6).

I needed to follow these [firewall instructions](https://v4.chriskrycho.com/2017/set-up-mosh-on-macos.html) and explicitly set the Command to `/usr/local/bin/mosh-server` (I also had to turn the firewall off to let it connect once and then turn it back on, maybe a reboot would have done the same).

This results in a locale error similar to #438 and #294. I also dumped `locale` via SSH:

<img width="1024" alt="IMG_0034" src="https://user-images.githubusercontent.com/10217/64108022-10065500-cd7c-11e9-9e52-63c79ee0008a.png">

For comparison I also have an Ubuntu server with locale set to en_US. That works like a charm.

I then added (see [Apple stack exchange](https://apple.stackexchange.com/questions/158673/how-to-get-utf-8-locale-when-connecting-via-ssh-to-macosx-from-putty-windows/158675) this to `~/.profile`:

```
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
```

Now I see a UTF8 locale when using regular ssh, but I still get the above error. Changing it to `nl_NL` didn't help. Changing my iPad region to "United States" didn't help either.

Prepending `LC_ALL=en_US.UTF-8` to the Command in the config screen did the trick! In fact, it also works when I switch my iPad region back to Netherlands, use `nl_NL` in the Command and in `.profile` on the iMac.

I suspect more people will want to use Blink to connect to their Mac at home, so maybe some of these steps can make it into the documentation?

**Comment by zestynotions** [comment]
adding the :
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

to my .zshrc file got my mosh working fine from my mac again.
No issues from ipad though.

**Comment by carloscabanero** [comment]
Closing here. The remote must have the proper locale and our mosh client has been also taking care of this for a while.
