### ISSUE TITLE
No Such File or Directory: [...]Debug-iphoneos/curl_ios_static.framework/curl_ios_static

### ISSUE THREAD

**Issue by MayusYT** [blinksh/blink#793]
Hi!
When trying to build blink in XCode using the install Script, I get the following error:
/clang: no such file or directory: '/Users/marius/Library/Developer/Xcode/DerivedData/Blink-bcrnfyfukxsufgfobbaqbfqkjxmp/Build/Products/Debug-iphoneos/curl_ios_static.framework/curl_ios_static'

How could I fix this?
Thanks in advance!

**Comment by yury** [comment]
Hi,

`git submodule init`
`git submodule update`
`./get_frameworks.sh'

**Comment by MayusYT** [comment]
Thanks! I just did that, and still get the same error. I am building for an iPhone 5 that runs iOS 10.3.3

This is the error:
```
/clang:-1: no such file or directory: '/Users/marius/Library/Developer/Xcode/DerivedData/Blink-bcrnfyfukxsufgfobbaqbfqkjxmp/Build/Products/Debug-iphoneos/curl_ios_static.framework/curl_ios_static'
```

**Comment by MayusYT** [comment]
Nevermind. Apparently iPhone 5 just isn't supported. It runs fine on my iPad. Thanks! :)

**Comment by yury** [comment]
Yep, you are right. We support only arm64 and iOS  greater than 11.
