### ISSUE TITLE
Shift as ESC remapping is buggy

### ISSUE THREAD

**Issue by Vincent-Carrier** [blinksh/blink#796]
Using iPad Pro 11” 2018 on iPadOS 13.1 Beta

Weirdly enough, when I turned on the Shift -> ESC option, I found myself unable to type “shift+num” characters i.e.: ˆ!@#$%ˆ&*()-=
Instead they triggered vim commands.
It would be nice if Shift only triggered ESC when pressed. Is this possible on iOS?

**Comment by curtismchale** [comment]
I have Shift as escape turned OFF, and yet sometimes it still triggers the escape key so I can’t type some characters like _ because it escapes instead of using shift. IPadOS 13.2

**Comment by yury** [comment]
Blink v13.1 is released with a fix. Closing issue. Feel free to reopen if needed.
