### ISSUE TITLE
blink stopped working.    Socket error: disconnected

### ISSUE THREAD

**Issue by gregorybclark** [blinksh/blink#797]
Things were working fine now nothing.

Using blink on iPad.

Does not work at all.  

All other clients I have work.

**Comment by jkraemer** [comment]
I also have connection problems recently, but not always. Sometimes ssh works but mosh hangs indefinitely, sometimes both just give this error, or "could not find remote IP" after a while. The remote IP error even happened when I put the IP in the host config.

One thing I saw on the server sometimes is "Did not receive identification string from 112.208.196.125 port 50009". That was when even SSH connection attempts failed. I am quite far away geographically from the server (300ms ping) but my connection is generally stable and mosh / ssh on my laptop always work. Happy to provide more info if necessary. I'll also look into getting access to some geographically closer VPS to see if that makes things better.

Another thing I noted - When I run IPsec (to the same host I'm trying to connect to with mosh or ssh), blink appears to bypass it and connect directly instead. Browsers pick up the VPN though. That does not happen with openVPN where blink also goes through the VPN.

Just tried again and what I see in auth.log on the server is:

```
Sep 10 03:09:40 case sshd[14255]: Accepted publickey for jk from 82.102.28.107 port 50185 ssh2: ED25519 SHA256:r7HqIgd2bUEztPY2bedujFA8wKh9MIzQoJMNdJxGEyw
Sep 10 03:09:40 case sshd[14255]: pam_unix(sshd:session): session opened for user jk by (uid=0)
Sep 10 03:09:40 case systemd-logind[885]: New session 4337 of user jk.
```

In Blink I see:

```
blink> mosh --verbose case
MoshClient:DEBUG:mosh-server new -s -c 256 -l LC_ALL=en_US.UTF-8 -- tmux att
MoshClient:DEBUG:ssh -v -o _printaddress=yes -o compression=no -t case mosh-server new -s -c 256 -l LC_ALL=en_US.UTF-8 -- tmux att
```

And nothing. Also does not respond to Ctrl-C. Closing with Cmd-W closes (or crashes?) Blink completely.

**Comment by jkraemer** [comment]
right now `ssh` and `mosh` commands consistently fail, with only `Did not receive identification string from IP` in `auth.log` on the server. Output of `ssh -vvv` in Blink:

````
blink> ssh -vvv case
ssh_connect: libssh 0.9.0 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
ssh_connect: current state : 1
Connect timeout
````

**Comment by jkraemer** [comment]
Oh well. The old Windows trick of rebooting apparently is relevant for Apple's gadgets now as well :) A reboot of the iPad fixed the above condition and ssh and mosh are back working.

**Comment by imiric** [comment]
Hi, I'm having the same issue since a few days ago. Blink v13.5.9.247, iPadOS 14.2.

Here's what I see with `ssh -vvvvv ...` after about a minute:

```
packet_send2: packet: wrote [type=94, len=16, padding_size=11, comp=4, payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_need_rekey: packet: [data_rekey_needed=0, out_blocks=115, in_blocks=1964
packet_send2: packet: wrote [type=94, len=16, padding_size=11, comp=4, payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_need_rekey: packet: [data_rekey_needed=0, out_blocks=115, in_blocks=1964
packet_send2: packet: wrote [type=94, len=16, padding_size=10, comp=5, payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_packet_need_rekey: packet: [data_rekey_needed=0, out_blocks=115, in_blocks=1964
packet_send2: packet: wrote [type=94, len=16, padding_size=11, comp=4, payload=10]
channel_write_common: channel_write wrote 1 bytes
ssh_socket_exception_callback: Socket exception callback: 1 (0)
ssh_socket_exception_callback: Socket error: disconnected
Socket error: disconnected
```

Sometimes I also see `Socket error: Unknown error: -1`.

I tried restarting the app and rebooting the iPad altogether, but the issue persists.

I haven't done any network or server changes, and my other devices can keep the connection without issues.

Any help is appreciated!

**Comment by wmorgue** [comment]
Message from 2022:

```bash
Interactive Shell error. connError(msg: "Socket error: Socket is not connected“
```

**Comment by GeojoL** [comment]
same problem

**Comment by scottdware** [comment]
> Message from 2022:
> 
> 
> 
> ```bash
> 
> Interactive Shell error. connError(msg: "Socket error: Socket is not connected“
> 
> ```

I am getting the same error when idle for a few seconds. IpadOS 16.1

**Comment by carloscabanero** [comment]
Hey, so this issue should have been closed a while ago, and any "similar" message for the last year is probably not due to the same issue.

The original issue was actually a bug on iOS that got fixed a while ago. We also rewrote the sockets and our whole SSH subsystem from scratch, so error messages (no Unknown Error -1, etc) are more accurate and connections more stable.

"Socket is not connected" means exactly that. The ssh session got disconnected. This can be due to the OS killing the socket (sometimes early if it is just a few seconds) for whatever reason, or the other side if there is any type of KAs.

The recommended way to go about this is 1) Use mosh or 2) use `geo track` command for localization security, and that has the secondary effect of not closing the socket.

If the issue happens on first login, please open a new issue.
