### ISSUE TITLE
SSH keys are sometimes lost if iPad pro is put to sleep during a SSH session

### ISSUE THREAD

**Issue by muammar** [blinksh/blink#798]
I have noticed that sometimes SSH keys are lost when I have a running SSH session and put the iPad pro to sleep. When that happens I have to create a new pair, and send the public key to the remote server. Have anyone else experienced this problem, too?

**Comment by petermbenjamin** [comment]
@muammar - I have not experienced this problem.
What version of Blink do you have?

**Comment by muammar** [comment]
I have version 12.10. It has just happened again. I do not know exactly how to reproduce it yet.

**Comment by petermbenjamin** [comment]
@muammar 
- What is your iPad model?
- What is your iOS version?
- How do you create your ssh keys?
- When you say lost, do you mean the entry disappears from config -> keys?

**Comment by muammar** [comment]
> @muammar
> 
> * What is your iPad model?

iPad Pro 11", 2018. 

> * What is your iOS version?

iPadOS 13.1

> * How do you create your ssh keys?

```
config
```

Then: Settings > Keys > +

After creating the key, I add it to the `host`. Then I copy the public key in the server. 

> * When you say lost, do you mean the entry disappears from config -> keys?

When I say lost it means that it is not anymore in the "Keys" settings.

**Comment by benshack** [comment]
I've also had this issue. Working in an SSH connection for a bit. Stop, sleep the iPad. Come back and my terminal settings are all missing / wiped, `id_rsa` has been changed (old one deleted, new one created?). Hosts are missing.

I have to re-select my theme, font, enter my host, send `id_rsa.pub` back up to my servers `authorized_hosts`. Basically it appears the software resets itself.

I'm on an iPad Pro 11" 2018 w/ iPad OS 13.1.2

**Comment by yury** [comment]
@benshack what version of blink are you using?

**Comment by muammar** [comment]
> I've also had this issue. Working in an SSH connection for a bit. Stop, sleep the iPad. Come back and my terminal settings are all missing / wiped, `id_rsa` has been changed (old one deleted, new one created?). Hosts are missing.
> 
> I have to re-select my theme, font, enter my host, send `id_rsa.pub` back up to my servers `authorized_hosts`. Basically it appears the software resets itself.
> 
> I'm on an iPad Pro 11" 2018 w/ iPad OS 13.1.2

That is exactly what was happening to me. It has not happened again though.

**Comment by benshack** [comment]
> @benshack what version of blink are you using?

12.10

**Comment by benshack** [comment]
Just happened again. The app seems to just reset, but if cloud sync is enabled it will reimport the hosts.

**Comment by yury** [comment]
@benshack can I invite you to TestFlight? I want to be sure that we don't have that issue in v13.

**Comment by benshack** [comment]
> @benshack can I invite you to TestFlight? I want to be sure that we don't have that issue in v13.

Of course.

**Comment by carloscabanero** [comment]
Fixed a while ago. It was an issue with iOS starting the app in the background and messing up file configurations when not available.
