### ISSUE TITLE
how to transfer ssh private and public key to ipad running blink

### ISSUE THREAD

**Issue by dimthe** [blinksh/blink#799]
as the title says , i want to use my private and public keys  in blink 
is there a way to do so without having to create new keys from within the blink app ? thanks

**Comment by dimthe** [comment]
Is there anyone who can help with this issue?

**Comment by yury** [comment]
Oh, sorry, missed issue.

Import private key via clipboard. 
`config` -> `Keys` -> `+` -> `Import from clipboard`.
