### ISSUE TITLE
Support for function keys

### ISSUE THREAD

**Issue by rekendahl** [blinksh/blink#8]
On the Apple Pro keyboard there are no function keys. There needs to be a way to send F1-F12 (at least) keys. 

I can imagine two ways: 

1. Some keyboard shortcut (cmd+f) to bring a prompt doc for f number
2. Use the custom keyboard bar.

**Comment by binaryben** [comment]
Some BT keyboards also don't have ESC keys for example (like mine). It will be important to support custom keys of all kinds most likely.

**Comment by carloscabanero** [comment]
With the ESC keys we have you covered, you will be able to reassign it to Caps, etc... 

Already planning how to do this, the keyboard bar will be configurable, so no problem with having it there. But with an external keyboard I think your proposal is perfect, maybe something like Cmd-Shift-f plus the number, showing a small popover at the bottom 

![image](https://cloud.githubusercontent.com/assets/536729/15745703/3d5ddf9c-28a1-11e6-9ff9-134dd963e2b8.jpeg)

to show you what you are doing?

**Comment by arronmabrey** [comment]
@carloscabanero that's very awesome to hear about the Caps-lock remapping!

**Comment by carloscabanero** [comment]
There is a good possibility of doing this before release. I'm considering just having a set of "special function keys" that could be reassigned in the configuration. Same with Page Up/Page Down. And in this way we would not require any special prompt, it would just be part of Blink configuration.

**Comment by carloscabanero** [comment]
This was done on last version :)
