### ISSUE TITLE
Focus is not automatic when switching back into Blink from another app

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#800]
In previous versions of iOS, when you switched away from Blink to another app and then back into Blink, the cursor was automatically focused where you left it (solid block in my case).

In iPadOS 13.1, when I switch back to Blink from another app, the focus is lost (outline of block in my case), and I have to tap the screen to get the focus back.

Is there a way to restore the old behavior?

Blink 13.0(132) via TestFlight.

**Comment by sbromberger** [comment]
Update: it seems to be somewhat application-dependent. When I switch to Slack and type in the box, then go back to Blink, the focus is lost. When I switch to Notes and type in a note, the focus is preserved, but there is frequently weird behavior (auto-repeating a character I typed in the note inside the shell, for example, or acting as if the command key is pressed when it isn't).

**Comment by petermbenjamin** [comment]
Hi @sbromberger - I am not able to replicate this.

My steps:
1. Open Blink
1. In Blink prompt: `echo hi`. Works as expected.
1. Switch to slack, type and send a message to myself
1. Switch back to Blink. Cursor is already focused and I can start typing right away.

**Comment by yury** [comment]
@petermbenjamin it is Blink v 13.0 issue. We relax autofocus a little bit to make more friendly for multiple windows. I will look on this.
