### ISSUE TITLE
Buggy External Display Support

### ISSUE THREAD

**Issue by pbnj** [blinksh/blink#806]
Blink: v13.0.139. Sep 27 2019 

I found 2 issues with external display support.

Issue 1: I can switch focus from iPad display to external display, but I cannot switch focus back to iPad display.

Repro Steps:
1. Connect to external display & launch Blink
1. Blink will be focused on iPad display at launch. Press `command` + `o` to focus external display.
1. Now, try to switch focus back to iPad display by pressing `command` + `o` again. Nothing happens. Cannot type anymore. But some Blink keyboard shortcuts work, like `command` + `w` to close shell, but it closes shell on iPad display not on currently focused display.

Issue 2: Moving shell to other screen does not work.

Repro Steps:
1. Focus iPad display and type any command, like `echo hi`
1. Press `command` + `shift` + `o`, nothing happens.

**Comment by yury** [comment]
cmd+shift+o not working right now.

for cmd+o issue please check build 140.

**Comment by curtismchale** [comment]
I’m seeing the same issue as of today with iPadOS 13.2

**Comment by carloscabanero** [comment]
This was all fixed.
