### ISSUE TITLE
Config > keys > Import from clipboard is not working

### ISSUE THREAD

**Issue by pjfsantiago** [blinksh/blink#807]
Hi Team,

I exported my AWS keys to RSA 2048 in clear text and copied the content to Blink > import from clipboard, and it fails with the message: Invalid key.

Even when copying the key from id_rsa to clipboard and then importing it fails with the same message.

**Comment by yury** [comment]
Hi @pjfsantiago 
What version of blink do you use?

On App Store version. Keys should have `\n` at the end file.

**Comment by pjfsantiago** [comment]
Hi Team,
My keys have the have line feed at the end.
I’m using IPadOs13.1.1
I added an extra blank line to the end of a file, then copy the text by
selecting it after opening the file and including the extra line feed, but
I get the same error.

**Comment by jonmacchio** [comment]
I'm currently experiencing the same issue running iOS 13.3.1 beta and Blink version 13.2.1 from the App Store.

**Comment by yury** [comment]
Should be fixed in Blink 15. Sorry for late response.
