### ISSUE TITLE
Two-finger swipe up broken on iOS 13

### ISSUE THREAD

**Issue by pyrmont** [blinksh/blink#808]
I use the two-finger swipe up gesture to paste things into Blink. I'm not having any success invoking this gesture on iOS 13. I couldn't see any reports of this.

I'm on an iPhone XS Max running iOS 13.1.

(I realise there are alternatives but this is the most convenient for me and it doesn't appear as if the gesture has been replaced with anything.)

**Comment by carloscabanero** [comment]
The new iOS has three finger tap showing a control panel. So we are using that for control ourselves too. You need to be on TestFlight version. Try it out! :)

**Comment by pyrmont** [comment]
@carloscabanero Is there a reason to switch to a three-finger tap? I've been using Blink on my phone for more than two years to do software development on the go and the two-finger swipe can be accomplished with two thumbs (meaning that it can be invoked while typing with your thumbs on the onscreen keyboard).

A three-finger tap can't be performed while holding the phone to type on the keyboard requiring the user to shift their grip. This is an ergonomic regression.

**Comment by carloscabanero** [comment]
That’s a good question and you raise a good flag. We made the decision for two reasons:
- Two finger scroll will now be used to do mouse scroll in the remote terminal. This is incredibly useful for editors and it works like a charm. I promise it takes things to the next level.
- Apple was investing in the three finger gestures and we found the hard way that going against them is usually a bad idea. A lot of people had problems discovering the two finger gesture and we hope the three finger one can actually become a more important part of the interface in the future too.

**Comment by pyrmont** [comment]
@carloscabanero I didn't find an issue raised about the change so I guess I'm in the minority. To that end, while I can appreciate it makes sense from a discoverability point of view for two-finger swipes to scroll the view, I'd really love it if this could be made a preference. I code in Vim and won't find scrolling to be much benefit. I would greatly prefer the previous behaviour.

Alternatively, what I really want is a way to be able to paste content from the iOS clipboard into Blink. Is there a keyboard shortcut that works with the onscreen keyboard to do this? That'd fix my issue.

**Comment by carloscabanero** [comment]
The new keyboard has a Cmd to the right, and then you can do cmd+v from there too!

**Comment by pyrmont** [comment]
That sounds cool! Is there a way to join the TestFlight group? I checked the project README and didn't see a link.

**Comment by carloscabanero** [comment]
Yep, send us a dm with your email on twitter or email me on cc at blink.sh
