### ISSUE TITLE
mosh disconnecting frequently

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#809]
version 13.0 (145) on iPadOS 13.1.2. No changes to mosh-server.

Ever since 13.0 (iPadOS 13), my mosh sessions, which used to persist for weeks, are terminated on the client end (mosh-server is still running, forcing me to ssh into the server and kill it before I use mosh again). It seems (though I can't confirm) that the blink process is ending during inactivity. This wasn't the case in previous versions.

**Comment by yury** [comment]
Yep, we noticed that too. This issue is main target for today.

**Comment by sbromberger** [comment]
You guys are so on top of things. Thank you very much for the quick turnaround on these issues.

**Comment by sbromberger** [comment]
It may be too early to claim success, but I haven't had a timeout since I updated to 13.0(147).

Just a small feature request: having the version at the top of the "config/about" page would be nice :)

**Comment by yury** [comment]
I think I nailed it :) testing...

**Comment by sdotz** [comment]
Glad to see a fix is in the works. Just chiming in that I have noticed this too.

**Comment by yury** [comment]
pushed Blink 13 build 152 with fix.

**Comment by yury** [comment]
Blink 13 is out!
