### ISSUE TITLE
When connecting with external monitor, no way to use that screen

### ISSUE THREAD

**Issue by wmwragg** [blinksh/blink#810]
On an iPhone 8 max (iOS 13.1.2) when connecting an external screen, a separates blink session is started on it. If an external keyboard is also connected, using command+O to switch to the external display seems to work, but doesn’t appear active, no text appears when typing. Also if no external keyboard is connected there seems no way to switch to the external monitor.

**Comment by yury** [comment]
What version of Blink do you have?

in Blink v13 you can press cmd+o on software kb too.

**Comment by wmwragg** [comment]
I’m on the latest iOS version 12.10, and there is no cmd key on the iPhone’s soft keyboard. But even when I use cmd+O on a connected keyboard, it appears to switch, but nothing happens when I type.

**Comment by yury** [comment]
iOS 13 breaks a lot for external monitors. We are cooking blink v13 for iOS 13 :)

**Comment by wmwragg** [comment]
Awesome, much appreciated

**Comment by drewwells** [comment]
any updates on this?

**Comment by wmwragg** [comment]
Latest version of blink fixes the issues I had
