### ISSUE TITLE
TF version on iPhone Xs can not use the full-screen of the external display

### ISSUE THREAD

**Issue by njuaplusplus** [blinksh/blink#811]
I am using the latest TF version on my iPhone Xs which runs ios 13.1. When I connected my iphone to the external display, only part of the display was used. The app-store version works greatly with ios 12 on my iphone 6s.

**Comment by yury** [comment]
Can you post a photo?

**Comment by njuaplusplus** [comment]
Here is the photo.

![image](https://user-images.githubusercontent.com/4112055/66214955-a043fc80-e690-11e9-9645-daabf9112581.png)

**Comment by yury** [comment]
Oh, that one.
What option do you have at 'config' -> 'Appearance' -> `External Display` ?

**Comment by njuaplusplus** [comment]
It's "scale".

**Comment by yury** [comment]
hmm. scale should work. Try to set it to none and reconnect monitor.

I will look. Thanks.

**Comment by njuaplusplus** [comment]
It didn't work. If I chose none, the window size is same, but the command prompt "blink>" became indented.

**Comment by yury** [comment]
Hi @njuaplusplus,

if you open photos app. Do you have insets with photo preview?

**Comment by njuaplusplus** [comment]
Sorry, I just saw your message. What do you mean by insets with photo preview?
Do you mean the photo app on external display?

**Comment by njuaplusplus** [comment]
Hi @yury, I checked the latest TF version, it uses full-size on the external display. Thanks a lot!!
Btw, I still couldn't map the caps to ctrl during the normal command line input outside vim. I really need this feature since I use tmux.

**Comment by andrius** [comment]
it is not bug related but @njuaplusplus could you share your experience, as far I understand you are trying to work only with iphone + keyboard + connected screen, correct? What cables and adapters do you use?

**Comment by njuaplusplus** [comment]
I am using Apple lightning to hdmi adapter and hdmi to hdmi cable.
