### ISSUE TITLE
Cannot enter PIN via external keyboard

### ISSUE THREAD

**Issue by ChaiTRex** [blinksh/blink#814]
PIN code cannot be entered via external keyboard

0. Return to Blink app after several minutes
0. At Touch ID screen, press Enter on external keyboard to cancel the fingerprint verification
0. Attempt to type in PIN code via external keyboard
0. Note that numeric keypresses do nothing, so PIN code cannot be entered via external keyboard

**Comment by yury** [comment]
In blink 13.2 we removed custom pin solution in favor of LocalAuthentication.framework.

You will be able to get access with FaceID/TouchID or enter pin code of device (which support kb input)

**Comment by yury** [comment]
Closing this issue. Feel free to reopen if needed.
