### ISSUE TITLE
Keep window size constant when keyboard bar is temporarily hidden

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#815]
When I have the Smart Keyboard connected so that the bottom strip of my shell window is taken up by the bar, if I take certain actions—like summoning Settings, switching shells, or switching to another app and back to Blink, the bar goes away, and then comes back when I can once again resume typing. At the font size I’m using, that means my usable screen geometry goes from a height of 54 lines to 58 lines and then back to 54 lines.

This isn’t a big deal at all in and of itself. But:
1. The screen flashing can be a little distracting and eye-straining.
2. Some full-screen visual programs in Unix do a lot of refreshing work when the window is resized, and so doing it twice unnecessarily is suboptimal. I have an omnipresent CPU indicator on the bottom status line in Tmux, and my CPU usage jumps substantially (though briefly) when this resizing happens.
1. I’ve even known some Unix fullscreen programs to crash if their window geometry changes back before it’s completed refreshing to the prior geometry (as can happen when the keyboard bar blips away for a moment and then returns).

**Comment by yury** [comment]
3f lock can solve resize for you?

**Comment by treyharris** [comment]
@yury Indeed! I saw the bar go away and come back and wrongly assumed it would be like changing font size, where even in lock the screen geometry changes. Thanks.
