### ISSUE TITLE
F11 and F12 keys not working on external keyboard

### ISSUE THREAD

**Issue by ChaiTRex** [blinksh/blink#816]
I have a Bluetooth keyboard with physical F-keys (Logitech K380) that are activated while holding the Fn key.

Pressing Fn+F1 through Fn+F12 within Mosh completely fails to send F1 through F12. Pressing Blink's workaround of ⌘+1 through ⌘+0 works to send F1 through F10, but ⌘+- and ⌘+= fail to send F11 and F12, as they're set to resize the font.

Please accept hardware F-keys from external keyboards that have them and please add a way to type F11 and F12 on external keyboards without F-keys.

**Comment by yury** [comment]
I have Logitech K480. And there is no single signal from iOS when pressing fn+F1-fn+F12. 

I think it is limitation of iOS. Please report issue to Apple. More reports they get higher chance they will fix it.

**Comment by ChaiTRex** [comment]
I've reported it to Apple via https://apple.com/feedback. Can it please be added in the meantime as a key combination like ⌘+Shift+1 for F11 and ⌘+Shift+2 for F12 or something like that? That would also allow it to work for external keyboards that don't have F-keys.

**Comment by yury** [comment]
Update - new webview based kb processor see that buttons. Will be fixed in next release.

**Comment by yury** [comment]
Blink v13.1 is out.

**Comment by videoMonkey** [comment]
I can’t find how to send shift+f1 to my terminal, f1-f10 is no problem. I use ctrl+1, but shift+ctrl+1 does not send shift+f1, any insights? Is this even possible?
