### ISSUE TITLE
ESC key on smart keys doesn’t work

### ISSUE THREAD

**Issue by sylvoie** [blinksh/blink#818]
Hello,

I don’t know if I’m the only one, when I edit text with VI, the escape on smart keys doesn’t work the first time. I need to press more times the ESC and move whit arrows to see disappearing « Insert » mode.

I use Shelly, and the ESC with the same server works fine. It seems that the problem is on ssh-client.

I need help!

Thank’s

Sylvain

**Comment by Avery-Whitaker** [comment]
Also having this issue

**Comment by sylvoie** [comment]
Thank you very much!!! New version of Blink correct that issue for me.

Very happy!
