### ISSUE TITLE
iPadOS and blink not compatible/stable?

### ISSUE THREAD

**Issue by fabien7337** [blinksh/blink#819]
Hey,
I have a lot of issue with iPadOS and Blink:
- suddenly crash
- losing session even with mosh
- keyboard not responsive (and working again after kill/open blink)

It not stable and very hard to work in these conditions :(

Is anyone having these kinds of problem?
Thanks!

—
Configuration:

IPad Pro 11’
iPadOS 13.1.2
Blink version ?
Tmux 2.8

**Comment by andrius** [comment]
I stop using mosh because of clipboard support. Waiting it a lot. Also colors in vim...

However with everything else it works like a charm. I use debian 9.x and 10.x with linuxbrew, nvim (in past vim) and tmux. Here is my initial configs: https://github.com/andrius/.dotfiles

I spent like 6-7 hours daily on blink.

Each the morning I just type `geo track` and then `ssh devserver t` (`t` is to attach or create tmux)

**Comment by zywx** [comment]
Thanks for the feedback!

What’s the point of using geo?

**Comment by andrius** [comment]
`geo track` as a side effect bypassing ios restrictions regarding background apps, so you can switch from blink to browser or some app for longer time and expect that ssh session won't disconnect. Either with mosh sessions it is good to have

Regarding colors, blink + mosh won't display all the colors, for example vim termguicolors won't work, see enclosed screenshots for ssh and mosh.

And finally regarding clipboard, it is possible to integrate vim/nvim ↔ tmux ↔ ipad clipboard with ssh by reusing magic codes (there is few references in various issues with blinksh, just broswe them). In ssh mode, clipboard is seamless, whatever I copy on tmux, I'll get **properly** formatted on ipad and vice-versa (I don't have to use ios/ipados copy mode)

![D502EBA7-A42D-4858-B62B-E75775C7A7FE](https://user-images.githubusercontent.com/26776/66549159-fd352c00-eb42-11e9-909c-e0b0056c87ea.jpeg)
![A286AFEA-05EA-466A-8A82-CC223D139191](https://user-images.githubusercontent.com/26776/66549160-fd352c00-eb42-11e9-99f7-d1dd6b126a5b.jpeg)

**Comment by yury** [comment]
@andrius if you install mosh server from the master. It will display colors correctly. Also latest mosh supports clipboard too. (in theory. I should test that and write tutorial how to setup it)

**Comment by andrius** [comment]
@yury mosh server are latest, it is installed by `linuxbrew`

```bash
~ ak@ak 7m 56s
❯ which mosh
/home/linuxbrew/.linuxbrew/bin/mosh

~ ak@ak
❯ which mosh-server 
/home/linuxbrew/.linuxbrew/bin/mosh-server

~ ak@ak
❯ dpkg -l |grep mosh

~ ak@ak
❯ mosh -v
mosh 1.3.2 [build mosh 1.3.2]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.```

**Comment by yury** [comment]
Yep, it should be not just latest. It should be build from head of master.
See #609

**Comment by andrius** [comment]
@yury it works (colors)! Who do use linuxbrew, do: `brew uninstall mosh && brew install --HEAD mosh`, maybe also will have to symlink mosh binaries.

Clipboard still won't :( We need wiki!

**Comment by bs** [comment]
Just poking my head in to say that latest mosh in Homebrew is still not compatible with ```termguicolors```.

Installing with ```—HEAD``` is working great. Would you accept a pull request with a bit of info  on how to setup mosh in the readme?

**Comment by andrius** [comment]
To confirm, everything currently works (colors and clipboard) with mosh-HEAD, I use mac and debian/ubuntu VPS with brew/linuxbrew

**Comment by carloscabanero** [comment]
Closing here as the issues reported are definitely not replicable. Please reopen if you are still having them.
