### ISSUE TITLE
Bezel sticking around when closing tab

### ISSUE THREAD

**Issue by Riprock** [blinksh/blink#82]
The bezel showing the current tab isn't disappearing after I close a tab. I don't remember this happening before the last update.
![image](https://cloud.githubusercontent.com/assets/148789/17714388/811a7ff6-63f7-11e6-85f2-b2079ef751f4.png)

**Comment by Riprock** [comment]
Making a new tab got rid of it. When I closed the new tab it was working again. No repro so far.

**Comment by carloscabanero** [comment]
Seems like a race condition in the timer for the popup, that the cancel and
show trigger at the same time. Difficult to reproduce but it is there. Will
see how to fix this one.

**Comment by carloscabanero** [comment]
Fixed on release version :)
