### ISSUE TITLE
No discoverable way to fix known_hosts key changes

### ISSUE THREAD

**Issue by ejheil** [blinksh/blink#820]
~~~
blink> ssh 10.0.0.132
Host key for server changed.
RSA key fingerprint is SHA256:U3v+56Bdk/vi3c/IdAuhYayyc/a6fgIR1PquInT7YH4.
For security reason, connection will be stopped
blink> 
~~~

Yeah I know, I reinstalled linux on that raspberry pi, now what do I do?  Ideally there'd be some kind of discoverable UI to deal with this, but if I could figure out how to change it on the command line that'd be fine.  There's no interactive editor for text files.

I tried some funny stuff like this:

~~~
awk '!/10.0.0.132/ { print }' known_hosts > known_hosts2
~~~

But that crashes the app.

**Comment by yury** [comment]
Yep, that crash fixed in v13.

You can use inline `sed`:
```sh
cd ~/.ssh
cat -n known_hosts
# remember line
sed -i.bak '5d' known_hosts
# where 5 is number of line you want to delete
```

**Comment by ogermer** [comment]
Hey @yury - would be nice to have a basic editor on board (besides ed...)

**Comment by yury** [comment]
@ogermer work in progress

**Comment by rcarmo** [comment]
It would be great if removing a host from the GUI list cleaned out their keys.

**Comment by yury** [comment]
@rcarmo we are working on full featured editor. Would be enough for you?

**Comment by rcarmo** [comment]
It would beat the sed hack :)

**Comment by jimmybrancaccio** [comment]
Definitely can't wait to see said editor. At least we have `sed` for now!

**Comment by thoschworks** [comment]
It would also be a nice fix, if the embeded `ssh-keygen` would support the option`-R <hostnamen>`.

**Comment by idcrook** [comment]
In `v13.5.8.245` the following works to remove a cached host signature from `known_hosts`

```shell
ssh-keygen -f .ssh/known_hosts -R 192.168.1.23
```

However, in the spirit of this issue, and my trying to find a working incantation (and then remembering it) for `ssh-keygen`, 
I think it would be handy in *config* -> Settings -> `Hosts` if there were a way to **clear matching any host keys in the GUI** for a given host

**Comment by patricegautier** [comment]
Neat ssh-keygen trick.  You don't even need to specify the known hosts file explicitely

**Comment by carloscabanero** [comment]
Closing as this one has been hanging as completed for a while. We offer many alternatives now:
- SSH prompts to re-write the new key directly.
- ssh-keygen.
- editing the known_hosts file.
