### ISSUE TITLE
ios 13 - unable to use two finger swipe gestures

### ISSUE THREAD

**Issue by nljackson** [blinksh/blink#823]
Blink: v12.10.109
iOS: 13.1.2

After updating to iOS 13 I am unable to use the two finger swipe gestures. Two finger tap for new windows works, as does one finger swipe left/right.

**Comment by aivanise** [comment]
I can confirm this. 7 days and no reaction whatsoever? Cant be that noone runs it under ios 13?

**Comment by gitcory** [comment]
Same.

**Comment by yury** [comment]
We are cooking blink 13. Hope release this week. With ton of fixes. 

We replaced our 2f up swipe with 3f tap to match iOS gestures. 

This gives us freedom to implement mouse scroll in terminal with two fingers.

**Comment by dirkhusemann** [comment]
Oh, cool!

**Comment by sukima** [comment]
![Anxiously Waiting](https://media.giphy.com/media/bQCWmEgKHasZG/giphy.gif)

**Comment by yury** [comment]
Closing. Feel free to reopen if needed.
