### ISSUE TITLE
Add a builtin text-editor

### ISSUE THREAD

**Issue by grayfall** [blinksh/blink#824]
I am not asking for something on the scale of `vi`/`vim`, but even something as simple as `nano` will be extremely helpful. For example, I've just purchased `blink` and tried to create and edit a local `.ssh/config` in blink itself (i.e. without downloading/importing it from somewhere), but I can't figure out any way of doing that.

**Comment by grayfall** [comment]
Just to clarify, the `cat > file` workaround is not only inconvenient, but also broken in the App Store version of the app

https://github.com/blinksh/blink/issues/756
https://github.com/blinksh/blink/issues/769

**Comment by yury** [comment]
We will add `ed` in blink 13. See [demo](https://youtu.be/0lkLCyzPKnQ)

**Comment by mrmen** [comment]
I know ed is an editor but it’s an hardcore one. Anyway to have something more standard ?

**Comment by normen** [comment]
Please go full hardcode and add VIM ❤️

**Comment by psaintemarie** [comment]
Any plans on adding something more user friendly? Even vi would work, but nano/pico could be alternatives.

**Comment by ck3mp3r** [comment]
Nano, pico, vi, anything but ed ;)

**Comment by ogermer** [comment]
Hi Yury -- ed is at least a starting point, but not the most easy. nano, vim, even emacs would be cool(er). Thx!

**Comment by yury** [comment]
Yep, we are working on powerful builtin editor

**Comment by kkk669** [comment]
I think [a-Shell](https://github.com/holzschu/a-shell)'s [vim support](https://github.com/holzschu/vim) may help you because both Blink Shell and a-Shell are using ios_system.

**Comment by kantgreven** [comment]
What about something like [Micro](https://micro-editor.github.io)? Wouldn't that be possible to port to be included with blink?

**Comment by carloscabanero** [comment]
This is ready for Blink 14 but we cannot give details yet 😊

**Comment by erikbgithub** [comment]
@carloscabanero @yury What‘s the current status?

**Comment by yury** [comment]
Current status is on pause, sorry.
We are working on stabilizing and bug fix new release. After release I will continue on editor.

**Comment by yury** [comment]
https://twitter.com/BlinkShell/status/1464618348960956425

**Comment by heywoodlh** [comment]
@yury Can I ask when the VSCode integration will actually be available to the stable release of Blink in the app store?

**Comment by yury** [comment]
Yes. In blink 15. 
we are trying hard to release it this month.
