### ISSUE TITLE
Multi-window mode in iPadOS 13

### ISSUE THREAD

**Issue by grayfall** [blinksh/blink#825]
iPadOS has introduced support for multi-window apps. Are you going to implement the feature in the foreseeable future?

**Comment by yury** [comment]
Yep, we are beta testing Blink 13. We can send you  invite, if you are interested.

**Comment by grayfall** [comment]
@yury yes, that would be lovely.

**Comment by grayfall** [comment]
@yury How can I get access to the demo?

**Comment by yury** [comment]
Send me your apple id at yury.korolev@gmail.com

**Comment by yury** [comment]
Blink 13 is out!
