### ISSUE TITLE
Blink hangs when doing cd ~/.ssh on the blink shell

### ISSUE THREAD

**Issue by sebastianw** [blinksh/blink#831]
When trying to change to the .ssh directory, mosh hangs.

`cd ~/.ssh` is all that is necessary to trigger this.

Device: iPad Pro with iOS 13, newest blink from the App Store.f

**Comment by yury** [comment]
Not a case for me ;(

Can you provide more details? (mosh version, os, shell)

**Comment by sebastianw** [comment]
Uh I had a brainfart, it‘s not a problem with mosh, its a problem with Blink. When I do cd ~/.ssh *blink* hangs directly. I‘m not sshing anywhere, just doing the cd ~/.ssh on the blink shell.

**Comment by sebastianw** [comment]
Okay and I just tried it again and now it works. No idea what changed from yesterday. :(
