### ISSUE TITLE
Configure doesn’t support § key for Esc on UK iPad pro

### ISSUE THREAD

**Issue by onlymee** [blinksh/blink#836]
UK Keyboard layout doesn’t have the ` key in the top left, it has § (±) instead, and the feature to simulate the Esc key would be very useful if it supported using the top left key on the UK keyboard layout too.

**Comment by andrius** [comment]
I agree, also backtick key (`) is important in some cases, i.e. editing markdown, i.e. in my case I can't use it as an ESC. Caps Lock work better, except cases when I have to switch to the browser or enter email

**Comment by botanicus** [comment]
@onlymee just a quick tip that's not addressing the issue, but perhaps will help: I've been using iPad Pro with the Smart Keyboard as my main working tool for the past year and half, and as much as I was shocked in the beginning (as in _"bloody hell, how do I get from the insert mode in Vim"_), I found out I have no need for Esc at all:

- Vim: use `Ctrl-c` instead of Escape. It's actually more practical, no need to reach that far to find Esc.
- Shell: use `Ctrl-[`, for instance `Ctrl-[ .` to copy the last argument of the last command.

Maybe you're aware of it already, but just in case you're not. Hope it helps.

**Comment by yury** [comment]
@botanicus, `cmd+.` System wise esc on iOS

**Comment by yury** [comment]
@celso @onlymee 

Can you log first 3 letters at the top of your kbs with https://jsfiddle.net/yuryk/1vdmk8ws/embedded/result/

simple first 3, then with holding shift and then with holding alt.

For example, on my kb https://gist.github.com/yury/19c4f5b02afb86a8307130daa8529f26

**Comment by kylef** [comment]
With the UK Apple Smart Key, § is key on top left (± with shift):

```
typed text:

    §

| n |    type |         code | key       | kc | mods | repeat | loc | comp | data |
|--:|--------:|-------------:|:----------|---:|-----:|-------:|----:|-----:|-----:|
| 1 | keydown | Unidentified | §         |  0 |      |        |   0 |      |      |
| 2 |   keyup | Unidentified | §         |  0 |      |        |   0 |      |      |
```

**Comment by andrius** [comment]
typed text: §12, then with Shift, then with Option. 
Keyboard type: Smart keyboard for ipad pro 11, English International

    §12±!@§¡™

|  n |        type |         code | key   | kc | mods | repeat | l | comp |      iType | data |
|---:|------------:|-------------:|:------|---:|-----:|-------:|--:|-----:|-----------:|-----:|
|  1 |     keydown | Unidentified | §     |  0 |      |        | 0 |      |            |      |
|  2 |   textInput |              |       |    |      |        |   |      |            |    § |
|  3 | beforeinput |              |       |    |      |        |   |      | insertText |    § |
|  4 |       input |              |       |    |      |        |   |      | insertText |    § |
|  5 |       keyup | Unidentified | §     |  0 |      |        | 0 |      |            |      |
|  6 |     keydown |       Digit1 | 1     | 49 |      |        | 0 |      |            |      |
|  7 |   textInput |              |       |    |      |        |   |      |            |    1 |
|  8 | beforeinput |              |       |    |      |        |   |      | insertText |    1 |
|  9 |       input |              |       |    |      |        |   |      | insertText |    1 |
| 10 |       keyup |       Digit1 | 1     | 49 |      |        | 0 |      |            |      |
| 11 |     keydown |       Digit2 | 2     | 50 |      |        | 0 |      |            |      |
| 12 |   textInput |              |       |    |      |        |   |      |            |    2 |
| 13 | beforeinput |              |       |    |      |        |   |      | insertText |    2 |
| 14 |       input |              |       |    |      |        |   |      | insertText |    2 |
| 15 |       keyup |       Digit2 | 2     | 50 |      |        | 0 |      |            |      |
| 16 |     keydown |   ShiftRight | Shift | 16 |    S |        | 2 |      |            |      |
| 17 |     keydown | Unidentified | ±     |  0 |    S |        | 0 |      |            |      |
| 18 |   textInput |              |       |    |      |        |   |      |            |    ± |
| 19 | beforeinput |              |       |    |      |        |   |      | insertText |    ± |
| 20 |       input |              |       |    |      |        |   |      | insertText |    ± |
| 21 |       keyup | Unidentified | ±     |  0 |    S |        | 0 |      |            |      |
| 22 |     keydown |       Digit1 | !     | 49 |    S |        | 0 |      |            |      |
| 23 |   textInput |              |       |    |      |        |   |      |            |    ! |
| 24 | beforeinput |              |       |    |      |        |   |      | insertText |    ! |
| 25 |       input |              |       |    |      |        |   |      | insertText |    ! |
| 26 |       keyup |       Digit1 | !     | 49 |    S |        | 0 |      |            |      |
| 27 |     keydown |       Digit2 | @     | 50 |    S |        | 0 |      |            |      |
| 28 |   textInput |              |       |    |      |        |   |      |            |    @ |
| 29 | beforeinput |              |       |    |      |        |   |      | insertText |    @ |
| 30 |       input |              |       |    |      |        |   |      | insertText |    @ |
| 31 |       keyup |       Digit2 | @     | 50 |    S |        | 0 |      |            |      |
| 32 |       keyup |   ShiftRight | Shift | 16 |      |        | 2 |      |            |      |
| 33 |     keydown |      AltLeft | Alt   | 18 |    A |        | 1 |      |            |      |
| 34 |     keydown | Unidentified | §     |  0 |    A |        | 0 |      |            |      |
| 35 |   textInput |              |       |    |      |        |   |      |            |    § |
| 36 | beforeinput |              |       |    |      |        |   |      | insertText |    § |
| 37 |       input |              |       |    |      |        |   |      | insertText |    § |
| 38 |       keyup | Unidentified | §     |  0 |    A |        | 0 |      |            |      |
| 39 |     keydown |       Digit1 | ¡     | 49 |    A |        | 0 |      |            |      |
| 40 |   textInput |              |       |    |      |        |   |      |            |    ¡ |
| 41 | beforeinput |              |       |    |      |        |   |      | insertText |    ¡ |
| 42 |       input |              |       |    |      |        |   |      | insertText |    ¡ |
| 43 |       keyup |       Digit1 | ¡     | 49 |    A |        | 0 |      |            |      |
| 44 |     keydown |       Digit2 | ™     | 50 |    A |        | 0 |      |            |      |
| 45 |   textInput |              |       |    |      |        |   |      |            |    ™ |
| 46 | beforeinput |              |       |    |      |        |   |      | insertText |    ™ |
| 47 |       input |              |       |    |      |        |   |      | insertText |    ™ |
| 48 |       keyup |       Digit2 | ™     | 50 |    A |        | 0 |      |            |      |
| 49 |       keyup |      AltLeft | Alt   | 18 |      |        | 1 |      |            |      |

**Comment by celso** [comment]
Hi @yury, here goes:

Normal:

typed text:

    §12

|  n |        type |         code | key  | kc | mods | repeat | l | comp |      iType | data |
|---:|------------:|-------------:|:-----|---:|-----:|-------:|--:|-----:|-----------:|-----:|
|  1 |     keydown | Unidentified | §    |  0 |      |        | 0 |      |            |      |
|  2 | beforeinput |              |      |    |      |        |   |      | insertText |    § |
|  3 |       input |              |      |    |      |        |   |      | insertText |    § |
|  4 |       keyup | Unidentified | §    |  0 |      |        | 0 |      |            |      |
|  5 |     keydown |       Digit1 | 1    | 49 |      |        | 0 |      |            |      |
|  6 | beforeinput |              |      |    |      |        |   |      | insertText |    1 |
|  7 |       input |              |      |    |      |        |   |      | insertText |    1 |
|  8 |       keyup |       Digit1 | 1    | 49 |      |        | 0 |      |            |      |
|  9 |     keydown |       Digit2 | 2    | 50 |      |        | 0 |      |            |      |
| 10 | beforeinput |              |      |    |      |        |   |      | insertText |    2 |
| 11 |       input |              |      |    |      |        |   |      | insertText |    2 |
| 12 |       keyup |       Digit2 | 2    | 50 |      |        | 0 |      |            |      |
| 13 |       keyup |     MetaLeft | Meta | 91 |      |        | 1 |      |            |      |
| 14 |      change |              |      |    |      |        |   |      |            |      |

With shift:


typed text:

    ±!"

|  n |        type |         code | key   |  kc | mods | repeat | l | comp |      iType | data |
|---:|------------:|-------------:|:------|----:|-----:|-------:|--:|-----:|-----------:|-----:|
|  1 |     keydown |   ShiftRight | Shift |  16 |    S |        | 2 |      |            |      |
|  2 |     keydown | Unidentified | ±     |   0 |    S |        | 0 |      |            |      |
|  3 | beforeinput |              |       |     |      |        |   |      | insertText |    ± |
|  4 |       input |              |       |     |      |        |   |      | insertText |    ± |
|  5 |       keyup | Unidentified | ±     |   0 |    S |        | 0 |      |            |      |
|  6 |     keydown |       Digit1 | !     |  49 |    S |        | 0 |      |            |      |
|  7 | beforeinput |              |       |     |      |        |   |      | insertText |    ! |
|  8 |       input |              |       |     |      |        |   |      | insertText |    ! |
|  9 |       keyup |       Digit1 | !     |  49 |    S |        | 0 |      |            |      |
| 10 |     keydown |       Digit2 | "     | 222 |    S |        | 0 |      |            |      |
| 11 | beforeinput |              |       |     |      |        |   |      | insertText |    " |
| 12 |       input |              |       |     |      |        |   |      | insertText |    " |
| 13 |       keyup |       Digit2 | "     | 222 |    S |        | 0 |      |            |      |
| 14 |       keyup |   ShiftRight | Shift |  16 |      |        | 2 |      |            |      |
| 15 |      change |              |       |     |      |        |   |      |            |      |

With alt (option):


typed text:

    §@

|  n |        type |         code | key   |  kc | mods | repeat | l | comp |      iType | data |
|---:|------------:|-------------:|:------|----:|-----:|-------:|--:|-----:|-----------:|-----:|
|  1 |     keydown |      AltLeft | Alt   |  18 |    A |        | 1 |      |            |      |
|  2 |     keydown | Unidentified | §     |   0 |    A |        | 0 |      |            |      |
|  3 | beforeinput |              |       |     |      |        |   |      | insertText |    § |
|  4 |       input |              |       |     |      |        |   |      | insertText |    § |
|  5 |       keyup | Unidentified | §     |   0 |    A |        | 0 |      |            |      |
|  6 |     keydown |       Digit1 |      |  49 |    A |        | 0 |      |            |      |
|  7 | beforeinput |              |       |     |      |        |   |      | insertText |     |
|  8 |       input |              |       |     |      |        |   |      | insertText |     |
|  9 |       keyup |       Digit1 |      |  49 |    A |        | 0 |      |            |      |
| 10 |     keydown |       Digit2 | @     |  50 |    A |        | 0 |      |            |      |
| 11 | beforeinput |              |       |     |      |        |   |      | insertText |    @ |
| 12 |       input |              |       |     |      |        |   |      | insertText |    @ |
| 13 |       keyup |       Digit2 | @     |  50 |    A |        | 0 |      |            |      |
| 14 |       keyup |      AltLeft | Alt   |  18 |      |        | 1 |      |            |      |
| 15 |      change |              |       |     |      |        |   |      |            |      |

**Comment by yury** [comment]
You can remap `§` with config->keyboard->custom presses in latest blink version.
Closing this issue. Feel free to reopen if needed.

**Comment by onlymee** [comment]
Amazing job. Sorry for missing the ask above.  Works fantastically.
