### ISSUE TITLE
[Feature] Support Toggling "Mirror" vs "Extended" modes for external displays

### ISSUE THREAD

**Issue by pbnj** [blinksh/blink#837]
It would be nice if users can toggle "Mirror" vs "Extended" modes for external displays.

Why?

1. when I have Blink+Safari in split screen, switching from Safari to Blink puts me in the Blink window on the iPad display, so I have to do an extra step to switch to Blink on external monitor.
1. I always focus on 1 display at any given time (multiple displays distract me more than help me be more productive). So, when I'm docked/in the office, the iPad sits on a stand next to the monitor and I focus on the external monitor.

**Comment by yury** [comment]
At first look there is no way to disable/enable that feature at runtime. ... will look more later.

**Comment by tonious** [comment]
Another use case: I tend to bring my iPad to meetings.  Once in a while I have to demo something on an external display, and mirroring would be really nice.  It doesn't even have to be system level iPadOS mirroring, as long as both screens render the same terminal.

**Comment by philips** [comment]
+1 to mirroring. I tried to do a demo and was so confused by the default behavior.

**Comment by gdbenson** [comment]
I love Blink and I'm using to go "iPad Only" in my classes. However, there are times when I just want to mirror the terminal to larger LCD screens for the students to see. For now, I have to use split view to make this work. It would be great to have an option to select mirroring or extended mode for external displays.

**Comment by wilfreddenton** [comment]
Problems I have with "extended" view while using `mosh`:
- It cannot be touched (obviously). If I have a bluetooth mouse connected via the Assistive Touch feature I cannot use the mouse within the external display.
- Command tabbing often results in a glitched out terminal in the external display and I have to close it.
- Disconnecting the external display results in the closing of the terminal that was displayed there.

**Comment by curtismchale** [comment]
I also find that the “extended” view gets disconnected regularly during a work session so I have to connect it again and then login to tmux....the regular iPad screen doesn’t have this issue and will stay logged in for days if I leave it.

**Comment by yury** [comment]
Good news. I found a way to switch it dynamically. Will be an option for that in next release.

**Comment by yury** [comment]
Added `Mirror` option to `config` -> `Appearance` -> `External Display`
