### ISSUE TITLE
PgUp, PgDown missing in on-screen keyboard on iPhone

### ISSUE THREAD

**Issue by zorinlynx** [blinksh/blink#839]
Prior to version 13 you could hit the "option" on-screen key on the left and have access to alternate keys including PgUp and PgDown. This no longer works, and PgUp/PgDown no longer seem to be available at all.

**Comment by yury** [comment]
yep, almost forget. Will fix. Thank you.

**Comment by yury** [comment]
CMD+arrows will do home/end/pageup/pagedown.

**Comment by zorinlynx** [comment]
This seems to be working well now. Thanks!
