### ISSUE TITLE
Caps to Ctrl is not functioning as expected in TF version.

### ISSUE THREAD

**Issue by njuaplusplus** [blinksh/blink#840]
Version: All TF versions
Devices: iPad Pro 13.1.3, iPhone Xs 13.1.3

I could use some vim combinations such as caps+[, caps + v, etc. in vim perfectly.
But I could not use caps as ctrl anywhere else.

In the config, I set both Caps as Ctrl and mapping Caps to Ctrl.

The mappings work very well as expected with the App Store version.

**Comment by Avery-Whitaker** [comment]
I use the app store version
The caps lock to escape remapping has recently stopped working for me.

**Comment by awper361** [comment]
Yes, me too. I am using the app store version.

**Comment by albertmichaelj** [comment]
My caps to ctrl is broken as well in the app store version. Seems to be the most recent update.

**Comment by alexclaydon** [comment]
I’m also having this problem.
