### ISSUE TITLE
Blank screen upon startup

### ISSUE THREAD

**Issue by ttelford** [blinksh/blink#841]
There is a blank screen upon app startup, or switching between applications.

Triple tap works, and I can delete the blank/bad shell and start a new one. But if I leave the app, and come back, I get a blank screen again. Any open mosh sessions are lost, because the terminal is just a blank screen. I have to close the terminal session to get any use of blink.

**Comment by yury** [comment]
ok, pushed build 153 with possible fix.

Thank you.

**Comment by ttelford** [comment]
Unfortunately, the problem persists. Though occasionally, after about five seconds, a blank term will pop up.

**Comment by yury** [comment]
What device are you using? What font? May be custom theme?

**Comment by ttelford** [comment]
iPhone 7 Plus.
Default Theme

**Comment by ttelford** [comment]
The latest build from this morning is much better. I haven’t seen a blank screen yet. I will continue to test a few days before saying it can be closed.

**Comment by ttelford** [comment]
I’m gonna call it good. Thank you!!!
