### ISSUE TITLE
Useless shake to "Undo Typing" modal dialog box

### ISSUE THREAD

**Issue by ChaiTRex** [blinksh/blink#842]
Typing a few characters and then accidentally shaking my iPad brings up an "Undo Typing" modal dialog box:

![0FCDD983-9D91-4B55-AB3E-C6FC7BEBE32B](https://user-images.githubusercontent.com/23159282/67614122-fafae080-f784-11e9-8fd5-9b8b30e16e34.jpeg)

Since this is useless (tapping "Undo" doesn't seem to remove what you've typed under any circumstances), can you please disable this action upon shaking? It gets in my way several times a day when I'm typing on an unstable surface, and it even discards characters I type on a hardware keyboard while the modal dialog is accidentally present.

**Comment by zorinlynx** [comment]
This is an iOS feature, and you can disable it in Settings -> Accessibility -> Touch -> Shake to Undo.

I don't know if you use the feature elsewhere in iOS, but if you don't, you can just flip off that switch and it'll be gone forever. Also with iOS 13 you can three finger swipe to the left to undo, which is far better than shaking in my opinion.

**Comment by yury** [comment]
Fixed. Fix will be in next release. 

Thank you
