### ISSUE TITLE
after update to the TF version, somehow zsh automatically switching to the vim mode

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#845]
I have rolled back version 12 to check is that blink-related or not (as I've recently updated iPadOS and zsh on VPS also get updated). With Blink shell 12 everything works well, while with TF version I must almost constantly press CapsLock (mapped to Esc) to exit zsh vi-mode.

Will try to update ticket, I have few servers and it is possible that issue I get could be eliminated by changing some of zsh settings.

TF versions I've tested were were 153 and 154

**Comment by yury** [comment]
can you post screenshot of your KB settings in blink?
I can't reproduce this...

**Comment by andrius** [comment]
only CapsLock → Esc mapping (restored TF to double check)

![28DCC0B6-EC44-4C81-8B49-D6EEC36CE7B9](https://user-images.githubusercontent.com/26776/67755649-ca42d180-fa38-11e9-9522-72f147137a92.jpeg)

**Comment by andrius** [comment]
After cleanup and reinstall of the zsh, it works. Now I have another issue, cmd-arrows mapping does not work (shift-arrows does)
