### ISSUE TITLE
Cursor keys mapping with Cmd does not working in TF build 154 (all right in 153)

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#846]
In vim or terminal Cmd and arrow-keys were working as an PgUp, PgDown, Home and End keys in v12 and until TF version 153. In 154 it simply does not work

Locale is `en_US.UTF-8` for everything. Tested in bash, zsh, tmux and vim

![F9A1BBFE-E7FE-4314-8345-A7295C6858FA](https://user-images.githubusercontent.com/26776/67783147-1b1eee00-fa6a-11e9-91b7-0b06c1393618.jpeg)

**Comment by yury** [comment]
Hi @andrius, trying to reproduce this.
Can you post output of blink `showkey` command. (with cmd+arrow as cursor keys)

**Comment by andrius** [comment]
```blink> showkey
Press any keys - Ctrl-D will terminate this program.
^[       27 0033 0x1b
O        79 0117 0x4f
H        72 0110 0x48
^[       27 0033 0x1b
O        79 0117 0x4f
F        70 0106 0x46
^[       27 0033 0x1b
[        91 0133 0x5b
5        53 0065 0x35
~       126 0176 0x7e
^[       27 0033 0x1b
[        91 0133 0x5b
6        54 0066 0x36
~       126 0176 0x7e
^D        4 0004 0x04```

**Comment by andrius** [comment]
After I've completely removed blink and restart ipad, and installed it again, issue just gone.
I had similar issues with Microsoft Office in past with licensing and only complete purge + reboot helped... something get cached
