### ISSUE TITLE
Where are the arrow keys for the on-board keyboard?

### ISSUE THREAD

**Issue by entonian** [blinksh/blink#847]
The arrows icon is grayed out in both IOS and iPadOS.

**Comment by bswinnerton** [comment]
Does it work if you place your finger on the arrow icon and swipe in the direction of the arrow you’d like to use?

**Comment by entonian** [comment]
Yes! Thank you.

**Comment by yury** [comment]
There are two reasons to make them that color. 

1. Indicate that you can drag them, like two letter keys. 
2. They are too bulky without opacity

**Comment by entonian** [comment]
Thank you. Good reasons.

I am leaving this open because I don’t know if you two would see my responses otherwise. Is the normal ending response to close and comment, since I am the originator of the issue report? Newby.

**Comment by yury** [comment]
We prefer authors of issues close them.
