### ISSUE TITLE
Esc then a numeral fails only on external keyboard

### ISSUE THREAD

**Issue by ChaiTRex** [blinksh/blink#851]
I'm used to pressing Esc, letting Esc go, and then pressing a numeral in WeeChat (a command line IRC client I use remotely through Blink) to switch to that buffer number.

That key sequence still works on the on-screen keyboard, so there's nothing changed on the remote end. It stopped working with my Logitech K380 external keyboard, though.

Because it worked fine a few days ago, I assume it was the Blink app update I got today.

---

iPadOS 13.2
Blink 13.0

**Comment by ChaiTRex** [comment]
This seems to work now in Blink 13.1.

**Comment by yury** [comment]
Closing. Thanks.
