### ISSUE TITLE
About window doesn't tell Blink version

### ISSUE THREAD

**Issue by ChaiTRex** [blinksh/blink#852]
In another bug report, I wanted to include a Blink version number, but the About window doesn't include that information.

![B9832193-4FA1-4A0A-9575-8F718676558B](https://user-images.githubusercontent.com/23159282/67983188-91eaf100-fbfa-11e9-9e18-4c96084e0061.jpeg)

---

iPadOS 13.2
Blink 13.0

**Comment by yury** [comment]
We print version in help command.
I also added version on `About` row.
![IMG_98712CE5FA99-1](https://user-images.githubusercontent.com/5250/71153335-ebaa8780-2249-11ea-9731-db227270671c.jpeg)
