### ISSUE TITLE
Caps lock as ctrl doesn't work with version 13 on smart keyboard

### ISSUE THREAD

**Issue by ElvishJerricco** [blinksh/blink#853]
It worked on iPadOS previously (albeit kind of unreliably), but not since the update the other day.

**Comment by chrismetcalf** [comment]
THANK GOD! I thought I was going crazy. I’m having the same issue - iPadOS on a Logitech Bluetooth keyboard.

**Comment by ElvishJerricco** [comment]
I've also discovered I can't send ctrl+space, even though I have "Grab Ctrl+Space" disabled. Given that I use this app primarily for Emacs, these two problems make the app 90% unusable for me.

**Comment by chrismetcalf** [comment]
Yeah basically none of my key mappings work anymore. Caps Lock -> Ctrl and Ctrl -> Esc.

Worse, Ctrl is unreliable mapped so sometimes I don’t have a Ctrl key...

**Comment by ElvishJerricco** [comment]
Curiously, "caps lock as ctrl" *does* seem to work for ctrl+/

**Comment by RockyLim92** [comment]
Same here, ```caps lock``` does not work properly since I upgrade to iPad OS 13.2

**Comment by awper361** [comment]
> I've also discovered I can't send ctrl+space regardless of whether or not I have "Grab Ctrl+Space" disabled. Given that I use this app primarily for Emacs over SSH, these two problems make the app 90% unusable for me.

Indeed, with out caps mapping, emacs and tmux need ctrl so often that almost broke my little finger.

**Comment by chrismetcalf** [comment]
Anybody figured out any workarounds that work? I’m trying out Terminus but I really prefer Blink and I don’t like the idea of having to pay a subscription for my SSH client. If it’s a money thing I’d rather kick some money towards Blink than Terminus.

**Comment by cctile** [comment]
#732 covers this issue.

**Comment by mcillkay** [comment]
it would be great if this issue could be prioritized for a fix — i use blink daily with emacs but the broken keybindings are making it extremely painful.
