### ISSUE TITLE
Latest version has broken “caps as CTRL”

### ISSUE THREAD

**Issue by hutchike** [blinksh/blink#855]
Using an Apple Smart Keyboard with iPad Air. Worked fine until I updated. :-(

**Comment by sideshowcoder** [comment]
Linking to #840 and #732 as they seem related.

**Comment by chrismetcalf** [comment]
#853 is the same too!

**Comment by jerryabramson** [comment]
I have somewhat isolated the issue.

The mapping is 'sort of working'.

When you press 'CapsLock-C' it properly sends the 'CTRL-C' [INTR].

Same is true for all key sequences (i.e. CapsLock-F moves forward one character, CapsLock-A moves to beginning of line].

However, pressing the CapsLock key is acting like a toggle key, similar to the designed behavior of CapsLock.

That is, the modifier to 'CTRL' remains active, so pressing 'A' moves to beginning of line, pressing 'C' send CTRL-C [INTR], etc.

If you then press the physical CapsLock key again, it is 'toggled' off, and the 'A' key properly sends the character 'A'.

I think you get the idea.....

**Comment by jerryabramson** [comment]
I have somewhat isolated the issue.

The mapping is 'sort of working'.

When you press 'CapsLock-C' it properly sends the 'CTRL-C' [INTR].

Same is true for all key sequences (i.e. CapsLock-F moves forward one character, CapsLock-A moves to beginning of line].

However, pressing the CapsLock key is acting like a toggle key, similar to the designed behavior of CapsLock.

That is, the modifier to 'CTRL' remains active, so pressing 'A' moves to beginning of line, pressing 'C' send CTRL-C [INTR], etc.

If you then press the physical CapsLock key again, it is 'toggled' off, and the 'A' key properly sends the character 'A'.

I think you get the idea.....

**Comment by jramapuram** [comment]
+1 for this issue; seems like CMD as ESC seems to be working fine: can use CMD + f to forward words (emacs style) everywhere. Not sure why the issue is just affecting CAPS ¯\_(ツ)_/¯

**Comment by OldhamMade** [comment]
Any updates on this? I bought Blink from the AppStore because of this feature. I’m heading on a trip in a couple of weeks and was hoping to just take my iPad and use Blink + DO for development and leave my heavy laptop at home. Caps-as-ctrl is hardwired into my hands, and the keyboard on the iPad is so small that trying to use the Ctrl key is actually kinda painful.

Really hoping we can get a dot release in the next 2 weeks to fix this!

**Comment by yury** [comment]
Integrating... TF should be at the end of the week.

**Comment by OldhamMade** [comment]
@yury wonderful! That’s great to hear.

BTW, further to @jerryabramson‘s comment, I’m also seeing similar behavior with “Grab Ctrl+Space”. This is pretty essential for Emacs use, as it’s used to mark regions. Right now it might work once, but then afterwards it switches to bring up the “change keyboard” menu — The same one that’s brought up when pressing the dedicated key to the left of the Ctrl button (with the globe). Not sure if your fix addresses that also?

**Comment by OldhamMade** [comment]
Oh, interesting; the first Ctrl+Space does nothing (doesn’t even set the mark), any following Ctrl+Space just enters a space.

If it helps, I’m connecting to an Ubuntu machine then starting Emacs directly (no Tmux/Screen session in the way).

**Comment by yury** [comment]
@OldhamMade unfortunately, Apple broke ctrl+space too. For CapsLock as Ctrl we found workaround, but for ctrl+space - not yet.

Anyway, as temporary solution you will able to map left or right cmd to ctrl+space combo, may be that will help.

**Comment by OldhamMade** [comment]
> Anyway, as temporary solution you will able to map left or right cmd to ctrl+space combo, may be that will help.

Allowing more options for the right Cmd/Option keys would be great! RightCmd+Spc seems like a very comfortable key press on the smaller iPad hardware keyboard.

**Comment by yury** [comment]
RightCmd+Spc  will not work too :( it is spotlight. But RightOption+Spc will work.

**Comment by cwis-public** [comment]
Incidentally, not seen it reported yet, but on iOS 13.2.3 with the latest Blink from the App Store, unmapped Caps Lock (I mean, “Caps Lock as Caps Lock”) doesn't work either.

@yury would this fix also fix this? If not let me know I can open a separate issue.

**Comment by yury** [comment]
Hi @cwis-public,

We have almost complete integration with new KB. I know, I promised to push TestFligh version last week, but turns out it is a lot.

One thing left, I will push TF on Monday.

![2706F5E1-C533-4E3E-BE7D-C8EFC8890405](https://user-images.githubusercontent.com/5250/70388487-9063d400-19c3-11ea-95e5-502af317fd64.png)
![FB4DEAD4-8280-49A0-9DD2-A4F2BA0F02F1](https://user-images.githubusercontent.com/5250/70388488-9063d400-19c3-11ea-8354-0d2c844556b2.png)
![70E4DDD4-5FB6-416B-91E1-108AEC3EA62D](https://user-images.githubusercontent.com/5250/70388489-9063d400-19c3-11ea-9a0a-afbfc2a30e3a.png)
![0ED40C16-6525-4207-801C-C995CC117F0C](https://user-images.githubusercontent.com/5250/70388490-90fc6a80-19c3-11ea-8813-9f826459fb70.png)

**Comment by chrismetcalf** [comment]
Any chance I could get onto the TestFlight?

**Comment by jerryabramson** [comment]
Me too?

**Comment by yury** [comment]
@chrismetcalf, @jerryabramson if you don't have previous TF access. Please send me your Apple IDs at yurykorolev@gmail.com.

I will push TF release later today.

**Comment by chrismetcalf** [comment]
@yury Sent! Thank you!

**Comment by jerryabramson** [comment]
Any update?

**Comment by yury** [comment]
@jerryabramson 
We got it working and testing it right now.
Sad, bu  we have some blockers: #893, #887. 

We have plan to simplify UI for keys config and release ASAP. 
Expect release next week.

**Comment by jerryabramson** [comment]
Hi Yury,

I was finally able to get the code to compile, and deployed to my iPad.

Apple sure makes this incredibly tough, I really hate xcode.

I see most of the stuff is done at the command-line, which is good.

But I think Xcode is required to deploy to a connected device.

[I do have a developer account].

I have been using build 189 for a couple of days, and it seems pretty good.

The control key mostly works, most of the time.

I am not having the issues with the command key that others are.

I am on iPadOS 13.3, using smart keyboard.

_Thank you,_

  * Jerry Abramson
  * jerry@jabramson.com <mailto:jerry@jabramson.com>
  * +1(603)888-1988 [home]
  * +1(603)566-3092 [cell]
  *

  * jerry.jabramson.com <http://jerry.jabramson.com>
  *

  * Jerry Abramson

**Comment by chrismetcalf** [comment]
@yury Generally the latest builds have been great, with the exception of one thing I'm not even sure is a "bug" - after using "caps as control", sometimes when I tab out into other apps, my capslock is on, even though it wasn't on in Blink.

**Comment by dmitryzykov** [comment]
@chrismetcalf 
https://github.com/blinksh/blink/issues/895

**Comment by agkozak** [comment]
More or less what @jerryabramson describes above just started happening to me this week. I'm using an Apple Smart Keyboard with Caps Lock mapped to Ctrl in Blink Shell itself. Every five minutes or so, Blink Shell decides that the Ctrl key is "on" the way the Caps Lock can be "on," and every character I press is a Ctrl-character -- till I press Caps lock again. Every once in a while, Caps Lock actually behaves as a Caps Lock, too.

This behavior made Blink Shell nearly unusable until I realized that I could now map Caps Lock to Ctrl in iPadOS Settings-- but it would be nice to have Blink Shell working again properly, too.
