### ISSUE TITLE
It still replicate sessions, like I click with two-fingers

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#856]
That happened just while I've switch blink to safari and back. Latest version from the appstore: Blink: v13.0.155. Oct 29 2019, then I had to click Cmd-W multiple times, but haven't received my initial session

![97CB4E1A-DCB2-491A-AC1A-00FAB348A1E8](https://user-images.githubusercontent.com/26776/68086083-24340480-fe48-11e9-9771-eaba37faea13.gif)

**Comment by dmitryzykov** [comment]
I have the same problem multiple times per day
IpadOS 13.2.2
Blink shell 13.0
But at the beginning i have my opened session, just need to close with Cmd-W a lot of new empty sessions. 
![98AF764D-9282-480C-97A6-31D59F159C64](https://user-images.githubusercontent.com/15911918/68529355-6bb60700-0306-11ea-9826-051a67f5229c.png)

**Comment by yury** [comment]
Should be fixed in Blink 13.1

**Comment by yury** [comment]
In blink v13.1 should be ok. Feel free to reopen issue if needed.
