### ISSUE TITLE
mosh connections hang

### ISSUE THREAD

**Issue by metageek** [blinksh/blink#858]
I bought blink today, and I’ve seen it mosh connections get hung twice. Both times were on my 9.7” iPad Pro (the only device I’ve tried blink on), running iPadOS 13.2, blink 13.0.155.

The first time, I’d been away about half an hour; the second time, about two minutes. Both times, the device had been locked by closing the Type Cover. The first time, it might also have had my Twiddler (Bluetooth keyboard) still connected; the second time, it definitely didn’t.

Both times, there was another connection open to the same host, which did not drop. Both times, the host was the same, a Linode VM running Debian. Running ps on the host still shows both the mosh-server processes.

The second time, I tried killing blink and restarting it; no help. The hung terminal is still saying, “mosh: Last contact 8:20 ago.” (with the time counting up).

I suppose it could be some middlebox objecting to the UDP traffic. Have you seen that before?

**Comment by LittleHouse75** [comment]
Same issue here.  Intermittent ability to reconnect to mosh sessions on Vultr.  I use an IPv6 only account.  Not sure if that comes into play.

**Comment by depili** [comment]
Before ipados 13 mosh sessions on blink were really reliable, after the upgrade the connection doesn't resume most of the times when awakening the ipad from sleep, and I have to kill the mosh client via escape and start a new one.

Probably something to do with the more agressive power management with ios 13?

**Comment by javierdemartin** [comment]
Possibly the same thing going on at #1048, will close this issue and track it there. Please if this is still happening or you have reproducible steps post them there.
