### ISSUE TITLE
Hosts list

### ISSUE THREAD

**Issue by sylvoie** [blinksh/blink#859]
Hello,

It will be useful to sort the host list in configuration screen.

Thank’s

Sylvain

**Comment by yury** [comment]
![98640560-A510-4F5F-BC3D-F4640644D60E](https://user-images.githubusercontent.com/5250/154631979-6883fa93-4f03-4e7b-8ecd-aeb89f9f1bf9.jpeg)

Added Sort and search.

Closing this issue. Fill free to reopen if needed.
