### ISSUE TITLE
CMD + K to clear buffer

### ISSUE THREAD

**Issue by kylef** [blinksh/blink#861]
Both on Terminal.app and iTerm 2, there is a keyboard shortcut to clear the buffer. It would be neat if Blink had the same shortcut.

**Comment by theusefulmonk** [comment]
`Ctrl-l` works currently.

**Comment by amcgregor** [comment]
@theusefulmonk I'll just point out that ⌘K (clear scrollback buffer) and ⌃L (clear screen) and a "clear" command are **not** the same things.

* Clearing the buffer means it's all gone.  Nothing remaining to scroll through.  It's potentially a security feature, the ability to wipe what has been seen.

* Clearing the current screen means erasing the 24 rows (or however many you have) at the end of the buffer.  Scrollback (content that had scrolled above the top of the display) will not be cleared.

* A `clear` command can only really effectively issue the same ⌃L ["control code"](https://en.wikipedia.org/wiki/Control_key#Table_of_examples) or an ANSI sequence such as `\033[0m\033[2J\033[1;1H` — reset character properties (color, background, weight), clear the visible display, move cursor to position 1, 1.  Or, worse-case, a command like that would just print N rows of blank lines to push the current screen contents into the scrollback.

**Comment by DAddYE** [comment]
+1, would be nice to allow users to map specific keys to blink commands.

**Comment by javierdemartin** [comment]
I'll work on this, progress will be tracked on #1041 as it's the most recent issue and close this one.
