### ISSUE TITLE
ipad pro12.9’(IOS13.2.1 & 13.2.2) cant run Blink13

### ISSUE THREAD

**Issue by laosuan** [blinksh/blink#864]
I updated to Blink shell 13, after that, blink get stuck forever. Almost keyword aren’t  work, Only press “Caommand** + ,” the setting  page is able to show up, but press the close button, every thing is stop. try to reinstall and update to IOS13.2.2, its still like that. Please fix the problem, thanks a lot.

**Comment by yury** [comment]
That is strange... Can you try to reboot device?

**Comment by laosuan** [comment]
> That is strange... Can you try to reboot device?

I reinstall blink few times, its be OK. Thanks
