### ISSUE TITLE
Glitch in App Design 

### ISSUE THREAD

**Issue by neafu** [blinksh/blink#867]
When I press "Add a new theme" while I'm in Dark Mode, it opens a glitched panel like the attached picture.

Blink Shell Version 13.0
In both iOS and iPadOS

![D43AD2EC-9FE1-4CB6-ADB6-F46CEEEB192C](https://user-images.githubusercontent.com/31031980/69481709-98007600-0e24-11ea-913d-7c1e9156d7aa.png)

**Comment by yury** [comment]
Fixed.
Thank you.
