### ISSUE TITLE
mosh hangs during connection

### ISSUE THREAD

**Issue by dnelson** [blinksh/blink#868]
on one of my servers (ubuntu 18.04.3), attempting to connect using mosh hangs indefinitely. It is also not possible to use Ctrl-C to cancel the connection attempt, which is frustrating.

It hangs at the following line in verbose mode:
```
MoshClient:DEBUG:mosh-server new -s -c 256 -l LC_ALL=en_US.UTF-8
MoshClient:DEBUG:ssh -v -o _printaddress=yes -o compression=no -t av mosh-server new -s -c 256 -l LC_ALL=en_US.UTF-8
```

I’ve successfully connected to the same server using mosh on another terminal app on iOS (Terminus), and can connect to it via ssh on Blink. I’m on the latest version of Blink in the app store. Any ideas on how to debug or what to do?

**Comment by j16sdiz** [comment]
Same problem here.
This is debian.

**Comment by j16sdiz** [comment]
`mosh -2` solved the problem

**Comment by carloscabanero** [comment]
This should have been fixed on libssh updates a while ago.

**Comment by pzeinlinger** [comment]
Unfortunately, I have the same problem with the most recent version

**Comment by carloscabanero** [comment]
@pzeinlinger can you connect to the machine over ssh?

**Comment by pzeinlinger** [comment]
Works fine all the time

**Comment by carloscabanero** [comment]
What does Mosh return when run in verbose mode?

If ssh connects fine, there shouldn't be any issues. Mosh first does a connection over ssh to figure out how to connect to the remote over UDP. Please check also that ports are open in the remote for that.

**Comment by pzeinlinger** [comment]
mosh connections from my computer also work fine.
mosh --verbose only logs 2 lines.... and can't be interrupted by Ctrl+C
```
MoshClient:DEBUG:mosh-server new -s -c 256 -l LC_ALL=en_US.UTF-8
MoshClient:DEBUG:ssh -v -...................
```

**Comment by pzeinlinger** [comment]
I've just realized that this issue is intermittent. Sometimes it connects.

**Comment by carloscabanero** [comment]
And ssh is also intermittent or it connects all the time?

I will keep an eye on it, as I am doing some work there now.

**Comment by carloscabanero** [comment]
Thanks for the report btw!!

**Comment by pzeinlinger** [comment]
No, ssh seems to connect every time (but I've just started to use Blink today) :-)
Btw, it's not a firewall problem, I've just tried to connect with no firewall in between and it still fails.

**Comment by Ajaymamtora** [comment]
Is there any update on this, i have the same issue on the latest version, iOS 14.6. Can’t connect unless I reboot my device
