### ISSUE TITLE
Feature request or education...

### ISSUE THREAD

**Issue by adameros** [blinksh/blink#869]
I loaded a .ssh/config file that works great form my linux and Mac systems, but it's not working in blink.

Specifically, I have a config file that automatically sets up a proxy through a bastion for logging in to end hosts, and this does not seem to be working.

Here is an anonymized (ips changes to XXX, and user names changed) example of the config file:
``
host api_status
        hostname -
host corp-west-host-1
        hostname 10.1.XXX.XXX
host corp-west-host-2
        hostname 10.1.XXX.XXX
host corp-east-host-1
        hostname 10.2.XXX.XXX
host corp-east-host-2
        hostname 10.2.XXX.XXX

########### Bastions and Proxies ###########

host corp-*
        # This bounces all corp-* servers off the aws bastion
        ProxyCommand ssh -q -W %h:%p bastion-corp
host bastion-corp
        # This defines the bastion
        hostname XXX.XXX.XXX.XXX
        port 22
host *
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
        loglevel = QUIET
        ServerAliveInterval 20
        ConnectTimeout 9001
        user mylogin
        # User's Key
        identityfile ~/.ssh/id_rsa
        identityfile ~/.ssh/OPS.pem
``
I loaded the config in to blink and I don't see the hosts loaded, and I didn't see a to add an entry without a hostname, like the "corp-*" proxy entry.

How can I load this in to config in to blink and get it to work?

**Comment by carloscabanero** [comment]
Just FTR, the way Blink works with ssh config files, it won’t show the hosts inside the settings, as you correctly mentioned. The hosts will be anyway accessible the same. Blink config is really just for convenience. We are working on a way to merge both.
