### ISSUE TITLE
Terminal window doesn't resize after hiding keyboard (while scrolling continues)

### ISSUE THREAD

**Issue by quinncomendant** [blinksh/blink#870]
On iPhone XR iOS 13.1.3 and Blink 13.0 (154), if I swipe down to hide the keyboard and continue scrolling content, the area where the keyboard was remains blank, i.e., the terminal window doesn't resize. This is perhaps a limitation caused by the UI to tradeoff the ability to scroll vs. instantly resize the window, so please mark this a `wontfix` if that's the case. 

Here's a video of the problem:

![out](https://user-images.githubusercontent.com/6884276/69885583-7af3f900-12a3-11ea-81f5-0d0d3e60ed26.gif)

This may be related to issues: #101, #277, #317.

**Comment by yury** [comment]
We try to reduce resizes. 

Closing as won't fix.

Thank you.
