### ISSUE TITLE
Are jump hosts supported?

### ISSUE THREAD

**Issue by Spandan-Madan** [blinksh/blink#871]
I need a SSH client to help with host chaining/jump host. Does this app support that? I am considering buying it for just this purpose. 

Thanks!

**Comment by yury** [comment]
We support proxy command, so you chain hosts with it.

I can invite you to Test Flight version, so you can try it before purchase.

**Comment by Spandan-Madan** [comment]
That would be really helpful @yury! Thanks a lot :)

The email on my Apple ID is spanmad@icloud.com, could you please send an invite to that email ID?

Best,
Spandan

**Comment by yury** [comment]
@Spandan-Madan sent you invite.
Check ProxyCommand  option under hosts configuration.

**Comment by sprig** [comment]
What about jump hosts on mosh, like what recent versions allow?
