### ISSUE TITLE
ECDSA private key import not working

### ISSUE THREAD

**Issue by ianeq** [blinksh/blink#872]
Hello, the ECDSA key import function is not working in version 13 (iPadOS 13.2.3) while trying to import p521 private key with resulting error message: “OpenSSL error. Could not creste Public Key.”

**Comment by yury** [comment]
@ianeq 
How do you generated that key? I want to reproduce this case.

**Comment by ianeq** [comment]
The key was generated on a Mac (macOS) and is working properly on any Mac or iPad (with Prompt 2). Subsequently, the private key was copied from Prompt 2 for iPadOS and pasted into Blink on the same iPad and then got the error when saving the key in Blink.
BTW: RSA (4096) private key generated the same way pasted properly into Blink and works flawlessly everywhere, just not the EC/P521 key.

**Comment by dmdx86** [comment]
I can also confirm that generating an ECDSA 521 key with ssh-keygen on Ubuntu 18.04 results in the same behavior.

**Comment by yury** [comment]
Fixed in blink v13.1.

Thank you.
