### ISSUE TITLE
ssh-agent forwarding not work

### ISSUE THREAD

**Issue by kecinzer** [blinksh/blink#873]
I can't figure out how to make ssh-agent forwarding. I'm connected with key to my server and I want to jump to another one using the same key, but it not work.

**Comment by giarc** [comment]
I just ran into this issue and it seems you have to start the ssh-agent, open a new blink tab, ssh-add <key name> and then ssh -A <host>. The blink tab with ssh-agent running needs to remain open, and MUST be done every time.

**Comment by kecinzer** [comment]
Its not working for me. Do I need something extra?

**Comment by giarc** [comment]
Have you used ssh agent forwarding before? its the same using blink, with the only wrinkle specific to blink shell being that you MUST run ssh-agent manually as it's not running by default:

In one blink tab (leave this open and running):
`$ ssh-agent`

open a new blink tab and add your key(s) to the ssh agent:

`$ ssh-add yourkeyname`

To confirm the key you want forwarded has been added to the ssh agent ( capital 'L' and lowercase 'l' would both work for this step, but _are_ different flags)  :

`$ ssh-add -L
`
Then ssh to your host with the 'forward my keys for this connection from the ssh agent' flag (capital 'A' as lowercase 'a' disables the option)

`$ ssh -A yourhost`


FYI: mosh doesn't support key forwarding... so if you're expecting mosh to work just like ssh in this regard, it won't.

<img width="1194" alt="Screenshot 2019-12-17 at 12 29 53 PM" src="https://user-images.githubusercontent.com/1385535/71020228-ef170500-20c9-11ea-8f46-dce9d86b817f.png">
<img width="1194" alt="Screenshot 2019-12-17 at 12 36 22 PM" src="https://user-images.githubusercontent.com/1385535/71020233-f1795f00-20c9-11ea-9364-8986552f6bf8.png">

**Comment by kecinzer** [comment]
You are my life saver. This works great! Thank you for the tutorial.
It will be great if it works out of the box, I hope Blink will do it in the future.

**Comment by luizribeiro** [comment]
What would it take for us to make this work out of the box?

Would the ideal way of doing this be a setting under config for ssh-agent forwarding, which would spin up the ssh-agent on the background and automatically add the `-A` option on any ssh connection?

**Comment by xslim** [comment]
Just installed latest blink from AppStore, and `ssh -A` is not there :(

**Comment by yury** [comment]
@xslim you have to run `ssh-agent` command in separate tab at this moment. We will improve that in next version.
So in one tab run `ssh-agent` command, then in another tab you can use `ssh-add` command to add keys and finally you can use `ssh -A`

**Comment by xslim** [comment]
Yes I did all that in beginning, and it did not work. After restarting the app it does work. Magic. :)

**Comment by carloscabanero** [comment]
Happy to report this is now part of 13.90.3.273 on TestFlight.

We have improved our integration, so it is not necessary to run it in the background. The agent is now handling all our key needs, and ssh -A should just work. This integration will help us run a bunch of other cool stuff, so please let us know.
