### ISSUE TITLE
No uppercase Danish characters

### ISSUE THREAD

**Issue by M0rtenB** [blinksh/blink#874]
Using Apple’s Smart Keyboard for my iPad Pro, holding shift and typing the Danish letters æ, ø and å, don’t produce their uppercase counterparts Æ, Ø and Å in Blink, as it should, but only lowercase.
With the on-screen keyboard, there are no problems.
In other apps, no problems.

On Blink 13.0.155. iPadOS 13.2.3.

**Comment by yury** [comment]
For now, you can turn off autorepeat in `config` -> `Keyboard`.

In next version it will work with autorepeat by default.
