### ISSUE TITLE
Change MOSH_ESCAPE_KEY

### ISSUE THREAD

**Issue by dmitryzykov** [blinksh/blink#875]
My main workflow is `blink -> mosh -> vim`
And my main annoyance is mosh’s ESC key.
Mosh uses `Ctrl-^` as ESC but it is very commonly used hotkey in vim to switch between buffers.

I want to change mosh’s ESC and found in the mosh documentation:

> There are two slightly different modes for escape sequences, depending whether the escape character is printable or not.

>If the escape character is a printable character, it must be prefixed with a newline, similar to OpenSSH. To send the escape character itself, type it twice. If the escape character is set to ~, mosh will behave much like OpenSSH.

>If the escape character is a non-printable control character, no prefix is used and the escape character is recognized at any time. To send the escape character itself, type the escape character, then its corresponding ASCII character (for Ctrl-^ you would type ^, for Ctrl-B you would type B).

>MOSH_ESCAPE_KEY (ENV variable)
> When set, this configures the escape character used for local commands. The escape character may be set to any ASCII character in the range 1-127. The variable must be set with a single literal ASCII character. Control characters are set with the actual ASCII control character, not with a printable representation such as "^B".

Blink allows to add an ENV variable by `setenv` but i encountered some problems:

1. I can’t insert non printable literal ASCII character in blink terminal. In linux bash\zsh it is possible to press `Ctrl+v` and then Keystroke which will be written as ASCII character. 
Is there any way how I can insert non printable literal ASCII character in blink?

2. When I tried to use printable char and set ENV variable  like `setenv MOSH_ESCAPE_KEY '^'` this ENV variable is temporary and can’t survive blink restart. 
Is there any way how to make an ENV variable persistent in blink? 

P.S. I’m not using Mosh’s ESC functionality, so if some how possible to disable it - that will be even better.

**Comment by yury** [comment]
Hi @dmitryzykov 

1. You will be able to assign key combo to custom sequence in next version of blink
2. You can define envs in ~/.blink/profile (echo "MOSH_ESCAPE_KEY=^" > .blink/profile). You need to restart app to get it loaded.

**Comment by dmitryzykov** [comment]
Hi @yury 
Thank you for your quick answer. Looking forward for the new version of blink.

During my tests with `MOSH_ESCAPE_KEY` i found strange blink+mosh behavior (video included):
When `MOSH_ESCAPE_KEY` is set to any valid to mosh printable ASCII char value ( e.g. `setenv MOSH_ESCAPE_KEY '~'` ) and i connect by mosh to a server and keep open vim and then minimize blink app (and wait a little bit) or just lock iPad and then open back blink - vim always became suspended ( as if i manually press `Ctrl+Z` ). 
It never happened when `MOSH_ESCAPE_KEY` is not set. 
It not happened when mosh lost network and reconnect (when i turned on fly mode on ipad and then turned off).
I tested it with different server environments (latest ubuntu with neovim and old centos with vim 7.x) and got the same strange behavior.
Also i tested it on my mac with mosh from brew, `export MOSH_ESCAPE_KEY='~'` and the same servers and couldn’t reproduce that problem. 
I can reproduce that only with blink and `MOSH_ESCAPE_KEY`

I recorded a whole test on the video: https://youtube.com/watch?v=S59-obI6JOg

**Comment by yury** [comment]
Yep, good catch. I really didn’t know that you can override `C-^` with env var :) So blink sends `C-^ C-Z` sequence to dump state to disk. So Blink should actually use `MOSH_ESCAPE_KEY` too send right sequence to suspend state.

Thank you. Will try to fix next week, after grant KB rewrite.

**Comment by dmitryzykov** [comment]
Thank you, looking forward for a new release with fixes.

**Comment by yury** [comment]
Ok, MOSH_ESCAPE_KEY="~" is working. (Note. Use " for env values in profile file)

**Comment by yury** [comment]
Update:
Actually it will not work with "~" :)

For escape characters with code >= 32 line feed is required.
So it should work with chars < 32.
You can use `\u` to set chars. Example `\u001e` is default Mosh Escape Key.

**Comment by dmitryzykov** [comment]
@yury 
Thank you. 
Sorry it is still not clear for me how to set non-conflicting with vim escape sequence and how to try it ( should i request access to blink beta?)

**Comment by yury** [comment]
Send me your Apple ID at yury.kotolev@gmail.com.

You can run blink `showkey` command. And try to find Ctrl+ combination that you don't use in vim. For instance `^\       28 0034 0x1c`. It is 28, so it doesn't require line feed.

**Comment by dmitryzykov** [comment]
@yury 
`echo 'MOSH_ESCAPE_KEY="\u001c"' > .blink/profile`
works well in tf 179, thank you.

**Comment by dmitryzykov** [comment]
@yury 
Blink has UI settings for mosh per host.
![C300C03D-441B-48B5-AAA4-39D1559F9BD9](https://user-images.githubusercontent.com/15911918/70732743-b2d25600-1d11-11ea-8c3d-4d526cdf6264.jpeg)
 
Please consider to add MOSH_ESCAPE_KEY settings here, for more user-friendly and intuitive configuration.

Or maybe consider to add global Mosh settings (ESC key, prediction, ssh options) in the Blink settings (Configuration section?).
![542E7336-A7BB-470B-BF6A-689B034273F7](https://user-images.githubusercontent.com/15911918/70733635-60923480-1d13-11ea-85a6-174673fd9f95.jpeg)

**Comment by yury** [comment]
@dmitryzykov it is really rare case... Should be ok with env var. Closing original issue. Feel free to reopen if needed.
