### ISSUE TITLE
new beta - caps lock->esc mapping not working

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#876]
In the mosh configuration, I've set caps lock to map to escape, but it's not being recognized in ssh or mosh. What am I missing?

Version 13.1(174).

(Update: Option->escape mapping doesn't appear to be working either. I'm hoping it's just something I'm failing to do correctly.)

**Comment by sbromberger** [comment]
New update: with these mappings, the software keyboard sends an escape after the next key is pressed (that is, in vi insert mode, hitting caps lock and then a letter will send an esc), but hardware keyboard is now broken (it worked passingly well in the previous beta though sometimes it would "stick" on caps lock so that other apps would have a problem until I cycled back to blink and hit caps lock again).

**Comment by sbromberger** [comment]
Closing out. The setting has to be for "Down", not "Modifier". Once you set "Down" to "Esc", it works. Sorry for the false alarm.

**Comment by yury** [comment]
We are thinking how we can improve UI/UX for that. If you have any ideas, please share.
