### ISSUE TITLE
Regression: ⌘ , doesn’t bring up config

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#877]
New TestFlight 13.1 (174) — if I hit  <kbd>⌘,</kbd>, the config sheet blinks in and immediately blinks back out (so fast I can’t catch it in a screen capture). To change prefs I have to open a new shell and do `config⏎`.

**Comment by sbromberger** [comment]
(I can't even get it to blink rapidly as you described using the hardware keyboard.)

**Comment by treyharris** [comment]
@sbromberger I can’t now either now that I’ve done a swipe-away and close/reopen of sessions in trying to figure out a different issue.

**Comment by yury** [comment]
Fixed in build 177.
Thank you.
