### ISSUE TITLE
Regression: URL selection and context menus don’t work

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#878]
The ability to select URL’s by holding a finger on any part of the URL, and the contextual menu with “Open” and “Copy” actions, have both disappeared (tap for YouTube screen capture):

[![Blink screen capture](https://img.youtube.com/vi/symJjw4B3Hw/0.jpg)](https://www.youtube.com/watch?v=symJjw4B3Hw)

**Comment by treyharris** [comment]
Also, note that when I enter text-selection mode, the bar goes away, causing the screen to redraw, which can move the item you’re trying to select. If you click elsewhere to start again, the status bar returns.

This isn’t bad in the case shown in the video because the text is already in scrollback so a window change doesn’t move the location of the text. But in (for instance) WeeChat’s normal text buffer mode, it makes it essentially impossible to select anything, because if the status bar appears it moves all the text up by one line, so if it disappears text goes down a line, then, if you tap to start selecting again, not only does the status bar reappear, but in WeeChat’s case, tapping in whitespace to the right of a text line is interpreted as a channel-change request. So, essentially, without freezing the screen with something like Tmux, it’s now impossible to select and copy text at all.

**Comment by yury** [comment]
Fixed in build 177. Thank you.

PS:
Apple calls it `shortcuts` bar in Config.app -> KB.
In API it is called `UITextInputAssistantItem`
We call it `smart keys` bar

**Comment by yury** [comment]
I'm closing this issue. Please feel free to reopen.
