### ISSUE TITLE
^C is mapped to ^M

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#879]
This is actually pretty dangerous, since ^C can be used to cancel a command, and instead is executing it in the latest beta (13.1.174). This is happening in both mosh and ssh, and in the blink console as well.

**Comment by sbromberger** [comment]
To test: from a blink prompt, type `ls` and instead of hitting enter, hit control-C. notice that `ls` executes.

**Comment by sbromberger** [comment]
@treyharris - would you mind confirming this? I'm hoping it's just a misconfiguration on my side....

**Comment by yury** [comment]
Confirming... working on that.

**Comment by yury** [comment]
Fixed in 177 build. Thank you.

**Comment by sbromberger** [comment]
Thank you, @yury. Possibly related: any chance we could get https://github.com/blinksh/blink/issues/813 back?

**Comment by sbromberger** [comment]
Confirmed fixed in 177. Thanks!!!
