### ISSUE TITLE
Can not typing on Slide Over

### ISSUE THREAD

**Issue by aofei** [blinksh/blink#880]
It happened in the latest beta v13.1 (174). The video record I just DMed to your Twitter.

**Comment by aofei** [comment]
Fixed in the latest beta v13.1 (177). 🎉

**Comment by aofei** [comment]
This problem doesn't seem to be resolved, it still happens from time to time, but I haven't found a way to reproduce it 100%. So I'll reopen this issue so that other people who encounter the same problem can find a place to discuss.

**Comment by yury** [comment]
@aofei 
Can’t repro yet. But try `cmd+o` shortcut next time.

**Comment by aofei** [comment]
This bug has happened very frequently recently.  `cmd+o` helped, but if I don't restart the app, I need to press `cmd+o` every time I return to Blink and want to go out again, which is very annoying. Therefore, the best workaround at the moment is to restart the app.

Still haven't found a 100% way to reproduce. Maybe you can try Slide Over for a while? I believe you will get lucky. 🤔

**Comment by yury** [comment]
Try 13.2 TF, I did some focus fixes...... still can’t reproduce :(

**Comment by aofei** [comment]
Still happens in TF Build 210.

**Comment by yury** [comment]
Yep, with Settings.app -> KB -> Shortcuts OFF I can reproduce it now.

**Comment by aofei** [comment]
Closing this issue because it hasn't been reproduced recently.
