### ISSUE TITLE
Mosh port range support

### ISSUE THREAD

**Issue by cbredi** [blinksh/blink#881]
Currently only one mosh port can be added to a host configuration.

Can you please implement a port range for mosh ports? When connecting to hosts behind firewalls that forward non-standard mosh ports only one connection is possible without a mosh port range.

Thank you!

**Comment by yury** [comment]
Hi @cbredi,

I have added port range support for mosh. Will be in next release.

**Comment by yury** [comment]
You can specify port range on config. Thank you.
