### ISSUE TITLE
option-arrow-keys does not working in tmux with TF vertsion

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#882]
All the Option-arrow keyboard bindings in tmux does not working with fresh TF version.

How to replicate:
remove blink,
install TF version
ssh / mosh and start/attach tmux with following snippet in tmux.conf file.

Expected result: option - left or option - right should switch window within current tmux session

```
  # Option left/right to switch window                                                                                                                                                 
  bind -n  M-Left previous-window                                                                                                                                                      
  bind -n M-Right next-window                                                                                                                                                          
```

**Comment by treyharris** [comment]
Emacs gets those keys still, but it’s getting them via two translations when I’m pretty sure before it was just one:

```
ESC <left> (translated from ESC M-O D)...
ESC <right> (translated from ESC M-O C)...
```

so it’s possible that the actual codes sent have changed slightly.

**Comment by yury** [comment]
@andrius can you also post your ~/.blink/kb.json

**Comment by andrius** [comment]
there is no such file

```ls -lai  ~/.blink/
total 32
38852532 drwxr-xr-x  6 mobile  mobile   192 Dec 11 19:31 .
38852038 drwxr-xr-x  5 mobile  mobile   160 Dec 11 19:30 ..
38858994 -rw-r--r--  1 mobile  mobile   687 Dec 11 19:30 defaults
38859354 -rw-r--r--@ 1 mobile  mobile    49 Dec 11 19:31 history.txt
38859338 -rw-r--r--  1 mobile  mobile  3225 Dec 11 19:31 hosts
38856965 -rw-r--r--  1 mobile  mobile   236 Dec 11 19:29 keys```

I also did restarted removed and installed blink and restarted ipad.

keyboard mappings:
![C65F7299-DA27-4854-8B24-E579A568646F](https://user-images.githubusercontent.com/26776/70649294-1ba3ca80-1c4d-11ea-946a-f5353aa49d48.jpeg)

**Comment by yury** [comment]
Ok
1. you don’t have kb.json bc you don’t modify anything. That is good ;)
2. you should set `Option` key modifier to `Escape`. (kb.json will appear and tmux will work. Tested myself)

**Comment by yury** [comment]
Probably we should set `Option` modifier to `Escape` by default (without skip accents). What do you think @carloscabanero ?

**Comment by andrius** [comment]
yes, works after I've set it to Esc

**Comment by treyharris** [comment]
And, indeed, the Emacs double-translation I mentioned above is no longer happening, so that suggests Emacs `describe-key` (<kbd>C-h k</kbd>) may be a good diagnostic for this sort of thing in the future.
