### ISSUE TITLE
Keyboard special keys vanish

### ISSUE THREAD

**Issue by ttelford** [blinksh/blink#883]
The special key section on the top of the keyboard vanishes when opening, or when switching from landscape to portrait.

It can be brought back by scrolling up to hide the keyboard, and tapping the screen to bring the keyboard back.

![B9E1C23A-749A-47A7-A666-25CF88463C65](https://user-images.githubusercontent.com/142838/70646535-546b8180-1c04-11ea-8100-40c28a1e630c.png)

**Comment by yury** [comment]
Yep, that is still in progress :)

Thank you.

**Comment by yury** [comment]
Fixed in Build 180.
