### ISSUE TITLE
glitch with additional keyboard panel when using hardware keyboard (TF 179)

### ISSUE THREAD

**Issue by dmitryzykov** [blinksh/blink#885]
trying tf 179
get additional keyboard panel when using hardware keyboard almost all the time.
![6BE6C427-BF8D-4E3B-9A96-53C1AC6F49A5](https://user-images.githubusercontent.com/15911918/70718660-477c8a00-1cf9-11ea-90b8-33d6404635b0.jpeg)
1. started blink
2. mosh to server
3. command+tab 
4. return to blink and have additional panel
5. hiding it with software button 
6. pressing enter and got it back

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15911918/70719007-f6b96100-1cf9-11ea-833f-30363c7f686e.gif)

**Comment by yury** [comment]
Yep, it is known issue. Will be fixed soon. (that hide button - hides it temprory)

**Comment by yury** [comment]
@dmitryzykov can we close this one? It should be ok in latest betas.

**Comment by dmitryzykov** [comment]
@yury 
Sure, didn’t see that problem in latest builds.
