### ISSUE TITLE
TF179: shift and ctl with arrow keys no longer work

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#886]
I have my vimrc mapping shift-downarrow to `Vj`, and control-right/left to next/previous buffer. In TF179, these keys no longer work (they worked at least in 177). Holding down shift while pressing the arrow keys has no different effect than just using the arrow keys.

**Comment by sbromberger** [comment]
Just wanted to thank you again for the amazingly fast support, @yury. Blink is a real joy to use and I'd be lost without it.

**Comment by yury** [comment]
Thank you!

Fixed in build 180

**Comment by sbromberger** [comment]
Confirmed fixed in 180. Thanks!!!

**Comment by yury** [comment]
Closing. Thank you!
