### ISSUE TITLE
IPad Pro with Folio Keyboard - Can’t insert special characters or dot

### ISSUE THREAD

**Issue by moxuz** [blinksh/blink#891]
I am using iOS 13.2.2 and I just installed blink.
I started getting this issue while in ssh where hitting dot (`.`) would just insert the last command I entered and I could not enter symbols.
I realized that when exiting ssh and in the main blink window I cant insert `.` or any symbols either. This does NOT happen when using the onscreen keyboard. This is only when using the folio keyboard. This seems to be intermittent and starts happening on and off. Restarting blink does not solve the issue, the symbols just start working after a few restarts and some waiting.

**Comment by yury** [comment]
It could be on CapsLock state (Which is broken on iOS 13). We are working on new version (13.1) to workaround that. I can send you TF invite. Please send me your Apple ID at yury.korolev@gmail.com if you are interested.

**Comment by moxuz** [comment]
Awesome, I’ve sent you an email. Thanks!

**Comment by yury** [comment]
Hi @moxuz i'm closing this issue since blink 13.1 released.

Feel free to reopen if needed.
