### ISSUE TITLE
 Frozen terminals

### ISSUE THREAD

**Issue by mauceri** [blinksh/blink#892]
I have to frozen terminals on ec2 instances which are deleted, how can I get rid of them? I tried to stop and restart Blink by double clicking the home button (I’m on an ipad pro) but the two frozen terminals remain when I restart...

**Comment by dmitryzykov** [comment]
have you tried to close tab in blink? 
`⌘W` on the keyboard or three fingers tap and `close` buton? 
![9BC288DF-EEF1-41AF-883F-C39FC1B99676](https://user-images.githubusercontent.com/15911918/71090304-653f6880-21ab-11ea-8523-fb4eca966f8e.jpeg)

**Comment by mauceri** [comment]
Many thanks! It works :)

Christian Mauceri, PhD

**Comment by yury** [comment]
Ok, I will close this issue. Feel free to reopen if needed.
