### ISSUE TITLE
TF Build 184: Copy&Paste shortcuts (⌘C & ⌘V) doesn't work

### ISSUE THREAD

**Issue by aofei** [blinksh/blink#893]
The copy&paste shortcuts doesn't work in the recent TF builds, but I haven't seen anyone posting related issues. Am I the only one who has encountered this problem? 🤔

I tried different approaches (such as Reset Keyboard) and none of them worked. 🤷‍♂️

**Comment by dmitryzykov** [comment]
tf184
I tried to copy with `⌘C` and it didn’t work in 50%. Sometimes it worked, sometimes is not. So i can confirm that have this problem too.
`⌘V` works all the time in my tests

**Comment by yury** [comment]
Fixed in build 185.

**Comment by dmitryzykov** [comment]
185 helped. Can’t reproduce anymore this issue. Thank you.

**Comment by aofei** [comment]
I also checked, works like a charm. ❤️

Closing this issue.

**Comment by yury** [comment]
Thank you!
