### ISSUE TITLE
Feature request: restore caps lock state when exiting

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#895]
I have caps lock mapped to esc in Blink. When I switch out of blink to another app, frequently caps lock is activated in that app when it wasn't before.

I don't know whether this is possible, but it would be very nice for Blink to restore whatever state caps lock was in before blink when swapping out to another app.

**Comment by yury** [comment]
Sad, but there is no API to set CapsLock state or prevent it from changing.

**Comment by sbromberger** [comment]
Oh. Too bad. Thanks very much for the quick reply. I'll close this out so as not to distract you further from your work. :)

**Comment by dmitryzykov** [comment]
@sbromberger I’m using workaround for this, maybe it will work for you too:
In iPad settings > general > keyboard > disable Caps Lock 
And iPad settings > general > keyboard > hardware Keyboard > enable Switch languages using Caps Lock
After that i don’t have any problems with enabled caps lock after blink.

![E25C338A-4798-407A-A616-BE10B92C5B59](https://user-images.githubusercontent.com/15911918/71325124-dc009c80-24f0-11ea-9978-f522f1f2aa67.jpeg)
![9AB2EED3-6BEA-4DCD-9750-998706901BB9](https://user-images.githubusercontent.com/15911918/71325125-dc009c80-24f0-11ea-944d-a3f2fe2216ac.jpeg)

**Comment by sbromberger** [comment]
I don't have the "switch languages" option since I only have one language selected, but I do have "enable caps lock" deselected, so my settings match yours there. Thanks though!
