### ISSUE TITLE
blink on iPhone not working 

### ISSUE THREAD

**Issue by antonmedv** [blinksh/blink#897]
On my iPad is working, but connecting from iPhone not working. Ssh displays nothing. 
Mosh says “Did not find remote IP address”. 
Confide synced via iCloud.

**Comment by yury** [comment]
Hi @antonmedv, what phone do you have?

Can I send you test flight version to test? (Email me your Apple ID at yury.korolev@gmail.com)

**Comment by antonmedv** [comment]
iPhone 11 Pro.

**Comment by antonmedv** [comment]
I installed test flight version. Still not working. What’s next? :)

**Comment by yury** [comment]
Can run ‘ssh -vvvvvv <host>’ command?

**Comment by antonmedv** [comment]
```
ssh_packet_userauth_failure: Access denied for 'publickey
'. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied for 'publickey
'. Authentication that can continue: publickey
```

Keys are synced via iCloud.

**Comment by yury** [comment]
We disabled keys sync for security reasons.

**Comment by antonmedv** [comment]
Oh, will be cool to see this somehow in the app. How to switch to normal (not testflight version?)
