### ISSUE TITLE
Option-arrow key, Option-enter don't work

### ISSUE THREAD

**Issue by ChaiTRex** [blinksh/blink#899]
With Blink 13.0, I could press Option+Down arrow and Option+Up arrow to cycle through chatrooms and Option+Enter to edit something in /fset in Weechat on Ubuntu. With Blink 13.1, those key combinations do nothing.

Luckily, Esc followed by Up arrow or Down arrow was fixed and works in the interim for cycling through chatrooms, but I can't seem to find a key combination to easily edit something in /fset.

---

iPadOS 13.3
Blink 13.1.196

**Comment by yury** [comment]
set `config->Keyboard->Option->AS MODIFIER` to `ESC`

**Comment by ChaiTRex** [comment]
Thank you. That worked.
