### ISSUE TITLE
Bell notifications

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#90]
The user needs a way to know when the bell rung in any of the open terminals and visit it directly.

**Comment by BinaryBen** [comment]
Not sure if seperate issue or not, but Prompt has a visual bell that flashes the entire screen with a subtle but quick fade in and out. It would be good if this could be implemented for screens in focus (as a toggle to replace the way the cursor flashes for those that prefer/don't notice the cursor flashing) - bonus points to make the colour customisable via the theme file (Prompt allows white, white or purple if you find the [Easter egg](https://panic.com/blog/violet-beep/))

**Comment by BinaryBen** [comment]
In terms of a way of notification of a bell in another terminal other than the one in focus, maybe a simple interface of a small circle in the top right with a number of notifications not yet seen; user could then just ⌘-][ as needed rather than implementing a "jump to" feature, which might be jarring to a users workflow anyway. Could also implement a ring around the dots on the existing HUD for the open terminals to help the user know which have a notification.

**Comment by carloscabanero** [comment]
Interesting idea changing the dots colour. That would be really nice.

**Comment by masochist** [comment]
A request for anyone who gets a round tuit for this: please provide an option for an *audible* bell. Visual bells are distracting and potentially harmful for those with epilepsy; audible bells, while inadvisable in public without headphones, don't have this problem and furthermore make it very clear that a bell has rung even if the user isn't looking at the terminal at the time it rings. If I'm afk for whatever reason, I want to know a bell run while I was away. If you're not looking at the terminal, then by definition you won't notice a visual bell.

**Comment by treyharris** [comment]
This has been in the icebox for awhile, but it would be very handy if a bell could result in a _system notification._ Right now I'm waiting on an interminably long test suite, so I'm browsing, using Discord, etc.—but without switching back to Blink every couple minutes, I can't be sure the test didn't abort. If I knew I'd get a notification, I wouldn't have to worry about this.

**Comment by treyharris** [comment]
(And yes, I know I'd probably have to enable `geo` for this to actually happen.)
