### ISSUE TITLE
Mosh Disconnect Support Request

### ISSUE THREAD

**Issue by garevans** [blinksh/blink#900]
Hi Folks, 

I have an issue with mosh, when the server disconnects (or reboots). I get locked in a blink screen asking me to use the keyboard combo Ctrl + .

I've tried the shortcut, but it doesn't disconnect the session. The only way I've been able to resolve is to delete / re-download the app. Am I missing something obvious?

**Comment by yury** [comment]
You can close tab with cmd+w or 3f tap and close button. 

![6D93BF29-C844-44C9-ADDA-E8AA398A0EF2](https://user-images.githubusercontent.com/5250/71661587-c5174100-2d5f-11ea-821d-38f42c137fa4.jpeg)

**Comment by garevans** [comment]
That’s exactly what I needed. I’m assuming the CTRL . Message was coming from Mosh rather than blink. 

I knew it would be user error! Thanks for the help!
