### ISSUE TITLE
Software keyboard caps lock doesn't work

### ISSUE THREAD

**Issue by j-tai** [blinksh/blink#901]
On Blink version 13.1, the caps lock on the software keyboard (double-tap shift key) no longer works. The characters typed in are not actually capitalized.

**Comment by adulescentulus** [comment]
For me no capital letter works on my iPad mini 5. When I press shift the following letter is always small. Using GBoard and native iOS keyboard is the same.
All worked before the last update

**Comment by cwis-public** [comment]
Not sure if this is related, the physical Caps Lock key on the Smart Keyboard Folio doesn't work neither. Let me know @yury if you'd like me to file a separate issue about this!

**Comment by yury** [comment]
@cwis-public can you gist your `.blink/kb.json` ?

**Comment by yury** [comment]
@cwis-public  no need in config. Found issue and fixed.

**Comment by adulescentulus** [comment]
@yury so all caps lock problems should be fixed by 5cdeef3 ? When will this be rolled out to the app store?

**Comment by yury** [comment]
Hope next week.  We pushed new release to public test flight, I can send you invite if you interested.

**Comment by adulescentulus** [comment]
@yury please, send me an invite. Do you need anything from me for this?

**Comment by yury** [comment]
Email me (Yury.korolev@gmail.com) your Apple ID.

**Comment by adulescentulus** [comment]
Ok, Build 204 works for me and capital letters are working again. Thanks!

**Comment by j-tai** [comment]
Fixed in version 13.2.
