### ISSUE TITLE
Themes and appearance changes don’t take effect.

### ISSUE THREAD

**Issue by jorgeamuniz** [blinksh/blink#902]
Using Blink on the latest iPad Pro 3rd gen running iPadOS 13.3 and themes are not working for me. I also try to change the font and font size but, there is no change to the appearance. I’ve tried ssh’ing to a server and force closing the app after making changes but, the appearance settings don’t take effect.

**Comment by yury** [comment]
@jorgeamuniz, 
Themes are applied to new sessions. Try create new shell with 2finger tap.

**Comment by yury** [comment]
Ok, closing... feel free to reopen if needed.
