### ISSUE TITLE
Feature request: more configurable shortcuts

### ISSUE THREAD

**Issue by vierpi** [blinksh/blink#903]
I have a Brydge keyboard for iPadPro 12.9 with German layout.  With this configuration it is not possible to type < and > on the hardware keyboard. There are characters like this on the keys B and N but these are not ASCII codes 60 (<) or 62 (>) but 8249 and 8260. For programming this is really annoying.
With the new version of blink in the Appstore (version 13.1) it is possible to define "Custom presses" but the configurable "Actions" for these shortcuts are static.

So I would like to request:
- Either add the actions "Press <" and "Press >"
- or even better make the actions user configurable

Thank you for your support.

**Comment by carloscabanero** [comment]
Thanks! Question for you, in other non-brydge keyboards, do the <> between shift and Y work properly with blink?

**Comment by vierpi** [comment]
I also have the Apple Magic Keyboard and there <> between Shift and Y do work properly with blink.

**Comment by yury** [comment]
@vierpi can log these keys with [logger](https://jsfiddle.net/yuryk/1vdmk8ws/embedded/result/) and post results here?

**Comment by vierpi** [comment]
I typed the keys ‹› which I would like to be replaced by <>:

typed text:

    ‹›

|  n |        type |      code | key   | kc | mods | repeat | l | comp |                 iType | data |
|---:|------------:|----------:|:------|---:|-----:|-------:|--:|-----:|----------------------:|-----:|
|  1 |     keydown | ShiftLeft | Shift | 16 |    S |        | 1 |      |                       |      |
|  2 |     keydown |  AltRight | Alt   | 18 |  S-A |        | 2 |      |                       |      |
|  3 |     keydown |      KeyB | ‹     | 66 |  S-A |        | 0 |      |                       |      |
|  4 | beforeinput |           |       |    |      |        |   |      |            insertText |    ‹ |
|  5 |       input |           |       |    |      |        |   |      |            insertText |    ‹ |
|  6 |       keyup |      KeyB | ‹     | 66 |  S-A |        | 0 |      |                       |      |
|  7 |     keydown |      KeyN | ›     | 78 |  S-A |        | 0 |      |                       |      |
|  8 | beforeinput |           |       |    |      |        |   |      |            insertText |    › |
|  9 |       input |           |       |    |      |        |   |      |            insertText |    › |
| 10 |       keyup |      KeyN | ›     | 78 |  S-A |        | 0 |      |                       |      |
| 11 |       keyup | ShiftLeft | Shift | 16 |    A |        | 1 |      |                       |      |
| 12 |       keyup |  AltRight | Alt   | 18 |      |        | 2 |      |                       |      |
| 13 |      change |           |       |    |      |        |   |      |                       |      |

**Comment by vierpi** [comment]
I can confirm that with latest v13.2.1.210 in Appstore this issue is solved.  Thank you.

**Comment by yury** [comment]
Thank you.
