### ISSUE TITLE
Touch ID lock can be bypassed by pressing Cancel

### ISSUE THREAD

**Issue by ChaiTRex** [blinksh/blink#905]
Whenever Blink locks with Touch ID, Touch ID can be bypassed by pressing the Cancel button at the Touch ID prompt.

* [Video demonstration](https://youtu.be/GQgs6hEZdaE)

---

Blink 13.1.196
iPadOS 13.3
iPad Air 2

**Comment by yury** [comment]
Fixed in v13.2

Feel free to reopen if needed.
