### ISSUE TITLE
Can’t dismiss stuck key notice

### ISSUE THREAD

**Issue by curtismchale** [blinksh/blink#906]
With the latest AppStore build I can’t dismiss the stuck command key build from Blink on my external monitor. Since it’s not a touch screen and the mouse support doesn’t extend to the second screen, I’m just stuck not being able to see the full screen I should be working on.

Possibly related to: https://github.com/blinksh/blink/issues/887

![IMG_0540](https://user-images.githubusercontent.com/74561/71900744-416ca400-3113-11ea-9568-2ab25b368b86.png)

**Comment by yury** [comment]
Pressing command key doesn’t dismiss this window?

**Comment by curtismchale** [comment]
only sometimes. In the screenshot above, it wouldn't and I finished out the bit of work I was doing with the notice up then quit blink and the notice was gone.

Sometimes, yes pressing the CMD key again does work and dismiss the window.

**Comment by yury** [comment]
I will try to switch to touch screen and show window there. Thanks.
