### ISSUE TITLE
Korean language doesn't work!

### ISSUE THREAD

**Issue by sstonejuProject** [blinksh/blink#909]
It doesn't work at lastest version
![1A3A5436-23BC-4878-BEA6-C7257E4B3F51](https://user-images.githubusercontent.com/37171336/72083241-cdb1dd80-3344-11ea-8095-8a70d0280ad3.jpeg)

**Comment by sstoneju** [comment]
correctly word is "작동이안되"

**Comment by yury** [comment]
@sstoneju can you record a video how you type this?

**Comment by sstoneju** [comment]
* used software keyboard
<iframe width="640" height="360" src="https://youtu.be/KhLdGqZ_2y0" frameborder="0" gesture="media" allowfullscreen=""></iframe>

* used software(ipadPro case) keyboard
<iframe width="640" height="360" src="https://youtu.be/2e0lPynEPGY" frameborder="0" gesture="media" allowfullscreen=""></iframe>

**Comment by yury** [comment]
@sstoneju thank you. Fix will be in next version.

**Comment by yury** [comment]
@sstoneju We have implemented basic support for Korean language. You can type words and delete backwards. But if you place cursor in other part of the row it will behave oddly. 
Sorry, I can’t find solution for that right now, we need help...
