### ISSUE TITLE
Default Key

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#91]
Per #79 and #36, it is difficult to understand the default key behavior. Currently, the user is required to create a key with the name "id_rsa", that the ssh convention establishes is marked as default and hence is the one always passed to the ssh client to try authentication. This process is unclear in the Blink case as keys are not inside a file system.

The proposal is to create by default, the first time the app is launched, an id_rsa without intervention of the user. This key will be marked as "default", and might be shown as such in the interface. The user is free to remove it and to create a new one with that naming. We can also offer the option to select multiple "default" keys that will always be tried when trying to log in to a server.

**Comment by goerz** [comment]
Just out of curiosity, what meaning do you assign to the 'icebox' label?

**Comment by carloscabanero** [comment]
Sorry, I was planning to drop this somewhere but didn't have time today. Icebox should be anything that needs some research or clarity before sending to development. 






On Tue, Aug 16, 2016 at 9:50 PM -0400, "Michael Goerz" <notifications@github.com> wrote:












Just out of curiosity, what meaning do you assign to the 'icebox' label?

**Comment by carloscabanero** [comment]
Done long ago :)
