### ISSUE TITLE
mosh disconnects in background and won't reconnect

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#910]
It seems to me that the last few TF versions have seen a regression in the way mosh works. In the past, closing the ipad for a while and then resuming had no issues with reestablishing a mosh session. Now, it's frequently the case that when the ipad is reopened after a delay (5-10 mins), the mosh client cannot reestablish its connection (bar on top saying "last contact X seconds ago"), requiring me to ssh into the server, do a `killall mosh-server`, and then reestablish a mosh connection (tmux is what's saving me here).

Currently on TF13.2(200).

**Comment by symbiont-wilfred-denton** [comment]
Yes this happens to me all the time on `v13.1.169` using a 12.9" iPad Pro (2018).

**Comment by yury** [comment]
@sbromberger is this still relevant? My mosh connections stay alive for a long time.

**Comment by sbromberger** [comment]
Nope. It looks like it's stable in the latest version. Thanks. Closing out.
