### ISSUE TITLE
Notch still Not handled on iPhone 11 Pro Max 

### ISSUE THREAD

**Issue by jimmyharris** [blinksh/blink#911]
Blink: v13.1.196. Dec 30 2019

Is my version

I’m running iOS 13.3

Sorry if this has been fixed I. Source already I can only use the AppStore release since I lack the hardware/software to build it myself.

**Comment by yury** [comment]
@jimmyharris try to set mode with 3f tap (fit/fill/cover)

See #386

**Comment by yury** [comment]
Ok, found issue with orientation detection. Will be better in next release.

Thank you.

**Comment by MwC-Trexx** [comment]
Issue appears on new iPhone 12 Pro on IOS 14.2 beta

**Comment by yury** [comment]
@MwC-Trexx 

I have added iPhone 12 models, but to make sure. Could you install Aida64 app from app store and send us Device -> Device Sting.

**Comment by MwC-Trexx** [comment]
Device String: iPhone13,3

[Paul Tisl - GMail - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=qsiop)	[qsiop]

On October 26, 2020 at 7:10 GMT, Yury Korolev <notifications@github.com> wrote:

[@MwC-Trexx](https://github.com/MwC-Trexx)

I have added iPhone 12 models, but to make sure. Could you install Aida64 app from app store and send us Device -> Device Sting.

**Comment by Tnuz** [comment]
Please fix notch for iPhone 13 series:
- iPhone14,2 : iPhone 13 Pro
- iPhone14,3 : iPhone 13 Pro Max
- iPhone14,4 : iPhone 13 Mini
- iPhone14,5 : iPhone 13
