### ISSUE TITLE
Can't change theme or font

### ISSUE THREAD

**Issue by Kamik423** [blinksh/blink#913]
On the iPhone 11 I can change the font setting oder theme setting, but the app does not adapt, even after force quitting.

**Comment by yury** [comment]
Hi @Kamik423, new appearance settings only apply to new terminals. So after you change settings, please open new shell with cmd+t or 2f tap. 
This is intentional behavior to speedup rendering and reflows.

**Comment by Kamik423** [comment]
When I force kill the app on iPhone, why does it not open a new shell?

Also this behavior should definitely be explained somewhere in that menu.

**Comment by yury** [comment]
We try to save state as much as possible. That is why you get your shell back. 

And I agree, we should clarify behavior for sure. We getting issues because of that and bad reviews too.
