### ISSUE TITLE
port forwarding (-L) using mosh

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#914]
Is there a way to port forward (`-L 8888:localhost:8888`) over a mosh session?

**Comment by yury** [comment]
Nope, mosh is doesn't support that yet :(

We may develop port forwarding via ssh bg process, to it will reconnect on lost connection.

**Comment by sbromberger** [comment]
Got it. Thank you.

**Comment by drewwells** [comment]
please re-open, port forwarding is useful feature to track
