### ISSUE TITLE
ssh fails without notice when (renamed) private key cannot be found

### ISSUE THREAD

**Issue by pro-sumer** [blinksh/blink#916]
On my iPad `ssh` immediately returned to the prompt for any host I tried, without any info.

After running `ssh -vvvvv` instead I discovered from the logging that Blink could not read my private key. Apparently I had renamed it in the _Keys_ settings, but not in the _Hosts_ settings.

Please show an error in the GUI when a private key cannot be read when executing `ssh`.

Additionally you might want to change the appearance of Key names in the host section: display it in red if it cannot be found? (Now it showed a no longer existing name in the same font/color as a valid key; only when I tapped on it I saw that it was actually set to _None_)

**Comment by carloscabanero** [comment]
This was already implemented as part of some iCloud sync changes.
