### ISSUE TITLE
Option to Disable Autocomplete Text Display

### ISSUE THREAD

**Issue by sonic6567** [blinksh/blink#918]
Enhancement Request

Provide a way to disable the displaying of the autocomplete text

For example, at the blink> prompt, start typing the letters ping and the display shows: ping - Send ICMP ECHO_REQUEST packets to network hosts. (with the non-typed portion being in a different color and disregarded by the system, of course)

I am rather ‘old school’ and I find stuff like this to be very distracting; I know what I want to type and what I expect to see as I type - having other letters displayed definitely has an impact on my speed and accuracy.

I appreciate the feature, and can see its uses. However, for an ‘old-school’ VI programmer with so much eye/muscle memory, it ends up being a huge distraction and hinderance.

**Comment by yury** [comment]
@sonic6567 

Thank you for your feedback. In next release you can disable repl hints with BLINK_REPL_HINTS env var.

```
echo “BLINK_REPL_HINTS=false” > .blink/profile
```

Be sure to restart the app.

**Comment by yury** [comment]
Closing this issue. Feel free to reopen if needed.

**Comment by sonic6567** [comment]
Hello,

Was this updated?  Why was it closed?

Thank you

Ben

**Comment by yury** [comment]
Yep, version with the fix is already in the App Store (v13.2.1). Update and set env var

**Comment by sonic6567** [comment]
Hello,

Wow.  that was fast, thank you.

I didn’t see #918 in the update notes (might have missed it)

How do I disable the autocomplete test display?

Thank you

Ben

**Comment by yury** [comment]
Hi @sonic6567. I posted instructions above. But I write again:

`echo "BLINK_REPL_HINTS=false" > .blink/profile

Be sure to restart the app.

**Comment by sonic6567** [comment]
Hello,

Oh, great.  Sorry - your email didn’t come through all the way (got cut off, I guess.) screenshot attached

I will give it a shot.  Thank you very much for getting this in place so fast.
Much appreciated.

Ben

**Comment by sonic6567** [comment]
Hello,

Tested this and it works great. Thank you; so much better!

Ben
