### ISSUE TITLE
Alt+[special character] (software keyboard) sends wrong keys

### ISSUE THREAD

**Issue by j-tai** [blinksh/blink#920]
Some Alt+[special character] combinations sends the wrong key. For example:

* `Alt+!` sends `ESC 1` instead of `ESC !`.
* `Alt+?` sends `ESC /` instead of `ESC ?`.
* `Alt+)` sends `ESC 0` instead of `ESC )`.
* etc.

**Comment by yury** [comment]
Hi @j-tai can you gist your `.blink/kb.json` file?

**Comment by j-tai** [comment]
I haven't modified any keyboard settings. I don't have a `kb.json` file in `.blink/`.

**Comment by yury** [comment]
Thank you.

**Comment by j-tai** [comment]
Fixed in version 13.2.
