### ISSUE TITLE
TF Build 204: "CapsLock -> Ctrl" mapping is partially broken

### ISSUE THREAD

**Issue by aofei** [blinksh/blink#921]
If this mapping is enabled, then pressing `CapsLock` is equivalent to pressing `CapsLock` and `Ctrl` one after the other. That is, two actions are triggered.

**Comment by yury** [comment]
Hi @aofei, can you post screenshot of CapsLock settings view?

We can't prevent CapsLock from changing input register (it changes in whole system). But we fix lowercase/uppercase ourselves when CapsLock is remapped in the blink.

**Comment by aofei** [comment]
![172592F9-D7AC-4001-9A98-2974D2D567E1](https://user-images.githubusercontent.com/5037285/72989846-07e1ab80-3e2a-11ea-8d76-b03b7128f27c.png)
![E56B9EE4-45D0-45EC-8BDD-694C48C48C43](https://user-images.githubusercontent.com/5037285/72989848-07e1ab80-3e2a-11ea-9d62-efee42cd4fec.png)

**Comment by yury** [comment]
So after `CapLock+L` if you type `hello` - you will get `HELLO`?
I can't reproduce this yet.

**Comment by aofei** [comment]
Yes.

Note that I upgraded to TF build 204 directly from the latest stable version without making any changes to the settings.

And, I just discovered another weird thing. After I overwrote the TF version with the latest stable version from the App Store, the problem still exists. It seems that the broken here is persisted.

**Comment by yury** [comment]
Can you try press `reset` button at the top right and set it again?

**Comment by aofei** [comment]
Have tried that too, didn't help.

Wait a moment, I'm backing up data now. I plan to reinstall Blink.

**Comment by yury** [comment]
before you reinstall. Can you gist your `.blink/kb.json` file?

**Comment by aofei** [comment]
The old `.blink/kb.json` file.

<details>
<summary><code>.blink/kb.json</code></summary>
<pre>
{
  "cursor" : {
    "shiftLoc" : 0,
    "controlLoc" : 0,
    "optionLoc" : 0,
    "keys" : [
      "91:1"
    ],
    "commandLoc" : 0,
    "action" : {
      "type" : "none"
    }
  },
  "option" : {
    "right" : {
      "code" : {
        "code" : "AltRight",
        "id" : "18:2",
        "key" : "Alt",
        "keyCode" : 18
      },
      "down" : "",
      "up" : "",
      "ignoreAccents" : true,
      "mod" : ""
    },
    "same" : true,
    "left" : {
      "code" : {
        "code" : "AltLeft",
        "id" : "18:1",
        "key" : "Alt",
        "keyCode" : 18
      },
      "down" : "",
      "up" : "",
      "ignoreAccents" : true,
      "mod" : ""
    }
  },
  "shortcuts" : [
    {
      "input" : "c",
      "action" : {
        "type" : "command",
        "value" : "clipboardCopy"
      },
      "modifiers" : 1048576
    },
    {
      "input" : "v",
      "action" : {
        "type" : "command",
        "value" : "clipboardPaste"
      },
      "modifiers" : 1048576
    },
    {
      "input" : "t",
      "action" : {
        "type" : "command",
        "value" : "windowNew"
      },
      "modifiers" : 1179648
    },
    {
      "input" : "w",
      "action" : {
        "type" : "command",
        "value" : "windowClose"
      },
      "modifiers" : 1179648
    },
    {
      "input" : "o",
      "action" : {
        "type" : "command",
        "value" : "windowFocusOther"
      },
      "modifiers" : 1048576
    },
    {
      "input" : "t",
      "action" : {
        "type" : "command",
        "value" : "tabNew"
      },
      "modifiers" : 1048576
    },
    {
      "input" : "w",
      "action" : {
        "type" : "command",
        "value" : "tabClose"
      },
      "modifiers" : 1048576
    },
    {
      "input" : "]",
      "action" : {
        "type" : "command",
        "value" : "tabNext"
      },
      "modifiers" : 1179648
    },
    {
      "input" : "UIKeyInputRightArrow",
      "action" : {
        "type" : "command",
        "value" : "tabNext"
      },
      "modifiers" : 1179648
    },
    {
      "input" : "[",
      "action" : {
        "type" : "command",
        "value" : "tabPrev"
      },
      "modifiers" : 1179648
    },
    {
      "input" : "UIKeyInputLeftArrow",
      "action" : {
        "type" : "command",
        "value" : "tabPrev"
      },
      "modifiers" : 1179648
    },
    {
      "input" : "o",
      "action" : {
        "type" : "command",
        "value" : "tabMoveToOtherWindow"
      },
      "modifiers" : 1179648
    },
    {
      "input" : "+",
      "action" : {
        "type" : "command",
        "value" : "zoomIn"
      },
      "modifiers" : 1048576
    },
    {
      "input" : "-",
      "action" : {
        "type" : "command",
        "value" : "zoomOut"
      },
      "modifiers" : 1048576
    },
    {
      "input" : "=",
      "action" : {
        "type" : "command",
        "value" : "zoomReset"
      },
      "modifiers" : 1048576
    },
    {
      "input" : ",",
      "action" : {
        "type" : "command",
        "value" : "configShow"
      },
      "modifiers" : 1048576
    }
  ],
  "fn" : {
    "shiftLoc" : 0,
    "controlLoc" : 0,
    "optionLoc" : 0,
    "keys" : [
      "91:1"
    ],
    "commandLoc" : 0,
    "action" : {
      "type" : "none"
    }
  },
  "capsLock" : {
    "code" : {
      "code" : "CapsLock",
      "id" : "20:0",
      "key" : "CapsLock",
      "keyCode" : 20
    },
    "down" : "",
    "up" : "",
    "ignoreAccents" : true,
    "mod" : "Control"
  },
  "shift" : {
    "right" : {
      "code" : {
        "code" : "ShiftRight",
        "id" : "16:2",
        "key" : "Shift",
        "keyCode" : 16
      },
      "down" : "",
      "up" : "",
      "ignoreAccents" : true,
      "mod" : "Shift"
    },
    "same" : true,
    "left" : {
      "code" : {
        "code" : "ShiftLeft",
        "id" : "16:1",
        "key" : "Shift",
        "keyCode" : 16
      },
      "down" : "",
      "up" : "",
      "ignoreAccents" : true,
      "mod" : "Shift"
    }
  },
  "command" : {
    "right" : {
      "code" : {
        "code" : "MetaRight",
        "id" : "93:0",
        "key" : "Meta",
        "keyCode" : 93
      },
      "down" : "",
      "up" : "",
      "ignoreAccents" : true,
      "mod" : ""
    },
    "same" : true,
    "left" : {
      "code" : {
        "code" : "MetaLeft",
        "id" : "91:1",
        "key" : "Meta",
        "keyCode" : 91
      },
      "down" : "",
      "up" : "",
      "ignoreAccents" : true,
      "mod" : ""
    }
  },
  "control" : {
    "right" : {
      "code" : {
        "code" : "ControlRight",
        "id" : "17:2",
        "key" : "Control",
        "keyCode" : 17
      },
      "down" : "",
      "up" : "",
      "ignoreAccents" : true,
      "mod" : "Control"
    },
    "same" : true,
    "left" : {
      "code" : {
        "code" : "ControlLeft",
        "id" : "17:1",
        "key" : "Control",
        "keyCode" : 17
      },
      "down" : "",
      "up" : "",
      "ignoreAccents" : true,
      "mod" : "Control"
    }
  }
}
</pre>
</details>

And I just reinstalled Blink, the problem still exists... 😣

**Comment by yury** [comment]
What kb do you use? What iOS version?

**Comment by aofei** [comment]
iPad Pro 12.9" + Smart Keyboard + iPadOS 13.3 (17C54)

**Comment by yury** [comment]
tested on two iPads - ok.

Can you screenshot you kb settings from Settings.app?

**Comment by aofei** [comment]
So, does this indicate that this isn't Blink's bug? Maybe something mysterious has changed in my iPadOS's underlying system? But I can't recall what I did, the only thing I remember is that I upgraded Blink.

**Comment by aofei** [comment]
Okay, wait a moment.

**Comment by yury** [comment]
Yep, found it. Shortcuts toggle :(

**Comment by yury** [comment]
Turn it on and everything will be ok. 
I will try to fix that today.

**Comment by aofei** [comment]
> Yep, found it. Shortcuts toggle :(

This helped! 🎉😄

**Comment by aofei** [comment]
But why? I haven't toggled it these days, it has been kept off and there have been no problems before.

**Comment by yury** [comment]
Long story short. Software kbs like GBoard doesn't send shift/caps presses, they just send uppercase letter or lowercase letter (see #901). So I have to detect software kb and pass letters unmodified.
This toggle somehow breaks kb type detection and blink thinks it is software kb.

(that toggle gives us a lot of headache)

**Comment by aofei** [comment]
Okay, so let me share the reason why I toggled it off before. When working with Slide Over, it will cause Blink's window height to change frequently, which will cause the Tmux window height to change with it, that's pretty annoying. But it seems now that I have no other choice but to leave it on.

Thanks (again) for your help! 😊

![D2886905-B89D-49F4-81B1-C0CCFB8A0296](https://user-images.githubusercontent.com/5037285/72996689-16ce5b00-3e36-11ea-9250-424bec913f94.png)
![C0DDBE72-1202-4135-ADF5-A0AFDD43C7CE](https://user-images.githubusercontent.com/5037285/72996684-1635c480-3e36-11ea-9caf-981676cef4ab.png)

**Comment by yury** [comment]
You can lock blink size with 3f tap and lock button. 
I will push fix to test flight today.

**Comment by yury** [comment]
Pushed v13.2.1 to review for public Test Flight.

**Comment by aofei** [comment]
TF Build 210 works even if I toggled the Shortcuts off. Good job! 👍

**Comment by aofei** [comment]
Problem resolved. Closing.
