### ISSUE TITLE
scp without key

### ISSUE THREAD

**Issue by ftoralesacosta** [blinksh/blink#923]
The servers I access require a password+OTP, and thus I cannot use keys to even ssh, let alone scp. Is there a way to use scp such that it prompts me for the password?

Alternatively, is it possible to scp from the remote server to the blink/iCloud folder?

Thanks!

**Comment by yury** [comment]
Sorry for late response.
It is fixed in Blink 14 and Blink 15. 

Closing, feel free to reopen if needed.

**Comment by ftoralesacosta** [comment]
Awesome! Thanks a bunch!
