### ISSUE TITLE
SSH unusable with MikroTik router

### ISSUE THREAD

**Issue by comfortablynick** [blinksh/blink#925]
I previously used the Termius app to ssh to my MikroTik router at home and at church. That app works fine, but I much prefer Blink and use that daily with my Linux servers. I am using 13.2.1 (210) from TestFlight.

I don't know how to troubleshoot this, but the MikroTik interface has tab completion which doesn't work, and the terminal doesn't scroll or page at all. If there's any diagnostic info I can provide please let me know.

**Comment by yury** [comment]
Hi @comfortablynick,

try to append `+t` to your login. 

See [instructions](https://wiki.mikrotik.com/wiki/Manual:Console_login_process) from mikrotik.

**Comment by comfortablynick** [comment]
Ha, that works! Thank you, I didn’t know about those instructions. For some reason it works on the Termius app without that trick, but it’s no big deal to set up the username as `sysman+t`.

Thanks again.
