### ISSUE TITLE
Add new font: JetBrains Mono

### ISSUE THREAD

**Issue by herrbischoff** [blinksh/blink#927]
I'd be happy if you'd consider adding the rather new JetBrains Mono font. It's a decent typeface gaining some popularity and is scheduled to become the default font for JetBrains IDE's (not that I'm a user of those).

The original files can be found here: https://www.jetbrains.com/lp/mono/

~~However, those somehow contain an annoying line spacing that does not work properly in terminal emulators. The NerdFont variant appears to solve this issue: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono~~

Update: the current official 1.0.2 version resolves this.

**Comment by yury** [comment]
Hmm, 13.2 includes JetBrains Mono already.

**Comment by yury** [comment]
Not sure what version we have. I will update to 1.0.2.

**Comment by herrbischoff** [comment]
In that case, maybe the Powerline patched ones are more interesting for hardcore shell users.

**Comment by herrbischoff** [comment]
Closing this issue since the new font version was committed in 7ab3cb92926888ca6cf161f5454345ff24cb4c4c in January already.
