### ISSUE TITLE
Have a default login name for all servers

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#93]
Most of the users have the same login name across all servers. The standard behavior is that the user's name at the host is also passed to the servers. Mimic that by providing a default and configurable user name.

**Comment by goerz** [comment]
Is this in addition to a (default) username that can be set for specific hosts in the upcoming Hosts configuration?

**Comment by carloscabanero** [comment]
Correct. We will have an app wide and a per host config :)

**Comment by carloscabanero** [comment]
- [ ] Add a new row on Settings at the end of the Connect section for Default User, showing the default user name from the "device" information, all lowercase.
http://stackoverflow.com/questions/8261961/better-way-to-get-the-users-name-from-device
- [ ] When tapping on it, go to another Settings section for user, with only one row with "User" - Edit box.
- [ ] Save the default user on BKDefaults.
- [ ] Use the default user for the connection when one is not specified.

**Comment by carloscabanero** [comment]
Done on v3

**Comment by iq6gGsk7** [comment]
This needs some care, default username doesn't appear when connecting to a host.

1. Set default username
2. Create a host without username set
3. Try connecting

blink> mosh myhost.net
Password for @myhost.net:
@myhost.net's password: 
Permission denied (publickey,password,keyboard-interactive).
Did not find remote IP address
blink> ssh myhost.net
Connected to 192.229.192.5
Password for @myhost.net:
@myhost.net's password: 
Permission denied (publickey,password,keyboard-interactive).

Blink: v3.021.6.63. Dec 23 2016

**Comment by iq6gGsk7** [comment]
@carloscabanero maybe my comment above went under the radar because this is labeled as closed...

**Comment by carloscabanero** [comment]
The feature was closed 24 days ago. Will handle this scenario as part of #211.
