### ISSUE TITLE
Support other browsers when opening links

### ISSUE THREAD

**Issue by ChaiTRex** [blinksh/blink#930]
If I run `echo https://google.com` and then highlight the URL, I can `Open google.com` in a context menu that appears. This opens in Safari. I'd strongly prefer to use Firefox instead.

Please allow, in settings, the choice of favorite browser, and open everything browser-related in that browser.

* [Demonstration video](https://youtu.be/aH-3cgvd4Qw)

---

Blink 13.2.1.210
iPadOS 13.3.1

**Comment by yury** [comment]
Hi @ChaiTRex,

We don’t have that setting in config UI. But you can set BROWSER env var. We support following values:

- brave
- firefox
- googlechrome
- opera
- safari
- yandexbrowser

```sh
echo “BROWSER=firefox” > .blink/profile
```

And restart blink

**Comment by ChaiTRex** [comment]
Thanks, that worked with one change (the quote marks made it into the file):

    echo BROWSER=firefox > .blink/profile
