### ISSUE TITLE
Change cursor on Insert mode vim

### ISSUE THREAD

**Issue by haininhhoang94** [blinksh/blink#931]
Hello there, so i want to ask if we can change the cursor in Insert mode vim to vertical line?

`let &t_SI.="\e[5 q" "SI = INSERT mode                                                                                 
 61 let &t_SR.="\e[4 q" "SR = REPLACE mode                                                                                
 62 let &t_EI.="\e[1 q" "EI = NORMAL mode (ELSE)  `

It works in iTerm but not in Blink

**Comment by yury** [comment]
It should work with ssh. Mosh doesn’t support that ;(

**Comment by yury** [comment]
![804CA2B4-3E5E-47C5-BEBC-28206B823CF2](https://user-images.githubusercontent.com/5250/73589637-c9af5080-44e9-11ea-9d8a-931641f3bc9c.png)

**Comment by haininhhoang94** [comment]
Thanks. Issues revolved nicely!
