### ISSUE TITLE
Does .ssh/config support LocalForward or DynamicForward options?

### ISSUE THREAD

**Issue by sofakng** [blinksh/blink#933]
Does the SSH configuration file (.ssh/config) support the LocalForward or DynamicForward options?

I'm trying to use DynamicForward and it doesn't appear to work.

There was also a question at the bottom of issue #142 indicating that LocalForward may not be supported either.

EDIT: Does Blink support dynamic forwarding at all?  It doesn't look like the -D option is supported.  If this is correct, can this feature be added?

**Comment by videoMonkey** [comment]
Does blink support the .ssh/config file? I can run `ssh -o “RemoteCommand=ls;bash” host` Where `host` is configured via blink config, but when I add 
```
Host host
  RemoteCommand ls; bash
```
To .ssh/config and run `ssh -v host` it says `unsupported Option: RemoteCommand`

Blink is super powerful, but really, really confusing to work with.

**Comment by yury** [comment]
Hi @videoMonkey.

We use libssh to parse config. You can check what is currently supported here https://gitlab.com/libssh/libssh-mirror/-/blob/master/src/config.c#L123 (not much...)

**Comment by jjo93sa** [comment]
@yury 

Thanks so much for blink shell, it's great.

The list of features supported by libssh seems to indicate both Match and ProxyJump are supported, but as per #970 I couldn't get this to work?

**Comment by videoMonkey** [comment]
@yury remote command is the same as startup command under the mosh settings? Or is this something that isn’t in the app store version?

**Comment by treuille** [comment]
I would love `LocalForward` in `.ssh/config` as well!

**Comment by yury** [comment]
In latest version you can add Local/Remove forward in `.ssh/config`

Closing this issue. Feel free to reopen if needed.
