### ISSUE TITLE
feature request: Add TextExpander touch functionality to the iOS app

### ISSUE THREAD

**Issue by aeses** [blinksh/blink#934]
Please add TextExpander touch functionality to the iOS app. 

TextExpander – Unlock Your Productivity
Easily insert text snippets in any application from a library of content created by you and your team.

https://textexpander.com/
https://smilesoftware.com/textexpander-ios/sdk
https://github.com/SmileSoftware/TextExpanderTouchSDK

Seems there is another request for same - https://github.com/blinksh/blink/issues/644#issue-387838857

**Comment by carloscabanero** [comment]
We support Snips which are more indicated for Blink and we can make into what we need. Please reopen as an Idea on Discussions and if it gets some traction, we can figure out what to do (maybe adding it as another source?)
