### ISSUE TITLE
Silly question, jailbreak advantage

### ISSUE THREAD

**Issue by adminy** [blinksh/blink#935]
I haven't looked deep into the code yet, but could you tell me if it's possible to execute binaries that are outside the sandbox? Or if I had to move them to the sandbox where to?

Or is that just not possible because there is a programming link to the binaries?

Thank you

**Comment by evanjs** [comment]
Was wondering this after seeing the news of the unc0ver jailbreak lately, and would love to see Blink working with both stock and jailbroken devices (and programs).
