### ISSUE TITLE
Can’t connect to home ubuntu server or digital ocean ubuntu.  New customer.  Help!

### ISSUE THREAD

**Issue by delthemale** [blinksh/blink#937]
Can anyone please give a detailed install and setup of virtual box ubuntu server connecting to blink and AWS and DigitalOcean setup.  PLEASE!!!!!!

**Comment by MindTooth** [comment]
I believe it to be out of the scope this project.

A good Google search would give you detailed articles on getting started.

DigitalOcean: https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-18-04

**Comment by javierdemartin** [comment]
I am closing this as we're working on basic/advanced docs and also for cloud providers so this is easy to understand. Until is made public on the website you can check out the progress [here](https://github.com/blinksh/blink/tree/raw/docs), the documentation for cloud providers will be available in the coming days.
