### ISSUE TITLE
Is there a book, or guide for blink?  Why are there NO YouTube vids for install and usage??

### ISSUE THREAD

**Issue by delthemale** [blinksh/blink#938]
I just paid 20 bucks for this product and all i see is a screen with blink on it.  Is there a detailed description of install and setup anywhere that us newbies can follow?  Why has this community no done any YouTube vids of install, config with different OS and platforms?  Help the newbs!!!!

**Comment by paulrouget** [comment]
https://www.blink.sh/

**Comment by delthemale** [comment]
> https://www.blink.sh/ < there’s a video there. Also, why do you need a video for? I find the app to be very straight forward. It’s a ssh client.

This is my first time using this app or any app to ssh.  I just need specific instructions on how to connect to ubuntu server going through virtualbox.  I can’t connect

**Comment by carloscabanero** [comment]
No worries. We will try to do better. Check this one out and let us know https://www.digitalocean.com/docs/droplets/how-to/connect-with-ssh/openssh/

**Comment by delthemale** [comment]
I think that’s the problem.  Everyone is just expected to automatically know what to do to connect, when that couldn’t be further from the truth.  Some of us are 17 year old students that have NO clue what we’re doing.  A owners manual that gives specific instructions on install and usage should be automatic.  At the very least, a series of YouTube vids from the developers and community that shows how to install, use and troubleshoot all known issues found on this forum should be available.  Neither is the case.  We’re just expected to automatically know how to use it.  Very unfair

**Comment by delthemale** [comment]
Dummy-proof install to AWS, DigitalOcean, Ubuntu server, Virtualbox, VMWare etc.  Step by step.  That’s not much to ask.  Could be done in pdf forms very quickly

**Comment by carloscabanero** [comment]
Fair enough. Let’s start with troubleshooting the issues you may have, and maybe even this thread could be the beginning of that guide.

**Comment by delthemale** [comment]
Indeed.  What are the settings needed for Virtualbox?  Pics would be helpful as well

**Comment by delthemale** [comment]
In other words, Nat, host only adapter etc.  Which one should i choose?  How to get the IP to use to connect?  How to generate keys and how to communicate with ubuntu server through vbox to apply keys?  And on

**Comment by delthemale** [comment]
How to connect iPad with blink to my ubuntu server to apply keys?

**Comment by delthemale** [comment]
I’m sure you professionals may think this is elementary but the average novice newcomer probably would be clueless

**Comment by carloscabanero** [comment]
Ok, so here is the thing. SSH is a standard protocol and we just implement the client side of it. The server side, which is your virtualbox and Ubuntu, belongs to those platforms. Most of your questions actually belong to that side. Although I agree at some point it may be interesting to provide some guidelines ourselves, at the moment that’s really out of the scope of what we do.

We are here to help, at every stage, even on those  parts that are not core to what Blink does. But please remember that no one here is entitled to anything and no one here was born knowing. We all can work on it together, and there isn’t a problem with that.

Here are a few links that may help you to ssh into a Ubuntu VM from a remote computer. Let me know if these ones help and where you are stuck next:
https://askubuntu.com/questions/131017/ssh-into-ubuntu-vm-remotely
https://m.youtube.com/watch?v=5BsShkcweIs

**Comment by delthemale** [comment]
Thanks soooo much for your help. It means a lot

**Comment by phi3nix** [comment]
I understand delthemale, I had issue setup blink too. I wrote saml manual how to start with Blink http://www.adminnotes.net/how-to-start-using-blink-shell-ios-app/
Luca

**Comment by andrius** [comment]
The discussion here is a great as a starting point — blink definitely needs a community, wiki and so on. Why not to do so, i.e. by creating gitter/telegram chat group with some website. The userbase is so different, ones do know systems a-z others just newbies in the world of SSH

**Comment by carloscabanero** [comment]
What would you say are great examples of communities that we could get inspiration from?

So full disclosure, a few months after launching Blink, I started to draft and got a professional writer to create a few articles for Blink. The idea was to help but also put a stance into what dev work on the iPad could look like. We got a few basic ones written and I think he did a great job. Now they may be a bit outdated but I think it could be easy to fix.

You can find them here: https://docs.google.com/document/d/1oOcLp9DYr8vrcMmup1I9xEDMWxdD9PuoIEUP-lYrQt8/edit?usp=sharing

I think they are great starting point for a guide too. We can make it as part of our GitHub or maybe in a separate blog? Let me now what you think and if they are useful.

**Comment by andrius** [comment]
@carloscabanero why not to use wiki right at GitHub and make a link on the main page (and either in the app description in the appstore etc)? Another option is to install it but that will require extra job to keep wiki mainained. And a gitter could be not so bad option for ongoing support (or a telegram group). Ideally that could be self-mainained by the community

**Comment by phi3nix** [comment]
@carloscabanero I like it. My biggest problem with Blink was just to start. I tired to use scp to copy public key. I was getting ssl errors. I troubleshoot for living, and I looked for documentation and there was nothing. This is great app, the best on the market. I think that you guys would have more beginner Linux user if the app have proper documentation. I can help.

**Comment by videoMonkey** [comment]
This ssh/mosh client is a lot different from other ones on the app store. It’s better, but I will admit that I, a reasonably experienced ssh user was a little confused when I first opened the app. I figured it out, but it wasn’t love at first site.

**Comment by javierdemartin** [comment]
We're currently working on shipping documentation for basic as well as advanced topics as you requested. I will ping you here once they're public. In the meantime you can see the Work In Progress [here](https://github.com/blinksh/blink/tree/raw/docs)

**Comment by javierdemartin** [comment]
Hey! [docs](https://blink.sh/docs/) are now live. Please feel free to check them out and suggest new changes or topics you'd like to see!

> https://blink.sh/docs/
