### ISSUE TITLE
CTRL+SPC for emacs not working.

### ISSUE THREAD

**Issue by Yannmm** [blinksh/blink#942]
Hi, I'm new to blink as well emacs.
Just learned the selection key combo: CTRL + SPC
However, it just switches input language of iOS.

So how can I use this magical key combo for emacs in blink?

Thanks, love this app.

**Comment by jerryabramson** [comment]
Disable alternate keyboard(s) (i.e. emoji) in iOS Settings.

If there is only one keyboard, CTRL-SPACE is passed to applications (i.e. blink)

**Comment by cctile** [comment]
@jerryabramson++ 

That said, would love to have a way to still have C-space without giving up my alternate keyboards.

**Comment by yury** [comment]
Fix is released with Blink 13.5.1

Add custom press with ctrl-space and assign it to ctrl-space
