### ISSUE TITLE
Segfault after multiple DNS lookups

### ISSUE THREAD

**Issue by nscaife** [blinksh/blink#945]
I ran across a problem today where after 13 repeated DNS queries using either `dig` or `nslookup`, I receive five `bus error` messages then `segmentation fault`.

I’m on an iPad Pro (12.9-inch) (3rd generation) with iPadOS 13.3.1.

To reproduce:

1. Close the entire app if open (swipe up on Blink in app launcher), then reopen Blink
2. Type `dig nolen.io` (domain irrelevant) and press return on official iPad keyboard
3. Press Up+Enter, repeat exactly twelve times
4. Subsequent runs will produce error, no other DNS queries will work without force closing Blink

Screenshot:

<img width="1366" alt="screenshot" src="https://user-images.githubusercontent.com/644072/74615979-6117c480-50e2-11ea-8814-3e93b8c2fa40.png">

**Comment by yury** [comment]
Ref holzschu/network_ios#9

**Comment by carloscabanero** [comment]
Done 17.3.0
