### ISSUE TITLE
Feature Request: traceroute

### ISSUE THREAD

**Issue by rrgeorge** [blinksh/blink#946]
I would like to request that traceroute be added to the blink pseudo-shell. It already provides some pretty amazing basic utilities, and i think traceroute is all that its missing.

**Comment by javierdemartin** [comment]
Traceroute and some other network analysis tools require root privileges and given the current sandbox limitations of iOS it's not possible.

More about this can be read on the [README](https://github.com/holzschu/ios_system#adding-more-commands) file of ios_system.

However, if possible we will implement in the future.

**Comment by vandalon** [comment]
Traceroute should not require root privileges, also please consider mtr :)
