### ISSUE TITLE
TF 13.3 (217) - delay when switching

### ISSUE THREAD

**Issue by sbromberger** [blinksh/blink#948]
Just started noticing - frequently, when I switch out of blink and then back, or when I select it from the icon, there's a 1-2 second delay before the terminal appears. Reboot of the ipad doesn't fix, and it doesn't happen with any other apps.

It also doesn't happen all the time. Is something timing out (like a cache holding the font or theme info) that is required before the window reappears?

**Comment by yury** [comment]
What font do you use?

**Comment by sbromberger** [comment]
A custom version of Source Code Pro with glyphs.

**Comment by sbromberger** [comment]
Just switched to Firacode (built-in) and it has the same issue.

**Comment by sbromberger** [comment]
I think I've figured out the problem. When switching back after a delay, a DNS request to `ocsp.apple.com` is made. If this site is inaccessible (or blocked), the delay occurs. Ensuring that the site is unblocked resolves the problem.
