### ISSUE TITLE
Feature request: support certificate authentication (ssh option CertificateFile)

### ISSUE THREAD

**Issue by tjim** [blinksh/blink#949]
I'd like to be able to use certificate authentication for ssh - where the server is configured to accept keys signed in a certificate from a second key. The ssh option CertificateFile is one way to specify this but this option is unsupported in blink.

The version of ssh-add does seem to support adding certificate files but the main ssh functionality does not seem to support it.

**Comment by 0xCMP** [comment]
I think this is a dupe of #653
