### ISSUE TITLE
Ranger File Browser

### ISSUE THREAD

**Issue by e2dubba** [blinksh/blink#95]
When I use ranger on the server, the app crashes. (In both ssh and mosh LAN and remote)

**Comment by yury** [comment]
You are doing something specific before crash?
Can't make it crash.
http://www.youtube.com/watch?v=WexTE75X38o

**Comment by e2dubba** [comment]
Well. This is embarrsing! I tried it again and my bug report is incorrect. It works just fine when I ssh/mosh into a machine on my LAN, but it still crashes for me when I ssh into my server. I had to build it from sources on my server. Let me rebuild it again on my server and see if that doesn't help it. But I wasn't doing anything specific, just browsing the file hierarchy.

**Comment by e2dubba** [comment]
Ranger also works for me when I mosh into my server. And it works with ssh. I think the issue may have been that I didn't have unicode set up well. But with unicode set up, it works perfectly. Apologies for the false trail.

**Comment by carloscabanero** [comment]
Ok, closing then :)
