### ISSUE TITLE
mosh disconnects frequently on iOS 13.4

### ISSUE THREAD

**Issue by sdotz** [blinksh/blink#950]
iPad Pro 12.9 and iOS 13.4 mosh repeatably disconnects after 60 seconds whether I switch apps or not. Oddly, SSH has no such issues even as I fly through the air on wack in-flight wifi.

After the 60 seconds I get the blue “Last contact..” message and have to close the session and start anew.

Any ways to debug this?

**Comment by yury** [comment]
What server do you use? Mac OS? Linux?

**Comment by sdotz** [comment]
Mac OS

**Comment by yury** [comment]
It is know issue on macOS. It can put machine to sleep. For ssh it keeps machine awake, but for other protocols not. When you mosh to machine, mosh runs ssh command first to get encryption key, so Mac will wake up for some time. 
Try to turn off auto sleep in system settings.

**Comment by sdotz** [comment]
Yup, that was it. Thank you.

In case it helps anyone else, I managed to change my sleep settings via command line using this:
https://gist.github.com/pwnsdx/2ae98341e7e5e64d32b734b871614915
