### ISSUE TITLE
Feature Request: Wake on LAN

### ISSUE THREAD

**Issue by rrgeorge** [blinksh/blink#951]
The ability to send the Wake on LAN magic packet to wake a host up.
Even better, if we can configure MOSH to send the WOL packet if the host stops responding.

**Comment by ickc** [comment]
The second behavior seems wrong.

**Comment by rrgeorge** [comment]
> The second behavior seems wrong.

That's probably true. That was just a passing thought because I was working on a machine that happen to be constantly going to sleep on me.

**Comment by dylancant** [comment]
wakeonlan would be a great feature

**Comment by tenderlove** [comment]
I would like this feature too, but I set up my host to wake on unicast activity (as outlined [here](https://unix.stackexchange.com/questions/421325/wake-on-lan-via-ssh).  Then mosh will wake the remote host up.

**Comment by pr1metine** [comment]
Hi Blink,
holzschu, the maintainer of [ios_system](https://github.com/holzschu/ios_system), has made the necessary changes for you to add "Wake on LAN". Please integrate these changes into the client.

**Comment by yury** [comment]
`wol` command will be in next release.
