### ISSUE TITLE
Blink fails without error (returns to `blink >`)

### ISSUE THREAD

**Issue by nsadeh** [blinksh/blink#956]
Hello - I bought Blink and am trying to run through https://medium.com/@TehBrofessor/ipad-pro-remote-station-part-1-55520445b2b6. I followed step-by-step but when I try to ssh into my domain I get first the boilerplate about unknown server, then when I trust the host key nothing happens - I just go back to `blink>`, not into the server. Subsequent ssh commands don't do anything but return to `blink>`.

**Comment by joshwbrick** [comment]
I am experiencing this exact same issue. Referenced issue doesn’t seem relevant here.

**Comment by alicehsiao** [comment]
Still experiencing the same issue. I can ssh into my local macbook, but cannot into my linux box.

**Comment by skynebula** [comment]
I have the same problem here too

**Comment by carloscabanero** [comment]
This was old SSH and does not apply anymore. Please reopen if necessary.
