### ISSUE TITLE
On screen keyboard doesn't go away when using Microsoft designer keyboard

### ISSUE THREAD

**Issue by farnasirim** [blinksh/blink#958]
It is necessary to focus on the terminal to be able to input text using the keyboard. Putting the on screen keyboard away takes away the focus (physical keyboard won't input anything), and refocusing on the terminal brings back the on screen keyboard.

**Comment by carloscabanero** [comment]
Hi @farnasirim! Thanks for your report. I’m sorry as this seems to be an isolated issue, but lets see if we can figure out what’s going on. Would you mind to respond to this questions, even if some of them sound a bit obvious?

1) By on-screen keyboard, we assume it is the full keyboard that is being displayed, or is it just Blink’s smart keys bar? 
2) Does this happen in Blink alone? Does this happen in other apps too?
3) Does it happen when you have the external display connected or just with the device?
4) Is it on iPadOS or iOS? What version are you running?
5) Have you tried with the Smart Keyboard for the iPad? Have you tried with any other keyboards other than the Microsoft Designer one?
6) Have you tried restarting the device? (You probably already have, but sometimes with this devices we forget that a reboot fixes software issues)

Thanks!

**Comment by farnasirim** [comment]
Hey @carloscabanero.
1. I mean the native iPadOS keyboard, be it the full, docked keyboard or the floating keyboard. They both stay.
2. Have seen it happen in another "terminal emulator" on my iPad, but works fine for example with JSLinux inside a browser window, so I assume it's probably not impossible?
3. Haven't tried this. Will update later.
4. iPadOS v 13.3.1 (17D50) - iPad Pro 11-inch
5. Haven't tried any other keyboards on my iPad. Given that I haven't found anyone else with quite the same problem, I'd blame the keyboard.
6. Won't help unfortunately.

**Comment by carloscabanero** [comment]
2. I meant if it happens in other apps, like notes or safari too, not necessarily another terminal emulator.

I think I can try to get the same keyboard as yours and see if it is really an issue with it. Can you send me the specific model? Thanks!

**Comment by farnasirim** [comment]
Hmm interesting, the osk doesn't go away in safari or google docs either?

If this is still of interest, the device is not mine (don't have the box) and there's not much written on the keyboard itself, but I'm pretty sure it's [this one](https://www.dell.com/en-ca/shop/accessories/apd/a8559273?gacd=9683780-3004-5761040-0-0&dgc=st&gclid=CjwKCAiAzJLzBRAZEiwAmZb0at038kuZdm9lQ7DLb_fuM5-ic-c-ZzPag2zZAl44Z7w2mGyBXqB-EBoCdfMQAvD_BwE&gclsrc=aw.ds).

**Comment by carloscabanero** [comment]
If it doesn’t go away on other apps, it may be an incompatibility with that keyboard on iOS. If you get the chance to try other bluetooth keyboards, we may be able to check if it is actually that one specifically and I can report it to Apple.

I’m afraid there isn’t much more we can do from our side. If it is ok with you, please close the issue.
