### ISSUE TITLE
Mosh with tmux erroneously have backscroll

### ISSUE THREAD

**Issue by ChaiTRex** [blinksh/blink#959]
When I'm running tmux inside of Mosh, I shouldn't be able to drag the terminal text down to see backscroll because both Mosh and tmux take total control over the screen and treat it as nonscrollable. Something has gone wrong if backscroll has been produced, and things inside Mosh and tmux are somehow able to produce backscroll.

This is not due to tmux accepting mouse events, as it doesn't correctly scroll back through, for example, a Bash session. Instead, the scrollback is inevitably some garbage snapshots of what was on the screen long ago.

This is annoying because if I accidentally drag my finger down when I'm trying to select some text, suddenly the actual contents of the Mosh screen are gone and I have to waste time scrolling down to get them back.

* [Example video of dragging the text down to see the backscroll](https://youtu.be/JPeTHTuN1Hg)

---

Blink shell 13.3.219
iPadOS 13.3.1

**Comment by yury** [comment]
Scroll inside tmux or vim or emacs works with 2f scroll.

**Comment by ChaiTRex** [comment]
I mean more that *one-finger scroll should do nothing* inside of Mosh or tmux. Instead, it brings up the remnants of useless former screen contents for some reason.

When I'm trying to use one finger to highlight text, it's annoying how often that the text on the screen disappears as it scrolls below as useless text replaces it.

**Comment by yury** [comment]
We released Blink v13.4 with a fix.

Closing this issue. Feel free to reopen if needed.
