### ISSUE TITLE
Long lines are getting extra newline chars when copy-pasting

### ISSUE THREAD

**Issue by toh-ableton** [blinksh/blink#961]
This is a regression of #125. Steps to reproduce are exactly as in the original bug:

#### Steps to reproduce:
1. Connect to a remote mac via ssh or mosh.
2. Enter
```
$ echo 111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
```
3. Copy the string of 1s that is echoed to the terminal
4. Enter
```
$ cat > /tmp/test.txt
```
5. Paste and enter Ctrl-D
6. Enter
```
$ wc -l /tmp/test.txt
```
#### Version
Blink: v13.3.219. Feb 12 2020

**Comment by cc12258** [comment]
This makes simple things like trying to copy and paste an ssh pub key which is a long single line impossible because Blink is splitting the key into many lines when going terminal to terminal. Please fix ASAP.

**Comment by dmitryzykov** [comment]
+1 for that issue.

**Comment by tomminux** [comment]
+1 please this fix ASAP. If using blink to do system administration this is actually a nightmare...

**Comment by yury** [comment]
Fix is released, feel free to reopen if needed.
