### ISSUE TITLE
Port forwarding stops when blink is running in the background

### ISSUE THREAD

**Issue by RalphFS** [blinksh/blink#964]
Port forwarding only seems to works for a few seconds when the app is running in the background. This seems to be mainly due to some limitations of iPadOS 13, but apparently there is some workaround (see below).

For example, if I run a jupyter notebook on port 9999 on a remote machine and then use the blink app to start a local port forwarding by typing "ssh -L 9999:localhost:9999 remoteHost", I can access the notebook locally in a browser on my iPad for about 30 seconds. After that iPadOS seems to pause /kill the blink app. Interestingly, the process continues as soon as I switch back to the Blink app, which then works again for a few seconds.

With the [termius app](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjFjNjXsq7oAhVJLewKHYxgAYoQFjAAegQIARAB&url=https%3A%2F%2Ftermius.com%2F&usg=AOvVaw0GQItTs65kIr1PbJt-j5bc) from the app store, however, port forwarding also works smoothly over a long time without any problems. 

So it seems to be possible to somehow continue running your app in the background. Could you please take a look at this. Port forwarding is one of the most important features for me and at the moment this is the only reason why I can't switch to blink completely. Thanks

**Comment by yury** [comment]
use `geo track` command. It will allow app to run longer in background.

**Comment by RalphFS** [comment]
thanks, that fixed the issue.
