### ISSUE TITLE
text selection not working

### ISSUE THREAD

**Issue by perelin** [blinksh/blink#965]
Hi, for whatever reason selecting text is no longer possible for me. Not sure but I think it came with the jump from the TestFlight version to the regular App Store version.

So, when I try to select any text with my finger on the blink screen, nothing happens. How can I start to debug this in a useful way?

Current version: 13.3.219 Feb 2020

**Comment by yury** [comment]
Hi @perelin. It is issue with iOS/iPadOS 13.4. We are working on it. We found solution, but we have to rewrite a lot.

**Comment by sbromberger** [comment]
This might seem obvious, but it also affects the ability to open URLs from within Blink.

**Comment by perelin** [comment]
Any way to support here? Testing or something?

**Comment by yury** [comment]
We will start push public betas next week, I think. Right now it is to raw for public testing.

**Comment by yury** [comment]
Ok, we a little bit behind the schedule. But I have good news!

iOS 13.4.5 beta fixes selection! (IME mode is still broken though)

**Comment by drewwells** [comment]
Is it safe to say that we should ask the blink team before upgrading our iPad/iOS versions?

**Comment by tomminux** [comment]
@yury any news on this? Public beta?

**Comment by yury** [comment]
@tomminux just pushed!

**Comment by sbromberger** [comment]
@yury you guys rock. Thanks very much for the fix. Being able to copy/paste again is fantastic!

**Comment by perelin** [comment]
Fix for text selection and copy/paste works great. Thanks!

I encountered some unrelated issue with the beta though (prompt rendering for https://starship.rs/ is broken). Should I report it here in detail, or open a new ticket?

**Comment by chriscameron** [comment]
When will you be updating the app store version?

**Comment by bora89** [comment]
Yes I am also wondering when will be updated the AppStore version?

**Comment by gravicle** [comment]
Is there a link to join the public beta? I am at gravicle [at] gmail.

**Comment by gravicle** [comment]
Can confirm text selection is back to working really well! 🙏

**Comment by wiremoons** [comment]
Hi

Any news or estimated timeline for the iOS app store version being made available please, to non beta testing users? 

I am missing not having any copy capabilities for the last few weeks, so looking forward to getting this basic functional back soon... :)   Thanks

**Comment by charlieegan3** [comment]
I'd also be interested in knowing when it's likely to land in the App Store. Is this the best place to ask for beta test flight access? ([rather than twitter](https://twitter.com/charlieegan3/status/1249247767278600193))

I'm apple.com [at] charlieegan3.com on testflight.

**Comment by VirtualWolf** [comment]
@charlieegan3 Looks like the update hit the App Store yesterday. 👍

**Comment by yury** [comment]
@wiremoons sorry not keeping you updated. We where in a hurry to fix that. There is no ETA, bc we where finding good way to workaround that issue. Not sure if we found best one, but have to rewrite a ton of input and layout code.
Again, sorry for delay. That was not easy fix.

I'm closing this issue since we pushed Blink v13.4 in App Store. Feel free to reopen if needed.
