### ISSUE TITLE
Stop terminal resize when keyboard toolbar appears from slide over app

### ISSUE THREAD

**Issue by willhbr** [blinksh/blink#967]
If you open an app in slide over and focus the keyboard in that app, the toolbar appears along the bottom of the screen, forcing Blink to shrink and re-draw. When Blink receives focus again, the toolbar disappears and the view expands and re-draws again. Is it possible to make the toolbar appear on top of blink (so that the bottom of the terminal is covered) to avoid this needless resize & re-draw? This is really frustrating when you're opening a messaging app in slide over while working in Blink. Here's a screenshot that hopefully makes this issue clearer:

![IMG_1257](https://user-images.githubusercontent.com/710254/77532673-6a6a2d00-6ee9-11ea-87ca-e3698df980d6.jpeg)

My cursor is focussed in Notes, and the toolbar has forced the bottom of my terminal (in this case, my tmux & vim status bars) to move upwards about 1cm.

**Comment by yury** [comment]
You can 3f tap on blink and press lock button at the bottom. This way blink would not resize its terminal.

**Comment by willhbr** [comment]
Thanks yury! 😄 quality of life dramatically improved
