### ISSUE TITLE
I’m not able to select text

### ISSUE THREAD

**Issue by albmtez** [blinksh/blink#973]
When I press into the screen with my finger or with the pencil text selection is not available anymore.

**Comment by bpottier** [comment]
I’m seeing this too. Latest version of iPadOS.

**Comment by willhbr** [comment]
See #965 - this is a known issue with iPadOS 13.4

**Comment by albmtez** [comment]
> See #965 - this is a known issue with iPadOS 13.4

Thanks willhbr. As there is already an issue on which they're working on, I close this one.
