### ISSUE TITLE
Feature Request: Keyboard shortcut to switch windows with external monitor plugged in.

### ISSUE THREAD

**Issue by b00giZm** [blinksh/blink#974]
Sometimes, I start using Blink on my iPad alone, but when I realize that I need some more screen real estate, I plug in my external monitor. Instead of logging out of my current session on the ipad window and log back into on the window at the external screen, I’d love to have a keyboard shortcut to “switch” the contents of the window on my iPad with the one of the external screen.

**Comment by yury** [comment]
`cmd+shift+o` moves current terminal to Other window

**Comment by b00giZm** [comment]
Awesome! Must have overseen that 👍
