### ISSUE TITLE
Mosh session on external screen hangs after iPad screen goes to sleep

### ISSUE THREAD

**Issue by b00giZm** [blinksh/blink#975]
## Description
With an external monitor plugged in, I’ve noticed that the session on the external screen hangs/is unresponsive, after the iPad screen goes to sleep and is woken up again.

## Steps to reproduce
- Connect external monitor
- Open mosh session on window on external screen
- Hit sleep/wake button
- Wake iPad
- CMD+O to window on external screen
- window is unresponsive (does also not react to `Ctrl-^ .`

## System
- iOS 13.4 (17E255)
- Blink v13.3.219

**Comment by kyelewis** [comment]
I'm having a similar issue on 17E255. 
@b00giZm did you connect your display after you opened Blink or before?

If I open Blink with display already connected, it is stuck on a white "Locked" screen and never recovers. 

If I open first and then connect a display, things work until I switch away to another app, and then switch back (after which the external screen is unresponsive as above)

Sometimes when re-opening, the iPad resprings.

**Comment by malbertus** [comment]
I have this same issue after switching applications from and back to Blink. The iPad session immediately picks up and is responsive, but the external monitor session is not responsive after a Cmd + o to switch to it.

As a workaround I found that creating and closing a new tab (Cmd + t followed by Cmd + w) reactivated the terminal.

**Comment by peppy** [comment]
This is still an issue. I can reproduce 100% of the time and makes blink nearly unusable on external displays.

Reproduction:

- Create session on external display (must be `mosh`, does not reproduce with `ssh`)
- Switch away from blink to another application
- Switch back
- Blink is now unresponsive, until creating a new tab and returning to the previous session

I'd classify this as a critical issue.

**Comment by carloscabanero** [comment]
This should now be fixed on latest TF. Let us know!

**Comment by peppy** [comment]
Can confirm this is fixed 👍
