### ISSUE TITLE
support for going one word back or forth through alt(option) + left/right

### ISSUE THREAD

**Issue by damex** [blinksh/blink#976]
hello,
  i just started using blink and see that there is no support for skipping words (go one word back/forth) using alt(option)+arrow keys (left/right) that let you on OSX terminal or on iOS safari/notes/reminders/mail/etc go one word back or forth.

  https://support.apple.com/en-gb/HT201236 says:

  Option–Left Arrow: Move the insertion point to the beginning of the previous word.
  Option–Right Arrow: Move the insertion point to the end of the next word.

  it is very useful for me on mac and since it is okay to add feature requests - is there a way this one could be added too?

  thank you

**Comment by yury** [comment]
Hi @damex, in config -> keyboard -> option -> set `AS MODIFIER` to `Esc`

**Comment by damex** [comment]
@yury  thank you, it fixes the issue.

is there a deletion could work the same way? like deleting one word at a time using alt (option) button + backspace.

maybe i need a separate issue to bring up for that issue?

**Comment by yury** [comment]
In blink shell or in other shell. In blink we could support that, but remote shells should handle that.

Feel free to open issue anyway, we will try to fix it.

**Comment by damex** [comment]
thank you
