### ISSUE TITLE
Mosh and DigitalOcean

### ISSUE THREAD

**Issue by akus85** [blinksh/blink#980]
I have created a ssh key with:
ssh-keygen -t rsa -b 4096 -C "blablabla"

if i try to run **mosh --verbose myhost** a receive this message "Did not find remote IP address"

with command **ssh -vvvvv myhost** obtain this output

`ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.6 (70600)
ssh_client_select_hostkeys: Order of wanted host keys: "ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss"
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
ssh_client_select_hostkeys: Algorithms found in known_hosts files: "ssh-ed25519"
ssh_client_select_hostkeys: Changing host key method to "ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss"
packet_send2: packet: wrote [type=20, len=980, padding_size=10, comp=969, payload=969]
ssh_send_kex: SSH_MSG_KEXINIT sent
ssh_packet_socket_callback: packet: read type 20 [len=1076,padding=6,comp=1069,payload=1069]
ssh_packet_process: Dispatching handler for packet type 20
ssh_kex_select_methods: Negotiated curve25519-sha256,ssh-ed25519,aes256-gcm@openssh.com,aes256-gcm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-256-etm@openssh.com,zlib@openssh.com,zlib@openssh.com,,
packet_send2: packet: wrote [type=30, len=44, padding_size=6, comp=37, payload=37]
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=188,padding=8,comp=179,payload=179]
ssh_packet_process: Dispatching handler for packet type 31
packet_send2: packet: wrote [type=21, len=12, padding_size=10, comp=1, payload=1]
crypt_set_algorithms2: Set output algorithm to aes256-gcm@openssh.com
crypt_set_algorithms2: Set HMAC output algorithm to aead-gcm
crypt_set_algorithms2: Set input algorithm to aes256-gcm@openssh.com
crypt_set_algorithms2: Set HMAC input algorithm to aead-gcm
ssh_init_rekey_state: Set rekey after 4294967296 blocks
ssh_init_rekey_state: Set rekey after 4294967296 blocks
ssh_packet_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: Processing 196 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
ssh_packet_newkeys: Signature verified and valid
ssh_packet_socket_callback: Processing 180 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 7 [len=160,padding=18,comp=141,payload=141]
ssh_packet_process: Dispatching handler for packet type 7
ssh_packet_ext_info: Received SSH_MSG_EXT_INFO
ssh_packet_ext_info: Follows 1 extensions
ssh_packet_ext_info: Extension: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
ssh_connect: current state : 7
blink: setting socket keepalive: 1
packet_send2: packet: wrote [type=5, len=32, padding_size=14, comp=17, payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_packet_socket_callback: packet: read type 6 [len=32,padding=14,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [type=50, len=48, padding_size=12, comp=35, payload=35]
ssh_packet_socket_callback: packet: read type 51 [len=32,padding=16,comp=15,payload=15]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
blink: using auth methods attempt: 1 of 5
blink: import key mykey2
ssh_pki_import_privkey_base64: Trying to decode privkey passphrase=false
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
packet_send2: packet: wrote [type=50, len=608, padding_size=11, comp=596, payload=596]
ssh_packet_socket_callback: packet: read type 51 [len=32,padding=16,comp=15,payload=15]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey
`

**Comment by yury** [comment]
Hi @akus85 how did you install mosh server on digital ocean? What user do you use to access DO?

can you run `ssh -G myhost` and make sure username is correct?

**Comment by akus85** [comment]
@yury yes it is correct

**Comment by yury** [comment]
@akus85 you generated key in blink or on remote machine and import it in blink?

**Comment by akus85** [comment]
@yury i generate my key in blink shell with command: `ssh-keygen -t rsa -b 4096 -C "blablabla"`

i try also in config-->key but obtain same message

**Comment by yury** [comment]
@akus85 how did you copy public key to server?

**Comment by akus85** [comment]
@yury  using command `cat .ssh/id_rsa.pub | pbcopy` , after in digitaocean.com copy my public key

**Comment by yury** [comment]
@akus85 I see that ssh command try to use `mykey2` not id_rsa

**Comment by akus85** [comment]
@yury yes i give this name from interface

**Comment by yury** [comment]
It seems that you have two different keys. id_rsa in file system and mykey2 in secure enclave.
Please try copy public key of mykey2 and install it on digital ocean machine.

**Comment by akus85** [comment]
@yury same error

i try, also, to import from clipboard in key interface and not working

**Comment by yury** [comment]
Hmm, just tried myself - everything is ok.

So what I did:

1. Created key in config -> keys (+) -> Create New. RSA/4096. with name `test`
2. Copied public key of it
3. In DO before creating new droplet, I added new ssh key (Pasted from clipboard).
4. Make sure that new key is selected with checkmark
5. Press `Create droplet`
6. After it is created. I added host (do) in config -> hosts. username root and select key (test).

after that I'm able to connect with `ssh do` command.

**Comment by akus85** [comment]
@yury ok thanks! i've create new droplet and now is ok!
Thank you for your time!

**Comment by yury** [comment]
Ok, closing this issue. Feel free to reopen if needed.

**Comment by mearleycf** [comment]
> Hmm, just tried myself - everything is ok.
> 
> So what I did:
> 
> 1. Created key in config -> keys (+) -> Create New. RSA/4096. with name `test`
> 2. Copied public key of it
> 3. In DO before creating new droplet, I added new ssh key (Pasted from clipboard).
> 4. Make sure that new key is selected with checkmark
> 5. Press `Create droplet`
> 6. After it is created. I added host (do) in config -> hosts. username root and select key (test).
> 
> after that I'm able to connect with `ssh do` command.

Just as a note, this worked for me as well, Feb 11 2021.

**Comment by carloscabanero** [comment]
Just as a note in case it helps, the authorized_keys file requires to end with a newline character by the SSH server. Sometimes when copying a public key there by hand we forget. And that may be why if you just let DigitalOcean generate the file, the same key will work for you.
