### ISSUE TITLE
[ios/ipados] Can’t select text and thus copy/paste text

### ISSUE THREAD

**Issue by ventz** [blinksh/blink#981]
Hi,

It seems that text select and in terms copy and paste is broken?

If you have an external keyboard it works, but without one there is no way to select text (and in terms copy/paste)

This is latest os on ios and ipados.

**Comment by willhbr** [comment]
See #965, this is a known issue.

**Comment by ventz** [comment]
@willhbr thanks!

**Comment by ventz** [comment]
@willhbr How do you get on the public beta channel?

**Comment by willhbr** [comment]
I'm not a contributor - I just follow the project

**Comment by yury** [comment]
Closing in favore #965.

Pushed our first public TF release with a fix.

**Comment by ventz** [comment]
@yury Thank you!
(Btw, how does one get on the beta channel?)

**Comment by yury** [comment]
email me (yury.korolev@gmail.com) your apple id
