### ISSUE TITLE
iPad Pro: Invalid Key, Clipboard content couldn’t be validated as a key

### ISSUE THREAD

**Issue by sc4224** [blinksh/blink#983]
Using the Blink Shell version 13.3 on the 2018 iPad Pro.

Tried generating a id_rsa key using the format:
`ssh-keygen -t rsa -b 4096 -C “your@email.com”`

Copied to clipboard using:
`cat ~/.ssh/id_rsa/id_rsa.pub | pbcopy`

Went to config > keys > + > Import from clipboard

Then I encountered this error:
Invalid Key, Clipboard content couldn’t be validated as a key

**Comment by jjo93sa** [comment]
I think you should be importing the private key, not the public key:
`cat ~/.ssh/id_rsa/id_rsa | pbcopy `

**Comment by sc4224** [comment]
thanks it all worked out.
