### ISSUE TITLE
Q: No external display shell, just mirror iPad there?

### ISSUE THREAD

**Issue by Boyeen** [blinksh/blink#984]
First, amazing project. I am blown away by the integration with mosh.

QUESTION: Is there a way to simply mirror the iPad shell when connected to an external monitor?
I know I can switch between the two shells but I just need a single ssh session on the iPad AND mirrored onto the external display (a projector in my case when teaching).

If this is NOT supported let me know and I will submit an enhancement request

**Comment by yury** [comment]
Hi @Boyeen. Thank you for kind words. 

In next version we will have toggle for mirror mode. See #837.

Closing this issue in favor of #837.
