### ISSUE TITLE
Config changes won’t save on new iPad

### ISSUE THREAD

**Issue by mikeal** [blinksh/blink#986]
I just got a new iPad Pro. My local hosts and keys were migrated by the regular iOS update process and then I also enabled iCloud sync.

However, none of it seems to actually be working in Blink. I can see the keys and hosts in `config` but none of those hosts seem to be configured in Blink. `ping` says it “cannot resolve host” and `mosh` says “Did not find remote IP address.”

I searched through the older issues and docs and can’t seem to find anything 🤷‍♂️

**Comment by mikeal** [comment]
I decided to just clear all the config settings and re-install the app.

The font is reset, so I know that it took, but now none of the config settings I set will keep either :( I try to even adjust the appearance and nothing sticks.

**Comment by jwhitley** [comment]
I’m seeing what may be the same problem. ssh/mosh/ping aren’t resolving LAN hosts, either explicit FQDN or via hosts setup in `config`, yet dig/nslookup resolve these hosts just fine. I verified that I’m not running 1.1.1.1 or similar. 🤔

**Comment by jwhitley** [comment]
Correction: on further digging, my issue follows #645 more closely, and was resolved by tweaking router IPv6 & dnsmasq configuration.

**Comment by mikeal** [comment]
Ya, my issue has to be config related, nothing sticks, I can’t even change the font.

I’ve deleted the app and all the local data multiple times and nothing seems to fix it.

**Comment by nicknisi** [comment]
I'm noticing the same problem with the font setting not being applied.

**Comment by yury** [comment]
@nicknisi font, theme settings are applied to new tabs only. We did that for performance reasons.

**Comment by nicknisi** [comment]
@yury Oops, you're right that does work. Thanks!

**Comment by mikeal** [comment]
Closing as this appears to be fixed on the new beta channel.
