### ISSUE TITLE
Since upgrading to iPadOS 13.4.1 I can’t type a space in the blink shell. 

### ISSUE THREAD

**Issue by djsavvy** [blinksh/blink#987]
I’m running Blink 13.3.219 (up-to-date from the App Store at the moment). Since I upgraded to iPadOS 13.4.1 (I think that’s the only change that occurred, but I’m not sure since I’m not a daily Blink user), I can’t type a space in the blink shell. Sometimes there is a blue border around the entire shell, but I can’t replicate it consistently. 

At one point I managed to use the up arrow to get back to a command to connect to a remote mosh server, but then I couldn’t type a space in vim either. Now I can’t seem to use the up arrow keys to get to previous commands either. 

I’m not really sure what’s going on. Any ideas?

**Comment by joshwbrick** [comment]
This exact same thing happened to me when I enabled

**Comment by joshwbrick** [comment]
The exact same thing happened to me. It is caused by enabling the ‘Full Keyboard Access’ setting in Settings > Accessibility > Keyboards > Hardware Keyboards.

It seems this feature is not compatible with blink.

![Uploading 79289392...]()

**Comment by yury** [comment]
Go to Settings.app -> Accessibility -> Keyboards -> Full Keyboard Access -> Commands and remap `Active` to SHIFT+space for instance, instead of just space
