### ISSUE TITLE
Allow custom key bindings to send key sequences

### ISSUE THREAD

**Issue by jwhitley** [blinksh/blink#991]
Perhaps related to the tmux key-configuration asks in #972, it would be great to be able to create custom key bindings which emit specified key sequences.  For example, in iTerm2, this is what the “Send Hex Codes” binding does.

Sample use case: I’d like to be able to set ⌘-1, ⌘-2, etc. to switch between tmux windows, which 99% of the time are effectively my “tabs”.  Specifically, that means emitting `<prefix>1`, `<prefix>2`, etc for these keys, where `<prefix>` is a key (default C-b, I use C-]) configured in the user’s .tmux.conf.

It’s possible to directly bind function keys in tmux, which is my current workaround, but they aren’t available for use by any applications running under tmux. Custom configuration like this in Blink would allow both a tmux window binding and an alternate function key binding to work like ⌘⌥-1, etc. as well as opening up numerous other convenience bindings.

**Comment by yury** [comment]
Yep, we internally designed keyboard to support that. We just need to find good UI for that.
