### ISSUE TITLE
ssh/mosh/bastian "quick" connect

### ISSUE THREAD

**Issue by fizzyade** [blinksh/blink#993]
This is something I've mentioed in the discord channel briefly, but I've just thought of an enhancement.

o <connection>

(I realise o is current set to an experimenal feature)

As far as I'm concerned, mosh connections should never go via the bastian, they don't/can't work - I don't know if it's been disabled yet, but it should be because setting the bastian breaks servers with mosh connections (or it did). 

it should attempt to connect directly via mosh if it's enabled, if not, then try direct connection to ssh.
if that fails, then attempt ssh connection via the bastian.

This means that with a single command, inside or outside my network I can connect in the most appropriate way to a server.

**Comment by carloscabanero** [comment]
Took a while to reply to this one, but we are tracking ways to improve mosh.

The SSH connection should work through the bastion to the final server, and as long as you have some type of access to the final server, mosh-server should be able to start. This is in cases where, for example, you may be in a VPN and give everyone access to the final nodes over a bastion.

I don't think we should decide what protocol to use from our side as that comes with different expectations, and adds a lot of "plumbing" that is not that useful.

Closing here, but please feel free to open an Idea on Discussions if anything else comes up.
