### ISSUE TITLE
Version 13.4: display problem

### ISSUE THREAD

**Issue by aofei** [blinksh/blink#997]
As you can see in the screenshot below, some lines disappeared due to the dynamic update of the [gotop](https://github.com/cjbassi/gotop) program in the right panel. It not only caused a display problem, but also caused all the content I entered in the same lines on the left panel to be hidden.

![023DAA69-3AFD-4577-9061-D58237309BF7](https://user-images.githubusercontent.com/5037285/80191787-cd65f580-8648-11ea-92b4-aaf21b14646c.jpeg)

**Comment by yury** [comment]
is it 100% reproducible? or it happens from time to time?

**Comment by aofei** [comment]
100%

**Comment by aofei** [comment]
In fact, IIRC, it has been a problem since TF Build 226. Sorry, I forgot to give you feedback earlier.

**Comment by yury** [comment]
mosh or ssh? can't repro yet

**Comment by aofei** [comment]
mosh + tmux

**Comment by aofei** [comment]
It may be related to the dynamic update of the `gotop` program in the right panel, because if I close it, the problem will be gone.

**Comment by yury** [comment]
![IMG_7E3909BE8D06-1](https://user-images.githubusercontent.com/5250/80192842-79471b00-8620-11ea-9f09-7275e1c21a52.j

**Comment by aofei** [comment]
> ![IMG_7E3909BE8D06-1](https://user-images.githubusercontent.com/5250/80192842-79471b00-8620-11ea-9f09-7275e1c21a52.j

Sorry, I can't see this pic.

```
AccessDeniedAccess Denied96E4447C34F1FD801ihNOnAWTlnWl2rfm/m8niEOmcdDV4DlbKOnv6TAV55HBkONg0DlNWcn3aJshi/tuXjqzJsS3pA=
```

**Comment by yury** [comment]
![IMG_7E3909BE8D06-1](https://user-images.githubusercontent.com/5250/80192954-a98eb980-8620-11ea-8420-ed9b1603db61.jpeg)

What version of tmux do you have?

**Comment by aofei** [comment]
tmux 3.0a + mosh 1.3.2

I'm using Arch Linux, so all my software should be up-to-date (I run `sudo pacman -Syu` every day).

**Comment by yury** [comment]
what font do you use? can you try Pragmata Pro?

**Comment by aofei** [comment]
Uhh... okay, it's caused by font, I'm using Source Code Pro. Pragmata Pro Mono has no problems.

**Comment by aofei** [comment]
Well, I just tried all the fonts and the following fonts are causing problems.

* Fira Code
* JetBrains Mono
* Roboto Mono
* Source Code Pro
* Menlo
* Courier
* Courier New

**Comment by waigx** [comment]
I see the same issue with my own patched Nerd Fonts.

**Comment by yury** [comment]
@aofei don't think it is blink update, it could be iOS update. 
There is no Braille glyphs in that fonts, and default substitution has very big line height.... Investigating...

**Comment by aofei** [comment]
I don't know, I updated version today, version 13.3 doesn't have this problem.

**Comment by yury** [comment]
Yep, you are right. It is contenteditable...

**Comment by yury** [comment]
@aofei I think I found the solution.

@waigx can you share your font, so I can take a look too

**Comment by waigx** [comment]
Thanks for the prompt reply! The font I've been using:
https://github.com/waigx/SFMonoNerd

**Comment by yury** [comment]
@waigx can you also provide setup for broken case?

**Comment by waigx** [comment]
The same as the original post. It broken with `bash`(3.2.57), `mosh`(1.3.2) and `gotop`(3.0.0):

![IMG_0281](https://user-images.githubusercontent.com/1830930/80217533-bf5ba900-8637-11ea-9b87-2ad25e447f35.PNG)

**Comment by yury** [comment]
Ok, fixed then. Pushing 13.4.1 to public TestFlight

**Comment by waigx** [comment]
Just confirmed the fix works good. Thanks

**Comment by aofei** [comment]
Closing due to the confirmed fix. Thanks~❤️
